// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/declareExtendsHelper ../../../request ../../../core/Accessor ../../../core/arrayUtils ../../../core/Error ../../../core/lang ../../../core/maybe ../../../core/now ../../../core/promiseUtils ../../../core/accessorSupport/decorators ./AsyncWorkerQueue ../webgl-engine/lib/Util ../../../views/support/Scheduler".split(" "),function(e,h,m,q,r,t,u,v,w,n,p,k,l,x,y,z){Object.defineProperty(h,"__esModule",{value:!0});e=function(e){function b(){var a=
null!==e&&e.apply(this,arguments)||this;a.tasks=new Map;a.doneQueue=[];a.updating=!1;return a}q(b,e);b.prototype.setup=function(a,c,b){var d=this;this.loadQueue=new x.AsyncWorkerQueue(function(a,c){return d.startLoading(a,c)},function(a,c){return d.doneLoadingCallback(a,c)},a,c);b&&(this.taskHandle=b.registerTask(z.Task.STREAM_DATA_LOADER,function(a){return d.update(a)},function(){return 0<d.doneQueue.length}))};b.prototype.destroy=function(){this.taskHandle&&(this.taskHandle.remove(),this.taskHandle=
null);this.tasks.forEach(function(a){a.abortController&&a.abortController.abort()});this.loadQueue.clear();this.tasks=this.doneQueue=this.loadQueue=null};Object.defineProperty(b.prototype,"busy",{get:function(){return this.loadQueue.busy},enumerable:!0,configurable:!0});b.prototype.request=function(a,c,b,d){var f=this,g=k.createResolver();g.__signal=n.isSome(d)?d.signal:null;var e=n.isSome(d)&&d.uid||a,h=this.createOrUpdateTask(a,c,b,e,g);k.onAbort(d,function(){return f.cancelRequest(h,g)});return g.promise};
b.prototype.createTask=function(a,c,b,d,f){a={url:a,docType:c,clientType:b,key:d,result:null,status:1,resourceRequest:null,abortController:null,resolvers:[],_cancelledInQueue:!1,startTime:0,duration:0,size:0};this.updateTask(a,f);this.tasks.set(d,a);1===this.tasks.size&&this._set("updating",!0);this.loadQueue.push(a);return a};b.prototype.cancelRequest=function(a,c){u.removeUnordered(a.resolvers,c);c.reject(k.createAbortError());0===a.resolvers.length&&(2===a.status&&(a.status=4,this.loadQueue.cancel(a),
a.abortController.abort(),a.resourceRequest=null,a.abortController=null),a.status=4,this.tasks.delete(a.key),0===this.tasks.size&&this._set("updating",!1))};b.prototype.taskKey=function(a,c,b){return a+":"+c+":"+b};b.prototype.updateTask=function(a,c){a.resolvers.push(c)};b.prototype.createOrUpdateTask=function(a,c,b,d,f){d=this.taskKey(d,c,b);var g=this.tasks.get(d);return g?(this.updateTask(g,f),g):this.createTask(a,c,b,d,f)};b.prototype.doneLoadingCallback=function(a,c){y.assert(2===a.status);
a.status=3;this.taskHandle?this.doneQueue.push({task:a,err:c}):this.doneLoading(a,c)};b.prototype.update=function(a){for(;!a.done&&0<this.doneQueue.length;){var c=this.doneQueue.shift();3!==c.task.status&&(c.err=c.err||k.createAbortError());this.doneLoading(c.task,c.err);a.madeProgress()}};b.prototype.doneLoading=function(a,c){for(var b=a.result instanceof HTMLImageElement?0:a.resolvers.length,d=0,f=a.resolvers;d<f.length;d++){var e=f[d];if(c)k.isAbortError(c)?e.reject(c):e.reject(new v("stream-data-loader:request-error",
"Failed to request resource at '"+a.url+"'. "+c,{url:a.url,error:c}));else{--b;var h=0>=b?a.result:w.clone(a.result);e.resolve(h)}}this.tasks.delete(a.key);0===this.tasks.size&&this._set("updating",!1)};b.prototype.startLoading=function(a,c){if(4===a.status)return!1;a.status=2;var b,d;switch(a.docType){case "binary":d="array-buffer";b=0;break;case "image":d="image";break;default:d="json"}a.startTime=p();a.abortController=k.createAbortController();a.resourceRequest=r(a.url,{responseType:d,timeout:b,
signal:a.abortController.signal});a.resourceRequest.then(function(b){a.duration=p()-a.startTime;a.size="binary"===a.docType?b.data.byteLength:0;a.result=b.data;a.abortController=null;c(a)},function(b){2===a.status&&c(a,b)});return!0};Object.defineProperty(b.prototype,"test",{get:function(){return{loadQueue:this.loadQueue}},enumerable:!0,configurable:!0});m([l.property({readOnly:!0})],b.prototype,"updating",void 0);return b=m([l.subclass("esri.views.3d.support.StreamDataLoader")],b)}(l.declared(t));
h.StreamDataLoader=e;h.default=e});