// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/tsSupport/generatorHelper ../../core/tsSupport/awaiterHelper ../../core/tsSupport/assignHelper ../../intl ../../request ../../Viewpoint ../../core/arrayUtils ../../core/Error ../../core/Handles ../../core/Loadable ../../core/promiseUtils ../../core/accessorSupport/decorators ../../geometry/Extent ../../tasks/PrintTask ../../tasks/support/fileFormat ../../tasks/support/layoutTemplate ../../tasks/support/PrintParameters ../../views/2d/viewpointUtils".split(" "),
function(C,D,n,d,p,q,r,e,t,u,v,g,w,x,h,c,y,k,l,m,z,A){function B(c){c.layoutOptions||(c.layoutOptions={});c.layoutOptions.customTextElements||(c.layoutOptions.customTextElements=[]);v.find(c.layoutOptions.customTextElements,function(b){return"date"in b})||c.layoutOptions.customTextElements.push({date:e.formatDate(Date.now(),e.convertDateFormatToIntlOptions("short-date"))})}return function(e){function b(a){a=e.call(this,a)||this;a._handles=new w;a._viewpoint=null;a.view=null;a.printServiceUrl=null;
a.updateDelay=1E3;a.templatesInfo=null;a.scaleEnabled=!1;a.error=null;a.print=a.print.bind(a);return a}n(b,e);b.prototype.destroy=function(){this._handles.destroy();this.view=this._handles=null};Object.defineProperty(b.prototype,"_printTask",{get:function(){return new k(this.printServiceUrl,{updateDelay:this.updateDelay})},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"state",{get:function(){return"loading"===this.loadStatus?"initializing":this.error||"failed"===this.loadStatus?
"error":this.get("view.ready")&&"loaded"===this.loadStatus?"ready":"disabled"},enumerable:!0,configurable:!0});b.prototype.load=function(a){this.addResolvingPromise(this._loadServiceDescription(a));return this.when()};b.prototype.print=function(a){var b;if(!this.view)return h.reject(new g("print:view-required","view is not set"));this.scaleEnabled?(this._viewpoint||(this._viewpoint=this.view.viewpoint.clone()),b=this._getExtent(this._viewpoint,a.outScale)):(this._viewpoint=null,b=this._getExtent(this.view.viewpoint));
B(a);a=new z({view:this.view,template:a,extent:b});return this._printTask.execute(a).catch(function(a){return h.reject(new g("print:export-error","An error occurred while exporting the web map.",{error:a}))})};b.prototype._loadServiceDescription=function(a){return q(this,void 0,void 0,function(){var b;return p(this,function(c){switch(c.label){case 0:return[4,this._getPrintTemplatesFromService(a)];case 1:return b=c.sent(),this._set("templatesInfo",b),[2]}})})};b.prototype._getPrintTemplatesFromService=
function(a){var b=this;return-1===this.printServiceUrl.toLowerCase().split("/").indexOf("gpserver")?(this.error=new g("print:invalid-print-service-url","Can't fetch print templates information from provided URL",{url:this.printServiceUrl}),h.reject(this.error)):t(this.printServiceUrl,r({},a,{query:{f:"json"},timeout:6E4})).then(function(a){a=a&&a.data;var c=null,d=null;(a&&a.parameters).forEach(function(a){var b=a.choiceList&&a.choiceList.slice(),f;b&&b.length&&a.defaultValue&&(f=b.indexOf(a.defaultValue));
-1<f&&(b.splice(f,1),b.unshift(a.defaultValue));if("Format"===a.name)c={defaultValue:l.fromJSON(a.defaultValue),choiceList:b.map(l.fromJSON)};else if("Layout_Template"===a.name){var b=b.filter(function(a){return"map_only"!==a.toLowerCase()}),e;f=void 0;b.some(function(a,b){a=a.toLowerCase();if(-1<a.indexOf("letter")&&-1<a.indexOf("landscape"))return e=b,!0;-1<a.indexOf("a4")&&-1<a.indexOf("landscape")&&(e=b);return!1});e&&(f=b[e],b.splice(e,1),b.unshift(f));d={defaultValue:m.fromJSON(b&&b[0]||a.defaultValue),
choiceList:b.map(m.fromJSON)}}});b.error=null;return{format:c,layout:d}}).catch(function(a){b.error=new g("print:unavailable-service-info","Can't fetch templates info from service",{error:a});throw b.error;})};b.prototype._getExtent=function(a,b){b=b||this.view.scale;var c=this.get("view.size");a=a?a.targetGeometry:null;return A.getExtent(new y,new u({scale:b,targetGeometry:a}),c)};d([c.property()],b.prototype,"view",void 0);d([c.property()],b.prototype,"printServiceUrl",void 0);d([c.property({dependsOn:["printServiceUrl"],
type:k})],b.prototype,"_printTask",null);d([c.property({dependsOn:["view.ready","error","loadStatus"],readOnly:!0})],b.prototype,"state",null);d([c.property()],b.prototype,"updateDelay",void 0);d([c.property({readOnly:!0})],b.prototype,"templatesInfo",void 0);d([c.property()],b.prototype,"scaleEnabled",void 0);d([c.property()],b.prototype,"error",void 0);return b=d([c.subclass("esri.widgets.Print.PrintViewModel")],b)}(c.declared(x))});