// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/generatorHelper ../../core/tsSupport/awaiterHelper ../../core/tsSupport/assignHelper ../../core/compilerUtils ../../core/maybe ../../core/promiseUtils ../../support/arcadeOnDemand ./previewCIMSymbol ./previewSymbol2D ./previewSymbol3D ./previewWebStyleSymbol ./utils".split(" "),function(C,p,D,E,F,G,v,H,I,J,K,L,M,w){function r(a,b){switch(a.type){case "web-style":return M.previewWebStyleSymbol(a,r,b);case "label-3d":case "line-3d":case "mesh-3d":case "point-3d":case "polygon-3d":return L.previewSymbol3D(a,
b);case "simple-marker":case "simple-line":case "simple-fill":case "picture-marker":case "picture-fill":case "text":return K.previewSymbol2D(a,b);case "cim":return J.previewCIMSymbol(a,b);default:G.neverReached(a)}}function z(a){return a&&"opacity"in a?a.opacity*z(a.parent):1}Object.defineProperty(p,"__esModule",{value:!0});var n=null;p.renderDotDensityPreviewHTML=function(a,b,c){var k=a.backgroundColor,d=a.outline;a=a.dotSize;var f=c&&c.swatchSize||22,m=Math.round(f*f/Math.pow(a,2)*.8),g=window.devicePixelRatio;
c=document.createElement("canvas");var h=f*g;c.width=h;c.height=h;c.style.width=c.width/g+"px";c.style.height=c.height/g+"px";var e=c.getContext("2d");k&&(e.fillStyle=k.toCss(!0),e.fillRect(0,0,h,h),e.fill());e.fillStyle=b.toCss(!0);if(n&&n.length/2===m)for(b=0;b<2*m;b+=2){var k=n[b],l=n[b+1];e.fillRect(k,l,a*g,a*g);e.fill()}else for(n=[],b=0;b<2*m;b+=2)k=Math.floor(Math.random()*(h-0+1)+0),l=Math.floor(Math.random()*(h-0+1)+0),n.push(k,l),e.fillRect(k,l,a*g,a*g),e.fill();d&&(d.color&&(e.strokeStyle=
d.color.toCss(!0)),e.lineWidth=d.width,e.strokeRect(0,0,h,h));d=new Image(f,f);d.src=c.toDataURL();return d};p.renderColorRampPreviewHTML=function(a,b){void 0===b&&(b={});var c="horizontal"===b.align,k=b.width,k=void 0===k?c?75:24:k,d=b.height,d=void 0===d?c?24:75:d;b=b.gradient;var f=void 0===b?!0:b;b=window.devicePixelRatio;var m=k*b,g=d*b;b=document.createElement("canvas");b.width=m;b.height=g;b.style.width=k+"px";b.style.height=d+"px";var h=b.getContext("2d"),e=c?m:0,l=c?0:g;if(f){var n=h.createLinearGradient(0,
0,e,l),p=1/(a.length-1);a.forEach(function(a,b){return n.addColorStop(b*p,a.toString())});h.fillStyle=n;h.fillRect(0,0,m,g)}else for(f=c?m/a.length:m,m=c?g:g/a.length,l=e=g=0;l<a.length;l++)h.fillStyle=a[l].toString(),h.fillRect(g,e,f,m),g=c?g+f:0,e=c?0:e+m;a=document.createElement("div");a.style.width=k+"px";a.style.height=d+"px";a.appendChild(b);return a};p.renderPreviewHTML=r;p.getDisplayedSymbol=function(a,b){return E(this,void 0,void 0,function(){var c,k,d,f,m,g,h,e,l,n,p,x,y,q,r,A,B,t;return D(this,
function(u){switch(u.label){case 0:if(!a)return[2,void 0];c=z(a.layer||a.sourceLayer);if(v.isSome(a.symbol))return k=a.symbol.clone(),w.applyColorToSymbol(k,null,c),[2,k];d=a.get("layer.renderer")||a.get("sourceLayer.renderer");return[4,d.getSymbolAsync(a)];case 1:f=u.sent();if(!f)return[2,void 0];f=f.clone();if(!("visualVariables"in d)||"visualVariables"in d&&!d.visualVariables||"visualVariables"in d&&d.visualVariables&&!d.visualVariables.length)return[2,f];if(!d.arcadeRequiredForVisualVariables||
!v.isNone(b)&&!v.isNone(b.arcade))return[3,3];g=m=F({},v.unwrap(b));return[4,I.loadArcade()];case 2:g.arcade=u.sent(),b=m,u.label=3;case 3:return[4,H.create(function(a){return C(["../../renderers/visualVariables/support/visualVariableUtils"],a)})];case 4:h=u.sent();e=[];l=[];n=[];p=[];x=0;for(y=d.visualVariables;x<y.length;x++)switch(q=y[x],q.type){case "color":e.push(q);break;case "opacity":l.push(q);break;case "rotation":p.push(q);break;case "size":n.push(q)}A=(r=!!e.length&&e[e.length-1])?h.getColor(r,
a,b):null;t=(B=!!l.length&&l[l.length-1])?h.getOpacity(B,a,b):null;null!=c&&(t=null!=t?t*c:c);w.applyColorToSymbol(f,A,t);n.forEach(function(c){return w.applySizeToSymbol(f,h.getSize(c,a,b),c.axis)});p.forEach(function(c){return w.applyRotationToSymbol(f,h.getRotationAngle(c,a,b),c.axis)});return[2,f]}})})}});