// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports @dojo/framework/shim/AbortController dojo/Deferred dojo/promise/all ./Error ./events ./maybe ./has ./clock @dojo/framework/shim/Promise".split(" "),function(K,c,H,t,I,z,A,n,k,J){function B(a){return k("esri-native-promise")?Promise.all(a):I(a)}function h(a,b){if(k("esri-native-promise"))return new Promise(a);var d=new t(b);try{a(function(a){return r(a).then(d.resolve)},d.reject)}catch(e){d.reject(e)}return d.promise}function l(a){void 0===a&&(a="Aborted");a=new z("AbortError",
a);a.dojoType="cancel";return a}function u(){return new H.default}function C(a){if(D(a))throw l();}function v(a){return n.isSome(a)?"aborted"in a?a:a.signal:a}function D(a){a=v(a);return n.isSome(a)&&a.aborted}function w(a,b){a=v(a);if(!n.isNone(a))if(a.aborted)b(l());else return A.once(a,"abort",function(){return b(l())})}function E(a){return a&&("AbortError"===a.name||"cancel"===a.dojoType)}function x(a){var b=null;a=h(function(a,e){b={resolve:a,reject:e}},a);b.promise=a;b.cancel=function(){b.reject(l())};
return b}function y(a){if(a){if("function"!==typeof a.forEach){var b=Object.keys(a),d=b.map(function(b){return a[b]});return y(d).then(function(a){var d={};b.forEach(function(b,e){return d[b]=a[e]});return d})}var e=null,c=p;return h(function(b,d){var f=[],q=a.length;0===q&&b(f);a.forEach(function(a){var g={promise:a||c(a)};f.push(g);g.promise.then(function(a){g.value=a}).catch(function(a){g.error=a}).then(function(){--q;0===q&&(e?d(l()):b(f))})})},function(b){e=b||"Invocation cancellation";a.forEach(function(a){"cancel"in
a&&a.cancel(b)})})}}function F(a){if(k("esri-native-promise"))return Promise.reject(a);var b=new t;b.reject(a);return b.promise}function p(a){void 0===a&&(a=void 0);if(k("esri-native-promise"))return Promise.resolve(a);var b=new t;b.resolve(a);return b.promise}function G(a,b,d){void 0===b&&(b=void 0);var e=u();w(d,function(){return e.abort()});return h(function(d){var c=setTimeout(function(){c=0;d(b)},a);w(e,function(){c&&(clearTimeout(c),F(l()))})},function(){return e.abort()})}function r(a){return a&&
"object"===typeof a&&"then"in a&&"function"===typeof a.then?a:p(a)}Object.defineProperty(c,"__esModule",{value:!0});k.add("esri-native-promise",!1);c.all=B;c.filter=function(a,b){var d=a.slice();return B(a.map(function(a,d){return b(a,d)})).then(function(a){return d.filter(function(b,d){return a[d]})})};c.create=h;c.createAbortError=l;c.createAbortController=u;c.throwIfAborted=C;c.isAborted=D;c.throwIfAbortError=function(a){if(E(a))throw a;};c.onAbort=w;c.onAbortOrThrow=function(a,b){a=v(a);if(!n.isNone(a))return C(a),
A.once(a,"abort",function(){return b(l())})};c.isAbortError=E;c.createDeferred=x;c.eachAlways=y;c.eachAlwaysValues=function(a){return y(a).then(function(a){return a.filter(function(a){return!!a.value}).map(function(a){return a.value})})};c.first=function(a){return a&&a.length?h(function(b,d){for(var c=0;c<a.length;c++)a[c].then(b,d)}):p()};c.reject=F;c.resolve=p;c.after=G;c.timeout=function(a,b,d,c){var e=d&&"abort"in d?d:null;null!=c||e||(c=d);var f=setTimeout(function(){f=0;e&&e.abort()},b),g=function(){throw c||
new z("promiseUtils:timeout","The wrapped promise did not resolve within "+b+" ms");};return a.then(function(a){if(0===f)throw g();clearTimeout(f);return a},function(a){clearTimeout(f);throw 0===f?g():a;})};c.wrapCallback=function(a){var b=!1;return h(function(){a(function(a){b||p(a)})},function(){return b=!0})};c.isPromiseLike=function(a){return a&&"function"===typeof a.then};c.when=r;c.debounce=function(a,b){void 0===b&&(b=-1);var c,e,q,f,g=null,h=function(){for(var d=[],m=0;m<arguments.length;m++)d[m]=
arguments[m];if(c)return e=d,f&&f.reject(l()),f=x(),d=f.promise,g&&(m=g,g=null,m.abort()),d;q=f||x();f=null;if(0<b){var k=u(),p=c=r(a.apply(void 0,d.concat([k.signal])));G(b).then(function(){c===p&&(f?k.abort():g=k)})}else c=1,c=r(a.apply(void 0,d));var d=function(){var a=e;e=q=c=g=null;null!=a&&h.apply(void 0,a)},m=c,n=q;m.then(d,d);m.then(n.resolve,n.reject);return n.promise};return h};c.createResolver=function(a){var b,c;a=h(function(a,d){b=a;c=d},a);var e=function(a){b(a)};e.resolve=function(a){return b(a)};
e.reject=function(a){return c(a)};e.timeout=function(a,b){return J.default.setTimeout(function(){return e.reject(b)},a)};e.promise=a;return e};c.always=function(a,b){return a.then(b,b)}});