// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/declareExtendsHelper ../../../../../core/tsSupport/decorateHelper ../../../../../core/tsSupport/assignHelper ../../../../../core/tsSupport/generatorHelper ../../../../../core/tsSupport/awaiterHelper ../../../../../core/Error ../../../../../core/has ../../../../../core/Logger ../../../../../core/MapPool ../../../../../core/maybe ../../../../../core/promiseUtils ../../../../../core/accessorSupport/decorators ../../../../../geometry/SpatialReference ../../../../../layers/support/LabelClass ../../../../../layers/support/labelFormatUtils ../../../../../renderers/support/jsonUtils ../../../engine ../../../arcade/utils ../../../engine/webgl/util/symbolUtils ../../../engine/webgl/util/vvFlagUtils ./BaseProcessor".split(" "),
function(w,x,D,l,U,n,t,ea,fa,V,y,M,m,h,N,W,X,Y,u,Z,aa,ba,ca){Object.defineProperty(x,"__esModule",{value:!0});var da=V.getLogger("esri.views.2d.layers.features.processors.SymbolProcessor");w=function(z){function b(){var c=null!==z&&z.apply(this,arguments)||this;c._symbolToMosaicItemMap=new Map;c._visualSetPromises=new Map;c.type="symbol";return c}D(b,z);b.prototype.initialize=function(){this._factory=this._createFactory()};b.prototype.destroy=function(){this._visualSetPromises.clear();this._symbolToMosaicItemMap.clear();
this.notifyChange("updating")};Object.defineProperty(b.prototype,"supportsTileUpdates",{get:function(){return!0},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"labelingInfo",{get:function(){return!this.config||M.isNone(this.config.labelingInfo)?null:this.config.labelingInfo.map(function(c){return W.fromJSON(c)})},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"labelClassInfos",{get:function(){var c=this;return this.labelingInfo?m.all(this.labelingInfo.map(function(a,
b){return t(c,void 0,void 0,function(){var c;return n(this,function(e){switch(e.label){case 0:return c={index:b,minScale:a.minScale,maxScale:a.maxScale},[4,X.createLabelFunction(a,this.service.fields,this.spatialReference)];case 1:return[2,(c.builder=e.sent(),c.symbol=a.symbol,c)]}})})})):m.resolve()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"hydrate",{get:function(){return Z.createHydrateFactory(this.service.geometryType)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,
"renderer",{get:function(){return this.config?Y.fromJSON(this.config.renderer):null},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"updating",{get:function(){return 0<this._visualSetPromises.size},enumerable:!0,configurable:!0});b.prototype.update=function(c){return t(this,void 0,void 0,function(){var a;return n(this,function(b){a=this._getMeshHash();this._set("config",c);a!==this._getMeshHash()?this._factory=this._createFactory():this._factory.update(this.labelingInfo,this.renderer,
this.tileStore.tileScheme.tileInfo);return[2]})})};b.prototype.onTileData=function(c,a,b){var d=this,e=a.addOrUpdate,p=a.remove,q=a.clear;a=e&&e.length?this._processFeatures(c,e,a.transformParams):m.resolve();var k=b.signal;a=a.then(function(a){return d.remoteClient.invoke("tileRenderer.onTileData",{tileKey:c.id,data:{addOrUpdate:a&&a.message||null,remove:p,clear:q}},{transferList:a&&a.transferList||null,signal:k})}).catch(function(a){return d._handleError(c,a,b)});this._visualSetPromises.set(c,a);
m.always(a,function(){return d._cleanPromise(c)});this.notifyChange("updating");return a};b.prototype.onTileError=function(c,a,b){var d=this;a=this.remoteClient.invoke("tileRenderer.onTileError",{tileKey:c.id,error:a},{signal:b.signal});this._visualSetPromises.set(c,a);m.always(a,function(){return d._cleanPromise(c)});this.notifyChange("updating");return a};b.prototype._getMeshHash=function(){var c=ba.getVVFlags("visualVariables"in this.renderer&&this.renderer.visualVariables||[]);return this.renderer.getMeshHash()+
"."+c};b.prototype._createFactory=function(){var c=this,a=this.service,b=a.geometryType,d=a.objectIdField,a=a.fields,e=N.fromJSON(this.spatialReference),a={geometryType:b,fields:a,spatialReference:e},e=new u.WGLTemplateStore(function(a,b){return c.remoteClient.invoke("tileRenderer.getMaterialItems",a,b)},!1),g=this.tileStore.tileScheme.tileInfo;this._matcher=u.createMatcher(this.renderer,e,a);return new u.WGLMeshFactory(b,d,this.renderer,e,this.labelingInfo,g)};b.prototype._cleanPromise=function(c){this._visualSetPromises.delete(c);
this.notifyChange("updating")};b.prototype._processFeatures=function(c,a,b){var d=this;if(!a||!a.length)return m.resolve(null);var e=this._factory,g={viewingMode:"",scale:c.scale};return this._matcher.then(function(c){return e.analyze(a,!1,c,b,g)}).then(function(a){return d._getLabelMosaicItems(c,a,b).then(function(g){return d._writeFeatures(c,a,b,g,e)})})};b.prototype._writeFeatures=function(c,a,b,d,e){for(var g=e.createMeshData(a.length),p={viewingMode:"",scale:c.scale},k=this._symbolToMosaicItemMap,
f=0;f<a.length;f++){var r=a[f];try{e.write(g,r,b,p,c.level,d,k)}catch(ga){}}return this._encodeDisplayData(g)};b.prototype._encodeDisplayData=function(c){var a={},b=[];c.encode(a,b);return{message:a,transferList:b}};b.prototype._handleError=function(b,a,p){p=p.signal;if(!m.isAbortError(a))return this.remoteClient.invoke("tileRenderer.onTileError",{tileKey:b.id,error:a.message},{signal:p})};b.prototype._getLabelMosaicItems=function(b,a,p){return t(this,void 0,void 0,function(){var c,e,g,q,k,f;return n(this,
function(d){switch(d.label){case 0:return c=y.acquire(),[4,this._createLabelFeatures(b.scale,a,c,p)];case 1:e=d.sent();g=this._symbolToMosaicItemMap;q=y.acquire();k=[];f=0;c.forEach(function(a,b){if(g.has(b.id)){var c=g.get(b.id).glyphMosaicItems,e=[];a.forEach(function(a){if(c&&c.length<a||!c[a])e[a]=a});0<e.length&&(q.set(f,b),k.push({symbol:b.toJSON(),id:f,glyphIds:e}),f++)}else{q.set(f,b);var d=[];a.forEach(function(a){return d.push(a)});k.push({symbol:b.toJSON(),id:f,glyphIds:d});f++}});if(0<
k.length)return[2,this.remoteClient.invoke("tileRenderer.getMaterialItems",k).then(function(a){for(var b=0;b<a.length;b++){var c=a[b],d=q.get(c.id);if(d)if(aa.isTextSymbol(d))if(g.has(d.id)){if(d=g.get(d.id).glyphMosaicItems,c=c.mosaicItem.glyphMosaicItems)for(var f=0;f<c.length;f++)null!=c[f]&&(d[f]=c[f])}else g.set(d.id,c.mosaicItem);else g.set(d.id,c.mosaicItem)}y.release(q);return e})];y.release(c);return[2,m.resolve(e)]}})})};b.prototype._getLabelClassInfosForScale=function(b){return t(this,
void 0,void 0,function(){var a;return n(this,function(c){switch(c.label){case 0:return[4,this.labelClassInfos];case 1:return a=c.sent(),[2,a.filter(function(a){var c=a.minScale;a=a.maxScale;return(!c||c>=b||0===c)&&(!a||a<=b||0===a)})]}})})};b.prototype._createLabelFeatures=function(b,a,p,d){return t(this,void 0,void 0,function(){var c,g,q,k,f,r,h,l,m,t,z,E,F,B,C,w,x,O,G,P,Q,R,H,S,v,I,J,K,T;return n(this,function(e){switch(e.label){case 0:return this.labelingInfo&&a&&0!==a.length?[4,this._getLabelClassInfosForScale(b)]:
[2,null];case 1:c=e.sent();if(0===c.length)return[2,null];g=y.acquire();q=new u.CollisionGrid(u.definitions.COLLISION_EARLY_REJECT_BUCKET_SIZE);k=0;for(f=a;k<f.length;k++){r=f[k];h=this.service.geometryType;m=l=0;if("esriGeometryPoint"===h||"esriGeometryPolygon"===h)if("esriGeometryPoint"===h?(t=r.geometry,l=t.x,m=t.y):(l=r.centroid.x,m=r.centroid.y),z=q.checkOverlap(l,m))continue;E=r.localId;F=[];for(B=0;B<c.length;B++){C=c[B];w=C.index;x=C.builder;O=C.symbol;G=r;if(!d)return da.error("mapview-labeling",
"Tried to evaluate geometry expression but no transformation found"),[2,void 0];P=d.transform;Q=d.hasZ;R=d.hasM;H=this.hydrate(r.geometry,P,Q,R);S=U({},r,{geometry:H});H.spatialReference=N.fromJSON(this.spatialReference);G=S;v=x.evaluate(G);if(!M.isNone(v)&&""!==v){u.definitions.DEBUG_LABELS&&(I="-"+E,v=v.substring(0,v.length-I.length)+I);J=u.bidiText(v);K=J[0];T=J[1];var n=O;e=K;var A=p;A.has(n)||A.set(n,new Set);for(var n=A.get(n),A=e.length,L=0;L<A;L++){var D=e.charCodeAt(L);n.add(D)}F.push({text:K,
rtl:T,id:w})}}g.set(E,F)}return[2,g]}})})};l([h.property({readOnly:!0})],b.prototype,"supportsTileUpdates",null);l([h.property()],b.prototype,"config",void 0);l([h.property({dependsOn:["config"]})],b.prototype,"labelingInfo",null);l([h.property({dependsOn:["labelingInfo","service","spatialReference"]})],b.prototype,"labelClassInfos",null);l([h.property({dependsOn:["service"]})],b.prototype,"hydrate",null);l([h.property({dependsOn:["config"],readOnly:!0})],b.prototype,"renderer",null);l([h.property({readOnly:!0})],
b.prototype,"updating",null);return b=l([h.subclass("esri.views.2d.layers.features.processors.SymbolProcessor")],b)}(h.declared(ca.default));x.default=w});