// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/assignHelper ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/awaiterHelper ../../../core/tsSupport/generatorHelper ../../../Color ../../../request ../../../symbols ../../../core/Accessor ../../../core/arrayUtils ../../../core/Collection ../../../core/Handles ../../../core/Logger ../../../core/maybe ../../../core/promiseUtils ../../../core/urlUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators ../../../layers/support/ExportImageParameters ../../../layers/support/fieldUtils ../../../renderers/support/jsonUtils ../../../renderers/visualVariables/SizeVariable ../../../symbols/support/symbolUtils ../../../symbols/support/utils ../../../views/2d/layers/support/clusterUtils ./colorRampUtils ./heatmapRampUtils ./relationshipRampUtils ./sizeRampUtils ./utils @dojo/framework/shim/Promise".split(" "),
function(da,va,K,ea,k,p,u,W,fa,L,ga,ha,ia,ja,ka,N,v,X,y,n,la,ma,na,oa,A,pa,qa,z,ra,Y,G,sa){function H(l){return"esri.renderers.SimpleRenderer"===l.declaredClass}function I(l){return"esri.renderers.ClassBreaksRenderer"===l.declaredClass}function P(l){return"esri.renderers.UniqueValueRenderer"===l.declaredClass}function Z(l){return"esri.renderers.HeatmapRenderer"===l.declaredClass}function B(l){return"esri.renderers.PointCloudClassBreaksRenderer"===l.declaredClass}function C(l){return"esri.renderers.PointCloudStretchRenderer"===
l.declaredClass}function J(l){return"esri.renderers.PointCloudUniqueValueRenderer"===l.declaredClass}var r=ka.getLogger("esri.widgets.Legend.support.ActiveLayerInfo"),aa=/^\s*(return\s+)?\$view\.scale\s*(;)?\s*$/i,D=new L.SimpleMarkerSymbol({size:6,outline:{color:[128,128,128,.5],width:.5}}),ta=new L.SimpleFillSymbol({style:"solid"}),ua=new L.SimpleMarkerSymbol({style:"path",path:"M10,5 L5,0 0,5 M5,0 L5,15",size:15,outline:{width:1,color:[85,85,85,1]}});return function(l){function f(a){a=l.call(this,
a)||this;a._handles=new ja;a._hasColorRamp=!1;a._hasOpacityRamp=!1;a._hasSizeRamp=!1;a._legendResponse={};a._webStyleSymbolCache=new Map;a._dotDensityUrlCache=new Map;a.children=new ia;a.layer=null;a.legendElements=[];a.parent=null;a.scale=null;a.title=null;a.view=null;return a}ea(f,l);f.prototype.initialize=function(){var a=this,b=function(){return a.notifyChange("ready")};this._handles.add([y.on(this,"children","change",function(c){var d=c.removed,e=a._handles;c.added.map(function(a){var c="activeLayerInfo-ready-watcher-"+
a.layer.uid;e.add(y.init(a,"ready",b),c)});d.forEach(function(a){return e.remove(a.layer.uid)});b()})])};f.prototype.destroy=function(){this._handles.destroy();this._dotDensityUrlCache=this._webStyleSymbolCache=this._legendResponse=this._handles=null};Object.defineProperty(f.prototype,"ready",{get:function(){return null===this.layer?!0:0<this.children.length?this._isGroupActive():0<this.legendElements.length},enumerable:!0,configurable:!0});Object.defineProperty(f.prototype,"isScaleDriven",{get:function(){var a=
this,b=this.layer;if(null===b)return!1;if("featureReduction"in b&&b.featureReduction&&"cluster"===b.featureReduction.type)return!0;if("renderer"in b&&b.renderer){if("dot-density"===b.renderer.type)return!0;var c=b.get("renderer.valueExpression");return aa.test(c)?!0:(b=b.get("renderer.visualVariables"))&&b.some(function(b){return a._isScaleDrivenSizeVariable(b)})}return!0},enumerable:!0,configurable:!0});Object.defineProperty(f.prototype,"version",{get:function(){return this._get("version")+1},enumerable:!0,
configurable:!0});f.prototype.buildLegendElementsForFeatureCollections=function(a){return p(this,void 0,void 0,function(){var b,c=this;return u(this,function(d){this.legendElements=[];b=a.map(function(a){if("esri.layers.FeatureLayer"===a.declaredClass)return c._buildRendererLegendElements(a.renderer,a.title,"append");if(a.featureSet&&a.featureSet.features.length){var b=a.layerDefinition,b=(b=b&&b.drawingInfo)&&na.fromJSON(b.renderer);return b?c._buildRendererLegendElements(b,a.name,"append"):(r.warn("drawingInfo not available!"),
null)}return null});return[2,v.eachAlways(b).then(function(){})]})})};f.prototype.buildLegendElementsForRenderer=function(a){return p(this,void 0,void 0,function(){return u(this,function(b){return[2,this._buildRendererLegendElements(a,null,"replace")]})})};f.prototype.buildLegendElementsForTools=function(){return p(this,void 0,void 0,function(){var a,b=this;return u(this,function(c){switch(c.label){case 0:a=this.layer;if("esri.layers.WMTSLayer"!==a.declaredClass)return[3,1];this._constructLegendElementsForWMTSlayer();
return[3,6];case 1:if("esri.layers.WMSLayer"!==a.declaredClass)return[3,2];this._constructLegendElementsForWMSSublayers();return[3,6];case 2:return"esri.layers.MapImageLayer"!==a.declaredClass?[3,4]:[4,this._constructLegendElementsForSublayers()];case 3:return c.sent(),[3,6];case 4:return this._handles.remove("imageryLayers-watcher"),[4,this._getLegendLayers().then(function(c){b.legendElements=[];c.forEach(function(c){if("esri.layers.ImageryLayer"===a.declaredClass){var d=a.watch("renderingRule, bandIds",
function(){b._legendResponse["default"]=null;b.buildLegendElementsForTools()});b._handles.add(d,"imageryLayers-watcher")}(c=b._generateSymbolTableElementForLegendLayer(c))&&c.infos.length&&("esri.layers.ImageryLayer"===a.declaredClass&&(c.title=a.title),b.legendElements.push(c));b.notifyChange("ready")});b.notifyChange("ready")}).catch(function(a){r.warn("Request to server for legend has failed!",a)})];case 5:c.sent(),c.label=6;case 6:return[2]}})})};f.prototype._isGroupActive=function(){var a=this.children;
return a.length?a.some(function(a){return a.ready}):!1};f.prototype._isScaleDrivenSizeVariable=function(a){if(a&&"size"!==a.type)return!1;var b=a.minSize,c=a.maxSize;return"object"===typeof b&&b?this._isScaleDrivenSizeVariable(b):"object"===typeof c&&c?this._isScaleDrivenSizeVariable(c):!!a.expression||aa.test(a.valueExpression)};f.prototype._buildRendererLegendElements=function(a,b,c){return p(this,void 0,void 0,function(){var d,e;return u(this,function(g){switch(g.label){case 0:return g.trys.push([0,
2,,3]),[4,this._getRendererLegendElements(a,b)];case 1:return d=g.sent(),"append"===c?Array.prototype.push.apply(this.legendElements,d):this.legendElements=d,this.notifyChange("ready"),[3,3];case 2:return e=g.sent(),r.warn("error while building legend for layer!",e),[3,3];case 3:return[2]}})})};f.prototype._constructLegendElementsForWMTSlayer=function(){this.legendElements=[];this._handles.remove("wmts-activeLayer-watcher");var a=this.layer,b=a.activeLayer;this._handles.add(y.watch(this.layer,"activeLayer",
this._constructLegendElementsForWMTSlayer.bind(this)),"wmts-activeLayer-watcher");if(b.styleId&&b.styles){var c=null;b.styles.some(function(a){return b.styleId===a.id?(c=a.legendUrl,!0):!1});c&&(this.legendElements=[{type:"symbol-table",title:b.title,infos:[{src:c,opacity:a.opacity}]}])}this.notifyChange("ready")};f.prototype._constructLegendElementsForWMSSublayers=function(){this.legendElements=[];this._handles.remove("wms-sublayers-watcher");var a=this.layer,b=null;if(a.customParameters||a.customLayerParameters)b=
K({},a.customParameters,a.customLayerParameters);this._handles.add(y.watch(this.layer,"sublayers",this._constructLegendElementsForWMSSublayers.bind(this)),"wms-sublayers-watcher");this.legendElements=this._generateLegendElementsForWMSSublayers(a.sublayers,b);this.notifyChange("ready")};f.prototype._generateLegendElementsForWMSSublayers=function(a,b){var c=this,d=[];this._handles.add(a.on("change",this._constructLegendElementsForWMSSublayers.bind(this)),"wms-sublayers-watcher");a.forEach(function(a){var e=
a.watch("title, visible, legendEnabled",function(){return c._constructLegendElementsForWMSSublayers()});c._handles.add(e,"wms-sublayers-watcher");a.visible&&a.legendEnabled&&(a=c._generateSymbolTableElementForWMSSublayer(a,b))&&a.infos.length&&d.unshift(a)});return d};f.prototype._generateSymbolTableElementForWMSSublayer=function(a,b){return!a.legendUrl&&a.sublayers?(b=this._generateLegendElementsForWMSSublayers(a.sublayers,b).filter(function(a){return a}),{type:"symbol-table",title:a.title,infos:b}):
this._generateSymbolTableElementForLegendUrl(a,b)};f.prototype._generateSymbolTableElementForLegendUrl=function(a,b){var c=a.legendUrl;if(c){var d={type:"symbol-table",title:a.title||a.name||a.id&&a.id+"",infos:[]};b&&(c+="?"+X.objectToQuery(b));d.infos.push({src:c,opacity:a.layer&&a.layer.opacity});return d}};f.prototype._getLegendLayers=function(a){var b=this,c=(a=a&&a.hasDynamicLayers?a.dynamicLayers:null)||"default",d=this._legendResponse&&this._legendResponse[c];return d?v.resolve(d):this._legendRequest(a).then(function(a){a=
a.layers;return b._legendResponse[c]=a})};f.prototype._legendRequest=function(a){var b=this.layer;a={f:"json",dynamicLayers:a};"esri.layers.ImageryLayer"===b.declaredClass&&(b.renderingRule&&(a.renderingRule=JSON.stringify(b.renderingRule.toJSON())),b.bandIds&&(a.bandIds=b.bandIds.join()),b.raster||b.viewId)&&(a=K({raster:b.raster,viewId:b.viewId},a));var c=b.url.replace(/(\/)+$/,"");"version"in b&&10.01<=b.version?(b=c.indexOf("?"),c=-1<b?c.substring(0,b)+"/legend"+c.substring(b):c+"/legend"):(b=
c.toLowerCase().indexOf("/rest/"),c=c.substring(0,b)+c.substring(b+5,c.length),c="https://utility.arcgis.com/sharing/tools/legend?soapUrl\x3d"+encodeURI(c)+"\x26returnbytes\x3dtrue");return fa(c,{query:a}).then(function(a){return a.data})};f.prototype._constructLegendElementsForSublayers=function(){var a=this;this.legendElements=[];this._handles.remove("sublayers-watcher");var b=this.layer,c=new la.ExportImageParameters({layer:b});return this._getLegendLayers(c).then(function(c){var d={};c.forEach(function(a){d[a.layerId]=
a});a._handles.add(y.watch(b,"sublayers",a._constructLegendElementsForSublayers.bind(a)),"sublayers-watcher");a.legendElements=a._generateLegendElementsForSublayers(b.sublayers,d,b.opacity);a.notifyChange("ready")}).catch(function(a){r.warn("Request to server for legend has failed!",a)}).then(function(){return c.destroy()})};f.prototype._generateLegendElementsForSublayers=function(a,b,c){var d=this,e=[];this._handles.add(a.on("change",this._constructLegendElementsForSublayers.bind(this)),"sublayers-watcher");
a.forEach(function(a){var g=a.watch("renderer, opacity, title, visible",function(){return d._constructLegendElementsForSublayers()});d._handles.add(g,"sublayers-watcher");a.visible&&a.legendEnabled&&(g=a&&null!=a.opacity?a.opacity:null,(a=d._generateSymbolTableElementForSublayer(a,b,null!=g?g*c:c))&&a.infos.length&&e.unshift(a))});return e};f.prototype._generateSymbolTableElementForSublayer=function(a,b,c){var d=b[a.id];return!d&&a.sublayers?(b=this._generateLegendElementsForSublayers(a.sublayers,
b,c).filter(function(a){return a}),{type:"symbol-table",title:a.title,infos:b}):this._generateSymbolTableElementForLegendLayer(d,a,c)};f.prototype._generateSymbolTableElementForLegendLayer=function(a,b,c){var d=this;if(a){var e=b&&b.renderer,g=b&&b.title||a.layerName;e&&(e=b&&b.title||this._getRendererTitle(e,b))&&(g&&(e.title=g),g=e);g={type:"symbol-table",title:g,infos:[]};a.legendType&&(g.legendType=a.legendType);a.legend&&this._isLegendLayerInScale(a,b)&&(b=b?this._sanitizeLegendForSublayer(a.legend.slice(),
b):a.legend,g.infos=b.map(function(b){var e=b.url;if(b.imageData&&0<b.imageData.length)e="data:image/png;base64,"+b.imageData;else if(0!==e.indexOf("http"))e=X.addTokenParameter(d.layer.url+"/"+a.layerId+"/images/"+e);else return null;return{label:b.label,src:e,opacity:c,width:b.width,height:b.height}}).filter(function(a){return!!a}));return g.infos.length?g:null}};f.prototype._isLegendLayerInScale=function(a,b){b=b||this.layer;var c=null,d=null,e=!0;!b.minScale&&0!==b.minScale||!b.maxScale&&0!==
b.maxScale?(0===a.minScale&&b.tileInfo&&(c=b.tileInfo.lods[0].scale),0===a.maxScale&&b.tileInfo&&(d=b.tileInfo.lods[b.tileInfo.lods.length-1].scale)):(c=Math.min(b.minScale,a.minScale)||b.minScale||a.minScale,d=Math.max(b.maxScale,a.maxScale));if(0<c&&c<this.scale||d>this.scale)e=!1;return e};f.prototype._sanitizeLegendForSublayer=function(a,b){if("version"in this.layer&&10.1>this.layer.version||0===a.length)return a;b=b.renderer;var c=null,d=null;a.some(function(a){return a.values})&&a.some(function(a,
b){a.values||(c=b,d=a,d.label||(d.label="others"));return null!=d});b?"unique-value"===b.type?d&&(a.splice(c,1),a.push(d)):"class-breaks"===b.type&&(d&&a.splice(c,1),a.reverse(),d&&a.push(d)):d&&(a.splice(c,1),a.push(d));return a};f.prototype._getRendererLegendElements=function(a,b){return p(this,void 0,void 0,function(){return u(this,function(c){return H(a)||I(a)||P(a)||"raster-stretch"===a.type||"raster-colormap"===a.type||Z(a)||B(a)||C(a)||J(a)||"esri.renderers.DotDensityRenderer"===a.declaredClass?
B(a)||C(a)||J(a)||"esri.renderers.PointCloudRGBRenderer"===a.declaredClass?[2,this._constructPointCloudRendererLegendElements(a,b)]:"dot-density"===a.type?[2,this._constructDotDensityRendererLegendElements(a)]:[2,this._constructRendererLegendElements(a,b)]:(r.warn("Renderer not supported!"),[2,[]])})})};f.prototype._getPointCloudRendererTitle=function(a){return a.legendOptions&&a.legendOptions.title||a.field};f.prototype._constructPointCloudRendererLegendElements=function(a,b){var c=this,d=[],e=null,
g=null;if(B(a))e={type:"symbol-table",title:b||this._getPointCloudRendererTitle(a),infos:[]},a.colorClassBreakInfos.forEach(function(a){e.infos.unshift({label:a.label||a.minValue+" - "+a.maxValue,value:[a.minValue,a.maxValue],symbol:c._getAppliedCloneSymbol(D,a.color)})});else if(C(a)){var g=a.stops,f=null;if(g.length&&(1===g.length&&(f=g[0].color),!f)){var h=g[0].value,q=g[g.length-1].value;null!=h&&null!=q&&(f=z.getColorFromPointCloudStops(h+(q-h)/2,g))}e={type:"symbol-table",title:null,infos:[{label:null,
value:null,symbol:this._getAppliedCloneSymbol(D,f||D.color)}]};g=z.getRampStopsForPointCloud(a.stops);g={type:"color-ramp",title:b||this._getPointCloudRendererTitle(a),infos:g,preview:A.renderColorRampPreviewHTML(g.map(function(a){return a.color}))}}else J(a)&&(e={type:"symbol-table",title:b||this._getPointCloudRendererTitle(a),infos:[]},a.colorUniqueValueInfos.forEach(function(a){e.infos.push({label:a.label||a.values.join(", "),value:a.values.join(", "),symbol:c._getAppliedCloneSymbol(D,a.color)})}));
e&&e.infos.length&&d.push(e);g&&g.infos.length&&d.push(g);a=d.reduce(function(a,b){return a.concat(b.infos)},[]).filter(function(a){return!!a.symbol}).map(function(a){return c._getSymbolPreview(a)});return v.eachAlways(a).then(function(){return d})};f.prototype._getElementInfoForDotDensity=function(a,b){var c=a.outline,c=a.dotSize+"-"+b+"-"+a.backgroundColor+"-"+(c&&JSON.stringify(c.toJSON())),d=this._dotDensityUrlCache;a=d.has(c)?d.get(c):A.renderDotDensityPreviewHTML(a,b);d.set(c,a);return{opacity:1,
src:a.src,preview:a,width:a.width,height:a.height}};f.prototype._constructDotDensityRendererLegendElements=function(a){var b=this,c=a.calculateDotValue(this.view.scale),d={type:"symbol-table",title:{value:c&&Math.round(c),unit:a.legendOptions&&a.legendOptions.unit||""},infos:[]};a.attributes.forEach(function(c){var e=b._getElementInfoForDotDensity(a,c.color);e.label=c.label||c.valueExpressionTitle||c.field;d.infos.push(e)});return v.resolve([d])};f.prototype._constructRendererLegendElements=function(a,
b){return p(this,void 0,void 0,function(){var c,d,e,g,f,h,q,l,n,k,p,Q,m,ba,r,O,R,S,y,T,ca,U,z,D,L,w,x,F,t,G,B,M,C,J,K,V=this;return u(this,function(E){switch(E.label){case 0:return[4,this._loadRenderer(a)];case 1:return c=E.sent(),this._hasSizeRamp=this._hasOpacityRamp=this._hasColorRamp=!1,[4,this._getVisualVariableLegendElements(c)];case 2:d=E.sent()||[];e={type:"symbol-table",title:b||this._getRendererTitle(c),infos:[]};g=null;f=!1;if(!Z(c))return[3,3];h=ra.getHeatmapRampStops(c);d.push({type:"heatmap-ramp",
title:b,infos:h,preview:A.renderColorRampPreviewHTML(h.map(function(a){return a.color}))});return[3,10];case 3:if(!P(c))return[3,4];if(l=(q=c&&c.authoringInfo)&&"relationship"===q.type){if(n=q.focus,k=q.numClasses,p=q.field1,Q=q.field2,k&&p&&Q){m=this.layer;ba=[p,Q];r=Y.getRotationAngleForFocus(n)||0;O=0;for(R=ba;O<R.length;O++)S=R[O],y=S.field,T=S.normalizationField,ca={field:this._getFieldAlias(y,m),normField:T&&this._getFieldAlias(T,m)},U=ua.clone(),U.angle=r,e.infos.push({label:ca,symbol:U}),
r+=90;z=Y.getRelationshipRampElement({focus:n,numClasses:k,infos:c.uniqueValueInfos});d.unshift(z)}}else D=c.field,c.uniqueValueInfos.forEach(function(a){a.symbol&&e.infos.push({label:a.label||V._getDomainName(D,a.value)||a.value,value:a.value,symbol:a.symbol})});c.defaultSymbol&&(e.infos.push({label:c.defaultLabel||"others",symbol:c.defaultSymbol}),f=!0);return[3,10];case 4:if(!I(c))return[3,5];g=this._isUnclassedRenderer(c);if(L=!g||!this._hasSizeRamp)c.classBreakInfos.forEach(function(a){a.symbol&&
e.infos.unshift({label:a.label||(g?null:a.minValue+" - "+a.maxValue),value:[a.minValue,a.maxValue],symbol:a.symbol})}),g&&(e.title=null),this._updateInfosforClassedSizeRenderer(c,e.infos);c.defaultSymbol&&!g&&(e.infos.push({label:c.defaultLabel||"others",symbol:c.defaultSymbol}),f=!0);return[3,10];case 5:if("raster-stretch"!==c.type)return[3,9];m=this.layer;x=w=void 0;c.statistics&&(w=c.statistics[0].min||c.statistics[0][0],x=c.statistics[0].max||c.statistics[0][1]);F=[];G=N.unwrap;return m.renderingRule?
[4,m.generateRasterInfo(m.renderingRule)]:[3,7];case 6:return B=E.sent(),[3,8];case 7:B=m.serviceRasterInfo,E.label=8;case 8:return t=G.apply(void 0,[B]),M=t.keyProperties.BandProperties,1===t.bandCount?(w=w||t.statistics&&t.statistics[0].min,x=x||t.statistics&&t.statistics[0].max,w&&x?d.push(this._getStretchLegendElements(c,{min:w,max:x})):this.buildLegendElementsForTools()):m.bandIds&&1===m.bandIds.length?(w=w||t.statistics&&t.statistics[m.bandIds[0]].min,x=x||t.statistics&&t.statistics[m.bandIds[0]].max,
w&&x?d.push(this._getStretchLegendElements(c,{min:w,max:x})):this.buildLegendElementsForTools()):3<=t.bandCount?M&&M.length>=t.bandCount?m.bandIds&&3===m.bandIds.length?(F=m.bandIds.map(function(a){return M[a].BandName}),e.infos=this._createSymbolTableElementMultiBand(F)):"lerc"===m.format?(F=[0,1,2].map(function(a){return M[a].BandName}),e.infos=this._createSymbolTableElementMultiBand(F)):this.buildLegendElementsForTools():"lerc"===m.format?(F=["band0","band1","band2"],e.infos=this._createSymbolTableElementMultiBand(F)):
this.buildLegendElementsForTools():this.buildLegendElementsForTools(),[3,10];case 9:"raster-colormap"===c.type?c.colormapInfos.forEach(function(a){e.infos.push({label:a.label,value:a.value,symbol:V._getAppliedCloneSymbol(ta,a.color)})}):H(c)&&c.symbol&&!this._hasSizeRamp&&e.infos.push({label:c.label,symbol:c.symbol}),E.label=10;case 10:return C=c.defaultSymbol,!C||f||H(c)||g&&!this._hasColorRamp&&!this._hasSizeRamp&&!this._hasOpacityRamp||d.push({type:"symbol-table",infos:[{label:c.defaultLabel||
"others",symbol:C}]}),e.infos.length&&d.unshift(e),J=this._getSymbolConfig("visualVariables"in c&&c.visualVariables),K=d.reduce(function(a,b){return a.concat(b.infos)},[]).filter(function(a){return!(!a||!a.symbol)}).map(function(a){return V._getSymbolPreview(a,J)}),c=null,[4,v.eachAlways(K)];case 11:return E.sent(),[2,d]}})})};f.prototype._getStretchLegendElements=function(a,b){a=z.getStrectchRampStops(a.colorRamp,b);return{type:"stretch-ramp",title:"",infos:a,preview:A.renderColorRampPreviewHTML(a.map(function(a){return a.color}))}};
f.prototype._createSymbolTableElementMultiBand=function(a){var b=[],c=["red","green","blue"];a.forEach(function(a,e){b.push({label:{colorName:c[e],bandName:a},src:sa.RGB_IMG_SOURCE[e],opacity:1})});return b};f.prototype._updateInfosforClassedSizeRenderer=function(a,b){var c=a.authoringInfo&&"class-breaks-size"===a.authoringInfo.type,d=a.classBreakInfos.some(function(a){return pa.isVolumetricSymbol(a.symbol)});if(c&&d){var e=G.REAL_WORLD_MAX_SIZE;a=a.classBreakInfos.length;var f=(e-G.REAL_WORLD_MIN_SIZE)/
(1<a?a-1:a);b.forEach(function(a,b){a.size=e-f*b})}};f.prototype._getSymbolConfig=function(a){var b=!1,c=!1;if(a)for(var d=0;d<a.length&&(!b||!c);d++){var e=a[d];"size"===e.type&&("height"===e.axis&&(b=!0),"width-and-depth"===e.axis&&(c=!0))}return b&&c?"tall":null};f.prototype._getSymbolPreview=function(a,b){return A.renderPreviewHTML(a.symbol,{size:a.size,opacity:this.layer.opacity,symbolConfig:b,rotation:a.symbol.angle}).then(function(b){a.preview=b;return a}).catch(function(){a.preview=null;return a})};
f.prototype._loadRenderer=function(a){return p(this,void 0,void 0,function(){var b,c,d,e,f=this;return u(this,function(g){switch(g.label){case 0:return b=[],a=a.clone(),[4,this._getMedianColor(a)];case 1:c=g.sent();if(I(a)||P(a))d=a.classBreakInfos||a.uniqueValueInfos,e=d.map(function(a){return f._fetchSymbol(a.symbol,c).then(function(b){a.symbol=b}).catch(function(){a.symbol=null})}),Array.prototype.push.apply(b,e);b.push(this._fetchSymbol(a.symbol||a.defaultSymbol,a.defaultSymbol?null:c).then(function(b){f._applySymbolToRenderer(a,
b,H(a))}).catch(function(){f._applySymbolToRenderer(a,null,H(a))}));return[2,v.eachAlways(b).then(function(){return a})]}})})};f.prototype._applySymbolToRenderer=function(a,b,c){c?a.symbol=b:a.defaultSymbol=b};f.prototype._getMedianColor=function(a){return p(this,void 0,void 0,function(){var b,c,d,e,f;return u(this,function(g){switch(g.label){case 0:if(!("visualVariables"in a&&a.visualVariables))return[2,null];b=ha.find(a.visualVariables,function(a){return"color"===a.type});if(!b)return[2,null];d=
c=null;if(b.stops){if(1===b.stops.length)return[2,b.stops[0].color];c=b.stops[0].value;d=b.stops[b.stops.length-1].value}e=c+(d-c)/2;return[4,new Promise(function(a,b){da(["../../../renderers/visualVariables/support/visualVariableUtils"],a,b)})];case 1:return f=g.sent().getColor,[2,f(b,e)]}})})};f.prototype._fetchSymbol=function(a,b){var c=this;if(!a)return v.reject();if("web-style"===a.type){var d=a.portal,d=a.name+"-"+a.styleName+"-"+a.styleUrl+"-"+(d&&d.url)+"-"+(d&&d.user&&d.user.username),e=
this._webStyleSymbolCache;e.has(d)||e.set(d,a.fetchSymbol());return e.get(d).then(function(a){return c._getAppliedCloneSymbol(a,b)}).catch(function(){r.warn("Fetching web-style failed!");return v.reject()})}return v.resolve(this._getAppliedCloneSymbol(a,b))};f.prototype._getAppliedCloneSymbol=function(a,b){if(!a)return a;a=a.clone();var c=-1<a.type.indexOf("3d");b=b&&b.toRgba();c?this._applyColorTo3dSymbol(a,b):a.color&&(a.color=new W(b||a.color));return a};f.prototype._applyColorTo3dSymbol=function(a,
b){b&&a.symbolLayers.forEach(function(a){a&&(a.material||(a.material={}),a.material.color=new W(b))})};f.prototype._createClusterSizeVariable=function(a){var b=qa.getActiveSizeStops(this.view,a);return new oa({field:a.field,legendOptions:{title:"Number of features"},minSize:b[2].size,minDataValue:b[2].value,maxSize:b[3].size,maxDataValue:b[3].value})};f.prototype._getVisualVariableLegendElements=function(a){return p(this,void 0,void 0,function(){var b,c,d,e,f,l,h,q,n,k,r=this;return u(this,function(g){switch(g.label){case 0:if(!("visualVariables"in
a&&a.visualVariables))return[2,null];b=a.visualVariables;c=[];d=[];e=[];f=this.layer;b.forEach(function(a){"color"===a.type?c.push(a):"size"===a.type?("levels"in a&&a.levels&&(a=r._createClusterSizeVariable(a)),d.push(a)):"opacity"===a.type&&e.push(a)});l=c.concat(d,e);0===c.length&&I(a)&&a.classBreakInfos&&1===a.classBreakInfos.length&&(h=(n=a.classBreakInfos[0])&&n.symbol);0===c.length&&H(a)&&(h=a.symbol);h&&(-1<h.type.indexOf("3d")?(k=h.symbolLayers.getItemAt(0),"water"===k.type?N.isSome(k.color)&&
(q=k.color):N.isSome(k.material)&&N.isSome(k.material.color)&&(q=k.material.color)):h.url||(q=h.color));return[4,v.all(l.map(function(b){return p(r,void 0,void 0,function(){var c,d,e,g,h,k,l,n;return u(this,function(m){switch(m.label){case 0:if(b.legendOptions&&!1===b.legendOptions.showLegend)return[3,8];c=this._getRampTitle(b,f);d=null;g=(e="getField"in f&&f.getField&&f.getField(b.field))&&ma.isDateField(e);return"color"!==b.type?[3,2]:[4,z.getRampStops(b,null,g)];case 1:return h=m.sent(),d={type:"color-ramp",
title:c,infos:h,preview:A.renderColorRampPreviewHTML(h.map(function(a){return a.color}))},this._hasColorRamp||(this._hasColorRamp=!(null==d.infos||!d.infos.length)),[3,7];case 2:if("size"!==b.type||"$view.scale"===b.valueExpression)return[3,5];k={type:"size-ramp",title:c};l=G.getRampStops;n=[a,b];return[4,this._getMedianColor(a)];case 3:return[4,l.apply(void 0,n.concat([m.sent(),this.scale,this.view,g]))];case 4:return d=(k.infos=m.sent(),k),this._hasSizeRamp||(this._hasSizeRamp=!(null==d.infos||
!d.infos.length)),[3,7];case 5:return"opacity"!==b.type?[3,7]:[4,z.getRampStops(b,q,g)];case 6:h=m.sent(),d={type:"opacity-ramp",title:c,infos:h,preview:A.renderColorRampPreviewHTML(h.map(function(a){return a.color}))},this._hasOpacityRamp||(this._hasOpacityRamp=!(null==d.infos||!d.infos.length)),m.label=7;case 7:return[2,d&&d.infos?d:null];case 8:return[2,void 0]}})})}))];case 1:return[2,g.sent().filter(function(a){return!!a})]}})})};f.prototype._getDomainName=function(a,b){if(a&&"function"!==typeof a){var c=
this.layer;return(c=(a=c.getField&&c.getField(a))&&c.getFieldDomain?c.getFieldDomain(a.name):null)&&c.codedValues?c.getName(b):null}return null};f.prototype._getRampTitle=function(a,b){var c=a.field,d=a.normalizationField,e=!1,f=!1,k=!1,h=null,c="function"===typeof c?null:c,d="function"===typeof d?null:d;if(null!=(a.legendOptions&&a.legendOptions.title))h=a.legendOptions.title;else if(a.valueExpressionTitle)h=a.valueExpressionTitle;else{if("renderer"in b&&b.renderer&&"authoringInfo"in b.renderer&&
b.renderer.authoringInfo&&b.renderer.authoringInfo.visualVariables)for(a=b.renderer.authoringInfo.visualVariables,h=0;h<a.length;h++){var l=a[h];if("color"===l.type){if("ratio"===l.style){e=!0;break}if("percent"===l.style){f=!0;break}if("percent-of-total"===l.style){k=!0;break}}}h={field:c&&this._getFieldAlias(c,b),normField:d&&this._getFieldAlias(d,b),ratio:e,ratioPercent:f,ratioPercentTotal:k}}return h};f.prototype._getRendererTitle=function(a,b){if(a.legendOptions&&a.legendOptions.title)return a.legendOptions.title;
if(a.valueExpressionTitle)return a.valueExpressionTitle;var c=this.layer,d=a.field,e=null,f=null;I(a)&&(e=a.normalizationField,f="percent-of-total"===a.normalizationType);d="function"===typeof d?null:d;e="function"===typeof e?null:e;a=null;if(d||e)a={field:b?d:d&&this._getFieldAlias(d,c),normField:b?e:e&&this._getFieldAlias(e,c),normByPct:f};return a};f.prototype._getFieldAlias=function(a,b){var c="popupTemplate"in b&&b.popupTemplate,c=c&&c.fieldInfos;b="function"===typeof a?null:"getField"in b&&
b.getField&&b.getField(a);var d=null;c&&c.some(function(b){return a===b.fieldName?(d=b,!0):!1});var c=d||b,e=null;c&&(e=d&&d.label||b&&b.alias||"name"in c&&c.name||"fieldName"in c&&c.fieldName);return e};f.prototype._isUnclassedRenderer=function(a){var b=a.visualVariables,c=!1;I(a)&&a.classBreakInfos&&1===a.classBreakInfos.length&&b&&(c=a.field?b.some(function(b){return!(!b||a.field!==b.field||(a.normalizationField||b.normalizationField)&&a.normalizationField!==b.normalizationField)}):!!b.length);
return c};k([n.property()],f.prototype,"children",void 0);k([n.property()],f.prototype,"layer",void 0);k([n.property()],f.prototype,"legendElements",void 0);k([n.property()],f.prototype,"parent",void 0);k([n.property({readOnly:!0})],f.prototype,"ready",null);k([n.property()],f.prototype,"scale",void 0);k([n.property({dependsOn:["layer.renderer?.valueExpression?","layer.renderer?.visualVariables?","layer.featureReduction?"],readOnly:!0})],f.prototype,"isScaleDriven",null);k([n.property()],f.prototype,
"title",void 0);k([n.property({dependsOn:["ready"],readOnly:!0,value:0})],f.prototype,"version",null);k([n.property()],f.prototype,"view",void 0);return f=k([n.subclass("esri.widgets.Legend.support.ActiveLayerInfo")],f)}(n.declared(ga))});