// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/declareExtendsHelper ../../../core/Accessor ../../../core/maybe ../../../core/accessorSupport/decorators ../../../core/libs/gl-matrix-2/vec3 ../../../core/libs/gl-matrix-2/vec3f64 ./lib/AutoDisposable ./lib/GeometryRecord ./lighting/Lightsources ./parts/Model ./parts/RenderView".split(" "),function(m,n,d,r,t,u,e,p,g,h,v,k,w,x){function q(d){return"function"===typeof d.addParentStage&&"function"===typeof d.removeParentStage}
Object.defineProperty(n,"__esModule",{value:!0});m=function(l){function a(){var b=null!==l&&l.apply(this,arguments)||this;b._viewContent=[];b._mainLightDirection=g.vec3f64.fromValues(0,1,0);return b}r(a,l);f=a;a.prototype.initialize=function(){this.model=new w;this._set("renderView",new x(this.container,this,this.model.getDirtySet(),this.options));this.setLighting({lights:[new k.MainLight(g.vec3f64.fromValues(.7,.7,.7)),new k.AmbientLight(g.vec3f64.fromValues(.3,.3,.3))],groundLightingFactor:.5,globalFactor:.5})};
a.prototype.destroy=function(){v.pool.prune(0);this.dispose()};Object.defineProperty(a.prototype,"dirty",{get:function(){var b=this.model.getDirtySet();return!(!b.hasDirtyGeometryRecords()&&!b.getDirtyMaterials())},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"mainLightDirection",{get:function(){return this._mainLightDirection},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"lighting",{get:function(){return this._lighting},enumerable:!0,configurable:!0});a.prototype.setLighting=
function(b){p.vec3.set(this._mainLightDirection,0,0,0);for(var a=0,c=b.lights;a<c.length;a++){var d=c[a];if(d instanceof k.MainLight){p.vec3.negate(this._mainLightDirection,d.direction);break}}this._lighting=b;this.renderView.setNeedsRender()};a.prototype.forceAllAnimations=function(b){this.getAll(3).forEach(function(a){u.applySome(a.animation,function(a){return a.forceTime(b)})});this.renderView.setNeedsRender()};a.prototype.add=function(b,a){this.model.add(b,a);q(a)&&a.addParentStage(this);this.renderView.setNeedsRender()};
a.prototype.remove=function(b,a){this.renderView.setNeedsRender();b=this.model.remove(b,a);q(b)&&b.removeParentStage(this);return b};a.prototype.notifyDirty=function(b,a,c){this.model.notifyDirty(b,a,c);this.renderView.setNeedsRender()};a.prototype.processDirty=function(){var b=this.model.getDirtySet(),a=b.getDirtyMaterials();if(b.hasDirtyGeometryRecords()||a){f.DebugSettings.logDirtySet&&console.log("Dirty set: "+this.model.getDirtySet().formatDebugInfo(!1));var c=b.commitLayers(this._viewContent);
(0<c[0].length+c[1].length+c[2].length||a)&&this.renderView.modify(c[0],c[1],c[2],a);f.DebugSettings.logDirtySet&&(console.log("RGs add: "+c[0].map(function(b){return b.uniqueName})),console.log("RGs remove: "+c[1].map(function(b){return b.uniqueName})));b.commit();b.clearDirtyMaterials();this.renderView.setNeedsRender()}};a.prototype.processDirtyLayer=function(b){var a=this.model.getDirtySet(),c=a.getDirtyMaterials();b=a.commitLayers([b]);(0<b[0].length+b[1].length+b[2].length||c)&&this.renderView.modify(b[0],
b[1],b[2],c);a.clearDirtyMaterials();this.renderView.setNeedsRender()};a.prototype.getContent=function(b,a){return this.model.get(b,a)};a.prototype.getAll=function(b){return this.model.getAll(b)};a.prototype.getCount=function(b){return this.model.getAll(b).size};a.prototype.getCamera=function(){return this.renderView.getCamera()};a.prototype.setCamera=function(b){this.renderView.setCamera(b)};a.prototype.getLayers=function(){return this.model.getAll(0)};a.prototype.getViewContent=function(){return this._viewContent.slice(0)};
a.prototype.addToViewContent=function(b){for(var a=[],c=0;c<b.length;c++)-1===this._viewContent.indexOf(b[c])&&a.push(b[c]);0<b.length&&(this.processDirty(),b=this.model.getDirtySet().getResidentRenderGeometriesFilteredByLayers(a),this.renderView.modify(b,[],[]),this._viewContent.push.apply(this._viewContent,a))};a.prototype.removeFromViewContent=function(b){this.processDirty();for(var a=this.model.getDirtySet(),c=this._viewContent,d=[],e=0;e<b.length;e++){var f=c.indexOf(b[e]);-1<f&&(c[f]=c[c.length-
1],c.pop(),d.push(b[e]))}b=a.getResidentRenderGeometriesFilteredByLayers(d);this.renderView.modify([],b,[])};a.prototype.addRenderPlugin=function(b,a){"intersect"in a&&this.sceneIntersectionHelper.addIntersectionHandler(a);this.renderView.renderPlugins.add(b,a)};a.prototype.removeRenderPlugin=function(a){"intersect"in a&&this.sceneIntersectionHelper.removeIntersectionHandler(a);this.renderView.renderPlugins.remove(a)};a.prototype.getContentDebugStrings=function(a){return this.model.formatDebugInfo(a)};
var f;a.DebugSettings={endFrameContentValidation:!1,logDirtySet:!1};d([e.property({constructOnly:!0})],a.prototype,"options",void 0);d([e.property({constructOnly:!0})],a.prototype,"sceneIntersectionHelper",void 0);d([e.property({constructOnly:!0})],a.prototype,"viewingMode",void 0);d([e.property({constructOnly:!0})],a.prototype,"container",void 0);d([h.autoDispose()],a.prototype,"model",void 0);d([h.autoDispose(),e.property()],a.prototype,"renderView",void 0);return a=f=d([e.subclass("esri.views.3d.webgl-engine.Stage")],
a)}(e.declared(h.AutoDisposableMixin(t)));n.Stage=m});