// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../../core/tsSupport/extendsHelper ../../../../../../core/screenUtils ../../alignmentUtils ../../color ../../fontUtils ../../materialKey/MaterialKey ./util ./WGLBaseTextTemplate ./WGLDynamicMeshTemplate ../../util/BidiText".split(" "),function(q,r,v,k,n,t,w,x,c,C,D,E){Object.defineProperty(r,"__esModule",{value:!0});var p=new Set;q=function(q){function f(u,a,h){var b=q.call(this,a)||this;b._horizontalAlignment="center";b._verticalAlignment="middle";b._glyphs=[];
b._cimTextLayer=a;var g=0;c.isFunction(a.color)||(g=t.premultiplyAlphaRGBA(a.color));b._dynamicPropertyMap.set("_color",function(b,e,d){return c.isFunction(a.color)?t.premultiplyAlphaRGBA(a.color(b,e,d)):g});var l=0;c.isFunction(a.color)||(l=t.premultiplyAlphaRGBA(a.outlineColor));b._dynamicPropertyMap.set("_haloColor",function(b,e,d){return c.isFunction(a.outlineColor)?t.premultiplyAlphaRGBA(a.outlineColor(b,e,d)):l});var m;c.isFunction(a.size)||(m=Math.min(Math.round(k.pt2px(a.size*a.sizeRatio)),
127));b._dynamicPropertyMap.set("_size",function(b,e,d){return c.isFunction(a.size)?Math.min(Math.round(k.pt2px(a.size(b,e,d)*a.sizeRatio)),127):m});var y;c.isFunction(a.outlineSize)||(y=Math.min(Math.floor(5*k.pt2px(a.outlineSize*a.sizeRatio)),127));b._dynamicPropertyMap.set("_haloSize",function(b,e,d){return c.isFunction(a.outlineSize)?Math.min(Math.floor(5*k.pt2px(a.outlineSize(b,e,d)*a.sizeRatio)),127):y});var z;c.isFunction(a.offsetX)||(z=Math.round(k.pt2px(a.offsetX*a.sizeRatio)));b._dynamicPropertyMap.set("_xOffset",
function(b,e,d){return c.isFunction(a.offsetX)?Math.round(k.pt2px(a.offsetX(b,e,d)*a.sizeRatio)):z});var A;c.isFunction(a.offsetY)||(A=Math.round(k.pt2px(a.offsetY*a.sizeRatio)));b._dynamicPropertyMap.set("_yOffset",function(b,e,d){return c.isFunction(a.offsetY)?Math.round(k.pt2px(a.offsetY(b,e,d)*a.sizeRatio)):A});var f;c.isFunction(a.decoration)||(f=w.getFontDecorationTop(a.decoration));b._dynamicPropertyMap.set("_decorationTop",function(b,e,d){return c.isFunction(a.decoration)?w.getFontDecorationTop(a.decoration(b,
e,d)):f});var n;c.isFunction(a.angle)||(n=a.angle);b._dynamicPropertyMap.set("_angle",function(b,e,d){return c.isFunction(a.angle)?a.angle(b,e,d):n});var p;c.isFunction(a.horizontalAlignment)||(p=a.horizontalAlignment);b._dynamicPropertyMap.set("_horizontalAlignment",function(b,e,d){return c.isFunction(a.horizontalAlignment)?a.horizontalAlignment(b,e,d):p});var r;c.isFunction(a.verticalAlignment)||(r=a.verticalAlignment);b._dynamicPropertyMap.set("_verticalAlignment",function(b,e,d){return c.isFunction(a.verticalAlignment)?
a.verticalAlignment(b,e,d):r});b._dynamicPropertyMap.set("_scaleFactor",function(a,b,d){return c.isFunction(h)?h(a,b,d):h});var B;c.isFunction(a.text)||(B=a.text);b._dynamicPropertyMap.set("_text",function(b,e,d){return c.isFunction(a.text)?a.text(b,e,d):B});var v=Math.min(Math.round(k.pt2px(a.referenceSize*a.sizeRatio)),127);b._referenceSize=Math.round(Math.sqrt(256*v));b._materialKey=x.createMaterialKey(b.geometryType,u,!1);u=x.TextMaterialKey.load(b._materialKey);u.sdf=!0;b._bitset=a.colorLocked?
1:0;b._materialKey=u.data;return b}v(f,q);f.fromCIMText=function(c,a,h){return new f(c,a,h)};f.prototype.analyze=function(c,a,h,b){var g=this._cimTextLayer;a="string"===typeof g.text?g.text:"function"===typeof g.text?g.text(a,h,b):"";var l=this._glyphs;p.clear();for(h=0;h<a.length;h++)p.add(a.charCodeAt(h));var m=[];p.forEach(function(a){if(l.length<a||void 0===l[a])m[a]=a});return c.getCIMMosaicItem(g.cim,m).then(function(a){if(a.glyphMosaicItems&&0<a.glyphMosaicItems.length)for(var b=a.glyphMosaicItems,
c=0;c<b.length;c++)void 0!==b[c]&&(l[c]=b[c]);return a})};f.prototype.bindFeature=function(c,a,h){var b=this,g=this._dynamicPropertyMap;g&&g.forEach(function(f,g){b[g]=f(c,a,h)});if(this._text&&0!==this._text.length){this._size*=this._scaleFactor;this._scale=this._size/24;this._xOffset*=this._scaleFactor;this._yOffset*=this._scaleFactor;this._justify=n.getJustification(this._horizontalAlignment||"center");this._xAlignD=n.getXAnchorDirection(this._horizontalAlignment||"center");this._yAlignD=-n.getYAnchorDirection(this._verticalAlignment||
"baseline");this._baseline="baseline"===(this._verticalAlignment||"baseline");for(var g=this._glyphs,l=E.bidiText(this._text),m=l[0],l=l[1],k=[],f=0;f<m.length;f++)k[m.charCodeAt(f)]=g[m.charCodeAt(f)];this.bindTextInfo(k,m,l);this._computeGlyphs(this._shapedGlyphs,this._shapedBox)}else this._shapedBox=this._shapedGlyphs=this._computedGlyphs=null};return f}(C.default(D.default));r.default=q});