// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../../core/tsSupport/extendsHelper ../../../../../../core/screenUtils ../../../../../../core/libs/gl-matrix-2/mat2d ../../../../../../core/libs/gl-matrix-2/mat2df32 ../../../../../../core/libs/gl-matrix-2/vec2 ../../../../../../core/libs/gl-matrix-2/vec2f32 ../../../../../../symbols/cim/enums ../../color ../../definitions ../../number ../../materialKey/MaterialKey ./WGLBaseMarkerTemplate ./WGLMeshTemplate".split(" "),function(u,C,G,f,D,H,n,E,z,y,I,g,F,J,K){Object.defineProperty(C,
"__esModule",{value:!0});u=function(u){function p(l,a,d,f,e,m,h,q,k,v,p,A,y,B,b,w,r,x,t){var c=u.call(this)||this;c.height=h;c.width=m;c.xOffset=a*t;c.yOffset=d*t;a=E.vec2f32.create();d=H.mat2df32.create();p=(B===z.Alignment.MAP?1:0)|(p?1:0)<<1|(y?1:0)<<2|(A?1:0)<<3;A=b&&b.sdf;D.mat2d.translate(d,d,E.vec2f32.fromValues(c.xOffset,-c.yOffset));f&&D.mat2d.rotate(d,d,3.14159265359/180*f);l=F.MarkerMaterialKey.load(F.createMaterialKey(c.geometryType,l,!1));l.sdf=A;l.pattern=!0;l.textureBinding=b.textureBinding;
c._materialKey=l.data;c._fillColor=e;c._outlineColor=k;c._sizeOutlineWidth=g.i8888to32(Math.round(Math.sqrt(256*m)),Math.round(Math.sqrt(256*h)),Math.round(Math.sqrt(256*v)),Math.round(Math.sqrt(256*q)));e=b.rect.x;q=b.rect.y;k=e+b.rect.width;v=q+b.rect.height;w=.5-((.5+w)*b.width+1)/b.rect.width;r=.5-((.5+r)*b.height+1)/b.rect.height;l=Math.round(Math.min(64*x,255));m*=b.rect.width/b.width*x*t;h*=b.rect.height/b.height*x*t;b=(w-.5)*m;r=(r-.5)*h;c._bitestAndDistRatio=g.i8888to32(0,0,p,l);n.vec2.set(a,
b,r);n.vec2.transformMat2d(a,a,d);c._offsetUpperLeft=g.i1616to32(16*a[0],16*a[1]);c._texUpperLeft=g.i1616to32(e,q);n.vec2.set(a,b+m,r);n.vec2.transformMat2d(a,a,d);c._offsetUpperRight=g.i1616to32(16*a[0],16*a[1]);c._texUpperRight=g.i1616to32(k,q);n.vec2.set(a,b,r+h);n.vec2.transformMat2d(a,a,d);c._offsetBottomLeft=g.i1616to32(16*a[0],16*a[1]);c._texBottomLeft=g.i1616to32(e,v);n.vec2.set(a,b+m,r+h);n.vec2.transformMat2d(a,a,d);c._offsetBottomRight=g.i1616to32(16*a[0],16*a[1]);c._texBottomRight=g.i1616to32(k,
v);return c}G(p,u);p.fromCIMMarker=function(l,a,d,g){var e=a.size,m=(d&&d.width||1)/(d&&d.height||1)*a.scaleX,h=a.scaleSymbolsProportionally&&a.frameHeight?e/a.frameHeight:1,q=y.premultiplyAlphaRGBA(a.color),k=y.premultiplyAlphaRGBA(a.outlineColor),v=f.pt2px(e),n=v*m,u=f.pt2px(a.offsetX||0),L=f.pt2px(a.offsetY||0),h=f.pt2px(a.outlineWidth||0)*h,B=a.alignment||z.Alignment.SCREEN,b=f.pt2px(a.referenceSize),w=a.rotation||0;a.rotateClockwise||(w=-w);var r=0,x=0,t=a.anchorPoint;t&&(a.isAbsoluteAnchorPoint?
e&&(r=-t.x/(e*m),x=t.y/e):(r=t.x,x=t.y));return new p(l,u,L,w,q,n,v,b,k,h,a.colorLocked,a.scaleSymbolsProportionally,!1,B,d,r,x,a.sizeRatio,g)};p.fromPictureMarker=function(l,a,d){var g=Math.round(f.pt2px(a.width)),e=Math.round(f.pt2px(a.height)),m=I.PICTURE_FILL_COLOR,h=Math.round(f.pt2px(a.xoffset||0)),q=Math.round(f.pt2px(a.yoffset||0));return new p(l,h,q,a.angle,m,g,e,e,0,0,!1,!1,!1,z.Alignment.SCREEN,d,0,0,1,1)};p.fromSimpleMarker=function(g,a,d){var l=y.premultiplyAlphaRGBA(a.color),e=Math.round(f.pt2px(a.size)),
m=Math.round(f.pt2px(a.xoffset||0)),h=Math.round(f.pt2px(a.yoffset||0)),q=a.style,k=a.outline,n=(k&&k.color&&y.premultiplyAlphaRGBA(k.color))|0,k=(k&&k.width&&Math.round(f.pt2px(k.width)))|0;return new p(g,m,h,a.angle,l,e,e,e,n,k,!1,!1,"cross"===q||"x"===q,z.Alignment.SCREEN,d,0,0,1.96875,1)};return p}(J.default(K.default));C.default=u});