// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/maybe ../../../../../core/libs/gl-matrix-2/mat3 ../../../../../core/libs/gl-matrix-2/mat3f64 ../../../../../core/libs/gl-matrix-2/mat4 ../../../../../core/libs/gl-matrix-2/vec2 ../../../../../core/libs/gl-matrix-2/vec3 ../../../../../core/libs/gl-matrix-2/vec3f64 ../../../../../core/libs/gl-matrix-2/vec4 ../../../support/geometryUtils ./AllRenderPasses ./RenderPass ../util/TwoVectorPosition ../../lib/depthRange".split(" "),function(m,n,p,h,t,u,q,f,v,w,x,
k,d,y,z){Object.defineProperty(n,"__esModule",{value:!0});m=function(){function c(a,b,e){this._renderView=a;this.rctx=b;this.shaderTechniqueRepository=e;this.canRender=!0;this._materialPassParams=new k.MaterialPassesParameters;this._shadowPassParams=new k.ShadowMapPassParameters;this._highlightPassParams=new k.HighlightPassParameters;this._systems=new Set;this._passes=[];this._shadowMapPass=this._registerPass(new d.RenderPass(b,this.shaderTechniqueRepository));this.passes={materialOpaque:this._registerPass(new d.RenderPass(b,
this.shaderTechniqueRepository)),materialTransparent:this._registerPass(new d.RenderPass(b,this.shaderTechniqueRepository)),materialIntegratedMesh:this._registerPass(new d.RenderPass(b,this.shaderTechniqueRepository)),shadowMap:this._shadowMapPass,highlight:this._registerPass(new d.RenderPass(b,this.shaderTechniqueRepository))}}c.prototype.register=function(a){this._systems.add(a)};c.prototype.prepareRender=function(){var a=this;this._passes.forEach(function(a){return a.prepareSubmit()});this._systems.forEach(function(b){b.submit(a.passes)});
this._passes.forEach(function(a){return a.finishSubmit()});this.shaderTechniqueRepository.frameUpdate()};c.prototype.render=function(a){if(5===a.slot)switch(this._configure(a),a.pass){case 0:this._materialPassParams.subPass=0;this._configureMaterialColorPass(a);this.passes.materialOpaque.dispatch(this._materialPassParams);break;case 1:this._materialPassParams.subPass=1;this.passes.materialOpaque.dispatch(this._materialPassParams);break;case 2:this._materialPassParams.subPass=2;this.passes.materialOpaque.dispatch(this._materialPassParams);
break;case 4:this.passes.highlight.dispatch(this._highlightPassParams);break;case 3:this._shadowMapPass.dispatch(this._shadowPassParams)}if(7===a.slot)switch(this._configure(a),a.pass){case 0:this._materialPassParams.subPass=0;this._configureMaterialColorPass(a);this.passes.materialTransparent.dispatch(this._materialPassParams);break;case 1:this._materialPassParams.subPass=1;this.passes.materialTransparent.dispatch(this._materialPassParams);break;case 2:this._materialPassParams.subPass=2,this.passes.materialTransparent.dispatch(this._materialPassParams)}if(2===
a.slot)switch(this._configure(a),a.pass){case 0:this._materialPassParams.subPass=0;this._configureMaterialColorPass(a);this.passes.materialIntegratedMesh.dispatch(this._materialPassParams);break;case 1:this._materialPassParams.subPass=1;this.passes.materialIntegratedMesh.dispatch(this._materialPassParams);break;case 2:this._materialPassParams.subPass=2,this.passes.materialIntegratedMesh.dispatch(this._materialPassParams)}return!0};c.prototype.notifyDirty=function(){this._renderView.setNeedsRender()};
c.prototype.slots=function(){return[5,7,2]};c.prototype.initializeRenderContext=function(){};c.prototype.uninitializeRenderContext=function(){};c.prototype.queryDepthRange=function(a){var b={near:Infinity,far:-Infinity};this._systems.forEach(function(e){e=e.queryShadowCasterDepthRange(a);p.isSome(e)&&z.union(b,e,b)});return b};Object.defineProperty(c.prototype,"shadowCastingEnabled",{get:function(){return p.isSome(this.passes.shadowMap)},set:function(a){a?(this._materialPassParams.shadowsEnabled=
!0,this.passes.shadowMap=this._shadowMapPass):(this._materialPassParams.shadowsEnabled=!1,this.passes.shadowMap=null)},enumerable:!0,configurable:!0});c.prototype._configureMaterialColorPass=function(a){var b=this;this._materialPassParams.shadowMap={bind:function(e){a.shadowMap.bind(e);var c=b._materialPassParams.viewTransform;f.vec3.add(g,c.worldFromView_TL,c.worldFromView_TH);a.shadowMap.bindView(e,g)}};this._materialPassParams.ambientOcclusion={bind:function(b){a.ssaoHelper.setUniforms(b)}};this._materialPassParams.ambientOcclusionEnabled=
a.ssaoHelper.enabled};c.prototype._configure=function(a){this._updateParameters(a,3===a.pass?this._shadowPassParams:4===a.pass?this._highlightPassParams:this._materialPassParams)};c.prototype._updateParameters=function(a,b){var c=a.camera,d=c.viewInverseTransposeMatrix;f.vec3.set(g,d[3],d[7],d[11]);l.set(g);f.vec3.copy(b.viewTransform.worldFromView_TH,l.high);f.vec3.copy(b.viewTransform.worldFromView_TL,l.low);h.mat3.fromMat4(b.viewTransform.viewFromCameraRelative_RS,c.viewMatrix);u.mat4.copy(b.viewTransform.projFromView,
c.projectionMatrix);0===b.identifier?(this._materialPassParams.transparent=7===a.slot,this._materialPassParams.integratedMesh=2===a.slot,this._materialPassParams.lighting=a.scenelightingData,h.mat3.transpose(r,b.viewTransform.viewFromCameraRelative_RS),h.mat3.invert(b.transformNormal_ViewFromGlobal,r),q.vec2.set(b.cameraNearFar,c.near,c.far)):1===b.identifier?q.vec2.set(b.cameraNearFar,c.near,c.far):2===b.identifier&&(b.highlightDepthTexture=a.highlightDepthTexture,w.vec4.copy(b.viewport,c.viewport));
x.boundedPlane.copy(a.sliceHelper.plane,b.slicePlane);f.vec3.subtract(b.slicePlane.origin,b.slicePlane.origin,g);b.slicePlaneEnabled=a.sliceHelper.isEnabled};c.prototype._registerPass=function(a){this._passes.push(a);return a};Object.defineProperty(c.prototype,"needsHighlight",{get:function(){return 0<this.passes.highlight.count},enumerable:!0,configurable:!0});return c}();n.RenderPassManager=m;var g=v.vec3f64.create(),r=t.mat3f64.create(),l=new y.TwoVectorPosition});