// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/compilerUtils ../../core/deprecate ../../core/Identifiable ../../core/Logger ../../core/urlUtils ../../core/accessorSupport/decorators ./MeshColor ../../views/support/screenshotUtils".split(" "),function(t,u,k,e,l,m,n,p,g,d,q,r){return function(h){function b(a){a=h.call(this,a)||this;a.type="image";m.deprecatedModule(p.getLogger("esri.geometry.support.ImageMeshColor"),"esri/geometry/support/ImageMeshColor",
{replacement:"esri/geometry/support/MeshTexture",version:"4.11"});return a}k(b,h);f=b;Object.defineProperty(b.prototype,"url",{get:function(){return this._get("url")||null},set:function(a){this._set("url",a);a&&this._set("data",null)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"data",{get:function(){return this._get("data")||null},set:function(a){this._set("data",a);a&&this._set("url",null)},enumerable:!0,configurable:!0});b.prototype.writeData=function(a,c,b,d){a instanceof
HTMLImageElement?a={type:"image-element",src:g.toJSON(a.src,d)}:a instanceof HTMLCanvasElement?(a=a.getContext("2d").getImageData(0,0,a.width,a.height),a={type:"canvas-element",imageData:this.encodeImageData(a)}):a={type:"image-data",imageData:this.encodeImageData(a)};c[b]=a};b.prototype.readData=function(a){switch(a.type){case "image-element":var c=new Image;c.src=a.src;return c;case "canvas-element":return a=this.decodeImageData(a.imageData),c=document.createElement("canvas"),c.width=a.width,c.height=
a.height,c.getContext("2d").putImageData(a,0,0),c;case "image-data":return this.decodeImageData(a.imageData);default:l.neverReached(a)}};Object.defineProperty(b.prototype,"transparent",{get:function(){var a=this.data,c=this.url;return a instanceof HTMLCanvasElement?this.imageDataContainsTransparent(a.getContext("2d").getImageData(0,0,a.width,a.height)):a instanceof ImageData?this.imageDataContainsTransparent(a):c&&(a=c.substr(c.length-4,4).toLowerCase(),c=c.substr(0,15).toLocaleLowerCase(),".png"===
a||"data:image/png;"===c)?!0:!1},set:function(a){null!=a?this._override("transparent",a):this._clearOverride("transparent")},enumerable:!0,configurable:!0});b.prototype.clone=function(){return new f({url:this.url,data:this.data})};b.prototype.encodeImageData=function(a){for(var c="",b=0;b<a.data.length;b++)c+=String.fromCharCode(a.data[b]);return{data:btoa(c),width:a.width,height:a.height}};b.prototype.decodeImageData=function(a){for(var c=atob(a.data),b=new Uint8ClampedArray(c.length),d=0;d<c.length;d++)b[d]=
c.charCodeAt(d);return r.wrapImageData(b,a.width,a.height)};b.prototype.imageDataContainsTransparent=function(a){for(var b=3;b<a.data.length;b+=4)if(255!==a.data[b])return!0;return!1};var f;e([d.property()],b.prototype,"type",void 0);e([d.property({type:String,json:{write:g.write}})],b.prototype,"url",null);e([d.property({json:{write:{overridePolicy:function(){return{enabled:!this.url}}}}}),d.property()],b.prototype,"data",null);e([d.writer("data")],b.prototype,"writeData",null);e([d.reader("data")],
b.prototype,"readData",null);e([d.property({type:Boolean,dependsOn:["data","url"],json:{write:{overridePolicy:function(){return{enabled:this._isOverridden("transparent")}}}}})],b.prototype,"transparent",null);return b=f=e([d.subclass("esri.geometry.support.ImageMeshColor")],b)}(d.declared(n.IdentifiableMixin(q.default)))});