// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/generatorHelper ../../core/tsSupport/awaiterHelper ../../core/tsSupport/assignHelper ../../core/maybe ../../core/libs/gl-matrix-2/mat3 ../../core/libs/gl-matrix-2/mat3f64 ./MeshMaterial ./MeshTexture ./meshUtils/georeference ../../views/3d/glTF/DefaultLoadingContext ../../views/3d/glTF/loader ../../views/3d/glTF/internal/indexUtils ../../views/3d/support/buffer/BufferView ../../views/3d/support/buffer/math ../../views/3d/support/buffer/utils ../../views/3d/webgl-engine/materials/DefaultMaterial".split(" "),
function(K,q,v,w,x,c,r,t,y,z,A,B,C,p,d,h,e,D){function E(a,d){var b=D.COLOR_GAMMA,b=[255*Math.pow(a.color[0],1/b),255*Math.pow(a.color[1],1/b),255*Math.pow(a.color[2],1/b),a.opacity],k=c.unwrap(c.applySome(a.textureColor,function(a){return d.get(a)})),e=c.unwrap(c.applySome(a.textureNormal,function(a){return d.get(a)})),f;a:{switch(a.alphaMode){case "OPAQUE":f="opaque";break a;case "MASK":f="mask";break a;case "BLEND":f="blend";break a}f=void 0}return new y({color:b,colorTexture:k,normalTexture:e,
alphaMode:f,alphaCutoff:a.alphaCutoff,doubleSided:a.doubleSided})}function H(a,F,b,k){var n=e.createBuffer(d.BufferViewVec3f64,b.attributes.position.count);h.vec3.transformMat4(n,b.attributes.position,b.transform);var f=c.applySome(b.attributes.normal,function(a){var g=e.createBuffer(d.BufferViewVec3f,a.count),c=r.mat3.normalFromMat4(t.mat3f64.create(),b.transform);h.vec3.transformMat3(g,a,c);return g.typedBuffer}),G=c.applySome(b.attributes.tangent,function(a){var g=e.createBuffer(d.BufferViewVec4f,
a.count),c=r.mat3.normalFromMat4(t.mat3f64.create(),b.transform);h.vec4.transformMat3(g,a,c);return g.typedBuffer}),l=c.applySome(b.attributes.texCoord0,function(a){var g=e.createBuffer(d.BufferViewVec2f,a.count);e.vec2.normalizeIntegerBuffer(g,a);return g.typedBuffer}),m=c.applySome(b.attributes.color,function(a){var b=e.createBuffer(d.BufferViewVec4u8,a.count);if(4===a.elementCount)a instanceof d.BufferViewVec4f?h.vec4.scale(b,a,255):a instanceof d.BufferViewVec4u8?e.vec4.copy(b,a):a instanceof
d.BufferViewVec4u16&&h.vec4.scale(b,a,1/255);else{e.vec4.fill(b,255,255,255,255);var c=new d.BufferViewVec3u8(b.buffer,0,4);a instanceof d.BufferViewVec3f?h.vec3.scale(c,a,255):a instanceof d.BufferViewVec3u8?e.vec3.copy(c,a):a instanceof d.BufferViewVec3u16&&h.vec3.scale(c,a,1/255)}return b.typedBuffer});k=A.georeference({position:n.typedBuffer,normal:c.unwrap(f),tangent:c.unwrap(G)},a,x({},k,{unit:"meters"}));n=I(b.indices||b.attributes.position.count,b.primitiveType);return{vertexAttributes:{position:k.position,
normal:k.normal,tangent:k.tangent,uv:c.unwrap(l),color:c.unwrap(m)},components:[{faces:n,material:F.get(b.material),trustSourceNormals:!0}],spatialReference:a.spatialReference}}function I(a,c){switch(c){case 4:return p.trianglesToTriangles(a);case 5:return p.triangleStripToTriangles(a);case 6:return p.triangleFanToTriangles(a)}}function J(a){return{horizontal:u(a.s),vertical:u(a.t)}}function u(a){switch(a){case 33071:return"clamp";case 33648:return"mirror";case 10497:return"repeat"}}Object.defineProperty(q,
"__esModule",{value:!0});q.loadGLTFMesh=function(a,c,b){return w(this,void 0,void 0,function(){var d,e,f,h,l,m;return v(this,function(g){switch(g.label){case 0:return d=new B.DefaultLoadingContext,[4,C.load(d,c,b)];case 1:return e=g.sent(),f=e.model,h=f.lods.shift(),l=new Map,m=new Map,f.textures.forEach(function(a,b){return l.set(b,new z({data:a.data,wrap:J(a.parameters.wrap)}))}),f.materials.forEach(function(a,b){return m.set(b,E(a,l))}),[2,h.parts.map(function(c){return H(a,m,c,b)})]}})})}});