// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../rasterRenderers ../../core/arrayUtils ../../core/lang ./RasterFunction ../../renderers/support/colorRampUtils ../../renderers/support/stretchRendererUtils".split(" "),function(E,m,t,y,u,l,v,z){function w(b){var a=b.Raster;return a&&"esri.layers.support.RasterFunction"===a.declaredClass?w(a.functionArguments):b}function A(b,a){var c=[],d=[],e=[],g=[],h=a.pixelType,f=(a=a.rasterAttributeTable)&&a.features,n=x(a);if(f&&Array.isArray(f)&&b.classBreakInfos)return b.classBreakInfos.forEach(function(a,
c){var e=a.symbol.color,d;e.a&&f.forEach(function(f){d=f.attributes[b.field];(d>=a.minValue&&d<a.maxValue||c===b.classBreakInfos.length-1&&d>=a.minValue)&&g.push([f.attributes[n],e.r,e.g,e.b])})}),h=h?r(g,h):g,a=new l,a.functionName="Colormap",a.functionArguments={},a.functionArguments.Colormap=h,a.variableName="Raster",a;b.classBreakInfos.forEach(function(a,b){var f=a.symbol&&a.symbol.color;f.a?(0===b?c.push(a.minValue,a.maxValue+1E-6):c.push(a.minValue+1E-6,a.maxValue+1E-6),d.push(b),g.push([b,
f.r,f.g,f.b])):e.push(a.minValue,a.maxValue)});h=h?r(g,h):g;a=new l;a.functionName="Remap";a.functionArguments={InputRanges:c,OutputValues:d,NoDataRanges:e};a.variableName="Raster";var k=new l;k.functionName="Colormap";k.functionArguments={Colormap:h,Raster:a};return k}function r(b,a){(a=B[String(a).toLowerCase()])&&b.push([Math.floor(a[0]-1),0,0,0],[Math.ceil(a[1]+1),0,0,0]);return b}function x(b){if(b)return(b=(b=b.fields)&&y.find(b,function(a){return a&&a.name&&"value"===a.name.toLowerCase()}))&&
b.name}function C(b,a){var c=[],d=a.pixelType,e=(a=a.rasterAttributeTable)&&a.features,g=x(a),h=!1;b.uniqueValueInfos&&b.uniqueValueInfos.forEach(function(a){var d=a.symbol.color;d.a&&(b.field!==g&&e?e&&e.forEach(function(e){String(e.attributes[b.field])===String(a.value)&&c.push([e.attributes[g],d.r,d.g,d.b])}):isNaN(a.value)?h=!0:c.push([a.value,d.r,d.g,d.b]))});if(h)return null;d=d&&0<c.length?r(c,d):c;a=new l;a.functionName="Colormap";a.functionArguments={};a.functionArguments.Colormap=d;a.variableName=
"Raster";return a}Object.defineProperty(m,"__esModule",{value:!0});var B={u1:[0,1],u2:[0,3],u4:[0,15],u8:[0,255],s8:[-128,127],u16:[0,65535],s16:[-32768,32767]},D={type:"multipart",colorRamps:[{fromColor:[0,0,255],toColor:[0,255,255]},{fromColor:[0,255,255],toColor:[255,255,0]},{fromColor:[255,255,0],toColor:[255,0,0]}]};m.isSupportedRendererType=function(b){b=b.type;return"raster-stretch"===b||"unique-value"===b||"class-breaks"===b};m.combineRenderingRules=function(b,a){if(!b||!a)return u.clone(b||
a);b=u.clone(b);"none"!==a.functionName.toLowerCase()&&(w(b.functionArguments).Raster=a);return b};m.convertRendererToRenderingRule=function(b,a){a=a||{};switch(b.type){case "raster-stretch":var c=new l;c.functionName="Stretch";var d=p[z.stretchTypeJSONDict.toJSON(b.stretchType)],e={StretchType:d,Statistics:b.statistics,DRA:b.dynamicRangeAdjustment,UseGamma:b.useGamma,Gamma:b.gamma,ComputeGamma:b.computeGamma};null!=b.outputMin&&(e.Min=b.outputMin);null!=b.outputMax&&(e.Max=b.outputMax);d===p.standardDeviation?
(e.NumberOfStandardDeviations=b.numberOfStandardDeviations,c.outputPixelType="u8"):d===p.percentClip?(e.MinPercent=b.minPercent,e.MaxPercent=b.maxPercent,c.outputPixelType="u8"):d===p.minMax?c.outputPixelType="u8":d===p.sigmoid&&(e.SigmoidStrengthLevel=b.sigmoidStrengthLevel);c.functionArguments=e;c.variableName="Raster";if(b.colorRamp){var d=b.colorRamp,e=new l,g=v.getColorRampName(d);e.functionArguments=g?{colorRamp:g}:!a.convertColorRampToColormap||"algorithmic"!==d.type&&"multipart"!==d.type?
{colorRamp:b.colorRamp.toJSON()}:{Colormap:v.convertColorRampToColormap(d,256)};e.variableName="Raster";e.functionName="Colormap";e.functionArguments.Raster=c;b=e}else b=c;return b;case "class-breaks":return A(b,a);case "unique-value":return C(b,a);case "raster-colormap":return(b=b.extractColormap())&&0!==b.length?(b=(a=a.pixelType)?r(b,a):b,a=new l,a.functionName="Colormap",a.functionArguments={},a.functionArguments.Colormap=b,b=a):b=void 0,b}};m.createDefaultRenderer=function(b,a){if(b){var c=b.attributeTable,
d=b.dataType,e=b.bandCount,g=b.pixelType,h=b.colormap,f=b.statistics,n=b.histograms;a&&0<a.length&&(f=f?a.map(function(a){return f[a]}):null,n=n?a.map(function(a){return n[a]}):null);var k;if(1===e&&h&&0<h.length)k=t.RasterColormapRenderer.createFromColormap(h);else if(1===e&&c){var l=c.fields.filter(function(a){return"red"===a.name.toLowerCase()})[0],m=c.fields.filter(function(a){return"green"===a.name.toLowerCase()})[0],p=c.fields.filter(function(a){return"blue"===a.name.toLowerCase()})[0],d=c.fields.filter(function(a){return"value"===
a.name})[0],q=c.fields.filter(function(a){return"classname"===a.name.toLowerCase()})[0];q||(q=c.fields.filter(function(a){return"string"===a.type})[0])||(q=d);l&&m&&p&&q&&(k=t.UniqueValueRenderer.fromJSON({field1:q.name,uniqueValueInfos:c.features.map(function(a){return{value:a.attributes[q.name],label:a.attributes[q.name],symbol:{color:[a.attributes[l.name],a.attributes[m.name],a.attributes[p.name],255],type:"esriSFS",style:"esriSFSSolid"}}})}))}else c=void 0,k=!1,e=a=b=void 0,"u8"===g&&"processed"===
d?(c="min-max",f=f||[{min:0,max:255},{min:0,max:255},{min:0,max:255}]):"u8"===g||"elevation"===d?(c="min-max",k=f?!1:!0):"scientific"===d?(c="min-max",k=f?!1:!0,b=D):n&&0<n.length?(c="percent-clip",e=a=.25):f?c="min-max":(c="percent-clip",k=!0),k=t.RasterStretchRenderer.fromJSON({stretchType:c,dra:k,colorRamp:b,min:0,max:255,statistics:k?null:f,histograms:k?null:n,maxPercent:a,minPercent:e});return k}};m.getDefaultBandCombination=function(b){var a,c,d,e,g,h,f=b.keyProperties&&b.keyProperties.BandProperties;
if(3<=b.bandCount){if(f&&f.length===b.bandCount){for(a=0;a<f.length;a++)f[a].BandName&&"red"===f[a].BandName.toLowerCase()&&(d=a),f[a].BandName&&"green"===f[a].BandName.toLowerCase()&&(e=a),f[a].BandName&&"blue"===f[a].BandName.toLowerCase()&&(g=a),f[a].BandName&&"nearinfrared"===f[a].BandName.toLowerCase()&&(h=a);void 0!==d&&void 0!==e&&void 0!==g?c=[d,e,g]:void 0!==d&&void 0!==e&&void 0!==h&&(c=[h,d,e])}!c&&3<b.bandCount&&(c=[0,1,2])}return c};var p={none:0,standardDeviation:3,histogramEqualization:4,
minMax:5,percentClip:6,sigmoid:9}});