// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/decorateHelper ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/generatorHelper ../../core/tsSupport/awaiterHelper ../../symbols ../../core/jsonMap ../../core/JSONSupport ../../core/lang ../../core/accessorSupport/decorators ./LabelExpressionInfo ./labelUtils ./types ../../symbols/support/defaults ../../symbols/support/jsonUtils".split(" "),function(B,C,e,r,D,E,l,t,u,m,b,n,v,w,x,f){function h(b){return b?"service"===b.origin?!1:!b.layer||
!w.isOfType(b.layer,"map-image"):!0}function q(b){return b?(b=y.exec(b))&&(b[1]||b[3])||null:null}var g=new t.default({esriServerPointLabelPlacementAboveCenter:"above-center",esriServerPointLabelPlacementAboveLeft:"above-left",esriServerPointLabelPlacementAboveRight:"above-right",esriServerPointLabelPlacementBelowCenter:"below-center",esriServerPointLabelPlacementBelowLeft:"below-left",esriServerPointLabelPlacementBelowRight:"below-right",esriServerPointLabelPlacementCenterCenter:"center-center",
esriServerPointLabelPlacementCenterLeft:"center-left",esriServerPointLabelPlacementCenterRight:"center-right",esriServerLinePlacementAboveAfter:"above-after",esriServerLinePlacementAboveAlong:"above-along",esriServerLinePlacementAboveBefore:"above-before",esriServerLinePlacementAboveStart:"above-start",esriServerLinePlacementAboveEnd:"above-end",esriServerLinePlacementBelowAfter:"below-after",esriServerLinePlacementBelowAlong:"below-along",esriServerLinePlacementBelowBefore:"below-before",esriServerLinePlacementBelowStart:"below-start",
esriServerLinePlacementBelowEnd:"below-end",esriServerLinePlacementCenterAfter:"center-after",esriServerLinePlacementCenterAlong:"center-along",esriServerLinePlacementCenterBefore:"center-before",esriServerLinePlacementCenterStart:"center-start",esriServerLinePlacementCenterEnd:"center-end",esriServerPolygonPlacementAlwaysHorizontal:"always-horizontal"},{ignoreUnknown:!0}),z=/^\s*\{([^}]+)\}\s*$/i,y=/^\s*(?:(?:\$feature\.(\w+))|(?:\$feature\[(["'])([\w\s]+)(\2)\]))\s*$/i;return function(p){function c(a){a=
p.call(this,a)||this;a.name=null;a.labelExpression=null;a.labelExpressionInfo=null;a.labelPlacement=null;a.maxScale=0;a.minScale=0;a.symbol=x.defaultTextSymbol2D;a.useCodedValues=void 0;a.where=null;return a}r(c,p);k=c;c.evaluateWhere=function(a,c){var b=function(a,c,b){switch(c){case "\x3d":return a==b?!0:!1;case "\x3c\x3e":return a!=b?!0:!1;case "\x3e":return a>b?!0:!1;case "\x3e\x3d":return a>=b?!0:!1;case "\x3c":return a<b?!0:!1;case "\x3c\x3d":return a<=b?!0:!1}return!1};try{if(null==a)return!0;
var d=a.split(" ");if(3===d.length)return b(c[d[0]],d[1],d[2]);if(7===d.length){var e=b(c[d[0]],d[1],d[2]),A=d[3],f=b(c[d[4]],d[5],d[6]);switch(A){case "AND":return e&&f;case "OR":return e||f}}return!1}catch(F){console.log("Error.: can't parse \x3d "+a)}};c.prototype.readLabelExpression=function(a,b){b=b.labelExpressionInfo;if(!b||!b.value&&!b.expression)return a};c.prototype.writeLabelExpression=function(a,b,c,d){this.labelExpressionInfo&&h(d)&&(null!=this.labelExpressionInfo.value?a=this.labelExpressionInfo.value.replace(/\{/g,
"[").replace(/\}/g,"]"):null!=this.labelExpressionInfo.expression&&(d=q(this.labelExpressionInfo.expression))&&(a="["+d+"]"));null!=a&&(b[c]=a)};c.prototype.writeLabelExpressionInfo=function(a,b,c,d){if(null==a&&null!=this.labelExpression&&h(d))a=new n({expression:this.getLabelExpressionArcade()});else if(!a)return;a=a.toJSON(d);a.expression&&(b[c]=a)};c.prototype.writeMaxScale=function(a,b){if(a||this.minScale)b.maxScale=a};c.prototype.writeMinScale=function(a,b){if(a||this.maxScale)b.minScale=a};
c.prototype.getLabelExpression=function(){var a={expression:"",type:"none"};this.labelExpressionInfo?this.labelExpressionInfo.value?(a.expression=this.labelExpressionInfo.value,a.type="conventional"):this.labelExpressionInfo.expression&&(a.expression=this.labelExpressionInfo.expression,a.type="arcade"):null!=this.labelExpression&&(a.expression=this.labelExpression.replace(/\[/g,"{").replace(/\]/g,"}"),a.type="conventional");return a};c.prototype.getLabelExpressionArcade=function(){var a=this.getLabelExpression();
if(!a)return null;switch(a.type){case "conventional":return v.convertTemplatedStringToArcade(a.expression);case "arcade":return a.expression}return null};c.prototype.getLabelExpressionSingleField=function(){var a=this.getLabelExpression();if(!a)return null;switch(a.type){case "conventional":return(a=a.expression.match(z))&&a[1].trim()||null;case "arcade":return q(a.expression)}return null};c.prototype.clone=function(){return new k({labelExpression:this.labelExpression,labelExpressionInfo:m.clone(this.labelExpressionInfo),
labelPlacement:this.labelPlacement,maxScale:this.maxScale,minScale:this.minScale,name:this.name,symbol:m.clone(this.symbol),where:this.where,useCodedValues:this.useCodedValues})};var k;e([b.property({type:String,json:{write:!0}})],c.prototype,"name",void 0);e([b.property({type:String,json:{write:{allowNull:!0}}})],c.prototype,"labelExpression",void 0);e([b.reader("labelExpression")],c.prototype,"readLabelExpression",null);e([b.writer("labelExpression")],c.prototype,"writeLabelExpression",null);e([b.property({type:n,
json:{write:{overridePolicy:function(a,b,c){return h(c)?{allowNull:!0}:{enabled:!1}}}}})],c.prototype,"labelExpressionInfo",void 0);e([b.writer("labelExpressionInfo")],c.prototype,"writeLabelExpressionInfo",null);e([b.property({type:g.apiValues,json:{type:g.jsonValues,read:g.read,write:g.write}})],c.prototype,"labelPlacement",void 0);e([b.property({type:Number})],c.prototype,"maxScale",void 0);e([b.writer("maxScale")],c.prototype,"writeMaxScale",null);e([b.property({type:Number})],c.prototype,"minScale",
void 0);e([b.writer("minScale")],c.prototype,"writeMinScale",null);e([b.property({types:l.symbolTypesLabel,json:{origins:{"web-scene":{types:l.symbolTypesLabel3D,read:f.read,write:f.writeTarget,default:null}},read:f.read,write:f.writeTarget,default:null}})],c.prototype,"symbol",void 0);e([b.property({type:Boolean,json:{write:!0}})],c.prototype,"useCodedValues",void 0);e([b.property({type:String,json:{write:!0}})],c.prototype,"where",void 0);return c=k=e([b.subclass("esri.layers.support.LabelClass")],
c)}(b.declared(u.JSONSupport))});