// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define({"esri/widgets/Search/nls/Search":{widgetLabel:"Potra\u017ei",searchButtonTitle:"Pretra\u017ei",clearButtonTitle:"O\u010disti pretragu",placeholder:"Prona\u0111i adresu ili mjesto",searchIn:"Tra\u017ei u",all:"Sve",allPlaceholder:"Prona\u0111i adresu ili mjesto",emptyValue:"Unesite termin za pretra\u017eivanje.",untitledResult:"Neimenovano",untitledSource:"Neimenovani izvor",noResults:"Nema rezultata",noResultsFound:"Nema prona\u0111enih rezultata.",noResultsFoundForValue:"Nema prona\u0111enih rezultata za {value}.",
showMoreResults:"Prika\u017ei jo\u0161 rezultata",hideMoreResults:"Sakrij",searchResult:"Rezultat pretra\u017eivanja",moreResultsHeader:"Vi\u0161e rezultata",useCurrentLocation:"Upotrijebi trenuta\u010dnu lokaciju",_localized:{}},"dojo/cldr/nls/gregorian":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"ned pon uto sri \u010det pet sub".split(" "),"months-format-narrow":"1. 2. 3. 4. 5. 6. 7. 8. 9. 10. 11. 12.".split(" "),"field-second-relative+0":"sada","quarters-standAlone-narrow":["1.",
"2.","3.","4."],"field-weekday":"Dan u tjednu","dateFormatItem-yQQQ":"QQQ y.","dateFormatItem-yMEd":"E, dd.MM.y.","field-wed-relative+0":"ova srijeda","field-wed-relative+1":"sljede\u0107a srijeda","dateFormatItem-GyMMMEd":"E, d. MMM y. G","dateFormatItem-MMMEd":"E, d. MMM",eraNarrow:["pr.n.e.","AD"],"field-tue-relative+-1":"pro\u0161li utorak","days-format-short":"ned pon uto sri \u010det pet sub".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d. MMMM y.","field-fri-relative+-1":"pro\u0161li petak",
"field-wed-relative+-1":"pro\u0161la srijeda","months-format-wide":"sije\u010dnja velja\u010de o\u017eujka travnja svibnja lipnja srpnja kolovoza rujna listopada studenoga prosinca".split(" "),"dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE, d. MMMM y.","field-thu-relative+-1":"pro\u0161li \u010detvrtak","dateFormatItem-Md":"dd.MM.","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"podne",
"dateFormatItem-yMd":"dd.MM.y.","field-era":"Era","dateFormatItem-yM":"MM.y.","months-standAlone-wide":"sije\u010danj velja\u010da o\u017eujak travanj svibanj lipanj srpanj kolovoz rujan listopad studeni prosinac".split(" "),"timeFormat-short":"HH:mm","quarters-format-wide":["1. kvartal","2. kvartal","3. kvartal","4. kvartal"],"dateFormatItem-yQQQQ":"QQQQ y.","timeFormat-long":"HH:mm:ss z","field-year":"Godina","dateFormatItem-yMMM":"LLL y.","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Sat",
"months-format-abbr":"sij velj o\u017eu tra svi lip srp kol ruj lis stu pro".split(" "),"field-sat-relative+0":"ova subota","field-sat-relative+1":"sljede\u0107a subota","timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"danas","field-thu-relative+0":"ovaj \u010detvrtak","field-day-relative+1":"sutra","field-thu-relative+1":"sljede\u0107i \u010detvrtak","dateFormatItem-GyMMMd":"d. MMM y. G","dateFormatItem-H":"HH","months-standAlone-abbr":"sij velj o\u017eu tra svi lip srp kol ruj lis stu pro".split(" "),
"quarters-format-abbr":["1kv","2kv","3kv","4kv"],"quarters-standAlone-wide":["1. kvartal","2. kvartal","3. kvartal","4. kvartal"],"dateFormatItem-Gy":"y. G","dateFormatItem-M":"L.","days-standAlone-wide":"nedjelja ponedjeljak utorak srijeda \u010detvrtak petak subota".split(" "),"dayPeriods-format-abbr-noon":"podne","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"ova nedjelja","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"sljede\u0107a nedjelja","quarters-standAlone-abbr":["1kv","2kv",
"3kv","4kv"],eraAbbr:["pr. Kr.","p. Kr."],"field-minute":"Minuta","field-dayperiod":"AM/PM","days-standAlone-abbr":"ned pon uto sri \u010det pet sub".split(" "),"dateFormatItem-d":"d.","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1.","2.","3.","4."],"field-day-relative+-1":"ju\u010der","dateTimeFormat-long":"{1} 'u' {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","dateFormatItem-MMMd":"d. MMM","dateFormatItem-MEd":"E, dd.MM.","dateTimeFormat-full":"{1} 'u' {0}","field-fri-relative+0":"ovaj petak",
"field-fri-relative+1":"sljede\u0107i petak","field-day":"Dan","days-format-wide":"nedjelja ponedjeljak utorak srijeda \u010detvrtak petak subota".split(" "),"field-zone":"Vremenska zona","months-standAlone-narrow":"1. 2. 3. 4. 5. 6. 7. 8. 9. 10. 11. 12.".split(" "),"dateFormatItem-y":"y.","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"pro\u0161le godine","field-month-relative+-1":"pro\u0161li mjesec","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"hh:mm a",
"dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"ned pon uto sri \u010det pet sub".split(" "),eraNames:["Prije Krista","Poslije Krista"],"dateFormatItem-yMMMd":"d. MMM y.","days-format-narrow":"NPUS\u010cPS".split(""),"field-month":"Mjesec","days-standAlone-narrow":"npus\u010dps".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"ovaj utorak","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","field-tue-relative+1":"sljede\u0107i utorak",
"dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"ovaj ponedjeljak","field-mon-relative+1":"sljede\u0107i ponedjeljak","dateFormat-short":"dd.MM.y.","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"P","field-second":"Sekunda","field-sat-relative+-1":"pro\u0161la subota","dateFormatItem-yMMMEd":"E, d. MMM y.",
"field-sun-relative+-1":"pro\u0161la nedjelja","field-month-relative+0":"ovaj mjesec","field-month-relative+1":"sljede\u0107i mjesec","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E, d.","field-week":"Tjedan","dateFormat-medium":"d. MMM y.","field-week-relative+-1":"pro\u0161li tjedan","field-year-relative+0":"ove godine","field-year-relative+1":"sljede\u0107e godine","dayPeriods-format-narrow-pm":"p","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"hh:mm:ss a",
"dateFormatItem-GyMMM":"LLL y. G","field-mon-relative+-1":"pro\u0161li ponedjeljak","field-week-relative+0":"ovaj tjedan","field-week-relative+1":"sljede\u0107i tjedan","dateFormatItem-yMM":"MM. y.","dateFormatItem-MMdd":"dd. MM.","dayPeriods-format-narrow-morning":"prijepodne","field-day-relative+2":"prekosutra","dayPeriods-format-narrow-evening":"nave\u010der","dateFormatItem-MMMMd":"d. MMMM","field-day-relative+-2":"prekju\u010der","dateFormatItem-yMMMM":"LLLL y.","dayPeriods-format-narrow-night":"no\u0107u",
"dayPeriods-format-narrow-earlyMorning":"ujutro","dateFormatItem-MMMMEd":"E, d. MMMM","dayPeriods-format-narrow-afternoon":"popodne",_localized:{}},"esri/widgets/Attribution/nls/Attribution":{widgetLabel:"Atribucija",_localized:{}},"esri/widgets/Compass/nls/Compass":{widgetLabel:"Kompas",reset:"Ponovno postavi orijentaciju kompasa",_localized:{}},"esri/widgets/NavigationToggle/nls/NavigationToggle":{widgetLabel:"Preklapanje navigacije",toggle:"Prebacuj se izme\u0111u kretanja po slici ili rotacije u 3D",
_localized:{}},"esri/widgets/Zoom/nls/Zoom":{widgetLabel:"Pove\u0107aj",zoomIn:"Pove\u0107aj",zoomOut:"Smanji",_localized:{}}});