// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/assignHelper ../../../../../core/tsSupport/awaiterHelper ../../../../../core/tsSupport/generatorHelper ../../../../../core/arrayUtils ../../../../../core/mathUtils ../../../../../core/promiseUtils ../../../../../core/requireUtils ../../../../../core/typedArrayUtil ../../../../../core/workers ../../../../../core/libs/gl-matrix-2/mat3 ../../../../../core/libs/gl-matrix-2/mat3f64 ../../../../../core/libs/gl-matrix-2/mat4 ../../../../../core/libs/gl-matrix-2/mat4f64 ../../../../../core/libs/gl-matrix-2/vec3 ../../../../../core/libs/gl-matrix-2/vec3f64 ../../../support/buffer/utils ../../core/shaderLibrary/attributes/VertexPosition.glsl ../../core/util/TwoVectorPosition ../GridLocalOriginFactory ../localOriginHelper ../LocalOriginManager ../Object3D ../PreinterleavedGeometryData ../TextureBackedBuffer/BufferManager ./bufferLayouts ./edgeBufferWriters ./EdgeProcessingWorker ./EdgeRenderer ./strokes ./util ../../../../webgl/BufferObject ../../../../webgl/VertexArrayObject module".split(" "),
function(S,J,K,t,B,T,L,E,U,V,W,F,M,X,N,C,G,Y,Z,aa,ba,ca,da,O,P,ea,x,Q,fa,z,ga,u,H,R,ha){Object.defineProperty(J,"__esModule",{value:!0});K=function(){function d(a,c,b){this.rctx=a;this.techniqueRepository=c;this.callbacks=b;this.profilingCallback=null;this.perObjectData=new Map;this.renderers=new Map;this.localOrigins=new da.LocalOriginManager(new ba);this.gpuMemoryUsage=this.numberOfRenderedEdges=0;this.worker=new fa;this.workerThread=null;this.destroyed=!1;this.tmpModelPosition=G.vec3f64.create();
this.tmpCameraPosition=G.vec3f64.create();this.componentColorManager=new ea.BufferManager(this.rctx,2)}d.prototype.initialize=function(){var a=this;W.open(U.getAbsMid("./EdgeProcessingWorker",S,ha)).then(function(b){a.destroyed?b.close():a.workerThread=b});for(var c=x.VertexLayout.createBuffer(4),b=0;4>b;b++)c.sideness.set(b,0,0===b||3===b?0:1),c.sideness.set(b,1,0===b||1===b?0:1);this.verticesBufferObject=H.createVertex(this.rctx,35044,c.buffer)};d.prototype.destroy=function(){this.destroyed||(this.workerThread&&
(this.workerThread.close(),this.workerThread=null),this.verticesBufferObject&&(this.verticesBufferObject.dispose(),this.verticesBufferObject=null),this.destroyed=!0)};d.prototype.getUsedMemory=function(){return this.gpuMemoryUsage};Object.defineProperty(d.prototype,"numberOfRenderedPrimitives",{get:function(){return this.numberOfRenderedEdges},enumerable:!0,configurable:!0});d.prototype.shouldRender=function(){return 0<this.renderers.size};d.prototype.addComponentObject=function(a,c,b,e,f,k,p,d){return t(this,
void 0,void 0,function(){var g,h,m;return B(this,function(l){switch(l.label){case 0:if(this.hasObject(a))return[2];g=[];m={loaded:E.create(function(a){return h=a}),renderables:[],center:b};this.perObjectData.set(a,m);g.push(this.addComponentGeometry(a,c,m,e,f,k,p,d));return[4,E.all(g)];case 1:return l.sent(),this.callbacks.setNeedsRender(),h(),[2]}})})};d.prototype.addObject=function(a,c,b,e,f){return t(this,void 0,void 0,function(){var k,p,d,g,h,m,l;return B(this,function(n){switch(n.label){case 0:if(this.hasObject(a))return[2];
k=[];d={loaded:E.create(function(a){return p=a}),renderables:[]};this.perObjectData.set(a,d);if(f&&f.mergeGeometries&&1<a.geometries.length&&this.canMergeGeometries(a))k.push(this.addObjectMergedGeometries(a,d,c,b));else for(g=0;g<a.geometries.length;g++)if(h=a.geometries[g],m=a.geometryRecords[g],l=m.material,l.supportsEdges){if(h.data instanceof P)throw Error("Deprecated");k.push(this.addGeometryNonPreinterleaved(a,d,h.data,m,c[0],b,e))}return[4,E.all(k)];case 1:return n.sent(),this.callbacks.setNeedsRender(),
p(),[2]}})})};d.prototype.hasObject=function(a){return this.perObjectData.has(a)};d.prototype.updateAllComponentOpacities=function(a,c){return t(this,void 0,void 0,function(){var b,e,f=this;return B(this,function(k){switch(k.label){case 0:return b=c instanceof Array?function(a){return c[a]}:function(){return c},[4,this.getObjectEntry(a)];case 1:return e=k.sent(),e.renderables.forEach(function(a){for(var c=a.components.meta.length,e=0;e<c;e++){var k=b(e),d=a.components.meta[e],l=d.index;d.material.opacity=
k;a.components.buffer.textureBuffer.setDataElement(l,1,3,255*k)}f.updateTransparency(a)}),this.callbacks.setNeedsRender(),[2]}})})};d.prototype.updateAllComponentMaterials=function(a,c,b,e){return t(this,void 0,void 0,function(){var f,k,d,q,g,h=this;return B(this,function(m){switch(m.label){case 0:return f=a instanceof O,k=!!b.slicePlaneEnabled,d=u.determineRendererType(c),q=z.EdgeRenderer.getKey(d,k,f),[4,this.getObjectEntry(a)];case 1:return g=m.sent(),g.renderables.forEach(function(b){if(q!==b.rendererKey){var f=
h.renderers.get(b.rendererKey),g=h.acquireRenderer(d,k,a instanceof O);f.removeRenderable(b);f.refCount.decrement();b.rendererKey=q;g.addRenderable(b)}for(f=0;f<c.length;f++)b.components.meta[f].material=c[f];e&&h.updateComponentBuffer(b.components);h.updateTransparency(b)}),this.callbacks.setNeedsRender(),[2]}})})};d.prototype.updateObjectVisibility=function(a,c){return t(this,void 0,void 0,function(){var b;return B(this,function(e){switch(e.label){case 0:return[4,this.getObjectEntry(a)];case 1:return b=
e.sent(),b.renderables.forEach(function(a){a.visible=c}),this.callbacks.setNeedsRender(),[2]}})})};d.prototype.removeObject=function(a){var c=this,b=this.perObjectData.get(a);b&&(this.perObjectData.delete(a),b.loaded.then(function(){b.renderables.forEach(function(a){c.removeRenderable(a)});c.callbacks.setNeedsRender()}))};d.prototype.getObjectEntry=function(a){return t(this,void 0,void 0,function(){var c;return B(this,function(b){switch(b.label){case 0:c=this.perObjectData.get(a);if(!c)throw"no object";
return[4,c.loaded];case 1:return b.sent(),[2,c]}})})};d.prototype.removeAll=function(){var a=this;this.perObjectData.forEach(function(c,b){a.removeObject(b)})};d.prototype.render=function(a,c){var b=this;this.localOrigins.updateViewMatrices(a.view);var e=a.viewInvTransp,f=G.vec3f64.create(),k=new aa.TwoVectorPosition,d=new Z.VertexPosition.ViewProjectionTransform,q=M.mat3f64.create();C.vec3.set(f,e[3],e[7],e[11]);k.set(f);C.vec3.copy(d.worldFromView_TH,k.high);C.vec3.copy(d.worldFromView_TL,k.low);
F.mat3.fromMat4(d.viewFromCameraRelative_RS,a.view);X.mat4.copy(d.projFromView,a.proj);e=M.mat3f64.create();F.mat3.transpose(e,d.viewFromCameraRelative_RS);F.mat3.invert(q,e);this.renderers.forEach(function(a){0===a.refCount.value&&(b.renderers.delete(a.key),a.dispose())});this.componentColorManager.garbageCollect();this.componentColorManager.updateTextures();var g=0,h=0;this.renderers.forEach(function(a){return a.forEachRenderable(function(a){g+=a.statistics.averageEdgeLength;h++},c)});if(0!==h){var e=
a.view,f=40*g/h,k=u.estimateLengthAtDistance(a.viewport[3],a.fovY,1,3.5*a.pixelRatio),m={distanceFalloffFactor:f,minimumEdgeLength:k,transparency:c,viewProjectionTransform:d,transformNormal_ViewFromGlobal:q};this.updateObjectCameraDistances(a);this.numberOfRenderedEdges=0;this.renderers.forEach(function(c){b.renderRegularEdges(c,a,m);b.renderSilhouetteEdges(c,a,m)});a.view=e}};d.prototype.updateTransparency=function(a){var c=u.determineEdgeTransparency(a.components.meta),b=u.determineObjectTransparency(a.components.meta);
if(c!==a.edgeTransparency||b!==a.objectTransparency)a.edgeTransparency=c,a.objectTransparency=b,this.renderers.get(a.rendererKey).setRenderablesDirty()};d.prototype.computeModelTransformWithLocalOrigin=function(a,c,b){a.getCombinedStaticTransformation(c,b);c.origin?this.localOrigins.register(c.origin):(a=C.vec3.set(this.tmpModelPosition,b[12],b[13],b[14]),c.origin=this.localOrigins.acquire(a));ca.applyToModelMatrix(c.origin.vec3,b);return b};d.prototype.updateComponentBuffer=function(a){var c=a.meta;
a=a.buffer;for(var b=0;b<c.length;b++){var e=c[b].material,f=c[b].index,d=L.clamp(Math.round(e.size*z.LINE_WIDTH_FRACTION_FACTOR),0,255),p=L.clamp(e.extensionLength,-z.EXTENSION_LENGTH_OFFSET,255-z.EXTENSION_LENGTH_OFFSET)+z.EXTENSION_LENGTH_OFFSET,q="solid"===e.type?0:1,g=255*e.opacity,e=e.color;a.textureBuffer.setData(f,0,255*e[0],255*e[1],255*e[2],255*e[3]);a.textureBuffer.setData(f,1,d,p,q,g)}};d.prototype.createComponentBuffers=function(a){for(var c=[],b=this.componentColorManager.getBuffer(a.length),
e=0;e<a.length;e++){var f=a[e],d=b.acquireIndex();c.push({index:d,material:f})}a={meta:c,buffer:b};this.updateComponentBuffer(a);return a};d.prototype.extractEdges=function(a,c,b,e,f){return this.worker.process({data:c,originalIndices:f,writerSettings:a,skipDeduplicate:b},e?null:this.workerThread)};d.prototype.createEdgeResources=function(a){var c={};if(0<a.regular.lodInfo.lengths.length){var b=new R(this.rctx,x.EdgeShaderAttributeLocations,{vertices:x.glVertexLayout,instances:Q.RegularEdgeBufferWriter.glLayout},
{vertices:this.verticesBufferObject,instances:H.createVertex(this.rctx,35044,a.regular.instancesData.buffer)});c.regular={vao:b,lod:a.regular.lodInfo}}0<a.silhouette.lodInfo.lengths.length&&(b=new R(this.rctx,x.EdgeShaderAttributeLocations,{vertices:x.glVertexLayout,instances:Q.SilhouetteEdgeBufferWriter.glLayout},{vertices:this.verticesBufferObject,instances:H.createVertex(this.rctx,35044,a.silhouette.instancesData.buffer)}),c.silhouette={vao:b,lod:a.silhouette.lodInfo});return c};d.prototype.disposeEdgeResources=
function(a){a.regular&&(a.regular.vao.vertexBuffers.instances.dispose(),a.regular.vao.dispose(!1),a.regular.vao=null);a.silhouette&&(a.silhouette.vao.vertexBuffers.instances.dispose(),a.silhouette.vao.dispose(!1),a.silhouette.vao=null)};d.prototype.addGeometryNonPreinterleaved=function(a,c,b,e,f,d,p){return t(this,void 0,void 0,function(){var k,g,h,m;return B(this,function(l){k=b.getAttribute("position");g=this.computeModelTransformWithLocalOrigin(a,e,N.mat4f64.create());h=e.origin;m={position:k,
indices:b.getIndices("position"),modelTransform:g,origin:h};return[2,this.addNonPreinterleaved(c,m,f,d,p)]})})};d.prototype.addNonPreinterleaved=function(a,c,b,e,f){void 0===f&&(f=!1);return t(this,void 0,void 0,function(){var d,p,q,g,h,m,l,n,D,v,A,y,r,w,I;return B(this,function(k){switch(k.label){case 0:d=this.acquireRenderer(b.type,e.slicePlaneEnabled||!1);p=c.modelTransform;q=c.origin;g=c.indices;h=c.position;m=h.data.length/h.strideIdx;l=x.EdgeInputBufferLayout.createBuffer(m);for(n=0;n<m;n++)l.position.set(n,
0,h.data[h.offsetIdx+n*h.strideIdx+0]),l.position.set(n,1,h.data[h.offsetIdx+n*h.strideIdx+1]),l.position.set(n,2,h.data[h.offsetIdx+n*h.strideIdx+2]);D=this.createComponentBuffers([b]);u.fillComponenBufferIndices(D.meta,[0,l.componentIndex.count],l.componentIndex);return[4,this.extractEdges(d.writerSettings,l,!1,f,g)];case 1:return v=k.sent(),A=this.createEdgeResources(v),y=A.regular,r=A.silhouette,w=(y?y.vao.size:0)+(r?r.vao.size:0),I={regular:y,silhouette:r,transform:{modelMatrix:p,origin:q},statistics:{gpuMemoryUsage:w,
averageEdgeLength:v.averageEdgeLength},components:D,visible:!0,edgeTransparency:u.determineEdgeTransparency(D.meta),objectTransparency:u.determineObjectTransparency(D.meta),distanceToCamera:0,rendererKey:d.key},a.renderables.push(I),d.addRenderable(I),this.gpuMemoryUsage+=w,[2]}})})};d.prototype.addComponentGeometry=function(a,c,b,e,f,d,p,q){return t(this,void 0,void 0,function(){var a,h,k,l,n,D,v,A,y,r,w;return B(this,function(g){switch(g.label){case 0:return a=u.determineRendererType(p),h=this.acquireRenderer(a,
q.slicePlaneEnabled||!1,!1),k=x.EdgeInputBufferLayout.createBuffer(e.count),Y.vec3.copy(k.position,e),l=this.createComponentBuffers(p),u.fillComponenBufferIndices(l.meta,d,k.componentIndex,f),n=h.writerSettings,[4,this.extractEdges(n,k,!0,!1,f)];case 1:return D=g.sent(),v=this.createEdgeResources(D),A=v.regular,y=v.silhouette,r=(A?A.vao.size:0)+(y?y.vao.size:0),w={regular:A,silhouette:y,transform:c,statistics:{gpuMemoryUsage:r,averageEdgeLength:D.averageEdgeLength},components:l,visible:!0,edgeTransparency:u.determineEdgeTransparency(l.meta),
objectTransparency:u.determineObjectTransparency(l.meta),distanceToCamera:0,rendererKey:h.key},b.renderables.push(w),h.addRenderable(w),this.gpuMemoryUsage+=r,[2]}})})};d.prototype.canMergeGeometries=function(a){for(var c=null,b=null,e=0;e<a.geometries.length;e++){var f=a.geometryRecords[e];if(f.material.supportsEdges){if(a.geometries[e].data instanceof P)return!1;if(!c)c=f.transformation;else if(!T.equals(c,f.transformation))return!1;if(!b&&f.origin)b=f;else if(b&&f.origin&&b.origin.id!==f.origin.id)return!1}}return!0};
d.prototype.addObjectMergedGeometries=function(a,c,b,e){return t(this,void 0,void 0,function(){var f,d,p,q,g,h,m,l,n,u,v,A,y,r,w,t,x,z,C,E,F;return B(this,function(k){switch(k.label){case 0:f=new Map;d=0;q=p=null;for(g=0;g<a.geometries.length;g++)if(h=a.geometries[g],m=a.geometryRecords[g],l=m.material,l.supportsEdges&&(!q&&m.origin&&(q=m),n=h.data.getIndices("position"),d+=n?n.length:0,n&&null==p||p===Uint16Array))p=V.isUint16Array(n)?Uint16Array:Uint32Array;u=d?new p(d):null;v=[];for(g=A=0;g<a.geometries.length;g++)if(h=
a.geometries[g],y=a.geometryRecords[g],l=y.material,l.supportsEdges){r=h.data.getAttribute("position");n=h.data.getIndices("position");w=f.get(r.data);if(null==w){w=v.length/3;for(t=r.offsetIdx;t<r.data.length;t+=r.strideIdx)v.push(r.data[t+0]),v.push(r.data[t+1]),v.push(r.data[t+2]);f.set(r.data,w)}if(n)for(x=0;x<n.length;x++)u[A++]=w+n[x]}z=q||a.geometryRecords[0];C=this.computeModelTransformWithLocalOrigin(a,z,N.mat4f64.create());E=z.origin;for(g=0;g<a.geometryRecords.length;g++)a.geometryRecords[g].origin=
E;F={position:{data:v,offsetIdx:0,strideIdx:3},indices:u,modelTransform:C,origin:E};return[4,this.addNonPreinterleaved(c,F,b[0],e)];case 1:return k.sent(),[2]}})})};d.prototype.acquireRenderer=function(a,c,b){void 0===b&&(b=!0);var e=z.EdgeRenderer.getKey(a,c,b),f=this.renderers.get(e);this.strokesTexture||(this.strokesTexture=ga.generateStrokesTexture(this.rctx));f||(f=new z.EdgeRenderer(this.rctx,this.techniqueRepository,{type:a,slicePlaneEnabled:c,strokesTexture:this.strokesTexture,legacy:b}),
this.renderers.set(e,f));f.refCount.increment();return f};d.prototype.removeRenderable=function(a){var c=this.renderers.get(a.rendererKey);c.removeRenderable(a);c.refCount.decrement();this.disposeEdgeResources(a);"origin"in a.transform&&this.localOrigins.release(a.transform.origin);this.gpuMemoryUsage-=a.statistics.gpuMemoryUsage;for(var c=0,b=a.components.meta;c<b.length;c++)a.components.buffer.releaseIndex(b[c].index)};d.prototype.updateObjectCameraDistances=function(a){var c=this;a=a.viewInvTransp;
C.vec3.set(this.tmpCameraPosition,a[3],a[7],a[11]);this.perObjectData.forEach(function(a,e){e="getCenter"in e?e.getCenter():a.center;var b=C.vec3.distance(e,c.tmpCameraPosition);a.renderables.forEach(function(a){return a.distanceToCamera=b})})};d.prototype.renderRegularEdges=function(a,c,b){var e=this;a.bindRegularEdges(c,b);a.forEachRenderable(function(d){if(d.visible&&d.regular){var f=u.computeEdgeCount(d.regular.lod.lengths,d.distanceToCamera,b);"origin"in d.transform&&(c.view=e.localOrigins.getViewMatrix(d.transform.origin));
a.renderRegularEdges(d,c,f);e.numberOfRenderedEdges+=f}},b.transparency)};d.prototype.renderSilhouetteEdges=function(a,c,b){var d=this;a.bindSilhouetteEdges(c,b);a.forEachRenderable(function(e){if(e.visible&&e.silhouette){var f=u.computeEdgeCount(e.silhouette.lod.lengths,e.distanceToCamera,b);"origin"in e.transform&&(c.view=d.localOrigins.getViewMatrix(e.transform.origin));a.renderSilhouetteEdges(e,c,f);d.numberOfRenderedEdges+=f}},b.transparency)};return d}();J.EdgeView=K});