// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
require({cache:{"esri/geometry/support/meshUtils/deduplicate":function(){define(["require","exports","../../../core/mathUtils"],function(q,a,l){function d(a,d,k){var n=a.byteLength/(4*d),r=new Uint32Array(a,0,n*d);a=new Uint32Array(n);var c=k&&k.minReduction||0,b=k&&k.originalIndices||null,e=k&&k.componentOffsets||null,f=0;if(e)for(k=0;k<e.length-1;k++){var h=e[k+1]-e[k];h>f&&(f=h)}else f=n;h=Math.floor(1.1*f)+1;if(null==g||g.length<2*h)g=new Uint32Array(l.nextHighestPowerOfTwo(2*h));for(k=0;k<2*
h;k++)g[k]=0;var f=0,p=0!==c?Math.ceil(7.84*1.96/(c*c)*c*(1-c)):n,w=1,t=e?e[1]:n;for(k=0;k<n;k++){if(k===p){var v=1-f/k;if(v+1.96*Math.sqrt(v*(1-v)/k)<c)return null;p*=2}if(k===t){for(t=0;t<2*h;t++)g[t]=0;t=e[++w]}for(var v=k*d,m,x=m=0;x<d;x++)m=r[v+x]+m|0,m=m+(m<<11)+(m>>>2)|0;m>>>=0;for(var x=m%h,I=f;0!==g[2*x+1];){if(g[2*x]===m){var q=g[2*x+1]-1,u=q*d;a:{for(var B=0;B<d;B++)if(r[v+B]!==r[u+B]){u=!1;break a}u=!0}if(u){I=a[q];break}}x++;x>=h&&(x-=h)}I===f&&(g[2*x]=m,g[2*x+1]=k+1,f++);a[k]=I}if(0!==
c&&1-f/n<c)return null;c=new Uint32Array(d*f);for(k=f=0;k<n;k++)if(a[k]===f){e=r;h=k*d;p=c;w=f*d;t=d;for(v=0;v<t;v++)p[w+v]=e[h+v];f++}if(b){d=new Uint32Array(b.length);for(k=0;k<d.length;k++)d[k]=a[b[k]];a=d}return{buffer:c.buffer,indices:a,uniqueCount:f}}Object.defineProperty(a,"__esModule",{value:!0});a.deduplicate=d;var g=null;a.default=d})},"esri/views/3d/support/meshProcessing":function(){define(["require","exports"],function(q,a){Object.defineProperty(a,"__esModule",{value:!0});a.computeNeighbors=
function(a,d){for(var g=a.length/3,p=new Uint32Array(d+1),m=new Uint32Array(d+1),k=function(b,e){b<e?p[b+1]++:m[e+1]++},n=0;n<g;n++){var r=a[3*n],c=a[3*n+1],b=a[3*n+2];k(r,c);k(c,b);k(b,r)}for(n=c=r=0;n<d;n++)b=p[n+1],k=m[n+1],p[n+1]=r,m[n+1]=c,r+=b,c+=k;for(var e=new Uint32Array(6*g),f=p[d],k=function(b,c,a){if(b<c){var w=p[b+1]++;e[2*w]=c;e[2*w+1]=a}else w=m[c+1]++,e[2*f+2*w]=b,e[2*f+2*w+1]=a},n=0;n<g;n++)r=a[3*n],c=a[3*n+1],b=a[3*n+2],k(r,c,n),k(c,b,n),k(b,r,n);r=function(b,c){var f=2*b;b=c-b;
for(c=1;c<b;c++){var a=e[f+2*c],w=e[f+2*c+1],t=c-1;for(t;0<=t&&e[f+2*t]>a;t--)e[f+2*t+2]=e[f+2*t],e[f+2*t+3]=e[f+2*t+1];e[f+2*t+2]=a;e[f+2*t+3]=w}};for(n=0;n<d;n++)r(p[n],p[n+1]),r(f+m[n],f+m[n+1]);for(var h=new Int32Array(3*g),l=function(b,e){return b===a[3*e]?0:b===a[3*e+1]?1:b===a[3*e+2]?2:-1},g=function(b,e){b=l(b,e);h[3*e+b]=-1},r=function(b,e,c,f){b=l(b,e);h[3*e+b]=f;c=l(c,f);h[3*f+c]=e},n=0;n<d;n++){for(var c=p[n],b=p[n+1],k=m[n],w=m[n+1];c<b&&k<w;){var t=e[2*c],v=e[2*f+2*k];t===v?(r(n,e[2*
c+1],v,e[2*f+2*k+1]),c++,k++):t<v?(g(n,e[2*c+1]),c++):(g(v,e[2*f+2*k+1]),k++)}for(;c<b;)g(n,e[2*c+1]),c++;for(;k<w;)v=e[2*f+2*k],g(v,e[2*f+2*k+1]),k++}return h}})},"esri/views/3d/support/buffer/workerHelper":function(){define(["require","exports","../../../../core/tsSupport/assignHelper","./BufferView","./InterleavedLayout"],function(q,a,l,d,g){function p(a){var g=[];a.fields.forEach(function(c,b){var e=c.constructor;c=l({},c,{constructor:e.ElementType+"_"+e.ElementCount});g.push([b,c])});return{stride:a.stride,
fields:g,fieldNames:a.fieldNames}}function m(a){var d=g.newLayout();d.stride=a.stride;d.fieldNames=a.fieldNames;a.fields.forEach(function(c){return d.fields.set(c[0],l({},c[1],{constructor:k.get(c[1].constructor)}))});return d}Object.defineProperty(a,"__esModule",{value:!0});a.packInterleavedBuffer=function(a,g){g.push(a.buffer);return{buffer:a.buffer,layout:p(a.layout)}};a.unpackInterleavedBuffer=function(a){return m(a.layout).createView(a.buffer)};a.packLayout=p;a.unpackLayout=m;q=[d.BufferViewFloat,
d.BufferViewVec2f,d.BufferViewVec3f,d.BufferViewVec4f,d.BufferViewMat3f,d.BufferViewMat4f,d.BufferViewFloat64,d.BufferViewVec2f64,d.BufferViewVec3f64,d.BufferViewVec4f64,d.BufferViewMat3f64,d.BufferViewMat4f64,d.BufferViewUint8,d.BufferViewVec2u8,d.BufferViewVec3u8,d.BufferViewVec4u8,d.BufferViewUint16,d.BufferViewVec2u16,d.BufferViewVec3u16,d.BufferViewVec4u16,d.BufferViewUint32,d.BufferViewVec2u32,d.BufferViewVec3u32,d.BufferViewVec4u32,d.BufferViewInt8,d.BufferViewVec2i8,d.BufferViewVec3i8,d.BufferViewVec4i8,
d.BufferViewInt16,d.BufferViewVec2i16,d.BufferViewVec3i16,d.BufferViewVec4i16,d.BufferViewInt32,d.BufferViewVec2i32,d.BufferViewVec3i32,d.BufferViewVec4i32];var k=new Map;q.forEach(function(a){return k.set(a.ElementType+"_"+a.ElementCount,a)})})},"esri/views/3d/support/buffer/BufferView":function(){define("require exports ../../../../core/tsSupport/extendsHelper ./internals/Mat3 ./internals/Mat4 ./internals/Scalar ./internals/Vec2 ./internals/Vec3 ./internals/Vec4".split(" "),function(q,a,l,d,g,p,
m,k,n){Object.defineProperty(a,"__esModule",{value:!0});q=function(a){function c(b,e,c,h){void 0===e&&(e=0);b=a.call(this,Float32Array,b,e,c,h)||this;b.elementType="f32";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="f32";return c}(p.BufferViewScalarImpl);a.BufferViewFloat=q;q=function(a){function c(b,e,c,h){void 0===e&&(e=0);b=a.call(this,Float32Array,b,e,c,h)||this;b.elementType="f32";return b}l(c,a);c.fromTypedArray=
function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="f32";return c}(m.BufferViewVec2Impl);a.BufferViewVec2f=q;q=function(a){function c(b,e,c,h){void 0===e&&(e=0);b=a.call(this,Float32Array,b,e,c,h)||this;b.elementType="f32";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="f32";return c}(k.BufferViewVec3Impl);a.BufferViewVec3f=q;q=function(a){function c(b,e,c,h){void 0===e&&(e=0);
b=a.call(this,Float32Array,b,e,c,h)||this;b.elementType="f32";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="f32";return c}(n.BufferViewVec4Impl);a.BufferViewVec4f=q;q=function(a){function c(b,e,c,h){void 0===e&&(e=0);b=a.call(this,Float32Array,b,e,c,h)||this;b.elementType="f32";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="f32";return c}(d.BufferViewMat3Impl);
a.BufferViewMat3f=q;d=function(a){function c(b,e,c,h){void 0===e&&(e=0);b=a.call(this,Float64Array,b,e,c,h)||this;b.elementType="f64";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="f64";return c}(d.BufferViewMat3Impl);a.BufferViewMat3f64=d;d=function(a){function c(b,e,c,h){void 0===e&&(e=0);b=a.call(this,Float32Array,b,e,c,h)||this;b.elementType="f32";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,
b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="f32";return c}(g.BufferViewMat4Impl);a.BufferViewMat4f=d;g=function(a){function c(b,e,c,h){void 0===e&&(e=0);b=a.call(this,Float64Array,b,e,c,h)||this;b.elementType="f64";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="f64";return c}(g.BufferViewMat4Impl);a.BufferViewMat4f64=g;g=function(a){function c(b,e,c,h){void 0===e&&(e=0);b=a.call(this,Float64Array,b,e,c,h)||
this;b.elementType="f64";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="f64";return c}(p.BufferViewScalarImpl);a.BufferViewFloat64=g;g=function(a){function c(b,e,c,h){void 0===e&&(e=0);b=a.call(this,Float64Array,b,e,c,h)||this;b.elementType="f64";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="f64";return c}(m.BufferViewVec2Impl);a.BufferViewVec2f64=
g;g=function(a){function c(b,e,c,h){void 0===e&&(e=0);b=a.call(this,Float64Array,b,e,c,h)||this;b.elementType="f64";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="f64";return c}(k.BufferViewVec3Impl);a.BufferViewVec3f64=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Float64Array,b,c,f,h)||this;b.elementType="f64";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+
b.byteLength)};c.ElementType="f64";return c}(n.BufferViewVec4Impl);a.BufferViewVec4f64=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Uint8Array,b,c,f,h)||this;b.elementType="u8";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="u8";return c}(p.BufferViewScalarImpl);a.BufferViewUint8=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Uint8Array,b,c,f,h)||this;b.elementType="u8";return b}
l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="u8";return c}(m.BufferViewVec2Impl);a.BufferViewVec2u8=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Uint8Array,b,c,f,h)||this;b.elementType="u8";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="u8";return c}(k.BufferViewVec3Impl);a.BufferViewVec3u8=g;g=function(a){function c(b,c,f,
h){void 0===c&&(c=0);b=a.call(this,Uint8Array,b,c,f,h)||this;b.elementType="u8";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="u8";return c}(n.BufferViewVec4Impl);a.BufferViewVec4u8=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Uint16Array,b,c,f,h)||this;b.elementType="u16";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType=
"u16";return c}(p.BufferViewScalarImpl);a.BufferViewUint16=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Uint16Array,b,c,f,h)||this;b.elementType="u16";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="u16";return c}(m.BufferViewVec2Impl);a.BufferViewVec2u16=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Uint16Array,b,c,f,h)||this;b.elementType="u16";return b}l(c,a);c.fromTypedArray=
function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="u16";return c}(k.BufferViewVec3Impl);a.BufferViewVec3u16=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Uint16Array,b,c,f,h)||this;b.elementType="u16";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="u16";return c}(n.BufferViewVec4Impl);a.BufferViewVec4u16=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=
0);b=a.call(this,Uint32Array,b,c,f,h)||this;b.elementType="u32";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="u32";return c}(p.BufferViewScalarImpl);a.BufferViewUint32=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Uint32Array,b,c,f,h)||this;b.elementType="u32";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="u32";return c}(m.BufferViewVec2Impl);
a.BufferViewVec2u32=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Uint32Array,b,c,f,h)||this;b.elementType="u32";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="u32";return c}(k.BufferViewVec3Impl);a.BufferViewVec3u32=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Uint32Array,b,c,f,h)||this;b.elementType="u32";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,
b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="u32";return c}(n.BufferViewVec4Impl);a.BufferViewVec4u32=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Int8Array,b,c,f,h)||this;b.elementType="i8";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="i8";return c}(p.BufferViewScalarImpl);a.BufferViewInt8=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Int8Array,b,c,f,h)||this;
b.elementType="i8";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="i8";return c}(m.BufferViewVec2Impl);a.BufferViewVec2i8=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Int8Array,b,c,f,h)||this;b.elementType="i8";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="i8";return c}(k.BufferViewVec3Impl);a.BufferViewVec3i8=g;g=function(a){function c(b,
c,f,h){void 0===c&&(c=0);b=a.call(this,Int8Array,b,c,f,h)||this;b.elementType="i8";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="i8";return c}(n.BufferViewVec4Impl);a.BufferViewVec4i8=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Int16Array,b,c,f,h)||this;b.elementType="i16";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType=
"i16";return c}(p.BufferViewScalarImpl);a.BufferViewInt16=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Int16Array,b,c,f,h)||this;b.elementType="i16";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="i16";return c}(m.BufferViewVec2Impl);a.BufferViewVec2i16=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Int16Array,b,c,f,h)||this;b.elementType="i16";return b}l(c,a);c.fromTypedArray=
function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="i16";return c}(k.BufferViewVec3Impl);a.BufferViewVec3i16=g;g=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Int16Array,b,c,f,h)||this;b.elementType="i16";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="i16";return c}(n.BufferViewVec4Impl);a.BufferViewVec4i16=g;p=function(a){function c(b,c,f,h){void 0===c&&(c=0);
b=a.call(this,Int32Array,b,c,f,h)||this;b.elementType="i32";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="i32";return c}(p.BufferViewScalarImpl);a.BufferViewInt32=p;m=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Int32Array,b,c,f,h)||this;b.elementType="i32";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="i32";return c}(m.BufferViewVec2Impl);
a.BufferViewVec2i32=m;k=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Int32Array,b,c,f,h)||this;b.elementType="i32";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="i32";return c}(k.BufferViewVec3Impl);a.BufferViewVec3i32=k;n=function(a){function c(b,c,f,h){void 0===c&&(c=0);b=a.call(this,Int32Array,b,c,f,h)||this;b.elementType="i32";return b}l(c,a);c.fromTypedArray=function(b,e){return new c(b.buffer,
b.byteOffset,e,b.byteOffset+b.byteLength)};c.ElementType="i32";return c}(n.BufferViewVec4Impl);a.BufferViewVec4i32=n})},"esri/views/3d/support/buffer/internals/Mat3":function(){define(["require","exports"],function(q,a){Object.defineProperty(a,"__esModule",{value:!0});q=function(){function a(a,g,p,m,k){void 0===p&&(p=0);this.TypedArrayConstructor=a;this.elementCount=9;a=this.TypedArrayConstructor;void 0===m&&(m=9*a.BYTES_PER_ELEMENT);var d=0===g.byteLength?0:p;this.typedBuffer=null==k?new a(g,d):
new a(g,d,(k-p)/a.BYTES_PER_ELEMENT);this.typedBufferStride=m/a.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}a.prototype.getMat=function(a,g){a*=this.typedBufferStride;for(var d=0;9>d;d++)g[d]=this.typedBuffer[a+d];return g};a.prototype.setMat=function(a,g){a*=this.typedBufferStride;for(var d=0;9>d;d++)this.typedBuffer[a+d]=g[d]};a.prototype.get=function(a,g){return this.typedBuffer[a*
this.typedBufferStride+g]};a.prototype.set=function(a,g,p){this.typedBuffer[a*this.typedBufferStride+g]=p};a.prototype.copyFrom=function(a,g,p){var d=this.typedBuffer,k=g.typedBuffer;a*=this.typedBufferStride;g=p*g.typedBufferStride;for(p=0;9>p;++p)d[a+p]=k[g+p]};Object.defineProperty(a.prototype,"buffer",{get:function(){return this.typedBuffer.buffer},enumerable:!0,configurable:!0});a.ElementCount=9;return a}();a.BufferViewMat3Impl=q})},"esri/views/3d/support/buffer/internals/Mat4":function(){define(["require",
"exports"],function(q,a){Object.defineProperty(a,"__esModule",{value:!0});q=function(){function a(a,g,p,m,k){void 0===p&&(p=0);this.TypedArrayConstructor=a;this.elementCount=16;a=this.TypedArrayConstructor;void 0===m&&(m=16*a.BYTES_PER_ELEMENT);var d=0===g.byteLength?0:p;this.typedBuffer=null==k?new a(g,d):new a(g,d,(k-p)/a.BYTES_PER_ELEMENT);this.typedBufferStride=m/a.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}
a.prototype.getMat=function(a,g){a*=this.typedBufferStride;for(var d=0;16>d;d++)g[d]=this.typedBuffer[a+d];return g};a.prototype.setMat=function(a,g){a*=this.typedBufferStride;for(var d=0;16>d;d++)this.typedBuffer[a+d]=g[d]};a.prototype.get=function(a,g){return this.typedBuffer[a*this.typedBufferStride+g]};a.prototype.set=function(a,g,p){this.typedBuffer[a*this.typedBufferStride+g]=p};a.prototype.copyFrom=function(a,g,p){var d=this.typedBuffer,k=g.typedBuffer;a*=this.typedBufferStride;g=p*g.typedBufferStride;
for(p=0;16>p;++p)d[a+p]=k[g+p]};Object.defineProperty(a.prototype,"buffer",{get:function(){return this.typedBuffer.buffer},enumerable:!0,configurable:!0});a.ElementCount=16;return a}();a.BufferViewMat4Impl=q})},"esri/views/3d/support/buffer/internals/Scalar":function(){define(["require","exports"],function(q,a){Object.defineProperty(a,"__esModule",{value:!0});q=function(){function a(a,g,p,m,k){void 0===p&&(p=0);this.TypedArrayConstructor=a;this.elementCount=1;a=this.TypedArrayConstructor;void 0===
m&&(m=a.BYTES_PER_ELEMENT);var d=0===g.byteLength?0:p;this.typedBuffer=null==k?new a(g,d):new a(g,d,(k-p)/a.BYTES_PER_ELEMENT);this.typedBufferStride=m/a.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}a.prototype.get=function(a){return this.typedBuffer[a*this.typedBufferStride]};a.prototype.set=function(a,g){this.typedBuffer[a*this.typedBufferStride]=g};Object.defineProperty(a.prototype,
"buffer",{get:function(){return this.typedBuffer.buffer},enumerable:!0,configurable:!0});a.ElementCount=1;return a}();a.BufferViewScalarImpl=q})},"esri/views/3d/support/buffer/internals/Vec2":function(){define(["require","exports","../../../../../core/libs/gl-matrix-2/vec2"],function(q,a,l){Object.defineProperty(a,"__esModule",{value:!0});q=function(){function a(a,d,m,k,n){void 0===m&&(m=0);this.TypedArrayConstructor=a;this.elementCount=2;a=this.TypedArrayConstructor;void 0===k&&(k=2*a.BYTES_PER_ELEMENT);
var g=0===d.byteLength?0:m;this.typedBuffer=null==n?new a(d,g):new a(d,g,(n-m)/a.BYTES_PER_ELEMENT);this.typedBufferStride=k/a.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}a.prototype.getVec=function(a,d){return l.vec2.set(d,this.typedBuffer[a*this.typedBufferStride],this.typedBuffer[a*this.typedBufferStride+1])};a.prototype.setVec=function(a,d){this.typedBuffer[a*this.typedBufferStride]=
d[0];this.typedBuffer[a*this.typedBufferStride+1]=d[1]};a.prototype.get=function(a,d){return this.typedBuffer[a*this.typedBufferStride+d]};a.prototype.set=function(a,d,m){this.typedBuffer[a*this.typedBufferStride+d]=m};a.prototype.copyFrom=function(a,d,m){var k=this.typedBuffer,g=d.typedBuffer;a*=this.typedBufferStride;d=m*d.typedBufferStride;k[a]=g[d];k[a+1]=g[d+1]};Object.defineProperty(a.prototype,"buffer",{get:function(){return this.typedBuffer.buffer},enumerable:!0,configurable:!0});a.ElementCount=
2;return a}();a.BufferViewVec2Impl=q})},"esri/core/libs/gl-matrix-2/vec2":function(){define(["require","exports","./math/vec2"],function(q,a,l){Object.defineProperty(a,"__esModule",{value:!0});a.vec2=l})},"esri/core/libs/gl-matrix-2/math/vec2":function(){define(["require","exports","./common"],function(q,a,l){function d(c,b,a){c[0]=b[0]-a[0];c[1]=b[1]-a[1];return c}function g(c,b,a){c[0]=b[0]*a[0];c[1]=b[1]*a[1];return c}function p(c,b,a){c[0]=b[0]/a[0];c[1]=b[1]/a[1];return c}function m(c,b){var a=
b[0]-c[0];c=b[1]-c[1];return Math.sqrt(a*a+c*c)}function k(c,b){var a=b[0]-c[0];c=b[1]-c[1];return a*a+c*c}function n(c){var b=c[0];c=c[1];return Math.sqrt(b*b+c*c)}function r(c){var b=c[0];c=c[1];return b*b+c*c}Object.defineProperty(a,"__esModule",{value:!0});a.copy=function(c,b){c[0]=b[0];c[1]=b[1];return c};a.set=function(c,b,a){c[0]=b;c[1]=a;return c};a.add=function(c,b,a){c[0]=b[0]+a[0];c[1]=b[1]+a[1];return c};a.subtract=d;a.multiply=g;a.divide=p;a.ceil=function(c,b){c[0]=Math.ceil(b[0]);c[1]=
Math.ceil(b[1]);return c};a.floor=function(c,b){c[0]=Math.floor(b[0]);c[1]=Math.floor(b[1]);return c};a.min=function(c,b,a){c[0]=Math.min(b[0],a[0]);c[1]=Math.min(b[1],a[1]);return c};a.max=function(c,b,a){c[0]=Math.max(b[0],a[0]);c[1]=Math.max(b[1],a[1]);return c};a.round=function(c,b){c[0]=Math.round(b[0]);c[1]=Math.round(b[1]);return c};a.scale=function(c,b,a){c[0]=b[0]*a;c[1]=b[1]*a;return c};a.scaleAndAdd=function(c,b,a,f){c[0]=b[0]+a[0]*f;c[1]=b[1]+a[1]*f;return c};a.distance=m;a.squaredDistance=
k;a.length=n;a.squaredLength=r;a.negate=function(c,b){c[0]=-b[0];c[1]=-b[1];return c};a.inverse=function(c,b){c[0]=1/b[0];c[1]=1/b[1];return c};a.normalize=function(c,b){var a=b[0],f=b[1],a=a*a+f*f;0<a&&(a=1/Math.sqrt(a),c[0]=b[0]*a,c[1]=b[1]*a);return c};a.dot=function(c,b){return c[0]*b[0]+c[1]*b[1]};a.cross=function(c,b,a){b=b[0]*a[1]-b[1]*a[0];c[0]=c[1]=0;c[2]=b;return c};a.lerp=function(c,b,a,f){var e=b[0];b=b[1];c[0]=e+f*(a[0]-e);c[1]=b+f*(a[1]-b);return c};a.random=function(c,b){b=b||1;var a=
2*l.RANDOM()*Math.PI;c[0]=Math.cos(a)*b;c[1]=Math.sin(a)*b;return c};a.transformMat2=function(c,b,a){var e=b[0];b=b[1];c[0]=a[0]*e+a[2]*b;c[1]=a[1]*e+a[3]*b;return c};a.transformMat2d=function(c,b,a){var e=b[0];b=b[1];c[0]=a[0]*e+a[2]*b+a[4];c[1]=a[1]*e+a[3]*b+a[5];return c};a.transformMat3=function(c,b,a){var e=b[0];b=b[1];c[0]=a[0]*e+a[3]*b+a[6];c[1]=a[1]*e+a[4]*b+a[7];return c};a.transformMat4=function(c,b,a){var e=b[0];b=b[1];c[0]=a[0]*e+a[4]*b+a[12];c[1]=a[1]*e+a[5]*b+a[13];return c};a.rotate=
function(c,b,a,f){var e=b[0]-a[0];b=b[1]-a[1];var k=Math.sin(f);f=Math.cos(f);c[0]=e*f-b*k+a[0];c[1]=e*k+b*f+a[1];return c};a.angle=function(c,b){var a=c[0];c=c[1];var f=b[0];b=b[1];var h=a*a+c*c;0<h&&(h=1/Math.sqrt(h));var k=f*f+b*b;0<k&&(k=1/Math.sqrt(k));a=(a*f+c*b)*h*k;return 1<a?0:-1>a?Math.PI:Math.acos(a)};a.str=function(c){return"vec2("+c[0]+", "+c[1]+")"};a.exactEquals=function(c,b){return c[0]===b[0]&&c[1]===b[1]};a.equals=function(c,b){var a=c[0];c=c[1];var f=b[0];b=b[1];return Math.abs(a-
f)<=l.EPSILON*Math.max(1,Math.abs(a),Math.abs(f))&&Math.abs(c-b)<=l.EPSILON*Math.max(1,Math.abs(c),Math.abs(b))};a.len=n;a.sub=d;a.mul=g;a.div=p;a.dist=m;a.sqrDist=k;a.sqrLen=r})},"esri/core/libs/gl-matrix-2/math/common":function(){define(["require","exports"],function(q,a){Object.defineProperty(a,"__esModule",{value:!0});a.EPSILON=1E-6;a.RANDOM=Math.random;var l=Math.PI/180,d=180/Math.PI;a.toRadian=function(a){return a*l};a.toDegree=function(a){return a*d};a.equals=function(d,p){return Math.abs(d-
p)<=a.EPSILON*Math.max(1,Math.abs(d),Math.abs(p))}})},"esri/views/3d/support/buffer/internals/Vec3":function(){define(["require","exports","../../../../../core/libs/gl-matrix-2/vec3"],function(q,a,l){Object.defineProperty(a,"__esModule",{value:!0});q=function(){function a(a,d,m,k,n){void 0===m&&(m=0);this.TypedArrayConstructor=a;this.elementCount=3;a=this.TypedArrayConstructor;void 0===k&&(k=3*a.BYTES_PER_ELEMENT);var g=0===d.byteLength?0:m;this.typedBuffer=null==n?new a(d,g):new a(d,g,(n-m)/a.BYTES_PER_ELEMENT);
this.typedBufferStride=k/a.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}a.prototype.getVec=function(a,d){return l.vec3.set(d,this.typedBuffer[a*this.typedBufferStride],this.typedBuffer[a*this.typedBufferStride+1],this.typedBuffer[a*this.typedBufferStride+2])};a.prototype.setVec=function(a,d){this.typedBuffer[a*this.typedBufferStride]=d[0];this.typedBuffer[a*this.typedBufferStride+
1]=d[1];this.typedBuffer[a*this.typedBufferStride+2]=d[2]};a.prototype.get=function(a,d){return this.typedBuffer[a*this.typedBufferStride+d]};a.prototype.set=function(a,d,m){this.typedBuffer[a*this.typedBufferStride+d]=m};a.prototype.copyFrom=function(a,d,m){var k=this.typedBuffer,g=d.typedBuffer;a*=this.typedBufferStride;d=m*d.typedBufferStride;k[a]=g[d];k[a+1]=g[d+1];k[a+2]=g[d+2]};Object.defineProperty(a.prototype,"buffer",{get:function(){return this.typedBuffer.buffer},enumerable:!0,configurable:!0});
a.ElementCount=3;return a}();a.BufferViewVec3Impl=q})},"esri/core/libs/gl-matrix-2/vec3":function(){define(["require","exports","./math/vec3"],function(q,a,l){Object.defineProperty(a,"__esModule",{value:!0});a.vec3=l})},"esri/core/libs/gl-matrix-2/math/vec3":function(){define(["require","exports","../factories/vec3f64","./common"],function(q,a,l,d){function g(b){var c=b[0],a=b[1];b=b[2];return Math.sqrt(c*c+a*a+b*b)}function p(b,c){b[0]=c[0];b[1]=c[1];b[2]=c[2];return b}function m(b,c,a){b[0]=c[0]-
a[0];b[1]=c[1]-a[1];b[2]=c[2]-a[2];return b}function k(b,c,a){b[0]=c[0]*a[0];b[1]=c[1]*a[1];b[2]=c[2]*a[2];return b}function n(b,c,a){b[0]=c[0]/a[0];b[1]=c[1]/a[1];b[2]=c[2]/a[2];return b}function r(b,c){var a=c[0]-b[0],e=c[1]-b[1];b=c[2]-b[2];return Math.sqrt(a*a+e*e+b*b)}function c(b,c){var a=c[0]-b[0],e=c[1]-b[1];b=c[2]-b[2];return a*a+e*e+b*b}function b(b){var c=b[0],a=b[1];b=b[2];return c*c+a*a+b*b}function e(b,c){var a=c[0],e=c[1],f=c[2],a=a*a+e*e+f*f;0<a&&(a=1/Math.sqrt(a),b[0]=c[0]*a,b[1]=
c[1]*a,b[2]=c[2]*a);return b}function f(b,c){return b[0]*c[0]+b[1]*c[1]+b[2]*c[2]}Object.defineProperty(a,"__esModule",{value:!0});a.length=g;a.copy=p;a.set=function(b,c,a,e){b[0]=c;b[1]=a;b[2]=e;return b};a.add=function(b,c,a){b[0]=c[0]+a[0];b[1]=c[1]+a[1];b[2]=c[2]+a[2];return b};a.subtract=m;a.multiply=k;a.divide=n;a.ceil=function(b,c){b[0]=Math.ceil(c[0]);b[1]=Math.ceil(c[1]);b[2]=Math.ceil(c[2]);return b};a.floor=function(b,c){b[0]=Math.floor(c[0]);b[1]=Math.floor(c[1]);b[2]=Math.floor(c[2]);
return b};a.min=function(b,c,a){b[0]=Math.min(c[0],a[0]);b[1]=Math.min(c[1],a[1]);b[2]=Math.min(c[2],a[2]);return b};a.max=function(b,c,a){b[0]=Math.max(c[0],a[0]);b[1]=Math.max(c[1],a[1]);b[2]=Math.max(c[2],a[2]);return b};a.round=function(b,c){b[0]=Math.round(c[0]);b[1]=Math.round(c[1]);b[2]=Math.round(c[2]);return b};a.scale=function(b,c,a){b[0]=c[0]*a;b[1]=c[1]*a;b[2]=c[2]*a;return b};a.scaleAndAdd=function(b,c,a,e){b[0]=c[0]+a[0]*e;b[1]=c[1]+a[1]*e;b[2]=c[2]+a[2]*e;return b};a.distance=r;a.squaredDistance=
c;a.squaredLength=b;a.negate=function(b,c){b[0]=-c[0];b[1]=-c[1];b[2]=-c[2];return b};a.inverse=function(b,c){b[0]=1/c[0];b[1]=1/c[1];b[2]=1/c[2];return b};a.normalize=e;a.dot=f;a.cross=function(b,c,a){var e=c[0],f=c[1];c=c[2];var h=a[0],d=a[1];a=a[2];b[0]=f*a-c*d;b[1]=c*h-e*a;b[2]=e*d-f*h;return b};a.lerp=function(b,c,a,e){var f=c[0],h=c[1];c=c[2];b[0]=f+e*(a[0]-f);b[1]=h+e*(a[1]-h);b[2]=c+e*(a[2]-c);return b};a.hermite=function(b,c,a,e,f,h){var d=h*h,k=d*(2*h-3)+1,g=d*(h-2)+h,n=d*(h-1);h=d*(3-2*
h);b[0]=c[0]*k+a[0]*g+e[0]*n+f[0]*h;b[1]=c[1]*k+a[1]*g+e[1]*n+f[1]*h;b[2]=c[2]*k+a[2]*g+e[2]*n+f[2]*h;return b};a.bezier=function(b,c,a,e,f,h){var d=1-h,k=d*d,g=h*h,n=k*d,k=3*h*k,d=3*g*d;h*=g;b[0]=c[0]*n+a[0]*k+e[0]*d+f[0]*h;b[1]=c[1]*n+a[1]*k+e[1]*d+f[1]*h;b[2]=c[2]*n+a[2]*k+e[2]*d+f[2]*h;return b};a.random=function(b,c){c=c||1;var a=2*d.RANDOM()*Math.PI,e=2*d.RANDOM()-1,f=Math.sqrt(1-e*e)*c;b[0]=Math.cos(a)*f;b[1]=Math.sin(a)*f;b[2]=e*c;return b};a.transformMat4=function(b,c,a){var e=c[0],f=c[1];
c=c[2];b[0]=a[0]*e+a[4]*f+a[8]*c+a[12];b[1]=a[1]*e+a[5]*f+a[9]*c+a[13];b[2]=a[2]*e+a[6]*f+a[10]*c+a[14];return b};a.transformMat3=function(b,c,a){var e=c[0],f=c[1];c=c[2];b[0]=e*a[0]+f*a[3]+c*a[6];b[1]=e*a[1]+f*a[4]+c*a[7];b[2]=e*a[2]+f*a[5]+c*a[8];return b};a.transformQuat=function(b,c,a){var e=a[0],f=a[1],h=a[2],d=c[0],k=c[1];c=c[2];var g=f*c-h*k,n=h*d-e*c,m=e*k-f*d;a=2*a[3];b[0]=d+g*a+2*(f*m-h*n);b[1]=k+n*a+2*(h*g-e*m);b[2]=c+m*a+2*(e*n-f*g);return b};a.rotateX=function(b,c,a,e){var f=[],h=[];
f[0]=c[0]-a[0];f[1]=c[1]-a[1];f[2]=c[2]-a[2];h[0]=f[0];h[1]=f[1]*Math.cos(e)-f[2]*Math.sin(e);h[2]=f[1]*Math.sin(e)+f[2]*Math.cos(e);b[0]=h[0]+a[0];b[1]=h[1]+a[1];b[2]=h[2]+a[2];return b};a.rotateY=function(b,c,a,e){var f=[],h=[];f[0]=c[0]-a[0];f[1]=c[1]-a[1];f[2]=c[2]-a[2];h[0]=f[2]*Math.sin(e)+f[0]*Math.cos(e);h[1]=f[1];h[2]=f[2]*Math.cos(e)-f[0]*Math.sin(e);b[0]=h[0]+a[0];b[1]=h[1]+a[1];b[2]=h[2]+a[2];return b};a.rotateZ=function(b,c,a,e){var f=[],h=[];f[0]=c[0]-a[0];f[1]=c[1]-a[1];f[2]=c[2]-a[2];
h[0]=f[0]*Math.cos(e)-f[1]*Math.sin(e);h[1]=f[0]*Math.sin(e)+f[1]*Math.cos(e);h[2]=f[2];b[0]=h[0]+a[0];b[1]=h[1]+a[1];b[2]=h[2]+a[2];return b};a.angle=function(b,c){p(h,b);p(z,c);e(h,h);e(z,z);b=f(h,z);return 1<b?0:-1>b?Math.PI:Math.acos(b)};var h=l.create(),z=l.create();a.str=function(b){return"vec3("+b[0]+", "+b[1]+", "+b[2]+")"};a.exactEquals=function(b,c){return b[0]===c[0]&&b[1]===c[1]&&b[2]===c[2]};a.equals=function(b,c){var a=b[0],e=b[1];b=b[2];var f=c[0],h=c[1];c=c[2];return Math.abs(a-f)<=
d.EPSILON*Math.max(1,Math.abs(a),Math.abs(f))&&Math.abs(e-h)<=d.EPSILON*Math.max(1,Math.abs(e),Math.abs(h))&&Math.abs(b-c)<=d.EPSILON*Math.max(1,Math.abs(b),Math.abs(c))};a.sub=m;a.mul=k;a.div=n;a.dist=r;a.sqrDist=c;a.len=g;a.sqrLen=b})},"esri/core/libs/gl-matrix-2/factories/vec3f64":function(){define(["require","exports"],function(q,a){function l(){return[0,0,0]}function d(){return[1,1,1]}function g(){return[1,0,0]}function p(){return[0,1,0]}function m(){return[0,0,1]}Object.defineProperty(a,"__esModule",
{value:!0});a.create=l;a.clone=function(a){return[a[0],a[1],a[2]]};a.fromValues=function(a,d,g){return[a,d,g]};a.fromArray=function(a){for(var d=l(),k=Math.min(3,a.length),c=0;c<k;++c)d[c]=a[c];return d};a.createView=function(a,d){return new Float64Array(a,d,3)};a.zeros=function(){return l()};a.ones=d;a.unitX=g;a.unitY=p;a.unitZ=m;a.ZEROS=l();a.ONES=d();a.UNIT_X=g();a.UNIT_Y=p();a.UNIT_Z=m()})},"esri/views/3d/support/buffer/internals/Vec4":function(){define(["require","exports","../../../../../core/libs/gl-matrix-2/vec4"],
function(q,a,l){Object.defineProperty(a,"__esModule",{value:!0});q=function(){function a(a,d,m,k,n){void 0===m&&(m=0);this.TypedArrayConstructor=a;this.elementCount=4;a=this.TypedArrayConstructor;void 0===k&&(k=4*a.BYTES_PER_ELEMENT);var g=0===d.byteLength?0:m;this.typedBuffer=null==n?new a(d,g):new a(d,g,(n-m)/a.BYTES_PER_ELEMENT);this.typedBufferStride=k/a.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}
a.prototype.getVec=function(a,d){return l.vec4.set(d,this.typedBuffer[a*this.typedBufferStride],this.typedBuffer[a*this.typedBufferStride+1],this.typedBuffer[a*this.typedBufferStride+2],this.typedBuffer[a*this.typedBufferStride+3])};a.prototype.setVec=function(a,d){this.typedBuffer[a*this.typedBufferStride]=d[0];this.typedBuffer[a*this.typedBufferStride+1]=d[1];this.typedBuffer[a*this.typedBufferStride+2]=d[2];this.typedBuffer[a*this.typedBufferStride+3]=d[3]};a.prototype.get=function(a,d){return this.typedBuffer[a*
this.typedBufferStride+d]};a.prototype.set=function(a,d,m){this.typedBuffer[a*this.typedBufferStride+d]=m};a.prototype.copyFrom=function(a,d,m){var k=this.typedBuffer,g=d.typedBuffer;a*=this.typedBufferStride;d=m*d.typedBufferStride;k[a]=g[d];k[a+1]=g[d+1];k[a+2]=g[d+2];k[a+3]=g[d+3]};Object.defineProperty(a.prototype,"buffer",{get:function(){return this.typedBuffer.buffer},enumerable:!0,configurable:!0});a.ElementCount=4;return a}();a.BufferViewVec4Impl=q})},"esri/core/libs/gl-matrix-2/vec4":function(){define(["require",
"exports","./math/vec4"],function(q,a,l){Object.defineProperty(a,"__esModule",{value:!0});a.vec4=l})},"esri/core/libs/gl-matrix-2/math/vec4":function(){define(["require","exports","./common"],function(q,a,l){function d(c,b,a){c[0]=b[0]-a[0];c[1]=b[1]-a[1];c[2]=b[2]-a[2];c[3]=b[3]-a[3];return c}function g(c,b,a){c[0]=b[0]*a[0];c[1]=b[1]*a[1];c[2]=b[2]*a[2];c[3]=b[3]*a[3];return c}function p(c,b,a){c[0]=b[0]/a[0];c[1]=b[1]/a[1];c[2]=b[2]/a[2];c[3]=b[3]/a[3];return c}function m(c,b){var a=b[0]-c[0],
f=b[1]-c[1],h=b[2]-c[2];c=b[3]-c[3];return Math.sqrt(a*a+f*f+h*h+c*c)}function k(c,b){var a=b[0]-c[0],f=b[1]-c[1],h=b[2]-c[2];c=b[3]-c[3];return a*a+f*f+h*h+c*c}function n(c){var b=c[0],a=c[1],f=c[2];c=c[3];return Math.sqrt(b*b+a*a+f*f+c*c)}function r(c){var b=c[0],a=c[1],f=c[2];c=c[3];return b*b+a*a+f*f+c*c}Object.defineProperty(a,"__esModule",{value:!0});a.copy=function(c,b){c[0]=b[0];c[1]=b[1];c[2]=b[2];c[3]=b[3];return c};a.set=function(c,b,a,f,h){c[0]=b;c[1]=a;c[2]=f;c[3]=h;return c};a.add=function(c,
b,a){c[0]=b[0]+a[0];c[1]=b[1]+a[1];c[2]=b[2]+a[2];c[3]=b[3]+a[3];return c};a.subtract=d;a.multiply=g;a.divide=p;a.ceil=function(c,b){c[0]=Math.ceil(b[0]);c[1]=Math.ceil(b[1]);c[2]=Math.ceil(b[2]);c[3]=Math.ceil(b[3]);return c};a.floor=function(c,b){c[0]=Math.floor(b[0]);c[1]=Math.floor(b[1]);c[2]=Math.floor(b[2]);c[3]=Math.floor(b[3]);return c};a.min=function(c,b,a){c[0]=Math.min(b[0],a[0]);c[1]=Math.min(b[1],a[1]);c[2]=Math.min(b[2],a[2]);c[3]=Math.min(b[3],a[3]);return c};a.max=function(c,b,a){c[0]=
Math.max(b[0],a[0]);c[1]=Math.max(b[1],a[1]);c[2]=Math.max(b[2],a[2]);c[3]=Math.max(b[3],a[3]);return c};a.round=function(a,b){a[0]=Math.round(b[0]);a[1]=Math.round(b[1]);a[2]=Math.round(b[2]);a[3]=Math.round(b[3]);return a};a.scale=function(a,b,e){a[0]=b[0]*e;a[1]=b[1]*e;a[2]=b[2]*e;a[3]=b[3]*e;return a};a.scaleAndAdd=function(a,b,e,f){a[0]=b[0]+e[0]*f;a[1]=b[1]+e[1]*f;a[2]=b[2]+e[2]*f;a[3]=b[3]+e[3]*f;return a};a.distance=m;a.squaredDistance=k;a.length=n;a.squaredLength=r;a.negate=function(a,b){a[0]=
-b[0];a[1]=-b[1];a[2]=-b[2];a[3]=-b[3];return a};a.inverse=function(a,b){a[0]=1/b[0];a[1]=1/b[1];a[2]=1/b[2];a[3]=1/b[3];return a};a.normalize=function(a,b){var c=b[0],f=b[1],h=b[2];b=b[3];var d=c*c+f*f+h*h+b*b;0<d&&(d=1/Math.sqrt(d),a[0]=c*d,a[1]=f*d,a[2]=h*d,a[3]=b*d);return a};a.dot=function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3]};a.lerp=function(a,b,e,f){var c=b[0],d=b[1],k=b[2];b=b[3];a[0]=c+f*(e[0]-c);a[1]=d+f*(e[1]-d);a[2]=k+f*(e[2]-k);a[3]=b+f*(e[3]-b);return a};a.random=function(a,
b){b=b||1;var c,f,h,d,k,g;do c=2*l.RANDOM()-1,f=2*l.RANDOM()-1,k=c*c+f*f;while(1<=k);do h=2*l.RANDOM()-1,d=2*l.RANDOM()-1,g=h*h+d*d;while(1<=g);k=Math.sqrt((1-k)/g);a[0]=b*c;a[1]=b*f;a[2]=b*h*k;a[3]=b*d*k;return a};a.transformMat4=function(a,b,e){var c=b[0],h=b[1],d=b[2];b=b[3];a[0]=e[0]*c+e[4]*h+e[8]*d+e[12]*b;a[1]=e[1]*c+e[5]*h+e[9]*d+e[13]*b;a[2]=e[2]*c+e[6]*h+e[10]*d+e[14]*b;a[3]=e[3]*c+e[7]*h+e[11]*d+e[15]*b;return a};a.transformQuat=function(a,b,e){var c=b[0],h=b[1],d=b[2],k=e[0],g=e[1],n=e[2];
e=e[3];var m=e*c+g*d-n*h,l=e*h+n*c-k*d,p=e*d+k*h-g*c,c=-k*c-g*h-n*d;a[0]=m*e+c*-k+l*-n-p*-g;a[1]=l*e+c*-g+p*-k-m*-n;a[2]=p*e+c*-n+m*-g-l*-k;a[3]=b[3];return a};a.str=function(a){return"vec4("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+")"};a.exactEquals=function(a,b){return a[0]===b[0]&&a[1]===b[1]&&a[2]===b[2]&&a[3]===b[3]};a.equals=function(a,b){var c=a[0],f=a[1],d=a[2];a=a[3];var k=b[0],g=b[1],n=b[2];b=b[3];return Math.abs(c-k)<=l.EPSILON*Math.max(1,Math.abs(c),Math.abs(k))&&Math.abs(f-g)<=l.EPSILON*Math.max(1,
Math.abs(f),Math.abs(g))&&Math.abs(d-n)<=l.EPSILON*Math.max(1,Math.abs(d),Math.abs(n))&&Math.abs(a-b)<=l.EPSILON*Math.max(1,Math.abs(a),Math.abs(b))};a.sub=d;a.mul=g;a.div=p;a.dist=m;a.sqrDist=k;a.len=n;a.sqrLen=r})},"esri/views/3d/support/buffer/InterleavedLayout":function(){define(["require","exports","./BufferView","./types"],function(q,a,l,d){Object.defineProperty(a,"__esModule",{value:!0});var g=function(){function a(a,d){this.layout=a;this.buffer="number"===typeof d?new ArrayBuffer(d*a.stride):
d;d=0;for(var k=a.fieldNames;d<k.length;d++){var c=k[d],b=a.fields.get(c);this[c]=new b.constructor(this.buffer,b.offset,this.stride)}}Object.defineProperty(a.prototype,"stride",{get:function(){return this.layout.stride},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"count",{get:function(){return this.buffer.byteLength/this.stride},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"byteLength",{get:function(){return this.buffer.byteLength},enumerable:!0,configurable:!0});
a.prototype.getField=function(a,d){return(a=this[a])&&a.elementCount===d.ElementCount&&a.elementType===d.ElementType?a:null};a.prototype.slice=function(d,g){return new a(this.layout,this.buffer.slice(d*this.stride,g*this.stride))};a.prototype.copyFrom=function(a,d,g,c){var b=this.stride;0===b%4?(a=new Uint32Array(a.buffer,d*b,c*b/4),g=new Uint32Array(this.buffer,g*b,c*b/4)):(a=new Uint8Array(a.buffer,d*b,c*b),g=new Uint8Array(this.buffer,g*b,c*b));g.set(a)};return a}();a.InterleavedBuffer=g;var p=
function(){function a(){this.stride=0;this.fields=new Map;this.fieldNames=[]}a.prototype.vec2f=function(a,d){this.appendField(a,l.BufferViewVec2f,d);return this};a.prototype.vec2f64=function(a,d){this.appendField(a,l.BufferViewVec2f64,d);return this};a.prototype.vec3f=function(a,d){this.appendField(a,l.BufferViewVec3f,d);return this};a.prototype.vec3f64=function(a,d){this.appendField(a,l.BufferViewVec3f64,d);return this};a.prototype.vec4f=function(a,d){this.appendField(a,l.BufferViewVec4f,d);return this};
a.prototype.vec4f64=function(a,d){this.appendField(a,l.BufferViewVec4f64,d);return this};a.prototype.mat3f=function(a,d){this.appendField(a,l.BufferViewMat3f,d);return this};a.prototype.mat3f64=function(a,d){this.appendField(a,l.BufferViewMat3f64,d);return this};a.prototype.mat4f=function(a,d){this.appendField(a,l.BufferViewMat4f,d);return this};a.prototype.mat4f64=function(a,d){this.appendField(a,l.BufferViewMat4f64,d);return this};a.prototype.vec4u8=function(a,d){this.appendField(a,l.BufferViewVec4u8,
d);return this};a.prototype.f32=function(a,d){this.appendField(a,l.BufferViewFloat,d);return this};a.prototype.f64=function(a,d){this.appendField(a,l.BufferViewFloat64,d);return this};a.prototype.u8=function(a,d){this.appendField(a,l.BufferViewUint8,d);return this};a.prototype.u16=function(a,d){this.appendField(a,l.BufferViewUint16,d);return this};a.prototype.i8=function(a,d){this.appendField(a,l.BufferViewInt8,d);return this};a.prototype.vec2i8=function(a,d){this.appendField(a,l.BufferViewVec2i8,
d);return this};a.prototype.vec2i16=function(a,d){this.appendField(a,l.BufferViewVec2i16,d);return this};a.prototype.vec2u8=function(a,d){this.appendField(a,l.BufferViewVec2u8,d);return this};a.prototype.vec4u16=function(a,d){this.appendField(a,l.BufferViewVec4u16,d);return this};a.prototype.u32=function(a,d){this.appendField(a,l.BufferViewUint32,d);return this};a.prototype.appendField=function(a,g,l){var c=g.ElementCount*d.elementTypeSize(g.ElementType);this.fields.set(a,{size:c,constructor:g,offset:this.stride,
optional:l});this.stride+=c;this.fieldNames.push(a)};a.prototype.alignTo=function(a){this.stride=Math.floor((this.stride+a-1)/a)*a;return this};a.prototype.hasField=function(a){return 0<=this.fieldNames.indexOf(a)};a.prototype.createBuffer=function(a){return new g(this,a)};a.prototype.createView=function(a){return new g(this,a)};a.prototype.clone=function(){var d=new a;d.stride=this.stride;d.fields=new Map;this.fields.forEach(function(a,g){return d.fields.set(g,a)});d.fieldNames=this.fieldNames.slice();
d.BufferType=this.BufferType;return d};return a}();a.InterleavedLayout=p;a.newLayout=function(){return new p}})},"esri/views/3d/support/buffer/types":function(){define(["require","exports","../../../../core/compilerUtils"],function(q,a,l){Object.defineProperty(a,"__esModule",{value:!0});a.elementTypeSize=function(a){switch(a){case "u8":return 1;case "u16":return 2;case "u32":return 4;case "i8":return 1;case "i16":return 2;case "i32":return 4;case "f32":return 4;case "f64":return 8;default:l.neverReached(a)}};
a.isSigned=function(a){switch(a){case "u8":case "u16":case "u32":return!1;case "i8":case "i16":case "i32":case "f32":case "f64":return!0;default:l.neverReached(a)}};a.isInteger=function(a){switch(a){case "u8":case "u16":case "u32":case "i8":case "i16":case "i32":return!0;case "f32":case "f64":return!1;default:l.neverReached(a)}};a.maximumValue=function(a){switch(a){case "u8":return 255;case "u16":return 65535;case "u32":return 4294967295;case "i8":return 127;case "i16":return 32767;case "i32":return 2147483647;
case "f32":return 3.402823E38;case "f64":return 1.79769E308;default:l.neverReached(a)}}})},"esri/views/3d/webgl-engine/lib/edgeRendering/bufferLayouts":function(){define(["require","exports","../../../support/buffer/glUtil","../../../support/buffer/InterleavedLayout"],function(q,a,l,d){Object.defineProperty(a,"__esModule",{value:!0});a.EdgeInputBufferLayout=d.newLayout().vec3f("position").u16("componentIndex").u16("_padding");a.VertexLayout=d.newLayout().vec2u8("sideness");a.glVertexLayout=l.glLayout(a.VertexLayout);
a.CommonInstancesLayout=d.newLayout().vec3f("position0").vec3f("position1").u16("componentIndex").u8("variantOffset",{glNormalized:!0}).u8("variantStroke").u8("variantExtension",{glNormalized:!0}).u8("_padding",{glPadding:!0}).u16("_padding2",{glPadding:!0});a.RegularEdgeInstancesLayout=a.CommonInstancesLayout.clone().vec3f("normal");a.SilhouetteEdgeInstancesLayout=a.CommonInstancesLayout.clone().vec3f("normalA").vec3f("normalB");a.EdgeShaderAttributeLocations={position0:0,position1:1,componentIndex:2,
variantOffset:4,variantStroke:5,variantExtension:6,normal:7,normalA:7,normalB:8,sideness:9}})},"esri/views/3d/support/buffer/glUtil":function(){define(["require","exports","../../../../core/tsSupport/assignHelper"],function(q,a,l){Object.defineProperty(a,"__esModule",{value:!0});var d={divisor:0};a.glLayout=function(a,m){void 0===m&&(m={});m=l({},d,m);var k=a.stride;return a.fieldNames.filter(function(d){d=a.fields.get(d).optional;return!(d&&d.glPadding)}).map(function(d){var l=a.fields.get(d),c=
l.constructor.ElementCount;var b=g[l.constructor.ElementType];if(!b)throw Error("BufferType not supported in WebGL");return{name:d,stride:k,count:c,type:b,offset:l.offset,normalized:!(!l.optional||!l.optional.glNormalized),divisor:m.divisor}})};var g={u8:5121,u16:5123,u32:5125,i8:5120,i16:5122,i32:5124,f32:5126}})},"esri/views/3d/webgl-engine/lib/edgeRendering/edgeBufferWriters":function(){define("require exports ../../../../../core/tsSupport/assignHelper ../../../../../core/tsSupport/extendsHelper ../../../../../core/RandomLCG ../../../../../core/libs/gl-matrix-2/vec3 ../../../../../core/libs/gl-matrix-2/vec3f64 ../../../support/buffer/glUtil ./bufferLayouts".split(" "),
function(q,a,l,d,g,p,m,k,n){Object.defineProperty(a,"__esModule",{value:!0});var r=function(){function a(){}a.prototype.updateSettings=function(a){this.settings=a};a.prototype.write=function(a,d,h){var g=c;g[0]=h.position0[0];g[1]=h.position0[1];g[2]=h.position0[2];g[3]=h.position1[0];g[4]=h.position1[1];g[5]=h.position1[2];e[0]=5381;for(g=0;g<b.length;g++)e[0]=31*e[0]+b[g];f.seed=e[0];var g=f.getIntRange(0,255),k=f.getIntRange(0,this.settings.variants-1),l=f.getFloat(),l=-(1-Math.min(l/.7,1))+Math.max(0,
l-.7)/(1-.7),l=255*(Math.pow(Math.abs(l),1.2)*(0>l?-1:1)*.5+.5);a.position0.setVec(d,h.position0);a.position1.setVec(d,h.position1);a.componentIndex.set(d,h.componentIndex);a.variantOffset.set(d,g);a.variantStroke.set(d,k);a.variantExtension.set(d,l)};a.prototype.trim=function(a,b){return a.slice(0,b)};return a}();a.CommonBufferWriter=r;var c=new Float32Array(6),b=new Uint32Array(c.buffer),e=new Uint32Array(1),f=new g;q=function(){function a(){this.commonWriter=new r}a.prototype.updateSettings=function(a){this.commonWriter.updateSettings(a)};
a.prototype.allocate=function(a){return n.RegularEdgeInstancesLayout.createBuffer(a)};a.prototype.write=function(a,b,c){this.commonWriter.write(a,b,c);p.vec3.add(h,c.faceNormal0,c.faceNormal1);p.vec3.normalize(h,h);a.normal.setVec(b,h)};a.prototype.trim=function(a,b){return this.commonWriter.trim(a,b)};a.Layout=n.RegularEdgeInstancesLayout;a.glLayout=k.glLayout(n.RegularEdgeInstancesLayout,{divisor:1});return a}();a.RegularEdgeBufferWriter=q;q=function(){function a(){this.commonWriter=new r}a.prototype.updateSettings=
function(a){this.commonWriter.updateSettings(a)};a.prototype.allocate=function(a){return n.SilhouetteEdgeInstancesLayout.createBuffer(a)};a.prototype.write=function(a,b,c){this.commonWriter.write(a,b,c);a.normalA.setVec(b,c.faceNormal0);a.normalB.setVec(b,c.faceNormal1)};a.prototype.trim=function(a,b){return this.commonWriter.trim(a,b)};a.Layout=n.SilhouetteEdgeInstancesLayout;a.glLayout=k.glLayout(n.SilhouetteEdgeInstancesLayout,{divisor:1});return a}();a.SilhouetteEdgeBufferWriter=q;var h=m.vec3f64.create()})},
"esri/core/libs/gl-matrix-2/vec3f64":function(){define(["require","exports","./factories/vec3f64"],function(q,a,l){Object.defineProperty(a,"__esModule",{value:!0});a.vec3f64=l})},"esri/views/3d/webgl-engine/lib/edgeRendering/edgePreprocessing":function(){define("require exports ../../../../../core/arrayUtils ../../../../../core/mathUtils ../../../../../core/typedArrayUtil ../../../../../core/libs/gl-matrix-2/vec3 ../../../../../core/libs/gl-matrix-2/vec3f64 ../../../support/mathUtils".split(" "),
function(q,a,l,d,g,p,m,k){function n(a,c){var e=d.acosClamped(a.cosAngle),f=b.fwd,h=b.ortho;k.directionFromTo(f,a.position1,a.position0);a=0<p.vec3.dot(p.vec3.cross(h,a.faceNormal0,a.faceNormal1),f)?-1:1;return e*a>c}function r(a){var b=a.faces.length/3,c=a.faces;a=a.neighbors;for(var e=0,d=0;d<b;d++)var f=a[3*d+0],h=a[3*d+1],g=a[3*d+2],k=c[3*d+0],l=c[3*d+1],m=c[3*d+2],e=e+(-1===f||k<l?1:0),e=e+(-1===h||l<m?1:0),e=e+(-1===g||m<k?1:0);for(var e=new Int32Array(4*e),n=0,d=0;d<b;d++){f=a[3*d+0];h=a[3*
d+1];g=a[3*d+2];k=c[3*d+0];l=c[3*d+1];m=c[3*d+2];if(-1===f||k<l)e[n++]=k,e[n++]=l,e[n++]=d,e[n++]=f;if(-1===h||l<m)e[n++]=l,e[n++]=m,e[n++]=d,e[n++]=h;if(-1===g||m<k)e[n++]=m,e[n++]=k,e[n++]=d,e[n++]=g}return e}function c(a){var b=a.faces.length/3,c=a.vertices.position;a=a.faces;for(var d=e.v0,f=e.v1,h=e.v2,g=new Float32Array(3*b),k=0;k<b;k++){var l=a[3*k+1],m=a[3*k+2];c.getVec(a[3*k+0],d);c.getVec(l,f);c.getVec(m,h);p.vec3.subtract(f,f,d);p.vec3.subtract(h,h,d);p.vec3.cross(d,f,h);p.vec3.normalize(d,
d);g[3*k+0]=d[0];g[3*k+1]=d[1];g[3*k+2]=d[2]}return g}Object.defineProperty(a,"__esModule",{value:!0});a.extractEdges=function(a,e,k,m){void 0===m&&(m=f);var h=a.vertices.position,q=a.vertices.componentIndex,z=d.deg2rad(m.anglePlanar);m=d.deg2rad(m.angleSignificantEdge);var t=Math.cos(m),w=Math.cos(z),u=b.edge,B=u.position0,J=u.position1,D=u.faceNormal0,F=u.faceNormal1,A=c(a),C=r(a),G=C.length/4;a=e.allocate(G);m=0;var N=k.allocate(G),O=0,P=0,Q=0,R=l.range(0,G),H=new Float32Array(G);g.forEach(H,function(a,
b,c){h.getVec(C[4*b+0],B);h.getVec(C[4*b+1],J);c[b]=p.vec3.distance(B,J)});R.sort(function(a,b){return H[b]-H[a]});for(var S=[],T=[],K=0;K<G;K++){var y=R[K],L=H[y],M=C[4*y+0],V=C[4*y+1],E=C[4*y+2],y=C[4*y+3],U=-1===y;h.getVec(M,B);h.getVec(V,J);if(U)p.vec3.set(D,A[3*E+0],A[3*E+1],A[3*E+2]),p.vec3.copy(F,D),u.componentIndex=q.get(M),u.cosAngle=p.vec3.dot(D,F);else{p.vec3.set(D,A[3*E+0],A[3*E+1],A[3*E+2]);p.vec3.set(F,A[3*y+0],A[3*y+1],A[3*y+2]);u.componentIndex=q.get(M);u.cosAngle=p.vec3.dot(D,F);
if(u.cosAngle>w)continue;-.9999>u.cosAngle&&p.vec3.copy(F,D)}P+=L;Q++;U||u.cosAngle<t?(e.write(a,m++,u),S.push(L)):n(u,z)&&(k.write(N,O++,u),T.push(L))}q=new Float32Array(S.reverse());z=new Float32Array(T.reverse());return{regular:{instancesData:e.trim(a,m),lodInfo:{lengths:q}},silhouette:{instancesData:k.trim(N,O),lodInfo:{lengths:z}},averageEdgeLength:P/Q}};var b={edge:{position0:m.vec3f64.create(),position1:m.vec3f64.create(),faceNormal0:m.vec3f64.create(),faceNormal1:m.vec3f64.create(),componentIndex:0,
cosAngle:0},ortho:m.vec3f64.create(),fwd:m.vec3f64.create()},e={v0:m.vec3f64.create(),v1:m.vec3f64.create(),v2:m.vec3f64.create()},f={anglePlanar:4,angleSignificantEdge:35}})},"esri/views/3d/support/mathUtils":function(){define(["require","exports","../../../core/mathUtils","../../../core/libs/gl-matrix-2/vec3","../../../core/libs/gl-matrix-2/vec3f64"],function(q,a,l,d,g){function p(a){for(var b in a){var c=a[b];c instanceof Function&&(a[b]=c.bind(a))}return a}Object.defineProperty(a,"__esModule",
{value:!0});a.cosCapped=function(a,c){return a>c?Math.cos(c):Math.cos(a)};a.fovx2fovy=function(a,c,d){return 2*Math.atan(d*Math.tan(.5*a)/c)};a.fovy2fovx=function(a,c,d){return 2*Math.atan(c*Math.tan(.5*a)/d)};a.maxScale=function(a){return Math.sqrt(Math.max(Math.max(a[0]*a[0]+a[4]*a[4]+a[8]*a[8],a[1]*a[1]+a[5]*a[5]+a[9]*a[9]),a[2]*a[2]+a[6]*a[6]+a[10]*a[10]))};a.scaleFromMatrix=function(a,c){d.vec3.set(a,Math.sqrt(c[0]*c[0]+c[4]*c[4]+c[8]*c[8]),Math.sqrt(c[1]*c[1]+c[5]*c[5]+c[9]*c[9]),Math.sqrt(c[2]*
c[2]+c[6]*c[6]+c[10]*c[10]));return a};a.makeOrthonormal=function(a,c,f){f=f||a;var b=d.vec3.dot(a,c);d.vec3.set(f,a[0]-b*c[0],a[1]-b*c[1],a[2]-b*c[2]);d.vec3.normalize(f,f)};a.tangentFrame=function(a,c,f){Math.abs(a[0])>Math.abs(a[1])?d.vec3.set(c,0,1,0):d.vec3.set(c,1,0,0);d.vec3.cross(f,a,c);d.vec3.normalize(c,c);d.vec3.cross(c,f,a);d.vec3.normalize(f,f)};a.moduloPositive=function(a,c){return(a%c+c)%c};a.cartesianToSpherical=function(a,c){var b=d.vec3.length(a),e=l.asinClamped(a[2]/b);d.vec3.set(c,
b,e,Math.atan2(a[1]/b,a[0]/b));return c};a.sphericalToCartesian=function(a,c){var b=a[0],e=a[1];a=a[2];var g=Math.cos(e);d.vec3.set(c,b*g*Math.cos(a),b*g*Math.sin(a),b*Math.sin(e))};a.directionFromTo=function(a,c,d){var b=d[0]-c[0],e=d[1]-c[1];c=d[2]-c[2];d=b*b+e*e+c*c;if(!d)return a[0]=0,a[1]=0,a[2]=0,a;d=1/Math.sqrt(d);a[0]=b*d;a[1]=e*d;a[2]=c*d;return a};a.bilerp=function(a,c,d,h,g,k){a+=(c-a)*g;return a+(d+(h-d)*g-a)*k};a.slerp=function(a,e,f,h){void 0===h&&(h=g.vec3f64.create());var b=d.vec3.length(a),
k=d.vec3.length(e),l=d.vec3.dot(a,e)/(b*k);if(.9999999999999999>l){var l=Math.acos(l),m=((1-f)*b+f*k)/Math.sin(l),k=m/k*Math.sin(f*l);d.vec3.scale(r,a,m/b*Math.sin((1-f)*l));d.vec3.scale(c,e,k);return d.vec3.add(h,r,c)}return d.vec3.lerp(h,a,e,f)};a.angle=function(a,e,f){a=d.vec3.normalize(r,a);e=d.vec3.normalize(c,e);var b=l.acosClamped(d.vec3.dot(a,e));return f&&(a=d.vec3.cross(n,a,e),0>d.vec3.dot(a,f))?-b:b};a.makePiecewiseLinearFunction=function(a){var b=a.length;return function(c){if(c<=a[0][0])return a[0][1];
if(c>=a[b-1][0])return a[b-1][1];for(var e=1;c>a[e][0];)e++;var d=a[e][0];c=(d-c)/(d-a[e-1][0]);return c*a[e-1][1]+(1-c)*a[e][1]}};a.vectorEquals=function(a,c){if(null==a||null==c)return a!==c;if(a.length!==c.length)return!1;for(var b=0;b<a.length;b++)if(a[b]!==c[b])return!1;return!0};q=function(){function a(a,b){this.min=a;this.max=b;this.range=b-a}a.prototype.ndiff=function(a,b){void 0===b&&(b=0);return Math.ceil((a-b)/this.range)*this.range+b};a.prototype._normalize=function(a,b,c,d){void 0===
d&&(d=0);c-=d;c<a?c+=this.ndiff(a-c):c>b&&(c-=this.ndiff(c-b));return c+d};a.prototype.normalize=function(a,b){return this._normalize(this.min,this.max,a,b)};a.prototype.clamp=function(a,b){void 0===b&&(b=0);return l.clamp(a-b,this.min,this.max)+b};a.prototype.monotonic=function(a,b,c){return a<b?b:b+this.ndiff(a-b,c)};a.prototype.minimalMonotonic=function(a,b,c){return this._normalize(a,a+this.range,b,c)};a.prototype.center=function(a,b,c){b=this.monotonic(a,b,c);return this.normalize((a+b)/2,c)};
a.prototype.diff=function(a,b,c){return this.monotonic(a,b,c)-a};a.prototype.shortestSignedDiff=function(a,b){a=this.normalize(a);b=this.normalize(b);var c=b-a;a=b<a?this.minimalMonotonic(a,b)-a:b-this.minimalMonotonic(b,a);return Math.abs(c)<Math.abs(a)?c:a};a.prototype.contains=function(a,b,c){b=this.minimalMonotonic(a,b);c=this.minimalMonotonic(a,c);return c>a&&c<b};return a}();a.Cyclical=q;a.planeFromPoints=function(a,c,f,g){d.vec3.subtract(m,c,a);d.vec3.subtract(k,f,a);d.vec3.cross(g,m,k);d.vec3.normalize(g,
g);g[3]=-d.vec3.dot(a,g)};var m=g.vec3f64.create(),k=g.vec3f64.create();a.cyclical2PI=p(new q(0,2*Math.PI));a.cyclicalPI=p(new q(-Math.PI,Math.PI));a.cyclicalDeg=p(new q(0,360));var n=g.vec3f64.create(),r=g.vec3f64.create(),c=g.vec3f64.create()})},"*noref":1}});
define("require exports ../../../../../core/tsSupport/awaiterHelper ../../../../../core/tsSupport/generatorHelper ../../../../../core/typedArrayUtil ../../../../../geometry/support/meshUtils/deduplicate ../../../support/meshProcessing ../../../support/buffer/workerHelper ./bufferLayouts ./edgeBufferWriters ./edgePreprocessing".split(" "),function(q,a,l,d,g,p,m,k,n,r,c){return function(){function a(){this.regularWriter=new r.RegularEdgeBufferWriter;this.silhouetteWriter=new r.SilhouetteEdgeBufferWriter}
a.prototype.process=function(a,b){return l(this,void 0,void 0,function(){var c,e,f;return d(this,function(d){switch(d.label){case 0:if(!b)return[3,2];c=[];e=this.packInput(a,c);this.wrappedWork;return[4,b.invoke("wrappedWork",e,{transferList:c})];case 1:return f=d.sent(),[2,this.unpackOutput(f)];case 2:return[2,this.work(a)]}})})};a.prototype.wrappedWork=function(a){return l(this,void 0,void 0,function(){var b,c,e,g;return d(this,function(d){b=this.unpackInput(a);c=this.work(b);e=[];this.packInputTransferables(b,
e);g=this.packOutput(c,e);return[2,{result:g,transferList:e}]})})};a.prototype.work=function(a){var b=this.extractEdgeInformation(a.data,a.skipDeduplicate,a.originalIndices);this.regularWriter.updateSettings(a.writerSettings);this.silhouetteWriter.updateSettings(a.writerSettings);return c.extractEdges(b,this.regularWriter,this.silhouetteWriter)};a.prototype.packInputTransferables=function(a,b){b.push(a.data.buffer)};a.prototype.packInput=function(a,b){this.packInputTransferables(a,b);b={dataBuffer:a.data.buffer,
writerSettings:a.writerSettings,skipDeduplicate:a.skipDeduplicate};a.originalIndices&&(b.originalIndicesBuffer=a.originalIndices.buffer,b.originalIndicesType=g.isUint32Array(a.originalIndices)?"Uint32Array":"Uint16Array");return b};a.prototype.unpackInput=function(a){return{data:n.EdgeInputBufferLayout.createView(a.dataBuffer),originalIndices:"Uint32Array"===a.originalIndicesType?new Uint32Array(a.originalIndicesBuffer):"Uint16Array"===a.originalIndicesType?new Uint16Array(a.originalIndicesBuffer):
void 0,writerSettings:a.writerSettings,skipDeduplicate:a.skipDeduplicate}};a.prototype.packOutput=function(a,b){b.push(a.regular.lodInfo.lengths.buffer);b.push(a.silhouette.lodInfo.lengths.buffer);return{regular:{instancesData:k.packInterleavedBuffer(a.regular.instancesData,b),lodInfo:{lengths:a.regular.lodInfo.lengths.buffer}},silhouette:{instancesData:k.packInterleavedBuffer(a.silhouette.instancesData,b),lodInfo:{lengths:a.silhouette.lodInfo.lengths.buffer}},averageEdgeLength:a.averageEdgeLength}};
a.prototype.unpackOutput=function(a){return{regular:{instancesData:k.unpackInterleavedBuffer(a.regular.instancesData),lodInfo:{lengths:new Float32Array(a.regular.lodInfo.lengths)}},silhouette:{instancesData:k.unpackInterleavedBuffer(a.silhouette.instancesData),lodInfo:{lengths:new Float32Array(a.silhouette.lodInfo.lengths)}},averageEdgeLength:a.averageEdgeLength}};a.prototype.extractEdgeInformation=function(a,b,c){if(b&&c)return b=m.computeNeighbors(c,a.count),{faces:c,neighbors:b,vertices:a};a=p.default(a.buffer,
a.stride/4,{originalIndices:c});b=m.computeNeighbors(a.indices,a.uniqueCount);return{faces:a.indices,neighbors:b,vertices:n.EdgeInputBufferLayout.createView(a.buffer)}};return a}()});