// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/Accessor ../../../core/compilerUtils ../../../core/Handles ../../../core/watchUtils ../../../core/accessorSupport/decorators ./PanoramicAtmosphere ./RealisticAtmosphere ./SimpleAtmosphere ./Stars".split(" "),function(t,u,h,d,k,l,m,e,c,n,g,p,q){var r=[12,13];return function(f){function a(){var b=null!==f&&f.apply(this,arguments)||this;b._handles=new m;b._initContext=null;b._pendingAtmosphere=
null;b._atmosphere=null;b._stars=null;return b}h(a,f);Object.defineProperty(a.prototype,"canRender",{get:function(){return!(!this.view.basemapTerrain||!this.view.basemapTerrain.renderer.canRender)||"global"!==this.view.viewingMode},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"updating",{get:function(){return null!=this._pendingAtmosphere},enumerable:!0,configurable:!0});a.prototype.initialize=function(){this.view._stage.addRenderPlugin(r,this)};a.prototype.destroy=function(){this._pendingAtmosphere&&
(this._pendingAtmosphere.destroy(),this._pendingAtmosphere=null);this._atmosphere&&(this._atmosphere.destroy(),this._atmosphere=null);this._stars&&(this._stars.destroy(),this._stars=null);this._handles&&this._handles.removeAll();this.view&&(this.view._stage.removeRenderPlugin(this),this._set("view",null))};a.prototype.initializeRenderContext=function(b){this._initContext=b;this.setup()};a.prototype.setup=function(){var b=this;this._handles.add(e.when(this.view,"basemapTerrain",function(){return b._updateBasemapTerrain()},
!0));this._handles.add([e.init(this.view,["viewingMode","environment.atmosphereEnabled","environment.atmosphere.quality"],function(){return b._updateAtmosphere()},!0),e.init(this.view,"environment.starsEnabled",function(){return b._updateStars()},!0)])};a.prototype.uninitializeRenderContext=function(){this._stars&&(this._stars.uninitializeRenderContext(),this._stars.destroy(),this._stars=null);this._atmosphere&&(this._atmosphere.uninitializeRenderContext(),this._atmosphere.destroy(),this._atmosphere=
null)};a.prototype.render=function(b){var a=!0;this._stars&&this._stars.canRender&&(a=this._stars.render(b)&&a);this._atmosphere&&this._atmosphere.canRender&&(a=this._atmosphere.render(b)&&a);return a};a.prototype._setNeedsRender=function(){this._initContext&&this._initContext.requestRender()};a.prototype._updateStars=function(){var b=this.view.get("environment.starsEnabled")||!1;b&&!this._stars?(this._stars=new q(this.view),this._stars.initializeRenderContext(this._initContext),this._setNeedsRender()):
!b&&this._stars&&(this._stars.destroy(),this._stars=null,this._setNeedsRender())};a.prototype._updateAtmosphere=function(){var b=this,a=this._getAtmosphereType();this.atmosphereType!==a&&(this.atmosphereType=a,this._pendingAtmosphere&&(this._pendingAtmosphere!==this._atmosphere&&this._pendingAtmosphere.destroy(),this._pendingAtmosphere=null),(a=this._getAtmosphereClass())?(a=new a(this.view),a.initializeRenderContext(this._initContext),null==this._atmosphere&&(this._atmosphere=a,this._setNeedsRender()),
this._pendingAtmosphere=a,a.when(function(){b._pendingAtmosphere!==b._atmosphere&&(b._atmosphere.destroy(),b._atmosphere=b._pendingAtmosphere);b._pendingAtmosphere=null;b._setNeedsRender();b._updateBasemapTerrain()})):(this._atmosphere&&(this._atmosphere.destroy(),this._atmosphere=null,this._setNeedsRender()),this._updateBasemapTerrain()))};a.prototype._getAtmosphereClass=function(){var a=this._getAtmosphereType();if(this.atmosphereClassFromType)return this.atmosphereClassFromType(a);switch(a){case "none":return null;
case "realistic":return g.RealisticAtmosphere;case "panoramic":return n;case "simple":return p;default:l.neverReached(a)}};a.prototype._getAtmosphereType=function(){var a=this.view.get("environment.atmosphereEnabled"),c=this.view.get("environment.atmosphere.quality");return a&&null!=c?"local"===this.view.viewingMode?"panoramic":"high"===c&&g.RealisticAtmosphere.isSupported(this._initContext)?"realistic":"simple":"none"};a.prototype._updateBasemapTerrain=function(){var a=this.view.basemapTerrain;a&&
(a.velvetOverground=null!=this._atmosphere&&"simple"===this.atmosphereType)};Object.defineProperty(a.prototype,"test",{get:function(){return{atmosphere:this._atmosphere}},enumerable:!0,configurable:!0});d([c.property({constructOnly:!0})],a.prototype,"view",void 0);d([c.property({constructOnly:!0})],a.prototype,"atmosphereClassFromType",void 0);d([c.property({dependsOn:["_pendingAtmosphere"]})],a.prototype,"updating",null);d([c.property()],a.prototype,"_pendingAtmosphere",void 0);return a=d([c.subclass("esri.views.3d.environment.EnvironmentRenderer")],
a)}(c.declared(k))});