// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../../../core/Handles ../../../core/watchUtils ../../../core/libs/gl-matrix-2/vec2 ../../../core/libs/gl-matrix-2/vec2f64 ../../../core/libs/gl-matrix-2/vec3 ../../../core/libs/gl-matrix-2/vec3f64 ../../../core/libs/gl-matrix-2/vec4 ../../../core/libs/gl-matrix-2/vec4f64 ./atmosphereUtils ../support/earthUtils ../support/buffer/glUtil ../support/buffer/InterleavedLayout ../webgl-engine/shaders/RealisticAtmospherePrograms ../../webgl/BufferObject ../../webgl/programUtils ../../webgl/renderState ../../webgl/VertexArrayObject".split(" "),
function(g,n,E,F,G,w,p,l,e,f,x,q,y,r,H,I,v,J,z,h,K){Object.defineProperty(n,"__esModule",{value:!0});g=function(){function b(a){this._view=a;this.canRender=!0;this._skyslot=12;this._hazeSlot=13;this._renderData={texDepth:l.vec2f64.create(),cameraPosition:f.vec3f64.create(),cameraUp:f.vec3f64.create(),cameraRight:f.vec3f64.create(),cameraDir:f.vec3f64.create(),halfSizeNearPlane:l.vec2f64.create(),cameraCenterOffset:l.vec2f64.create(),sphereComp:q.vec4f64.create(),atmosParams1:q.vec4f64.create(),atmosParams2:q.vec4f64.create(),
atmosParams3:f.vec3f64.create(),invWavelength:A,invWavelengthScaled:m,radii:l.vec2f64.create(),scale:0,scaleDepth:t,lowerAlphaBlendBound:0,scaleOverScaleDepth:0,oneOverScaleDepth:0,scaleDepthBlue:u,oneOverScaleDepthBlue:B,scaleOverScaleDepthBlue:0,g:d,g2:d*d,miePhaseCoefficients:C,nearFar:l.vec2f64.create(),cameraHeight:0,cameraHeightSq:0,C:0,CSur:0,innerFadeDistance:0,altitudeFade:0};this._lowerElevationBoundRadius=0;this._earthRadius=r.earthRadius;this._updateRadius(r.earthRadius)}b.prototype.destroy=
function(){this._handles&&(this._handles.destroy(),this._handles=null);this._hazeProgram&&(this._hazeProgram.dispose(),this._hazeProgram=null);this._skyProgram&&(this._skyProgram.dispose(),this._skyProgram=null);this._vao&&(this._vao.dispose(),this._vao=null)};b.prototype.when=function(a){return F(this,void 0,void 0,function(){return E(this,function(c){a();return[2]})})};b.prototype.initializeRenderContext=function(a){var c=this;a=a.rctx;this._handles=new G;this._updateElevation({spatialReference:this._view.basemapTerrain.spatialReference,
tile:this._view.basemapTerrain.rootTiles[0],extent:this._view.basemapTerrain.rootTiles[0].extent,context:"ground"});this._handles.add(w.on(this._view,"basemapTerrain","elevation-change",function(a){return c._updateElevation(a)},function(){return c._updateElevation()}));this._handles.add(w.on(this._view,"basemapTerrain","elevation-bounds-change",function(){return c._updateVisibleElevationBounds()},function(){return c._updateVisibleElevationBounds()}));this._hazeProgram=z.createProgram(a,v.program,
{haze:!0});this._skyProgram=z.createProgram(a,v.program);this._hazePipelineState=h.makePipelineState({blending:h.separateBlendingParams(1,0,769,1),colorWrite:h.defaultColorWriteParams});this._skyPipelineState=h.makePipelineState({blending:h.separateBlendingParams(770,1,771,771),depthTest:{func:515},colorWrite:h.defaultColorWriteParams});this._vao=this._createVertexArrayObject(a)};b.prototype.uninitializeRenderContext=function(){this.destroy()};b.prototype.render=function(a){if(a.slot!==this._hazeSlot&&
a.slot!==this._skyslot||0!==a.pass)return!1;this._update(a.camera);a.slot===this._skyslot&&this._renderSky(a);a.slot===this._hazeSlot&&this._renderHaze(a);return!0};b.prototype._renderSky=function(a){var c=a.rctx,b=this._skyProgram;c.bindProgram(b);c.setPipelineState(this._skyPipelineState);b.setUniform3fv("atmosParams3",this._renderData.atmosParams3);this._renderCommon(b,a)};b.prototype._renderHaze=function(a){var c=this,b=a.rctx,d=a.offscreenRenderingHelper,e=this._hazeProgram;b.bindProgram(e);
b.setPipelineState(this._hazePipelineState);d.renderDepthDetached(function(){b.bindTexture(d.depthTexture,0);e.setUniform1i("depthTex",0);c._renderCommon(e,a)})};b.prototype._renderCommon=function(a,c){var b=c.rctx;a.setUniform3fv("invWavelength",this._renderData.invWavelength);a.setUniform3fv("invWavelengthScaled",this._renderData.invWavelengthScaled);c.scenelightingData.setLightDirectionUniform(a);a.setUniform4fv("sphereComp",this._renderData.sphereComp);a.setUniform3fv("cameraPosition",this._renderData.cameraPosition);
a.setUniform3fv("cameraUp",this._renderData.cameraUp);a.setUniform3fv("cameraRight",this._renderData.cameraRight);a.setUniform3fv("cameraDir",this._renderData.cameraDir);a.setUniform2fv("nearFar",this._renderData.nearFar);a.setUniform2fv("halfSizeNearPlane",this._renderData.halfSizeNearPlane);a.setUniform2fv("cameraCenterOffset",this._renderData.cameraCenterOffset);a.setUniform2fv("radii",this._renderData.radii);a.setUniform4fv("atmosParams1",this._renderData.atmosParams1);a.setUniform4fv("atmosParams2",
this._renderData.atmosParams2);a.setUniform1f("innerFadeDistance",this._renderData.innerFadeDistance);a.setUniform1f("altitudeFade",this._renderData.altitudeFade);b.bindVAO(this._vao);a.assertCompatibleVertexAttributeLocations(this._vao);b.drawArrays(5,0,4)};b.prototype._createVertexArrayObject=function(a){var c=D.createBuffer(4);c.position.setVec(0,[-1,-1,1]);c.position.setVec(1,[1,-1,1]);c.position.setVec(2,[-1,1,1]);c.position.setVec(3,[1,1,1]);c.uv0.setVec(0,[0,0]);c.uv0.setVec(1,[1,0]);c.uv0.setVec(2,
[0,1]);c.uv0.setVec(3,[1,1]);return new K(a,v.program.attributes,{geometry:H.glLayout(D)},{geometry:J.createVertex(a,35044,c.buffer)})};b.prototype._adjustRadiusForTesselation=function(a){return a*Math.cos(Math.PI/Math.pow(2,4)/16)};b.prototype._updateElevation=function(a){a=a?a.tile:this._view.basemapTerrain.rootTiles[0];0===a.lij[0]&&(a=this._adjustRadiusForTesselation(r.earthRadius+a.elevationBounds[0]),a!==this._lowerElevationBoundRadius&&(this._lowerElevationBoundRadius=a,this._earthRadius=-1,
this._updateVisibleElevationBounds()))};b.prototype._updateVisibleElevationBounds=function(){var a=this._adjustRadiusForTesselation(r.earthRadius+this._view.basemapTerrain.elevationBounds.min);(0>this._earthRadius||a<this._earthRadius)&&this._updateRadius(a)};b.prototype._updateRadius=function(a){this._earthRadius=a;var c=a/10*10.25,b=1/(c-a),f=b/t,g=b/u,h=.3*(c-a)+a,k=this._renderData;x.vec4.set(k.atmosParams1,b,t,f,L);x.vec4.set(k.atmosParams2,d,u,g,B);e.vec3.set(k.atmosParams3,d*d,C,h);p.vec2.set(k.radii,
a,c);k.scale=b;k.lowerAlphaBlendBound=h;k.scaleOverScaleDepth=f;k.scaleOverScaleDepthBlue=g;c=y.INNER_ATMOSPHERE_DEPTH;k.innerFadeDistance=2*Math.sqrt((2*a-c)*c)};b.prototype._update=function(a){a&&(e.vec3.negate(this._renderData.cameraDir,a.viewForward),e.vec3.copy(this._renderData.cameraUp,a.viewUp),e.vec3.copy(this._renderData.cameraRight,a.viewRight),this._renderData.cameraHeight=e.vec3.length(a.eye),this._renderData.cameraHeightSq=this._renderData.cameraHeight*this._renderData.cameraHeight,this._renderData.C=
this._renderData.cameraHeightSq-this._renderData.radii[1]*this._renderData.radii[1],this._renderData.CSur=this._renderData.cameraHeightSq-this._renderData.radii[0]*this._renderData.radii[0],this._renderData.sphereComp=q.vec4f64.fromValues(this._renderData.cameraHeight,this._renderData.cameraHeightSq,this._renderData.C,this._renderData.CSur),e.vec3.copy(this._renderData.cameraPosition,a.eye),p.vec2.set(this._renderData.halfSizeNearPlane,Math.tan(a.fovX/2)/(a.width/a.fullWidth),Math.tan(a.fovY/2)/(a.height/
a.fullHeight)),p.vec2.set(this._renderData.cameraCenterOffset,(a.padding[3]+a.width/2)/a.fullWidth-.5,(a.padding[2]+a.height/2)/a.fullHeight-.5),p.vec2.set(this._renderData.nearFar,a.near,a.far),this._renderData.altitudeFade=y.computeInnerAltitudeFade(this._renderData.cameraHeight-this._earthRadius))};b.isSupported=function(a){return a.rctx.capabilities.depthTexture};return b}();n.RealisticAtmosphere=g;n=.02*Math.PI;g=.004*Math.PI;var A=f.vec3f64.fromValues(1/Math.pow(.65,4),1/Math.pow(.57,4),1/Math.pow(.475,
4)),m=f.vec3f64.clone(A);e.vec3.scale(m,m,n);e.vec3.add(m,m,f.vec3f64.fromValues(g,g,g));var t=.25,u=.05,L=1/t,B=1/u,d=-.99999,C=(1-d*d)/(2+d*d)*1.5,D=I.newLayout().vec3f("position").vec2f("uv0")});