// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../../../core/mathUtils ../../../core/mathUtils ../../../core/promiseUtils ../../../core/watchUtils ../../../core/libs/gl-matrix-2/mat4 ../../../core/libs/gl-matrix-2/mat4f64 ../../../core/libs/gl-matrix-2/vec2 ../../../core/libs/gl-matrix-2/vec2f64 ../../../core/libs/gl-matrix-2/vec3 ../../../core/libs/gl-matrix-2/vec3f64 ./atmosphereUtils ./resources/SimpleAtmosphereTexture ../support/earthUtils ../support/imageUtils ../support/mathUtils ../support/buffer/glUtil ../support/buffer/InterleavedLayout ../webgl-engine/lib/glUtil3D ../webgl-engine/lib/Util ../webgl-engine/shaders/SimpleAtmospherePrograms ../../webgl/BufferObject ../../webgl/programUtils ../../webgl/renderState ../../webgl/Texture ../../webgl/Util ../../webgl/VertexArrayObject".split(" "),
function(u,aa,F,G,H,I,v,J,K,L,M,N,k,m,w,O,l,P,Q,R,S,T,x,p,U,y,q,V,z,W){function A(h,c,b,a,f){var e=k.vec3.length(h),g=a*Math.sqrt(e*e-a*a)/e,d=f.silCircleV1,l=f.silCircleV2;k.vec3.scale(f.silCircleCenter,h,Math.sqrt(a*a-g*g)/e);k.vec3.cross(d,h,c);1>k.vec3.squaredLength(d)&&k.vec3.cross(d,h,b);k.vec3.scale(d,d,g/k.vec3.length(d));k.vec3.cross(l,d,h);k.vec3.scale(l,l,g/k.vec3.length(l));return g}function B(h,c,b,a){k.vec3.add(n,a.silCircleCenter,a.silCircleV2);k.vec3.scale(r,n,C);K.mat4.lookAt(t,c,
n,b);x.project(n,t,h.projectionMatrix,h.viewport);x.project(r,t,h.projectionMatrix,h.viewport);return k.vec3.distance(n,r)/h.height}var D=-w.INNER_ATMOSPHERE_DEPTH,X=(l.earthRadius+D)/l.earthRadius,Y=(l.earthRadius+0)/l.earthRadius,C=(l.earthRadius+3E5)/l.earthRadius,Z=Q.makePiecewiseLinearFunction([[50,.1015625],[500,.21875],[5E3,.51171875],[5E4,.4140625]]);u=function(){function h(c){this.slot=12;this._renderData={texV:N.vec2f64.create(),silCircleCenter:m.vec3f64.create(),silCircleV1:m.vec3f64.create(),
silCircleV2:m.vec3f64.create(),altitudeFade:0,innerScale:0,undergroundFadeAlpha:0};this._fadeVaoCount=0;this._readyResolver=v.createResolver();this._readyController=v.createAbortController();this.view=c}Object.defineProperty(h.prototype,"canRender",{get:function(){return null!=this._texture},enumerable:!0,configurable:!0});h.prototype.when=function(c){return G(this,void 0,void 0,function(){return F(this,function(b){switch(b.label){case 0:return[4,this._readyResolver.promise];case 1:return b.sent(),
c(),[2]}})})};h.prototype.initializeRenderContext=function(c){var b=this,a=c.rctx;this._cameraChangeHandle=J.init(this.view,"state.camera",function(){return c.requestRender()},!0);this._program=y.createProgram(a,p.colorPass);this._fadeProgram=y.createProgram(a,p.fadePass);this._vao=this._createRibbon(a);this._vaoCount=z.vertexCount(this._vao,"geometry");this._fadeVao=T.createQuadVAO(a);this._fadeVaoCount=z.vertexCount(this._fadeVao,"geometry");P.requestImage(O,{signal:this._readyController.signal}).then(function(f){b._texture=
new V(a,{pixelFormat:6408,dataType:5121,wrapMode:33071,samplingMode:9729,flipped:!0},f);c.requestRender();b._readyController=null;b._readyResolver.resolve()});this._pipelineState=q.makePipelineState({blending:q.separateBlendingParams(770,1,771,771),depthTest:{func:515},colorWrite:q.defaultColorWriteParams})};h.prototype.uninitializeRenderContext=function(){this.destroy()};h.prototype.destroy=function(){this._readyResolver.reject();this._cameraChangeHandle&&(this._cameraChangeHandle.remove(),this._cameraChangeHandle=
null);this._texture&&(this._texture.dispose(),this._texture=null);this._program&&(this._program.dispose(),this._program=null);this._fadeProgram&&(this._fadeProgram.dispose(),this._fadeProgram=null);this._fadeVao&&(this._fadeVao.dispose(),this._fadeVao=null);this._readyController&&(this._readyController.abort(),this._readyController=null)};h.prototype.render=function(c){if(c.slot!==this.slot||0!==c.pass)return!1;this._update(c.camera);var b=c.rctx;b.setPipelineState(this._pipelineState);if(1>this._renderData.undergroundFadeAlpha){var a=
this._program;b.bindProgram(a);a.setUniformMatrix4fv("proj",c.camera.projectionMatrix);a.setUniformMatrix4fv("view",c.camera.viewMatrix);a.setUniform3fv("silCircleCenter",this._renderData.silCircleCenter);a.setUniform3fv("silCircleV1",this._renderData.silCircleV1);a.setUniform3fv("silCircleV2",this._renderData.silCircleV2);a.setUniform2fv("texV",this._renderData.texV);b.bindTexture(this._texture,0);a.setUniform1i("tex",0);c.scenelightingData.setLightDirectionUniform(a);a.setUniform1f("altitudeFade",
this._renderData.altitudeFade);a.setUniform1f("innerScale",this._renderData.innerScale);b.bindVAO(this._vao);b.drawArrays(4,0,this._vaoCount)}0<this._renderData.undergroundFadeAlpha&&(a=this._fadeProgram,b.bindProgram(a),a.setUniform1f("undergroundFadeAlpha",this._renderData.undergroundFadeAlpha),c.scenelightingData.setLightDirectionUniform(a),a.setUniform3fv("cameraPosition",c.camera.eye),b.bindVAO(this._fadeVao),b.drawArrays(5,0,this._fadeVaoCount));return!0};h.prototype._update=function(c){var b=
m.vec3f64.create(),a=l.earthRadius,f=k.vec3.length(c.eye),e=f-a;this._renderData.undergroundFadeAlpha=0>e?Math.min(-e/5E3,1):0;var g=a+D,d=a+Math.max(50,e);this._renderData.innerScale=d*d/(Math.sqrt(d*d-a*a)*Math.sqrt(d*d-g*g)+a*g)-1;this._renderData.altitudeFade=w.computeInnerAltitudeFade(e);k.vec3.scale(b,c.eye,(a+50)/f);A(b,c.center,c.up,a,this._renderData);b=B(c,b,c.up,this._renderData);f=Z(e);g=.001953125;d=0+b*f*1;50<e&&(A(c.eye,c.center,c.up,a,this._renderData),c=B(c,c.eye,c.up,this._renderData),
c=H.clamp((c-1.5)/(b-1.5),0,1),g=0+.001953125*c,d=0+1*I.lerp(1,b*f,c));M.vec2.set(this._renderData.texV,g,d)};h.prototype._createRibbon=function(c){var b=new Float32Array(1155),a=new Uint32Array(1920);b[0]=0;b[1]=0;b[2]=-1;for(var f=0;128>f;f++){var e=9*f+3;b[e+0]=f;b[e+1]=X;b[e+2]=-1;b[e+3]=f;b[e+4]=Y;b[e+5]=0;b[e+6]=f;b[e+7]=C;b[e+8]=1;var e=3*f+1,g=127===f?1:e+3,d=15*f;a[d+0]=e;a[d+1]=e+1;a[d+2]=g+1;a[d+3]=g+1;a[d+4]=g;a[d+5]=e;a[d+6]=e+1;a[d+7]=e+2;a[d+8]=g+2;a[d+9]=g+2;a[d+10]=g+1;a[d+11]=e+
1;a[d+12]=e;a[d+13]=g;a[d+14]=0}e=E.createBuffer(a.length);g=e.position;for(f=0;f<a.length;++f)d=3*a[f],g.set(f,0,b[d]),g.set(f,1,b[d+1]),g.set(f,2,b[d+2]);return new W(c,p.colorPass.attributes,{geometry:R.glLayout(E)},{geometry:U.createVertex(c,35044,e.buffer)})};return h}();var t=L.mat4f64.create(),n=m.vec3f64.create(),r=m.vec3f64.create(),E=S.newLayout().vec3f("position");return u});