// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../../../request ../../../core/asyncUtils ../../../core/Error ../../../core/Logger ../../../core/promiseUtils ../../../core/watchUtils ../../../core/libs/gl-matrix-2/mat4 ../../../core/libs/gl-matrix-2/mat4f64 ../support/buffer/glUtil ../support/buffer/InterleavedLayout ../webgl-engine/shaders/StarsPrograms ../../webgl/BufferObject ../../webgl/programUtils ../../webgl/renderState ../../webgl/VertexArrayObject".split(" "),
function(w,p,x,y,z,A,q,B,r,C,f,k,D,E,t,F,G,m,H){var u=B.getLogger("esri.views.3d.environment.Stars");p=function(){function d(a){this.slot=12;this.numBinaryFloats=2;this.numBinaryUInt8=1;this.bytesPerStar=9;this._loadDataController=r.createAbortController();this._numStars=0;this._modelMatrix=k.mat4f64.create();this.view=a;this._loadDataPromise=this._loadBrightStarCatalogue()}Object.defineProperty(d.prototype,"canRender",{get:function(){return null!=this._vao},enumerable:!0,configurable:!0});d.prototype.destroy=
function(){this._loadDataController&&(this._loadDataController.abort(),this._loadDataController=null);this._dateHandle&&(this._dateHandle.remove(),this._dateHandle=null);this._program&&(this._program.dispose(),this._program=null);this._vao&&(this._vao.dispose(),this._vao=null)};d.prototype.initializeRenderContext=function(a){var b=this;this._initContext=a;var c=a.rctx;this._program=G.createProgram(c,t.program);this._pipelineState=m.makePipelineState({blending:m.separateBlendingParams(770,1,771,771),
depthTest:{func:515},colorWrite:m.defaultColorWriteParams});this._dateHandle=C.init(this.view,"environment.lighting.date",function(a){return b._update(a)});this._loadDataPromise.then(function(){b._numStars=b._starData.byteLength/b.bytesPerStar;var d=new Float32Array(b._starData,0,b._numStars*b.numBinaryFloats),g=new Uint8Array(b._starData,b._numStars*b.numBinaryFloats*4,b._numStars*b.numBinaryUInt8);b._vao=b._createVertexArrayObject(c,d,g);a.requestRender()})};d.prototype.uninitializeRenderContext=
function(){this.destroy()};d.prototype.render=function(a){if(a.slot!==this.slot||0!==a.pass)return!1;var b=a.rctx,c=this._program;b.bindProgram(c);a=a.camera;c.setUniformMatrix4fv("view",a.viewMatrix);c.setUniformMatrix4fv("proj",a.projectionMatrix);c.setUniform4fv("viewport",a.fullViewport);c.setUniformMatrix4fv("model",this._modelMatrix);c.setUniform1f("pixelRatio",a.pixelRatio);b.setPipelineState(this._pipelineState);b.bindVAO(this._vao);c.assertCompatibleVertexAttributeLocations(this._vao);b.drawArrays(0,
0,this._numStars);return!0};d.prototype._computeDayDuration=function(a){var b=new Date(a.getFullYear(),0,1,11,58,56),c=new Date(a.getFullYear()+1,0,1,11,58,55);return(+a-+b)/(+c-+b)};d.prototype._update=function(a){if(a){var b=a.getHours()/12,c=a.getMinutes()/60*(2/24),d=a.getSeconds()/60*(2/1440),b=(b+c+d-.9972222)%2;a=2*this._computeDayDuration(a);c=this._modelMatrix;f.mat4.copy(c,I);f.mat4.rotateZ(c,c,-a*Math.PI);f.mat4.multiply(c,J,c);f.mat4.rotateZ(c,c,-b*Math.PI);this._initContext.requestRender()}};
d.prototype._hexToRGB=function(a){return[parseInt(a.substring(0,2),16),parseInt(a.substring(2,4),16),parseInt(a.substring(4,6),16)]};d.prototype._unpackUint8Attributes=function(a){return 192<=a?[2.9,a-192]:160<=a?[2.5,a-160]:128<=a?[2,a-128]:96<=a?[1.5,a-96]:64<=a?[1,a-64]:32<=a?[.7,a-32]:[.4,a]};d.prototype._createVertexArrayObject=function(a,b,c){for(var d=v.createBuffer(this._numStars),g=d.position,f=d.color,k=d.size,e=0;e<this._numStars;e++){var l=b[2*e+0],h=b[2*e+1];g.set(e,0,-Math.cos(l)*Math.sin(h));
g.set(e,1,-Math.sin(l)*Math.sin(h));g.set(e,2,-Math.cos(h));l=this._unpackUint8Attributes(c[e]);h=this._hexToRGB(K[l[1]]);f.set(e,0,255*h[0]);f.set(e,1,255*h[1]);f.set(e,2,255*h[2]);f.set(e,3,255);k.set(e,l[0])}return new H(a,t.program.attributes,{geometry:D.glLayout(v)},{geometry:F.createVertex(a,35044,d.buffer)})};d.prototype._verifyStartData=function(a){if(!a)throw new q("stars:no-data-received","Failed to create stars because star catalogue is missing");a=a.byteLength/this.bytesPerStar;if(0!==
a%1||5E4<a||5E3>a)throw new q("stars:invalid-data","Failed to create stars because star catalogue data is invalid");};d.prototype._loadBrightStarCatalogue=function(){return y(this,void 0,void 0,function(){var a,b,c;return x(this,function(d){switch(d.label){case 0:return n?(this._starData=n,[2]):[4,A.result(z(w.toUrl("./resources/stars.wsv"),{responseType:"array-buffer",signal:this._loadDataController.signal}))];case 1:a=d.sent();this._loadDataController=null;if(!1===a.ok){if(r.isAbortError(a.error))throw a.error;
u.error("loadBrightStarCatalogue",a.error.message);return[2]}b=a.value;c=b.data;try{this._verifyStartData(c)}catch(g){throw u.error("loadBrightStarCatalogue",g),g;}this._starData=n=c;return[2]}})})};return d}();var K="9bb2ff;9eb5ff;aabfff;bbccff;ccd8ff ;dae2ff;e4e9ff;eeefff;f8f6ff;fff9fb;fff5ef;fff1e5;ffeddb;ffe9d2;ffe6ca;ffe3c3;ffe0bb;ffddb4;ffdaad;ffd6a5;ffd29c;ffcc8f;ffc178;ffa94b;ff7b00".split(";"),J=k.mat4f64.fromValues(1,0,0,0,0,.9174771405229186,.39778850739794974,0,0,-.39778850739794974,.9174771405229186,
0,0,0,0,1),I=k.mat4f64.fromValues(1,0,0,0,0,.9174771405229186,-.39778850739794974,0,0,.39778850739794974,.9174771405229186,0,0,0,0,1),v=E.newLayout().vec3f("position").vec4u8("color").f32("size"),n=null;return p});