// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/libs/gl-matrix-2/vec3f64 ../../../../core/libs/gl-matrix-2/vec4f64 ../../support/debugFlags ../../webgl-engine/lib/intersectorUtils ./Camera ./DefaultVertexBufferLayouts ./DrapedUpdates ./glUtil3D ./GridLocalOriginFactory ./Renderer ./TextureTechnique ../lighting/Lightsources ../materials/ColorMaterial ../materials/HUDMaterial ../materials/RibbonLineMaterial ../../../webgl/FramebufferObject ../../../webgl/Texture ../../../webgl/Util".split(" "),function(r,
L,q,x,t,y,z,A,B,C,D,E,u,F,G,H,I,J,K,v){r=function(){function b(a,c,d,e,h,f,b){var g=this;this._renderTargets={};this._clearColor=x.vec4f64.fromValues(0,0,0,0);this._uniqueIdx=0;this._localOrigins=new D;this.longitudeCyclical=null;this._rctx=a;this._canvas=c;this._testTextureTechniqueConfig=new u.TextureTechniqueConfiguration;this._testTextureTechniqueConfig.hasAlpha=!0;this._testTextureTechnique=f.acquireAndReleaseExisting(u.TextureTechnique,this._testTextureTechniqueConfig,this._testTextureTechnique);
this._modelDirtySet=b;this._modelDirtySet.onMaterialChanged=function(){return g._emitContentChanged()};this._renderer=new E(d,e,h,f,this._rctx,"draped",function(){return g._emitContentChanged()});this._updates=new B.DrapedUpdates(this._renderer,{emitContentChanged:function(){return g._emitContentChanged()},emitUpdatingChanged:function(){return g._emitUpdatingChanged()}});this._renderer.onHasHighlightsChanged=function(a){if(g.onHasHighlightsChanged)g.onHasHighlightsChanged(a)};this._renderer.setLighting({lights:[new F.AmbientLight(q.vec3f64.fromValues(1,
1,1))],groundLightingFactor:1,globalFactor:0})}b.prototype.dispose=function(){for(var a in this._renderTargets)this._renderTargets[a].dispose();this._renderTargets=null;this._renderer.dispose();this._renderer=null;this._updates.dispose();this._updates=null};b.prototype.disposeRenderTarget=function(a){var c=this._renderTargets[a];c&&c.dispose();delete this._renderTargets[a]};Object.defineProperty(b.prototype,"updating",{get:function(){return this._updates.updating},enumerable:!0,configurable:!0});
b.prototype.commitChanges=function(){this._updates.commitChanges()};b.prototype.getRenderTargetTexture=function(a){return(a=this._renderTargets[a])?a.colorTexture:null};b.prototype.addRenderGeometries=function(a){for(var c=0;c<a.length;c++){var d=a[c];null==d.origin&&(d.origin=this._localOrigins.getOrigin(d.center));d.idx=this._uniqueIdx++}this._updates.add(a)};b.prototype.removeRenderGeometries=function(a){this._updates.remove(a)};b.prototype.updateRenderGeometries=function(a,c){this._updates.modify(a,
c)};b.prototype.updateRenderOrder=function(a){0<a.size&&(this._renderer.modifyRenderOrder(),this._emitContentChanged())};b.prototype.setBackgroundColor=function(a){this._clearColor=a;this._emitContentChanged()};b.prototype.updateHighlights=function(a){this._updates.modify(a,16)};b.prototype.isEmpty=function(){return this._renderer.isEmpty()&&!t.OVERLAY_DRAW_TEST_TEXTURE};b.prototype.processDirtyMaterials=function(){var a=this._modelDirtySet.getDirtyMaterials();a&&this._renderer.modify(null,0,null,
0,null,0,a);this._modelDirtySet.clearDirtyMaterials()};Object.defineProperty(b.prototype,"hasHighlights",{get:function(){return this._renderer.hasHighlights},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"hasWater",{get:function(){return this._renderer.hasWater},enumerable:!0,configurable:!0});b.prototype.draw=function(a,c){return this.drawPass(0,a,c)};b.prototype.drawNormals=function(a,c){return this.drawPass(2,a,c)};b.prototype.drawHighlights=function(a,c){return this.drawPass(4,
a,c)};b.prototype.drawPass=function(a,c,d){var e=this;if(0===d.numViews)return!1;this._pixelRatio=d.pixelRatio*Math.abs(d.views[0].extent[2]-d.views[0].extent[0])/Math.abs(d.views[0].viewport[2]-d.views[0].viewport[0]);if(this.isEmpty()||4===a&&!this.hasHighlights||2===a&&!this.hasWater)return!1;this.processDirtyMaterials();if(!this._hasNonZeroSizedView(d))return!1;c=this._renderTargets[c];if(!c)return!1;var h=this._rctx,f=d.width,b=d.height;c.width===f&&c.height===b||c.resize(f,b);var l=k.camera;
k.fbo=c;k.views=d.views;k.numViews=d.numViews;k.predraw=t.OVERLAY_DRAW_TEST_TEXTURE?function(){return e._drawTestTexture(f,b,w[d.index%w.length])}:null;l.near=1;l.far=1E4;l.pixelRatio=d.pixelRatio||1;h.bindFramebuffer(c);h.setClearColor.apply(h,this._clearColor);h.clearSafe(16384);this._renderer.renderGeometryPassDraped(a,k);h.bindFramebuffer(null);h.setViewport(0,0,this._canvas.width,this._canvas.height);c.colorTexture.descriptor.hasMipmap&&c.colorTexture.generateMipmap();k.views=null;k.numViews=
0;k.fbo=null;return!0};b.prototype._hasNonZeroSizedView=function(a){for(var c=0;c<a.numViews;c++){var d=a.views[c];if(d.extent[0]!==d.extent[2]&&d.extent[1]!==d.extent[3])return!0}return!1};b.prototype._drawTestTexture=function(a,c,d){var e=this._rctx;if(!this._testPatternTexture){for(var b=new Uint8Array(a*c*4),f=0,g=0;g<c;g++)for(var l=0;l<a;l++){var k=Math.floor(l/10),m=Math.floor(g/10);2>k||2>m||10*k>a-20||10*m>c-20?(b[f++]=255,b[f++]=255,b[f++]=255,b[f++]=255):(b[f++]=255,b[f++]=255,b[f++]=255,
k&1&&m&1?b[f++]=l&1^g&1?0:255:b[f++]=k&1^m&1?0:128)}this._testPatternTexture=new K(e,{target:3553,pixelFormat:6408,dataType:5121,samplingMode:9728,width:a,height:c},b);this._testPatternProgram=this._testTextureTechnique.program;this._testPatternPipelineState=this._testTextureTechnique.pipeline;this._quadVAO=C.createQuadVAO(e,A.Pos3Tex)}a=this._testPatternProgram;e.bindProgram(a);e.setPipelineState(this._testPatternPipelineState);a.setUniform4f("color",d[0],d[1],d[2],1);a.setUniform1i("tex",0);e.bindTexture(this._testPatternTexture,
0);e.bindVAO(this._quadVAO);e.drawArrays(5,0,v.vertexCount(this._quadVAO,"geometry"))};b.prototype.updateLogic=function(a){return this._renderer.updateLogic(a)};b.prototype._emitContentChanged=function(){if(this.onContentChanged)this.onContentChanged()};b.prototype._emitUpdatingChanged=function(){if(this.onUpdatingChanged)this.onUpdatingChanged()};b.prototype.createRenderTarget=function(a,c,b,e){for(var d=a,f=0;this._renderTargets[d];)d=a+"_"+ ++f;this._renderTargets[d]=new J(this._rctx,{colorTarget:0,
depthStencilTarget:0},{target:3553,pixelFormat:6408,dataType:5121,wrapMode:33071,samplingMode:e,hasMipmap:c,maxAnisotropy:b,width:0,height:0});return d};b.prototype.getGpuMemoryUsage=function(){var a=0,c;for(c in this._renderTargets)a+=v.getGpuMemoryUsage(this._renderTargets[c]);return a};b.prototype.intersect=function(a,c,b){var e=this,d=0;this._renderer.forEachRenderGeometry(function(f){if(!b||b(f)){if(f.material instanceof G||f.material instanceof I||f.material instanceof H){e.intersectRenderGeometry(f,
c,0,a,d);var g=e.longitudeCyclical;g&&(f.center[0]-f.bsRadius<g.min&&e.intersectRenderGeometry(f,c,g.range,a,d),f.center[0]+f.bsRadius>g.max&&e.intersectRenderGeometry(f,c,-g.range,a,d))}d++}})};b.prototype.intersectRenderGeometry=function(a,c,b,e,h){var d=this;b+=a.transformation[12];var g=a.transformation[13];n[0]=c[0]-b;n[1]=c[1]-g;n[2]=1;p[0]=c[0]-b;p[1]=c[1]-g;p[2]=0;a.pixelRatio=this._pixelRatio;a.material.intersect(a,null,a.getShaderTransformation(),e,n,p,function(b,c,f){d.addIntersectionResult(f,
a.material.renderPriority,h,e,a.data.layerUid,a.data.graphicUid)},a.calculateShaderTransformation,!0)};b.prototype.addIntersectionResult=function(a,b,d,e,h,f){var c={type:"external",metadata:{layerUid:h,graphicUid:f}};h=function(f){f.set(c,null,e.results.terrain.dist,e.results.terrain.normal,e.results.terrain.transformation,b,null,null,a,d);f.intersector="DrapedRenderer"};(null==e.results.min.drapedLayerOrder||b>=e.results.min.drapedLayerOrder)&&(null==e.results.min.dist||e.results.terrain.dist<=
e.results.min.dist)&&h(e.results.min);0!==e.options.store&&(null==e.results.max.drapedLayerOrder||b<e.results.max.drapedLayerOrder)&&(null==e.results.max.dist||e.results.terrain.dist>e.results.max.dist)&&h(e.results.max);2===e.options.store&&(f=new y.IntersectorResult(e.ray),h(f),e.results.all.push(f))};Object.defineProperty(b.prototype,"test",{get:function(){return{renderer:this._renderer}},enumerable:!0,configurable:!0});return b}();var w=[[1,.5,.5],[.5,.5,1],[.5,1,.5]],k={fbo:null,camera:new z.default,
views:null,numViews:0},n=q.vec3f64.create(),p=q.vec3f64.create();return r});