// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/ObjectPool ../../../../core/PooledArray ../../../../core/libs/gl-matrix-2/vec3 ../../../../core/libs/gl-matrix-2/vec3f64 ../../support/geometryUtils ./Util".split(" "),function(G,Q,N,v,p,g,q,H){function z(c,a,b){b=b||c;b[0]=c[0]+a;b[1]=c[1]+a;b[2]=c[2]+a;return b}function A(c,a,b){return!q.frustum.intersectsSphere(b.planes,q.sphere.wrap(a,c))}function O(c,a,b){if(!w.length)for(var e=0;8>e;++e)w.push({index:0,distance:0});for(e=0;8>e;++e){var d=I[e];w.data[e].index=
e;w.data[e].distance=x(c,a,d)}w.sort(function(a,b){return a.distance-b.distance});b.clear();for(e=0;8>e;++e)b.push(w.data[e].index)}function C(c,a){for(var b=Infinity,e=null,d=0;8>d;++d){var r=x(c,a,J[d]);r<b&&(b=r,e=J[d])}return e}function x(c,a,b){return a*(c[0]*b[0]+c[1]*b[1]+c[2]*b[2])}G=function(){function c(a,b,e,d){this._maximumObjectsPerNode=10;this._maximumDepth=20;this._degenerateObjects=new Set;this._objectCount=0;this._objectToBoundingSphere=e;d&&(void 0!==d.maximumObjectsPerNode&&(this._maximumObjectsPerNode=
d.maximumObjectsPerNode),void 0!==d.maximumDepth&&(this._maximumDepth=d.maximumDepth));isNaN(a[0])||isNaN(a[1])||isNaN(a[2])||isNaN(b)?this._root=new f(null,g.vec3f64.fromValues(0,0,0),.5):this._root=new f(null,a,b/2)}Object.defineProperty(c.prototype,"center",{get:function(){return this._root.center},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"size",{get:function(){return 2*this._root.halfSize},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"root",{get:function(){return this._root.node},
enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"maximumObjectsPerNode",{get:function(){return this._maximumObjectsPerNode},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"maximumDepth",{get:function(){return this._maximumDepth},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"objectCount",{get:function(){return this._objectCount},enumerable:!0,configurable:!0});c.prototype.destroy=function(){this._degenerateObjects.clear();this._root=null;f.clearPool();
D=[null];u.prune();w.prune();E.prune()};c.prototype.add=function(a,b){a=this._objectOrObjectsArray(a);b=null==b?a.length:b;this._objectCount+=b;this._grow(a,b);for(var e=f.acquire(),d=0;d<b;d++){var c=a[d];e.init(this._root);this._isDegenerate(c)?this._degenerateObjects.add(c):this._add(c,e)}f.release(e)};c.prototype.remove=function(a,b){a=this._objectOrObjectsArray(a);this._objectCount-=a.length;for(var e=f.acquire(),d=0;d<a.length;d++){var c=a[d],h=b||this._boundingSphereFromObject(c,K);this._isValidRadius(h.radius)?
(e.init(this._root),this._remove(c,h,e)):this._degenerateObjects.delete(c)}f.release(e);this._shrink()};c.prototype.update=function(a,b){if(this._isValidRadius(b.radius)||!this._isDegenerate(a))this.remove(a,b),this.add(a)};c.prototype.forEachAlongRay=function(a,b,e){var d=this,c=q.ray.wrap(a,b);this._forEachNode(this._root,function(a){if(!d._intersectsNode(c,a))return!1;a=a.node;a.terminals.forEach(function(a){d._intersectsObject(c,a)&&e(a)});null!==a.residents&&a.residents.forEach(function(a){d._intersectsObject(c,
a)&&e(a)});return!0})};c.prototype.forEachAlongRayWithVerticalOffset=function(a,b,e,d){var c=this,h=q.ray.wrap(a,b);this._forEachNode(this._root,function(a){if(!c._intersectsNodeWithOffset(h,a,d))return!1;a=a.node;a.terminals.forEach(function(a){c._intersectsObjectWithOffset(h,a,d)&&e(a)});null!==a.residents&&a.residents.forEach(function(a){c._intersectsObjectWithOffset(h,a,d)&&e(a)});return!0})};c.prototype.forEach=function(a){this._forEachNode(this._root,function(b){b=b.node;b.terminals.forEach(a);
null!==b.residents&&b.residents.forEach(a);return!0});this._degenerateObjects.forEach(a)};c.prototype.forEachDegenerateObject=function(a){this._degenerateObjects.forEach(a)};c.prototype.findClosest=function(a,b,e,d,c){return this._findClosest(a,"front-to-back"===b?1:-1,e,d,c)};c.prototype.forEachInDepthRange=function(a,b,e,d,c,h,l,g){this._forEachInDepthRange(a,b,"front-to-back"===e?1:-1,d,c,h,l,g)};c.prototype.forEachNode=function(a){this._forEachNode(this._root,function(b){return a(b.node,b.center,
2*b.halfSize)})};c.prototype._intersectsNode=function(a,b){z(b.center,2*-b.halfSize,k);z(b.center,2*b.halfSize,m);return H.rayBoxTest(a.origin,a.direction,k,m)};c.prototype._intersectsNodeWithOffset=function(a,b,e){z(b.center,2*-b.halfSize,k);z(b.center,2*b.halfSize,m);e.applyToMinMax(k,m);return H.rayBoxTest(a.origin,a.direction,k,m)};c.prototype._intersectsObject=function(a,b){var e=this._objectToBoundingSphere.getRadius(b);return 0<e?q.sphere.intersectsRay(q.sphere.wrap(e,this._objectToBoundingSphere.getCenter(b)),
a):!0};c.prototype._intersectsObjectWithOffset=function(a,b,e){var d=this._objectToBoundingSphere.getRadius(b);return 0<d?q.sphere.intersectsRay(e.applyToBoundingSphere(d,this._objectToBoundingSphere.getCenter(b)),a):!0};c.prototype._forEachNode=function(a,b){a=f.acquire().init(a);for(var e=[a];0!==e.length;){a=e.pop();if(b(a)&&!a.isLeaf())for(var d=0;d<a.node.children.length;d++)a.node.children[d]&&e.push(f.acquire().init(a).advance(d));f.release(a)}};c.prototype._forEachNodeDepthOrdered=function(a,
b,e,d){void 0===d&&(d=1);a=f.acquire().init(a);var c=[a];for(O(e,d,E);0!==c.length;){a=c.pop();if(b(a)&&!a.isLeaf())for(e=7;0<=e;--e)d=E.data[e],d>=a.node.children.length||a.node.children[d]&&c.push(f.acquire().init(a).advance(d));f.release(a)}};c.prototype._findClosest=function(a,b,e,c,g){var d=this,l=Infinity,r=Infinity,f=null,k=C(a,b),m=0,q=function(g){++m;if(!c||c(g)){var h=d._objectToBoundingSphere.getCenter(g),n=d._objectToBoundingSphere.getRadius(g);if(!e||!A(h,n,e)){var h=x(a,b,h),k=h-n;k<
l&&(l=k,r=h+n,f=g)}}};this._forEachNodeDepthOrdered(this._root,function(c){if(null!=g&&m>=g||e&&A(c.center,c.halfSize*L,e))return!1;p.vec3.scale(t,k,c.halfSize);p.vec3.add(t,t,c.center);if(x(a,b,t)>r)return!1;c=c.node;c.terminals.forEach(function(a){q(a)});null!==c.residents&&c.residents.forEach(function(a){q(a)});return!0},a,b);return f};c.prototype._forEachInDepthRange=function(a,b,e,c,g,h,l,f){var d=this,r=-Infinity,n=Infinity,k={setRange:function(a){1===e?(r=Math.max(r,a.near),n=Math.min(n,a.far)):
(r=Math.max(r,-a.far),n=Math.min(n,-a.near))}};k.setRange(c);var m=x(b,e,a),q=C(b,e),w=C(b,-1*e),u=0,v=function(a){++u;if(!l||l(a)){var c=d._objectToBoundingSphere.getCenter(a),f=d._objectToBoundingSphere.getRadius(a),p=x(b,e,c)-m;p-f>n||p+f<r||h&&A(c,f,h)||g(a,k)}};this._forEachNodeDepthOrdered(this._root,function(a){if(null!=f&&u>=f||h&&A(a.center,a.halfSize*L,h))return!1;p.vec3.scale(t,q,a.halfSize);p.vec3.add(t,t,a.center);if(x(b,e,t)-m>n)return!1;p.vec3.scale(t,w,a.halfSize);p.vec3.add(t,t,a.center);
if(x(b,e,t)-m<r)return!1;a=a.node;a.terminals.forEach(function(a){v(a)});null!==a.residents&&a.residents.forEach(function(a){v(a)});return!0},b,e)};c.prototype._objectOrObjectsArray=function(a){if(Array.isArray(a))return a;D[0]=a;return D};c.prototype._remove=function(a,b,c){u.clear();b=c.advanceTo(b,function(a,b){u.push(a.node);u.push(b)})?c.node.terminals:c.node.residents;b.removeUnordered(a);if(0===b.length)for(a=u.length-2;0<=a&&this._purge(u.data[a],u.data[a+1]);a-=2);};c.prototype._nodeIsEmpty=
function(a){if(0!==a.terminals.length)return!1;if(null!==a.residents)return 0===a.residents.length;for(var b=0;b<a.children.length;b++)if(a.children[b])return!1;return!0};c.prototype._purge=function(a,b){0<=b&&(a.children[b]=null);return this._nodeIsEmpty(a)?(null===a.residents&&(a.residents=new v({shrink:!0})),!0):!1};c.prototype._add=function(a,b){b.advanceTo(this._boundingSphereFromObject(a,K))?b.node.terminals.push(a):(b.node.residents.push(a),b.node.residents.length>this._maximumObjectsPerNode&&
b.depth<this._maximumDepth&&this._split(b))};c.prototype._split=function(a){var b=a.node.residents;a.node.residents=null;for(var c=0;c<b.length;c++){var d=f.acquire().init(a);this._add(b.data[c],d);f.release(d)}};c.prototype._grow=function(a,b){var c=this;0!==b&&(a=this._boundingSphereFromObjects(a,b,function(a,b){return c._boundingSphereFromObject(a,b)},y),this._isValidRadius(a.radius)&&!this._fitsInsideTree(a)&&(this._nodeIsEmpty(this._root.node)?(p.vec3.copy(this._root.center,a.center),this._root.halfSize=
1.25*a.radius):(b=f.acquire(),this._rootBoundsForRootAsSubNode(a,b),this._placingRootViolatesMaxDepth(b)?this._rebuildTree(a,b):this._growRootAsSubNode(b),f.release(b))))};c.prototype._rebuildTree=function(a,b){var c=this;p.vec3.copy(F.center,b.center);F.radius=b.halfSize;a=this._boundingSphereFromObjects([a,F],2,function(a){return a},P);b=f.acquire().init(this._root);this._root.initFrom(null,a.center,1.25*a.radius);this._forEachNode(b,function(a){c.add(a.node.terminals.data,a.node.terminals.length);
null!==a.node.residents&&c.add(a.node.residents.data,a.node.residents.length);return!0});f.release(b)};c.prototype._placingRootViolatesMaxDepth=function(a){var b=0;this._forEachNode(this._root,function(a){b=Math.max(b,a.depth);return!0});return b+Math.log(a.halfSize/this._root.halfSize)*Math.LOG2E>this._maximumDepth};c.prototype._rootBoundsForRootAsSubNode=function(a,b){var c=a.radius,d=a.center;a=-Infinity;for(var g=this._root.center,h=this._root.halfSize,l=0;3>l;l++){var f=Math.max(0,Math.ceil((g[l]-
h-(d[l]-c))/(2*h))),k=Math.max(0,Math.ceil((d[l]+c-(g[l]+h))/(2*h)))+1;a=Math.max(a,Math.pow(2,Math.ceil(Math.log(f+k)*Math.LOG2E)));B[l].min=f;B[l].max=k}for(l=0;3>l;l++)f=B[l].min,k=B[l].max,c=(a-(f+k))/2,f+=Math.ceil(c),k+=Math.floor(c),M[l]=g[l]-h-f*h*2+(k+f)*h;return b.initFrom(null,M,a*h,0)};c.prototype._growRootAsSubNode=function(a){var b=this._root.node;p.vec3.copy(y.center,this._root.center);y.radius=this._root.halfSize;this._root.init(a);a.advanceTo(y,null,!0);a.node.children=b.children;
a.node.residents=b.residents;a.node.terminals=b.terminals};c.prototype._shrink=function(){for(;;){var a=this._findShrinkIndex();if(-1===a)break;this._root.advance(a);this._root.depth=0}};c.prototype._findShrinkIndex=function(){if(0!==this._root.node.terminals.length||this._root.isLeaf())return-1;for(var a=null,b=this._root.node.children,c=0,d=0;d<b.length&&null==a;)c=d++,a=b[c];for(;d<b.length;)if(b[d++])return-1;return c};c.prototype._isDegenerate=function(a){a=this._objectToBoundingSphere.getRadius(a);
return!this._isValidRadius(a)};c.prototype._isValidRadius=function(a){return!isNaN(a)&&-Infinity!==a&&Infinity!==a&&0<a};c.prototype._fitsInsideTree=function(a){var b=this._root.center,c=this._root.halfSize,d=a.center;return a.radius<=c&&d[0]>=b[0]-c&&d[0]<=b[0]+c&&d[1]>=b[1]-c&&d[1]<=b[1]+c&&d[2]>=b[2]-c&&d[2]<=b[2]+c};c.prototype._boundingSphereFromObject=function(a,b){p.vec3.copy(b.center,this._objectToBoundingSphere.getCenter(a));b.radius=this._objectToBoundingSphere.getRadius(a);return b};c.prototype._boundingSphereFromObjects=
function(a,b,c,d){if(1===b){var e=c(a[0],y);p.vec3.copy(d.center,e.center);d.radius=e.radius}else{k[0]=Infinity;k[1]=Infinity;k[2]=Infinity;m[0]=-Infinity;m[1]=-Infinity;m[2]=-Infinity;for(var g=0;g<b;g++)if(e=c(a[g],y),this._isValidRadius(e.radius)){var f=k,n=e.center,q=e.radius;f[0]=Math.min(f[0],n[0]-q);f[1]=Math.min(f[1],n[1]-q);f[2]=Math.min(f[2],n[2]-q);f=m;n=e.center;e=e.radius;f[0]=Math.max(f[0],n[0]+e);f[1]=Math.max(f[1],n[1]+e);f[2]=Math.max(f[2],n[2]+e)}p.vec3.lerp(d.center,k,m,.5);d.radius=
Math.max(m[0]-k[0],m[1]-k[1],m[2]-k[2])/2}return d};return c}();var f=function(){function c(a,b,c){void 0===c&&(c=0);this.center=g.vec3f64.create();this.initFrom(a,b,c,0)}c.prototype.init=function(a){return this.initFrom(a.node,a.center,a.halfSize,a.depth)};c.prototype.initFrom=function(a,b,e,d){void 0===a&&(a=null);void 0===e&&(e=this.halfSize);void 0===d&&(d=this.depth);this.node=a||c.createEmptyNode();b&&p.vec3.copy(this.center,b);this.halfSize=e;this.depth=d;return this};c.prototype.advance=function(a){var b=
this.node.children[a];b||(b=c.createEmptyNode(),this.node.children[a]=b);this.node=b;this.halfSize/=2;this.depth++;a=I[a];this.center[0]+=a[0]*this.halfSize;this.center[1]+=a[1]*this.halfSize;this.center[2]+=a[2]*this.halfSize;return this};c.prototype.advanceTo=function(a,b,c){for(void 0===c&&(c=!1);;){if(this.isTerminalFor(a))return b&&b(this,-1),!0;if(this.isLeaf()&&!c)return b&&b(this,-1),!1;this.isLeaf()&&(this.node.residents=null);var d=this._childIndex(a);b&&b(this,d);this.advance(d)}};c.prototype.isLeaf=
function(){return null!=this.node.residents};c.prototype.isTerminalFor=function(a){return a.radius>this.halfSize/2};c.prototype._childIndex=function(a){a=a.center;for(var b=this.center,c=0,d=0;3>d;d++)b[d]<a[d]&&(c|=1<<d);return c};c.createEmptyNode=function(){return{children:[null,null,null,null,null,null,null,null],terminals:new v({shrink:!0}),residents:new v({shrink:!0})}};c.acquire=function(){return c._pool.acquire()};c.release=function(a){c._pool.release(a)};c.clearPool=function(){c._pool.prune()};
c._pool=new N(c);return c}(),I=[g.vec3f64.fromValues(-1,-1,-1),g.vec3f64.fromValues(1,-1,-1),g.vec3f64.fromValues(-1,1,-1),g.vec3f64.fromValues(1,1,-1),g.vec3f64.fromValues(-1,-1,1),g.vec3f64.fromValues(1,-1,1),g.vec3f64.fromValues(-1,1,1),g.vec3f64.fromValues(1,1,1)],J=[g.vec3f64.fromValues(-1,-1,-1),g.vec3f64.fromValues(-1,-1,1),g.vec3f64.fromValues(-1,1,-1),g.vec3f64.fromValues(-1,1,1),g.vec3f64.fromValues(1,-1,-1),g.vec3f64.fromValues(1,-1,1),g.vec3f64.fromValues(1,1,-1),g.vec3f64.fromValues(1,
1,1)],L=Math.sqrt(3),D=[null],M=g.vec3f64.create(),t=g.vec3f64.create(),k=g.vec3f64.create(),m=g.vec3f64.create(),u=new v,K={center:g.vec3f64.create(),radius:0},y={center:g.vec3f64.create(),radius:0},F={center:g.vec3f64.create(),radius:0},P={center:g.vec3f64.create(),radius:0},B=[{min:0,max:0},{min:0,max:0},{min:0,max:0}],w=new v,E=new v;return G});