// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ./glUtil3D ./RenderTargetHelper ./Util ../shaders/OffscreenPrograms ../../../webgl/renderState ../../../webgl/Util".split(" "),function(q,r,k,l,m,e,d,g){var n=[0,0,0,0],p=[0,1,0,1];return function(){function a(b,c){this.dimensions={width:4,height:4};this._enabled=!1;this._background={type:"color",color:[0,0,0,1]};this._compositePipelineState=new Map;this._rctx=c;c=this.renderTargetHelper=new l.RenderTargetHelper(c);this.mainColor=c.registerColorTarget({name:"mainColor"});this.mainDepth=
c.registerDepthTarget({name:"mainDepth"});this.linearDepth=c.registerColorTarget({name:"linearDepth",samplingMode:9728});this.normal=c.registerColorTarget({name:"normal"});this.highlight=c.registerColorTarget({name:"highlight",dataType:32819});this.hudVisibility=c.registerColorTarget({name:"hudVisibility",dataType:32819});this.tmpColor=c.registerColorTarget({name:"tmpColor"});this.tmpDepth=c.registerDepthTarget({name:"tmpDepth"});this._compositeProgram=b.getProgram(e.composite);this._compositePipelineState.set("none",
d.makePipelineState({colorWrite:d.defaultColorWriteParams}));this._compositePipelineState.set("alpha",d.makePipelineState({blending:d.separateBlendingParams(770,1,771,771),colorWrite:d.defaultColorWriteParams}));this._compositePipelineState.set("premultiplied-alpha",d.makePipelineState({blending:d.simpleBlendingParams(1,771),colorWrite:d.defaultColorWriteParams}));this._compositeTransparentToHUDVisibilityProgram=b.getProgram(e.compositeTransparentToHUDVisibility);this._compositeTransparentToHUDVisibilityPipelineState=
d.makePipelineState({colorWrite:{r:!1,g:!0,b:!1,a:!1}});this._compositeOccludedProgram=b.getProgram(e.compositeOccluded);this._compositeOccludedPipelineState=d.makePipelineState({blending:d.simpleBlendingParams(1,771),colorWrite:d.defaultColorWriteParams})}Object.defineProperty(a.prototype,"width",{get:function(){return this.dimensions.width},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"height",{get:function(){return this.dimensions.height},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,
"enabled",{get:function(){return this._enabled},set:function(b){b?this.enable():this.disable()},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"background",{get:function(){return this._background},set:function(b){this._background=b},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"framebuffer",{get:function(){return this.renderTargetHelper.getFramebuffer(this.dimensions,this.mainColor,this.mainDepth)},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,
"colorTexture",{get:function(){return this.framebuffer.colorTexture},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"depthTexture",{get:function(){return this.framebuffer.depthStencilTexture},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"linearDepthTexture",{get:function(){return this.renderTargetHelper.getAllocatedColorTexture(this.linearDepth)},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"normalTexture",{get:function(){return this.renderTargetHelper.getAllocatedColorTexture(this.normal)},
enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"highlightTexture",{get:function(){return this.renderTargetHelper.getAllocatedColorTexture(this.highlight)},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"hudVisibilityTexture",{get:function(){return this.getColorTexture(this.hudVisibility)},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"tmpColorTexture",{get:function(){return this.getColorTexture(this.tmpColor)},enumerable:!0,configurable:!0});
a.prototype.initializeFrame=function(b,c){m.assert(this.enabled);var a=this._rctx;this.dimensions.width=b.fullWidth;this.dimensions.height=b.fullHeight;this.outputFramebuffer=c;this.bindTarget(this.mainColor,this.mainDepth);a.setClearStencil(0);b=this._background.color;a.setClearColor(b[0]*b[3],b[1]*b[3],b[2]*b[3],b[3]);a.clearSafe(17664)};a.prototype.renderAndComposite=function(b,c){this.renderToTargets(b,this.tmpColor,this.mainDepth,n);this.composite(this.getColorTexture(this.tmpColor),this.framebuffer,
c)};a.prototype.renderHUDVisibility=function(b){this.renderToTargets(b,this.hudVisibility,this.mainDepth,p)};a.prototype.compositeTransparentTerrainOntoHUDVisibility=function(){var b=this,c=this._rctx;this.renderToTargets(function(){var a=b._compositeTransparentToHUDVisibilityProgram;c.bindProgram(a);c.setPipelineState(b._compositeTransparentToHUDVisibilityPipelineState);a.setUniform1i("tex",1);c.bindTexture(b.getColorTexture(b.tmpColor),1);c.bindVAO(b.quadVAO);c.drawArrays(5,0,g.vertexCount(b.quadVAO,
"geometry"))},this.hudVisibility,this.mainDepth)};a.prototype.compositeTransparentTerrainOntoMain=function(){this.composite(this.getColorTexture(this.tmpColor),this.framebuffer,"premultiplied-alpha")};a.prototype.compositeOccludedOntoMain=function(b){var c=this._rctx,a=this._compositeOccludedProgram;this.bindFramebuffer();c.bindProgram(a);c.setPipelineState(this._compositeOccludedPipelineState);c.bindVAO(this.quadVAO);c.bindTexture(this.getColorTexture(this.tmpColor),0);a.setUniform1i("occludedColorMap",
0);a.setUniform1f("opacity",b);c.drawArrays(5,0,g.vertexCount(this.quadVAO,"geometry"));c.bindVAO(null)};a.prototype.bindFramebuffer=function(){this._rctx.bindFramebuffer(this.framebuffer)};a.prototype.renderDepthDetached=function(b){var c=this.bindTarget(this.mainColor);b(c);this.bindTarget(this.mainColor,this.mainDepth)};a.prototype.composite=function(b,c,a){void 0===b&&(b=this.framebuffer.colorTexture);void 0===c&&(c=this.outputFramebuffer);void 0===a&&(a="none");var d=this._rctx,h=this._compositeProgram;
d.bindFramebuffer(c);d.bindProgram(h);d.setPipelineState(this._compositePipelineState.get(a));h.setUniform1i("tex",1);d.bindTexture(b,1);d.bindVAO(this.quadVAO);d.drawArrays(5,0,g.vertexCount(this.quadVAO,"geometry"))};a.prototype.disposeTarget=function(b){this.renderTargetHelper.disposeTargetResource(b)};a.prototype.enable=function(){this.enabled||(this._enabled=!0,this.quadVAO=k.createQuadVAO(this._rctx))};a.prototype.disable=function(){this.enabled&&(this._enabled=!1,this.renderTargetHelper.disposeAllResource(),
this.quadVAO.dispose(!0),this.quadVAO=null)};a.prototype.renderToTargets=function(b,a,d,f,e){var c=this._rctx;a=this.bindTarget(a,d);d=0;f&&(c.setClearColor(f[0],f[1],f[2],Math.max(1E-13,f[3])),d|=16384);e&&(d|=256);c.clearSafe(d);b(a);c.gl.flush();this.bindTarget(this.mainColor,this.mainDepth);return a};a.prototype.bindTarget=function(b,a){b=this.renderTargetHelper.getFramebuffer(this.dimensions,b,a);this._rctx.bindFramebuffer(b);return b};a.prototype.getColorTexture=function(a){return this.renderTargetHelper.getColorTexture(a,
this.dimensions)};a.prototype.getGpuMemoryUsage=function(){var a=0;this.renderTargetHelper&&(a+=this.renderTargetHelper.getGpuMemoryUsage());return a};return a}()});