// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/Logger ./TextureTechnique ./Util ../../../webgl/Texture".split(" "),function(k,t,p,m,h,n){var q=p.getLogger("esri.views.3d.webgl-engine.lib.TextureRepository");k=function(){function c(a,b,f,d,c){this.NUM_PARALLEL=8;this._fallbackTextureTransparent=this._fallbackTexture=null;this.textures=a;this._textureTechniqueConfig=new m.TextureTechniqueConfiguration;this._textureTechnique=b.acquireAndReleaseExisting(m.TextureTechnique,this._textureTechniqueConfig,this._textureTechnique);
this.getViewportToRestore=f;this.onNewlyTexturesLoaded=c;this._rctx=d;this.NUM_PARALLEL=8;this.id2textureRef={};this.loading={};this._queue=[];this.listeners=[];this.maxMaxAnisotropy=(this.afExt=d.capabilities.textureFilterAnisotropic)?d.parameters.maxMaxAnisotropy:1;this.maxAnisotropy=Math.min(8,this.maxMaxAnisotropy);this._fallbackTextureData=new Uint8Array(256);this._fallbackTextureTransparentData=new Uint8Array(256);for(a=0;a<this._fallbackTextureData.length;++a)this._fallbackTextureData[a]=255,
this._fallbackTextureTransparentData[a]=0!==(a+1)%4?255:0;this._fallbackTextureDesc={target:3553,pixelFormat:6408,dataType:5121,samplingMode:9728,width:8,height:8,maxAnisotropy:8};this.onNewlyTexturesLoaded()}c.prototype.acquire=function(a,b,f){var d=this,g=this.id2textureRef[a];if(null==g){var e=this.textures.get(a);h.assert(void 0!==e);e.setUnloadFunc(function(a){return d._unload(a)});b=!0===b;var l=this._createGLTextureDescription(e),g=new c.TextureRef(null);h.assert(null==this.id2textureRef[a]);
this.id2textureRef[a]=g;if(e.initializeThroughRender)a=e.initializeThroughRender(this._rctx,l),g.setGLTexture(a),f&&f(g);else if(e.deferredLoading())this.getLoadingCount()<this.NUM_PARALLEL?this._loadImage(a,l,f):this._queue.push([a,l,f]);else try{e.initializeThroughUpload(this._rctx,l,this._textureTechnique,this.getViewportToRestore(),function(a){g.setGLTexture(a);d.onNewlyTexturesLoaded();f&&f(g)})}catch(r){q.error("#acquire","Error loading texture: "+r.toString())}null==g.getGLTexture()&&g.setGLTexture(b?
this.fallbackTextureTransparent:this.fallbackTexture);this.onNewlyTexturesLoaded()}g.incRefCnt();return g};c.prototype.release=function(a){a=this.id2textureRef[a];void 0!==a&&(a.decRefCnt(),h.assert(0<=a.getRefCnt()))};c.prototype.getLoadingCount=function(){return Object.keys(this.loading).length};c.prototype.getTexture=function(a){return this.textures.get(a)};c.prototype.getMaxAnisotropy=function(){return this.maxAnisotropy};c.prototype._unload=function(a){var b=this.id2textureRef[a];void 0!==b&&
((b=b.getGLTexture())&&b!==this.fallbackTextureTransparent&&b!==this.fallbackTexture&&b.dispose(),delete this.id2textureRef[a]);this.next(a)};c.prototype._createGLTextureDescription=function(a){return{target:3553,pixelFormat:6408,dataType:5121,maxAnisotropy:this.afExt&&a.params&&a.params.mipmap&&!a.params.disableAnisotropy?this.maxAnisotropy:void 0,wrapMode:a.params&&a.params.wrap}};c.prototype.next=function(a){if(a in this.loading){delete this.loading[a];var b=Object.keys(this.id2textureRef),f=Object.keys(this.loading);
this.listeners.forEach(function(d){d(a,b,f)});this.processQueue()}};c.prototype._loadImage=function(a,b,f){var d=this;h.assert(null==this.loading[a]);this.loading[a]=!0;var c=this.textures.get(a);h.assert(void 0!==c);setTimeout(function(){var e=d.id2textureRef[a];e&&e.getRefCnt()&&c.initializeThroughUpload(d._rctx,b,d._textureTechnique,d.getViewportToRestore(),function(b){d.next(a);d.onNewlyTexturesLoaded();e&&e.getRefCnt()&&(e.setGLTexture(b),f&&f(e))})},0)};c.prototype.processQueue=function(){for(var a=
[],b=0;b<this._queue.length;++b){var c=this._queue[b][0],d=this.id2textureRef[c];void 0!==d&&(0===d.getRefCnt()?(d.getGLTexture().dispose(),delete this.id2textureRef[c]):a.push(this._queue[b]))}this._queue=a;a=Math.min(this.NUM_PARALLEL-Object.keys(this.loading).length,this._queue.length);for(b=0;b<a;++b)this._loadImage(this._queue[b][0],this._queue[b][1],this._queue[b][2]);this._queue.splice(0,a)};Object.defineProperty(c.prototype,"fallbackTexture",{get:function(){this._fallbackTexture||(this._fallbackTexture=
new n(this._rctx,this._fallbackTextureDesc,this._fallbackTextureData));return this._fallbackTexture},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"fallbackTextureTransparent",{get:function(){this._fallbackTextureTransparent||(this._fallbackTextureTransparent=new n(this._rctx,this._fallbackTextureDesc,this._fallbackTextureTransparentData));return this._fallbackTextureTransparent},enumerable:!0,configurable:!0});return c}();(function(c){var a=function(){function a(a){this._glTexture=
null;this._refCount=0;this._glTexture=a}a.prototype.incRefCnt=function(){++this._refCount};a.prototype.decRefCnt=function(){--this._refCount;h.assert(0<=this._refCount)};a.prototype.getRefCnt=function(){return this._refCount};a.prototype.setGLTexture=function(a){this._glTexture=a};a.prototype.getGLTexture=function(){return this._glTexture};return a}();c.TextureRef=a})(k||(k={}));return k});