// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/libs/gl-matrix-2/mat4f64 ../../../support/buffer/glUtil ../../lib/DefaultVertexAttributeLocations ./Instance ./utils ../../../../webgl/BufferObject ../../../../webgl/Util ../../../../webgl/VertexArrayObject".split(" "),function(z,A,q,r,t,u,k,v,w,x){function y(e,a){var c=new Map,f=function(b,a){var d=b.origin.id,f=b.data.id,g=c.get(d);g||(g={origin:b.origin.vec3,deltaByGeometry:new Map},c.set(d,g));d=g.deltaByGeometry.get(f);d||(d={renderData:b.data,toAdd:[],
toRemove:[]},g.deltaByGeometry.set(f,d));(a?d.toAdd:d.toRemove).push(b)};e.forEach(function(b){f(b,!0)});a.forEach(function(b){f(b,!1)});return c}function p(e,a,c){var f=a.elementCount(e),f=a.allocate(f);a.write({},e,f,0);c.setData(f.buffer)}return function(){function e(a,c,f,b){void 0===b&&(b=t.Default3D);this.type="InstancedRenderer";this._dataByOrigin=new Map;this._highlightCount=0;this._rctx=a;this._vertexAttributeLocations=b;this._material=f;this._materialRep=c;this._glMaterials=k.acquireMaterials(this._material,
this._materialRep);this._bufferWriter=f.createBufferWriter()}e.prototype.dispose=function(){k.releaseMaterials(this._material,this._materialRep)};Object.defineProperty(e.prototype,"isEmpty",{get:function(){return 0===this._dataByOrigin.size},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"hasHighlights",{get:function(){return 0<this._highlightCount},enumerable:!0,configurable:!0});e.prototype.hasWater=function(){return!1};e.prototype.renderPriority=function(){return this._material.renderPriority};
e.prototype.modify=function(a){this.updateGeometries(a.toUpdate);this.addAndRemoveGeometries(a.toAdd,a.toRemove);this.updateHighlightCount()};e.prototype.addAndRemoveGeometries=function(a,c){var f=this,b=this._rctx,e=this._bufferWriter,d=this._dataByOrigin;a=y(a,c);var h=e.vertexBufferLayout;a.forEach(function(a,c){var l=d.get(c);l||(l={origin:a.origin,highlightCount:0,dataByGeometry:new Map},d.set(c,l));a.deltaByGeometry.forEach(function(a,c){var d=l.dataByGeometry.get(c);!d&&0<a.toAdd.length&&(d=
{vao:new x(b,f._vertexAttributeLocations,{geometry:r.glLayout(h)},{geometry:v.createVertex(b,35044)}),vertexCount:0,instances:new Map,highlightCount:0},p(a.renderData,e,d.vao.vertexBuffers.geometry),d.vertexCount=w.vertexCount(d.vao,"geometry"),l.dataByGeometry.set(c,d));var g=d.instances;a.toAdd.forEach(function(b){var a=q.mat4f64.create();k.calculateTransformRelToOrigin(b,a);var c=k.generateRenderGeometryVisibleIndexRanges(b),f=k.generateRenderGeometryHighlightRanges(b),a=new u(b.name,0,d.vertexCount,
c,f,a,b.instanceParameters,b.idx,b.data.id);g.set(b.uniqueName,a);l.highlightCount=null;d.highlightCount=null});a.toRemove.forEach(function(b){g.delete(b.uniqueName)});0===g.size&&(d.vao.dispose(),l.dataByGeometry.delete(c))});0===l.dataByGeometry.size&&d.delete(c)})};e.prototype.updateGeometries=function(a){var c=this._dataByOrigin,f=this._bufferWriter;a.forEach(function(b){var a=b.updateType;b=b.renderGeometry;var d=c.get(b.origin.id),e=d&&d.dataByGeometry.get(b.data.id),g=e&&e.instances.get(b.uniqueName);
g&&(a&1&&(g.displayedIndexRange=k.generateRenderGeometryVisibleIndexRanges(b)),a&17&&(g.highlightedIndexRanges=k.generateRenderGeometryHighlightRanges(b),d.highlightCount=null,e.highlightCount=null),a&2&&p(b.data,f,e.vao.vertexBuffers.geometry),a&4&&k.calculateTransformRelToOrigin(b,g.transformation,g.transformationNormal))})};e.prototype.updateHighlightCount=function(){var a=this;this._highlightCount=0;this._dataByOrigin.forEach(function(c){if(null==c.highlightCount){var f=0;c.dataByGeometry.forEach(function(b){if(null==
b.highlightCount){var a=0;b.instances.forEach(function(b){b.highlightedIndexRanges&&++a});b.highlightCount=a}f+=b.highlightCount});c.highlightCount=f}a._highlightCount+=c.highlightCount})};e.prototype.render=function(a,c,f,b){var e=this,d=this._rctx,h=this._glMaterials.get(c.pass),g=4===c.pass;if(!h||null!=a&&!h.beginSlot(a)||g&&0===this._highlightCount)return!1;h.bind(d,f);var n=!1;this._dataByOrigin.forEach(function(a){g&&0===a.highlightCount||(f.origin=a.origin,h.bindView(f),a.dataByGeometry.forEach(function(a){n=
g?e.renderHighlightPass(h,a,b)||n:e.renderDefaultPass(h,a,b)||n}))});d.bindVAO(null);h.release();return n};e.prototype.renderDefaultPass=function(a,c,f){var b=this._rctx,e=a.getDrawMode(),d=c.vao,h=c.vertexCount;a.ensureAttributeLocations(d);b.bindVAO(d);var g=!1;c.instances.forEach(function(c){var d=c.displayedIndexRange;d&&0===d.length||(a.bindInstance(c),d?k.drawArraysFaceRange(b,d,0,e,f):k.drawArrays(b,e,0,h,f),g=!0)});return g};e.prototype.renderHighlightPass=function(a,c,e){var b=this._rctx,
f=a.getDrawMode(),d=c.vao,h=c.vertexCount;if(0!==c.highlightCount){a.ensureAttributeLocations(d);b.bindVAO(d);var g=!1;c.instances.forEach(function(c){var d=c.highlightedIndexRanges;if(d&&0!==d.length)for(a.bindInstance(c),c=0;c<d.length;c++){var m=d[c];k.drawArrays(b,f,m.range?m.range[0]:0,m.range?m.range[1]-m.range[0]+1:h,e);g=!0}});return g}};return e}()});