// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/tsSupport/decorateHelper ../../../../core/tsSupport/assignHelper ../../../../core/maybe ../../../../core/maybe ../core/shaderLibrary/Slice.glsl ../core/shaderLibrary/Transform.glsl ../core/shaderLibrary/output/OutputHighlight.glsl ../core/shaderLibrary/shading/VisualVariables.glsl ../core/shaderTechnique/ReloadableShaderModule ../core/shaderTechnique/ShaderTechnique ../core/shaderTechnique/ShaderTechniqueConfiguration ./RibbonLine.glsl ../../../webgl/Program ../../../webgl/renderState".split(" "),
function(m,g,k,c,h,n,p,q,r,t,u,v,w,b,x,y,e){Object.defineProperty(g,"__esModule",{value:!0});g.RibbonVertexAttributeConstants={POSITION:"position",SUBDIVISIONFACTOR:"subdivisionFactor",UV0:"uv0",AUXPOS1:"auxpos1",AUXPOS2:"auxpos2",SUBDIVISIONS:"subdivisions",COLOR:"color",COLORFEATUREATTRIBUTE:"colorFeatureAttribute",SIZE:"size",SIZEFEATUREATTRIBUTE:"sizeFeatureAttribute",OPACITYFEATUREATTRIBUTE:"opacityFeatureAttribute"};g.ribbonVertexAttributeLocations={position:0,subdivisionFactor:1,uv0:2,auxpos1:3,
auxpos2:4,size:6,sizeFeatureAttribute:6,color:5,colorFeatureAttribute:5,opacityFeatureAttribute:7};h=function(b){function a(f,a){a=b.call(this,f,a)||this;a.stipplePattern=null;a.stippleTextureBind=null;a.stippleTextureRepository=f.stippleTextureRepository;return a}k(a,b);a.prototype.initializeProgram=function(f){var b=a.shader.get(),d=this.configuration,b=b.build({output:d.output,slicePlaneEnabled:d.slicePlaneEnabled,sliceHighlightDisabled:d.sliceHighlightDisabled,stippleEnabled:d.stippleEnabled,
stippleOffColorEnabled:d.stippleOffColorEnabled,stippleUVMaxEnabled:d.stippleIntegerRepeatsEnabled,stippleIntegerRepeatsEnabled:d.stippleIntegerRepeatsEnabled,roundCaps:d.roundCaps,roundJoins:d.roundJoins,vvColor:d.vvColor,vvSize:d.vvSize,vvOpacity:d.vvOpacity});return new y(f.rctx,b.generateSource("vertex"),b.generateSource("fragment"),g.ribbonVertexAttributeLocations)};a.prototype.dispose=function(){b.prototype.dispose.call(this);this.stippleTextureRepository.release(this.stipplePattern);this.stippleTextureBind=
this.stipplePattern=null};a.prototype.bindPass=function(f,a,b){4===this.configuration.output&&t.OutputHighlight.bindOutputHighlight(f,this.program,b);this.program.setUniform1f("symbolLineWidth",a.width);this.program.setUniform4fv("symbolColor",a.color);this.program.setUniform1f("miterLimit","miter"!==a.join?0:a.miterLimit);this.program.setUniform1f("nearPlane",b.nearFar[0]);this.program.setUniform1f("pixelRatio",b.pixelRatio);this.program.setUniform2fv("screenSize",[b.viewport[2],b.viewport[3]]);
u.VisualVariables.bindUniformsWithOpacity(this.program,a);if(this.stipplePattern!==a.stipplePattern){var c=a.stipplePattern;this.stippleTextureBind=this.stippleTextureRepository.swap(this.stipplePattern,c);this.stipplePattern=c}this.configuration.stippleEnabled&&(f=p.isSome(this.stippleTextureBind)?this.stippleTextureBind(f,0)*b.pixelRatio:1,this.program.setUniform1i("stipplePatternTexture",0),this.program.setUniform1f("stipplePatternPixelSizeInv",1/f),this.configuration.stippleOffColorEnabled&&(a=
n.expect(a.stippleOffColor),this.program.setUniform4f("stippleOffColor",a[0],a[1],a[2],3<a.length?a[3]:1)))};a.prototype.bindDraw=function(a){r.Transform.bindUniforms(this.program,a);q.Slice.bindUniformsWithOrigin(this.program,this.configuration,a)};a.prototype.bindInstance=function(a){this.program.setUniformMatrix4fv("model",a.transformation)};a.prototype.initializePipeline=function(){var a=this.configuration;return 0===a.output?e.makePipelineState({blending:e.separateBlendingParams(770,1,771,771),
polygonOffset:a.polygonOffset&&l,depthTest:{func:513},depthWrite:!a.transparent&&a.writeDepth&&e.defaultDepthWriteParams,colorWrite:e.defaultColorWriteParams}):e.makePipelineState({polygonOffset:a.polygonOffset&&l,depthTest:{func:513},depthWrite:!a.transparent&&a.writeDepth&&e.defaultDepthWriteParams,colorWrite:e.defaultColorWriteParams})};a.prototype.bindPipelineState=function(a){a.setPipelineState(this.pipeline)};a.shader=new v.ReloadableShaderModule(x,"./RibbonLine.glsl",m);return a}(w.ShaderTechnique);
g.RibbonLineTechnique=h;var l={factor:0,units:-4};h=function(e){function a(){var a=null!==e&&e.apply(this,arguments)||this;a.output=0;a.slicePlaneEnabled=!1;a.sliceHighlightDisabled=!1;a.vertexColors=!1;a.transparent=!1;a.polygonOffset=!1;a.writeDepth=!1;a.stippleEnabled=!1;a.stippleOffColorEnabled=!1;a.stippleIntegerRepeatsEnabled=!1;a.roundCaps=!1;a.roundJoins=!1;a.vvSize=!1;a.vvColor=!1;a.vvOpacity=!1;return a}k(a,e);c([b.parameter({count:6})],a.prototype,"output",void 0);c([b.parameter()],a.prototype,
"slicePlaneEnabled",void 0);c([b.parameter()],a.prototype,"sliceHighlightDisabled",void 0);c([b.parameter()],a.prototype,"vertexColors",void 0);c([b.parameter()],a.prototype,"transparent",void 0);c([b.parameter()],a.prototype,"polygonOffset",void 0);c([b.parameter()],a.prototype,"writeDepth",void 0);c([b.parameter()],a.prototype,"stippleEnabled",void 0);c([b.parameter()],a.prototype,"stippleOffColorEnabled",void 0);c([b.parameter()],a.prototype,"stippleIntegerRepeatsEnabled",void 0);c([b.parameter()],
a.prototype,"roundCaps",void 0);c([b.parameter()],a.prototype,"roundJoins",void 0);c([b.parameter()],a.prototype,"vvSize",void 0);c([b.parameter()],a.prototype,"vvColor",void 0);c([b.parameter()],a.prototype,"vvOpacity",void 0);return a}(b.ShaderTechniqueConfiguration);g.RibbonLineTechniqueConfiguration=h});