// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/generatorHelper ../../../../../core/tsSupport/awaiterHelper ../../../../../core/promiseUtils ../../utils ../../../../support/heatmapUtils ../../../../../support/arcadeOnDemand ../../../../../tasks/support/ClassBreaksDefinition ../../../../../tasks/support/generateRendererUtils".split(" "),function(W,f,u,v,M,N,F,O,P,Q){function G(a,b,c){b=null==b?-Infinity:b;c=null==c?Infinity:c;return a.filter(function(a){return null!=a&&p(a)&&a>=b&&a<=c})}function t(a,
b){return v(this,void 0,void 0,function(){var c,d,e,g,m,k,l,h,C,f,r;return u(this,function(n){switch(n.label){case 0:return c=a.field,d="function"===typeof c,e=a.valueExpression,g=a.normalizationType,m=a.normalizationField,k=a.normalizationTotal,l=[],h=a.view,f=C=null,e?q?[3,2]:[4,O.loadArcade()]:[3,3];case 1:q=r=n.sent().arcadeUtils,n.label=2;case 2:C=q.createFunction(e),f=h&&q.getViewInfo({viewingMode:"2d"===h.type?"map":h.viewingMode,scale:h.scale,spatialReference:h.spatialReference}),n.label=
3;case 3:if(!b)return[2,l];b.forEach(function(a){var b=a.attributes,h;e?(h=q.createExecContext(a,f),h=q.executeFunction(C,h)):d?h=c.call(null,a):b&&(h=b[c]);g&&null!=h&&p(h)&&(b=b&&parseFloat(b[m]),"log"===g&&0!==h?h=Math.log(h)*Math.LOG10E:"percent-of-total"===g&&p(k)&&0!==k?h=h/k*100:"field"===g&&p(b)&&0!==b&&(h/=b));l.push(h)});return[2,l]}})})}function R(a,b){for(var c=Number.POSITIVE_INFINITY,d=Number.NEGATIVE_INFINITY,e=null,g=null,m=null,k=null,l=0;l<a.length;l++)var h=a[l],e=e+h,c=Math.min(c,
h),d=Math.max(d,h);if(l=a.length){g=e/l;for(k=m=0;k<a.length;k++)h=a[k],m+=Math.pow(h-g,2);k=b?1<l?m/(l-1):0:0<l?m/l:0;m=Math.sqrt(k)}else d=c=null;return{avg:g,count:l,max:d,min:c,stddev:m,sum:e,variance:k}}function H(a){var b=a.field,c=a.classificationMethod||"equal-interval",d=a.normalizationType,e=a.normalizationField,g=new P;g.classificationField=b;g.breakCount=a.breakCount;g.classificationMethod=c;g.standardDeviationInterval="standard-deviation"===c?a.standardDeviationInterval||1:void 0;g.normalizationType=
d;g.normalizationField="field"===d?e:void 0;return g}function I(a,b){var c=b.classBreaks,d=c[0].minValue,e=c[c.length-1].maxValue,g="standard-deviation"===a.classificationMethod,m=S,c=c.map(function(a){var c=a.label;a={minValue:a.minValue,maxValue:a.maxValue,label:c};if(g&&c){var b=c.match(m).map(function(a){return+a.trim()});2===b.length?(a.minStdDev=b[0],a.maxStdDev=b[1],0>b[0]&&0<b[1]&&(a.hasAvg=!0)):1===b.length&&(-1<c.indexOf("\x3c")?(a.minStdDev=null,a.maxStdDev=b[0]):-1<c.indexOf("\x3e")&&
(a.minStdDev=b[0],a.maxStdDev=null))}return a});return{minValue:d,maxValue:e,classBreakInfos:c,normalizationTotal:b.normalizationTotal}}function y(a,b,c){b=(b-a)/c;for(var d=[],e,g=1;g<=c;g++)e=a+b,e=Number(e.toFixed(16)),d.push([a,e]),a=e;return d}function J(a){var b=a.field,c=a.normalizationType,d=a.normalizationField;a=a.normalizationTotal;var e=b;"percent-of-total"===c?e="(("+b+" / "+a+") * 100)":"log"===c?e="(log("+b+") * "+T+")":"field"===c&&(e="("+b+" / "+d+")");return e}function U(a,b){for(var c=
-1,d=a.length-1;0<=d;d--)if(b>=a[d][0]){c=d;break}return c}function K(a,b){var c;b=b.toLowerCase();if(a)for(var d in a)if(d.toLowerCase()!==b){c=a[d];break}return c}function D(a,b){var c;b=b.toLowerCase();if(a)for(var d in a)if(d.toLowerCase()===b){c=a[d];break}return c}function E(a,b){if(b)for(var c in a)a[c].label=b[c];return{count:a}}function L(a,b,c){var d=a.count;a=[];c&&b&&"coded-value"===b.type&&b.codedValues.forEach(function(a){a=a.code;d.hasOwnProperty(a)||(d[a]={data:a,count:0})});for(var e in d)b=
d[e],a.push({value:b.data,count:b.count,label:b.label});return{uniqueValueInfos:a}}function p(a){return"number"===typeof a&&!isNaN(a)&&Infinity!==a&&-Infinity!==a}Object.defineProperty(f,"__esModule",{value:!0});var V=/_value$/i,S=/\s*(\+|-)?((\d+(\.\d+)?)|(\.\d+))\s*/gi,T=Math.LOG10E;f.statisticTypes="min max avg stddev count sum variance".split(" ");var q=null;f.getSummaryStatisticsFromFeatureSet=function(a,b){a=(a=a&&a.features)&&a[0]&&a[0].attributes;var c={},d;for(d in a)c[d.replace(V,"").toLowerCase()]=
a[d];c.min===c.max&&null!=c.min&&null==c.stddev&&(c.stddev=c.variance=0);b&&("min max avg stddev sum variance".split(" ").forEach(function(a){null!=c[a]&&(c[a]=Math.ceil(c[a]))}),c.min===c.max&&null!=c.min&&(c.avg=c.min,c.stddev=c.variance=0));return c};f.calculateStatsFromMemory=function(a,b,c){return v(this,void 0,void 0,function(){var d,e;return u(this,function(g){switch(g.label){case 0:return[4,t(a,b)];case 1:return d=g.sent(),d=G(d,a.minValue,a.maxValue),e=R(d,!a.normalizationType),c&&["avg",
"stddev","variance"].forEach(function(a){null!=e[a]&&(e[a]=Math.ceil(e[a]))}),[2,e]}})})};f.getDataValues=t;f.processSummaryStatisticsResult=function(a){for(var b in a)-1<f.statisticTypes.indexOf(b)&&(p(a[b])||(a[b]=null));return a};f.createCBDefn=H;f.calculateHeatmapStats=function(a,b,c,d,e,g){void 0===b&&(b=10);var m=new Float64Array(e*g),k=F.createKernel(b);b=Math.round(3*b);var l=Number.POSITIVE_INFINITY,h=Number.NEGATIVE_INFINITY,f=0,x=0,r=0,n=0;c=F.createValueFunction(d,c);for(d=0;d<a.length;d++)for(var A=
a[d],w=A.geometry,p=w.x-b,q=w.y-b,u=Math.max(0,p),f=Math.max(0,q),v=Math.min(g,w.y+b),w=Math.min(e,w.x+b),A=+c(A.attributes),t=f;t<v;t++)for(var y=k[t-q],B=u;B<w;B++){var f=t*e+B,z=m[f],f=m[f]+=y*k[B-p]*A,z=f-z,x=x+z,r=r+z*z;f<l&&(l=f);f>h&&(h=f);n++}return n?{mean:x/n,stdDev:Math.sqrt((r-x*x/n)/n),min:l,max:h,mid:(h-l)/2,count:n}:{mean:0,stddev:0,min:0,max:0,mid:0,count:0}};f.calculateClassBreaksFromMemory=function(a,b){return v(this,void 0,void 0,function(){var c,d,e,g;return u(this,function(f){switch(f.label){case 0:return c=
a.normalizationTotal,d=H({field:a.field,normalizationType:a.normalizationType,normalizationField:a.normalizationField,classificationMethod:a.classificationMethod,standardDeviationInterval:a.standardDeviationInterval,breakCount:a.numClasses||5}),[4,t(a,b)];case 1:return e=f.sent(),e=G(e,a.minValue,a.maxValue),g=Q.createGenerateRendererClassBreaks({definition:d,values:e,normalizationTotal:c}),[2,I(a,g)]}})})};f.resolveCBResult=I;f.getEqualIntervalBins=y;f.generateBinParams=function(a){var b=[],c=a.classBreaks,
d=c[0].minValue,e=c[c.length-1].maxValue;c.forEach(function(a){b.push([a.minValue,a.maxValue])});return{min:d,max:e,intervals:b,sqlExpr:J({field:a.field,normalizationType:a.normalizationType,normalizationField:a.normalizationField,normalizationTotal:a.normalizationTotal}),excludeZerosExpr:a.where,normTotal:a.normalizationTotal}};f.getFieldExpr=J;f.calculateHistogramFromMemory=function(a,b,c){return v(this,void 0,void 0,function(){var d,e,g,f,k,l,h,p,q,r,n;return u(this,function(m){switch(m.label){case 0:return d=
b.min,e=b.max,g=b.normTotal,f=a.numBins||10,k=b.intervals||y(d,e,f),l=k.map(function(a,b){return{minValue:k[b][0],maxValue:k[b][1],count:0}}),[4,t(a,c)];case 1:h=m.sent();p=0;for(q=h;p<q.length;p++)r=q[p],null!=r&&r>=d&&r<=e&&(n=U(k,r),-1<n&&l[n].count++);return[2,{bins:l,minValue:d,maxValue:e,normalizationTotal:g}]}})})};f.getHistogramFromFeatureSet=function(a,b,c,d,e){var g={};a&&a.features&&a.features.forEach(function(a){var b=a.attributes;a=K(b,"countOFExpr");b=D(b,"countOFExpr");0!==a&&(g[a]=
b)});var f=[];y(b,c,d).forEach(function(a,b){b=(b+1).toString();f.push({minValue:a[0],maxValue:a[1],count:g.hasOwnProperty(b)?g[b]:0})});return{bins:f,minValue:b,maxValue:c,normalizationTotal:e}};f.getUniqueValuesFromFeatureSet=function(a,b,c,d){var e="countOF"+(c||"Expr"),g={},f=!1;(a&&a.features).forEach(function(a){var b=a.attributes;a=D(b,e);b=c?D(b,c):K(b,e);null===b&&0===a&&(f=!0);if(null==b||"string"===typeof b&&""===b.trim())b=null;null==g[b]?g[b]={count:a,data:b}:g[b].count+=a});return c&&
f?b.queryFeatureCount(c+" is NULL").then(function(a){g["null"].count+=a||0;return E(g,d)}).catch(function(){return E(g,d)}):M.resolve(E(g,d))};f.createUVResult=L;f.calculateUniqueValuesFromMemory=function(a,b,c){return v(this,void 0,void 0,function(){var d,e,g,f,k;return u(this,function(l){switch(l.label){case 0:return[4,t(a,b)];case 1:d=l.sent();e={};g=0;for(f=d;g<f.length;g++){k=f[g];if(null==k||"string"===typeof k&&""===k.trim())k=null;null==e[k]?e[k]={count:1,data:k}:e[k].count++}return[2,L({count:e},
c,a.returnAllCodedValues)]}})})};f.msSinceUnixEpochSQL=function(a,b){return N.getDateDiffSQL(a,new Date(0),b,"milliseconds").sqlExpression};f.isValidNumber=p});