// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("../core/declare dojo/dom-attr dojo/keys dijit/registry dijit/Dialog ../kernel ../core/lang ../core/Error ../core/domUtils ../core/promiseUtils ../intl/substitute ./IdentityManagerBase dojo/i18n!./nls/identity dijit/form/Button dijit/form/Form dijit/form/ValidationTextBox".split(" "),function(v,k,w,f,n,q,x,g,m,r,y,t,z){var u=y.substitute,A=t.Credential;return v([t.IdentityManagerBase],{declaredClass:"esri.identity.IdentityManager",constructor:function(d){x.mixin(this,d)},_dialogContent:"\x3cdiv data-dojo-type\x3d'dijit.form.Form' data-dojo-props\x3d'\"class\":\"esriIdForm\"'\x3e\x3cdiv class\x3d'dijitDialogPaneContentArea'\x3e\x3cdiv style\x3d'padding-bottom: 5px; word-wrap: break-word;'\x3e{info}\x3c/div\x3e\x3cdiv style\x3d'margin: 0px; padding: 0px; height: 10px;'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriErrorMsg' style\x3d'display: none; color: white; background-color: #D46464; text-align: center; padding-top: 3px; padding-bottom: 3px;'\x3e{invalidUser}\x3c/div\x3e\x3cdiv style\x3d'margin: 0px; padding: 0px; height: 10px;'\x3e\x3c/div\x3e\x3ctable style\x3d'width: 100%;'\x3e\x3ctr\x3e\x3ctd\x3e\x3clabel\x3e{lblUser}\x3cbr/\x3e\x3cinput data-dojo-type\x3d'dijit.form.ValidationTextBox' data-dojo-props\x3d'type:\"text\", \"class\":\"esriIdUser\", required:true, trim:true, style:\"width: 100%;\", autocapitalize:\"none\", autocorrect:\"off\", spellcheck:false' /\x3e\x3c/label\x3e\x3c/td\x3e\x3c/tr\x3e\x3ctr\x3e\x3ctd\x3e\x3clabel\x3e{lblPwd}\x3cbr/\x3e\x3cinput data-dojo-type\x3d'dijit.form.ValidationTextBox' data-dojo-props\x3d'type:\"password\", \"class\":\"esriIdPwd\", required:true, style:\"width: 100%;\"' /\x3e\x3c/label\x3e\x3c/td\x3e\x3c/tr\x3e\x3c/table\x3e\x3c/div\x3e\x3cdiv class\x3d'dijitDialogPaneActionBar'\x3e\x3cbutton data-dojo-type\x3d'dijit.form.Button' data-dojo-props\x3d'type:\"button\", \"class\":\"esriIdSubmit\"'\x3e{lblOk}\x3c/button\x3e\x3cbutton data-dojo-type\x3d'dijit.form.Button' data-dojo-props\x3d'type:\"button\", \"class\":\"esriIdCancel\"'\x3e{lblCancel}\x3c/button\x3e\x3c/div\x3e\x3c/div\x3e",
signIn:function(d,b,a){this._nls||(this._nls=z);this._loginDialog||(this._loginDialog=this.dialog=this._createLoginDialog(),this.emit("dialog-create"));var e=this._loginDialog,l=a&&a.error,f=a&&a.token,c=r.createResolver();if(a&&a.signal)r.onAbort(a.signal,function(){e.onCancel()});if(e.open)return d=new g("identity-manager:busy","BUSY"),c.reject(d),c.promise;m.hide(e.errMsg_);l&&l.details&&403==l.details.httpStatus&&f&&(k.set(e.errMsg_,"innerHTML",this._nls.forbidden),m.show(e.errMsg_));e.dfd_=c;
e.serverInfo_=b;e.resUrl_=d;e.admin_=a&&a.isAdmin;e.signal_=a&&a.signal;k.set(e.resLink_,{title:d,innerHTML:"("+(this.getResourceName(d)||this._nls.lblItem)+")"});k.set(e.serverLink_,{title:b.server,innerHTML:(-1!==b.server.toLowerCase().indexOf("arcgis.com")?"ArcGIS Online":b.server)+" "});e.txtPwd_.set("value","");e.show();return c.promise},_createLoginDialog:function(){var d=this._nls,b=u(this._dialogContent,d),b=u(b,{resource:"\x3cspan class\x3d'resLink' style\x3d'word-wrap: break-word;'\x3e\x3c/span\x3e",
server:"\x3cspan class\x3d'serverLink' style\x3d'word-wrap: break-word;'\x3e\x3c/span\x3e"}),a=new n({title:d.title,content:b,"class":" esri-widget esriSignInDialog esriIdentityDialog",style:"width: 18em;",esriIdMgr_:this,onShow:function(){this.domNode.classList.add("esriIdentityDialog--visible")},onHide:function(){this.domNode.classList.remove("esriIdentityDialog--visible")},keypressed_:function(a){a.charOrCode===w.ENTER&&this.execute_()},execute_:function(){var a=this.txtUser_.get("value"),b=this.txtPwd_.get("value"),
f=this.dfd_,c=this;if(this.form_.validate()&&a&&b){this.btnSubmit_.set("label",d.lblSigning);var p=q.id.findCredential(c.resUrl_,a),g=function(b){c.btnSubmit_.set("label",d.lblOk);c.btnSubmit_.set("disabled",!1);m.hide(c.errMsg_);c.hide();n._DialogLevelManager.hide(c);var e=c.serverInfo_;c.dfd_=c.serverInfo_=c.generateDfd_=c.resUrl_=c.signal_=null;var l,g,h=p,k;b&&(l=b.token,g=null!=b.expires?Number(b.expires):null,k=!!b.ssl,h?(h.userId=a,h.token=l,h.expires=g,h.validity=b.validity,h.ssl=k,h.creationTime=
Date.now()):h=new A({userId:a,server:e.server,token:l,expires:g,ssl:k,isAdmin:c.admin_,validity:b.validity}));f.resolve(h)};p&&!p._enqueued?g():(c.btnSubmit_.set("disabled",!0),c.generateDfd_=q.id.generateToken(this.serverInfo_,{username:a,password:b},{isAdmin:this.admin_,signal:this.signal_}).then(g,function(a){c.btnSubmit_.set("disabled",!1);c.generateDfd_=null;c.btnSubmit_.set("label",d.lblOk);k.set(c.errMsg_,"innerHTML",a&&a.details&&a.details.httpStatus?d.invalidUser:d.noAuthService);m.show(c.errMsg_)}))}},
cancel_:function(){var b=a.dfd_,d=a.resUrl_,f=a.serverInfo_;a.btnSubmit_.set("disabled",!1);a.dfd_=a.serverInfo_=a.generateDfd_=a.resUrl_=a.signal_=null;m.hide(a.errMsg_);n._DialogLevelManager.hide(a);a.esriIdMgr_.emit("dialog-cancel",{resourceUrl:d,serverInfo:f});d=new g("identity-manager:user-aborted","ABORTED");b.reject(d)}}),b=a.domNode;a.form_=f.byNode(b.getElementsByClassName("esriIdForm")[0]);a.txtUser_=f.byNode(b.getElementsByClassName("esriIdUser")[0]);a.txtPwd_=f.byNode(b.getElementsByClassName("esriIdPwd")[0]);
a.btnSubmit_=f.byNode(b.getElementsByClassName("esriIdSubmit")[0]);a.btnCancel_=f.byNode(b.getElementsByClassName("esriIdCancel")[0]);a.resLink_=b.getElementsByClassName("resLink")[0];a.serverLink_=b.getElementsByClassName("serverLink")[0];a.errMsg_=b.getElementsByClassName("esriErrorMsg")[0];a.connect(a.txtUser_,"onKeyPress",a.keypressed_);a.connect(a.txtPwd_,"onKeyPress",a.keypressed_);a.connect(a.btnSubmit_,"onClick",a.execute_);a.connect(a.btnCancel_,"onClick",a.onCancel);a.connect(a,"onCancel",
a.cancel_);return a}})});