// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../../../core/tsSupport/assignHelper ../../../core/Error ../PixelBlock ./ImageCanvasDecoder ./JpgPlus ./Lerc2Codec ./LercCodec ./Png ./Raw ./TiffDecoder".split(" "),function(W,X,z,C,D,v,p,J,K,L,M,N,E,O){function P(a,b){if(!F)throw new v("rasterCoded:decode","lerc decoder is not supported on big endian platform");var c=b.width,g=b.height,e=b.pixelType,d=G(e),m=d.pixelTypeCtor;b=null==b.noDataValue?
d.noDataValue:b.noDataValue;for(var d=0,t,h=0,n,u=a.byteLength-10;h<u;){var k=M.decode(a,{inputOffset:h,encodedMaskData:t,returnMask:0===d?!0:!1,returnEncodedMask:0===d?!0:!1,returnFileInfo:!0,pixelType:m,noDataValue:b});if(c&&g&&(k.width!==c||k.height!==g))throw new v("rasterCoded:decode","lerc decoded result has width or height different from specified in options");h=k.fileInfo.eofOffset;0===d&&(t=k.encodedMaskData,n=new p({width:k.width,height:k.height,pixels:[],pixelType:e,mask:k.maskData,statistics:[]}));
d++;n.addData({pixels:k.pixelData,statistics:{minValue:k.minValue,maxValue:k.maxValue,noDataValue:k.noDataValue}})}return n}function Q(a,b){if(!F)throw new v("rasterCoded:decode","lerc decoder is not supported on big endian platform");for(var c=0,g=0,e=0,d,m,t=a.byteLength-10,h=[],n=b.width,u=b.height;g<t;){b=L.decode(a,{inputOffset:g,maskData:d,returnFileInfo:!0});if(n&&u&&(b.width!==n||b.height!==u))throw new v("rasterCoded:decode","lerc2 decoded result has width or height different from what's specified in options");
g=b.fileInfo.eofOffset;0===c&&(e=b.fileInfo.numValidPixel,d=b.maskData,m=new p({width:b.width,height:b.height,pixels:[],pixelType:b.fileInfo.pixelType,mask:b.maskData,statistics:[]}));b.fileInfo.mask&&0<b.fileInfo.mask.numBytes&&h.push(b.maskData);c++;m.addData({pixels:b.pixelData,statistics:{minValue:b.minValue,maxValue:b.maxValue}})}g=c=a=0;if(1<h.length){g=m.width*m.height;d=new Uint8Array(g);d.set(h[0]);for(a=1;a<h.length;a++)for(e=h[a],c=0;c<g;c++)d[c]&=e[c];for(c=e=0;c<g;c++)e+=d[c];m.mask=
d}m.validPixelCount=e;return m}function R(a){a=O.decode(a);a=new p({width:a.width,height:a.height,pixels:a.pixels,pixelType:a.pixelType.toLowerCase(),mask:a.maskData,statistics:null});a.updateStatistics();return a}function H(a,b,c){var g=G(b.pixelType).pixelTypeCtor;a=("bsq"===c?E.decodeBSQ:E.decodeBIP)(a,{bandCount:b.planes,width:b.width,height:b.height,pixelType:g});b=new p({width:b.width,height:b.height,pixels:a.pixels,pixelType:b.pixelType,mask:a.mask,statistics:null});b.updateStatistics();return b}
function S(a){a=K.decode(a);a=new p({width:a.width,height:a.height,pixels:a.pixels,pixelType:"U8",mask:a.mask,statistics:null});a.updateStatistics();return a}function T(a,b){a=new Uint8Array(a);var c=new N(a);a=b.width;var g=b.height;b=a*g;for(var c=c.decode(),e=0,d=0,d=new Uint8Array(b),e=0;e<b;e++)d[e]=c[4*e+3];g=new p({width:a,height:g,pixels:[],pixelType:"U8",mask:d,statistics:[]});for(e=0;3>e;e++){a=new Uint8Array(b);for(d=0;d<b;d++)a[d]=c[4*d+e];g.addData({pixels:a})}g.updateStatistics();return g}
function U(a,b,c){return C(this,void 0,void 0,function(){var g,e,d,m;return z(this,function(t){switch(t.label){case 0:return g=new J,e=D({applyJpegMask:!1},b),[4,g.decode(a,e,c)];case 1:return d=t.sent(),m=new p(d),m.updateStatistics(),[2,m]}})})}function I(a){if(null==a)throw new v("rasterCodec:decode","parameter encodeddata is required.");a=new Uint8Array(a,0,10);var b="";255===a[0]&&216===a[1]?b="jpg":137===a[0]&&80===a[1]&&78===a[2]&&71===a[3]?b="png":67===a[0]&&110===a[1]&&116===a[2]&&90===a[3]&&
73===a[4]&&109===a[5]&&97===a[6]&&103===a[7]&&101===a[8]&&32===a[9]?b="lerc":76===a[0]&&101===a[1]&&114===a[2]&&99===a[3]&&50===a[4]&&32===a[5]?b="lerc2":73===a[0]&&73===a[1]&&42===a[2]&&0===a[3]||77===a[0]&&77===a[1]&&0===a[2]&&42===a[3]?b="tiff":-1<String.fromCharCode.apply(null,a).toLowerCase().indexOf("error")&&(b="error");return b}function V(a){var b=null;switch(a){case "lerc":b=P;break;case "lerc2":b=Q;break;case "jpg":b=S;break;case "png":b=T;break;case "bsq":b=function(a,b){return H(a,b,"bsq")};
break;case "bip":b=function(a,b){return H(a,b,"bip")};break;case "tiff":b=R;break;case "error":b=function(){throw new v("rasterCodec:decode","input data contains error");};break;default:b=function(){throw new v("rasterCodec:decode","unsupported raster format");}}return b}function G(a){var b=null,c=null;switch(a?a.toLowerCase():"f32"){case "u1":case "u2":case "u4":case "u8":c=Math.pow(2,8)-1;b=Uint8Array;break;case "u16":c=c||Math.pow(2,16)-1;b=Uint16Array;break;case "u32":c=c||Math.pow(2,32)-1;b=
Uint32Array;break;case "s8":c=c||0-Math.pow(2,7);b=Int8Array;break;case "s16":c=c||0-Math.pow(2,15);b=Int16Array;break;case "s32":c=c||0-Math.pow(2,31);b=Int32Array;break;default:b=Float32Array}return{pixelTypeCtor:b,noDataValue:c}}var F=function(){var a=new ArrayBuffer(4),b=new Uint8Array(a);(new Uint32Array(a))[0]=1;return 1===b[0]}();return function(){function a(){}a.getFormat=function(a){a=I(a);"lerc2"===a?a="lerc":"error"===a&&(a="");return a};a.decode=function(a,c,g){return C(this,void 0,void 0,
function(){var b,d,m;return z(this,function(e){switch(e.label){case 0:if(null==a)throw new v("rasterCodec:decode","missing encodeddata parameter.");if(null==c||null==c.width||null==c.height)throw new v("rasterCodec:decode","requires width and height in options parameter.");b=c.format&&c.format.toLowerCase();if(!b||"bsq"!==b&&"bip"!==b)b=I(a);return!c.useCanvas||"jpg"!==b&&"png"!==b?[3,2]:[4,U(a,c,g)];case 1:return m=e.sent(),[3,3];case 2:d=V(b);c.isPoint&&(c=D({},c),c.width++,c.height++);m=d(a,c);
if(c.isPoint){var h=m,n=void 0;void 0===n&&(n=1);if(h){var u=h.pixels,k=h.width,p=h.mask;if(u&&0!==u.length){var t=u.length,r=k-1,w=h.height-1,B=[],l,f,q,x,y,A,z=h.getPixelArrayConstructor(h.pixelType);if(0===n){for(n=0;n<t;n++){x=u[n];y=new z(r*w);for(l=0;l<w;l++)for(q=l*k,f=0;f<r;f++)y[l*r+f]=x[q+f];B.push(y)}if(p)for(A=new Uint8Array(r*w),l=0;l<w;l++)for(q=l*k,f=0;f<r;f++)A[l*r+f]=p[q+f]}else{for(n=0;n<t;n++){x=u[n];y=new z(r*w);for(l=0;l<w;l++)for(q=l*k,f=0;f<r;f++)y[l*r+f]=(x[q+f]+x[q+f+1]+x[q+
k+f]+x[q+k+f+1])/4;B.push(y)}if(p)for(A=new Uint8Array(r*w),l=0;l<w;l++)for(q=l*k,f=0;f<r;f++)A[l*r+f]=Math.min.apply(null,[p[q+f],p[q+f+1],p[q+k+f],p[q+k+f+1]])}h.width=r;h.height=w;h.mask=A;h.pixels=B}}}e.label=3;case 3:return[2,m]}})})};return a}()});