// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/assignHelper ../../../../../core/mathUtils ../../../../../core/maybe ../../../../../core/libs/gl-matrix-2/mat4 ../../../../../core/libs/gl-matrix-2/mat4f32 ../../../../../core/libs/gl-matrix-2/mat4f64 ../../../../../core/libs/gl-matrix-2/vec3 ../../../../../core/libs/gl-matrix-2/vec3f64 ../../../../../core/libs/gl-matrix-2/vec4 ../../../../../geometry/support/aaBoundingBox ../../lib/ComponentUtils ../../lib/doublePrecisionUtils ../../lib/screenSizePerspectiveUtils ../../lib/Util".split(" "),
function(oa,d,ga,O,G,P,ha,ia,A,z,I,H,Q,ja,ka,R){function S(a,b,c,e,x,f){var h=M(b,c,T);H.setMin(t,a.getBBMin());H.setMax(t,a.getBBMax());G.isSome(x)&&x.applyToAABB(t);if(J(t,b,h,e)){var h=a.getPrimitiveIndices(),d=a.getIndices(),K=a.getPosition(),g=h?h.length:d.length/3;if(g>la&&(a=a.getChildren(),void 0!==a)){for(h=0;8>h;++h)void 0!==a[h]&&S(a[h],b,c,e,x,f);return}L(b,c,0,g,d,K,h,x,f)}}function L(a,b,c,e,x,f,h,d,K){var g,n,k;if(h){var p,l,m=f.data,t=f.offsetIdx;f=f.strideIdx;var z=a[0],A=a[1];a=
a[2];var E=b[0]-z,F=b[1]-A;for(b=b[2]-a;c<e;++c){var B=h[c],u=3*B;l=t+f*x[u++];var r=m[l++],q=m[l++];g=m[l];l=t+f*x[u++];var w=m[l++];n=m[l++];p=m[l];l=t+f*x[u];u=m[l++];k=m[l++];l=m[l];G.isSome(d)&&(g=d.applyToVertex(r,q,g),r=g[0],q=g[1],g=g[2],p=d.applyToVertex(w,n,p),w=p[0],n=p[1],p=p[2],l=d.applyToVertex(u,k,l),u=l[0],k=l[1],l=l[2]);w-=r;n-=q;p-=g;u-=r;k-=q;l-=g;var y=F*l-k*b,D=b*u-l*E,C=E*k-u*F,v=w*y+n*D+p*C;if(!(Math.abs(v)<=U)){r=z-r;q=A-q;g=a-g;y=r*y+q*D+g*C;if(0<v){if(0>y||y>v)continue}else if(0<
y||y<v)continue;D=q*p-n*g;g=g*w-p*r;q=r*n-w*q;r=E*D+F*g+b*q;if(0<v){if(0>r||y+r>v)continue}else if(0<r||y+r<v)continue;q=(u*D+k*g+l*q)/v;0<=q&&(w=N(w,n,p,u,k,l,V),K(q,w,B))}}}else for(h=f.data,m=f.offsetIdx,t=f.strideIdx,f=a[0],z=a[1],A=a[2],a=b[0]-f,E=b[1]-z,F=b[2]-A,b=c,c*=3;b<e;++b)if(k=m+t*x[c++],r=h[k++],q=h[k++],g=h[k],k=m+t*x[c++],B=h[k++],w=h[k++],n=h[k],k=m+t*x[c++],p=h[k++],u=h[k++],k=h[k],G.isSome(d)&&(g=d.applyToVertex(r,q,g),r=g[0],q=g[1],g=g[2],n=d.applyToVertex(B,w,n),B=n[0],w=n[1],
n=n[2],k=d.applyToVertex(p,u,k),p=k[0],u=k[1],k=k[2]),B-=r,w-=q,n-=g,p-=r,u-=q,k-=g,v=E*k-u*F,y=F*p-k*a,D=a*u-p*E,l=B*v+w*y+n*D,!(Math.abs(l)<=U)){r=f-r;q=z-q;g=A-g;v=r*v+q*y+g*D;if(0<l){if(0>v||v>l)continue}else if(0<v||v<l)continue;y=q*n-w*g;g=g*B-n*r;q=r*w-B*q;r=a*y+E*g+F*q;if(0<l){if(0>r||v+r>l)continue}else if(0<r||v+r<l)continue;q=(p*y+u*g+k*q)/l;0<=q&&(B=N(B,w,n,p,u,k,V),K(q,B,b))}}function N(a,b,c,e,d,f,h){A.vec3.set(W,a,b,c);A.vec3.set(X,e,d,f);A.vec3.cross(h,W,X);A.vec3.normalize(h,h);return h}
function M(a,b,c){return A.vec3.set(c,1/(b[0]-a[0]),1/(b[1]-a[1]),1/(b[2]-a[2]))}function J(a,b,c,e){return Y(a,b,c,e,Infinity)}function Y(a,b,c,e,d){var f=(a[0]-e-b[0])*c[0],h=(a[3]+e-b[0])*c[0],m=Math.min(f,h),f=Math.max(f,h),h=(a[1]-e-b[1])*c[1],x=(a[4]+e-b[1])*c[1],f=Math.min(f,Math.max(h,x));if(0>f)return!1;m=Math.max(m,Math.min(h,x));if(m>f)return!1;h=(a[2]-e-b[2])*c[2];a=(a[5]+e-b[2])*c[2];f=Math.min(f,Math.max(h,a));if(0>f)return!1;m=Math.max(m,Math.min(h,a));return m>f?!1:m<d}function Z(a,
b,c,e){return ka.scale(a,c,b,e)}function aa(a,b){b=b?aa(b):{};for(var c in a){var e=a[c];e&&e.forEach&&(e=ma(e));null==e&&c in b||(b[c]=e)}return b}function ma(a){var b=[];a.forEach(function(a){return b.push(a)});return b}Object.defineProperty(d,"__esModule",{value:!0});var ba=ia.mat4f64.create(),t=H.create(),C=R.VertexAttrConstants;d.intersectTriangleGeometry=function(a,b,c,e,d,f,h){b=b&&b.componentVisibilities;c=c.tolerance;if(1<a.componentCount)a:{var m=M(e,d,T),x=a.componentCount,g=a.componentOffsets,
n=a.getIndices(C.POSITION),k=a.getAttribute(C.POSITION),p=a.boundingInfo;if(p&&(H.setMin(t,p.getBBMin()),H.setMax(t,p.getBBMax()),G.isSome(f)&&f.applyToAABB(t),!J(t,e,m,c)))break a;for(p=0;p<x;p++)if(!b||Q.getVisibility(b,p)){if(a.getComponentAABB){var l=a.getComponentAABB(p,t);G.isSome(f)&&f.applyToAABB(l);if(!J(l,e,m,c))continue}L(e,d,g[p]/3,g[p+1]/3,n,k,void 0,f,h)}}else if(!b||Q.getVisibility(b,0))a.boundingInfo?(R.assert("triangle"===a.data.primitiveType),S(a.boundingInfo,e,d,c,f,h)):(b=a.getIndices(C.POSITION),
a=a.getAttribute(C.POSITION),L(e,d,0,b.length/3,b,a,void 0,f,h))};var T=z.vec3f64.create(),U=Math.pow(2,-52),V=z.vec3f64.create();d.intersectTriangles=L;var W=z.vec3f64.create(),X=z.vec3f64.create();d.computeNormal=N;d.computeInvDir=M;d.intersectAabbInvDir=J;d.intersectAabbInvDirBefore=Y;d.transformToWorld=function(a,b,c){return I.vec4.set(c,a[0]-b[0],a[1]-b[1],a[2]-b[2],1)};d.transformToView=function(a,b,c,e){P.mat4.translate(ba,c,b);c=ba;return I.vec4.transformMat4(e,a,c)};d.transformToProjection=
function(a,b,c,e){e[0]=a[0]+c[0];e[1]=a[1]+c[1];e[2]=a[2]+c[2];e[3]=a[3];return I.vec4.transformMat4(e,e,b)};d.transformToNDC=function(a,b){return I.vec4.scale(b,a,1/Math.abs(a[3]))};d.applyScreenSizePerspectiveScale=Z;d.verticalOffsetAtDistance=function(a,b,c,e,d){var f=(c.screenLength||0)*a.pixelRatio;d&&(f=Z(f,b,e,d));return O.clamp(f*Math.tan(.5*a.fovY)/(.5*a.fullHeight)*b,c.minWorldLength||0,null!=c.maxWorldLength?c.maxWorldLength:Infinity)};d.acquireIfNotUndefined=function(a,b,c){if(void 0!==
a)return b.acquire(a,c)};d.releaseIfNotUndefined=function(a,b){void 0!==a&&b.release(a)};var ca=ha.mat4f32.create();d.bindView=function(a,b,c){P.mat4.translate(ca,b,a);c.setUniform3fv("localOrigin",a);c.setUniformMatrix4fv("view",ca)};d.bindCamPos=function(a,b,c){c.setUniform3f("camPos",b[3]-a[0],b[7]-a[1],b[11]-a[2])};var da=z.vec3f64.create(),ea=z.vec3f64.create();d.bindViewOriginDouble=function(a,b){ja.encodeDoubleArraySplit(a,da,ea,3);b.setUniform3fv("viewOriginHi",da);b.setUniform3fv("viewOriginLo",
ea)};var fa=z.vec3f64.create();d.bindSlicePlane=function(a,b,c){A.vec3.subtract(fa,b.origin,a);c.setUniform3fv("slicePlaneOrigin",fa);c.setUniform3fv("slicePlaneBasis1",b.basis1);c.setUniform3fv("slicePlaneBasis2",b.basis2)};d.bindVerticalOffset=function(a,b,c){if(a){var e=b.fovY,d=b.viewport[3],f=void 0;void 0===f&&(f=na);f.screenLength=a.screenLength;f.perDistance=Math.tan(.5*e)/(.5*d);f.minWorldLength=a.minWorldLength;f.maxWorldLength=a.maxWorldLength;a=f;c.setUniform4f("verticalOffset",a.screenLength*
(b.pixelRatio||1),a.perDistance,a.minWorldLength,a.maxWorldLength)}};d.bindHighlightRendering=function(a,b,c){a.bindTexture(b.highlightDepthTexture,5);c.setUniform1i("depthTex",5);c.setUniform4f("highlightViewportPixelSz",0,0,1/b.viewport[2],1/b.viewport[3])};d.bindScreenSizePerspective=function(a,b,c){void 0===c&&(c="screenSizePerspectiveAlignment");if(a){var e=a.parameters;b.setUniform4f(c,e.divisor,e.offset,e.minPixelSize,a.paddingPixelsOverride)}};d.copyParameters=aa;d.updateParameters=function(a,
b){var c=!1,e;for(e in b){var d=b[e];void 0!==d&&(c=!0,Array.isArray(d)?a[e]=d.slice():a[e]=d)}return c};(function(a){function b(a){return(a.shadowMappingEnabled?1:0)|(a.ssaoEnabled?2:0)}a.create=function(a,d){for(var c=[],f=0;2>f;f++)for(var e=0;2>e;e++){var m=b({shadowMappingEnabled:1===f,ssaoEnabled:1===e}),t=b({shadowMappingEnabled:1===f,ssaoEnabled:1===e&&a.receiveSSAO});c[m]=c[t]||d({receiveShadows:1===f,receiveSSAO:1===e&&a.receiveSSAO})}return{programs:c.filter(function(a){return null!=a}),
byParameter:c}};a.lookup=function(a,e){return a.byParameter[b(e)]};a.programs=function(a){return a.programs}})(d.BindParametersMap||(d.BindParametersMap={}));d.intersectDrapedRenderLineGeometry=function(a,b,c,e,d){if(b.options.selectionMode){b=a.getAttribute(C.POSITION).data;var f=a.getAttribute(C.SIZE),h=c[0];c=c[1];a=(((f&&f.data[0])+e)/2+4)*a.pixelRatio;e=Number.MAX_VALUE;for(f=0;f<b.length-5;f+=3){var m=b[f],t=b[f+1],g=h-m,n=c-t,m=b[f+3]-m,t=b[f+4]-t,k=O.clamp((m*g+t*n)/(m*m+t*t),0,1),g=m*k-g,
n=t*k-n,n=g*g+n*n;n<e&&(e=n)}e<a*a&&d()}};d.colorMixModes={multiply:1,ignore:2,replace:3,tint:4};var la=1E3,na={screenLength:0,perDistance:0,minWorldLength:0,maxWorldLength:0};d.defaultPBRMaterialParameters={roughnessFactor:.6,metallicFactor:0,reflectanceFactor:.2};d.defaultPBRTreeMaterialParameters={roughnessFactor:1,metallicFactor:0,reflectanceFactor:.2};d.getDefaultPBRMaterialParameters=function(a,b){return ga({usePBR:a},b?d.defaultPBRTreeMaterialParameters:d.defaultPBRMaterialParameters)}});