// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/generatorHelper ../../../../../core/tsSupport/awaiterHelper ../../../../../core/Logger ../../../../../core/libs/gl-matrix-2/vec2f64 ../../../support/imageUtils ../../../../webgl/Texture".split(" "),function(d,f,k,l,m,n,p,g){Object.defineProperty(f,"__esModule",{value:!0});var q=m.getLogger("esri.views.3d.webgl-engine.materials.internal.waterMaterialUtils");f.waterParameterDefaultsLocal={waveTexture:d.toUrl("../../../../../images/materials/water/normals.jpg"),
perturbationTexture:d.toUrl("../../../../../images/materials/water/perturbation.jpg"),waveStrength:.06,waveTextureRepeat:32,waveDirection:n.vec2f64.fromValues(1,0),waveVelocity:.05,flowStrength:.015,flowOffset:-.5,animationSpeed:.35,color:[0,.35686,.4,1],transparent:!1,writeDepth:!0,slicePlaneEnabled:!1,isDraped:!1,receiveShadows:!0};f.wavePresets={"calm-small":{waveStrength:.005,perturbationStrength:.02,textureRepeat:12,waveVelocity:.01},"rippled-small":{waveStrength:.02,perturbationStrength:.09,
textureRepeat:32,waveVelocity:.07},"slight-small":{waveStrength:.05,perturbationStrength:.07,textureRepeat:28,waveVelocity:.1},"moderate-small":{waveStrength:.075,perturbationStrength:.07,textureRepeat:24,waveVelocity:.1},"calm-medium":{waveStrength:.003125,perturbationStrength:.01,textureRepeat:8,waveVelocity:.02},"rippled-medium":{waveStrength:.035,perturbationStrength:.015,textureRepeat:12,waveVelocity:.07},"slight-medium":{waveStrength:.06,perturbationStrength:.015,textureRepeat:8,waveVelocity:.12},
"moderate-medium":{waveStrength:.09,perturbationStrength:.03,textureRepeat:4,waveVelocity:.12},"calm-large":{waveStrength:.01,perturbationStrength:0,textureRepeat:4,waveVelocity:.05},"rippled-large":{waveStrength:.025,perturbationStrength:.01,textureRepeat:8,waveVelocity:.11},"slight-large":{waveStrength:.06,perturbationStrength:.02,textureRepeat:3,waveVelocity:.13},"moderate-large":{waveStrength:.14,perturbationStrength:.03,textureRepeat:2,waveVelocity:.15}};d=function(){function a(){this.loadingCount=
0;this.data=[];this.loadingState=0}a.prototype.loadTexture=function(h,b,c){return l(this,void 0,void 0,function(){var a,d;return k(this,function(e){switch(e.label){case 0:this.loadingCount++,e.label=1;case 1:return e.trys.push([1,3,,4]),[4,p.requestImage(c)];case 2:return a=e.sent(),this.data[b]=new g(h,this.getTextureProps(a.width,a.height,!0),a),[3,4];case 3:return d=e.sent(),q.warn("Failed to load texture for water material.",d),this.data[b]=new g(h,this.getTextureProps(1,1,!0)),[3,4];case 4:return this.loadingCount--,
[2]}})})};a.prototype.getTextureProps=function(a,b,c){void 0===c&&(c=!1);return{target:3553,pixelFormat:6408,dataType:5121,wrapMode:10497,samplingMode:9987,hasMipmap:c,maxAnisotropy:8,width:a,height:b}};a.prototype.ready=function(){return 2===this.loadingState?!0:1===this.loadingState&&0===this.loadingCount?(this.loadingState=2,!0):!1};a.prototype.loading=function(){return 1===this.loadingState};a.prototype.initialize=function(a,b){for(var c=0;c<b.length;c++)this.loadTexture(a,c,b[c]);this.loadingState=
1};a.prototype.bindRepo=function(a){for(var b=0;b<this.data.length;b++)a.bindTexture(this.data[b],b)};return a}();f.waterTextureRepo=new d});