// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/assignHelper ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../../../Camera ../../../Viewpoint ../../../core/Accessor ../../../core/Error ../../../core/Handles ../../../core/Logger ../../../core/maybe ../../../core/promiseUtils ../../../core/scheduling ../../../core/screenUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators ../../../core/libs/gl-matrix-2/vec4 ../../../core/libs/gl-matrix-2/vec4f64 ../../../geometry/Extent ../../../geometry/Point ../../../geometry/support/webMercatorUtils ../camera/constraintUtils ../camera/intersectionUtils ./ConstraintsManager ./Frustum ./controllers/PointToPointAnimationController ./controllers/SurfaceCollisionCorrectionController ../support/cameraUtils ../support/PropertiesPool ../support/viewpointUtils ../webgl-engine/lib/Camera ../../animation/easing".split(" "),
function(q,A,B,K,k,r,t,v,x,L,w,M,N,n,m,O,P,u,f,F,Q,G,R,S,C,H,T,U,D,I,e,V,E,W,X){Object.defineProperty(A,"__esModule",{value:!0});var h=N.getLogger("esri.views.3d.state.ViewStateManager");q=function(q){function b(a){a=q.call(this,a)||this;a.propertiesPool=new V.default({frustum:U.default},a);a.handles=new M;a.cameraSetByUser=!1;a.internalSetOrder=[];a.immediateGoToController=null;a.animatedGoToController=null;a.ready=!1;a.updateDevicePixelRatio=null;return a}K(b,q);Object.defineProperty(b.prototype,
"camera",{get:function(){if(!this.ready)return this._get("camera");var a=e.internalToExternal(this.view,this.view.state.camera),c=this._get("camera");return a&&c&&a.equals(c)?c:a},set:function(a){this.updatePropertyBeforeReady("camera",a)||this.setStateCamera(e.externalToInternal(this.view,a),{applyConstraints:!1})||h.error("#camera\x3d","Invalid camera",a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"center",{get:function(){return this.ready?this.view.pointsOfInterest.centerOnContent.location:
this._get("center")},set:function(a){this.updatePropertyBeforeReady("center",a)||(a?this.isCompatible(a)?this.setStateCamera(this.centerToCamera(a),{applyConstraints:!0})?this.view.pointsOfInterest.centerOnContent.update():h.error("#center\x3d","Invalid center",a):h.error("#center\x3d","Center has an incompatible spatial reference (center: "+(a.spatialReference?a.spatialReference.wkid:"none")+", view: "+this.view.spatialReference.wkid+")",a):h.error("#center\x3d","Center may not be null or undefined"))},
enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"extent",{get:function(){return this.ready?e.toExtent(this.view,this.view.state.camera,this.view.pointsOfInterest.centerOnContent.renderLocation):this._get("extent")},set:function(a){this.updatePropertyBeforeReady("extent",a)||(a?this.isCompatible(a)?this.setStateCamera(this.extentToCamera(a),{applyConstraints:!0})||h.error("#extent\x3d","Invalid extent",a):h.error("#extent\x3d","Extent has an incompatible spatial reference (extent: "+
(a.spatialReference?a.spatialReference.wkid:"none")+", view: "+this.view.spatialReference.wkid+")",a):h.error("#extent\x3d","Extent may not be null or undefined"))},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"frustum",{get:function(){var a=this.propertiesPool.get("frustum");a.renderCoordsHelper=this.view.renderCoordsHelper;a.update(this.view.state.camera);return a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"hasInitialView",{get:function(){return!!this.view.get("map.initialViewProperties.viewpoint")},
enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"scale",{get:function(){if(!this.ready)return this._get("scale");var a=this.view.pointsOfInterest.centerOnContent;return e.distanceToScale(this.view,a.distance,a.location.latitude)},set:function(a){this.updatePropertyBeforeReady("scale",a)||this.setStateCamera(this.scaleToCamera(a),{applyConstraints:!0})||h.error("#scale\x3d","Invalid scale",a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"padding",{get:function(){if(!this.ready)return this._get("padding");
var a=this.view.state.camera,c=a.padding,d=a.pixelRatio,a=this._get("padding"),b=Math.round(c[0]/d),g=Math.round(c[1]/d),e=Math.round(c[2]/d),c=Math.round(c[3]/d);return null!=a&&a.top===b&&a.right===g&&a.bottom===e&&a.left===c?a:{top:b,right:g,bottom:e,left:c}},set:function(a){this.updatePropertyBeforeReady("padding",a)||(this.paddingToArray(a,this.view.state.camera.pixelRatio,y),this.view.state.updateCamera(function(a){return a.padding=y}))},enumerable:!0,configurable:!0});b.prototype.paddingToArray=
function(a,c,d){a?F.vec4.set(d,a.top||0,a.right||0,a.bottom||0,a.left||0):F.vec4.set(d,0,0,0,0);for(a=0;4>a;a++)d[a]=Math.round(d[a]*c)};Object.defineProperty(b.prototype,"screenCenter",{get:function(){var a=this.padding;return P.createScreenPoint((this.view.width-(a.left+a.right))/2+a.left,(this.view.height-(a.top+a.bottom))/2+a.top)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"viewpoint",{get:function(){return this.ready?E.fromCamera(this.view,this.camera):this._get("viewpoint")},
set:function(a){if(!this.updatePropertyBeforeReady("viewpoint",a))if(a)if(this.isCompatible(a))this.setStateCamera(this.viewpointToCamera(a),{applyConstraints:!a.camera})||h.error("#viewpoint\x3d","Invalid viewpoint",a);else{var c=a.camera?a.camera.position:a.targetGeometry,c=c&&c.spatialReference;h.error("#viewpoint\x3d","Viewpoint has an incompatible spatial reference (viewpoint: "+(c?c.wkid:"none")+", view: "+this.view.spatialReference.wkid+")",a)}else h.error("#viewpoint\x3d","Viewpoint may not be null or undefined")},
enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"zoom",{get:function(){return this.ready?e.scaleToZoom(this.view,this.scale):this._get("zoom")},set:function(a){this.updatePropertyBeforeReady("zoom",a)||this.setStateCamera(this.zoomToCamera(a),{applyConstraints:!0})||h.error("#zoom\x3d","Invalid zoom",a)},enumerable:!0,configurable:!0});b.prototype.initialize=function(){var a=this;this.handles.add([this.view.watch("state.camera",function(c){return a.cameraChangedSync(c)},!0),u.on(this.view,
"state.events","before-camera-change",function(c){return a.updateElevation(c.camera)})]);u.once(this.view,"state.camera",function(c){return a.updateElevation(c)},!0);this.handles.add(O.addFrameTask({prepare:function(){return a.prepareFrame()}}));this.handles.add(this.view.watch("state.cameraController",function(){a.cameraSetByUser=!0;a.handles.remove(z);a.cancelImmediateGoTo()}));this.handles.add(u.on(this.view,"state.events","camera-projection-changed",function(){return a.notifyChange("scale")}))};
b.prototype.destroy=function(){this.deinit();this.handles&&(this.handles.destroy(),this.handles=null);this.propertiesPool&&(this.propertiesPool.destroy(),this.propertiesPool=null)};b.prototype.init=function(){var a=this;this.constraintsManager=new T.default({view:this.view});this.prepareFrame();var c=this.getInitialProperties();this.cameraSetByUser=!1;this._set("ready",!0);for(var d=0;d<c.length;d++){var b=c[d];this.set(b.name,b.value)}this.cameraSetByUser||((c=this.view.get("map.initialViewProperties.viewpoint")||
this.view.initialExtent)&&this.isCompatible(c)?this.setInitialView(c):"local"===this.view.state.mode&&this.handles.add(u.whenOnce(this.view.basemapTerrain,"ready",function(){a.handles.remove(z);a.setInitialView(a.view.groundExtent)}),z))};b.prototype.deinit=function(){this.ready&&(this._override("padding",this.padding),this.cancelImmediateGoTo(),this.cancelAnimatedGoTo(),this._set("ready",!1),this._clearOverride("hasInitialView"),this.internalSetOrder.length=0,this.cameraSetByUser=!1,this.handles.remove(z),
this.constraintsManager&&(this.constraintsManager.destroy(),this.constraintsManager=null))};b.prototype.goTo=function(a,c){return t(this,void 0,void 0,function(){var d;return r(this,function(b){d=B({animate:!0},c);return d.animate?[2,this.goToAnimated(a,d)]:[2,this.goToImmediate(a,d)]})})};b.prototype.debugSetCameraOnContent=function(){this.setStateCamera(H.cameraOnContentAlongViewDirection(this.view),{applyConstraints:!1})};b.prototype.step=function(a){var c=this.view.state,d=c&&this.view.state.cameraController;
d&&(c.updateCamera(function(c){d.stepController(a,c)}),d.steppingFinished&&d.finishController())};b.prototype.cancelImmediateGoTo=function(){var a=this.immediateGoToController;n.isSome(a)&&(this.immediateGoToController=null,a.abort())};b.prototype.cancelAnimatedGoTo=function(){var a=this.animatedGoToController;n.isSome(a)&&(this.animatedGoToController=null,a.abort())};b.prototype.getInitialProperties=function(){for(var a=new Set,c=[],d=0,b=Y;d<b.length;d++){var g=b[d],e=g.propertyName,g=g.overrides,
h=a.has(e),p=this._isOverridden(e);!h&&p&&c.push({name:e,value:this._get(e)});this._clearOverride(e);(h||p)&&g.forEach(function(c){return a.add(c)})}return c};b.prototype.setInitialView=function(a){if(a&&!this.cameraSetByUser)if(a instanceof v)this.setStateCamera(e.externalToInternal(this.view,a),{applyConstraints:!1});else if(a instanceof x)if(a.targetGeometry instanceof G){var c=e.fromExtent(this.view,a.targetGeometry,0,.5,e.OrientationMode.LOCKED);this.setStateCamera(e.externalToInternal(this.view,
c),{applyConstraints:!0})}else c={applyConstraints:!a.camera},a=this.viewpointToCamera(a),this.setStateCamera(a,c);else c=e.fromExtent(this.view,a,0,.5,e.OrientationMode.LOCKED),this.setStateCamera(e.externalToInternal(this.view,c),{applyConstraints:!0})};b.prototype.updatePropertyBeforeReady=function(a,c){if(!this.ready){this._override(a,c);var d=this.internalSetOrder.indexOf(a);-1!==d&&(this.internalSetOrder=this.internalSetOrder.splice(d,1));c&&(this.internalSetOrder.push(a),-1!==Z.indexOf(a)&&
this._override("hasInitialView",!0));return!0}return!1};b.prototype.isCompatible=function(a){return a?a instanceof x?a.camera?this.isCompatible(a.camera):this.isCompatible(a.targetGeometry):a instanceof v?this.isCompatible(a.position):a.spatialReference&&S.canProject(a.spatialReference,this.view.spatialReference):!1};b.prototype.getPreservingHeadingTilt=function(a){void 0===a&&(a=aa);this.cameraSetByUser?(a.heading=this.camera.heading,a.tilt=this.camera.tilt):(a.heading=0,a.tilt=.5);return a};b.prototype.centerPointAtDistanceToCamera=
function(a,c,d){void 0===d&&(d=l);var b=this.getPreservingHeadingTilt();return(a=e.getObserverForPointAtDistance(this.view,b.heading,b.tilt,a,c,e.OrientationMode.ADJUST))?(d.copyFrom(this.view.state.camera),d.eye=a.eye,d.center=a.center,d.up=a.up,d):null};b.prototype.centerToCamera=function(a){var c=this.view.pointsOfInterest.centerOnContent;c.update();return this.centerPointAtDistanceToCamera(a,c.distance)};b.prototype.extentToCamera=function(a){var c=this.getPreservingHeadingTilt();a=e.fromExtent(this.view,
a,c.heading,c.tilt,e.OrientationMode.ADJUST,ba);return e.externalToInternal(this.view,a)};b.prototype.scaleToCamera=function(a){if(null==a)return null;var c=this.view.pointsOfInterest.centerOnContent;c.update();var d=c.renderLocation;a=e.scaleToDistance(this.view,a,c.location.latitude);return this.centerPointAtDistanceToCamera(d,a)};b.prototype.zoomToCamera=function(a){return this.scaleToCamera(e.zoomToScale(this.view,a))};b.prototype.viewpointToCamera=function(a){return(a=E.toCamera(this.view,a))?
e.externalToInternal(this.view,a):null};b.prototype.setStateCamera=function(a,c){var d=this;if(!a||!this.view.state.stopActiveCameraController())return!1;this.cameraSetByUser=!0;this.cancelImmediateGoTo();this.view.state.updateCamera(function(b){b.copyFrom(a);c.applyConstraints&&C.applyAll(d.view,b)});c.applyConstraints||(this.view.state.cameraController=new I.SurfaceCollisionCorrectionController({view:this.view,desiredCamera:a}));return!0};b.prototype.prepareFrame=function(){var a=this.view,c=a.container,
d=a.canvas;if(c&&d){n.isSome(this.updateDevicePixelRatio)&&this.updateDevicePixelRatio();var a=this.view.pixelRatio,b=Math.round(c.clientWidth*a),c=Math.round(c.clientHeight*a);0!==b&&0!==c&&(d.width=b,d.height=c,this.view.state&&(d=this.view.state.camera,d.fullWidth!==b||d.fullHeight!==c||d.pixelRatio!==a))&&(l.copyFrom(d),l.pixelRatio!==a&&(this.paddingToArray(this.padding,a,y),l.padding=y),l.fullWidth=b,l.fullHeight=c,l.pixelRatio=a,this.view.state.camera=l)}};b.prototype.updateElevation=function(a){var c=
this.view.basemapTerrain&&this.view.basemapTerrain.spatialReference,b=this.view.renderCoordsHelper.getAltitude(a.eye),c=c?H.surfaceElevationBelowEye(this.view,a):0;a.relativeElevation=b-c};b.prototype.cameraChangedSync=function(a){a&&this.view._stage&&this.view._stage.setCamera(a)};b.prototype.createGoToCamera=function(a,c){return t(this,void 0,void 0,function(){var b,J,g,h,f,p,k,n;return r(this,function(d){switch(d.label){case 0:return[4,u.whenOnce(this,"ready",c.signal,!0)];case 1:return d.sent(),
m.throwIfAborted(c),[4,E.create(this.view,a,c.signal)];case 2:b=d.sent();J=!!(a instanceof x&&a.camera||a instanceof v);g=b.camera;if(!this.isCompatible(g))throw p=(f=(h=g.position)&&h.spatialReference)?f.wkid:"none",k=this.view.spatialReference.wkid,new w("goto:incompatible-spatialreference","Resulting camera has an incompatible spatial reference (camera: "+p+", view: "+k+")",{camera:g});n=e.externalToInternal(this.view,g);if(!n)throw new w("goto:invalid-camera","Resulting camera is invalid");return[2,
{viewpoint:b,camera:n,isFullySpecified:J}]}})})};b.prototype.cancellableGoTo=function(a,c){var b=this,e,g=function(){b.view.state.cameraController===a&&a.active&&a.asyncResult===e&&a.stopController()};return m.create(function(b,d){e={resolve:b,reject:d};a.asyncResult=e;m.onAbort(c,g)},g)};b.prototype.goToImmediate=function(a,c){return t(this,void 0,void 0,function(){var b,e,g,f=this;return r(this,function(d){this.cancelAnimatedGoTo();this.cancelImmediateGoTo();b=m.createAbortController();m.onAbort(c,
function(){return b.abort()});e=this.createGoToCamera(a,B({},c,{signal:b.signal}));g=function(){f.immediateGoToController===b&&(f.immediateGoToController=null)};this.immediateGoToController=b;return[2,e.then(function(a){g();f.setStateCamera(a.camera,{applyConstraints:!a.isFullySpecified})}).catch(function(a){g();!m.isAbortError(a)&&a instanceof w&&a.message&&h.error("#goTo()","Failed to create camera from target, "+a.message[0].toLowerCase()+a.message.slice(1));throw a;})]})})};b.prototype.goToAnimatedBeforeReady=
function(a,c){return t(this,void 0,void 0,function(){var b;return r(this,function(d){switch(d.label){case 0:return this.cancelAnimatedGoTo(),b=m.createAbortController(),m.onAbort(c,function(){return b.abort()}),this.animatedGoToController=b,c=B({},c,{signal:b.signal}),[4,u.whenOnce(this.view,"ready",b.signal)];case 1:return d.sent(),this.animatedGoToController=null,[2,this.goToAnimated(a,c)]}})})};b.prototype.goToAnimated=function(a,c){return t(this,void 0,void 0,function(){var b,e,g,f,k,p,l=this;
return r(this,function(d){this.cancelAnimatedGoTo();if(!this.ready)return[2,this.goToAnimatedBeforeReady(a,c)];b=this.view.state.cameraController;b instanceof D.PointToPointAnimationController&&(b.updateStateFromViewAnimation(),b.active&&(e=b));null==e&&(e=new D.PointToPointAnimationController(this.view.state,this.view.sceneIntersectionHelper,"animation"));g=e.viewAnimation;if(n.isNone(g))return h.warn("Unreachable code in ViewStateManager"),[2];f=this.createGoToCamera(a,c);g.update(f.then(function(a){return a.viewpoint}));
if(e!==b&&!this.view.state.switchCameraController(e))return g.stop(),h.error("#goTo()","Cannot start an animation while interacting"),[2,m.reject(new w("view:goto-cannot-interrupt","Cannot start an animation while interacting"))];k=g.target;p=function(){return l.view.state.cameraController===e&&n.isSome(e.viewAnimation)&&e.viewAnimation.target===k&&e.active};f.then(function(a){var b=a.viewpoint,d=a.camera,f=a.isFullySpecified;return t(l,void 0,void 0,function(){var a,h,l=this;return r(this,function(m){switch(m.label){case 0:if(!p())return[2];
n.isSome(e.viewAnimation)&&(e.viewAnimation.update(b),k=e.viewAnimation.target);f?(a=new I.SurfaceCollisionCorrectionController({view:this.view,desiredCamera:d}),C.applySurfaceCollisionConstraint(this.view,d,1)):C.applyAll(this.view,d);e.begin(d,this.internalAnimateOptions(c));h=function(){var b=l.view.state.cameraController;a&&(b&&b.active?b instanceof D.PointToPointAnimationController&&n.isSome(b.viewAnimation)&&b.viewAnimation.target===k&&(l.view.state.cameraController=a):n.isSome(e.viewAnimation)&&
e.viewAnimation.target===k&&(l.view.state.cameraController=a))};return[4,g.when(h,h)];case 1:return m.sent(),[2]}})})}).catch(function(a){!m.isAbortError(a)&&a instanceof w&&a.message&&h.error("#goTo()","Failed to create camera from target, "+a.message[0].toLowerCase()+a.message.slice(1));if(p())throw l.view.state.cameraController.stopController(),a;});return[2,this.cancellableGoTo(e,c)]})})};b.prototype.internalAnimateOptions=function(a){var b={};a&&(null!=a.speedFactor&&(b.speedFactor=a.speedFactor),
null!=a.duration&&(b.duration=a.duration/1E3),null!=a.maxDuration&&(b.maxDuration=a.maxDuration/1E3),null!=a.easing&&(b.easing="string"===typeof a.easing?X.named[a.easing]:a.easing));return b};k([f.property({type:v,dependsOn:["view.state.camera","ready"]})],b.prototype,"camera",null);k([f.property({type:R,dependsOn:["view.pointsOfInterest.centerOnContent.location","ready"]})],b.prototype,"center",null);k([f.property({type:G,dependsOn:["view.state.camera","ready","view.pointsOfInterest.centerOnContent.location"]})],
b.prototype,"extent",null);k([f.property({readOnly:!0,dependsOn:["view.state.camera","ready"]})],b.prototype,"frustum",null);k([f.property({readOnly:!0,dependsOn:["view.map.initialViewProperties?.viewpoint"]})],b.prototype,"hasInitialView",null);k([f.property({readOnly:!0,type:Boolean})],b.prototype,"ready",void 0);k([f.property({dependsOn:["view.pointsOfInterest.centerOnContent.distance","ready"],type:Number})],b.prototype,"scale",null);k([f.property({dependsOn:["view.state.camera","ready"]})],b.prototype,
"padding",null);k([f.property({readOnly:!0,dependsOn:["view.width","view.height","padding"]})],b.prototype,"screenCenter",null);k([f.property({constructOnly:!0})],b.prototype,"view",void 0);k([f.property({type:x,dependsOn:["camera","ready"]})],b.prototype,"viewpoint",null);k([f.property({type:Number,dependsOn:["scale"]})],b.prototype,"zoom",null);k([f.property({constructOnly:!0})],b.prototype,"updateDevicePixelRatio",void 0);return b=k([f.subclass("esri.views.3d.state.ViewStateManager")],b)}(f.declared(L));
A.ViewStateManager=q;var Z="camera viewpoint extent scale center zoom".split(" "),Y=[{propertyName:"camera",overrides:["viewpoint"]},{propertyName:"viewpoint",overrides:["extent"]},{propertyName:"extent",overrides:["center","scale"]},{propertyName:"center",overrides:[]},{propertyName:"scale",overrides:["zoom"]},{propertyName:"zoom",overrides:[]},{propertyName:"padding",overrides:[]}],aa={heading:0,tilt:0},ba=new v,l=new W.default,y=Q.vec4f64.create(),z="pending-initial-view";A.default=q});