// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper dojo/i18n!../../nls/smartMapping ../../../PopupTemplate ../../../core/Error ../../../intl/substitute ../../../popup/ExpressionInfo ../../../popup/FieldInfo ../statistics/support/predominanceUtils".split(" "),function(Y,w,x,y,e,h,M,m,p,n,q){function t(a){return a.legendOptions&&a.legendOptions.title?a.legendOptions.title:N}function l(a){return{fieldInfo:new n({fieldName:"expression/predominant-category"}),
expressionInfo:new p({name:"predominant-category",title:z,expression:q.getArcadeForPredominantCategoryAlias(a)})}}function u(a){a=a.map(function(a){return a.fieldName});return{fieldInfo:new n({fieldName:"expression/predominant-value",format:{digitSeparator:!0,places:1}}),expressionInfo:new p({name:"predominant-value",title:A,expression:q.getArcadeForPredominantCategoryValue(a),returnType:"number"})}}function O(a){a=a.map(function(a){return a.fieldName});return{fieldInfo:new n({fieldName:"expression/predominant-margin",
format:{digitSeparator:!0,places:0}}),expressionInfo:new p({name:"predominant-margin",title:B,expression:q.getArcadeForPredominanceMargin(a),returnType:"number"})}}function C(a){a=a.map(function(a){return a.fieldName});return{fieldInfo:new n({fieldName:"expression/predominant-strength",format:{digitSeparator:!0,places:0}}),expressionInfo:new p({name:"predominant-strength",title:D,expression:q.getArcadeForStrengthOfPredominance(a),returnType:"number"})}}function E(a){return{fieldInfo:new n({fieldName:"expression/predominant-categories-list"}),
expressionInfo:new p({name:"predominant-categories-list",title:P,expression:q.getArcadeForOrderedFields(a)})}}function F(a){a=a.map(function(a){return a.fieldName});return{fieldInfo:new n({fieldName:"expression/predominant-total",format:{digitSeparator:!0,places:0}}),expressionInfo:new p({name:"predominant-total",title:Q,expression:q.getArcadeForSumOfFields(a),returnType:"number"})}}function G(a){a=l(a.fieldInfos);a=new h({expressionInfos:[a.expressionInfo],fieldInfos:[a.fieldInfo],content:m.substitute(e.predominantCategoryContent,
{expression:"\x3cb\x3e{"+a.fieldInfo.fieldName+"}\x3c/b\x3e"})});return{name:"predominant-category",title:z,value:a}}function H(a){var c=a.renderer,b=a.fieldInfos;a=l(b);var d=u(b),b=C(b),c=new h({expressionInfos:[d.expressionInfo,a.expressionInfo,b.expressionInfo],fieldInfos:[d.fieldInfo,a.fieldInfo,b.fieldInfo],content:m.substitute(e.predominantCategoryStrengthContent,{title:t(c),expression1:"{"+d.fieldInfo.fieldName+"}",expression2:"\x3cb\x3e{"+a.fieldInfo.fieldName+"}\x3c/b\x3e",expression3:"\x3cb\x3e{"+
b.fieldInfo.fieldName+"}%\x3c/b\x3e"})});return{name:"predominant-category-strength",title:D,value:c}}function I(a){var c=a.renderer,b=a.fieldInfos;a=l(b);var d=u(b),b=F(b),c=new h({expressionInfos:[d.expressionInfo,a.expressionInfo,b.expressionInfo],fieldInfos:[d.fieldInfo,a.fieldInfo,b.fieldInfo],content:m.substitute(e.predominantCategoryTotalContent,{title:t(c),expression1:"{"+d.fieldInfo.fieldName+"}",expression2:"\x3cb\x3e{"+a.fieldInfo.fieldName+"}\x3c/b\x3e",expression3:"{"+b.fieldInfo.fieldName+
"}"})});return{name:"predominant-category-total",title:R,value:c}}function J(a){var c=a.renderer,b=a.fieldInfos;a=l(b);var d=u(b),k=C(b),b=F(b),c=new h({expressionInfos:[d.expressionInfo,a.expressionInfo,b.expressionInfo,k.expressionInfo],fieldInfos:[d.fieldInfo,a.fieldInfo,b.fieldInfo,k.fieldInfo],content:m.substitute(e.predominantCategoryTotalStrengthContent,{title:t(c),expression1:"{"+d.fieldInfo.fieldName+"}",expression2:"\x3cb\x3e{"+a.fieldInfo.fieldName+"}\x3c/b\x3e",expression3:"\x3cb\x3e{"+
k.fieldInfo.fieldName+"}%\x3c/b\x3e",expression4:"{"+b.fieldInfo.fieldName+"}"})});return{name:"predominant-category-total-strength",title:S,value:c}}function T(a){var c=a.renderer;a=a.fieldInfos;var b=l(a),c=new h({expressionInfos:[b.expressionInfo],fieldInfos:[b.fieldInfo],content:[{type:"text",text:'\x3cdiv\x3e\x3cb\x3e\x3cfont size\x3d"3"\x3e{'+b.fieldInfo.fieldName+"}\x3c/font\x3e\x3c/b\x3e\x3c/div\x3e"},{type:"media",mediaInfos:{type:"pie-chart",title:t(c),value:{fields:a.map(function(a){return a.fieldName})}}}]});
return{name:"predominant-category-chart",title:U,value:c}}function V(a,c){a=a.authoringInfo;a="predominance"===a.type?a.fields:[];if(!a||!a.length)throw new M("predominance-popup:insufficient-info","unable to find input fields in authoringInfo");var b=null;"popupTemplate"in c&&c.popupTemplate&&(b=c.popupTemplate.fieldInfos);return a.map(function(a){var d=c.getField(a),f=new n({fieldName:d.name,label:d.alias});b&&b.some(function(a){return a&&a.fieldName.toLowerCase()===d.name.toLowerCase()?(f=a.clone(),
!0):!1});return f})}function K(a){return y(this,void 0,void 0,function(){var c,b,d;return x(this,function(e){switch(e.label){case 0:return c=a.renderer,b=a.layer,[4,b.load()];case 1:return e.sent(),d=V(c,b),[2,{renderer:c,fieldInfos:d}]}})})}function L(a){return y(this,void 0,void 0,function(){var c;return x(this,function(b){switch(b.label){case 0:return[4,K(a)];case 1:c=b.sent();b=G(c);var d=c.fieldInfos,k=l(d),d=u(d),k=new h({expressionInfos:[d.expressionInfo,k.expressionInfo],fieldInfos:[d.fieldInfo,
k.fieldInfo],content:m.substitute(e.predominantCategoryValueContent,{expression1:"\x3cb\x3e{"+k.fieldInfo.fieldName+"}\x3c/b\x3e",expression2:"\x3cb\x3e{"+d.fieldInfo.fieldName+"}\x3c/b\x3e"})}),k={name:"predominant-category-value",title:A,value:k},f=c.fieldInfos,d=l(f),v=u(f),f=O(f),d=new h({expressionInfos:[v.expressionInfo,d.expressionInfo,f.expressionInfo],fieldInfos:[v.fieldInfo,d.fieldInfo,f.fieldInfo],title:m.substitute(e.mostCommon,{expression:"{expression/predominant-category}"}),content:m.substitute(e.predominantCategoryValueMarginContent,
{expression1:"\x3cb\x3e{"+d.fieldInfo.fieldName+"}\x3c/b\x3e",expression2:"\x3cb\x3e{"+v.fieldInfo.fieldName+"}\x3c/b\x3e",expression3:"\x3cb\x3e{"+f.fieldInfo.fieldName+"}\x3c/b\x3e"})}),d={name:"predominant-category-value-margin",title:B,value:d},v=J(c),f=c.renderer,g=E(c.fieldInfos),f=new h({expressionInfos:[g.expressionInfo],fieldInfo:[g.fieldInfo],title:t(f),content:"{"+g.fieldInfo.fieldName+"}"}),f={name:"predominant-categories-list",title:W,value:f},r=c.fieldInfos,g=l(r),r=E(r),g=new h({expressionInfos:[g.expressionInfo,
r.expressionInfo],fieldInfos:[g.fieldInfo,r.fieldInfo],content:[{type:"text",text:'\x3cdiv\x3e\x3cb\x3e\x3cfont size\x3d"3"\x3e{'+g.fieldInfo.fieldName+"}\x3c/font\x3e\x3c/b\x3e\x3c/div\x3e"},{type:"text",text:"{"+r.fieldInfo.fieldName+"}"}]});return[2,[b,k,d,v,f,{name:"predominant-basic-summary",title:X,value:g},I(c),H(c),T(c)]]}})})}Object.defineProperty(w,"__esModule",{value:!0});var z=e.predominantCategory,A=e.predominantCategoryValue,U=e.predominantCategoryWithChart,R=e.predominantCategoryWithTotal,
S=e.predominantCategoryWithTotalAndStrength,D=e.strengthOfPredominance,B=e.marginOfVictory,P=e.listOfCategories,Q=e.sumOfCategories,W=e.orderedListOfValues,X=e.basicSummary,N=e.competingFields;w.getAllTemplates=L;w.getTemplates=function(a){return y(this,void 0,void 0,function(){var c,b,d,e,f,h;return x(this,function(g){switch(g.label){case 0:return c=a.renderer,[4,K(a)];case 1:return b=g.sent(),d=c.hasVisualVariables("size",!1),e=c.hasVisualVariables("opacity"),f=G(b),d&&e&&(f=J(b)),d&&!e&&(f=I(b)),
!d&&e&&(f=H(b)),[4,L(a)];case 2:return h=g.sent(),[2,{primaryTemplate:f,secondaryTemplates:h.filter(function(a){return a.name!==f.name})}]}})})}});