// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../Graphic ../../../core/Accessor ../../../core/Handles ../../../core/has ../../../core/mathUtils ../../../core/mathUtils ../../../core/maybe ../../../core/scheduling ../../../core/accessorSupport/decorators ../../../core/libs/gl-matrix-2/vec2 ../../../core/libs/gl-matrix-2/vec3 ../../../core/libs/gl-matrix-2/vec3f64 ../../../core/libs/gl-matrix-2/vec4 ../../../core/libs/gl-matrix-2/vec4f64 ../../../geometry/Point ../../../geometry/support/aaBoundingRect ../../../layers/support/timeUtils ../../../symbols/SimpleMarkerSymbol ../state/utils/viewUtils ../support/animationUtils ../support/debugFlags ../support/debugFlags ../support/earthUtils ../support/geometryUtils ../support/mathUtils ../support/projectionUtils ../webgl-engine/lib/Intersector ../webgl-engine/lib/localOrigin ../../support/Scheduler".split(" "),
function(B,C,I,t,J,K,L,M,u,N,O,P,q,Q,p,x,r,D,R,f,S,T,U,V,W,E,X,Y,F,w,Z,G,aa){function ba(f,d){for(var a=W.TESTS_DISABLE_UPDATE_THRESHOLDS?0:1E-5*Math.max(f[2]-f[0],f[3]-f[1],d[2]-d[0],d[3]-d[1]),b=0;4>b;b++)if(Math.abs(d[b]-f[b])>a)return!0;return!1}Object.defineProperty(C,"__esModule",{value:!0});var ca=[[-.1,-2,3.9,2],[-.1,-3.9,3.9,.1],[-2,-3.9,2,.1],[-3.9,-3.9,.1,.1],[-3.9,-2,.1,2],[-3.9,-.1,.1,3.9],[-2,-.1,2,3.9],[-.1,-.1,3.9,3.9]],z;B=function(y){function d(){var a=null!==y&&y.apply(this,arguments)||
this;a._handles=new L;a._overlaySR=null;a._renderSR=null;a._overlaySREqualsRenderSR=!0;a._connectedLayers=new Map;a._overlays=null;a._renderedAltitude=0;a._placementDirty=!1;a._drawTexturesDirty=!1;a._drawTexturesAnimateDirty=!1;a._isSpherical=!1;a._longitudeCyclical=null;a._latestOriginId=0;a._maxResolution=M("esri-mobile")?2048:4096;a._animationTimeLast=0;a.opacity=0;return a}I(d,y);Object.defineProperty(d.prototype,"hasHighlights",{get:function(){return this._renderer.hasHighlights},enumerable:!0,
configurable:!0});d.prototype.initialize=function(){var a=this;this._stage=this.view._stage;this._renderer=this._stage.renderView.getDrapedRenderer();this._renderer.onHasHighlightsChanged=function(){return a.onHasHighlightsChanged()};this._renderer.onContentChanged=function(){return a.setDrawTexturesDirty()};this._renderer.onUpdatingChanged=function(){return a._setOverlayUpdating()};this._renderer.forceUpdate=function(b){a.updateOverlays(b);a._drawOverlayTextures()};this.groundIntersector=new Z(this.view.viewingMode);
this.groundIntersector.options.backfacesTerrain=!0;this.groundIntersector.options.invisibleTerrain=!0;this.groundIntersector.options.hud=!1;this._handles.add([this.view.watch(["pointsOfInterest.renderPointOfView","pointsOfInterest.centerOnSurfaceFrequent.location","pixelRatio"],function(){return a.setOverlayPlacementDirty()}),this.terrainSurface.on("elevation-change",function(){return a.setOverlayPlacementDirty()}),this.view.on("resize",function(){return a.setOverlayPlacementDirty()}),this.watch("suspended",
function(){return a._setOverlayUpdating()},!0),P.addFrameTask({preRender:function(b){a.hasOverlays()&&(a._dispatchRendererUpdate(b),a._drawOverlayTextures())}}),this.view.resourceController.scheduler.registerTask(aa.Task.OVERLAY_MANAGER,function(){return a.updateOverlays()},function(){return a.needsUpdate()})])};d.prototype.destroy=function(){var a=this;this._connectedLayers.forEach(function(b){return a._unregisterLayerView(b.layerView)});this._disposeOverlays();this._handles&&(this._handles.destroy(),
this._handles=null)};d.prototype.onHasHighlightsChanged=function(){this.setOverlayPlacementDirty();this.notifyChange("hasHighlights")};d.prototype.hasOverlays=function(){return!!this._overlays};d.prototype.setSpatialReference=function(a,b){this._overlaySR=a;this._longitudeCyclical=null;if(a){if(this._renderSR=this.view.renderSpatialReference,this._overlaySREqualsRenderSR=this._overlaySR.equals(this._renderSR),this._isSpherical=b)this._longitudeCyclical=a.isWebMercator?new F.Cyclical(-2.0037508342787E7,
2.0037508342787E7):new F.Cyclical(-180,180),this._renderer.longitudeCyclical=this._longitudeCyclical}else this._disposeOverlays()};d.prototype.updateLayerViews=function(a){for(var b=this,c=0,e=this.view.allLayerViews.items;c<e.length;c++){var d=e[c];"supportsDraping"in d&&d.supportsDraping&&!this._connectedLayers.has(d.uid)&&this._registerLayerView(d)}this._connectedLayers.forEach(function(c,e){c=c.layerView;a.has(e)||b._unregisterLayerView(c)})};d.prototype._registerLayerView=function(a){var b=this,
c=a.uid,e=a.on("draped-data-change",function(){return b.setOverlayPlacementDirty()});this._connectedLayers.set(c,{eventHandles:[e],layerView:a});a.setDrapingExtent&&this._overlays&&this._overlays.forEach(function(c,e){a.setDrapingExtent(e,c.extent,b._overlaySR,c.resolution,c.renderLocalOrigin,c.pixelRatio)});this.setOverlayPlacementDirty();this._setLayerViewOverlayUpdating(a,this.layerViewOverlayUpdating)};d.prototype._unregisterLayerView=function(a){var b=this;this._connectedLayers.forEach(function(c,
e){if(c.layerView===a){if(c.eventHandles)for(var d=0;d<c.eventHandles.length;d++)c.eventHandles[d].remove();b._connectedLayers.delete(e);b.setOverlayPlacementDirty();a.destroyed||b._setLayerViewOverlayUpdating(a,!1)}})};d.prototype.setOverlayPlacementDirty=function(){this._placementDirty||(this._placementDirty=!0,this._setOverlayUpdating())};d.prototype.updateOverlays=function(a){void 0===a&&(a=this.view.state.camera);if(this._overlaySR){var b;b=u.nextHighestPowerOfTwo(Math.max(a.fullWidth,a.fullHeight)+
256);var c=Math.min(b,this._maxResolution);this._computeOverlayExtents(a,b,v);this._initOverlays();this._updateOverlay(0,v.inner,c,1);this._updateOverlay(1,v.outer,c,f.width(v.inner)/f.width(v.outer));this.opacity=1;this.terrainSurface.updateTileOverlayParams();this._placementDirty=!1;this.setDrawTexturesDirty();this.terrainSurface.updateOverlayOpacity()}};d.prototype._updateOverlay=function(a,b,c,e){var d=this,g=this._overlays[a];if(ba(b,g.extent)||c!==g.resolution||g.pixelRatio!==e)f.set(g.extent,
b),g.resolution=c,g.pixelRatio=e,e=f.center(g.extent),g.renderLocalOrigin=G.fromValues(e[0],e[1],0,"OV_"+this._latestOriginId++),this._connectedLayers.forEach(function(e){e=e.layerView;e.setDrapingExtent&&e.setDrapingExtent(a,b,d._overlaySR,c,g.renderLocalOrigin,g.pixelRatio)})};d.prototype.needsUpdate=function(){return this._placementDirty&&(0<this._connectedLayers.size||0<this.view.graphics.length||E.OVERLAY_DRAW_TEST_TEXTURE)&&!!this._overlaySR&&!this._get("suspended")&&this.terrainSurface.ready};
d.prototype.updateOpacity=function(a){return this._overlays?this._getAltitudeBasedOpacity(a,this._renderedAltitude):1};d.prototype._getAltitudeBasedOpacity=function(a,b){return 3.5*a<b?Math.sqrt(u.clamp((a-b/10)/(b/3.5-b/10),0,1)):1};d.prototype.setTileParameters=function(a,b,c){if(this._overlays){var e=this._overlays[0],d=this._overlays[1];a=f.intersection(a.extent,a.surface.extent,H);this._rectInsideRect(a,e.extent)?(this._setTileOverlayData(a,e,b.overlays[0]),this._invalidateTileOverlayData(b.overlays[1])):
this._rectanglesOverlap(a,e.extent)?(this._setTileOverlayData(a,e,b.overlays[0]),this._setTileOverlayData(a,d,b.overlays[1])):(this._rectanglesOverlap(a,d.extent)?this._setTileOverlayData(a,d,b.overlays[0]):this._invalidateTileOverlayData(b.overlays[0]),this._invalidateTileOverlayData(b.overlays[1]))}else this._invalidateTileOverlayData(b.overlays[0]),this._invalidateTileOverlayData(b.overlays[1]);b.overlayOpacity=void 0!==c?c:1};d.prototype.overlayPixelSizeInMapUnits=function(a){if(!this._overlays)return 0;
var b=this._overlays[0],c=this._overlays[1];a=this._pointIsInExtent(a,b.extent)?b:c;return(a.extent[2]-a.extent[0])/a.resolution};d.prototype._setTileOverlayData=function(a,b,c){var e=b.extent;c.texScale[0]=(a[2]-a[0])/(e[2]-e[0]);c.texScale[1]=(a[3]-a[1])/(e[3]-e[1]);var d=a[0];if(this._longitudeCyclical){var d=this._longitudeCyclical.minimalMonotonic(e[0],d),g=this._longitudeCyclical.minimalMonotonic(e[0],a[2]);d>g&&(d=g-(a[2]-a[0]))}c.texOffset[0]=(d-e[0])/(e[2]-e[0]);c.texOffset[1]=(a[1]-e[1])/
(e[3]-e[1]);c.renderTargetId=b.valid?b.renderTargetId:null;c.highlightRenderTargetId=b.highlightValid?b.highlightRenderTargetId:null;c.waterMaskRenderTargetId=b.waterMaskValid?b.waterMaskRenderTargetId:null};d.prototype._invalidateTileOverlayData=function(a){a.renderTargetId=null;a.highlightRenderTargetId=null;a.waterMaskRenderTargetId=null};d.prototype._createEmptyOverlay=function(a){var b=this._renderer.createRenderTarget("overlay"+a,!0,8,9987),c=this._renderer.createRenderTarget("overlayHighlight"+
a,!1,8,9987);a=this._renderer.createRenderTarget("overlayWaterMask"+a,!0,8,9987);return{extent:f.create(),resolution:0,renderTargetId:b,valid:!1,highlightRenderTargetId:c,highlightValid:!1,waterMaskRenderTargetId:a,waterMaskValid:!1,renderLocalOrigin:G.fromValues(0,0,0,"O"),pixelRatio:1}};d.prototype._initOverlays=function(){this._overlays||(this._overlays=[this._createEmptyOverlay(0),this._createEmptyOverlay(1)])};d.prototype._disposeOverlays=function(){var a=this;this._overlays&&(this._overlays.forEach(function(b){a._renderer.disposeRenderTarget(b.renderTargetId);
a._renderer.disposeRenderTarget(b.highlightRenderTargetId);a._renderer.disposeRenderTarget(b.waterMaskRenderTargetId)}),this._overlays=null)};d.prototype._dispatchRendererUpdate=function(a){var b=S.Milliseconds(a.time-this._animationTimeLast);b<V.DESIRED_DRAPED_ANIMATION_MS||(this._animationTimeLast=a.time,this._renderer.updateLogic({dt:b,camera:this._stage.getCamera()})&&(this._drawTexturesAnimateDirty=!0))};d.prototype.setDrawTexturesDirty=function(){this._overlays?this._drawTexturesDirty||(this._drawTexturesDirty=
!0,this._setOverlayUpdating()):this.setOverlayPlacementDirty()};d.prototype._intersectGroundFromView=function(a,b,c,e){c=this.view.sceneIntersectionHelper.getCenterRayWithSubpixelOffset(a,da,b,c);b=c.origin;c=p.vec3.add(A,c.origin,c.direction);this.groundIntersector.reset(b,c);this.groundIntersector.intersect([],null,a);this.view.basemapTerrain.intersect(this.groundIntersector,null,b,c);return this.groundIntersector.results.min.getIntersectionPoint(e)};d.prototype._setLayerViewOverlayUpdating=function(a,
b){"overlayUpdating"in a&&(a.overlayUpdating=b)};Object.defineProperty(d.prototype,"layerViewOverlayUpdating",{get:function(){return this.needsUpdate()||this._drawTexturesDirty||this._renderer.updating},enumerable:!0,configurable:!0});d.prototype._setOverlayUpdating=function(){var a=this,b=this.layerViewOverlayUpdating;this._connectedLayers.forEach(function(c){return a._setLayerViewOverlayUpdating(c.layerView,b)});var c=this.view.graphicsView;O.isSome(c)&&(c.overlayUpdating=b)};d.prototype._findHorizonBasedPointOfInterest=
function(a,b,c){var e=.5;if("global"===this.view.viewingMode){e=x.vec3f64.clone(a.eye);p.vec3.normalize(e,e);p.vec3.negate(e,e);b=p.vec3.length(b);b=Math.asin(b/p.vec3.length(a.eye));var d=Math.acos(p.vec3.dot(a.viewForward,e)),e=u.clamp((b-(d-.5*a.fovY))/a.fovY,0,1);b=u.clamp((-b-(d-.5*a.fovY))/a.fovY,0,1);e=1===e&&0===b?.5:b+.55*(e-b)}else e=D.vec4f64.fromValues(0,Math.tan(.5*Math.PI-Math.acos(-a.viewForward[2])),1,0),e=r.vec4.transformMat4(e,e,a.projectionMatrix)[1],e=u.clamp(.5+.5*e,0,1),e=1===
e||0===e?.5:0<a.eye[2]?.55*e:1-.55*(1-e);return this._intersectGroundFromView(a,.5,e,c)?!0:!1};d.prototype._computeOverlayExtents=function(a,b,c){var e=this.terrainSurface.extent,d=this.view.pointsOfInterest.centerOnSurfaceFrequent.renderLocation,g=x.vec3f64.create();this._findHorizonBasedPointOfInterest(a,d,g)||p.vec3.copy(g,d);this._renderedAltitude=this.view.renderCoordsHelper.getAltitude(a.eye);var k=p.vec3.distance(a.eye,g),d=U.viewAngle(this.view.renderCoordsHelper,d,a.eye),d=Math.PI/2-Math.abs(d-
Math.PI/2);if(E.OVERLAY_SHOW_CENTER){var l=new T({color:[255,0,0],outline:{color:[255,255,255],width:2}}),m=new R;w.vectorToPoint(g,this._renderSR,m,this._overlaySR);l=new J({geometry:m,symbol:l});void 0!==z&&this.view.graphics.remove(z);this.view.graphics.add(l);z=l}this._overlaySREqualsRenderSR||w.vectorToVector(g,this._renderSR,g,this._overlaySR);b=b*a.perRenderPixelRatio*k/2;m=!1;k=Infinity;this._isSpherical&&(this._overlaySR.isWebMercator?(b/=Math.cos(w.webMercator.y2lat(g[1])),k=this.terrainSurface.extent[3],
k*=.999):(m=!0,b/=X.metersPerDegree,k=90),b>=k&&(b=k,g[1]=0,this._overlaySR.isWebMercator&&(g[0]=0)));l=1;m&&(l=1/Math.max(.2,Math.cos(Math.abs(N.deg2rad(g[1])))),180<b*l&&(l=180/b));var h=b*l,m=c.inner;m[0]=g[0]-h;m[1]=g[1]-b;m[2]=g[0]+h;m[3]=g[1]+b;this._isSpherical&&this._shiftExtentToFitBounds(m,Infinity,k);c=c.outer;f.set(c,m);6*h>e[2]-e[0]?f.set(c,e):d<=.25*Math.PI?(c[0]-=h,c[1]-=b,c[2]+=h,c[3]+=b):(w.vectorToVector(a.eye,this._renderSR,A,this._overlaySR),Q.vec2.subtract(n,g,A),a=-Math.atan2(n[1],
n[0])+.125*Math.PI,0>a&&(a+=2*Math.PI),r.vec4.scale(n,ca[Math.floor(a/(.25*Math.PI))],2*b),n[0]*=l,n[2]*=l,r.vec4.add(c,c,n));this._isSpherical&&(c[0]=this._longitudeCyclical.clamp(c[0]),c[2]=this._longitudeCyclical.clamp(c[2]),c[1]=Math.max(c[1],-k),c[3]=Math.min(c[3],k));!this._isSpherical&&e&&(a=f.intersection(m,e,H),e=f.intersection(c,e,ea),f.contains(a,e)&&(c[2]=c[0],c[3]=c[1]))};d.prototype._drawOverlayTextures=function(){if(this._drawTexturesDirty||this._drawTexturesAnimateDirty){var a=this._drawOverlay(0),
b=this._drawOverlay(1);0!==a&&0!==b||this.terrainSurface.updateTileOverlayParams();this._drawTexturesDirty?(this._drawTexturesAnimateDirty=this._drawTexturesDirty=!1,this._setOverlayUpdating(),this.terrainSurface.requestRender(),this.terrainSurface.setPendingUpdates()):(this._drawTexturesAnimateDirty=!1,this._setOverlayUpdating(),this.terrainSurface.requestRender(0))}};d.prototype._setupGeometryViewsCyclical=function(a,b,c){this._setupGeometryViewsDirect(a,b,c);var d=.001*this._longitudeCyclical.range;
if(b[0]-d<=this._longitudeCyclical.min){var h=a.views[a.numViews++];r.vec4.set(h.viewport,0,0,c,c);f.offset(b,this._longitudeCyclical.range,0,h.extent)}b[2]+d>=this._longitudeCyclical.max&&(h=a.views[a.numViews++],r.vec4.set(h.viewport,0,0,c,c),f.offset(b,-this._longitudeCyclical.range,0,h.extent))};d.prototype._setupGeometryViewsDirect=function(a,b,c){a.numViews=1;a=a.views[0];f.set(a.extent,b);r.vec4.set(a.viewport,0,0,c,c)};d.prototype._drawOverlay=function(a){var b=this._overlays[a],c=b.valid,
d=b.highlightValid,f=b.waterMaskValid,g=b.extent,k=b.resolution,l=b.pixelRatio;this._longitudeCyclical?this._setupGeometryViewsCyclical(h,g,k):this._setupGeometryViewsDirect(h,g,k);h.width=k;h.height=k;h.pixelRatio=l*this.view.state.camera.pixelRatio;h.index=a;k=this._renderer;a=k.draw(b.renderTargetId,h);g=k.drawHighlights(b.highlightRenderTargetId,h);k=k.drawNormals(b.waterMaskRenderTargetId,h);b.valid=a;b.highlightValid=g;b.waterMaskValid=k;return a!==c||g!==d||k!==f?0:1};d.prototype._rectanglesOverlap=
function(a,b){return this._longitudeCyclical?(this._longitudeCyclical.contains(b[0],b[2],a[0])||this._longitudeCyclical.contains(b[0],b[2],a[2])||this._longitudeCyclical.contains(a[0],a[2],b[0]))&&!(a[1]>b[3]||a[3]<b[1]):f.intersects(a,b)};d.prototype._rectInsideRect=function(a,b){return this._longitudeCyclical?this._longitudeCyclical.contains(b[0],b[2],a[0])&&this._longitudeCyclical.contains(b[0],b[2],a[2])&&a[1]>b[1]&&a[3]<b[3]:f.contains(b,a)};d.prototype._pointIsInExtent=function(a,b){if(this._longitudeCyclical)return this._longitudeCyclical.contains(b[0],
b[2],a.x)&&a.y>=b[1]&&a.y<=b[3];var c=a.x;a=a.y;return c>b[0]&&c<b[2]&&a>b[1]&&a<b[3]};d.prototype._shiftExtentToFitBounds=function(a,b,c){var d=0,h=0;a[0]<-b?d=a[0]+b:a[2]>b&&(d=b-a[2]);a[1]<-c?h=a[1]+c:a[3]>c&&(h=c-a[3]);f.offset(a,d,h)};Object.defineProperty(d.prototype,"test",{get:function(){return{overlays:this._overlays,renderer:this._renderer}},enumerable:!0,configurable:!0});t([q.property()],d.prototype,"view",void 0);t([q.property()],d.prototype,"terrainSurface",void 0);t([q.property({readOnly:!0,
aliasOf:"terrainSurface.suspended"})],d.prototype,"suspended",void 0);t([q.property({type:Boolean})],d.prototype,"hasHighlights",null);return d=t([q.subclass("esri.views.3d.terrain.OverlayManager")],d)}(q.declared(K));C.OverlayManager=B;var h={width:0,height:0,pixelRatio:0,views:[{viewport:f.create(),extent:f.create()},{viewport:f.create(),extent:f.create()},{viewport:f.create(),extent:f.create()}],numViews:0,index:0},n=D.vec4f64.create(),A=x.vec3f64.create(),v={inner:f.create(),outer:f.create()},
H=f.create(),ea=f.create(),da=Y.ray.create()});