// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/arrayUtils ../../../core/mathUtils ../../../core/libs/gl-matrix-2/vec2 ../../../core/libs/gl-matrix-2/vec2f64 ../../../core/libs/gl-matrix-2/vec4 ../../../core/libs/gl-matrix-2/vec4f64 ../../../geometry/support/aaBoundingBox ../support/buffer/glUtil ./PatchGeometryFactory ./TerrainConst ./tileUtils ../webgl-engine/lib/DefaultVertexAttributeLocations ../../webgl/BufferObject ../../webgl/VertexArrayObject".split(" "),function(n,p,v,w,q,x,y,r,t,z,A,B,C,D,u,E){Object.defineProperty(p,
"__esModule",{value:!0});n=function(){function b(){this.overlayTexOffset=x.vec2f64.create();this.texOffsetAndScale=r.vec4f64.create();this.geometryInfo={indices:null,vertexAttributes:null,boundingBox:t.empty(),numSurfaceIndices:0,numSkirtIndices:0,numWithoutSkirtIndices:0,numVertsPerRow:0,skirtLength:0,uvOffsetAndScale:r.vec4f64.create()}}b.prototype.init=function(a){this.tile=a;a=this.geometryInfo;a.indices=null;a.vertexAttributes=null;t.empty(a.boundingBox);a.numSurfaceIndices=0;a.numSkirtIndices=
0;a.numWithoutSkirtIndices=0;a.numVertsPerRow=0;this.geometryState={numVertsPerRow:0,samplerData:null,clippingArea:null,wireframe:!1};this.textureReference=this._texture=this._vao=null;y.vec4.set(this.texOffsetAndScale,0,0,1,1);this.opacity=1;if(this.overlays){a=0;for(var f=this.overlays;a<f.length;a++){var c=f[a];c.renderTargetId=null;c.highlightRenderTargetId=null;c.waterMaskRenderTargetId=null;q.vec2.set(c.texScale,1,1);q.vec2.set(c.texOffset,0,0)}}else for(this.overlays=[null,null],a=0;2>a;a++)this.overlays[a]=
{renderTargetId:null,highlightRenderTargetId:null,waterMaskRenderTargetId:null,texScale:[1,1],texOffset:[0,0]};this.overlayOpacity=1;this.localOrigin=null};b.prototype.updateGeometry=function(a,f){if(!this._updateGeometryState(f))return!1;this._releaseGeometry();this._createGeometry(a);return!0};b.prototype.releaseGeometry=function(){return this._releaseGeometry()?(this.geometryState={numVertsPerRow:0,samplerData:null,clippingArea:null,wireframe:!1},!0):!1};b.prototype.ensureTexture=function(a,f){this._texture&&
this._texture.descriptor.width!==a&&this.releaseTexture();this._texture||(this._texture=f(),this.tile.setMemoryDirty());return this._texture};b.prototype.releaseTexture=function(){this._texture&&(this._texture.dispose(),this._texture=null,this.tile.setMemoryDirty());this.textureReference=null};b.prototype._updateGeometryState=function(a){var f=this._getElevationInfo(),c=this.tile.level,d=8>c?this.tile.numSubdivisionsAtLevel[c]+1:2;f.samplerData&&(d=this.tile.maxTesselation,d=w.clamp((d>>Math.max(c-
f.maxTileLevel,B.ELEVATION_DESIRED_RESOLUTION_LEVEL-(this.tile.vlevel-c)))+1,2,d+1));c=this.tile.clippingArea;if(!this.tile.intersectsClippingArea||this.tile.isWithinClippingArea)c=null;var e=this.geometryState,b=!1;e.numVertsPerRow!==d&&(e.numVertsPerRow=d,b=!0);f.changed&&(e.samplerData=f.samplerData,b=!0);v.equals(e.clippingArea,c)||(e.clippingArea=c,b=!0);e.wireframe!==a&&(e.wireframe=a,b=!0);return b};b.prototype._createGeometry=function(a){this.tile.createGeometry(this.geometryState,this.localOrigin);
var b=this.geometryInfo.vertexAttributes,c=this.geometryInfo.indices,d=a.gl;this._vao=new E(a,D.Default3D,{geometry:z.glLayout(b.layout)},{geometry:u.createVertex(a,d.STATIC_DRAW,b.buffer)},u.createIndex(a,d.STATIC_DRAW,c))};b.prototype._releaseGeometry=function(){if(!this._vao)return!1;this._vao.dispose();this._vao=null;A.releaseGeometry(this.geometryInfo);return!0};Object.defineProperty(b.prototype,"vao",{get:function(){return this._vao},enumerable:!0,configurable:!0});b.prototype._getElevationInfo=
function(){for(var a=this.geometryState.samplerData,b=this.tile.layerInfo[0],c=b.length,d=Array(c),e=0,l=0,m=!1,k=0;k<c;k++){var h=b[k];if(h.upsampleInfo){var h=h.upsampleInfo.tile,g=h.layerInfo[0][k].data,g=g&&g.samplerData;a&&a[e]===g||(m=!0);d[e++]=g;l=Math.max(l,h.lij[0])}else h.data&&(g=this.tile.surface.layerViewByIndex(k,0),C.fallsWithinLayer(this.tile,g.layer,!1)&&(g=h.data,a&&a[e]===g.samplerData||(m=!0),d[e++]=g.samplerData,l=this.tile.lij[0]))}a&&a.length!==e&&(m=!0);0<e?d.length=e:d=null;
return{changed:m,samplerData:d,maxTileLevel:l}};Object.defineProperty(b.prototype,"estimatedGeometryMemoryUsage",{get:function(){return this.geometryInfo.indices.byteLength+this.geometryInfo.vertexAttributes.byteLength},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"textureDescriptor",{get:function(){return this._texture?this._texture.descriptor:null},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"test",{get:function(){return{hasTexture:null!=this._texture}},
enumerable:!0,configurable:!0});return b}();p.PatchRenderData=n});