// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/arrayUtils ../../../core/mathUtils ../../../core/promiseUtils ../../../core/libs/gl-matrix-2/vec2 ../../../core/libs/gl-matrix-2/vec2f64 ../../../core/libs/gl-matrix-2/vec3 ../../../core/libs/gl-matrix-2/vec3f64 ../../../core/libs/gl-matrix-2/vec4 ../../../core/libs/gl-matrix-2/vec4f64 ../../../geometry/support/aaBoundingRect ../../2d/engine/vectorTiles/VectorTile ./ElevationBounds ./ElevationTileAgent ./MapTileAgent ./TerrainConst ./terrainUtils ./TileAgent ./TilePerLayerInfo ./tileUtils ../../webgl/Texture ../../webgl/Util".split(" "),
function(u,x,J,K,L,y,M,f,p,N,O,z,F,G,A,B,n,P,g,H,m,I,C){function v(b){b.dispose();b instanceof A?A.Pool.release(b):b instanceof B&&B.Pool.release(b)}Object.defineProperty(x,"__esModule",{value:!0});var D=P.weakAssert,E=p.vec3f64.create(),r=p.vec3f64.create(),h=p.vec3f64.create(),q=O.vec4f64.create();u=function(){return function(){this.angledSplitBias=this.maxLod=this.relativeHeightLimit=this.relativeWidthLimit=this.fovY=this.fovX=0;this.aboveGround=!0}}();x.SplitLimits=u;u=function(){function b(a){this._numSubdivisionAtLevel=
a;this.lij=[0,0,0];this._children=[null,null,null,null];this._dirty=!0;this.extent=z.create();this._elevationBounds=M.vec2f64.create();this.layerInfo=Array(2);this.extentInRadians=z.create();this.centerAtSeaLevel=p.vec3f64.create();this._center=[p.vec3f64.create(),p.vec3f64.create(),p.vec3f64.create()];this.up=p.vec3f64.unitZ();this._intersectsClippingArea=this._isWithinClippingArea=!0;this._clippingArea=null;this._maxTesselation=0;this._usedMemory=t;this._curvatureHeight=this._radius=this._edgeLen2=
this._edgeLen=this.renderOrder=this._screenDepth=this._mapDataRefCount=this._mapTileMemory=0}Object.defineProperty(b.prototype,"usedMemory",{get:function(){this._usedMemory===t&&this._updateMemoryUsed();return this._usedMemory+(this.isCached?0:this.mapTileMemory)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"cachedMemory",{get:function(){return this.isCached?this.mapTileMemory:0},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"mapTileMemory",{get:function(){this._usedMemory===
t&&this._updateMemoryUsed();for(var a=this._mapTileMemory,c=0,e=this.layerInfo[1];c<e.length;c++){var b=e[c].data;b instanceof F.VectorTile&&(a+=b.getMemoryUsage())}return a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"isCached",{get:function(){return!this.shouldRender&&0>=this._mapDataRefCount},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"maxTesselation",{get:function(){return this._maxTesselation},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,
"numSubdivisionsAtLevel",{get:function(){return this._numSubdivisionAtLevel},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"isWithinClippingArea",{get:function(){return this._isWithinClippingArea},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"intersectsClippingArea",{get:function(){return this._intersectsClippingArea},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"clippingArea",{get:function(){return this._clippingArea},enumerable:!0,configurable:!0});
Object.defineProperty(b.prototype,"parent",{get:function(){return this._parent},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"children",{get:function(){return this._children},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"surface",{get:function(){return this._surface},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"elevationBounds",{get:function(){return this._elevationBounds},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,
"level",{get:function(){return this.lij[0]},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"edgeLen",{get:function(){return this._edgeLen},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"radius",{get:function(){return this._radius},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"screenDepth",{get:function(){return this._screenDepth},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"visible",{get:function(){if(this._dirty){var a=
this._isVisible();a!==this._visible&&(this._visible=a,this.updateAgentSuspension(),this._visible=a);this._dirty=!1}return this._visible},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"rendered",{get:function(){return!!this.renderData},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"shouldRender",{get:function(){if(!this.visible)return!1;if(0===this.surface.lodSnapping){var a=this.level-this._surface.snapLevel;if(0===a)return!0;if(1===a)return!1}return this.isLeaf},
enumerable:!0,configurable:!0});b.prototype.init=function(a,c,e){this.lij[0]=a[0];this.lij[1]=a[1];this.lij[2]=a[2];e.tilingScheme.getExtent(a[0],a[1],a[2],this.extent,this.extentInRadians);this._intersectsClippingArea=this._isWithinClippingArea=!0;this._clippingArea=null;this._mapDataRefCount=0;e.upsampleMapCache.pop(m.tile2str(this));this._radius=this._edgeLen2=this._edgeLen=0;this.vlevel=a?a[0]:0;c&&c._elevationBounds?y.vec2.copy(this._elevationBounds,c.elevationBounds):y.vec2.set(this._elevationBounds,
0,0);this._pendingUpdates=0;this.renderData=null;this._screenDepth=0;this._visible=!1;this._parent=c;this.unsetChildren();this._surface=e;this.updateVisibility();for(a=0;2>a;a++){c=e.numLayers(a);var b=this.layerInfo[a];this.layerInfo[a]?b.length=c:(b=Array(c),this.layerInfo[a]=b);for(var d=0;d<c;d++)b[d]=H.TilePerLayerInfo.makeEmptyLayerInfo(a,this._surface.upsampleInfoPool,b[d]),0===a&&this.findElevationBoundsForLayer(d,-1)}this.computeElevationBounds();this._maxTesselation=Math.min(e.tilingScheme.pixelSize,
n.MAX_PATCH_TESSELATION)};b.prototype.release=function(){D(!this.renderData,"tile.renderData was not unloaded");this._surface.upsampleMapCache.pop(m.tile2str(this));for(var a=0;2>a;a++)for(var c=0,e=this.layerInfo[a];c<e.length;c++)e[c].dispose();this._surface=this._parent=null;this._usedMemory=t};b.prototype.refMapData=function(){++this._mapDataRefCount;this.isCached||this._surface.upsampleMapCache.pop(m.tile2str(this))};b.prototype.unrefMapData=function(){--this._mapDataRefCount;if(this.isCached){var a=
this.cachedMemory;0<a&&(this._surface.upsampleMapCache.put(m.tile2str(this),this,a),this.setMemoryDirty())}};b.prototype.setMemoryDirty=function(){this._usedMemory=t};Object.defineProperty(b.prototype,"cpuImageMemorySize",{get:function(){var a=this._surface.tilingScheme.pixelSize;return a*a*4},enumerable:!0,configurable:!0});b.prototype._updateMemoryUsed=function(){this._mapTileMemory=this._usedMemory=0;for(var a=this.cpuImageMemorySize,c=0,e=this.layerInfo[1];c<e.length;c++){var b=e[c],b=b.data;
b instanceof I?this._mapTileMemory+=C.getGpuMemoryUsage(b):b instanceof HTMLImageElement&&(this._mapTileMemory+=a)}c=0;for(e=this.layerInfo[0];c<e.length;c++)b=e[c],this._usedMemory+=b.data?a:0;this.renderData&&(this._usedMemory+=this.renderData.estimatedGeometryMemoryUsage,a=this.renderData.textureDescriptor)&&(this._mapTileMemory+=C.getGpuMemoryUsage(a));this.isCached&&this._surface.upsampleMapCache.updateSize(m.tile2str(this),this,this.cachedMemory)};b.prototype.getUsedMemoryForLayer=function(a,
c){c=this.layerInfo[a][c];if(!c||!c.data)return 0;if(1===a&&!this.isCached){a=c.data;if(a instanceof I)return C.getGpuMemoryUsage(a);if(a instanceof HTMLImageElement)return this.cpuImageMemorySize;if(a instanceof F.VectorTile)return a.getMemoryUsage()}else if(0===a)return this.cpuImageMemorySize;return 0};b.prototype.updateScreenDepth=function(a){f.vec3.copy(q,this._center[0]);q[3]=1;N.vec4.transformMat4(q,q,a);this._screenDepth=0>q[2]?0:q[2]/q[3]};b.prototype.shouldSplit=function(a,c,b){var e=this.level;
f.vec3.subtract(E,this._center[0],c);var d=f.vec3.squaredLength(E),w=0;f.vec3.subtract(r,this._center[1],c);var l=f.vec3.squaredLength(r);l<d&&(d=l,w=1);f.vec3.subtract(r,this._center[2],c);l=f.vec3.squaredLength(r);l<d&&(d=l,w=2);if(this._edgeLen2>d&&e<a.maxLod||0===b&&1===this._surface.snapLevel-e)return 1;b=Math.sqrt(d);var l=f.vec3.dot(this.up,E),d=this._elevationBounds[1]-this._elevationBounds[0],g=d/this.edgeLen;if(a.aboveGround&&0<l&&.001>g&&0<l/b-Math.sin(this._curvatureHeight/(this.edgeLen*
Math.SQRT1_2)*Math.PI)-g)return 0;g=this._edgeLen/(a.fovX*b*2);return g<a.relativeWidthLimit?this.vlevel!==this.level?(this.vlevel=this.level,2):0:e>=a.maxLod?(a=e+Math.ceil(-K.log2(a.relativeWidthLimit/g)),a!==this.vlevel?(this.vlevel=a,2):0):6<e&&(f.vec3.subtract(r,this._center[w],c),f.vec3.scale(h,this.up,l),f.vec3.subtract(h,h,r),e=f.vec3.squaredLength(h),e>this._radius*this._radius&&(f.vec3.scale(h,h,this._radius/Math.sqrt(e)),f.vec3.add(h,h,this._center[w]),f.vec3.subtract(h,c,h),Math.min(1,
(Math.abs(f.vec3.dot(h,this.up))+.5*d+this._curvatureHeight)/f.vec3.length(h))*(this._edgeLen/(a.fovY*b*2))<.1/a.angledSplitBias*a.relativeHeightLimit))?0:1};b.prototype.setChildren=function(a,c,b,k){D(!!(a&&c&&b&&k),"Null child passed");this._children[0]=a;this._children[1]=c;this._children[2]=b;this._children[3]=k};b.prototype.unsetChildren=function(){this._children[0]=null;this._children[1]=null;this._children[2]=null;this._children[3]=null};b.prototype.load=function(a){this.refMapData();for(var c=
0;2>c;c++)this.layerInfo[c]&&this._createOrUpdateAgents(0,c);a.loadTile(this)};b.prototype.unload=function(a){a.unloadTile(this);for(a=0;2>a;a++)for(var c=0,b=this.layerInfo[a];c<b.length;c++){var k=b[c];k.loadingAgent&&k.loadingAgent!==g.TILE_AGENT_DONE&&(v(k.loadingAgent),k.loadingAgent=null);k.pendingUpdates=0}this.resetPendingUpdate(16);this.resetPendingUpdate(32);this.unrefMapData()};b.prototype.unloadMapData=function(){for(var a=0,c=this.layerInfo[1];a<c.length;a++){var b=c[a];b.loadingAgent&&
b.loadingAgent!==g.TILE_AGENT_DONE&&(v(b.loadingAgent),b.loadingAgent=null);b.pendingUpdates=0}this.renderData&&this.renderData.releaseTexture();this.setMemoryDirty()};b.prototype.updateClippingStatus=function(a){if(z.equals(a,this._clippingArea))return!1;var c=this._intersectsClippingArea,b=this._isWithinClippingArea;a?(this._intersectsClippingArea=this.intersectsExtent(a),this._isWithinClippingArea=this.isWithinExtent(a)):this._isWithinClippingArea=this._intersectsClippingArea=!0;this._clippingArea=
a;this.updateVisibility();a=b&&this._isWithinClippingArea;c=!b&&!c&&!this._isWithinClippingArea&&!this._intersectsClippingArea;!this.renderData||a||c||this.setPendingUpdate(16);return!0};b.prototype.updateVisibility=function(){this._dirty=!0;this._surface.setPendingUpdates()};b.prototype.getLayerInfo=function(a,c){return this.layerInfo[c][a]};b.prototype.hasLayerData=function(a,c){a=this.layerInfo[c][a];return!(!a||!a.data||a.dataInvalidated)};b.prototype.hasDataAvailable=function(a,c,b){return(c=
this.layerInfo[b][c].tilemap)?"unavailable"!==c.getAvailability(a.lij[1],a.lij[2]):!0};Object.defineProperty(b.prototype,"updating",{get:function(){if(this.hasPendingUpdates)return!0;for(var a=0;2>a;a++)for(var c=0,b=this.layerInfo[a];c<b.length;c++){var k=b[c];if(k.loadingAgent&&k.loadingAgent!==g.TILE_AGENT_DONE&&k.loadingAgent.updating)return!0}return!1},enumerable:!0,configurable:!0});b.prototype.isSuspended=function(a){return this.hasPendingUpdate(1)?!0:0===a?!1:!this.visible};Object.defineProperty(b.prototype,
"hasPendingUpdates",{get:function(){return 0!==this._pendingUpdates},enumerable:!0,configurable:!0});b.prototype.hasPendingUpdate=function(a){return(this._pendingUpdates&a)===a};b.prototype.setPendingUpdate=function(a){this._pendingUpdates|=a;this._surface.setPendingUpdates()};b.prototype.resetPendingUpdate=function(a){return this.hasPendingUpdate(a)?(this._pendingUpdates&=~a,!0):!1};b.prototype.requestLayerData=function(a,c,b){n.TILE_LOADING_DEBUGLOG&&console.log("tile %s layer %d/%d requested by tile %s",
this.lij.toString(),c,a,b.tile.lij.toString());var e=this.layerInfo[c][a];if(-1<e.waitingAgents.indexOf(b))return console.warn("agent already requested this piece of map data (tile %s, agent tile %s, layer: %d/%d)",this.lij.toString(),b.tile.lij.toString(),c,a),!0;e.waitingAgents.push(b);if(e.data&&!e.dataInvalidated)return console.warn("agent requested existing data (tile %s, agent tile %s, layer: %d/%d)",this.lij.toString(),b.tile.lij.toString(),c,a),b.dataArrived(this),!0;if(e.requestPromise)return!0;
e.requestAbort=L.createAbortController();var d=this._surface.requestTileData(this,a,c,e.requestAbort);if(!d)return e.requestAbort=null,!1;a=function(){e.requestPromise===d&&(e.requestPromise=null,e.requestAbort=null)};e.requestPromise=d;d.then(a,a);return!!e.requestPromise};Object.defineProperty(b.prototype,"isLeaf",{get:function(){return null==this._children[0]},enumerable:!0,configurable:!0});b.prototype.hasLij=function(a){return this.lij[0]===a[0]&&this.lij[1]===a[1]&&this.lij[2]===a[2]};b.prototype.findByLij=
function(a){return this.hasLij(a)?this:this.isLeaf?null:(a=this._children[0].findByLij(a)||this._children[1].findByLij(a)||this._children[2].findByLij(a)||this._children[3].findByLij(a))?a:null};b.prototype.distanceToSquared=function(a){return f.vec3.squaredLength(f.vec3.subtract(h,this._center[0],a))};b.prototype.containsPoint=function(a){var c=this.extent;return a[0]>=c[0]&&a[1]>=c[1]&&a[0]<=c[2]&&a[1]<=c[3]};b.prototype.unrequestLayerData=function(a,c,b){n.TILE_LOADING_DEBUGLOG&&console.log("tile %s layer %d/%d canceled by tile %s",
this.lij.toString(),c,a,b.tile.lij.toString());var e=this.layerInfo[c][a],d=e.waitingAgents;b=null!=J.removeUnordered(d,b);D(b,"agent has not requested this piece of map data");1>d.length&&(e.abortRequest(),n.TILE_LOADING_DEBUGLOG&&console.log("tile %s layer %d/%d request/loading canceled",this.lij.toString(),c,a),this._updateMemoryUsed())};b.prototype.dataArrived=function(a,c,b){a=this.layerInfo[c][a];a.data=b;a.dataInvalidated=!1;for(b=0;b<a.waitingAgents.length;b++)a.waitingAgents[b].dataArrived(this);
a.waitingAgents.length=0;this._updateMemoryUsed()};b.prototype.dataMissing=function(a,c,b){b.notInTilemap||console.error("Tile "+this.lij.toString()+" layer "+c+"/"+a+" error "+b);a=this.layerInfo[c][a];a.dataMissing=!0;for(c=0;c<a.waitingAgents.length;c++)a.waitingAgents[c].dataMissing();a.waitingAgents.length=0;this._updateMemoryUsed()};b.prototype.updateRenderData=function(a){switch(a){case 1:return this.updateTexture();case 0:return this.updateGeometry()}};b.prototype.updateTexture=function(){this.renderData&&
this.setPendingUpdate(32)};b.prototype.updateGeometry=function(){this.setPendingUpdate(16);for(var a=0,c=this.layerInfo[0];a<c.length;a++)c[a].pendingUpdates|=16};b.prototype.invalidateLayerData=function(a,c){this.layerInfo[c][a].invalidateSourceData();this.restartAgents(c)};b.prototype.computeElevationBounds=function(){y.vec2.set(this._elevationBounds,Number.MAX_VALUE,-Number.MAX_VALUE);for(var a=!0,c=0,b=this.layerInfo[0];c<b.length;c++){var k=b[c];k.elevationBounds&&(this._elevationBounds[0]=Math.min(this._elevationBounds[0],
k.elevationBounds.min),this._elevationBounds[1]=Math.max(this._elevationBounds[1],k.elevationBounds.max),k.elevationBounds.hasNoDataValues||(a=!1))}a&&(this._elevationBounds[0]=Math.min(this._elevationBounds[0],0),this._elevationBounds[1]=Math.max(this._elevationBounds[1],0));this.updateRadiusAndCenter()};b.prototype._updateCenter=function(){f.vec3.scale(h,this.up,.5*(this._elevationBounds[0]+this._elevationBounds[1]));f.vec3.add(this._center[0],this.centerAtSeaLevel,h);f.vec3.scale(h,this.up,this._elevationBounds[0]);
f.vec3.add(this._center[1],this.centerAtSeaLevel,h);f.vec3.scale(h,this.up,this._elevationBounds[1]);f.vec3.add(this._center[2],this.centerAtSeaLevel,h)};b.prototype.findElevationBoundsForLayer=function(a,b){var c=this.layerInfo[0][a];if(!c.elevationBounds||c.elevationBounds.level<b)if(b=this._surface.layerViewByIndex(a,0),m.fallsWithinLayer(this,b.layer,!1)){b=Q;var k=!1;if(c.data){var d=c.data;b.min=d.bounds[0];b.max=d.bounds[1];b.hasNoDataValues=d.hasNoDataValues;b.level=this.lij[0];k=!0}else{for(var f=
0,l=void 0,d=void 0,g=this._parent;g&&(!d||f<n.ELEVATION_DESIRED_RESOLUTION_LEVEL)&&!(f=this.vlevel-g.level,l=d||l,d=g.layerInfo[0][a].data,!d&&l&&f>=n.ELEVATION_DESIRED_RESOLUTION_LEVEL);g=g._parent);if(d=d||l)d.computeMinMaxValue(this.lij[0],this.lij[1],this.lij[2],b),Infinity!==b.min&&(b.level=d.level,k=!0)}k&&(c.elevationBounds||(c.elevationBounds=new G.ElevationBounds),c.elevationBounds.copyFrom(b))}};b.prototype.modifyLayers=function(a,b,e){for(var c=this.layerInfo[e],d=0;d<c.length;d++){var f=
c[d];f.loadingAgent&&f.loadingAgent!==g.TILE_AGENT_DONE&&(v(f.loadingAgent),f.loadingAgent=null);f.waitingAgents.length=0}if(1===e)for(d=0;d<c.length;++d)void 0===a[d]&&c[d].dispose();a=b.length;f=Array(a);for(d=0;d<a;d++){var l=b[d];f[d]=-1<l?c[l]:H.TilePerLayerInfo.makeEmptyLayerInfo(e,this._surface.upsampleInfoPool)}this.layerInfo[e]=f;this._updateMemoryUsed()};b.prototype.restartAgents=function(a){this.renderData&&(this._createOrUpdateAgents(0,a),this.updateRenderData(a))};b.prototype.updateAgents=
function(a){if(this.renderData){for(var b=this.layerInfo[a],e=0;e<b.length;e++){var f=b[e];f.loadingAgent===g.TILE_AGENT_DONE&&(f.loadingAgent=null)}this._createOrUpdateAgents(0,a)}};b.prototype.updateAgentSuspension=function(){for(var a=0;2>a;a++)for(var b=this.isSuspended(a),e=0,f=this.layerInfo[a];e<f.length;e++){var d=f[e];d.loadingAgent&&d.loadingAgent!==g.TILE_AGENT_DONE&&(d.loadingAgent.setSuspension(b),d.loadingAgent===g.TILE_AGENT_DONE&&this.updateRenderData(a))}};b.prototype.removeLayerAgent=
function(a,b){a=this.layerInfo[b][a];a.loadingAgent&&a.loadingAgent!==g.TILE_AGENT_DONE&&a.loadingAgent.dispose();a.loadingAgent=null};b.prototype.agentDone=function(a,b){var c=this.layerInfo[b][a];c.loadingAgent=g.TILE_AGENT_DONE;c.data||c.upsampleInfo||this._createOrUpdateAgents(a+1,b)};b.prototype._createOrUpdateAgents=function(a,b){for(var c=this.isSuspended(b),f=this.layerInfo[b];a<f.length;++a){var d=f[a],h=!1,l=this._surface.layerViewByIndex(a,b);if(d.loadingAgent)m.fallsWithinLayer(this,l.layer,
!1)?(d.loadingAgent!==g.TILE_AGENT_DONE&&(n.TILE_LOADING_DEBUGLOG&&console.log(m.tile2str(this),"update suspended",c),d.loadingAgent.setSuspension(c)),d.loadingAgent!==g.TILE_AGENT_DONE&&(h=d.loadingAgent.update(),n.TILE_LOADING_DEBUGLOG&&console.log(m.tile2str(this),"update"))):d.dispose();else if(m.fallsWithinLayer(this,l.layer,!1)){var h=d,p=a,q=b,r=c,t=0===q?A.Pool.acquire():B.Pool.acquire();t.init(this,p,q,r);h.loadingAgent=t;h=d.loadingAgent.startLoading();n.TILE_LOADING_DEBUGLOG&&console.log(m.tile2str(this),
"start");h?d.loadingAgent===g.TILE_AGENT_DONE&&(n.TILE_LOADING_DEBUGLOG&&console.log(m.tile2str(this),"done"),this.setPendingUpdate(16)):(v(d.loadingAgent),d.loadingAgent=g.TILE_AGENT_DONE,n.TILE_LOADING_DEBUGLOG&&console.log(m.tile2str(this),"done"))}d.loadingAgent===g.TILE_AGENT_DONE&&this.updateRenderData(b);if(h&&l.isOpaque)break}};b.prototype.isWithinExtent=function(a){var b=this.extent;return b[0]>=a[0]&&a[2]>=b[2]&&b[1]>=a[1]&&a[3]>=b[3]};b.prototype.intersectsExtent=function(a){var b=this.extent;
return b[2]>=a[0]&&a[2]>=b[0]&&b[3]>=a[1]&&a[3]>=b[1]};Object.defineProperty(b.prototype,"test",{get:function(){return{cachedMemory:this.cachedMemory}},enumerable:!0,configurable:!0});return b}();x.Tile=u;var Q=new G.ElevationBounds,t=-1});