// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/declareExtendsHelper ../../../../core/tsSupport/decorateHelper ../../../../core/Accessor ../../../../core/Collection ../../../../core/Handles ../../../../core/Logger ../../../../core/PooledArray ../../../../core/watchUtils ../../../../core/accessorSupport/decorators ../../../../geometry/support/aaBoundingRect ./FeatureTileDescriptor3D ./FeatureTileMeasurements3D ../../support/projectionUtils ../../../support/index".split(" "),function(e,h,m,d,n,p,
q,r,t,u,c,f,v,w,x,g){Object.defineProperty(h,"__esModule",{value:!0});var y=r.getLogger("esri.views.3d.layers.support.FeatureTileFetcher3D");e=function(e){function b(a){a=e.call(this,a)||this;a.tiles=new p;a.tileSize=512;a.idToTile=new Map;a.handles=new q;a.clients=new Set;a._dirty=!1;a._newTiles=new t;return a}m(b,e);Object.defineProperty(b.prototype,"tilingScheme",{get:function(){var a=this.tilingSchemeOwner.tilingScheme;return a?a.clone():null},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,
"filterExtent",{set:function(a){if(a&&!a.spatialReference.equals(this.viewState.spatialReference))y.error("#extent","extent spatial reference needs to be in the same spatial reference as the view");else{var b=this._get("filterExtent");b===a||b&&a&&b.equals(a)||(a=a?a.clone():null,this._set("filterExtent",a),this._setDirty())}},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"filterExtentRect",{get:function(){if(!this.filterExtent||!this.tilingScheme)return null;var a=f.create();
x.extentToBoundingRect(this.filterExtent,a,this.tilingScheme.spatialReference);return a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"rootTileIds",{get:function(){return this.filterExtentRect?this.tilingScheme.rootTilesInExtent(this.filterExtentRect):[[0,0,0]]},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"suspended",{set:function(a){a!==this._get("suspended")&&(this._set("suspended",a),this._setDirty())},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,
"updating",{get:function(){return this._dirty||!!this._pendingTiles},enumerable:!0,configurable:!0});b.prototype.initialize=function(){var a=this;this.handles.add(this.watch(["tilingScheme","tileSize"],function(){return a._reset()},!0));this.handles.add(u.init(this,["tileSize","cameraOnSurface.location","tilingScheme","viewState.camera","focus.locationOnSurface"],function(){return a._setDirty()}));this.scheduler&&(this._frameWorker=this.scheduler.registerTask(g.Task.FEATURE_TILE_TREE,function(b){return a._update(b)},
function(){return a.updating}))};b.prototype.destroy=function(){this._frameWorker&&(this._frameWorker.remove(),this._frameWorker=null);this.handles&&(this.handles.destroy(),this.handles=null)};b.prototype.addClient=function(){var a=this,b=z++;this.clients.add(b);1===this.clients.size&&this._setDirty();return{remove:function(){return a._removeClient(b)}}};b.prototype._removeClient=function(a){this.clients.delete(a);this._hasClients||this._clear()};Object.defineProperty(b.prototype,"_hasClients",{get:function(){return 0<
this.clients.size},enumerable:!0,configurable:!0});b.prototype._setDirty=function(){!this._hasClients||this.suspended||this._dirty||(this._frameWorker?(this._dirty=!0,this.notifyChange("updating")):this._update(g.noBudget))};b.prototype._clear=function(){this.tiles.removeAll();this.idToTile.clear();this._reset();this._dirty=!1;this.notifyChange("updating")};b.prototype._update=function(a){this._dirty=!1;this._pendingTiles||(this._startUpdate(),this._frameWorker&&(this._frameWorker.task=g.Task.FEATURE_TILE_TREE_ACTIVE));
this._subdivideTilesForView(a);!this._pendingTiles&&this._frameWorker&&(this._frameWorker.task=g.Task.FEATURE_TILE_TREE);this.notifyChange("updating")};b.prototype._startUpdate=function(){if(!this.suspended)if(this.tilingScheme){this._tileMeasurements||(this._tileMeasurements=new w.FeatureTileMeasurements3D({renderCoordsHelper:this.renderCoordsHelper,tilingScheme:this.tilingScheme,tileSize:this.tileSize,maxVerticalScreenSize:l}));var a=this.cameraOnSurface.location;this._tileMeasurements.begin(this.viewState.camera,
this.focus?this.focus.locationOnSurface:a,a.z);this._pendingTiles=this._getRootTiles()}else this._clear()};b.prototype._reset=function(){this._newTiles.clear();this._pendingTiles=this._tileMeasurements=null;this._setDirty()};b.prototype._getRootTiles=function(){var a=this;return this.rootTileIds.map(function(b){return new v.FeatureTileDescriptor3D(b[0],b[1],b[2],a.tilingScheme)})};b.prototype._purgeHorizonTiles=function(a){a.sort(function(a,b){a=a.measures.screen.rect;b=b.measures.screen.rect;return a[1]+
a[3]-(b[1]+b[3])});f.empty(k);for(var b=0;b<a.length;b++)if(f.expand(k,a.data[b].measures.screen.rect),f.height(k)>l)return a.data.slice(b,a.length);return[]};b.prototype._subdivideTilesForView=function(a){var b;if(this._pendingTiles){for(;0<this._pendingTiles.length&&!a.done;){var c=this._pendingTiles.pop();a.madeProgress();if(!this.filterExtentRect||f.intersects(this.filterExtentRect,c.extent))this._tileMeasurements.updateTile(c),0!==c.measures.visibility&&(c.measures.shouldSplit?(this.tilingScheme.ensureMaxLod(c.lij[0]+
1),(b=this._pendingTiles).push.apply(b,c.getChildren())):this._newTiles.push(c))}0===this._pendingTiles.length&&(this._updateTiles(this._purgeHorizonTiles(this._newTiles)),this._newTiles.clear(),this._tileMeasurements.end(),this._pendingTiles=null)}};b.prototype._updateTiles=function(a){for(var b=this,c=0,d=this.tiles.items;c<d.length;c++)d[c].used=!1;a=a.filter(function(a){var c=b.idToTile.get(a.id);c?(c.copyMeasurementsFrom(a),c.used=!0):b.idToTile.set(a.id,a);return!c});c=this.tiles.items.filter(function(a){return a.used?
!1:(b.idToTile.delete(a.id),!0)});this.tiles.removeMany(c);this.tiles.addMany(a);this.sortTiles()};b.prototype.sortTiles=function(){this.tiles.sort(function(a,b){return a.measures.visibility!==b.measures.visibility?2===a.measures.visibility?-1:1:a.measures.distance-b.measures.distance});this.tiles.forEach(function(a,b){return a.loadPriority=b})};d([c.property({constructOnly:!0})],b.prototype,"scheduler",void 0);d([c.property({constructOnly:!0})],b.prototype,"renderCoordsHelper",void 0);d([c.property({constructOnly:!0})],
b.prototype,"tilingSchemeOwner",void 0);d([c.property({constructOnly:!0})],b.prototype,"cameraOnSurface",void 0);d([c.property({constructOnly:!0})],b.prototype,"focus",void 0);d([c.property({constructOnly:!0})],b.prototype,"viewState",void 0);d([c.property()],b.prototype,"tiles",void 0);d([c.property()],b.prototype,"tileSize",void 0);d([c.property({readOnly:!0,dependsOn:["tilingSchemeOwner.tilingScheme"]})],b.prototype,"tilingScheme",null);d([c.property()],b.prototype,"filterExtent",null);d([c.property({readOnly:!0,
dependsOn:["filterExtent","tilingScheme"]})],b.prototype,"filterExtentRect",null);d([c.property({readOnly:!0,dependsOn:["filterExtentRect"]})],b.prototype,"rootTileIds",null);d([c.property({value:!1})],b.prototype,"suspended",null);d([c.property({readOnly:!0})],b.prototype,"updating",null);return b=d([c.subclass("esri.views.3d.layers.support.FeatureTileTree3D")],b)}(c.declared(n));h.FeatureTileTree3D=e;var z=0,k=f.create(),l=10;h.default=e});