// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/declareExtendsHelper ../../../../core/tsSupport/decorateHelper ../../../../core/tsSupport/assignHelper ../../../../core/tsSupport/awaiterHelper ../../../../core/tsSupport/generatorHelper ../../../../core/Accessor ../../../../core/Handles ../../../../core/Logger ../../../../core/maybe ../../../../core/now ../../../../core/promiseUtils ../../../../core/scheduling ../../../../core/watchUtils ../../../../core/accessorSupport/decorators ../../../../geometry/support/aaBoundingRect ../../../../layers/graphics/dehydratedFeatures ../../../../tasks/support/QuantizationParameters ../../../../tasks/support/Query ./featureReference ./FeatureTile ../../terrain/tileUtils ../../../support/index ../../../support/QueueProcessor".split(" "),
function(y,w,J,k,Z,t,u,K,L,M,m,C,q,N,O,e,x,p,P,D,E,Q,R,F,S){function z(e){return"dummy-tile-full-extent"===e.id}function T(e){for(var b=0,a=0;a<e.length;a++){var c=e[a];c.features&&0<c.features.length&&c.alive&&(b=Math.max(b,c.descriptor.lij[0]))}return b}Object.defineProperty(w,"__esModule",{value:!0});var U=E.SingleFeatureReference,V=E.MultiFeatureReference,G=M.getLogger("esri.views.3d.layers.support.FeatureTileFetcher3D");y=function(n){function b(a){a=n.call(this,a)||this;a.useTileCount=!1;a.updating=
!1;a.updatingTotal=0;a.updatingRemaining=0;a.expectedFeatureDiff=0;a.maximumNumberOfFeaturesExceeded=!1;a.maximumNumberOfFeaturesExceededThrottle=1E3;a.maximumNumberOfFeaturesExceededNext=0;a._fullRatio=1;a._farRatio=1;a.changes={updates:{adds:[],removes:[]},adds:[],removes:[]};a.handles=new L;a._dirty=!1;a.idToFeatureTile=new Map;a.displayingFeatureReferences=new Map;a.numDisplayingFeatureReferences=0;a.suspended=!0;a.pendingEdits=null;return a}J(b,n);Object.defineProperty(b.prototype,"maximumNumberOfFeatures",
{set:function(a){a=a||Infinity;var c=this._get("maximumNumberOfFeatures");a===c||1>a||(this._set("maximumNumberOfFeatures",a),this.maximumFeaturesUpdated(c,a))},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"memoryFactor",{set:function(a){this.memoryFactor!==a&&(this._set("memoryFactor",a),this.setDirty())},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"lodFactor",{set:function(a){this.lodFactor!==a&&(this._set("lodFactor",a),this.supportsResolution&&this.refetch())},
enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"memoryForUnusedFeatures",{get:function(){var a=0;this.forEachFeatureTile(function(c){return a+=c.estimatedUnusedSize});return a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"totalVertices",{get:function(){var a=0;this.forEachFeatureTile(function(c){return a+=c.numVertices});return a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"totalFeatures",{get:function(){var a=0;this.forEachFeatureTile(function(c){return a+=
c.numFeatures});return a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"filterExtent",{set:function(a){if(a&&this.context.tilingScheme&&!a.spatialReference.equals(this.context.tilingScheme.spatialReference))G.error("#filterExtent\x3d","extent needs to be in the same spatial reference as the tiling scheme");else{var c=this._get("filterExtent");c===a||c&&a&&c.equals(a)||(a=a?a.clone():null,this._set("filterExtent",a),this.reclip(a,c))}},enumerable:!0,configurable:!0});b.prototype.initialize=
function(){var a=this;this.fetchQueue=this.createFetchQueue();this.handles.add(O.on(this,"tileDescriptors","change",function(){return a.setDirty()},function(){return a.setDirty()}));this.objectIdField=this.context.objectIdField;this.FeatureReferenceClass=this.context.capabilities.supportsMultipleResolutions?V:U;var c=this.context.scheduler;m.isSome(c)&&this.handles.add(c.registerTask(F.Task.FEATURE_TILE_FETCHER,function(c){return a.update(c)},function(){return a._dirty||0<a.maximumNumberOfFeaturesExceededNext}));
this.setDirty()};b.prototype.destroy=function(){var a=this;this.handles&&(this.handles.destroy(),this.handles=null);this.forEachFeatureTile(function(c){a.cancelFetchTile(c);a.removeTile(c)});this.idToFeatureTile.clear();this.displayingFeatureReferences.clear();this.fetchQueue.destroy();this.fetchQueue=null;this.pendingEdits&&(this.pendingEdits.controller.abort(),this.pendingEdits=null)};Object.defineProperty(b.prototype,"paused",{get:function(){return this.suspended||!!this.pendingEdits},enumerable:!0,
configurable:!0});b.prototype.restart=function(){var a=this;this.fetchQueue.clear();this.forEachFeatureTile(function(c){a.clearTile(c);a.resetFetchTile(c)});m.isSome(this.context.memoryCache)&&this.context.memoryCache.clear();this.setDirty()};b.prototype.refetch=function(){var a=this;this.fetchQueue.clear();this.forEachFeatureTile(function(c){a.cancelFetchTile(c);a.resetFetchTile(c)});m.isSome(this.context.memoryCache)&&this.context.memoryCache.clear();this.setDirty()};b.prototype.suspend=function(){this.suspended||
(this.suspended=!0,this.pause(),this.setDirty())};b.prototype.resume=function(){this.suspended&&(this.suspended=!1,this.unpause())};b.prototype.pause=function(){this.paused&&(this.fetchQueue.pause(),this.fetchQueue.reset(),this.updated())};b.prototype.unpause=function(){this.paused||(this.setDirty(),this.fetchQueue.resume(),this.updated())};b.prototype.getFeatureTileById=function(a){return this.idToFeatureTile.get(a)||null};b.prototype.forEachFeatureTile=function(a){this.idToFeatureTile.forEach(a)};
b.prototype.applyEdits=function(a){var c=this;this.pendingEdits||(this.pendingEdits={edits:q.resolve(),count:0,controller:q.createAbortController()},this.pause());this.pendingEdits.count++;var b=this.pendingEdits.edits.then(function(){return a.result.catch(function(a){if(q.isAbortError(a))throw a;return null}).then(function(a){return a?(c.applyEditsDeleteFeatures(a.deletedFeatures),c.applyEditsAddUpdateFeatures(a.addedFeatures,a.updatedFeatures,c.pendingEdits.controller.signal).then(function(){return a})):
a}).then(function(a){0===--c.pendingEdits.count&&(c.pendingEdits=null,m.isSome(c.context.memoryCache)&&c.context.memoryCache.clear(),c.unpause(),c.updated());return a})});this.pendingEdits.edits=b;this.updated();return b};b.prototype.applyEditsDeleteFeatures=function(a){var c=this;if(0!==a.length){var b=new Set;a.forEach(function(a){return b.add(a.objectId)});this.forEachFeatureTile(function(a){if(a.features){var f=a.features.filter(function(a){return!b.has(p.getObjectId(a,c.objectIdField))});f.length!==
a.features.length&&(a.setFeatures(f,0),c.invalidateCounts())}})}};b.prototype.applyEditsAddUpdateFeatures=function(a,c,b){return t(this,void 0,void 0,function(){var f,l,g,h=this;return u(this,function(d){switch(d.label){case 0:f=[];l=new Set;a.forEach(function(a){return f.push(a.objectId)});c.forEach(function(a){f.push(a.objectId);l.add(a.objectId)});if(0===f.length)return[2];g=[];this.forEachFeatureTile(function(a){(a=h.applyEditsAddUpdateTile(a,f,l,b))&&g.push(a)});return[4,q.eachAlways(g)];case 1:return d.sent(),
[2]}})})};b.prototype.applyEditsAddUpdateTile=function(a,c,b,d){return t(this,void 0,void 0,function(){var f,g,h,A,e,B,k,n=this;return u(this,function(l){switch(l.label){case 0:if(!a.features)return[2];f=this.createQuery(a);f.resultType=void 0;f.cacheHint=!1;f.objectIds=c;return[4,this.queryFeatures(f,d)];case 1:g=l.sent();h=null;0<b.size&&(A=a.features.filter(function(a){return!b.has(p.getObjectId(a,n.objectIdField))}),A.length!==a.features.length&&(h=A));if(0<g.features.length)for(h||(h=a.features.slice()),
this.context.adjustVerticalScale(g.features),e=0,B=g.features;e<B.length;e++)k=B[e],h.push(k);h&&(a.setFeatures(h,0),this.invalidateCounts());return[2]}})})};b.prototype.queryFeatures=function(a,c){return this.context.query.queryFeaturesDehydrated(a,{signal:c,timeout:W})};b.prototype.createFetchQueue=function(){var a=this;return new S.QueueProcessor({concurrency:6,task:F.Task.FEATURE_TILE_FETCHER,scheduler:this.context.scheduler,peeker:function(c){return a.highestPriorityTile(c)},process:function(c,
b){return a.fetchTile(c,b)}})};b.prototype.highestPriorityTile=function(a){return a.reduce(function(a,b){return a&&a.descriptor.loadPriority<=b.descriptor.loadPriority?a:b},null)};b.prototype.setDirty=function(){this._dirty=!0;this.updated()};b.prototype.update=function(a){var c=this;this.maximumNumberOfFeaturesExceededNext&&C()>=this.maximumNumberOfFeaturesExceededNext&&this.updateMaximumNumberOfFeaturesExceeded();if(this._dirty&&this.constructed){this._dirty=!1;var b=this.getListOfTiles();this.markTilesNotAlive(b);
if(a.run(function(){return c.addTiles(b,a)})&&a.run(function(){return c.filterExtentTiles(b,a)})&&a.run(function(){return c.removeTiles(b,a)})&&!a.done){var d=this.sortTiles(b);a.run(function(){return c.displayTiles(d,a)})&&a.run(function(){return c.queueFetchTiles(d,a)})&&a.run(function(){return c.updateMemoryEstimates(d,a)})||this.setDirty();this.updated()}else this.setDirty()}};b.prototype.markTilesNotAlive=function(a){for(var c=0;c<a.length;c++)a[c].alive=!1};b.prototype.addTiles=function(a,c){var b=
this;if(this.suspended)return!1;this.tileDescriptors.forEach(function(f){var d=b.getFeatureTileById(f.id);d?d.alive=!0:c.done||(a.push(b.addTile(f)),c.madeProgress())});return c.hasProgressed};b.prototype.filterExtentTiles=function(a,c){for(var b=0;b<a.length;b++){var d=a[b];if(c.done)break;d.alive&&(d.filtered=!d.intersects(this.filterExtent),d.filtered&&(this.clearTile(d),c.madeProgress()))}return c.hasProgressed};b.prototype.removeTiles=function(a,c){for(var b=a.length-1;0<=b&&!c.done;b--){var d=
a[b];d.alive||(this.removeTile(d),b!==a.length-1&&(a[b]=a[a.length-1]),a.pop(),c.madeProgress())}return c.hasProgressed};b.prototype.sortTiles=function(a){a.sort(function(a,b){return a.descriptor.loadPriority-b.descriptor.loadPriority});return a};b.prototype.displayTiles=function(a,c){for(var b=this,d=this.updateRatio(a),l=function(a){if(!c.run(function(){var c=1>b._fullRatio?d(a)*b._farRatio:1;a.reduceFeatures(c,b.memoryFactor,b.objectIdField)&&b.setDirty();return b.showTile(a)}))return g.setDirty(),
"break"},g=this,h=0;h<a.length&&"break"!==l(a[h]);h++);return c.hasProgressed};b.prototype.queueFetchTiles=function(a,c){for(var b=this,d=function(a){if(!c.run(function(){return b.queueFetchTile(a)}))return l.setDirty(),{value:!0}},l=this,g=0;g<a.length;g++){var h=d(a[g]);if("object"===typeof h)return h.value}return c.hasProgressed};b.prototype.updateMemoryEstimates=function(a,c){var b=this;a.some(function(a){return c.run(function(){return a.updateMemoryEstimates()})?!1:(b.setDirty(),!0)});return c.hasProgressed};
b.prototype.reclip=function(a,c){var b=this;this.constructed&&(this.forEachFeatureTile(function(d){d.displayingFeatures&&0!==d.displayingFeatures.length&&(d.intersection(c,H),d.intersection(a,I),x.equals(H,I)||b.hideTileFeatures(d))}),this.forEachFeatureTile(function(a){return b.showTile(a)}),this.updated())};b.prototype.updated=function(){var a=this,c=this._dirty||0<this.fetchQueue.length&&!this.paused||!!this.pendingEdits;this._set("updating",c);if(c){var b=c=0,d=0,l=0,g=0,h=0,e=this.displayingFeatureReferences.size/
this.numDisplayingFeatureReferences;this.forEachFeatureTile(function(c){++d;if(c.isFetching&&c.hasPreciseFeatureCount){var f=a.maximumFeaturesForTile(c)*(1-c.emptyFeatureRatio);h+=f-(c.displayingFeatures?c.displayingFeatures.length*e:0)}c.needsFetching?++g:0<c.numFeatures&&(++l,b+=c.numFeatures)});var g=g+(this.fetchQueue?this.fetchQueue.length:0),k=0;b?(c=b,k=Math.min(g*b/l,b)):(c=d,k=g);h=Math.min(this.maximumNumberOfFeatures-this.features.length,h);this._set("updatingTotal",c);this._set("updatingRemaining",
k);this._set("expectedFeatureDiff",h)}else this._set("updatingTotal",0),this._set("updatingRemaining",0),this._set("expectedFeatureDiff",0);this.debugger&&this.debugger.update();this.updating||(this.maximumNumberOfFeaturesExceededNext=this.maximumNumberOfFeaturesExceededNext||C()+this.maximumNumberOfFeaturesExceededThrottle)};b.prototype.updateMaximumNumberOfFeaturesExceeded=function(){if(!this.updating){var a=!1;this.forEachFeatureTile(function(c){a=a||c.perTileMaximumNumberOfFeaturesExceeded});
this.maximumNumberOfFeaturesExceededNext=0;this._set("maximumNumberOfFeaturesExceeded",a)}};b.prototype.updateRatio=function(a){for(var c=T(a),b=function(a){return 1/(1<<Math.max(0,c-a.descriptor.lij[0]))},d=0,l=0,g=0;g<a.length;g++)var h=a[g],e=h.numFeatures,d=d+e,l=l+e*b(h);this._fullRatio=Math.min(1,this.maximumNumberOfFeatures/d);this._farRatio=this.maximumNumberOfFeatures/l;this.scheduleUpdated();return b};b.prototype.maximumFeaturesUpdated=function(a,c){var b=this;a!==c&&(c>a&&this.forEachFeatureTile(function(a){if(a.featuresMissing){var c=
b.maximumFeaturesForTile(a);a.features&&(a.features.length>=c||5===a.fetchStatus)||(b.cancelFetchTile(a),b.resetFetchTile(a))}}),this.setDirty())};b.prototype.addTile=function(a){a=new Q(a);this.idToFeatureTile.set(a.id,a);this.resetFetchTile(a);this.referenceDisplayingFeaturesFromRelatedTiles(a);return a};b.prototype.referenceDisplayingFeaturesFromRelatedTiles=function(a){var c=this,b=a.descriptor.resolution;this.forEachFeatureTile(function(d){if(d.displayingFeatures&&a!==d&&(!a.descriptor.lij||
!d.descriptor.lij||R.tilesAreRelated(a.descriptor.lij,d.descriptor.lij))){a.displayingFeatures=a.displayingFeatures||[];var f=0;for(d=d.displayingFeatures;f<d.length;f++){var g=d[f];a.displayingFeatures.push(g);g=c.displayingFeatureReferences.get(p.getObjectId(g,c.objectIdField));g.ref(g.feature,b);c.numDisplayingFeatureReferences++}}});a.featureLimit=a.displayingFeatures?a.displayingFeatures.length:0};b.prototype.removeTile=function(a){this.clearTile(a);this.idToFeatureTile.delete(a.id)};b.prototype.resetFetchTile=
function(a){a.filtered=!a.intersects(this.filterExtent);a.filtered?a.needsFetching&&(a.fetchStatus=4):a.fetchStatus=0};b.prototype.cancelFetchTile=function(a){a.fetchRequest&&(a.fetchRequest=null,a.fetchStatus=0,this.fetchQueue.abort(a))};b.prototype.fetchTile=function(a,c){return t(this,void 0,void 0,function(){var b,d,l,g,h,e,k,n,v,r,m,p;return u(this,function(f){switch(f.label){case 0:if(!this.needsNumFeatures(a))return[3,4];f.label=1;case 1:return f.trys.push([1,3,,4]),b=a,[4,this.fetchCount(a,
c)];case 2:return b.numFeatures=f.sent(),this.updateRatio(this.getListOfTiles()),[3,4];case 3:return d=f.sent(),q.isAbortError(d)?[2,void 0]:[3,4];case 4:l=this.maximumFeaturesForTile(a);g=this.getMaxRecordCount(a);h=Math.ceil(l/g);if(z(a)||!this.context.capabilities.supportsMaxRecordCountFactor||a.numFeatures<=l&&h>D.MAX_MAX_RECORD_COUNT_FACTOR)return[2,this.fetchPagedTile(a,c)];e=this.createQuery(a);e.maxRecordCountFactor=Math.ceil(l/g);a.isRefetching&&a.features&&0<a.features.length&&(k=Math.ceil(a.features.length/
(1-a.emptyFeatureRatio)/g),e.maxRecordCountFactor=Math.max(k+1,e.maxRecordCountFactor));return[4,this.queryFeatures(e,c)];case 5:return n=f.sent(),v=n.features,m=(r=n.exceededTransferLimit)?e.maxRecordCountFactor>=D.MAX_MAX_RECORD_COUNT_FACTOR?5:4:5,a.featuresMissing=v.length<a.numFeatures||r,p=this._removeEmptyFeatures(v),this.context.adjustVerticalScale(v),a.setFeatures(v,p),this.invalidateCounts(),[2,m]}})})};b.prototype.fetchCount=function(a,c){return t(this,void 0,void 0,function(){return u(this,
function(b){return[2,this.context.query.queryFeatureCount(this.createFeatureCountQuery(a),{signal:c})]})})};b.prototype.fetchPagedTile=function(a,c){return t(this,void 0,void 0,function(){var b,d,e,g,h,k,n,m,p,r,q;return u(this,function(f){switch(f.label){case 0:g=d=b=0,h=this.maximumFeaturesForTile(a)-g,k=this.getMaxRecordCount(a),f.label=1;case 1:return n=this.createQuery(a),m=this.setPagingParameters(n,b,h,k),[4,this.queryFeatures(n,c)];case 2:return p=f.sent(),r=p.features,q=p.exceededTransferLimit,
m&&(b+=n.num),g+=r.length,d+=this._removeEmptyFeatures(r),this.context.adjustVerticalScale(r),a.featuresMissing=b<a.numFeatures||q,e=e?e.concat(r):r,a.setFeatures(e,d),this.invalidateCounts(),this.setDirty(),h=this.maximumFeaturesForTile(a)-g,!m||!q||0>=h?[2,q?4:5]:[3,1];case 3:return[2]}})})};b.prototype.createFeatureCountQuery=function(a){a=this.createQuery(a);this.context.capabilities.supportsCacheHint&&(a.resultType=void 0,a.cacheHint=!0);return a};b.prototype.createQuery=function(a){var b=this.context.createQuery(),
f=a.descriptor.extent;f&&(b.geometry=x.toExtent(f,this.context.tilingScheme.spatialReference));this.setResolutionParams(b,a);this.useTileQuery(a)?b.resultType="tile":this.context.capabilities.supportsCacheHint&&(b.cacheHint=!0);return b};b.prototype.setPagingParameters=function(a,b,f,d){if(!this.context.capabilities.supportsPagination)return!1;a.start=b;0<f&&this.context.capabilities.supportsMaxRecordCountFactor?(a.maxRecordCountFactor=Math.ceil(f/d),a.num=Math.min(a.maxRecordCountFactor*d,f)):a.num=
Math.min(d);return!0};b.prototype.getEffectiveTileResolution=function(a){if(null==a.descriptor.resolution)return null;var b="global"===this.context.viewingMode?this.context.tilingScheme.resolutionAtLevel(3):Infinity;return Math.min(a.descriptor.resolution,b)/this.lodFactor};Object.defineProperty(b.prototype,"supportsResolution",{get:function(){return this.context.capabilities.supportsMultipleResolutions&&"point"!==this.context.geometryType},enumerable:!0,configurable:!0});b.prototype.setResolutionParams=
function(a,b){this.supportsResolution&&(b=this.getEffectiveTileResolution(b),null!=b&&(this.context.capabilities.supportsQuantization?a.quantizationParameters=new P.default({mode:"view",originPosition:"upper-left",tolerance:b,extent:this.context.fullExtent}):"polyline"===this.context.geometryType&&(a.maxAllowableOffset=b)))};b.prototype._removeEmptyFeatures=function(a){for(var b=a.length,f=0;f<a.length;)p.hasVertices(a[f].geometry)?++f:(a[f]=a[a.length-1],--a.length);return b-a.length};b.prototype.needsNumFeatures=
function(a){return this.useTileCount&&!a.hasPreciseFeatureCount&&!z(a)};b.prototype.getMaxRecordCount=function(a){var b=this.context,f=b.tileMaxRecordCount,b=b.maxRecordCount;return this.useTileQuery(a)&&m.isSome(f)&&0<f&&this.context.capabilities.supportsResultType?f:m.isSome(b)&&0<b?b:X};b.prototype.useTileQuery=function(a){return z(a)&&this.context.capabilities.supportsCacheHint?!1:this.context.capabilities.supportsResultType};b.prototype.queueFetchTile=function(a){var b=this;if(!a.needsFetching)return!1;
var f=m.isSome(this.context.memoryCache)&&this.context.memoryCache.pop(a.id);if(f)return a.loadCache(f),this.setDirty(),this.scheduleUpdated(),!0;a.fetchStatus=a.needsRefetching?3:2;var d=!1,e=!1,g=this.fetchQueue.push(a).then(function(b){a.fetchRequest=null;a.fetchStatus=b}).catch(function(c){a.fetchRequest===g&&(a.fetchRequest=null,a.fetchStatus=4);q.isAbortError(c)?d=!0:(a.setFeatures([],0),b.invalidateCounts(),a.featuresMissing=!1,b.context.logFetchError(G,c))}).then(function(){e=!0;d||b.setDirty();
b.scheduleUpdated()});e||(a.fetchRequest=g);return!0};b.prototype.scheduleUpdated=function(){var a=this;this.handles&&!this.handles.has("scheduleUpdated")&&this.handles.add(N.schedule(function(){a.handles.remove("scheduleUpdated");a.updated()}),"scheduleUpdated")};b.prototype.showTile=function(a){if(a.displayingFeatures&&!a.needsDisplayUpdate)return!1;var b=a.features;if(0===a.featureLimit||!b)return b=a.displayingFeatures&&0<a.displayingFeatures.length,this.hideTileFeatures(a),a.displayingFeatures=
[],b;var f=a.descriptor.resolution,d=this.changes.updates,e=this.changes.adds,g=Math.min(a.featureLimit,b.length);a.featureLimit=g;for(var h=0;h<g;++h){var k=b[h],n=p.getObjectId(k,this.objectIdField),m=this.displayingFeatureReferences.get(n);m?(k=m.ref(k,f),k.oldVersion!==k.newVersion&&(d.removes.push(k.oldVersion),d.adds.push(k.newVersion))):(this.displayingFeatureReferences.set(n,new this.FeatureReferenceClass(k,f)),e.push(k));this.numDisplayingFeatureReferences++}this.hideTileFeatures(a);this.applyChanges();
a.displayingFeatures=b.slice(0,g);return!0};b.prototype.hideTile=function(a){this.cancelFetchTile(a);this.hideTileFeatures(a)};b.prototype.hideTileFeatures=function(a){if(a.displayingFeatures){for(var b=this.changes.updates,f=this.changes.removes,d=0,e=a.displayingFeatures;d<e.length;d++){var g=p.getObjectId(e[d],this.objectIdField),h=this.displayingFeatureReferences.get(g);h&&((h=h.unref(a.descriptor.resolution),this.numDisplayingFeatureReferences--,h)?h.oldVersion!==h.newVersion&&(null==h.newVersion?
(this.displayingFeatureReferences.delete(g),f.push(h.oldVersion)):(b.adds.push(h.newVersion),b.removes.push(h.oldVersion))):console.error("Hiding unreferenced feature"))}this.applyChanges();a.displayingFeatures=null}};b.prototype.applyChanges=function(){var a=this.changes.updates;0<a.removes.length&&(this.features.removeMany(a.removes),a.removes.length=0);0<a.adds.length&&(this.features.addMany(a.adds),a.adds.length=0);for(var a=this.changes.adds,b=this.changes.removes,f=Math.min(a.length,b.length),
d=0;d<f;){var e=Math.min(d+Y,f);this.features.addMany(a.slice(d,e));this.features.removeMany(b.slice(d,e));d=e}a.length>f&&this.features.addMany(0===d?a:a.slice(d));b.length>f&&this.features.removeMany(0===d?b:b.slice(d));a.length=0;b.length=0};b.prototype.clearTile=function(a){this.hideTile(a);a.features&&m.isSome(this.context.memoryCache)&&this.context.memoryCache.put(a.id,a.cacheItem,16+a.estimatedSize);a.setFeatures(null,0);this.invalidateCounts()};b.prototype.invalidateCounts=function(){this.notifyChange("totalVertices");
this.notifyChange("totalFeatures");this.notifyChange("memoryForUnusedFeatures")};b.prototype.getListOfTiles=function(){var a=Array(this.idToFeatureTile.size),b=0;this.forEachFeatureTile(function(c){return a[b++]=c});return a};Object.defineProperty(b.prototype,"storedFeatures",{get:function(){return this.getListOfTiles().reduce(function(a,b){return a+(b.features?b.features.length:0)},0)},enumerable:!0,configurable:!0});b.prototype.maximumFeaturesForTile=function(a){return Math.min(Math.ceil((a.hasPreciseFeatureCount?
a.numFeatures:this.maximumNumberOfFeatures)*(1>this._fullRatio?this._farRatio:1)/(1-a.emptyFeatureRatio)),a.hasPreciseFeatureCount?a.numFeatures:Infinity)};Object.defineProperty(b.prototype,"test",{get:function(){var a=this;return{update:function(b){a.fetchQueue.test.update(b);a.update(b)}}},enumerable:!0,configurable:!0});k([e.property({constructOnly:!0})],b.prototype,"features",void 0);k([e.property()],b.prototype,"tileDescriptors",void 0);k([e.property({value:Infinity})],b.prototype,"maximumNumberOfFeatures",
null);k([e.property({value:1})],b.prototype,"memoryFactor",null);k([e.property({value:1})],b.prototype,"lodFactor",null);k([e.property()],b.prototype,"useTileCount",void 0);k([e.property({readOnly:!0})],b.prototype,"updating",void 0);k([e.property({readOnly:!0})],b.prototype,"updatingTotal",void 0);k([e.property({readOnly:!0})],b.prototype,"updatingRemaining",void 0);k([e.property({readOnly:!0})],b.prototype,"expectedFeatureDiff",void 0);k([e.property({readOnly:!0})],b.prototype,"memoryForUnusedFeatures",
null);k([e.property({readOnly:!0})],b.prototype,"maximumNumberOfFeaturesExceeded",void 0);k([e.property({constructOnly:!0})],b.prototype,"maximumNumberOfFeaturesExceededThrottle",void 0);k([e.property({readOnly:!0})],b.prototype,"totalVertices",null);k([e.property({readOnly:!0})],b.prototype,"totalFeatures",null);k([e.property()],b.prototype,"filterExtent",null);k([e.property({constructOnly:!0})],b.prototype,"context",void 0);return b=k([e.subclass("esri.views.3d.layers.support.FeatureTileFetcher3D")],
b)}(e.declared(K));w.FeatureTileFetcher3D=y;w.contextCapabilitiesFromLayer=function(e){var b=e.capabilities.query;a:switch(e.geometryType){case "polyline":e=!0;break a;case "polygon":e=e.capabilities&&e.capabilities.query&&e.capabilities.query.supportsQuantization;break a;default:e=!1}return{supportsMultipleResolutions:e,supportsPagination:!(!b||!b.supportsPagination),supportsResultType:!(!b||!b.supportsResultType),supportsCacheHint:!(!b||!b.supportsCacheHint),supportsQuantization:!(!b||!b.supportsQuantization),
supportsQuantizationEditMode:!(!b||!b.supportsQuantizationEditMode),supportsMaxRecordCountFactor:!(!b||!b.supportsMaxRecordCountFactor),supportsFormatPBF:!(!b||!b.supportsFormatPBF)}};var X=2E3,H=x.create(),I=x.create(),W=6E5,Y=200;w.default=y});