// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define(["require","exports","../../../../../../core/tsSupport/makeTemplateObjectHelper","../attributes/VertexTextureCoordinates.glsl","../../shaderModules/interfaces"],function(q,c,d,p,e){function f(c,a){var b=c.fragment,f=a.hasMetalnessAndRoughnessTexture||a.hasEmissionTexture||a.hasOcclusionTexture;a.usePBR&&f&&c.include(p.VertexTextureCoordinates,a);a.usePBR&&(b.uniforms.add("roughnessFactor","float"),b.uniforms.add("metalnessFactor","float"),b.uniforms.add("emissionFactor","vec3"),b.uniforms.add("reflectanceFactor",
"float"),b.code.add(e.glsl(g||(g=d(["\n    float reflectance;\n    float roughness;\n    float metalness;\n    vec3 emission;\n    float occlusion;\n    "],["\n    float reflectance;\n    float roughness;\n    float metalness;\n    vec3 emission;\n    float occlusion;\n    "])))),a.hasMetalnessAndRoughnessTexture&&(b.uniforms.add("texMetallicRoughness","sampler2D"),a.supportsTextureAtlas&&b.uniforms.add("texMetallicRoughnessSize","vec2"),b.code.add(e.glsl(h||(h=d(["\n    void applyMetallnessAndRoughness(TextureLookupParameter params) {\n      vec3 metallicRoughness \x3d textureLookup(texMetallicRoughness, params).rgb;\n\n      roughness *\x3d metallicRoughness.g;\n      metalness *\x3d metallicRoughness.b;\n    }\n    "],
["\n    void applyMetallnessAndRoughness(TextureLookupParameter params) {\n      vec3 metallicRoughness \x3d textureLookup(texMetallicRoughness, params).rgb;\n\n      roughness *\x3d metallicRoughness.g;\n      metalness *\x3d metallicRoughness.b;\n    }\n    "]))))),a.hasEmissionTexture&&(b.uniforms.add("texEmission","sampler2D"),a.supportsTextureAtlas&&b.uniforms.add("texEmissionSize","vec2"),b.code.add(e.glsl(k||(k=d(["\n    void applyEmission(TextureLookupParameter params) {\n      emission *\x3d textureLookup(texEmission, params).rgb;\n    }\n    "],
["\n    void applyEmission(TextureLookupParameter params) {\n      emission *\x3d textureLookup(texEmission, params).rgb;\n    }\n    "]))))));a.usePBR&&a.hasOcclusionTexture?(b.uniforms.add("texOcclusion","sampler2D"),a.supportsTextureAtlas&&b.uniforms.add("texOcclusionSize","vec2"),b.code.add(e.glsl(l||(l=d(["\n    void applyOcclusion(TextureLookupParameter params) {\n      occlusion *\x3d textureLookup(texOcclusion, params).r;\n    }\n\n    float getBakedOcclusion() {\n      return occlusion;\n    }\n    "],
["\n    void applyOcclusion(TextureLookupParameter params) {\n      occlusion *\x3d textureLookup(texOcclusion, params).r;\n    }\n\n    float getBakedOcclusion() {\n      return occlusion;\n    }\n    "]))))):b.code.add(e.glsl(m||(m=d(["\n    float getBakedOcclusion() { return 1.0; }\n    "],["\n    float getBakedOcclusion() { return 1.0; }\n    "]))));a.usePBR&&b.code.add(e.glsl(n||(n=d(["\n    void applyPBRFactors() {\n      reflectance \x3d reflectanceFactor;\n      roughness \x3d roughnessFactor;\n      metalness \x3d metalnessFactor;\n      emission \x3d emissionFactor;\n      occlusion \x3d 1.0;\n      ",
"\n      ","\n      ","\n      ","\n    }\n  "],["\n    void applyPBRFactors() {\n      reflectance \x3d reflectanceFactor;\n      roughness \x3d roughnessFactor;\n      metalness \x3d metalnessFactor;\n      emission \x3d emissionFactor;\n      occlusion \x3d 1.0;\n      ","\n      ","\n      ","\n      ","\n    }\n  "])),f?"vtc.uv \x3d vuv0;":"",a.hasMetalnessAndRoughnessTexture?a.supportsTextureAtlas?"vtc.size \x3d texMetallicRoughnessSize; applyMetallnessAndRoughness(vtc);":"applyMetallnessAndRoughness(vtc);":
"",a.hasEmissionTexture?a.supportsTextureAtlas?"vtc.size \x3d texEmissionSize; applyEmission(vtc);":"applyEmission(vtc);":"",a.hasOcclusionTexture?a.supportsTextureAtlas?"vtc.size \x3d texOcclusionSize; applyOcclusion(vtc);":"applyOcclusion(vtc);":""))}Object.defineProperty(c,"__esModule",{value:!0});c.PhysicallyBasedRenderingParameters=f;(function(c){c.bindUniforms=function(a,b){a.setUniform1f("metalnessFactor",b.metallicFactor);a.setUniform1f("roughnessFactor",b.roughnessFactor);a.setUniform3fv("emissionFactor",
b.emissiveFactor);a.setUniform1f("reflectanceFactor",b.reflectanceFactor)}})(f=c.PhysicallyBasedRenderingParameters||(c.PhysicallyBasedRenderingParameters={}));var g,h,k,l,m,n});