// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/generatorHelper ../../core/tsSupport/awaiterHelper ../../Basemap ../../Ground ../../WebScene ../../core/compilerUtils ../../core/accessorSupport/ensureType ../../core/accessorSupport/extensions/serializableProperty/type ../../layers/GroupLayer ../../layers/KMLLayer ../../layers/mixins/OperationalLayer ./utils".split(" "),function(ba,F,e,f,K,L,M,v,z,N,G,O,H,P){function x(a,b,c){return f(this,void 0,void 0,function(){var d;return e(this,function(g){switch(g.label){case 0:d=
b.typeName;switch(d){case "array":return[3,1];case "union":return[3,3];case "json":return[3,5];case "native":return[3,7];case "enum":return[3,9]}return[3,11];case 1:return[4,Q(a,b,c)];case 2:return g.sent(),[3,12];case 3:return[4,R(a,b,c)];case 4:return g.sent(),[3,12];case 5:return[4,I(a,b,c)];case 6:return g.sent(),[3,12];case 7:return[4,S(a,b,c)];case 8:return g.sent(),[3,12];case 9:return[4,T(a,b,c)];case 10:return g.sent(),[3,12];case 11:v.neverReached(b),g.label=12;case 12:return[2]}})})}function S(a,
b,c){return f(this,void 0,void 0,function(){return e(this,function(d){c.addProperty({name:a,type:t(b),default:b.default});return[2]})})}function U(a){a=a.slice();a.sort();return a}function T(a,b,c){return f(this,void 0,void 0,function(){var d;return e(this,function(g){d=b.values.slice();b.nullable&&d.push(null);c.currentClass&&c.currentClass.typeValue&&"type"===a?c.addProperty({name:a,type:"string",enum:'"'+c.currentClass.typeValue+'"'}):c.addProperty({name:a,type:t(b),enum:U(d).map(function(a){return"string"===
typeof a?'"'+a+'"':""+a}).join("|"),default:b.default});return[2]})})}function Q(a,b,c){return f(this,void 0,void 0,function(){return e(this,function(d){switch(d.label){case 0:return[4,x(a+"[]",b.elementType,c)];case 1:return d.sent(),[2]}})})}function R(a,b,c){return f(this,void 0,void 0,function(){var d,g,A,h,k,m;return e(this,function(n){switch(n.label){case 0:d=[],g=0,A=b.types,n.label=1;case 1:if(!(g<A.length))return[3,5];h=A[g];if("native"!==h.type.typeName&&b.key)return[3,2];d.push(h.type);
return[3,4];case 2:var l=h.type;n=h.value;if("json"===l.typeName){var e=(l=(l=l.type.__accessorMetadata__)&&l.properties&&l.properties&&l.properties.type)&&q(l),f=(e=e&&e.type)||l&&l.type;f&&Array.isArray(f)&&1===f.length&&"string"===typeof f[0]&&(n=e?f[0]:B(l,f[0]))}k=a+"\x3c"+n+"\x3e";return[4,x(k,h.type,c)];case 3:n.sent(),n.label=4;case 4:return g++,[3,1];case 5:return d.length&&(m=d.map(t),b.nullable&&m.push("null"),m.sort(),c.addProperty({type:m.join("|"),name:a,default:b.default})),[2]}})})}
function V(a,b,c){return f(this,void 0,void 0,function(){return e(this,function(d){return a.type===M&&"layers"===b?[2,r("web-scene/operational-layers")]:a.type===K&&"baseLayers"===b?[2,r("web-scene/basemap")]:a.type===L&&"layers"===b?[2,r("web-scene/ground")]:a.type===G&&"layers"===b?[2,r("web-scene/operational-layers",function(a){return a!==G})]:[2,W(c)]})})}function I(a,b,c){return f(this,void 0,void 0,function(){var d,g,f,h,k,m,n,l,p,t,q,r,u,y,w,v;return e(this,function(e){switch(e.label){case 0:d=
b.type.__accessorMetadata__;g=b.type.prototype.declaredClass.replace(/\./g,"/");f=d&&d.properties;if(!f)return a&&c.addProperty({name:a,type:"unknown"}),[2,null];h=g;k=null;if(m=a&&a.match(/<([^>]+)>$/))h+="--"+m[1],k=m[1];if((n=c.seen.get(h))&&a)return c.addProperty({name:a,type:n}),[2,n];l={type:b.type,name:g,id:h,properties:[]};a&&(c.addProperty({name:a,type:l}),l.typeValue=k);c.push(a,l);p=[];for(t in f)p.push(t);q=0;e.label=1;case 1:if(!(q<p.length))return[3,7];r=p[q];u=f[r];y=C(u);if(!y||!y.enabled)return[3,
6];w=y.target;return"string"!==typeof w&&null!=w?[3,4]:[4,V(b,r,u)];case 2:return(v=e.sent())?[4,x("string"===typeof w?w:r,v,c)]:[3,6];case 3:return e.sent(),[3,6];case 4:return[4,X(w,c)];case 5:e.sent(),e.label=6;case 6:return q++,[3,1];case 7:return[2,c.pop()]}})})}function X(a,b){return f(this,void 0,void 0,function(){var c,d,g,f,h,k;return e(this,function(e){switch(e.label){case 0:c=[];for(d in a)c.push(d);g=0;e.label=1;case 1:if(!(g<c.length))return[3,4];f=c[g];h=a[f];k=void 0;k=h.types?u(h.types):
p(h.type);k.default=h.default;k=D(k);return[4,x(f,k,b)];case 2:e.sent(),e.label=3;case 3:return g++,[3,1];case 4:return[2]}})})}function r(a,b){return f(this,void 0,void 0,function(){var c,d,g,f,h,k,m,n;return e(this,function(e){switch(e.label){case 0:c=H.supportedTypes[a];d={typeName:"union",key:"layerType",types:[]};g=[];for(f in c)g.push(f);h=0;e.label=1;case 1:if(!(h<g.length))return[3,4];k=g[h];return[4,H.typeModuleMap[k]()];case 2:m=e.sent();if(!m||b&&!b(m)||m===O)return[3,3];d.types.push({type:{typeName:"json",
type:m},value:k});e.label=3;case 3:return h++,[3,1];case 4:if(0===d.types.length)return[2,null];n={typeName:"array",elementType:1===d.types.length?d.types[0].type:d};return[2,n]}})})}function t(a){switch(a.typeName){case "array":return t(a.elementType)+"[]";case "union":var b=a.types.map(function(a){return t(a.type)});a.nullable&&b.push("null");b.sort();return""+b.join(" | ");case "native":switch(a.type){case Number:return"number";case z.Integer:return"integer";case String:return"string";case Boolean:return"boolean";
case Object:return"object";default:return"unknown"}case "json":return a.type.prototype.declaredClass;case "enum":return"string";default:v.neverReached(a)}}function Y(a){a=a.prototype.itemType&&a.prototype.itemType.Type;if(!a)return{typeName:"array",elementType:{typeName:"native",type:null}};if("function"===typeof a)return{typeName:"array",elementType:p(a)};if(a.typeMap){var b=[],c;for(c in a.typeMap){var d=a.typeMap[c];b.push({type:p(d),value:E(d)?null:c})}return{typeName:"array",elementType:{typeName:"union",
key:"string"===typeof a.key?a.key:"type",types:b}}}}function Z(a){if("json"!==a.typeName)return null;var b=(a=a.type.__accessorMetadata__)&&a.properties&&a.properties.type,c=(a=(a=b&&q(b))&&a.type)||b&&b.type;return c&&Array.isArray(c)&&"string"===typeof c[0]?a?a:b.type.map(function(a){return B(b,a)}):null}function D(a){if("array"===a.typeName)return a.elementType=D(a.elementType),a;var b=Z(a);return b?{typeName:"union",key:"type",types:b.map(function(b){return{value:b,type:a}})}:a}function W(a){var b=
q(a);if(b.types)return u(b.types);if(!b.type&&a.types)return u(a.types);var b=D,c=q(a),d=C(a),e=p(c&&c.type||a.type);c&&void 0!==c.default&&"function"!==typeof c.default&&(e.default=B(a,c.default));d.allowNull&&(e.nullable=!0);return b(e)}function u(a){if(Array.isArray(a))return{typeName:"array",elementType:u(a[0])};var b=[],c;for(c in a.typeMap){var d=a.typeMap[c];b.push({type:p(d),value:E(d)?null:c})}return{typeName:"union",key:"string"===typeof a.key?a.key:"type",types:b}}function B(a,b){a=C(a);
var c=a.writer;return null!=c&&c.name&&-1!==c.name.indexOf("JSONMapWrite")?(c={value:""},a.writer(b,c,"value"),c.value):b}function p(a){return a?z.isLongFormType(a)?J(a):Array.isArray(a)?"string"===typeof a[0]||"number"===typeof a[0]?{typeName:"enum",values:a}:1<a.length?{typeName:"union",key:null,types:a.map(function(a){return{type:p(a),value:null}})}:{typeName:"array",elementType:p(a[0])}:N.isCollection(a)?Y(a):E(a)?{typeName:"native",type:a}:aa(a)?{typeName:"json",type:a}:{typeName:"native",type:null}:
{typeName:"native",type:null}}function J(a){switch(a.type){case "native":return{typeName:"native",type:a.value};case "array":return{typeName:"array",elementType:p(a.value)};case "one-of":return{typeName:"union",key:null,types:a.values.map(function(a){return{type:J(a),value:null}})};default:v.neverReached(a)}}function aa(a){return(a=a._meta&&a._meta.bases)?a.some(function(a){return a&&a.prototype&&("esri.core.JSONSupport"===a.prototype.declaredClass||"esri.core.MultiOriginJSONSupport"===a.prototype.declaredClass)}):
!1}function E(a){return a===String||a===Boolean||a===Number||a===z.Integer||a===Object}function q(a){if(!a.json)return null;var b=a.json.origins;a=a.json;var c=b&&b["web-document"];return b&&b["web-scene"]||c||a||null}function C(a){if(!a.json)return null;var b=a.json.origins;a=a.json.write;var c=b&&b["web-document"]&&b["web-document"].write;return b&&b["web-scene"]&&b["web-scene"].write||c||a||null}Object.defineProperty(F,"__esModule",{value:!0});F.scan=function(a){return f(this,void 0,void 0,function(){var b;
return e(this,function(c){b=new P.ScanContext;return[2,I(null,{typeName:"json",type:a},b)]})})}});