// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/generatorHelper ../../core/tsSupport/awaiterHelper ../../core/tsSupport/extendsHelper ../../core/tsSupport/assignHelper ../../core/Error ../../core/promiseUtils ../schema ./utils".split(" "),function(E,v,g,n,F,y,z,q,t,u){function G(b,a){if(a.properties){if("layerType"in a.properties)return a.properties.layerType.enum[0];if("type"in a.properties)return a.properties.type.enum[0]}switch(b){case "multipoint_geometry_schema.json":return"multipoint";case "point_geometry_schema.json":return"point";
case "polyline_geometry_schema.json":return"polyline";case "polygon_geometry_schema.json":return"polygon";case "extent_schema.json":return"extent"}}function A(b){return"array"===b.type?A(b.items)+"[]":b.type}function H(b){var a={count:b.length,refsCount:0,typesCount:0,distinctTypes:[],type:null},c=new Set,d;for(d in b){var e=b[d];e.$ref?a.refsCount++:e.type&&(a.typesCount++,c.add(A(e)))}c.forEach(function(b){return a.distinctTypes.push(b)});a.distinctTypes.sort();a.refsCount===a.count?a.type="refs":
2===a.count&&0<a.refsCount&&1===a.distinctTypes.length&&"null"===a.distinctTypes[0]?a.type="refsAndNull":a.typesCount===a.count?(a.type="types",a.distinctTypes=a.distinctTypes):a.type="mix";return a}function w(b,a,c,d,e){return n(this,void 0,void 0,function(){var h,f,l,k,p;return g(this,function(m){switch(m.label){case 0:h=G(b,c);d=d?d.replace("\x3c?TYPE?\x3e",h?"\x3c"+h+"\x3e":""):null;if("array"!==c.type&&"properties"in c)return[3,2];(f=e.currentClass?null:{type:b,name:b,id:b+"--"+a,typeValue:a,
properties:[]})&&e.push(null,f);return[4,r(c,d,e)];case 1:return m.sent(),[2,f];case 2:e.hasFilteredProperties?(m=e.filteredPropertiesArray.join("/"),l=b+"--"+a+"--"+m):l=b+"--"+a;if((k="drawingInfo_schema.json"!==b&&e.seen.get(l))&&d)return e.addProperty({name:d,type:k}),[2,k];p={type:b,name:b,id:l,typeValue:a,properties:[]};d&&e.addProperty({name:d,type:p});e.push(d,p);return[4,r(c,"",e)];case 3:return m.sent(),[2,e.pop()]}})})}function B(b,a,c){return n(this,void 0,void 0,function(){var d,e,h,
f,l,k,p;return g(this,function(m){switch(m.label){case 0:return[4,c.requestSchema(b.$ref)];case 1:d=m.sent();var g=d.schema;e="layerDefinition"===g.title?null:(g=g.properties&&g.properties.type)&&g.enum?g.enum:null;if(!e)return[3,6];h=0;f=e;m.label=2;case 2:if(!(h<f.length))return[3,5];l=f[h];k=y({},d.schema);k.properties=y({},k.properties,{type:{type:"string",enum:[l]}});p=-1===a.indexOf("\x3c?TYPE?\x3e")?a+"\x3c?TYPE?\x3e":a;return[4,w(d.schemaId,l,k,p,c)];case 3:m.sent(),m.label=4;case 4:return h++,
[3,2];case 5:return[2,void 0];case 6:return[4,w(d.schemaId,null,d.schema,a,c)];case 7:return m.sent(),[2,void 0]}})})}function I(b,a){if(!x(b))return!1;b=b.stack.map(function(a){return a.klass.type}).join("/");return/.*pointCloudLayer_schema\.json\/layerDefinition_schema\.json\/drawingInfo_schema\.json$/.test(b)&&"renderer"===a}function J(b,a){if(!x(b))return!1;b=b.stack.map(function(a){return a.klass.type}).join("/");return/.*rasterDataLayer_schema\/.json\/layerDefinition_schema\.json\/drawingInfo_schema\.json$/.test(b)&&
"renderer"===a}function x(b){return b.currentClass&&"drawingInfo_schema.json"===b.currentClass.name}function K(b,a,c){if(x(c)){var d=I(c,a),e=J(c,a);return b.filter(function(a){if(/uniqueValueFromStyleRenderer_schema\.json$/.test(a.$ref))return!1;var b=/pointCloud.*Renderer/.test(a.$ref);a=/raster.*Renderer/.test(a.$ref);return d===b&&a===e})}return c.currentClass&&"operationalLayers_schema.json"===c.currentClass.name?b.filter(function(a){return"kmlLayer_schema.json"!==a.$ref}):b}function L(b,a,c){return n(this,
void 0,void 0,function(){return g(this,function(d){switch(d.label){case 0:return[4,r(b.items,a+"[]",c)];case 1:return d.sent(),[2]}})})}function M(b,a,c){return n(this,void 0,void 0,function(){var d=this;return g(this,function(e){switch(e.label){case 0:return[4,c.withFilteredProperties(null,function(e){return n(d,void 0,void 0,function(){var d,h,k,p,m;return g(this,function(f){switch(f.label){case 0:d=[];for(h in b.properties)d.push(h);k=0;f.label=1;case 1:if(!(k<d.length))return[3,4];p=d[k];if(e&&
!e.has(p))return[3,3];m=a?a+"."+p:p;return[4,r(b.properties[p],m,c)];case 2:f.sent(),f.label=3;case 3:return k++,[3,1];case 4:return[2]}})})})];case 1:return e.sent(),[2]}})})}function C(b,a,c){void 0===a&&(a="");void 0===c&&(c=new Set);for(var d=0;d<b.length;d++){var e=b[d];if("properties"in e)for(var h in e.properties){var f=e.properties[h],l=a?a+"."+h:h,k=Object.keys(f);if(0===k.length||1===k.length&&"$ref"===k[0])c.add(l);else if(1===k.length&&"allOf"===k[0])c.add(l),C(f.allOf,l,c);else throw Error("unexpected allOf filter construct: "+
JSON.stringify(f));}}return c}function N(b,a,c){return n(this,void 0,void 0,function(){var d,e,h,f,l;return g(this,function(k){switch(k.label){case 0:d=null;e=0;for(h=b.allOf;e<h.length;e++)if(f=h[e],"$ref"in f){if(d)throw Error("Cannot process more than 1 ref in an allOf construct");d=f}else if(!("properties"in f))throw Error("allOf construct only allows simple top-level property filters");l=C(b.allOf);return[4,c.withFilteredProperties(l,function(){return B(d,a,c)})];case 1:return k.sent(),[2]}})})}
function O(b,a,c){return n(this,void 0,void 0,function(){var d,e,h,f,l,k,p,m,n,q;return g(this,function(g){switch(g.label){case 0:d=H(b.oneOf);if("refs"!==d.type&&"refsAndNull"!==d.type)return[3,6];e=K(b.oneOf,a,c);h=0;f=e;g.label=1;case 1:if(!(h<f.length))return[3,5];l=f[h];return"null"!==l.type?[3,2]:[3,4];case 2:return[4,r(l,(a||"")+"\x3c?TYPE?\x3e",c)];case 3:g.sent(),g.label=4;case 4:return h++,[3,1];case 5:return[2];case 6:if("types"===d.type)return c.addProperty({name:a,type:u.sorted(d.distinctTypes).join("|")}),
[2];k=[];for(p in b.oneOf)k.push(p);m=0;g.label=7;case 7:if(!(m<k.length))return[3,10];n=k[m];q=".oneOf["+n+"]";return[4,r(b.oneOf[n],""+a+q,c)];case 8:g.sent(),g.label=9;case 9:return m++,[3,7];case 10:return[2]}})})}function P(b,a,c){return n(this,void 0,void 0,function(){return g(this,function(d){switch(d.label){case 0:return[4,B(b,a,c)];case 1:return d.sent(),[2]}})})}function Q(b,a,c){return n(this,void 0,void 0,function(){var d,e;return g(this,function(h){d="unknown";b.type&&(d=Array.isArray(b.type)?
u.sorted(b.type).join("|"):b.type.replace(/ /g,"").split(",").join("|"));e={name:a,type:d,default:b.default};b.enum&&(e.enum=u.sorted(b.enum).map(function(a){return"string"===typeof a?'"'+a+'"':""+a}).join("|"));c.addProperty(e);return[2]})})}function r(b,a,c){return n(this,void 0,void 0,function(){return g(this,function(d){return"array"===b.type?[2,L(b,a,c)]:"properties"in b?[2,M(b,a,c)]:"allOf"in b?[2,N(b,a,c)]:"oneOf"in b?[2,O(b,a,c)]:"$ref"in b?[2,P(b,a,c)]:[2,Q(b,a,c)]})})}function D(b){return 0===
b.indexOf("#/definitions/")?b.slice(14):b}Object.defineProperty(v,"__esModule",{value:!0});v.scan=function(b,a){return n(this,void 0,void 0,function(){var c;return g(this,function(d){switch(d.label){case 0:return[4,R.create(b,a)];case 1:return c=d.sent(),[2,w((b||"webScene")+"_schema.json",null,c.schemaRoot,null,c)]}})})};var R=function(b){function a(a,d,e){var c=b.call(this)||this;c.definitions=a;c.schemaRoot=d;c.requestSchema=e;c.filteredProperties=null;c.requestSchema.bind(c);return c}F(a,b);Object.defineProperty(a.prototype,
"hasFilteredProperties",{get:function(){return this.filteredProperties&&0<this.filteredProperties.size},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"filteredPropertiesArray",{get:function(){var a=[];this.filteredProperties.forEach(function(b){return a.push(b)});return a},enumerable:!0,configurable:!0});a.prototype.withFilteredProperties=function(a,b){return n(this,void 0,void 0,function(){var c,d,f,l=this;return g(this,function(e){switch(e.label){case 0:return c=this.filteredProperties,
this.filteredProperties=null,d=function(a){l.filteredProperties||(l.filteredProperties=new Set);l.filteredProperties.add(a)},c&&c.forEach(function(a){a=a.split(".");1<a.length&&(d(a[0]),d(a.slice(1).join(".")))}),a&&a.forEach(d),[4,b(c)];case 1:return f=e.sent(),this.filteredProperties=c,[2,f]}})})};a.create=function(b,d){return n(this,void 0,void 0,function(){return g(this,function(c){return d&&d.useRemoteSchema?[2,a.createRemote(b,d.baseUrl)]:[2,a.createLocal(b)]})})};a.createLocal=function(b){return new a(t.json.definitions,
b?t.json.definitions[b+"_schema.json"]:t.json,a.getLocalSchemaRequest())};a.createRemote=function(b,d){return n(this,void 0,void 0,function(){var c,h,f;return g(this,function(e){switch(e.label){case 0:return[4,a.getRemoteSchemaRequest(d)];case 1:return c=e.sent(),h=new a({},null,c),[4,h.requestSchema((b||"webscene")+"_schema.json")];case 2:return f=e.sent().schema,[2,new a(h.definitions,f,c)]}})})};a.getLocalSchemaRequest=function(){return function(a){a=D(a);var b=this.definitions[a];return b?q.resolve({schemaId:a,
schema:b}):q.reject(new z("flatspec-spec:invalid-local-schema","Schema reference is not a local reference"))}};a.getRemoteSchemaRequest=function(b){return n(this,void 0,void 0,function(){var d,c;return g(this,function(e){switch(e.label){case 0:if(!b)return[2,q.reject(new z("flatspec-spec:missing-base-url","The base url of the remote schema directory must be specified when using a remote schema"))];d=a.getLocalSchemaRequest();return[4,q.create(function(a){return E(["../../request"],a)})];case 1:return c=
e.sent(),[2,function(a){var e=this;return d.call(this,a).catch(function(){return c(b+"/"+a,{responseType:"json"}).then(function(b){e.definitions[D(a)]=b.data;return{schemaId:a,schema:b.data}})})}]}})})};return a}(u.ScanContext);v.schemaDefinitions=Object.keys(t.json.definitions).map(function(b){return b.replace(/_schema\.json$/,"")})});