// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define(["require","exports","../../../../../core/iteratorUtils","../../../../../core/Logger"],function(e,f,g,m){Object.defineProperty(f,"__esModule",{value:!0});var n=m.getLogger("esri.views.3d.webgl-engine.core.shaderModules.shaderBuilder");e=function(){function a(){this.vertex=new h;this.fragment=new h;this.attributes=new p;this.varyings=new q;this.extensions=new r;this.defines=new k;this._includedModules=new Map}a.prototype.include=function(b,c){this._includedModules.has(b)?this._includedModules.get(b)!==
c&&n.error("Trying to include shader module multiple times with different sets of options."):(this._includedModules.set(b,c),"shaderModule"in b?b.shaderModule(this,c):b(this,c))};a.prototype.generateSource=function(b){var c=this.extensions.generateSource(b),a=this.attributes.generateSource(b),t=this.varyings.generateSource(),d="vertex"===b?this.vertex:this.fragment,e=d.uniforms.generateSource(),f=d.code.generateSource();b="vertex"===b?u:v;d=this.defines.generateSource().concat(d.defines.generateSource());
return"\n"+c.join("\n")+"\n\n"+d.join("\n")+"\n\n"+b+"\n\n"+e.join("\n")+"\n\n"+a.join("\n")+"\n\n"+t.join("\n")+"\n\n"+f.join("\n")};return a}();f.ShaderBuilder=e;var w=function(){function a(){this._entries=[];this._set=new Set}a.prototype.add=function(b,a,l){var c=b+"_"+a+"_"+l;this._set.has(c)||(this._entries.push([b,a,l]),this._set.add(c));return this};a.prototype.generateSource=function(){return this._entries.map(function(b){var a=b[2];return"uniform "+b[1]+" "+b[0]+(a?"["+a+"]":"")+";"})};return a}(),
x=function(){function a(){this._entries=[]}a.prototype.add=function(b){this._entries.push(b)};a.prototype.generateSource=function(){return this._entries};return a}(),h=function(){return function(){this.uniforms=new w;this.code=new x;this.defines=new k}}(),p=function(){function a(){this._entries=[]}a.prototype.add=function(b,a){this._entries.push([b,a])};a.prototype.generateSource=function(a){return"fragment"===a?[]:this._entries.map(function(a){return"attribute "+a[1]+" "+a[0]+";"})};return a}(),
q=function(){function a(){this._entries=[]}a.prototype.add=function(a,c){this._entries.push([a,c])};a.prototype.generateSource=function(){return this._entries.map(function(a){return"varying "+a[1]+" "+a[0]+";"})};return a}(),r=function(){function a(){this._entries=new Set}a.prototype.add=function(a){this._entries.add(a)};a.prototype.generateSource=function(b){var c="vertex"===b?a.WHITELIST_VERTEX:a.WHITELIST_FRAGMENT;return g.valuesOfSet(this._entries).filter(function(a){return 0<=c.indexOf(a)}).map(function(a){return"#extension "+
a+" : enable"})};a.WHITELIST_FRAGMENT=["GL_EXT_shader_texture_lod","GL_OES_standard_derivatives"];a.WHITELIST_VERTEX=[];return a}(),k=function(){function a(){this._entries=new Map}a.prototype.addInt=function(a,c){c=0===c%1?c.toFixed(0):c.toString();this._entries.set(a,c)};a.prototype.addFloat=function(a,c){c=0===c%1?c.toFixed(1):c.toString();this._entries.set(a,c)};a.prototype.generateSource=function(){return g.pairsOfMap(this._entries).map(function(a){return"#define "+a[0]+" "+a[1]})};return a}(),
v="#ifdef GL_FRAGMENT_PRECISION_HIGH\n  precision highp float;\n  precision highp sampler2D;\n#else\n  precision mediump float;\n  precision mediump sampler2D;\n#endif",u="precision highp float;\nprecision highp sampler2D;"});