// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/libs/gl-matrix-2/mat4 ../../../../core/libs/gl-matrix-2/mat4f64 ../../../../core/libs/gl-matrix-2/vec3 ../../../../core/libs/gl-matrix-2/vec3f64 ../../../../geometry/Point ./Graphics3DSymbolCommonCode ./graphicUtils ../../support/debugFlags ../../support/projectionUtils ../../webgl-engine/lib/Util".split(" "),function(N,n,H,u,v,l,I,A,J,B,F,K){Object.defineProperty(n,"__esModule",{value:!0});var L=K.VertexAttrConstants,w=new I,g=l.vec3f64.create(),d=l.vec3f64.create(),
t=l.vec3f64.create(),c=u.mat4f64.create(),G=l.vec3f64.create(),p={verticalDistanceToGround:0,terrainElevation:0};n.perVertexElevationAligner=function(e,a,h,b){e=e.stageObject;w.spatialReference=h.spatialReference;for(var C=e.geometryRecords,c=C.length,q="absolute-height"!==a.mode,r=0,x=0;x<c;x++){var f=C[x].geometry,m=C[x].getShaderTransformation();d[0]=m[12];d[1]=m[13];d[2]=m[14];f.invalidateBoundingInfo();for(var m=f.data.getVertexAttr(),y=m[L.POSITION],f=y.data,m=m.mapPos.data,y=y.size,l=f.length/
y,k=0,D=0,E=!1,u=0,v=0;v<l;v++){w.x=m[D++];w.y=m[D++];w.z=m[D++];t[0]=f[k];t[1]=f[k+1];t[2]=f[k+2];var z=A.computeElevation(h,w,a,b,q?p:null);q&&(u+=p.terrainElevation);g[0]=f[k]+d[0];g[1]=f[k+1]+d[1];g[2]=f[k+2]+d[2];b.setAltitude(z,g);f[k]=g[0]-d[0];f[k+1]=g[1]-d[1];f[k+2]=g[2]-d[2];if(B.TESTS_DISABLE_UPDATE_THRESHOLDS)E=!0;else if(z=n.updateThresholdInMeters/b.unitInMeters,Math.abs(t[0]-f[k])>=z||Math.abs(t[1]-f[k+1])>=z||Math.abs(t[2]-f[k+2])>=z)E=!0;k+=y}r+=u/l;E&&e.geometryVertexAttrsUpdated(x)}return r/
c};n.perObjectElevationAligner=function(e,a,h,b){e=e.stageObject;var c=a.centerPointInElevationSR,d=0,q=0;if(e.metadata.usesVerticalDistanceToGround)d=A.computeElevation(h,c,a,b,p),J.updateVertexAttributeAuxpos1w(e,p.verticalDistanceToGround),q=p.terrainElevation;else{var r="absolute-height"!==a.mode,d=A.computeElevation(h,c,a,b,r?p:null);r&&(q=p.terrainElevation)}a=H.mat4.copy(M,e.objectTransformation);h=v.vec3.set(G,a[12],a[13],a[14]);B.DISABLE_ELEVATION_ALIGNERS_ITERATIVE_UPDATES?(g[0]=c.x,g[1]=
c.y,g[2]=d,F.computeLinearTransformation(c.spatialReference,g,a,b.spatialReference)&&(e.objectTransformation=a)):b.setAltitudeOfTransformation(d,a);b=n.updateThresholdInMeters/b.unitInMeters;if(Math.abs(a[12]-h[0])>=b||Math.abs(a[13]-h[1])>=b||Math.abs(a[14]-h[2])>=b)e.objectTransformation=a;return q};var M=u.mat4f64.create();n.perLodInstanceElevationAligner=function(e,a,h,b){var d=a.centerPointInElevationSR,l=0,q=0,r="absolute-height"!==a.mode,l=A.computeElevation(h,d,a,b,r?p:null);r&&(q=p.terrainElevation);
a=e.graphics3DSymbolLayer.lodRenderer.instanceData;e=e.instanceIndex;a.getGlobalTransform(e,c);h=v.vec3.set(G,c[12],c[13],c[14]);B.DISABLE_ELEVATION_ALIGNERS_ITERATIVE_UPDATES?(g[0]=d.x,g[1]=d.y,g[2]=l,F.computeLinearTransformation(d.spatialReference,g,c,b.spatialReference)&&a.setGlobalTransform(e,c)):b.setAltitudeOfTransformation(l,c);b=n.updateThresholdInMeters/b.unitInMeters;(Math.abs(c[12]-h[0])>=b||Math.abs(c[13]-h[1])>=b||Math.abs(c[14]-h[2])>=b)&&a.setGlobalTransform(e,c);return q};n.updateThresholdInMeters=
.01;n.iterativeUpdatesEnabled=!0});