// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/tsSupport/generatorHelper ../../../../core/tsSupport/awaiterHelper ../../../../Color ../../../../core/arrayUtils ../../../../core/compilerUtils ../../../../core/Logger ../../../../core/mathUtils ../../../../core/maybe ../../../../core/libs/gl-matrix-2/vec3f64 ../../../../core/libs/gl-matrix-2/vec4f64 ./ElevationContext ./featureExpressionInfoUtils ./Graphics3DSymbolCommonCode ./graphicUtils ./Loadable ./symbolComplexity".split(" "),
function(l,g,v,G,H,w,x,y,z,r,h,A,B,t,m,n,p,C,D){function k(d,b){d=null!=d?b.attributes[d]:0;return null!=d&&isFinite(d)?d:0}Object.defineProperty(g,"__esModule",{value:!0});var d=new t,q=z.getLogger("esri.views.3d.layers.graphics.Graphics3DSymbolLayer");l=function(g){function b(a,c,e,b){var f=g.call(this)||this;f._elevationInfoOverride=null;f.complexity=null;f.logger=q;f._elevationOptions={supportsOffsetAdjustment:!1,supportsOnTheGround:!0};f.symbol=a;f.symbolLayer=c;f._context=e;f._symbolLayerOrder=
e.layerOrder;f._symbolLayerOrderDelta=e.layerOrderDelta;f._elevationContext=new t;f._material=null;f.complexity=f.computeComplexity();f._updateDrivenProperties(b);f._updateElevationContext();return f}v(b,g);b.prototype.getCachedSize=function(){return null};Object.defineProperty(b.prototype,"needsDrivenTransparentPass",{get:function(){return this._drivenProperties.opacity&&!this._drivenProperties.opacityAlwaysOpaque},enumerable:!0,configurable:!0});b.prototype._logGeometryCreationWarnings=function(a,
c,e,b){var f=a.geometryData&&a.geometryData.polygons;b+=" geometry failed to be created";var d=null;a.projectionSuccess?!c.length||1===c.length&&!c[0].length?d=b+" (no "+e+" were defined)":Array.isArray(c)&&Array.isArray(c[0])?c.some(function(a){return 1===a.length})?d=b+" ("+e+" should contain at least 2 vertices)":f&&0===f.length&&"rings"===e&&(d=b+" (filled "+e+" should use clockwise winding - try reversing the order of vertices)"):d=b+" ("+e+" should be defined as a 2D array)":d=b+" (failed to project geometry to view spatial reference)";
d&&q.warnOncePerTick(d)};b.prototype._validateGeometryType=function(a,c,b){if(x.includes(c,a.type))return!0;this.logger.warn("unsupported geometry type for "+b+(" symbol: "+a.type));return!1};b.prototype._validateGeometry=function(a){return"point"!==a.type||r.isFinite(a.x)&&r.isFinite(a.y)?!0:(q.warn("point coordinate is not a valid number, graphic skipped"),!1)};b.prototype._defaultElevationInfoNoZ=function(){return E};b.prototype._defaultElevationInfoZ=function(){return F};b.prototype._updateElevationContext=
function(){this._elevationContext.setDefaults();h.isSome(this._elevationInfoOverride)?this._elevationContext.mixinApi(this._elevationInfoOverride):this._context.layer.elevationInfo&&(this._elevationContext.mixinApi(this._context.layer.elevationInfo),this._elevationContext.featureExpressionInfoContext=this._context.featureExpressionInfoContext)};b.prototype.getDefaultElevationInfo=function(a){return a.hasZ?this._defaultElevationInfoZ():this._defaultElevationInfoNoZ()};b.prototype.getGeometryElevationMode=
function(a,c){void 0===c&&(c=this.getDefaultElevationInfo(a));return this._elevationContext.mode||c.mode};b.prototype.setElevationInfoOverride=function(a){this._elevationInfoOverride=a;this._updateElevationContext()};b.prototype.getGraphicElevationContext=function(a){var c=h.expect(a.geometry),b=this.getDefaultElevationInfo(c);d.setUnit(null!=this._elevationContext.unit?this._elevationContext.unit:b.unit);d.mode=this.getGeometryElevationMode(c,b);d.setOffsetMeters(null!=this._elevationContext.meterUnitOffset?
this._elevationContext.meterUnitOffset:b.offset);d.featureExpressionInfoContext=this._elevationContext.featureExpressionInfoContext;this._elevationOptions.supportsOnTheGround||"on-the-ground"!==d.mode||(d.mode="relative-to-ground",d.setOffsetMeters(0),d.featureExpressionInfoContext=m.zeroContext);if(c=d.featureExpressionInfoContext&&d.featureExpressionInfoContext.arcade)a=m.createFeature(c.modules,a,this._context.layer),m.setContextFeature(d.featureExpressionInfoContext,a);return d};b.prototype.prepareSymbolLayerPatch=
function(a){};b.prototype.updateGeometry=function(a,c){return!1};b.prototype.onRemoveGraphic=function(a){};b.prototype._getDrapedZ=function(){return-2};b.prototype._updateDrivenProperties=function(a){var c={color:!1,opacity:!1,opacityAlwaysOpaque:!0,size:!1};a||(a=this._context.renderer)&&"visualVariables"in a&&a.visualVariables&&a.visualVariables.forEach(function(a){switch(a.type){case "color":c.color=!0;if(a.stops)for(var b=0;b<a.stops.length;b++){var e=a.stops[b].color;e&&(c.opacity=!0,1>e.a&&
(c.opacityAlwaysOpaque=!1))}break;case "opacity":c.opacity=!0;c.opacityAlwaysOpaque=!1;break;case "size":c.size=!0}});this._drivenProperties=c};b.prototype._getLayerOpacity=function(){if(this._context.layerView&&"fullOpacity"in this._context.layerView)return this._context.layerView.fullOpacity;var a=this._context.layer.opacity;return null==a?1:a};b.prototype._getCombinedOpacity=function(a,c){void 0===c&&(c=u);var b;b=1*this._getLayerOpacity();if(this._drivenProperties.opacity)return b;h.isSome(a)?
b*=a.a:c.hasIntrinsicColor||(b=0);return b};b.prototype._getCombinedOpacityAndColor=function(a,b){void 0===b&&(b=u);b=this._getCombinedOpacity(a,b);if(this._drivenProperties.color)return p.mixinColorAndOpacity(null,b);a=h.isSome(a)?w.toUnitRGB(a):A.vec3f64.ONES;return p.mixinColorAndOpacity(a,b)};b.prototype._getVertexOpacityAndColor=function(a,b,e){a=p.mixinColorAndOpacity(this._drivenProperties.color?a.color:null,this._drivenProperties.opacity?a.opacity:null);e&&(a[0]*=e,a[1]*=e,a[2]*=e,a[3]*=e);
return b?new b(a):a};b.prototype._getIdHint=function(a){void 0===a&&(a="");return this._context.layer.id+"_symbol"+a};b.prototype.isFastUpdatesEnabled=function(){return this._fastUpdates&&this._fastUpdates.enabled};b.prototype.updateSymbolLayerOrder=function(a,b){this._symbolLayerOrder=a;this._symbolLayerOrderDelta=b};b.prototype.computeComplexity=function(){return D.defaultSymbolLayerComplexity(this.symbol,this.symbolLayer)};b.prototype.setDrawOrder=function(a,b,e){this.updateSymbolLayerOrder(a,
b);this._material&&(this._material.renderPriority=a,e.add(this._material.id))};b.prototype.destroy=function(){this.abortLoad()};b.prototype.globalPropertyChanged=function(a,b,e){switch(a){case "opacity":return this.layerOpacityChanged(b,e);case "elevationInfo":return a=this._elevationContext.mode,this._updateElevationContext(),this.layerElevationInfoChanged(b,e,a)===n.SymbolUpdateType.RECREATE?!1:!0;case "slicePlaneEnabled":return this.slicePlaneEnabledChanged(b,e);case "physicalBasedRenderingEnabled":return this.physicalBasedRenderingChanged();
case "pixelRatio":return this.pixelRatioChanged();default:return y.neverReachedSilent(a),!1}};b.prototype.updateGraphics3DGraphicElevationInfo=function(a,b,e){var c=this,d=n.SymbolUpdateType.UPDATE;a.forEach(function(a){var f=b(a);h.isSome(f)?(a=c.getGraphicElevationContext(a.graphic),f.needsElevationUpdates=e(a.mode),f.elevationContext.set(a)):d=n.SymbolUpdateType.RECREATE});return d};b.prototype.applyRendererDiff=function(a,b){return!1};b.prototype.getFastUpdateAttrValues=function(a){if(!this._fastUpdates.enabled)return null;
var b=this._fastUpdates.visualVariables,d=b.size?k(b.size.field,a):0,g=b.color?k(b.color.field,a):0;a=b.opacity?k(b.opacity.field,a):0;return B.vec4f64.fromValues(d,g,a,0)};return b}(C.Loadable);g.Graphics3DSymbolLayer=l;g.getAttributeValue=k;var E={mode:"on-the-ground",offset:0,unit:"meters"},F={mode:"absolute-height",offset:0,unit:"meters"},u={hasIntrinsicColor:!1};g.default=l});