// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../geometry ../../../../core/compilerUtils ../../../../core/libs/gl-matrix-2/mat4 ../../../../core/libs/gl-matrix-2/mat4f64 ../../../../core/libs/gl-matrix-2/vec3f64 ../../../../geometry/support/coordsUtils ../../../../geometry/support/triangulationUtils ../../../../layers/graphics/dehydratedFeatures ./graphicUtils ../../support/projectionUtils ../../webgl-engine/lib/Object3D".split(" "),function(P,f,A,J,K,B,L,C,M,p,D,u,N){function x(a,b,c,d,e){var f=b.z||0,k=c.featureExpressionInfoContext;
switch(c.mode){case "on-the-ground":return c=a.getElevation(b,"ground")||0,e&&(e.verticalDistanceToGround=0,e.terrainElevation=c),c;case "relative-to-ground":return a=a.getElevation(b,"ground")||0,c=c.calculateOffsetRenderUnits(d),null==k&&(c+=f),e&&(e.verticalDistanceToGround=c,e.terrainElevation=a),c+a;case "relative-to-scene":return a=a.getElevation(b,"scene")||0,c=c.calculateOffsetRenderUnits(d),e&&(e.verticalDistanceToGround=c,e.terrainElevation=a),c+a;case "absolute-height":return c=c.calculateOffsetRenderUnits(d),
null==k&&(c+=f),e&&(a=a.getElevation(b,"ground")||0,e.verticalDistanceToGround=c-a,e.terrainElevation=a),c;default:J.neverReached(c.mode)}return 0}function E(a,b,c,d,e,f,k,h){var r=h.mode,l=0,g=0,t=0;k=h.calculateOffsetRenderUnits(k);h=h.featureExpressionInfoContext;m.spatialReference=a.spatialReference;c*=3;e*=3;for(var n=0;n<f;++n){m.x=b[c+0];m.y=b[c+1];m.z=b[c+2];switch(r){case "on-the-ground":g=l=a.getElevation(m)||0;t+=l;break;case "relative-to-ground":l=a.getElevation(m)||0;g=l+k;null==h&&(g+=
m.z);t+=l;break;case "relative-to-scene":l=a.getElevation(m,"scene")||0;g=l+k;t+=l;break;case "absolute-height":g=k,null==h&&(g+=m.z)}d[e+0]=b[c+0];d[e+1]=b[c+1];d[e+2]=g;c+=3;e+=3}return{terrainElevation:t/f}}function y(a,b,c){a=M.pathsToTriangulationInfo(a,b,c);return{vertexData:a.position,polygons:a.polygons,outlines:a.outlines}}function F(a,b,c,d,e){b*=3;d*=3;for(var f=0;f<e;++f)c[d++]=a[b++],c[d++]=a[b++],c[d++]=a[b++]}function z(a,b,c,d,e,f,k){return u.bufferToBuffer(a,c,b,d,f,e,k)}function v(a,
b,c){u.pointToVector(a,b,c)}function G(a,b){return!(a[0]>b[3]||a[0]<b[0]||a[1]>b[4]||a[1]<b[1])}function H(a,b){return!(b[0]>a[3]||b[3]<a[0]||b[1]>a[4]||b[4]<a[1])}Object.defineProperty(f,"__esModule",{value:!0});var g=L.vec3f64.create(),m=p.makeDehydratedPoint(0,0,0,null);f.createStageObjectForPoint=function(a,b,c,d,e,f,k,h,q,l,m,t){var r=c?c.length:0,w=a.clippingExtent;v(b,g,a.elevationProvider.spatialReference);if(w&&!G(g,w))return null;v(b,g,a.renderSpatialReference);w=a.localOriginFactory.getOrigin(g);
h=new N({castShadow:!1,metadata:{layerUid:q,graphicUid:l,usesVerticalDistanceToGround:!!m},idHint:h});for(q=0;q<r;q++)h.addGeometry(c[q],d[q],e?e[q]:B.mat4f64.IDENTITY,f,w,t);c=a.renderSpatialReference;d=a.elevationProvider;e=a.renderCoordsHelper;a=0;var p;h.metadata.usesVerticalDistanceToGround?(a=x(d,b,k,e,n),D.updateVertexAttributeAuxpos1w(h,n.verticalDistanceToGround),p=n.terrainElevation):(f="absolute-height"!==k.mode,a=x(d,b,k,e,f?n:null),f&&(p=n.terrainElevation));k=K.mat4.copy(O,h.objectTransformation);
g[0]=b.x;g[1]=b.y;g[2]=a;u.computeLinearTransformation(b.spatialReference,g,k,c)?h.objectTransformation=k:console.warn("Could not locate symbol object properly, it might be misplaced");return{object:h,terrainElevation:p}};f.extendPointGraphicElevationContext=function(a,b,c){a=a.elevationContext;c=c.spatialReference;v(b,g,c);a.centerPointInElevationSR=p.makeDehydratedPoint(g[0],g[1],b.hasZ?g[2]:0,c)};f.placePointOnGeometry=function(a){switch(a.type){case "point":return a;case "polygon":case "extent":return D.computeCentroid(a);
case "polyline":var b=a.paths[0];if(!b||0===b.length)break;b=C.getPointOnPath(b,C.getPathLength(b)/2);return p.makeDehydratedPoint(b[0],b[1],b[2],a.spatialReference);case "mesh":return a.extent.center}return null};f.computeElevation=x;f.applyElevation=E;var O=B.mat4f64.create();f.copyPathData=y;f.copyVertices=F;f.applyOrigin=function(a,b,c,d){var e=Math.floor(b+(c-1)/2);d[0]=a[3*e+0];d[1]=a[3*e+1];d[2]=a[3*e+2];b*=3;for(e=0;e<c;++e)a[b++]-=d[0],a[b++]-=d[1],a[b++]-=d[2]};f.setZ=function(a,b,c,d){b*=
3;for(var e=0;e<c;++e)a[b+2]=d,b+=3};f.offsetZ=function(a,b,c,d){b*=3;for(var e=0;e<c;++e)a[b+2]+=d,b+=3};f.scaleZ=function(a,b,c,d){b*=3;for(var e=0;e<c;++e)a[b+2]*=d,b+=3};f.flatArrayToArrayOfArrays=function(a,b,c){var d=[];b*=3;for(var e=0;e<c;++e)d.push([a[b++],a[b++],a[b++]]);return d};f.reproject=z;f.reprojectPoint=v;f.getGeometryVertexData3D=function(a,b,c,d,e,f,k,h){var g=e.spatialReference;a=y(a,b,h);b=a.vertexData;h=b.length/3;var l=new Float64Array(b.length),r=!0;c.equals(g)?F(b,0,l,0,
b.length):r=z(b,0,c,l,0,g,h);c=E(e,l,0,b,0,h,f,k);g.equals(d)||z(b,0,g,b,0,d,h);return{geometryData:a,vertexData:b,projectionSuccess:r,eleVertexData:l,terrainElevation:c.terrainElevation}};f.getGeometryVertexDataDraped=function(a,b,c,d){a=y(a,!1,d);d=a.vertexData;var e=d.length/3,f=!0;b.equals(c)||(f=u.bufferToBuffer(d,b,0,d,c,0,e));return{geometryData:a,vertexData:d,projectionSuccess:f}};f.computeBoundingBox=function(a,b,c,d){d[0]=Number.MAX_VALUE;d[1]=Number.MAX_VALUE;d[2]=Number.MAX_VALUE;d[3]=
-Number.MAX_VALUE;d[4]=-Number.MAX_VALUE;d[5]=-Number.MAX_VALUE;b*=3;for(var e=0;e<c;++e){var f=a[b++],g=a[b++],h=a[b++];f<d[0]&&(d[0]=f);g<d[1]&&(d[1]=g);h<d[2]&&(d[2]=h);f>d[3]&&(d[3]=f);g>d[4]&&(d[4]=g);h>d[5]&&(d[5]=h)}return d};var I;(function(a){a[a.NONE=0]="NONE";a[a.UPDATE=1]="UPDATE";a[a.RECREATE=2]="RECREATE"})(I=f.SymbolUpdateType||(f.SymbolUpdateType={}));f.elevationModeChangeUpdateType=function(a,b,c){return null==b||null==c?a.definedChanged:"on-the-ground"===b&&"on-the-ground"===c?a.staysOnTheGround:
b===c||"on-the-ground"!==b&&"on-the-ground"!==c?I.UPDATE:a.onTheGroundChanged};f.getGeometryAsPolygon=function(a){switch(a.type){case "extent":return A.Polygon.fromExtent(a);case "polygon":return a}return null};f.getGeometryAsPoly=function(a){switch(a.type){case "extent":return A.Polygon.fromExtent(a);case "polygon":case "polyline":return a}return null};f.pointInBox2D=G;f.boxesIntersect2D=H;f.boundingBoxClipped=function(a,b){return b?!H(a,b):!1};f.needsElevationUpdates2D=function(a){return"relative-to-ground"===
a||"relative-to-scene"===a};f.needsElevationUpdates3D=function(a){return"absolute-height"!==a};var n={verticalDistanceToGround:0,terrainElevation:0}});