// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/tsSupport/generatorHelper ../../../../core/tsSupport/awaiterHelper ../../../../Color ../../../../Color ../../../../core/maybe ../../../../core/screenUtils ../../../../core/libs/earcut/earcut ../../../../core/libs/gl-matrix-2/mat4 ../../../../core/libs/gl-matrix-2/mat4f64 ../../../../core/libs/gl-matrix-2/vec3f64 ../../../../geometry/support/aaBoundingBox ./constants ./ElevationAligners ./Graphics3DDrapedGraphicLayer ./Graphics3DObject3DGraphicLayer ./Graphics3DSymbolCommonCode ./Graphics3DSymbolLayer ./graphicUtils ./lineUtils ./polygonUtils ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/Object3D ../../webgl-engine/lib/RenderGeometry ../../webgl-engine/materials/ColorMaterial ../../webgl-engine/materials/lineStippleUtils ../../webgl-engine/materials/NativeLineMaterial ../../webgl-engine/materials/RibbonLineMaterial".split(" "),
function(q,v,E,F,G,H,I,n,x,y,r,t,J,u,z,K,L,M,k,N,O,A,B,C,P,D,Q,R,w,S){Object.defineProperty(v,"__esModule",{value:!0});q=function(q){function e(a,d,l,b){a=q.call(this,a,d,l,b)||this;a._hasOutline=!1;return a}E(e,q);e.prototype.doLoad=function(){return G(this,void 0,void 0,function(){return F(this,function(a){this._prepareFillResources();this._prepareOutlineResources();return[2]})})};e.prototype._prepareFillResources=function(){var a=n.get(this.symbolLayer,"material","color"),a=this._getCombinedOpacityAndColor(a);
this._material=new Q({color:a,transparent:1>a[3]||this.needsDrivenTransparentPass,polygonOffset:!1,vertexColors:!0,slicePlaneEnabled:this._context.slicePlaneEnabled},this._getIdHint("_colormat"));this._context.stage.add(3,this._material)};e.prototype._prepareOutlineResources=function(){var a=this.symbolLayer.outline;if(this._isValidOutline(a)){this._hasOutline=!0;var d;d=x.pt2px(a.size);var l=a.stipplePattern?R.createStipplePattern(a.stipplePattern.map(x.pt2px)):null,a=a.stippleOffColor?I.toUnitRGBA(a.stippleOffColor):
null;d=1.5<d?new S({width:d,color:this._getOutlineColor(),polygonOffset:!0,slicePlaneEnabled:this._context.slicePlaneEnabled,isClosed:!0,stipplePattern:l,stippleIntegerRepeats:!0,stippleOffColor:a},this._getIdHint("_outline_ribbonlinemat")):new w({color:this._getOutlineColor(),slicePlaneEnabled:this._context.slicePlaneEnabled,width:d,stipplePattern:l,stippleIntegerRepeats:!0,stippleOffColor:a},this._getIdHint("_outline_nativelinemat"));this._outlineMaterial=d;this._context.stage.add(3,this._outlineMaterial)}};
e.prototype._isValidOutline=function(a){return n.isSome(a)&&a.size&&0<a.size&&n.isSome(a.color)};e.prototype.destroy=function(){q.prototype.destroy.call(this);this._material&&(this._context.stage.remove(3,this._material.id),this._material=null);this._outlineMaterial&&(this._context.stage.remove(3,this._outlineMaterial.id),this._outlineMaterial=null)};e.prototype.createGraphics3DGraphic=function(a){var d=a.graphic;if(!this._validateGeometryType(d.geometry,e.validGeometryTypes,this.symbolLayer.type)||
!this._validateGeometry(d.geometry))return null;var l="graphic"+d.uid;a=this._getVertexOpacityAndColor(a.renderingInfo,Uint8Array,255);var b=this.getGraphicElevationContext(d);return"on-the-ground"===b.mode?this._createAsOverlay(d,a,l):this._createAs3DShape(d,a,b,l,d.uid)};e.prototype.layerOpacityChanged=function(){var a=this._material.getParameters().color,d=n.get(this.symbolLayer,"material","color"),d=this._getCombinedOpacity(d);this._material.setParameterValues({color:[a[0],a[1],a[2],d],transparent:1>
d||this.needsDrivenTransparentPass});this._outlineMaterial&&(a=this._outlineMaterial.getParameters().color,this._outlineMaterial.setParameterValues({color:[a[0],a[1],a[2],this._getOutlineOpacity()]}));return!0};e.prototype.layerElevationInfoChanged=function(a,d,b){var l=this._elevationContext.mode;b=k.elevationModeChangeUpdateType(e.elevationModeChangeTypes,b,l);if(b!==k.SymbolUpdateType.UPDATE)return b;var g=k.needsElevationUpdates2D(l);return this.updateGraphics3DGraphicElevationInfo(a,d,function(){return g})};
e.prototype.slicePlaneEnabledChanged=function(){this._material.setParameterValues({slicePlaneEnabled:this._context.slicePlaneEnabled});this._outlineMaterial&&this._outlineMaterial.setParameterValues({slicePlaneEnabled:this._context.slicePlaneEnabled});return!0};e.prototype.physicalBasedRenderingChanged=function(){return!0};e.prototype.pixelRatioChanged=function(){return!0};e.prototype.setDrawOrder=function(a,d,b){this.updateSymbolLayerOrder(a,d);this._material&&(this._material.renderPriority=a+d/
2,b.add(this._material.id));this._outlineMaterial&&(this._outlineMaterial.renderPriority=a,b.add(this._outlineMaterial.id))};e.prototype._createAs3DShape=function(a,d,l,e,g){var f=k.getGeometryAsPolygon(a.geometry);a=k.getGeometryVertexData3D(f.rings,f.hasZ,f.spatialReference,this._context.renderSpatialReference,this._context.elevationProvider,this._context.renderCoordsHelper,l,1);b.idHint=e;b.color=d;b.data=a;var c;this._hasOutline&&(c=new Float64Array(a.vertexData));b.outNum=0;b.outGeometries=[];
b.outTransforms=[];b.outMaterials=[];this._createAs3DShapeFill(b);b.data.vertexData=c;this._createAs3DShapeOutline(b);this._logGeometryCreationWarnings(b.data,f.rings,"rings","FillSymbol3DLayer");if(0===b.outNum)return null;d=new P({geometries:b.outGeometries,materials:b.outMaterials,transformations:b.outTransforms,castShadow:!1,metadata:{layerUid:this._context.layer.uid,graphicUid:g},idHint:e});d=new M(this,d,b.outGeometries,null,null,K.perVertexElevationAligner,l);d.alignedTerrainElevation=a.terrainElevation;
d.needsElevationUpdates=k.needsElevationUpdates2D(l.mode);return d};e.prototype._createAs3DShapeFill=function(a){for(var d=a.data.geometryData.polygons,b=a.data.eleVertexData,e=a.data.vertexData,g=function(c){var g=d[c],h=g.count,l=g.index;if(f._context.clippingExtent&&(k.computeBoundingBox(b,l,h,m),k.boundingBoxClipped(m,f._context.clippingExtent)))return"continue";c=new Float64Array(b.buffer,3*l*b.BYTES_PER_ELEMENT,3*h);g=g.holeIndices.map(function(a){return a-l});g=y(c,g,3);if(0===g.length)return"continue";
k.applyOrigin(e,l,h,p);g=new Uint32Array(g);h=new Float64Array(e.buffer,3*l*e.BYTES_PER_ELEMENT,3*h);c=B.createPolygonGeometryData({indices:g,vertices:h,color:a.color,eleVertices:c});c=new C(c,a.idHint);c.singleUse=!0;h=t.mat4f64.create();r.mat4.translate(h,h,p);a.outGeometries.push(c);a.outMaterials.push(f._material);a.outTransforms.push(h);a.outNum++},f=this,c=0;c<d.length;++c)g(c)};e.prototype._createAs3DShapeOutline=function(a){if(this._hasOutline)for(var d=a.data.geometryData.outlines,b=a.data.eleVertexData,
e=a.data.vertexData,g=0;g<d.length;++g){var f=d[g],c=f.index,h=f.count;if(this._context.clippingExtent&&(k.computeBoundingBox(b,c,h,m),k.boundingBoxClipped(m,this._context.clippingExtent)))continue;k.applyOrigin(e,c,h,p);f=new Float64Array(b.buffer,3*c*b.BYTES_PER_ELEMENT,3*h);c=new Float64Array(e.buffer,3*c*e.BYTES_PER_ELEMENT,3*h);c=A.createPolylineGeometry(c,f,z.WHITE,1,this._outlineMaterial instanceof w?0:1);c=new C(c,a.idHint+"outline"+g);c.singleUse=!0;f=t.mat4f64.create();r.mat4.translate(f,
f,p);a.outGeometries.push(c);a.outMaterials.push(this._outlineMaterial);a.outTransforms.push(f);a.outNum++}};e.prototype._createAsOverlay=function(a,d,e){var l=k.getGeometryAsPolygon(a.geometry);this._material.renderPriority=this._symbolLayerOrder+this._symbolLayerOrderDelta/2;this._hasOutline&&(this._outlineMaterial.renderPriority=this._symbolLayerOrder);var g=k.getGeometryVertexDataDraped(l.rings,l.spatialReference,this._context.overlaySR,1);b.idHint=e;b.color=d;b.data=g;var f;this._hasOutline&&
(f=new Float64Array(g.vertexData));b.outNum=0;b.outGeometries=[];b.outBoundingBox=u.empty();b.layerUid=this._context.layer.uid;b.graphicsUid=a.uid;this._createAsOverlayFill(b);b.data.vertexData=f;this._createAsOverlayOutline(b);this._logGeometryCreationWarnings(b.data,l.rings,"rings","FillSymbol3DLayer");return 0<b.outNum?new L(this,b.outGeometries,b.outBoundingBox):null};e.prototype._createAsOverlayFill=function(a){for(var d=a.data.vertexData,b=a.data.geometryData.polygons,e=function(c){var h=b[c];
c=h.count;var e=h.index;k.computeBoundingBox(d,e,c,m);if(k.boundingBoxClipped(m,g._context.clippingExtent))return"continue";var f=new Float64Array(d.buffer,3*e*d.BYTES_PER_ELEMENT,3*c),h=h.holeIndices.map(function(a){return a-e}),f=y(f,h,3);if(0===f.length)return"continue";u.expand(a.outBoundingBox,m);k.applyOrigin(d,e,c,p);k.setZ(d,e,c,g._getDrapedZ());c=new Uint32Array(f.length);for(h=0;h<f.length;h++)c[h]=f[h]+e;c=B.createPolygonGeometryData({indices:c,vertices:d,color:a.color});f=new D(c);f.data.layerUid=
a.layerUid;f.data.graphicUid=a.graphicsUid;f.material=g._material;h=m;f.center=[.5*(h[0]+h[3]),.5*(h[1]+h[4]),0];f.bsRadius=.5*Math.sqrt((h[3]-h[0])*(h[3]-h[0])+(h[4]-h[1])*(h[4]-h[1]));h=t.mat4f64.create();r.mat4.translate(h,h,p);f.transformation=h;f.name=a.idHint;f.uniqueName=a.idHint+"#"+c.id;a.outGeometries.push(f);a.outNum++},g=this,f=0;f<b.length;++f)e(f)};e.prototype._createAsOverlayOutline=function(a){if(this._hasOutline)for(var d=a.data.vertexData,b=a.data.geometryData.outlines,e=0;e<b.length;++e){var g=
b[e],f=g.index,g=g.count;k.computeBoundingBox(d,f,g,m);if(!k.boundingBoxClipped(m,this._context.clippingExtent)){u.expand(a.outBoundingBox,m);k.applyOrigin(d,f,g,p);k.setZ(d,f,g,this._getDrapedZ());f=new Float64Array(d.buffer,3*f*d.BYTES_PER_ELEMENT,3*g);f=A.createPolylineGeometry(f,null,z.WHITE,1,this._outlineMaterial instanceof w?0:1);g=new D(f);g.data.layerUid=a.layerUid;g.data.graphicUid=a.graphicsUid;g.material=this._outlineMaterial;var c=m;g.center=[.5*(c[0]+c[3]),.5*(c[1]+c[4]),0];g.bsRadius=
.5*Math.sqrt((c[3]-c[0])*(c[3]-c[0])+(c[4]-c[1])*(c[4]-c[1]));c=t.mat4f64.create();r.mat4.translate(c,c,p);g.transformation=c;g.name=a.idHint+"outline";g.uniqueName=a.idHint+"outline#"+f.id;a.outGeometries.push(g);a.outNum++}}};e.prototype._getOutlineOpacity=function(){var a=n.get(this.symbolLayer,"outline","color");return this._getLayerOpacity()*(n.isSome(a)?a.a:0)};e.prototype._getOutlineColor=function(){var a=n.get(this.symbolLayer,"outline","color"),b=this._getOutlineOpacity();return O.mixinColorAndOpacity(n.isSome(a)?
H.toUnitRGB(a):null,b)};e.validGeometryTypes=["polyline","polygon","extent"];e.elevationModeChangeTypes={definedChanged:k.SymbolUpdateType.RECREATE,staysOnTheGround:k.SymbolUpdateType.NONE,onTheGroundChanged:k.SymbolUpdateType.RECREATE};return e}(N.default);v.Graphics3DPolygonFillSymbolLayer=q;var m=u.create(),p=J.vec3f64.create(),b={idHint:null,data:null,outNum:0,outBoundingBox:null,outGeometries:null,outMaterials:null,outTransforms:null,color:null};v.default=q});