// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/generatorHelper ../../../../core/tsSupport/awaiterHelper ../../../../core/asyncUtils ../../../../core/maybe ../../../../core/ObjectPool ../../../../core/libs/gl-matrix-2/vec2 ../../../../core/libs/gl-matrix-2/vec2f64 ../../../../core/libs/gl-matrix-2/vec3 ../../../../core/libs/gl-matrix-2/vec3f64 ../../../../geometry/Polygon ../../../../geometry/support/aaBoundingBox ../../../../geometry/support/aaBoundingRect ../../../../layers/graphics/dehydratedFeatures ../../../../layers/graphics/featureConversionUtils ./featureExpressionInfoUtils ../../support/projectionUtils".split(" "),
function(F,G,q,r,w,k,x,y,z,t,u,A,g,l,p,B,C,D){var v=new x(Array,function(b){return g.set(b,g.ZERO)},null,10,5),E=l.create();return function(){function b(a,c,d,b,e){this._labelGraphics=[];this._auxiliaryGraphics=[];for(var h=Array(2),f=0;f<h.length;f++)h[f]=Array(4);this._visibilityFlags=h;this._featureExpressionFeature=null;this._optimizedGeometry={geometry:null,hasZ:!1,hasM:!1};this.extent=null;this.isElevationSource=!1;++c.referenced;this.graphics3DSymbol=c;this.graphic=a;this._graphics=d;this._featureExpressionFeature=
e?C.createFeature(e,a,b):null;a=0;for(c=this._graphics;a<c.length;a++)d=c[a],k.isSome(d)&&(this.isElevationSource=this.isElevationSource||d.isElevationSource)}b.prototype.initialize=function(a,c){var d=this;this._layer=a;this._stage=c;this.forEachSymbolLayerGraphic(function(b){b.initialize(a,c);b.setVisibility(d.isVisible())})};b.prototype.destroy=function(){this.forEachSymbolLayerGraphic(function(a){return a.destroy()});this._auxiliaryGraphics=this._graphics=null;--this.graphics3DSymbol.referenced;
this.graphics3DSymbol=null};Object.defineProperty(b.prototype,"destroyed",{get:function(){return null==this._graphics},enumerable:!0,configurable:!0});b.prototype.clearLabelGraphics=function(){this.forEachLabelGraphic(function(a){return a.destroy()});this._labelGraphics.length=0};b.prototype.addLabelGraphic=function(a,c,d){this._labelGraphics.push(a);a.initialize(c,d);a.setVisibility(this.isVisible(1))};b.prototype.addAuxiliaryGraphic=function(a){this._auxiliaryGraphics.push(a);this._layer&&(a.initialize(this._layer,
this._stage),a.setVisibility(this.isVisible()))};b.prototype.isDraped=function(){var a=!1;this.forEachSymbolLayerGraphic(function(c){"draped"===c.type&&(a=!0)});return a};b.prototype.isVisible=function(a,c){void 0===a&&(a=0);for(var d=0;d<=a;d++)for(var b=this._visibilityFlags[d],e=0;e<b.length;++e)if(!1===b[e]&&e!==c)return!1;return!0};b.prototype.hasVisibilityFlag=function(a,c){return null!=this._visibilityFlags[c][a]};b.prototype.setVisibilityFlag=function(a,c,d){var b=this.isVisible(d);this._visibilityFlags[d][a]=
c;var e=this.isVisible(d);if(b===e)return!1;if(1===d)this.forEachLabelGraphic(function(a){return a.setVisibility(e)});else{this.forEachSymbolLayerGraphic(function(a){return a.setVisibility(e)});var g=this.isVisible(1);this.forEachLabelGraphic(function(a){return a.setVisibility(g)})}return!0};b.prototype.clearVisibilityFlag=function(a,c){void 0===c&&(c=0);return this.setVisibilityFlag(a,void 0,c)};b.prototype.getBSRadius=function(){var a=0;this.forEachSymbolLayerGraphic(function(c){a=Math.max(a,c.getBSRadius())});
return a};b.prototype.getCenterObjectSpace=function(a){void 0===a&&(a=u.vec3f64.create());if(0===this._graphics.length)return t.vec3.set(a,0,0,0),a;var c=this._graphics[0];return k.isSome(c)?c.getCenterObjectSpace(a):a};b.prototype.computeExtent=function(a){if(!this.extent){this.extent=l.create();var c=this.graphic.geometry;if(k.isNone(c))return this.extent=null,!1;var d=c.spatialReference;p.computeAABR(c,this.extent);if(!d.equals(a)&&!D.boundingRectToBoundingRect(this.extent,d,this.extent,a))return this.extent=
null,!1}return!0};b.prototype.getAsOptimizedGeometry=function(a,c){if(this._optimizedGeometry.geometry&&this._optimizedGeometry.hasZ===a&&this._optimizedGeometry.hasM===c)return this._optimizedGeometry.geometry;this._optimizedGeometry.geometry=this._convertGraphicToOptimizedGeometry(this.graphic,a,c);this._optimizedGeometry.hasZ=a;this._optimizedGeometry.hasM=c;return this._optimizedGeometry.geometry};b.prototype._convertGraphicToOptimizedGeometry=function(a,c,d){a=a.geometry;if("mesh"===a.type||
"extent"===a.type)a=A.fromExtent("mesh"===a.type?a.extent:a);return B.convertFromGeometry(a,c,d)};Object.defineProperty(b.prototype,"usedMemory",{get:function(){var a=this,c=p.estimateAttributesObjectSize(this.graphic.attributes);this.forEachSymbolLayerGraphic(function(d){var b=d.graphics3DSymbolLayer.complexity;d="draped"===d.type?b.memory.draped:b.memory;c+=d.bytesPerFeature;d.bytesPerCoordinate&&(c+=p.numVertices(a.graphic.geometry)*d.bytesPerCoordinate)});return c},enumerable:!0,configurable:!0});
b.prototype.computeAttachmentOrigin=function(){for(var a={render:{origin:u.vec3f64.create(),num:0},draped:{origin:z.vec2f64.create(),num:0}},c=0,d=this._graphics;c<d.length;c++){var b=d[c];k.isNone(b)||b.computeAttachmentOrigin(a)}a.render.num&&t.vec3.scale(a.render.origin,a.render.origin,1/a.render.num);a.draped.num&&y.vec2.scale(a.draped.origin,a.draped.origin,1/a.draped.num);return a};b.prototype.getProjectedBoundingBox=function(a,c,d,b,e){return r(this,void 0,void 0,function(){var h=this;return q(this,
function(f){switch(f.label){case 0:return e||(e={boundingBox:null,requiresDrapedElevation:!1,screenSpaceObjects:[]}),e.boundingBox?g.empty(e.boundingBox):e.boundingBox=g.empty(),e.requiresDrapedElevation=!1,[4,w.forEach(this._graphics,function(f){return r(h,void 0,void 0,function(){var h,m,n;return q(this,function(l){switch(l.label){case 0:if(k.isNone(f))return[2];h="draped"===f.type?c:a;m=v.acquire();return[4,f.getProjectedBoundingBox(h,d,e.screenSpaceObjects,b,m)];case 1:return n=l.sent(),isFinite(n[2])&&
isFinite(n[5])||(e.requiresDrapedElevation=!0),n&&g.expand(e.boundingBox,m),v.release(m),[2]}})})})];case 1:return f.sent(),g.allFinite(e.boundingBox)||l.allFinite(g.toRect(e.boundingBox,E))?[2,e]:[2,null]}})})};b.prototype.needsElevationUpdates=function(){for(var a=0,c=this._graphics;a<c.length;a++){var b=c[a];if(k.isSome(b)&&("object3d"===b.type||"lod-instance"===b.type)&&b.needsElevationUpdates)return!0}a=0;for(c=this._labelGraphics;a<c.length;a++)if((b=c[a])&&b.needsElevationUpdates)return!0;
return!1};b.prototype.alignWithElevation=function(a,c,b){var d=this;this.forEachRenderedGraphic(function(e){"object3d"!==e.type&&"lod-instance"!==e.type||e.alignWithElevation(a,c,d._featureExpressionFeature,b)})};b.prototype.addHighlight=function(a,c){this.forEachSymbolLayerGraphic(function(b){return b.addHighlight(a,c)})};b.prototype.removeHighlight=function(a){this.forEachSymbolLayerGraphic(function(c){return c.removeHighlight(a)})};b.prototype.forEachGraphicList=function(a,c){a.forEach(function(a,
b){return a&&c(a,b)})};b.prototype.forEachSymbolLayerGraphic=function(a){this.forEachGraphicList(this._graphics,a);this.forEachGraphicList(this._auxiliaryGraphics,a)};b.prototype.forEachLabelGraphic=function(a){this.forEachGraphicList(this._labelGraphics,a)};b.prototype.forEachRenderedGraphic=function(a){this.forEachSymbolLayerGraphic(a);this.forEachLabelGraphic(a)};return b}()});