// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/tsSupport/generatorHelper ../../../../core/tsSupport/awaiterHelper ../../../../core/Error ../../../../core/maybe ../../../../core/ObjectPool ../../../../core/screenUtils ../../../../core/libs/gl-matrix-2/vec2f64 ../../../../symbols/callouts/calloutUtils ./ElevationAligners ./Graphics3DObject3DGraphicLayer ./Graphics3DSymbolCommonCode ./Graphics3DSymbolLayer ./graphicUtils ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/GeometryData ../../webgl-engine/lib/GeometryUtil ../../webgl-engine/lib/TextRenderParameters ../../webgl-engine/lib/TextTexture ../../webgl-engine/materials/HUDMaterial".split(" "),
function(r,t,z,A,B,C,f,D,E,F,G,H,I,l,J,v,K,L,u,M,N,w){function x(l,c,a){l&&l.forEach(function(b){var y=c(b);f.isSome(y)&&a(y,b.graphic)})}Object.defineProperty(t,"__esModule",{value:!0});var O=[0,0,1];r=function(n){function c(a,b,c,d){a=n.call(this,a,b,c,d)||this;a._geometryDataPool=new D(L.GeometryData,function(a,b,d){var c=b.translation;d=f.isSome(d)?[d.displayWidth,d.displayHeight]:[0,0];b=b.centerOffset;0===a.indexCount?u.createPointGeometry(O,c,null,d,b,[0,0],null,a):u.updatePointGeometry(null,
c,null,d,b,null,null,a)});a._elevationOptions={supportsOffsetAdjustment:!0,supportsOnTheGround:!1};return a}z(c,n);c.prototype.doLoad=function(){return B(this,void 0,void 0,function(){var a;return A(this,function(b){if(!this._drivenProperties.size&&(a=v.validateSymbolLayerSize(this.symbolLayer.size)))throw new C("graphics3dtextsymbollayer:invalid-size",a);this._createTextRenderParameters();return[2]})})};c.prototype._createTextRenderParameters=function(){this._textRenderParameters=M.default.fromSymbol(this.symbolLayer,
this._context.layerView.view.pixelRatio)};c.prototype.destroy=function(){n.prototype.destroy.call(this);this._geometryDataPool.destroy()};c.prototype.createGraphics3DGraphic=function(a){a=a.graphic;var b=l.placePointOnGeometry(a.geometry);if(f.isNone(b))return this.logger.warn("unsupported geometry type for text symbol: "+a.geometry.type),null;var c=this.symbolLayer.text;if(!c)return null;var d=G.isCalloutSupport(this.symbol)&&this.symbol.hasVisibleVerticalOffset()?this.symbol:null;return this._createAs3DShape(a,
b,c,d)};c.prototype.onRemoveGraphic=function(a){this._geometryDataPool.release(a.stageObject.geometries[0].data)};c.prototype.createLabel=function(a,b,c,d){a=a.graphic;var g=l.placePointOnGeometry(a.geometry);if(f.isNone(g))return this.logger.warn("unsupported geometry type for label: "+a.geometry.type),null;var h=b.text;return h?this._createAs3DShape(a,g,h,b,b,c,d):null};c.prototype.getGraphicElevationContext=function(a,b){void 0===b&&(b=0);a=n.prototype.getGraphicElevationContext.call(this,a);a.addOffsetRenderUnits(b);
return a};c.prototype.layerOpacityChanged=function(){this.logger.warn("layer opacity change not yet implemented in Graphics3DTextSymbolLayer");return!1};c.prototype.layerElevationInfoChanged=function(a,b){var c=this;x(a,b,function(a,b){c.updateGraphicElevationContext(b,a)});return l.SymbolUpdateType.UPDATE};c.prototype.slicePlaneEnabledChanged=function(a,b){var c=this;x(a,b,function(a){var b=0;for(a=a.stageObject.geometryRecords;b<a.length;b++)a[b].material.setParameterValues({slicePlaneEnabled:c._context.slicePlaneEnabled})});
return!0};c.prototype.physicalBasedRenderingChanged=function(){return!0};c.prototype.pixelRatioChanged=function(){return!1};c.prototype.updateGraphicElevationContext=function(a,b){a=this.getGraphicElevationContext(a,b.metadata.elevationOffset);b.elevationContext.set(a);b.needsElevationUpdates=l.needsElevationUpdates2D(a.mode)||"absolute-height"===a.mode};c.prototype._defaultElevationInfoNoZ=function(){return P};c.prototype._createAs3DShape=function(a,b,c,d,g,h,p){void 0===g&&(g=Q);var q=this.getGraphicElevationContext(a,
g.elevationOffset),m=this._context.layer.id+"_label_"+a.uid,k="polyline"===f.get(a.geometry,"type"),n=a.uid;a=this._context.stage.renderView.renderingContext;var e=v.namedAnchorToHUDMaterialAnchorPos[g.anchor in v.namedAnchorToHUDMaterialAnchorPos?g.anchor:"center"];a=f.isNone(p)?new N(a,c,this._textRenderParameters,m):null;e={occlusionTest:!0,screenOffset:g.screenOffset,anchorPos:e,polygonOffset:!0,color:[1,1,1,1],centerOffsetUnits:g.centerOffsetUnits,debugDrawBorder:g.debugDrawBorder,drawInSecondSlot:!0};
f.isSome(a)&&(e.textureId=a.id,e.texCoordScale=a.texcoordScale);f.isSome(p)&&(e.textureId=p.textureId);if(f.isSome(d)&&f.isSome(d.verticalOffset)){d=d.verticalOffset;p=d.minWorldLength;var r=d.maxWorldLength;e.verticalOffset={screenLength:E.pt2px(d.screenLength),minWorldLength:p||0,maxWorldLength:null!=r?r:Infinity}}this._context.screenSizePerspectiveEnabled&&(d=this._context.sharedResources,p=d.screenSizePerspectiveSettings,e.screenSizePerspective=d.screenSizePerspectiveSettingsLabels.overridePadding(this._textRenderParameters.haloSize),
e.screenSizePerspectiveAlignment=p);k&&(e.shaderPolygonOffset=1E-4);e.slicePlaneEnabled=this._context.slicePlaneEnabled;k=null;d=JSON.stringify(e);f.isSome(h)?(k=h.getMaterial(d),null==k&&(k=new w(e,m),h.addMaterial(d,k))):k=new w(e,m);k=[k];e=this._geometryDataPool.acquire(g,a);e=[new K(e,m)];m=l.createStageObjectForPoint(this._context,b,e,k,null,null,q,m,this._context.layer.uid,n,!0);if(null===m)return null;n=H.perObjectElevationAligner;h=new I(this,m.object,e,f.isNone(h)?k:null,f.isSome(a)?[a]:
null,n,q);h.alignedTerrainElevation=m.terrainElevation;h.needsElevationUpdates=l.needsElevationUpdates2D(q.mode)||"absolute-height"===q.mode;var q=f.isSome(a)?a:g,t=q.displayWidth,u=q.displayHeight;h.getScreenSize=function(a){void 0===a&&(a=F.vec2f64.create());a[0]=t;a[1]=u;return a};h.metadata={labelText:c,elevationOffset:g.elevationOffset};l.extendPointGraphicElevationContext(h,b,this._context.elevationProvider);return h};return c}(J.default);t.Graphics3DTextSymbolLayer=r;var P={mode:"relative-to-ground",
offset:0},Q={text:null,translation:[0,0,0],elevationOffset:0,centerOffset:[0,0,0,1],screenOffset:[0,0],anchor:"center",verticalOffset:null,centerOffsetUnits:null,debugDrawBorder:!1,displayWidth:0,displayHeight:0};t.default=r});