// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/tsSupport/generatorHelper ../../../../core/tsSupport/awaiterHelper ../../../../core/asyncUtils ../../../../core/maybe ../../../../core/promiseUtils ./Graphics3DGraphic ./Graphics3DObject3DGraphicLayer ./Graphics3DSymbolLayerFactory ./Loadable ./symbolComplexity".split(" "),function(A,B,r,l,m,t,f,u,v,w,x,y,z){return function(n){function b(a,d,c){var e=n.call(this)||this;e._symbol=a;e._context=d;e._backgroundLayers=c;
e._destroyed=!1;e.symbolLayers=[];e.referenced=0;return e}r(b,n);Object.defineProperty(b.prototype,"symbol",{get:function(){return this._symbol},set:function(a){this._symbol=a;if(this.symbolLayers)for(var d=0;d<a.symbolLayers.length;d++){var c=this.symbolLayers[d];f.isNone(c)||(c.symbol=a,c.symbolLayer=a.symbolLayers.items[d])}},enumerable:!0,configurable:!0});b.prototype.doLoad=function(a){return m(this,void 0,void 0,function(){var d,c,e,h,g,b,k=this;return l(this,function(q){switch(q.label){case 0:d=
this._symbol.symbolLayers;this._backgroundLayers&&(d=this._backgroundLayers.concat(d));for(c=d.length;this.symbolLayers.length<d.length;)this.symbolLayers.push(null);this.symbolLayers.length=d.length;e=this._context.layerOrder;h=function(b){var h=d.getItemAt(b);if(!1===h.enabled)return"continue";g._context.layerOrder=e+(1-(1+b)/c);g._context.layerOrderDelta=1/c;var f=x.make(g.symbol,h,g._context,h._ignoreDrivers);u.onAbortOrThrow(a,function(){k.symbolLayers[b]=null;f.destroy()});g.symbolLayers[b]=
f};g=this;for(b=0;b<c;b++)h(b);this._context.layerOrder=e;return[4,t.forEach(this.symbolLayers,function(a,d){return m(k,void 0,void 0,function(){return l(this,function(c){switch(c.label){case 0:if(!f.isSome(a))return[3,4];c.label=1;case 1:return c.trys.push([1,3,,4]),[4,a.load()];case 2:return c.sent(),[3,4];case 3:return c.sent(),this.symbolLayers[d]=null,[3,4];case 4:return[2]}})})})];case 1:q.sent();if(this.symbolLayers.length&&!this.symbolLayers.some(function(a){return!!a}))throw Error();return[2]}})})};
b.prototype.getSymbolLayerSize=function(a){a=this.symbolLayers[a];return f.isSome(a)?a.getCachedSize():null};b.prototype.createGraphics3DGraphic=function(a,d){for(var c=a.graphic,e=Array(this.symbolLayers.length),b=0;b<this.symbolLayers.length;b++){var g=this.symbolLayers[b];e[b]=f.isSome(g)?g.createGraphics3DGraphic(a):null}return new v(c,d||this,e,a.layer,this._context.arcade||this._context.featureExpressionInfoContext&&this._context.featureExpressionInfoContext.arcade&&this._context.featureExpressionInfoContext.arcade.modules||
null)};Object.defineProperty(b.prototype,"complexity",{get:function(){return z.totalSymbolComplexities(this.symbolLayers.map(function(a){return f.isSome(a)&&a.complexity}))},enumerable:!0,configurable:!0});b.prototype.globalPropertyChanged=function(a,d){for(var c=this.symbolLayers.length,e=function(c){var e=b.symbolLayers[c],g=function(a){a=a._graphics[c];return a instanceof w?a:null};if(f.isSome(e)&&!e.globalPropertyChanged(a,d,g))return{value:!1}},b=this,g=0;g<c;g++){var p=e(g);if("object"===typeof p)return p.value}return!0};
b.prototype.applyRendererDiff=function(a,d){return 1!==this.loadStatus?!1:this.symbolLayers.reduce(function(c,e){return c&&(f.isNone(e)||e.applyRendererDiff(a,d))},!0)};b.prototype.prepareSymbolPatch=function(a){if(2!==this.loadStatus&&"partial"===a.diff.type){var d=a.diff.diff;if(d.symbolLayers&&"partial"===d.symbolLayers.type){var c=d.symbolLayers.diff;this.symbolLayers.forEach(function(d,b){var e;if(!f.isNone(d)){var h=c[b];if(h){var k={diff:h,graphics3DGraphicPatches:[],symbolLayerStatePatches:[]};
d.prepareSymbolLayerPatch(k);(e=a.symbolStatePatches).push.apply(e,k.symbolLayerStatePatches);k.graphics3DGraphicPatches.length&&a.graphics3DGraphicPatches.push(function(a,c){var d=a._graphics[b];f.isSome(d)&&k.graphics3DGraphicPatches.forEach(function(a){return a(d,c)})})}}})}}};b.prototype.updateGeometry=function(a,d){for(var c=0;c<this.symbolLayers.length;c++){var e=this.symbolLayers[c];if(!f.isNone(e)){var b=a._graphics[c];if(f.isSome(b)&&!e.updateGeometry(b,d))return!1}}return!0};b.prototype.onRemoveGraphic=
function(a){for(var d=0;d<this.symbolLayers.length;d++){var c=this.symbolLayers[d];if(!f.isNone(c)){var b=a._graphics[d];if(f.isSome(b))c.onRemoveGraphic(b)}}};b.prototype.getFastUpdateStatus=function(){var a=0,d=0,c=0;this.symbolLayers.forEach(function(b){f.isNone(b)||(0===b.loadStatus?a++:b.isFastUpdatesEnabled()?c++:d++)});return{loading:a,slow:d,fast:c}};b.prototype.setDrawOrder=function(a,d){for(var c=this.symbolLayers.length,b=1/c,h=0;h<c;h++){var g=this.symbolLayers[h];f.isSome(g)&&g.setDrawOrder(a+
(1-(1+h)/c),b,d)}};b.prototype.destroy=function(){if(this.destroyed)console.error("Graphics3DSymbol.destroy called when already destroyed!");else{this.abortLoad();for(var a=0,b=this.symbolLayers;a<b.length;a++){var c=b[a];f.isSome(c)&&c.destroy()}this.symbolLayers.length=0;this._destroyed=!0}};Object.defineProperty(b.prototype,"destroyed",{get:function(){return this._destroyed},enumerable:!0,configurable:!0});return b}(y.Loadable)});