// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/tsSupport/generatorHelper ../../../../core/tsSupport/awaiterHelper ../../../../core/tsSupport/assignHelper ../../../../Color ../../../../core/Error ../../../../core/mathUtils ../../../../core/maybe ../../../../core/screenUtils ../../../../core/libs/gl-matrix-2/mat4 ../../../../core/libs/gl-matrix-2/mat4f64 ../../../../core/libs/gl-matrix-2/vec3 ../../../../core/libs/gl-matrix-2/vec3f64 ../../../../core/libs/gl-matrix-2/vec4f32 ../../../../geometry/support/aaBoundingBox ../../../../renderers/support/renderingInfoUtils ./ElevationAligners ./Graphics3DDrapedGraphicLayer ./Graphics3DObject3DGraphicLayer ./Graphics3DSymbolCommonCode ./Graphics3DSymbolLayer ./lineUtils ../support/FastSymbolUpdates ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/Object3D ../../webgl-engine/lib/RenderGeometry ../../webgl-engine/materials/lineStippleUtils ../../webgl-engine/materials/RibbonLineMaterial ../../webgl-engine/shaders/RibbonLineTechnique".split(" "),
function(z,A,H,I,J,K,L,M,N,f,u,B,C,q,x,O,D,P,Q,R,S,g,v,T,E,U,V,W,X,F,e){Object.defineProperty(A,"__esModule",{value:!0});z=function(y){function d(b,a,c,d){b=y.call(this,b,a,c,d)||this;b._lineWidthLOD=1;return b}H(d,y);d.prototype.doLoad=function(){return J(this,void 0,void 0,function(){var b;return I(this,function(a){this._vvConvertOptions={modelSize:[1,1,1],symbolSize:[1,1,1],unitInMeters:1,transformation:{anchor:[0,0,0],scale:[1,1,1],rotation:[0,0,0]},supportedTypes:{size:!0,color:!0,opacity:!0,
rotation:!1}};this._fastUpdates=this._context.renderer&&this._context.renderer.visualVariables&&0<this._context.renderer.visualVariables.length?E.initFastSymbolUpdatesState(this._context.renderer,this._vvConvertOptions):{enabled:!1};if(!this._drivenProperties.size){b=null!=this.symbolLayer.size?this.symbolLayer.size:u.px2pt(1);if(0>b)throw new M("graphics3dlinesymbollayer:invalid-size","Symbol sizes may not be negative values");"round"===this.symbolLayer.join&&(this._lineWidthLOD=1.863798+-2.0062872/
Math.pow(1+b/18.2313,.8856294))}return[2]})})};d.prototype.getMaterialParameters=function(b){var a=this._getCombinedOpacityAndColor(f.get(this.symbolLayer,"material","color"));b={width:1,color:a,polygonOffset:!0,join:this.symbolLayer.join||"miter",cap:this.symbolLayer.cap||"butt",transparent:1>a[3]||this.needsDrivenTransparentPass,slicePlaneEnabled:this._context.slicePlaneEnabled,isClosed:b,stipplePattern:this.symbolLayer.stipplePattern?X.createStipplePattern(this.symbolLayer.stipplePattern.map(u.pt2px)):
null,stippleOffColor:this.symbolLayer.stippleOffColor?L.toUnitRGBA(this.symbolLayer.stippleOffColor):null,stippleIntegerRepeats:!0};this._drivenProperties.size?this._fastUpdates.enabled&&this._fastUpdates.visualVariables.size&&(b.width=u.pt2px(1)):(a=null!=this.symbolLayer.size?this.symbolLayer.size:u.px2pt(1),b.width=u.pt2px(a));return this._fastUpdates&&this._fastUpdates.visualVariables?K({},b,this._fastUpdates.materialParameters):b};Object.defineProperty(d.prototype,"lineMaterial",{get:function(){f.isNone(this._lineMaterial)&&
(this._lineMaterial=new F(this.getMaterialParameters(!1),this._getIdHint("_ribbonlinemat")),this._context.stage.add(3,this._lineMaterial));return this._lineMaterial},enumerable:!0,configurable:!0});Object.defineProperty(d.prototype,"ringMaterial",{get:function(){f.isNone(this._ringMaterial)&&(this._ringMaterial=new F(this.getMaterialParameters(!0),this._getIdHint("_ribbonlinemat")),this._context.stage.add(3,this._ringMaterial));return this._ringMaterial},enumerable:!0,configurable:!0});d.prototype.destroy=
function(){y.prototype.destroy.call(this);f.isSome(this._lineMaterial)&&(this._context.stage.remove(3,this._lineMaterial.id),this._lineMaterial=null);f.isSome(this._ringMaterial)&&(this._context.stage.remove(3,this._ringMaterial.id),this._ringMaterial=null)};d.prototype.setDrawOrder=function(b,a,c){y.prototype.setDrawOrder.call(this,b,a,c);f.isSome(this._lineMaterial)&&(this._lineMaterial.renderPriority=b,c.add(this._lineMaterial.id));f.isSome(this._ringMaterial)&&(this._ringMaterial.renderPriority=
b,c.add(this._ringMaterial.id))};d.prototype.getDrivenSize=function(b){var a=new Float32Array(1);a[0]=this._drivenProperties.size&&b.size?u.pt2px(P.getDriverAxisSizeValue(b.size)):1;return a};d.prototype.getSizeFeatureAttribute=function(b){var a=new Float32Array(1);a[0]=v.getAttributeValue(this._fastUpdates.visualVariables.size.field,b);return a};d.prototype.getDrivenColor=function(b){var a=O.vec4f32.fromValues(1,1,1,1);this._drivenProperties.color&&b.color&&(a[0]=b.color[0],a[1]=b.color[1],a[2]=
b.color[2],0<b.color.length&&(a[3]=b.color[3]));this._drivenProperties.opacity&&b.opacity&&(a[3]=b.opacity);return a};d.prototype.getColorFeatureAttribute=function(b){var a=new Float32Array(1);a[0]=v.getAttributeValue(this._fastUpdates.visualVariables.color.field,b);return a};d.prototype.getOpacityFeatureAttribute=function(b){var a=new Float32Array(1);a[0]=v.getAttributeValue(this._fastUpdates.visualVariables.opacity.field,b);return a};d.prototype.createGraphics3DGraphic=function(b){var a=b.graphic,
c=a.geometry;if(!this._validateGeometryType(a.geometry,d.validGeometryTypes,this.symbolLayer.type)||!this._validateGeometry(c))return null;var c="polygon"===c.type||"extent"===c.type?"rings":"paths",g="graphic"+a.uid,e=this.getGraphicElevationContext(a);return"on-the-ground"===e.mode?this._createAsOverlay(b,c,g,this._context.layer.uid):this._createAs3DShape(b,c,e,g,a.uid)};d.prototype.applyRendererDiff=function(b,a){for(var c in b.diff)switch(c){case "visualVariables":if(E.updateFastSymbolUpdatesState(this._fastUpdates,
a,this._vvConvertOptions))f.isSome(this._lineMaterial)&&this._lineMaterial.setParameterValues(this._fastUpdates.materialParameters),f.isSome(this._ringMaterial)&&this._ringMaterial.setParameterValues(this._fastUpdates.materialParameters);else return!1;break;default:return!1}return!0};d.prototype.layerOpacityChanged=function(){f.isSome(this._lineMaterial)&&this.updateMaterialLayerOpacity(this._lineMaterial);f.isSome(this._ringMaterial)&&this.updateMaterialLayerOpacity(this._ringMaterial);return!0};
d.prototype.updateMaterialLayerOpacity=function(b){var a=b.getParameters().color,c=f.get(this.symbolLayer,"material","color"),c=this._getCombinedOpacity(c);b.setParameterValues({color:[a[0],a[1],a[2],c],transparent:1>c||this.needsDrivenTransparentPass})};d.prototype.layerElevationInfoChanged=function(b,a,c){var e=this._elevationContext.mode;c=g.elevationModeChangeUpdateType(d.elevationModeChangeTypes,c,e);if(c!==g.SymbolUpdateType.UPDATE)return c;var f=g.needsElevationUpdates2D(e);return this.updateGraphics3DGraphicElevationInfo(b,
a,function(){return f})};d.prototype.slicePlaneEnabledChanged=function(){f.isSome(this._lineMaterial)&&this._lineMaterial.setParameterValues({slicePlaneEnabled:this._context.slicePlaneEnabled});f.isSome(this._ringMaterial)&&this._ringMaterial.setParameterValues({slicePlaneEnabled:this._context.slicePlaneEnabled});return!0};d.prototype.physicalBasedRenderingChanged=function(){return!0};d.prototype.pixelRatioChanged=function(){return!0};d.prototype._createAs3DShape=function(b,a,c,d,e){var r=g.getGeometryAsPoly(b.graphic.geometry),
h=r[a],l=[],f=[],k=[],G=x.vec3f64.create(),u=Array(6),r=g.getGeometryVertexData3D(h,r.hasZ,r.spatialReference,this._context.renderSpatialReference,this._context.elevationProvider,this._context.renderCoordsHelper,c,"rings"===a?1:0);this._logGeometryCreationWarnings(r,h,a,"LineSymbol3DLayer");if(0<h.length){for(var h=r.geometryData.outlines,w=r.eleVertexData,m=r.vertexData,t=0;t<h.length;++t){var n=h[t];if(!(1>=n.count)){var p=n.index,q=n.count;if(this._context.clippingExtent&&(g.computeBoundingBox(w,
p,q,u),g.boundingBoxClipped(u,this._context.clippingExtent)))continue;g.applyOrigin(m,p,q,G);n=new Float64Array(w.buffer,3*p*w.BYTES_PER_ELEMENT,3*q);p=new Float64Array(m.buffer,3*p*m.BYTES_PER_ELEMENT,3*q);p=this._createGeometryData(b,p,n,a);p=new U(p,d+"path"+t);p.singleUse=!0;l.push(p);f.push("rings"===a?this.ringMaterial:this.lineMaterial);p=C.mat4f64.create();B.mat4.translate(p,p,G);k.push(p)}}if(0<l.length)return b=new V({geometries:l,materials:f,transformations:k,castShadow:!1,metadata:{layerUid:this._context.layer.uid,
graphicUid:e},idHint:d}),l=new S(this,b,l,null,null,Q.perVertexElevationAligner,c),l.alignedTerrainElevation=r.terrainElevation,l.needsElevationUpdates=g.needsElevationUpdates2D(c.mode),l}return null};d.prototype._createGeometryData=function(b,a,c,d){a=T.createPolylineGeometryData(a,c,"rings"===d?1:0);if("round"===this.symbolLayer.join){c=a.vertexAttributes[e.RibbonVertexAttributeConstants.POSITION].data;d=c.length/3;var g=new Float32Array(d),r=Y,h=Z;q.vec3.set(r,0,0,0);for(var l=-1;l<d;++l){var f=
0>l?d+l:l,k=(l+1)%d;q.vec3.set(h,c[3*k+0]-c[3*f+0],c[3*k+1]-c[3*f+1],c[3*k+2]-c[3*f+2]);q.vec3.normalize(h,h);0<=l&&(f=1*(Math.PI-N.acosClamped(q.vec3.dot(r,h)))*aa*this._lineWidthLOD,g[l]=Math.max(Math.floor(f),0));q.vec3.scale(r,h,-1)}a.vertexAttributes[e.RibbonVertexAttributeConstants.SUBDIVISIONS]={size:1,data:g,offsetIdx:0,strideIdx:1};a.indices[e.RibbonVertexAttributeConstants.SUBDIVISIONS]=a.indices[e.RibbonVertexAttributeConstants.POSITION]}c=new Uint32Array(a.vertexAttributes[e.RibbonVertexAttributeConstants.POSITION].data.length);
a.indices[e.RibbonVertexAttributeConstants.SIZE]=c;this._fastUpdates.enabled&&this._fastUpdates.visualVariables.size?(a.vertexAttributes[e.RibbonVertexAttributeConstants.SIZEFEATUREATTRIBUTE]={size:1,data:this.getSizeFeatureAttribute(b.graphic),offsetIdx:0,strideIdx:1},a.indices[e.RibbonVertexAttributeConstants.SIZEFEATUREATTRIBUTE]=c):(a.vertexAttributes[e.RibbonVertexAttributeConstants.SIZE]={size:1,data:this.getDrivenSize(b.renderingInfo),offsetIdx:0,strideIdx:1},a.indices[e.RibbonVertexAttributeConstants.SIZE]=
c);this._fastUpdates.enabled&&this._fastUpdates.visualVariables.color?(a.vertexAttributes[e.RibbonVertexAttributeConstants.COLORFEATUREATTRIBUTE]={size:1,data:this.getColorFeatureAttribute(b.graphic),offsetIdx:0,strideIdx:1},a.indices[e.RibbonVertexAttributeConstants.COLORFEATUREATTRIBUTE]=c):(a.vertexAttributes[e.RibbonVertexAttributeConstants.COLOR]={size:4,data:this.getDrivenColor(b.renderingInfo),offsetIdx:0,strideIdx:4},a.indices[e.RibbonVertexAttributeConstants.COLOR]=c);this._fastUpdates.enabled&&
this._fastUpdates.visualVariables.opacity&&(a.vertexAttributes[e.RibbonVertexAttributeConstants.OPACITYFEATUREATTRIBUTE]={size:1,data:this.getOpacityFeatureAttribute(b.graphic),offsetIdx:0,strideIdx:1},a.indices[e.RibbonVertexAttributeConstants.OPACITYFEATUREATTRIBUTE]=c);return a};d.prototype._createAsOverlay=function(b,a,c,d){var f=b.graphic,e=g.getGeometryAsPoly(f.geometry),h=e[a],l="rings"===a?this.ringMaterial:this.lineMaterial;l.renderPriority=this._symbolLayerOrder;var q=[],k=Array(6),u=D.empty(),
v=x.vec3f64.create(),e=g.getGeometryVertexDataDraped(h,e.spatialReference,this._context.overlaySR,"rings"===a?1:0);this._logGeometryCreationWarnings(e,h,a,"LineSymbol3DLayer");if(0<h.length){for(var h=e.vertexData,e=e.geometryData.outlines,w=0;w<e.length;++w){var m=e[w],t=m.index,m=m.count;g.computeBoundingBox(h,t,m,k);if(!g.boundingBoxClipped(k,this._context.clippingExtent)){D.expand(u,k);g.applyOrigin(h,t,m,v);g.setZ(h,t,m,this._getDrapedZ());m=new Float64Array(h.buffer,3*t*h.BYTES_PER_ELEMENT,
3*m);t=C.mat4f64.create();B.mat4.translate(t,t,v);var m=this._createGeometryData(b,m,null,a),n=new W(m);n.data.layerUid=d;n.data.graphicUid=f.uid;n.material=l;n.center=[.5*(k[0]+k[3]),.5*(k[1]+k[4]),0];n.bsRadius=.5*Math.sqrt((k[3]-k[0])*(k[3]-k[0])+(k[4]-k[1])*(k[4]-k[1]));n.transformation=t;n.name=c;n.uniqueName=c+"#"+m.id;q.push(n)}}return new R(this,q,u)}return null};d.validGeometryTypes=["polyline","polygon","extent"];d.elevationModeChangeTypes={definedChanged:g.SymbolUpdateType.RECREATE,staysOnTheGround:g.SymbolUpdateType.NONE,
onTheGroundChanged:g.SymbolUpdateType.RECREATE};return d}(v.Graphics3DSymbolLayer);A.Graphics3DLineSymbolLayer=z;var Y=x.vec3f64.create(),Z=x.vec3f64.create(),aa=4/Math.PI;A.default=z});