// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/tsSupport/generatorHelper ../../../../core/tsSupport/awaiterHelper ../../../../core/tsSupport/assignHelper ../../../../core/devEnvironmentUtils ../../../../core/mathUtils ../../../../core/maybe ../../../../core/string ../../../../core/libs/gl-matrix-2/mat3 ../../../../core/libs/gl-matrix-2/mat3f64 ../../../../core/libs/gl-matrix-2/mat4 ../../../../core/libs/gl-matrix-2/mat4f64 ../../../../core/libs/gl-matrix-2/vec3 ../../../../core/libs/gl-matrix-2/vec3f64 ../../../../geometry/support/aaBoundingBox ../../glTF/DefaultLoadingContext ../../glTF/esriProvidedModelParameters ../../glTF/loader ../../glTF/internal/indexUtils ./wosrLoader ../../support/buffer/BufferView ../../support/buffer/math ../../support/buffer/utils ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/GeometryData ../../webgl-engine/lib/Texture ../../webgl-engine/materials/DefaultMaterial ../../webgl-engine/materials/internal/MaterialUtil".split(" "),
function(ja,B,ka,Q,T,E,U,V,e,W,K,X,Y,Z,r,F,G,aa,N,ba,I,ca,u,x,y,da,ea,C,L,fa){function R(c){var f=c.match(/(.*\.(gltf|glb))(\?lod=([0-9]+))?$/);return f?{fileType:"gltf",url:f[1],specifiedLodIndex:null!=f[4]?Number(f[4]):null}:c.match(/(.*\.(json|json\.gz))$/)?{fileType:"wosr",url:c,specifiedLodIndex:null}:{fileType:"unknown",url:c,specifiedLodIndex:null}}function O(c,f,k,l){var z=c.model,n=X.mat3f64.create(),q=[],D=new Map,m=new Map;z.lods.forEach(function(c,r){if(void 0===l||r===l){var F=0,t={name:c.name,
stageResources:{textures:[],materials:[],geometries:[]},lodThreshold:e.isSome(c.lodThreshold)?c.lodThreshold:null,pivotOffset:[0,0,0],numberOfVertices:0,boundingBox:G.empty()};q.push(t);c.parts.forEach(function(b){var l=b.material+(b.attributes.normal?"_normal":"")+(b.attributes.color?"_color":"")+(b.attributes.texCoord0?"_texCoord0":"")+(b.attributes.tangent?"_tangent":""),a=z.materials.get(b.material),v=e.isSome(b.attributes.texCoord0),p=e.isSome(b.attributes.normal);if(!D.has(l)){if(v){if(e.isSome(a.textureColor)&&
!m.has(a.textureColor)){var d=z.textures.get(a.textureColor),g=E({},d.parameters,{preMultiplyAlpha:!0});m.set(a.textureColor,new C(d.data,a.textureColor,g))}e.isSome(a.textureNormal)&&!m.has(a.textureNormal)&&(d=z.textures.get(a.textureNormal),g=E({},d.parameters,{preMultiplyAlpha:!0}),m.set(a.textureNormal,new C(d.data,a.textureNormal,g)));e.isSome(a.textureOcclusion)&&!m.has(a.textureOcclusion)&&(d=z.textures.get(a.textureOcclusion),g=E({},d.parameters,{preMultiplyAlpha:!0}),m.set(a.textureOcclusion,
new C(d.data,a.textureOcclusion,g)));e.isSome(a.textureEmissive)&&!m.has(a.textureEmissive)&&(d=z.textures.get(a.textureEmissive),g=E({},d.parameters,{preMultiplyAlpha:!0}),m.set(a.textureEmissive,new C(d.data,a.textureEmissive,g)));e.isSome(a.textureMetallicRoughness)&&!m.has(a.textureMetallicRoughness)&&(d=z.textures.get(a.textureMetallicRoughness),g=E({},d.parameters,{preMultiplyAlpha:!0}),m.set(a.textureMetallicRoughness,new C(d.data,a.textureMetallicRoughness,g)))}var q=L.COLOR_GAMMA,d=Math.pow(a.color[0],
1/q),g=Math.pow(a.color[1],1/q),w=Math.pow(a.color[2],1/q),h=Math.pow(a.emissiveFactor[0],1/q),r=Math.pow(a.emissiveFactor[1],1/q),q=Math.pow(a.emissiveFactor[2],1/q);D.set(l,new L(E({},f,{transparent:"BLEND"===a.alphaMode,textureAlphaMode:ga(a.alphaMode),textureAlphaCutoff:a.alphaCutoff,diffuse:[d,g,w],ambient:[d,g,w],opacity:a.opacity,doubleSided:a.doubleSided,doubleSidedType:"winding-order",cullFace:a.doubleSided?0:2,vertexColors:!!b.attributes.color,vertexTangents:!!b.attributes.tangent,normals:p?
"default":"screenDerivative",castShadows:!0,receiveSSAO:!0,textureId:e.isSome(a.textureColor)&&v?m.get(a.textureColor).id:void 0,colorMixMode:a.colorMixMode,normalTextureId:e.isSome(a.textureNormal)&&v?m.get(a.textureNormal).id:void 0,textureAlphaPremultiplied:!0,occlusionTextureId:e.isSome(a.textureOcclusion)&&v?m.get(a.textureOcclusion).id:void 0,emissiveTextureId:e.isSome(a.textureEmissive)&&v?m.get(a.textureEmissive).id:void 0,metallicRoughnessTextureId:e.isSome(a.textureMetallicRoughness)&&v?
m.get(a.textureMetallicRoughness).id:void 0,emissiveFactor:[h,r,q],metallicFactor:a.metallicFactor,roughnessFactor:a.roughnessFactor},k),l))}a:{p=b.indices||b.attributes.position.count;switch(b.primitiveType){case 4:d=I.trianglesToTriangles(p);break a;case 5:d=I.triangleStripToTriangles(p);break a;case 6:d=I.triangleFanToTriangles(p);break a}d=void 0}g={};w={};p=b.attributes.position.count;h=y.createBuffer(u.BufferViewVec3f,p);x.vec3.transformMat4(h,b.attributes.position,b.transform);w.position={data:h.typedBuffer,
size:h.elementCount};g.position=d;e.isSome(b.attributes.normal)&&(h=y.createBuffer(u.BufferViewVec3f,p),K.mat3.normalFromMat4(n,b.transform),x.vec3.transformMat3(h,b.attributes.normal,n),w.normal={data:h.typedBuffer,size:h.elementCount},g.normal=d);e.isSome(b.attributes.tangent)&&(h=y.createBuffer(u.BufferViewVec4f,p),K.mat3.normalFromMat4(n,b.transform),x.vec4.transformMat3(h,b.attributes.tangent,n),w.tangent={data:h.typedBuffer,size:h.elementCount},g.tangent=d);e.isSome(b.attributes.texCoord0)&&
(h=y.createBuffer(u.BufferViewVec2f,p),y.vec2.normalizeIntegerBuffer(h,b.attributes.texCoord0),w.uv0={data:h.typedBuffer,size:h.elementCount},g.uv0=d);e.isSome(b.attributes.color)&&(h=y.createBuffer(u.BufferViewVec4u8,p),4===b.attributes.color.elementCount?b.attributes.color instanceof u.BufferViewVec4f?x.vec4.scale(h,b.attributes.color,255):b.attributes.color instanceof u.BufferViewVec4u8?y.vec4.copy(h,b.attributes.color):b.attributes.color instanceof u.BufferViewVec4u16&&x.vec4.scale(h,b.attributes.color,
1/256):(y.vec4.fill(h,255,255,255,255),r=new u.BufferViewVec3u8(h.buffer,0,4),b.attributes.color instanceof u.BufferViewVec3f?x.vec3.scale(r,b.attributes.color,255):b.attributes.color instanceof u.BufferViewVec3u8?y.vec3.copy(r,b.attributes.color):b.attributes.color instanceof u.BufferViewVec3u16&&x.vec3.scale(r,b.attributes.color,1/256)),w.color={data:h.typedBuffer,size:h.elementCount},g.color=d);b=new da(new ea.GeometryData(w,g),"gltf_"+c.name+"_"+F++);t.stageResources.geometries.push(b);t.stageResources.materials.push(D.get(l));
v&&(e.isSome(a.textureColor)&&t.stageResources.textures.push(m.get(a.textureColor)),e.isSome(a.textureNormal)&&t.stageResources.textures.push(m.get(a.textureNormal)),e.isSome(a.textureOcclusion)&&t.stageResources.textures.push(m.get(a.textureOcclusion)),e.isSome(a.textureEmissive)&&t.stageResources.textures.push(m.get(a.textureEmissive)),e.isSome(a.textureMetallicRoughness)&&t.stageResources.textures.push(m.get(a.textureMetallicRoughness)));t.numberOfVertices+=p;l=b.boundingInfo;G.expand(t.boundingBox,
l.getBBMin());G.expand(t.boundingBox,l.getBBMax())})}});return q}function ga(c){switch(c){case "BLEND":return"blend";case "MASK":return"mask";case "OPAQUE":return"opaque";default:return"blend"}}function ha(c){var f=c.model.lods.length;c.meta.isEsriSymbolResource&&c.model.lods.forEach(function(c){if(!e.isSome(c.lodThreshold)){var l=(c.name||"").replace("Imposter","Realistic_LOD0").split("_LOD")[0],k=c.parts.reduce(function(c,f){return c+f.attributes.position.count},0);c.lodThreshold=ia(l,k,f)}})}function ia(c,
f,k){void 0===c&&(c="");if(1===k)return null;if(c in N.lodThresholdLUT){k=N.lodThresholdLUT[c].vertexCounts;c=N.lodThresholdLUT[c].thresholds;var l=k.length;if(1>=l)return null;if(f<=k[0]){var e=(k[1]-k[0])/(c[1]-c[0]);f-=k[0];return Math.max(0,c[0]+f*e)}if(f>=k[l-1])return e=(k[l-1]-k[l-2])/(c[l-1]-c[l-2]),f-=k[l-1],c[l-1]+f*e;for(var n=1;n<k.length;++n){var q=k[n-1],r=k[n],l=c[n-1],e=c[n];if(f<r)return f=(f-q)/(r-q),l*(1-f)+e*f}}return null}Object.defineProperty(B,"__esModule",{value:!0});B.fetch=
function(c,f){void 0===f&&(f={});return T(this,void 0,void 0,function(){var k,l,z,n,q,D,m,x,C,B,t;return Q(this,function(b){switch(b.label){case 0:return k=R(U.adjustStaticAGOUrl(c)),"wosr"!==k.fileType?[3,2]:[4,ca.load(k.url,f)];case 1:return l=b.sent(),[2,{lods:[l],referenceBoundingBox:l.boundingBox,isEsriSymbolResource:!1,isWosr:!0}];case 2:return z=new aa.DefaultLoadingContext(f.streamDataRequester),[4,ba.load(z,k.url,f)];case 3:n=b.sent();a:if(b=n,b.meta.isEsriSymbolResource)for(var G=0,a=b.model.lods;G<
a.length;G++){var v=a[G],p;b:{var d=v.name,g=b.meta.uri;void 0===d&&(d="");void 0===g&&(g="");p=W.endsWith(d,"Imposter");d=d.split("__")[0];if(-1!==g.indexOf("/RealisticTrees/")&&(g=N.treeParamsTable[d])){p={crownCenter:g.center,crownDimensions:g.radius,imposter:p};break b}p=void 0}if(!p)break a;b.customMeta.esriTreeRendering=!0;g=0;for(v=v.parts;g<v.length;g++){var d=v[g],I=d.attributes.normal;if(e.isNone(I))break a;for(var w=d.attributes.position,h=w.count,K=F.vec3f64.create(),L=F.vec3f64.create(),
H=F.vec3f64.create(),M=y.createBuffer(u.BufferViewVec4u8,h),S=y.createBuffer(u.BufferViewVec3f,h),P=Y.mat4.invert(Z.mat4f64.create(),d.transform),Q=r.vec3.transformMat4(F.vec3f64.create(),p.crownCenter,P),P=r.vec3.transformMat4(F.vec3f64.create(),p.crownDimensions,P),A=0;A<h;A++){w.getVec(A,L);I.getVec(A,K);r.vec3.subtract(H,L,Q);r.vec3.divide(H,H,P);var J=V.clamp(r.vec3.length(H),0,1),J=.6+.4*J*J;r.vec3.lerp(H,H,K,.2);S.setVec(A,H);M.set(A,0,255*J);M.set(A,1,255*J);M.set(A,2,255*J);M.set(A,3,255)}d.attributes.normal=
S;d.attributes.color=M}}ha(n);q=n.meta.isEsriSymbolResource?fa.getDefaultPBRMaterialParameters(f.usePBR,n.customMeta.esriTreeRendering):{usePBR:!0};D=E({},f.materialParamsMixin,{treeRendering:n.customMeta.esriTreeRendering});if(null!=k.specifiedLodIndex)return m=O(n,q,D,k.specifiedLodIndex),x=m[0].boundingBox,0!==k.specifiedLodIndex&&(C=O(n,q,D,k.specifiedLodIndex),x=C[0].boundingBox),[2,{lods:m,referenceBoundingBox:x,isEsriSymbolResource:n.meta.isEsriSymbolResource,isWosr:!1}];B=O(n,q,D);t=B[0].boundingBox;
return[2,{lods:B,referenceBoundingBox:t,isEsriSymbolResource:n.meta.isEsriSymbolResource,isWosr:!1}]}})})};B.parseUrl=R;B.gltfToEngineResources=O});