// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
require({cache:{"esri/views/2d/layers/features/tileRenderers/BaseTileRenderer":function(){define("require exports ../../../../../core/tsSupport/declareExtendsHelper ../../../../../core/tsSupport/decorateHelper ../../../../../core/HandleOwner ../../../../../core/accessorSupport/decorators".split(" "),function(l,d,q,a,v,g){Object.defineProperty(d,"__esModule",{value:!0});l=function(d){function e(a){a=d.call(this,a)||this;a.tiles=new Map;return a}q(e,d);e.prototype.destroy=function(){this.tiles.clear();
this.layer=this.layerView=this.tileInfoView=this.tiles=null};Object.defineProperty(e.prototype,"updating",{get:function(){return this.isUpdating()},enumerable:!0,configurable:!0});e.prototype.acquireTile=function(a){var e=this,r=this.createTile(a);r.once("isReady",function(){return e.notifyChange("updating")});this.tiles.set(a.id,r);return r};e.prototype.lockAttributeTextureUpload=function(){};e.prototype.unlockAttributeTextureUpload=function(){};e.prototype.forceAttributeTextureUpload=function(){};
e.prototype.forEachTile=function(a){this.tiles.forEach(a)};e.prototype.releaseTile=function(a){this.tiles.delete(a.key.id);this.disposeTile(a)};e.prototype.isUpdating=function(){var a=!0;this.tiles.forEach(function(e){a=a&&e.isReady});return!a};e.prototype.setHighlight=function(){};e.prototype.invalidateLabels=function(){};e.prototype.requestUpdate=function(){this.layerView.requestUpdate()};a([g.property()],e.prototype,"layer",void 0);a([g.property()],e.prototype,"layerView",void 0);a([g.property()],
e.prototype,"tileInfoView",void 0);a([g.property()],e.prototype,"updating",null);return e=a([g.subclass("esri.views.2d.layers.features.tileRenderers.BaseTileRenderer")],e)}(g.declared(v.HandleOwner));d.default=l})},"esri/views/2d/layers/features/tileRenderers/support/visualVariablesUtils":function(){define("require exports ../../../../../../core/tsSupport/assignHelper ../../../../../../core/screenUtils ../../../../engine ../../../../engine/webgl/definitions ../../../../../3d/layers/support/FastSymbolUpdates".split(" "),
function(l,d,q,a,v,g,p){function e(b){return{value:b.value,size:a.toPt(b.size)}}function r(b){return b.map(function(b){return e(b)})}function t(b){return"string"===typeof b||"number"===typeof b?a.toPt(b):{type:"size",expression:b.expression,stops:r(b.stops)}}function w(b){var a={values:[0,0,0,0,0,0,0,0],opacities:[0,0,0,0,0,0,0,0]};if(v.Utils.isString(b.field))if(b.stops){if(8<b.stops.length)return null;var m=b.stops;for(b=0;8>b;++b){var e=m[Math.min(b,m.length-1)];a.values[b]=e.value;a.opacities[b]=
e.opacity}}else return null;else if(b.stops&&0<=b.stops.length)for(m=b.stops&&0<=b.stops.length&&b.stops[0].opacity,b=0;8>b;b++)a.values[b]=Infinity,a.opacities[b]=m;else return null;return a}Object.defineProperty(d,"__esModule",{value:!0});var x=v.enums.WGLVVFlag;d.getVisualVariableSizeValueRepresentationRatio=function(b,a){if(!b||!a)return b;switch(a){case "radius":case "distance":return 2*b;case "area":return Math.sqrt(b)}return b};d.stopToSizeStop=e;d.normalizeSizeStops=r;d.normalizeSizeElement=
t;d.getVisualVariablesFields=function(b){var a=b&&0<b.length?{}:null;a&&b.forEach(function(b){var m=b.type;b.field&&(a[m]=b.field)});return a};var m=function(b){var m=[],e=[];b=r(b);for(var u=b.length,n=0;6>n;n++){var d=b[Math.min(n,u-1)];m.push(d.value);e.push(null==d.size?g.NAN_MAGIC_NUMBER:a.pt2px(d.size))}return{values:new Float32Array(m),sizes:new Float32Array(e)}};d.convertVisualVariables=function(b){var a=b&&0<b.length?{}:null,e=a?{}:null;if(!a)return{vvFields:a,vvRanges:e};for(var d=0;d<b.length;d++){var n=
b[d],g=n.type;n.field&&(a[g]=n.field);if("size"===g)switch(e.size||(e.size={}),v.getTypeOfSizeVisualVariable(n)){case x.SIZE_MINMAX_VALUE:e.size.minMaxValue={minDataValue:n.minDataValue,maxDataValue:n.maxDataValue,minSize:t(n.minSize),maxSize:t(n.maxSize)};break;case x.SIZE_SCALE_STOPS:e.size.scaleStops={stops:r(n.stops)};break;case x.SIZE_FIELD_STOPS:if(n.levels){var g={},l;for(l in n.levels)g[l]=m(n.levels[l]);e.size.fieldStops={type:"level-dependent",levels:g}}else e.size.fieldStops=q({type:"static"},
m(n.stops));break;case x.SIZE_UNIT_VALUE:e.size.unitValue={unit:n.valueUnit,valueRepresentation:n.valueRepresentation}}else if("color"===g)for(n=p.convertVisualVariables([n],{modelSize:null,symbolSize:null,unitInMeters:1,transformation:null}),e.color=n.color,n=0;32>n;n+=4)v.color.premultiplyAlpha(e.color.colors,n,!0);else"opacity"===g?e.opacity=w(n):"rotation"===g&&(e.rotation={type:n.rotationType})}return{vvFields:a,vvRanges:e}}})},"esri/views/3d/layers/support/FastSymbolUpdates":function(){define("require exports ../../../../core/compilerUtils ../../../../core/mathUtils ../../../../core/libs/gl-matrix-2/mat3 ../../../../core/libs/gl-matrix-2/mat3f64 ../../../../core/libs/gl-matrix-2/mat4 ../../../../core/libs/gl-matrix-2/mat4f64 ../../../../core/libs/gl-matrix-2/vec3 ../../../../core/libs/gl-matrix-2/vec3f64 ../../../../renderers/support/utils ../../support/debugFlags".split(" "),
function(l,d,q,a,v,g,p,e,r,t,w,x){function m(c){return null!==c&&void 0!==c}function b(c){return"number"===typeof c}function y(c){return"string"===typeof c}function k(c,f){c&&c.push(f)}function u(c,f,h,a,e){var z=c.minSize,d=c.maxSize;if(c.expression)return k(e,"Could not convert size info: expression not supported"),!1;if(c.useSymbolValue)return c=a.symbolSize[h],f.minSize[h]=c,f.maxSize[h]=c,f.offset[h]=f.minSize[h],f.factor[h]=0,f.type[h]=1,!0;if(m(c.field)){if(m(c.stops)){if(2===c.stops.length&&
b(c.stops[0].size)&&b(c.stops[1].size))return n(c.stops[0].size,c.stops[1].size,c.stops[0].value,c.stops[1].value,f,h),f.type[h]=1,!0;k(e,"Could not convert size info: stops only supported with 2 elements");return!1}if(b(z)&&b(d)&&m(c.minDataValue)&&m(c.maxDataValue))return n(z,d,c.minDataValue,c.maxDataValue,f,h),f.type[h]=1,!0;if(null!=w.meterIn[c.valueUnit])return f.minSize[h]=-Infinity,f.maxSize[h]=Infinity,f.offset[h]=0,f.factor[h]=1/w.meterIn[c.valueUnit],f.type[h]=1,!0;if("unknown"===c.valueUnit)return k(e,
"Could not convert size info: proportional size not supported"),!1;k(e,"Could not convert size info: scale-dependent size not supported");return!1}if(!m(c.field)){if(c.stops&&c.stops[0]&&b(c.stops[0].size))return f.minSize[h]=c.stops[0].size,f.maxSize[h]=c.stops[0].size,f.offset[h]=f.minSize[h],f.factor[h]=0,f.type[h]=1,!0;if(b(z))return f.minSize[h]=z,f.maxSize[h]=z,f.offset[h]=z,f.factor[h]=0,f.type[h]=1,!0}k(e,"Could not convert size info: unsupported variant of sizeInfo");return!1}function n(c,
f,h,a,b,e){a=0<Math.abs(a-h)?(f-c)/(a-h):0;b.minSize[e]=0<a?c:f;b.maxSize[e]=0<a?f:c;b.offset[e]=c-h*a;b.factor[e]=a}function H(c,f,h,a){if(c.normalizationField||c.valueRepresentation)return k(a,"Could not convert size info: unsupported property"),null;var b=c.field;if(null!=b&&!y(b))return k(a,"Could not convert size info: field is not a string"),null;if(!f.size)f.size={field:c.field,minSize:[0,0,0],maxSize:[0,0,0],offset:[0,0,0],factor:[0,0,0],type:[0,0,0]};else if(c.field)if(!f.size.field)f.size.field=
c.field;else if(c.field!==f.size.field)return k(a,"Could not convert size info: multiple fields in use"),null;switch(c.axis){case "width":return(b=u(c,f.size,0,h,a))?f:null;case "height":return(b=u(c,f.size,2,h,a))?f:null;case "depth":return(b=u(c,f.size,1,h,a))?f:null;case "width-and-depth":return(b=u(c,f.size,0,h,a))&&u(c,f.size,1,h,a),b?f:null;case null:case void 0:case "all":return(b=(b=(b=u(c,f.size,0,h,a))&&u(c,f.size,1,h,a))&&u(c,f.size,2,h,a))?f:null;default:return k(a,'Could not convert size info: unknown axis "'+
c.axis+'""'),null}}function I(c,f,a){for(var b=0;3>b;++b){var h=f.unitInMeters;1===c.type[b]&&(h*=f.modelSize[b],c.type[b]=2);c.minSize[b]/=h;c.maxSize[b]/=h;c.offset[b]/=h;c.factor[b]/=h}if(0!==c.type[0])f=0;else if(0!==c.type[1])f=1;else if(0!==c.type[2])f=2;else return k(a,"No size axis contains a valid size or scale"),!1;for(b=0;3>b;++b)0===c.type[b]&&(c.minSize[b]=c.minSize[f],c.maxSize[b]=c.maxSize[f],c.offset[b]=c.offset[f],c.factor[b]=c.factor[f],c.type[b]=c.type[f]);return!0}function G(c,
f,b){c[4*f+0]=b.r/255;c[4*f+1]=b.g/255;c[4*f+2]=b.b/255;c[4*f+3]=b.a}function J(c,f,b){if(c.normalizationField)return k(b,"Could not convert color info: unsupported property"),null;if(y(c.field))if(c.stops){if(8<c.stops.length)return k(b,"Could not convert color info: too many color stops"),null;f.color={field:c.field,values:[0,0,0,0,0,0,0,0],colors:[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]};b=c.stops;for(c=0;8>c;++c){var a=b[Math.min(c,b.length-1)];f.color.values[c]=a.value;
G(f.color.colors,c,a.color)}}else return k(b,"Could not convert color info: missing stops or colors"),null;else if(c.stops&&0<=c.stops.length)for(b=c.stops&&0<=c.stops.length&&c.stops[0].color,f.color={field:null,values:[0,0,0,0,0,0,0,0],colors:[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},c=0;8>c;c++)f.color.values[c]=Infinity,G(f.color.colors,c,b);else return k(b,"Could not convert color info: no field and no colors/stops"),null;return f}function K(c,b,a){if(c.normalizationField)return k(a,
"Could not convert opacity info: unsupported property"),null;if(y(c.field))if(c.stops){if(8<c.stops.length)return k(a,"Could not convert opacity info: too many opacity stops"),null;b.opacity={field:c.field,values:[0,0,0,0,0,0,0,0],opacityValues:[0,0,0,0,0,0,0,0]};a=c.stops;for(c=0;8>c;++c){var f=a[Math.min(c,a.length-1)];b.opacity.values[c]=f.value;b.opacity.opacityValues[c]=f.opacity}}else return k(a,"Could not convert opacity info: missing stops or opacities"),null;else if(c.stops&&0<=c.stops.length)for(a=
c.stops&&0<=c.stops.length&&c.stops[0].opacity,b.opacity={field:null,values:[0,0,0,0,0,0,0,0],opacityValues:[0,0,0,0,0,0,0,0]},c=0;8>c;c++)b.opacity.values[c]=Infinity,b.opacity.opacityValues[c]=a;else return k(a,"Could not convert opacity info: no field and no opacities/stops"),null;return b}function D(c,b,a){c=2===a&&"arithmetic"===c.rotationType;b.offset[a]=c?90:0;b.factor[a]=c?-1:1;b.type[a]=1}function L(c,b,a){if(!y(c.field))return k(a,"Could not convert rotation info: field is not a string"),
null;if(!b.rotation)b.rotation={field:c.field,offset:[0,0,0],factor:[1,1,1],type:[0,0,0]};else if(c.field)if(!b.rotation.field)b.rotation.field=c.field;else if(c.field!==b.rotation.field)return k(a,"Could not convert rotation info: multiple fields in use"),null;switch(c.axis){case "tilt":return D(c,b.rotation,0),b;case "roll":return D(c,b.rotation,1),b;case null:case void 0:case "heading":return D(c,b.rotation,2),b;default:return k(a,'Could not convert rotation info: unknown axis "'+c.axis+'""'),
null}}function E(c,b,a){if(!c)return null;var f=!b.supportedTypes||!!b.supportedTypes.size,e=!b.supportedTypes||!!b.supportedTypes.color,m=!b.supportedTypes||!!b.supportedTypes.rotation,h=!!b.supportedTypes&&!!b.supportedTypes.opacity,d=c.reduce(function(c,d){if(!c)return c;if(d.valueExpression)return k(a,"Could not convert visual variables: arcade expressions not supported"),null;switch(d.type){case "size":return f?H(d,c,b,a):c;case "color":return e?J(d,c,a):c;case "opacity":return h?K(d,c,a):null;
case "rotation":return m?L(d,c,a):c;default:return q.neverReached(d),null}},{size:null,color:null,opacity:null,rotation:null});return 0<c.length&&d&&!d.size&&!d.color&&!d.opacity&&!d.rotation||d&&d.size&&!I(d.size,b,a)?null:d}function B(c,b,a){if(!!c!==!!b||c&&c.field!==b.field)return!1;if(c&&"rotation"===a)for(a=0;3>a;a++)if(c.type[a]!==b.type[a]||c.offset[a]!==b.offset[a]||c.factor[a]!==b.factor[a])return!1;return!0}function F(c,b){var a={vvSizeEnabled:!1,vvSizeMinSize:null,vvSizeMaxSize:null,vvSizeOffset:null,
vvSizeFactor:null,vvSizeValue:null,vvColorEnabled:!1,vvColorValues:null,vvColorColors:null,vvOpacityEnabled:!1,vvOpacityValues:null,vvOpacityOpacities:null,vvSymbolAnchor:null,vvSymbolRotationMatrix:null},f=c&&null!=c.size;c&&c.size?(a.vvSizeEnabled=!0,a.vvSizeMinSize=c.size.minSize,a.vvSizeMaxSize=c.size.maxSize,a.vvSizeOffset=c.size.offset,a.vvSizeFactor=c.size.factor):c&&f&&(a.vvSizeValue=b.transformation.scale);if(c&&f){a.vvSymbolAnchor=b.transformation.anchor;a.vvSymbolRotationMatrix=g.mat3f64.create();
p.mat4.identity(A);var m=b.transformation.rotation[2],f=b.transformation.rotation[0],d=b.transformation.rotation[1];b=A;void 0===b&&(b=e.mat4f64.create());m=m||0;f=f||0;d=d||0;0!==m&&p.mat4.rotateZ(b,b,-m/180*Math.PI);0!==f&&p.mat4.rotateX(b,b,f/180*Math.PI);0!==d&&p.mat4.rotateY(b,b,d/180*Math.PI);v.mat3.fromMat4(a.vvSymbolRotationMatrix,A)}c&&c.color&&(a.vvColorEnabled=!0,a.vvColorValues=c.color.values,a.vvColorColors=c.color.colors);c&&c.opacity&&(a.vvOpacityEnabled=!0,a.vvOpacityValues=c.opacity.values,
a.vvOpacityOpacities=c.opacity.opacityValues);return a}Object.defineProperty(d,"__esModule",{value:!0});d.convertVisualVariables=E;d.initFastSymbolUpdatesState=function(b,a){return!b||x.DISABLE_FAST_UPDATES?{enabled:!1}:(b=E(b.visualVariables,a))?{enabled:!0,visualVariables:b,materialParameters:F(b,a),requiresShaderTransformation:b&&null!=b.size}:{enabled:!1}};d.updateFastSymbolUpdatesState=function(b,a,e){if(!a||!b.enabled)return!1;var c=b.visualVariables;a=E(a.visualVariables,e);if(!(a&&B(c.size,
a.size,"size")&&B(c.color,a.color,"color")&&B(c.rotation,a.rotation,"rotation")&&B(c.opacity,a.opacity,"opacity")))return!1;b.visualVariables=a;b.materialParameters=F(a,e);b.requiresShaderTransformation=a&&null!=a.size;return!0};d.getMaterialParams=F;var C;(function(b){var c=e.mat4f64.create(),m=t.vec3f64.create();b.evaluateModelTransform=function(b,e,f){if(!b.vvSizeEnabled)return f;p.mat4.copy(c,f);f=b.vvSymbolRotationMatrix;p.mat4.set(A,f[0],f[1],f[2],0,f[3],f[4],f[5],0,f[6],f[7],f[8],0,0,0,0,1);
p.mat4.multiply(c,c,A);for(f=0;3>f;++f)m[f]=a.clamp(b.vvSizeOffset[f]+e[0]*b.vvSizeFactor[f],b.vvSizeMinSize[f],b.vvSizeMaxSize[f]);p.mat4.scale(c,c,m);p.mat4.translate(c,c,b.vvSymbolAnchor);return c};b.evaluateModelTransformScale=function(b,c,e){if(!c.vvSizeEnabled)return r.vec3.set(b,1,1,1);for(var f=0;3>f;++f)b[f]=a.clamp(c.vvSizeOffset[f]+e[0]*c.vvSizeFactor[f],c.vvSizeMinSize[f],c.vvSizeMaxSize[f]);return b}})(C||(C={}));var A=e.mat4f64.create();d.evaluateModelTransform=C.evaluateModelTransform;
d.evaluateModelTransformScale=C.evaluateModelTransformScale})},"esri/core/libs/gl-matrix-2/mat3f64":function(){define(["require","exports","./factories/mat3f64"],function(l,d,q){Object.defineProperty(d,"__esModule",{value:!0});d.mat3f64=q})},"esri/core/libs/gl-matrix-2/factories/mat3f64":function(){define(["require","exports"],function(l,d){Object.defineProperty(d,"__esModule",{value:!0});d.create=function(){return[1,0,0,0,1,0,0,0,1]};d.clone=function(d){return[d[0],d[1],d[2],d[3],d[4],d[5],d[6],
d[7],d[8]]};d.fromValues=function(d,a,l,g,p,e,r,t,w){return[d,a,l,g,p,e,r,t,w]};d.createView=function(d,a){return new Float64Array(d,a,9)}})},"esri/core/libs/gl-matrix-2/mat4f64":function(){define(["require","exports","./factories/mat4f64"],function(l,d,q){Object.defineProperty(d,"__esModule",{value:!0});d.mat4f64=q})},"esri/core/libs/gl-matrix-2/factories/mat4f64":function(){define(["require","exports"],function(l,d){function q(){return[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}Object.defineProperty(d,"__esModule",
{value:!0});d.create=q;d.clone=function(a){return[a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8],a[9],a[10],a[11],a[12],a[13],a[14],a[15]]};d.fromValues=function(a,d,g,p,e,r,l,w,x,m,b,y,k,u,n,q){return[a,d,g,p,e,r,l,w,x,m,b,y,k,u,n,q]};d.createView=function(a,d){return new Float64Array(a,d,16)};d.IDENTITY=q()})},"esri/views/3d/support/debugFlags":function(){define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/Accessor ../../../core/accessorSupport/decorators".split(" "),
function(l,d,q,a,v,g){return new (function(d){function e(){var a=null!==d&&d.apply(this,arguments)||this;a.SCENEVIEW_HITTEST_RETURN_INTERSECTOR=!1;a.SCENEVIEW_LOCKING_LOG=!1;a.HIGHLIGHTS_GRID_OPTIMIZATION_DISABLED=!1;a.HIGHLIGHTS_VISUALIZE_BLOCKS=!1;a.HIGHLIGHTS_PROFILE_TO_CONSOLE=!1;a.DECONFLICTOR_SHOW_OUTLINES=!1;a.DECONFLICTOR_SHOW_OUTLINES_INVISIBLE=!1;a.DECONFLICTOR_SHOW_GRID=!1;a.LABELS_SHOW_BORDER=!1;a.OVERLAY_DRAW_TEST_TEXTURE=!1;a.OVERLAY_SHOW_CENTER=!1;a.TESTS_DISABLE_UPDATE_THRESHOLDS=
!1;a.DISABLE_DECONFLICTOR_VISIBILITY_OFFSET=!1;a.DISABLE_ELEVATION_ALIGNERS_ITERATIVE_UPDATES=!1;a.DRAW_MESH_GEOMETRY_NORMALS=!1;a.FEATURE_TILE_FETCH_SHOW_TILES=!1;a.FEATURE_TILE_TREE_SHOW_TILES=!1;a.TERRAIN_TILE_TREE_SHOW_TILES=!1;a.I3S_TREE_SHOW_TILES=!1;a.ENABLE_PROFILE_DEPTH_RANGE=!1;a.DISABLE_FAST_UPDATES=!1;a.LOD_INSTANCE_RENDERER_DISABLE_UPDATES=!1;a.LOD_INSTANCE_RENDERER_COLORIZE_BY_LEVEL=!1;a.EDGES_SHOW_HIDDEN_TRANSPARENT_EDGES=!1;return a}q(e,d);a([g.property()],e.prototype,"SCENEVIEW_HITTEST_RETURN_INTERSECTOR",
void 0);a([g.property()],e.prototype,"SCENEVIEW_LOCKING_LOG",void 0);a([g.property()],e.prototype,"HIGHLIGHTS_GRID_OPTIMIZATION_DISABLED",void 0);a([g.property()],e.prototype,"HIGHLIGHTS_VISUALIZE_BLOCKS",void 0);a([g.property()],e.prototype,"HIGHLIGHTS_PROFILE_TO_CONSOLE",void 0);a([g.property()],e.prototype,"DECONFLICTOR_SHOW_OUTLINES",void 0);a([g.property()],e.prototype,"DECONFLICTOR_SHOW_OUTLINES_INVISIBLE",void 0);a([g.property()],e.prototype,"DECONFLICTOR_SHOW_GRID",void 0);a([g.property()],
e.prototype,"LABELS_SHOW_BORDER",void 0);a([g.property()],e.prototype,"OVERLAY_DRAW_TEST_TEXTURE",void 0);a([g.property()],e.prototype,"OVERLAY_SHOW_CENTER",void 0);a([g.property()],e.prototype,"TESTS_DISABLE_UPDATE_THRESHOLDS",void 0);a([g.property()],e.prototype,"DISABLE_DECONFLICTOR_VISIBILITY_OFFSET",void 0);a([g.property()],e.prototype,"DISABLE_ELEVATION_ALIGNERS_ITERATIVE_UPDATES",void 0);a([g.property()],e.prototype,"DRAW_MESH_GEOMETRY_NORMALS",void 0);a([g.property()],e.prototype,"FEATURE_TILE_FETCH_SHOW_TILES",
void 0);a([g.property()],e.prototype,"FEATURE_TILE_TREE_SHOW_TILES",void 0);a([g.property()],e.prototype,"TERRAIN_TILE_TREE_SHOW_TILES",void 0);a([g.property()],e.prototype,"I3S_TREE_SHOW_TILES",void 0);a([g.property()],e.prototype,"ENABLE_PROFILE_DEPTH_RANGE",void 0);a([g.property()],e.prototype,"DISABLE_FAST_UPDATES",void 0);a([g.property()],e.prototype,"LOD_INSTANCE_RENDERER_DISABLE_UPDATES",void 0);a([g.property()],e.prototype,"LOD_INSTANCE_RENDERER_COLORIZE_BY_LEVEL",void 0);a([g.property()],
e.prototype,"EDGES_SHOW_HIDDEN_TRANSPARENT_EDGES",void 0);return e=a([g.subclass("esri.views.3d.support.DebugFlags")],e)}(g.declared(v)))})},"esri/views/2d/layers/features/tileRenderers/support/WGLFeatureView":function(){define("require exports ../../../../../../core/tsSupport/assignHelper ../../../../../../core/tsSupport/extendsHelper ../../../../../../core/tsSupport/generatorHelper ../../../../../../core/tsSupport/awaiterHelper ../../../../../../core/promiseUtils ../../../../engine ../../../../engine/FeatureContainer ../../../../engine/webgl/enums".split(" "),
function(l,d,q,a,v,g,p,e,r,t){Object.defineProperty(d,"__esModule",{value:!0});l=function(d){function g(a,b,e){a=d.call(this,a,b.clips)||this;a._pointToCallbacks=new Map;a._layer=e;a._layerView=b;return a}a(g,d);g.prototype.renderChildren=function(a){this.hasAnimation&&a.painter.effects.integrate.draw(a,a.attributeView);d.prototype.renderChildren.call(this,a)};g.prototype.hitTest=function(a,b){a=[a,b];b=p.createResolver();this._pointToCallbacks.set(a,b);this.requestRender();return b.promise};g.prototype.doRender=
function(a){var b=this._layer,e=b.maxScale,m=a.state.scale;m<=(b.minScale||Infinity)&&m>=e&&d.prototype.doRender.call(this,a)};Object.defineProperty(g.prototype,"hasAnimation",{get:function(){return this.hasLabels},enumerable:!0,configurable:!0});Object.defineProperty(g.prototype,"hasLabels",{get:function(){return!(!this._layer.labelingInfo||!this._layer.labelingInfo.length)},enumerable:!0,configurable:!0});Object.defineProperty(g.prototype,"labelsVisible",{get:function(){return this._layer.labelsVisible},
enumerable:!0,configurable:!0});g.prototype.prepareRenderPasses=function(a){var b=this,m=a.registerRenderPass({name:"label",brushes:[e.brushes.Label],target:function(){return b._layer.labelsVisible?b.children:null},drawPhase:t.WGLDrawPhase.LABEL|t.WGLDrawPhase.LABEL_ALPHA}),g=a.registerRenderPass({name:"geometry",brushes:[e.brushes.Fill,e.brushes.Line,e.brushes.Marker,e.brushes.Text],target:function(){return b.children},effects:[{apply:a.effects.highlight,enable:function(){return!!b._layerView.hasHighlight()}},
{apply:a.effects.hittest,enable:function(){return!!b._pointToCallbacks.size},args:function(){return b._pointToCallbacks}}]});return d.prototype.prepareRenderPasses.call(this,a).concat([g,m])};return g}(r.FeatureContainer);d.WGLFeatureView=l})},"esri/views/2d/engine/FeatureContainer":function(){define("require exports ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../../../core/tsSupport/extendsHelper ../../../core/tsSupport/assignHelper ../../../core/promiseUtils ../../../core/promiseUtils ../../../geometry/support/aaBoundingRect ../engine".split(" "),
function(l,d,q,a,v,g,p,e,r,t){Object.defineProperty(d,"__esModule",{value:!0});l=function(d){function l(a,b){a=d.call(this,a,b)||this;a._rendererInfo=new t.WGLRendererInfo;a.attributeView=new t.AttributeStoreView;return a}v(l,d);l.prototype.destroy=function(){this.removeAllChildren();this.children.forEach(function(a){return a.destroy()});this.attributeView.destroy()};l.prototype.whenAttached=function(){var a=this;return this.attached?p.resolve():p.create(function(b){return a.once("attached",function(){return b()})})};
l.prototype.setRendererInfo=function(a,b,d){this._rendererInfo.setInfo(a,b,d);this.requestRender()};l.prototype.getMaterialItems=function(d,b){return a(this,void 0,void 0,function(){var a,g,m,n;return q(this,function(u){switch(u.label){case 0:return d&&0!==d.length?[4,this.whenAttached()]:[2,null];case 1:return u.sent(),a=this.stage.painter.textureManager,g=d.map(function(d){return a.rasterizeItem(d.symbol,d.glyphIds,b)}),[4,e.all(g)];case 2:return m=u.sent(),n=m.map(function(a,b){return{id:d[b].id,
mosaicItem:a}}),[2,n]}})})};l.prototype.onTileData=function(a,b){if(!(b.addOrUpdate&&"tileDisplayData"in b.addOrUpdate)){var d=b.addOrUpdate&&t.TileData.decode(b.addOrUpdate);b=g({},b,{addOrUpdate:d})}a.setData(b,this.hasLabels,this.labelsVisible);this.contains(a)||this.addChild(a);this.requestRender()};l.prototype.onTileError=function(a){a.clear();this.contains(a)||this.addChild(a)};l.prototype.renderChildren=function(a){this._rendererInfo.update(a.state);this.attributeView.bindTextures(this.stage.context);
d.prototype.renderChildren.call(this,a)};l.prototype.createTile=function(a){var b=this._tileInfoView.getTileBounds(r.create(),a);return new t.WGLTile(a,b)};l.prototype.destroyTile=function(a){this.removeChild(a);a.destroy()};l.prototype.attach=function(){this._initializeExtensions();return d.prototype.attach.call(this)};l.prototype.createRenderParams=function(a){return g({},d.prototype.createRenderParams.call(this,a),{rendererInfo:this._rendererInfo,attributeView:this.attributeView})};l.prototype._initializeExtensions=
function(){var a=this.stage.context.capabilities;a.textureFloat;a.vao};return l}(t.TileContainer);d.FeatureContainer=l})},"*noref":1}});
define("require exports ../../../../../core/tsSupport/declareExtendsHelper ../../../../../core/tsSupport/decorateHelper ../../../../../core/tsSupport/assignHelper ../../../../../core/tsSupport/generatorHelper ../../../../../core/tsSupport/awaiterHelper ../../../../../core/accessorSupport/decorators ../../../../../geometry/support/aaBoundingRect ../../../engine ../support/rendererUtils ./BaseTileRenderer ./support/visualVariablesUtils ./support/WGLFeatureView".split(" "),function(l,d,q,a,v,g,p,e,r,
t,w,x,m,b){Object.defineProperty(d,"__esModule",{value:!0});l=function(d){function k(){return null!==d&&d.apply(this,arguments)||this}q(k,d);k.prototype.install=function(a){var d=new b.WGLFeatureView(this.tileInfoView,this.layerView,this.layer);this.featuresView=d;a.addChild(d)};k.prototype.uninstall=function(a){a.removeChild(this.featuresView);this.featuresView.destroy()};k.prototype.hitTest=function(a,b){return this.featuresView.hitTest(a,b)};k.prototype.supportsRenderer=function(a){return null!=
a&&-1!==["simple","class-breaks","unique-value","dot-density","dictionary"].indexOf(a.type)};k.prototype.onConfigUpdate=function(a,b){b=null;"visualVariables"in a&&(b=(w.simplifyVVRenderer(a).visualVariables||[]).map(function(a){var b=a.clone();"normalizationField"in a&&(b.normalizationField=null);a.valueExpression&&"$view.scale"!==a.valueExpression&&(b.valueExpression=null,b.field="nop");return b}),b=m.convertVisualVariables(b));this.featuresView.setRendererInfo(a,b,this.layerView.effects);this.featuresView.setClips(this.layerView.clips)};
k.prototype.onTileData=function(a){var b=this.tiles.get(a.tileKey);if(b)this.featuresView.onTileData(b,a.data);this.layerView.view.labelManager.requestUpdate()};k.prototype.onTileError=function(a){if(a=this.tiles.get(a.tileKey))this.featuresView.onTileError(a)};k.prototype.forceAttributeTextureUpload=function(){this.featuresView.attributeView.forceTextureUpload()};k.prototype.lockAttributeTextureUpload=function(){this.featuresView.attributeView.lockTextureUpload()};k.prototype.unlockAttributeTextureUpload=
function(){this.featuresView.attributeView.unlockTextureUpload()};k.prototype.getMaterialItems=function(a){return p(this,void 0,void 0,function(){return g(this,function(b){return[2,this.featuresView.getMaterialItems(a)]})})};k.prototype.invalidateLabels=function(){this.layer.labelingInfo&&this.layer.labelsVisible&&(this.tiles.forEach(function(a){return a.isDirty=!0}),this.layerView.view.labelManager.requestUpdate())};k.prototype.createTile=function(a){var b=this.tileInfoView.getTileBounds(r.create(),
a);a=new t.WGLTile(a,b);this.layer.labelingInfo&&this.layerView.view.labelManager.addTile(this.layerView,a);return a};k.prototype.disposeTile=function(a){this.featuresView.removeChild(a);this.layer.labelingInfo&&this.layerView.view.labelManager.removeTile(this.layerView,a.key.id);a.destroy();this.layerView.view.labelManager.requestUpdate()};return k=a([e.subclass("esri.views.2d.layers.features.tileRenderers.SymbolTileRenderer")],k)}(e.declared(x.default));d.default=l});