// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/domUtils ../../core/accessorSupport/decorators ../Widget ./widget".split(" "),function(y,z,v,c,q,b,w,f){var x="bottom bottom-start bottom-end left left-start left-end right right-start right-end top top-start top-end".split(" "),t={position:"absolute",top:"-9999px",left:9999*(f.isRTL()?1:-1)+"px","z-index":""};return function(u){function a(a){var h=u.call(this,a)||this;h.anchorElement=
null;h.open=!1;h.renderContentFunction=null;h._afterRootCreate=function(a){h._rootNode=a;h._updatePosition(a)};h._updatePosition=function(a){var d=h.renderContentFunction;if(h.open&&d){var g=h._getAnchor();if(g){var d=h.placement,e=g.getBoundingClientRect(),g=e.left,b=e.height,c=e.width,e=e.top,k=a.firstElementChild,p=getComputedStyle(k),n=parseInt(p.marginTop,10)+parseInt(p.marginBottom,10),p=parseInt(p.marginLeft,10)+parseInt(p.marginRight,10),n=k.offsetHeight+n,k=k.offsetWidth+p,f=document.scrollingElement||
document.documentElement,p=f.scrollLeft,f=f.scrollTop,r=document.documentElement,q=r.offsetHeight,r=r.offsetWidth,l,m;-1<d.indexOf("top")&&(m=e-n,l="top-start"===d?g:"top-end"===d?g+c-k:g+c/2-k/2);-1<d.indexOf("bottom")&&(m=e+b,l="bottom-start"===d?g:"bottom-end"===d?g+c-k:g+c/2-k/2);-1<d.indexOf("left")&&(l=g-k,m="left-start"===d?e:"left-end"===d?e+b-n:e+b/2-n/2);-1<d.indexOf("right")&&(l=g+c,m="right-start"===d?e:"right-end"===d?e+b-n:e+b/2-n/2);0>l?l=g:l+k>r&&(l-=l+k-r);0>m?m=e+b:m+n>q&&(m-=m+
n-q);a.style.top=m+f+"px";a.style.left=l+p+"px";a.style.zIndex="1000"}}else a.style.top=t.top,a.style.left=t.left,a.style.zIndex=t["z-index"]};return h}v(a,u);a.prototype.initialize=function(){this._projector.append(document.body,this.render)};a.prototype.destroy=function(){this.renderContentFunction=this.anchorElement=this.owner=null;this._projector.detach(this.render);q.remove(this._rootNode)};Object.defineProperty(a.prototype,"container",{set:function(a){},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,
"owner",{set:function(a){this._set("owner",a)},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"placement",{get:function(){return"top"},set:function(a){-1===x.indexOf(a)?this._clearOverride("placement"):this._override("placement",a)},enumerable:!0,configurable:!0});a.prototype.render=function(){var a=this.open,b=this.owner,c=this.renderContentFunction;return f.tsx("div",{class:this.classes("esri-popover",a?"esri-popover--open":null),styles:t,afterCreate:this._afterRootCreate,afterUpdate:this._updatePosition},
a&&c&&c.call(b))};a.prototype._getAnchor=function(){var a=this.anchorElement;return q.byId("function"===typeof a?a():a)};c([b.property(),f.renderable()],a.prototype,"anchorElement",void 0);c([b.property()],a.prototype,"container",null);c([b.property(),f.renderable()],a.prototype,"open",void 0);c([b.property(),f.renderable()],a.prototype,"owner",null);c([b.property(),f.renderable()],a.prototype,"placement",null);c([b.property(),f.renderable()],a.prototype,"renderContentFunction",void 0);return a=c([b.subclass("esri.widgets.support.Popover")],
a)}(b.declared(w))});