// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/assignHelper ../../../../core/tsSupport/declareExtendsHelper ../../../../core/tsSupport/decorateHelper ../../../../core/tsSupport/generatorHelper ../../../../core/tsSupport/awaiterHelper ../../../../geometry ../../../../core/arrayUtils ../../../../core/Error ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/watchUtils ../../../../core/accessorSupport/decorators ../../../../geometry/support/quantizationUtils ../../../../geometry/support/spatialReferenceUtils ../../../../layers/support/arcgisLayerUrl ../../../../layers/support/fieldUtils ../../statistics/support/predominanceUtils ../../statistics/support/utils ../utils ./LayerAdapter ./support/utils ../../../../tasks/GenerateRendererTask ../../../../tasks/support/GenerateRendererParameters ../../../../tasks/support/QuantizationParameters ../../../../tasks/support/Query ../../../../tasks/support/StatisticDefinition ../../../../tasks/support/UniqueValueDefinition".split(" "),
function(Y,Z,x,N,I,y,v,O,J,r,P,n,A,C,K,L,Q,B,D,p,R,S,l,T,E,U,V,F,W){return function(M){function f(a){return M.call(this,a)||this}N(f,M);f.prototype.destroy=function(){this._hasLocalSource=null};f.prototype._isStatsSupportedOnService=function(){var a=this.layer;return!a.get("capabilities.query.supportsStatistics")||"multipatch"===this.geometryType&&!Q.isHostedAgolService(a.url)&&10.5>a.version?n.reject(new r("feature-layer-adapter:not-supported","Layer does not support statistics query")):n.resolve()};
f.prototype._fetchFeaturesFromMemory=function(a,c){var b=this.layer;return this._hasLocalSource?n.resolve(b.source):a?a.whenLayerView(b).then(function(a){var b=A.whenFalseOnce(a,"updating").then(function(){return a.queryFeatures(c)}).then(function(a){return a.features});return n.timeout(b,1E4,null)}):n.reject(new r("feature-layer-adapter:insufficient-data","view is required to fetch the features from layerView"))};f.prototype._fetchFeaturesFromService=function(a){return this.layer.queryFeatures(a).then(function(a){return a&&
a.features})};f.prototype._fetchFeaturesForStats=function(a){var c=this;return R.getFieldsList({field:a.field,normalizationField:a.normalizationField,valueExpression:a.valueExpression}).then(function(b){return c.getSampleFeatures({sampleSize:-1,view:a.view,requiredFields:b})})};f.prototype._summaryStatsFromGenRend=function(a){var c=a.normalizationType,b=a.normalizationField;return this.classBreaks({field:a.field,numClasses:5,classificationMethod:"standard-deviation",standardDeviationInterval:.25,
normalizationType:c,normalizationField:"field"===c?b:void 0,minValue:a.minValue,maxValue:a.maxValue}).then(function(a){var b,c,e;a.classBreakInfos.some(function(a){a.hasAvg&&(b=a);return!!b});b&&(e=b.maxValue-b.minValue,c=b.minValue+e/2,e*=4);return l.processSummaryStatisticsResult({min:a.minValue,max:a.maxValue,avg:c,stddev:e})})};f.prototype._getSummaryStatsQuery=function(a,c){var b=a.field,e=a.normalizationType,g=a.normalizationField,d=a.normalizationTotal;c=this.supportsSQLExpression&&c?l.msSinceUnixEpochSQL(this,
b):a.sqlExpression;var d=l.getFieldExpr({field:b,normalizationType:e,normalizationField:g,normalizationTotal:d}),h=c||d,d=h?p.getRangeExpr(h,a.minValue,a.maxValue):null,b=p.getSQLFilterForNormalization({field:b,normalizationField:g,normalizationType:e});a=p.mergeWhereClauses(a.sqlWhere,b);a=p.mergeWhereClauses(a,d);b=this.layer.createQuery();b.where=p.mergeWhereClauses(b.where,a);b.sqlFormat=c?"standard":null;b.outStatistics=l.statisticTypes.map(function(a){var b=new F;b.statisticType="variance"===
a?"var":a;b.onStatisticField=h;b.outStatisticFieldName=a+"_value";return b});return b};f.prototype._summaryStatsFromServiceQuery=function(a,c){return v(this,void 0,void 0,function(){var b,e,g,d;return y(this,function(h){switch(h.label){case 0:return[4,this._isStatsSupportedOnService()];case 1:h.sent();if("percent-of-total"!==a.normalizationType)return[3,3];b=a;return[4,this._getNormalizationTotal(a.field,a.normalizationType)];case 2:b.normalizationTotal=h.sent(),h.label=3;case 3:return e=this._getSummaryStatsQuery(a,
c),[4,this.layer.queryFeatures(e)];case 4:return g=h.sent(),d=l.getSummaryStatisticsFromFeatureSet(g,c),[2,l.processSummaryStatisticsResult(d)]}})})};f.prototype._summaryStatsFromClientQuery=function(a,c){var b=this,e=a.view;return e?e.whenLayerView(this.layer).then(function(e){var d=A.whenFalseOnce(e,"updating").then(function(){return e.queryFeaturesJSON(b._getSummaryStatsQuery(a,c))}).then(function(a){return l.getSummaryStatisticsFromFeatureSet(a,c)}).then(l.processSummaryStatisticsResult);n.timeout(d,
1E4,null);return d}):n.reject(new r("feature-layer-adapter:insufficient-data","view is required to query stats from layerView"))};f.prototype._summaryStatsFromMemory=function(a,c){return v(this,void 0,void 0,function(){var b,e,g,d,h,k,f,m,w,u,q;return y(this,function(t){switch(t.label){case 0:return b=a.field,e=a.valueExpression,g=a.view,d={field:b,valueExpression:e,normalizationField:a.normalizationField,view:g},(k=a.features)?[3,2]:[4,this._fetchFeaturesForStats(d)];case 1:k=t.sent(),t.label=2;
case 2:f=(h=k)&&h.length;if(!f)throw new r("feature-layer-adapter:insufficient-data","No features are available to calculate statistics");m=x({},a);return"percent-of-total"!==m.normalizationType?[3,4]:[4,l.calculateStatsFromMemory({field:b},h)];case 3:w=t.sent();u=w.sum;if(null==u)throw new r("feature-layer-adapter:invalid","invalid normalizationTotal");m.normalizationTotal=u;t.label=4;case 4:return[4,l.calculateStatsFromMemory(m,h,c)];case 5:return q=t.sent(),[2,l.processSummaryStatisticsResult(q)]}})})};
f.prototype._uvFromGenRenderer=function(a,c){var b=this,e=a.field,g=new W;g.attributeField=e;var d=new E;d.classificationDefinition=g;return this.generateRenderer(d).then(function(a){var c={},d=b.getField(e);a.uniqueValues.forEach(function(a){var b=a.value;if(null==b||""===b||"string"===typeof b&&(""===b.trim()||"\x3cnull\x3e"===b.toLowerCase()))b=null;null==c[b]?c[b]={count:a.count,data:B.isNumericField(d)&&b?Number(b):b}:c[b].count+=a.count});return{count:c}}).then(function(b){return l.createUVResult(b,
c,a.returnAllCodedValues)})};f.prototype._getUVQuery=function(a){var c=a.field,b=a.sqlExpression,e="countOF"+(c||"Expr"),g=new F;g.statisticType="count";g.onStatisticField=b?"1":c;g.outStatisticFieldName=e;e=this.layer.createQuery();e.where=p.mergeWhereClauses(e.where,a.sqlWhere);e.sqlFormat=b?"standard":null;e.outStatistics=[g];e.groupByFieldsForStatistics=[c||b];return e};f.prototype._uvFromServiceQuery=function(a,c){var b=this;return this._isStatsSupportedOnService().then(function(){return b.layer.queryFeatures(b._getUVQuery(a))}).then(function(c){return l.getUniqueValuesFromFeatureSet(c,
b,a.field)}).then(function(b){return l.createUVResult(b,c,a.returnAllCodedValues)})};f.prototype._uvFromClientQuery=function(a,c){var b=this,e=a.view;return e?e.whenLayerView(this.layer).then(function(e){var d=A.whenFalseOnce(e,"updating").then(function(){return e.queryFeaturesJSON(b._getUVQuery(a))}).then(function(c){return l.getUniqueValuesFromFeatureSet(c,b,a.field)}).then(function(b){return l.createUVResult(b,c,a.returnAllCodedValues)});n.timeout(d,1E4,null);return d}):n.reject(new r("feature-layer-adapter:insufficient-data",
"view is required to query stats from layerView"))};f.prototype._uvFromMemory=function(a,c){var b={field:a.field,valueExpression:a.valueExpression,view:a.view};return(a.features?n.resolve(a.features):this._fetchFeaturesForStats(b)).then(function(b){return l.calculateUniqueValuesFromMemory(a,b,c)})};f.prototype._calcBinsSQL=function(a,c){var b=[],e=c.length;c.forEach(function(c,d){c=p.mergeWhereClauses(a+" \x3e\x3d "+c[0],a+(d===e-1?" \x3c\x3d ":" \x3c ")+c[1]);b.push("WHEN ("+c+") THEN "+(d+1))});
return["CASE",b.join(" "),"ELSE 0 END"].join(" ")};f.prototype._getNormalizationTotal=function(a,c){return a&&"percent-of-total"===c?this.summaryStatistics({field:a}).then(function(a){return a.sum}):n.resolve(null)};f.prototype._getQueryParamsForExpr=function(a,c){if(!a.valueExpression&&!a.sqlExpression){var b=a.field,e=b?this.getField(b):null,e=B.isDateField(e);c={field:b,normalizationType:a.normalizationType,normalizationField:a.normalizationField,normalizationTotal:c};return{sqlExpression:e?l.msSinceUnixEpochSQL(this,
b):l.getFieldExpr(c),sqlWhere:e?null:a.sqlWhere||p.getSQLFilterForNormalization(a)}}return{valueExpression:a.valueExpression,sqlExpression:a.sqlExpression,sqlWhere:a.sqlWhere}};f.prototype._getDataRange=function(a,c,b){return null!=c&&null!=b?n.resolve({min:c,max:b}):this.summaryStatistics(a).then(function(a){return{min:a.min,max:a.max}})};f.prototype._histogramForExpr=function(a){var c=this;return this._getNormalizationTotal(a.field,a.normalizationType).then(function(b){var e=c._getQueryParamsForExpr(a,
b);return c._getDataRange(e,a.minValue,a.maxValue).then(function(g){var d=g.min,h=g.max,k=a.numBins||10;g=l.getEqualIntervalBins(d,h,k);g=c._calcBinsSQL(e.sqlExpression,g);var f=new F({statisticType:"count",outStatisticFieldName:"countOFExpr",onStatisticField:"1"}),m=c.layer.createQuery();m.where=p.mergeWhereClauses(m.where,e.sqlWhere);m.sqlFormat="standard";m.outStatistics=[f];m.groupByFieldsForStatistics=[g];m.orderByFields=[g];return c._isStatsSupportedOnService().then(function(){return c.layer.queryFeatures(m)}).then(function(a){return l.getHistogramFromFeatureSet(a,
d,h,k,b)})})})};f.prototype._histogramForField=function(a){var c=this,b=null,b=null!=a.minValue&&null!=a.maxValue?n.resolve({min:a.minValue,max:a.maxValue}):this.summaryStatistics(a).then(function(a){if(!a.count)throw new r("feature-layer-adapter:insufficient-data","Either the layer has no features or none of the features have data for the field");return{min:a.min,max:a.max}});return b.then(function(b){return c._getBins({min:b.min,max:b.max},a.field,a.numBins)})};f.prototype._getBins=function(a,c,
b){void 0===b&&(b=10);var e=a.min,g=a.max,d=a.normTotal,h=a.excludeZerosExpr,k=a.intervals||l.getEqualIntervalBins(e,g,b);return this._queryBins(k,a.sqlExpr||c,h).then(function(a){return{bins:a.map(function(a,b){return{minValue:k[b][0],maxValue:k[b][1],count:a.value}}),minValue:e,maxValue:g,normalizationTotal:d}})};f.prototype._queryBins=function(a,c,b){for(var e=this,g=[],d=a.length,h=0;h<d;h++){var k=p.mergeWhereClauses(b,p.mergeWhereClauses(c+" \x3e\x3d "+a[h][0],null!==a[h][1]?c+(h===d-1?" \x3c\x3d ":
" \x3c ")+a[h][1]:""));g.push(k)}return n.eachAlways(g.map(function(a){return e.queryFeatureCount(a)}))};f.prototype._binParamsFromGenRend=function(a,c){var b=a.field,e=a.normalizationType,g=a.normalizationField,d=p.getSQLFilterForNormalization({field:b,normalizationType:e,normalizationField:g});a=new E({classificationDefinition:l.createCBDefn({field:b,normalizationType:e,normalizationField:g,classificationMethod:a.classificationMethod,standardDeviationInterval:a.standardDeviationInterval,breakCount:a.numBins||
10}),where:p.mergeWhereClauses(d,c)});return this.generateRenderer(a).then(function(a){return l.generateBinParams({field:b,normalizationType:e,normalizationField:g,normalizationTotal:a.normalizationTotal,classBreaks:a.classBreaks,where:d})})};f.prototype._histogramFromMemory=function(a){var c=this,b=a.field,e=a.normalizationType,g=a.valueExpression,d=a.classificationMethod,h=a.minValue,k=a.maxValue,f=a.view,m={field:b,valueExpression:g,normalizationField:a.normalizationField,view:f};return(a.features?
n.resolve(a.features):this._fetchFeaturesForStats(m)).then(function(m){if(!m||!m.length)throw new r("feature-layer-adapter:insufficient-data","No features are available to calculate histogram");var t=null!=h&&null!=k,q=null;d&&"equal-interval"!==d||e?(t=x({},a),t.features=m,q=c._getBinParamsFromMemory(t)):q=t?n.resolve({min:h,max:k,source:"parameters"}):c.summaryStatistics({field:b,valueExpression:g,features:m,view:f}).then(function(a){return a.count?{min:a.min,max:a.max}:n.reject(new r("feature-layer-adapter:insufficient-data",
"No features are available to calculate histogram"))});return q.then(function(b){return l.calculateHistogramFromMemory(a,b,m)})})};f.prototype._getBinParamsFromMemory=function(a){return v(this,void 0,void 0,function(){var c,b,e,g,d,h,f,t,m,n;return y(this,function(k){c=a.field;b=a.valueExpression;e=a.classificationMethod;g=a.standardDeviationInterval;d=a.normalizationType;h=a.normalizationField;f=a.minValue;t=a.maxValue;m=a.features;n=a.view;return[2,this._classBreaksFromMemory({field:c,valueExpression:b,
normalizationType:d,normalizationField:h,classificationMethod:e,standardDeviationInterval:g,minValue:f,maxValue:t,numClasses:a.numBins,features:m,view:n}).then(function(a){var b=a.normalizationTotal;a=a.classBreakInfos;var e=p.getSQLFilterForNormalization({field:c,normalizationType:d,normalizationField:h});return l.generateBinParams({field:c,normalizationType:d,normalizationField:h,normalizationTotal:b,classBreaks:a,where:e})})]})})};f.prototype._classBreaksFromGenRend=function(a){var c=a.field,b=
a.normalizationType,e=a.normalizationField,g=a.normalizationTotal,d=p.getSQLFilterForNormalization({field:c,normalizationType:b,normalizationField:e}),g=l.getFieldExpr({field:c,normalizationType:b,normalizationField:e,normalizationTotal:g}),g=p.getRangeExpr(g,a.minValue,a.maxValue),c=l.createCBDefn({field:c,normalizationType:b,normalizationField:e,classificationMethod:a.classificationMethod,standardDeviationInterval:a.standardDeviationInterval,breakCount:a.numClasses||5}),b=new E;b.classificationDefinition=
c;b.where=p.mergeWhereClauses(d,g);return this.generateRenderer(b).then(function(b){return l.resolveCBResult(a,b)})};f.prototype._classBreaksFromInterpolation=function(a){for(var c=a.minValue,b=a.maxValue,e=a.numClasses||5,g=[],d=(b-c)/e,h=0;h<e;h++){var f=c+h*d;g.push({minValue:f,maxValue:f+d})}g[e-1].maxValue=b;a=l.resolveCBResult(a,{classBreaks:g,normalizationTotal:a.normalizationTotal});return n.resolve(a)};f.prototype._classBreaksFromMemory=function(a){return v(this,void 0,void 0,function(){var c,
b,e,g,d,h,f,t,m,n,u;return y(this,function(k){switch(k.label){case 0:return c=a.field,b=a.normalizationField,e=a.valueExpression,g=a.view,d={field:c,valueExpression:e,normalizationField:b,view:g},(f=a.features)?[3,2]:[4,this._fetchFeaturesForStats(d)];case 1:f=k.sent(),k.label=2;case 2:t=(h=f)&&h.length;if(!t)throw new r("feature-layer-adapter:insufficient-data","No features are available to calculate statistics");m=x({},a);return"percent-of-total"!==m.normalizationType?[3,4]:[4,l.calculateStatsFromMemory({field:c},
h)];case 3:n=k.sent();u=n.sum;if(null==u)throw new r("feature-layer-adapter:invalid","invalid normalizationTotal");m.normalizationTotal=u;k.label=4;case 4:return[2,l.calculateClassBreaksFromMemory(m,h)]}})})};f.prototype._heatmapStatsFromMemory=function(a,c){var b=this,e=a.blurRadius,g=a.field,d=a.view,h=d.state,f=h.size,t=new U.default({extent:d.extent,tolerance:h.resolution}),h=new V({returnGeometry:!0,geometry:d.extent,quantizationParameters:t});return(a.features?n.resolve(a.features):this._fetchFeaturesFromMemory(d,
h)).then(function(a){a=b._quantizeFeatures(a,t,d);if(!a||!a.length)return{count:0,min:null,max:null,avg:null,stddev:null};if(a=l.calculateHeatmapStats(a,e,c,g,f[0],f[1]))return{count:a.count,min:a.min,max:a.max,avg:a.mean,stddev:a.stdDev};throw new r("feature-layer-adapter:invalid","unable to calculate heatmap statistics");})};f.prototype._quantizeFeatures=function(a,c,b){var e=this,g=K.toQuantizationTransform(c);c=b.spatialReference;var d=b.size,f=L.isWrappable(c);b=L.getInfo(c);var k=Math.round((b.valid[1]-
b.valid[0])/g.scale[0]);return a.map(function(a){var b=new O.Point(P.unwrap(a.geometry));K.quantizePoint(g,b,b,b.hasZ,b.hasM);a.geometry=f?e._wrapPoint(b,k,d[0]):b;return a})};f.prototype._wrapPoint=function(a,c,b){0>a.x?a.x+=c:a.x>b&&(a.x-=c);return a};f.prototype.getField=function(a){void 0===a&&(a="");return this.layer.getField(a)};f.prototype.getFieldUsageInfo=function(a){return this.getField(a)?{supportsLabelingInfo:!0,supportsRenderer:!0,supportsPopupTemplate:!0,supportsLayerQuery:!0,supportsStatistics:!0}:
null};f.prototype.getFieldDomain=function(a,c){return this.layer.getFieldDomain(a,c)};f.prototype.summaryStatistics=function(a){var c=this,b=a.field,b=b?this.getField(b):null,e=B.isDateField(b),g=(b=a.valueExpression||a.sqlExpression)&&!a.sqlExpression,d=a.view,d=d&&"3d"===d.type;return this._hasLocalSource||a.features||g?g||a.features||d?this._summaryStatsFromMemory(a,e):this._summaryStatsFromClientQuery(a,e):this.supportsSQLExpression||!e&&!b?(a.normalizationType&&!this.supportsSQLExpression?this._summaryStatsFromGenRend(a):
this._summaryStatsFromServiceQuery(a,e)).catch(function(){return c._summaryStatsFromMemory(a,e)}):n.reject(new r("feature-layer-adapter:not-supported","Layer does not support standardized SQL expression for queries"))};f.prototype.uniqueValues=function(a){var c=this,b=a.field,e=a.valueExpression,g=a.sqlExpression,d=(b?this.getField(b):null)&&this.getFieldDomain(b),f=e&&(!g||!this.supportsSQLExpression),k=(b=a.view)&&"3d"===b.type;return this._hasLocalSource||a.features||f?f||a.features||k?this._uvFromMemory(a,
d):this._uvFromClientQuery(a,d):this._uvFromServiceQuery(a,d).catch(function(b){return a.field?c._uvFromGenRenderer(a,d):b}).catch(function(){return f||a.features||k?c._uvFromMemory(a,d):c._uvFromClientQuery(a,d)})};f.prototype.histogram=function(a){var c=this,b=a.field,e=a.normalizationType,g=a.normalizationField,d=a.classificationMethod,f=b?this.getField(b):null,f=B.isDateField(f),k=a.valueExpression||a.sqlExpression,t=k&&!a.sqlExpression,m=this.supportsSQLExpression,w=!d||"equal-interval"===d,
u=a.minValue,q=a.maxValue,X=null!=u&&null!=q,z=a.numBins||10;return this._hasLocalSource||a.features||t?this._histogramFromMemory(a):(k||m)&&w?k&&!m?n.reject(new r("feature-layer-adapter:not-supported","Layer does not support standardized SQL expression for queries")):this._histogramForExpr(a):f&&w?n.reject(new r("feature-layer-adapter:not-supported","Normalization and date field are not allowed when layer does not support standardized SQL expression for queries")):e||!w?this._binParamsFromGenRend(a).then(function(d){if(!X)return c._getBins(d,
b,z);if(u>d.max||q<d.min)throw new r("histogram:insufficient-data","Range defined by 'minValue' and 'maxValue' does not intersect available data range of the field");if(w)return c._getBins({min:u,max:q,sqlExpr:d.sqlExpr,excludeZerosExpr:d.excludeZerosExpr},b,z);d=l.getFieldExpr({field:b,normalizationType:e,normalizationField:g,normalizationTotal:d.normTotal});d=p.getRangeExpr(d,u,q);return c._binParamsFromGenRend(a,d).then(function(a){return c._getBins(a,b,z)})}):this._histogramForField(a)};f.prototype.classBreaks=
function(a){var c=this,b=!1!==a.analyzeData,e=this._hasLocalSource||a.features||a.valueExpression;return b&&e?this._classBreaksFromMemory(a):(b?this._classBreaksFromGenRend(a):this._classBreaksFromInterpolation(a)).catch(function(){return c._classBreaksFromMemory(a)})};f.prototype.queryFeatureCount=function(a){if(this._hasLocalSource)return n.reject(new r("feature-layer-adapter:not-supported","Layer does not support count query"));var c=this.layer,b=c.createQuery();b.where=p.mergeWhereClauses(b.where,
a);return c.queryFeatureCount(b)};f.prototype.generateRenderer=function(a){var c=this.layer;if(this._hasLocalSource||10.1>c.version)return n.reject(new r("feature-layer-adapter:not-supported","Layer does not support generateRenderer operation (requires ArcGIS Server version 10.1+)"));var b=new T({url:c.parsedUrl.path,source:c.dynamicDataSource,gdbVersion:c.gdbVersion}),c=c.createQuery();a.where=p.mergeWhereClauses(a.where,c.where);return b.execute(a)};f.prototype.heatmapStatistics=function(a){var c=
this,b=a.field,e=a.fieldOffset;return(b&&null==e?this.summaryStatistics({field:b}):n.resolve(null)).then(function(b){var d=e||0;if(b){var f=b.min,g=b.max;b.count?f===g&&0===f?d=1:0>=g?d="abs":0>f&&(d=-1.01*f):d=1}return c._heatmapStatsFromMemory(a,d).then(function(a){return x({},a,{summaryStatistics:b,fieldOffset:d})})})};f.prototype.predominantCategories=function(a){return v(this,void 0,void 0,function(){var c,b,e,f,d,h,k,l,m,n,u,q,p,z,v,G,H;return y(this,function(g){switch(g.label){case 0:if(!this._hasLocalSource&&
!this.supportsSQLExpression)throw new r("feature-layer-adapter:not-supported","Layer does not support advanced SQL expressions and standardized queries");c=a.fields;b=a.view;e=D.getArcadeForPredominantCategory(c);f=D.getSQLForPredominantCategoryName(c);d=b&&"3d"===b.type;return b&&this._hasLocalSource?d?[4,this._uvFromMemory({valueExpression:e,view:b})]:[3,2]:[3,5];case 1:return l=g.sent(),[3,4];case 2:return[4,this._uvFromClientQuery({valueExpression:e,view:b})];case 3:l=g.sent(),g.label=4;case 4:return k=
l,[3,7];case 5:return[4,this._uvFromServiceQuery({sqlExpression:f.expression,valueExpression:e})];case 6:k=g.sent(),g.label=7;case 7:h=k;m=h.uniqueValueInfos;n=m.map(function(a){return a.value});u=c.filter(function(a){return-1===n.indexOf(a)});q=0;for(p=u;q<p.length;q++)z=p[q],m.push({value:z,count:0});m.sort(function(a,b){return c.indexOf(a.value)-c.indexOf(b.value)});v=0;for(G=m;v<G.length;v++)H=G[v],H.value===D.noDominantCategoryField&&(H.value=null);return[2,{predominantCategoryInfos:m}]}})})};
f.prototype.getSampleFeatures=function(a){return v(this,void 0,void 0,function(){var c,b,e,f,d,h,k,l,m,n,p,q,r,v,x=this;return y(this,function(g){switch(g.label){case 0:c=a.view,b=a.sampleSize,e=a.requiredFields,f=a.returnGeometry,d=this.layer.createQuery(),h=1,d.outSpatialReference=a.spatialReference||c&&c.spatialReference,d.returnGeometry=!!f,d.outFields=e,k=[],g.label=1;case 1:return g.trys.push([1,7,,8]),l=!0,e&&e.length?[4,c.whenLayerView(this.layer)]:[3,4];case 2:return m=g.sent(),[4,A.whenFalseOnce(m,
"updating")];case 3:g.sent(),l=e.every(function(a){a=x.getField(a);return-1<m.availableFields.indexOf(a.name)}),g.label=4;case 4:return l?[4,this._fetchFeaturesFromMemory(c,d)]:[3,6];case 5:k=g.sent();if(k.length&&0<b&&b<=k.length)return[2,J.pickRandom(k,b,h)];g.label=6;case 6:return[3,8];case 7:return g.sent(),[3,8];case 8:return g.trys.push([8,12,,13]),this._hasLocalSource?[2,k]:[4,this.queryFeatureCount()];case 9:n=g.sent();p=this.layer.capabilities.query.maxRecordCount;q=-1===b?n:b;q=p&&q>p?p:
q;if(n<=k.length||k.length>=p)return[2,k];r=c.extent.width/c.width/c.scale*4E5;d.maxAllowableOffset=a.resolution||r;return n<=q?[2,this._fetchFeaturesFromService(d)]:2E4>=n?[4,this.layer.queryObjectIds()]:[3,11];case 10:return v=g.sent(),d.objectIds=J.pickRandom(v,q,h),[2,this._fetchFeaturesFromService(d)];case 11:return this.layer.get("capabilities.query.supportsPagination")&&(d.num=q),[2,this._fetchFeaturesFromService(d)];case 12:return g.sent(),[2,k];case 13:return[2]}})})};f.prototype.load=function(a){var c=
this;a=this.layer.load(a).then(function(a){c.geometryType=a.geometryType;c.objectIdField=a.objectIdField;c.supportsSQLExpression=a.get("capabilities.query.supportsSqlExpression");c._hasLocalSource=!a.url&&!!a.source;c.hasQueryEngine=c._hasLocalSource;c.minScale=a.minScale;c.maxScale=a.maxScale;c.fullExtent=a.fullExtent});this.addResolvingPromise(a);return this.when()};I([C.property({constructOnly:!0})],f.prototype,"layer",void 0);return f=I([C.subclass("esri.renderers.smartMapping.support.adapters.FeatureLayerAdapter")],
f)}(C.declared(S))});