// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/generatorHelper ../../core/tsSupport/awaiterHelper ../../core/Collection ../../core/has ../../core/promiseUtils ../../layers/support/lazyLayerLoader ../PortalItem ./mapNotesUtils ./portalLayers ../../renderers/support/styleUtils".split(" "),function(L,q,m,k,w,M,x,l,y,z,A,B){function C(a,d,c){return k(this,void 0,void 0,function(){var b;return m(this,function(e){switch(e.label){case 0:return b=new a,b.read(d,c.context),"group"===b.type&&r(d)?[4,D(b,d,c.context)]:
[3,2];case 1:e.sent(),e.label=2;case 2:return[4,B.loadStyleRenderer(b,c.context)];case 3:return e.sent(),[2,b]}})})}function t(a,d){return k(this,void 0,void 0,function(){var c;return m(this,function(b){switch(b.label){case 0:return[4,E(a,d)];case 1:return c=b.sent(),[2,C(c,a,d)]}})})}function E(a,d){return k(this,void 0,void 0,function(){var c,b,e,g,f,n,p,u;return m(this,function(h){switch(h.label){case 0:c=d.context;switch(c.origin){case "web-scene":switch(c.layerContainerType){case "basemap":h=
F;break;case "ground":h=G;break;default:h=H}break;default:switch(c.layerContainerType){case "basemap":h=I;break;default:h=J}}b=h;e=a.layerType||a.type;!e&&d&&d.defaultLayerType&&(e=d.defaultLayerType);f=(g=b[e])?l.layerLookupMap[g]:l.layerLookupMap.UnknownLayer;if("Feature Collection"!==a.type)return[3,4];if(!a.itemId)return[3,3];n=new y({id:a.itemId,portal:c&&c.portal});return[4,n.load()];case 1:return h.sent(),[4,A.selectLayerClassPath(n)];case 2:p=h.sent(),u=p.className||"UnknownLayer",f=l.layerLookupMap[u],
h.label=3;case 3:return[3,5];case 4:"ArcGISFeatureLayer"===e&&(z.isMapNotesLayer(a)?f=l.layerLookupMap.MapNotesLayer:r(a)&&(f=l.layerLookupMap.GroupLayer)),h.label=5;case 5:return a.wmtsInfo&&(f=l.layerLookupMap.WMTSLayer),[2,f()]}})})}function r(a){if("ArcGISFeatureLayer"!==a.layerType||"Feature Collection"===a.type)return!1;a=a.featureCollection;return!!(a&&a.layers&&1<a.layers.length)}function K(a,d,c){return k(this,void 0,void 0,function(){var b,e,g;return m(this,function(f){switch(f.label){case 0:return b=
new w,e=v(b,Array.isArray(d.layers)?d.layers:[],c),[4,a];case 1:return g=f.sent(),[4,e];case 2:return f.sent(),"group"===g.type?(g.layers.addMany(b),[2,g]):[2,void 0]}})})}function D(a,d,c){return k(this,void 0,void 0,function(){var b,e,g,f,n;return m(this,function(p){switch(p.label){case 0:return b=l.layerLookupMap.FeatureLayer,[4,b()];case 1:return e=p.sent(),g=d.featureCollection,f=g.showLegend,n=g.layers.map(function(a){var b=new e;b.read(a,c);null!=f&&b.read({showLegend:f},c);return b}),a.layers.addMany(n),
[2]}})})}function v(a,d,c){return k(this,void 0,void 0,function(){var b,e,g,f,n,p,k,h,l;return m(this,function(m){switch(m.label){case 0:if(!d)return[2];b=[];e=0;for(g=d;e<g.length;e++)f=g[e],n=t(f,c),"GroupLayer"===f.layerType?b.push(K(n,f,c)):b.push(n);return[4,x.eachAlways(b)];case 1:p=m.sent();k=0;for(h=p;k<h.length;k++)l=h[k],!l.value||c.filter&&!c.filter(l.value)||a.add(l.value);return[2]}})})}Object.defineProperty(q,"__esModule",{value:!0});var H={ArcGISFeatureLayer:"FeatureLayer",ArcGISImageServiceLayer:"ImageryLayer",
ArcGISMapServiceLayer:"MapImageLayer",PointCloudLayer:"PointCloudLayer",ArcGISSceneServiceLayer:"SceneLayer",IntegratedMeshLayer:"IntegratedMeshLayer",BuildingSceneLayer:"BuildingSceneLayer",ArcGISTiledElevationServiceLayer:"ElevationLayer",ArcGISTiledImageServiceLayer:"TileLayer",ArcGISTiledMapServiceLayer:"TileLayer",GroupLayer:"GroupLayer",WebTiledLayer:"WebTileLayer",CSV:"CSVLayer",VectorTileLayer:"VectorTileLayer",WMS:"WMSLayer",DefaultTileLayer:"TileLayer",KML:"KMLLayer",RasterDataLayer:"UnsupportedLayer"},
G={ArcGISTiledElevationServiceLayer:"ElevationLayer",DefaultTileLayer:"ElevationLayer"},F={ArcGISTiledMapServiceLayer:"TileLayer",ArcGISTiledImageServiceLayer:"TileLayer",OpenStreetMap:"OpenStreetMapLayer",WebTiledLayer:"WebTileLayer",VectorTileLayer:"VectorTileLayer",ArcGISImageServiceLayer:"UnsupportedLayer",WMS:"UnsupportedLayer",ArcGISMapServiceLayer:"UnsupportedLayer",DefaultTileLayer:"TileLayer"},J={ArcGISFeatureLayer:"FeatureLayer",ArcGISImageServiceLayer:"ImageryLayer",ArcGISImageServiceVectorLayer:"UnsupportedLayer",
ArcGISMapServiceLayer:"MapImageLayer",ArcGISStreamLayer:"StreamLayer",ArcGISTiledImageServiceLayer:"TileLayer",ArcGISTiledMapServiceLayer:"TileLayer",VectorTileLayer:"VectorTileLayer",WebTiledLayer:"WebTileLayer",CSV:"CSVLayer",GeoRSS:"GeoRSSLayer",KML:"KMLLayer",WFS:"UnsupportedLayer",WMS:"WMSLayer",BingMapsAerial:"BingMapsLayer",BingMapsRoad:"BingMapsLayer",BingMapsHybrid:"BingMapsLayer",DefaultTileLayer:"TileLayer"},I={ArcGISImageServiceLayer:"ImageryLayer",ArcGISImageServiceVectorLayer:"UnsupportedLayer",
ArcGISMapServiceLayer:"MapImageLayer",ArcGISTiledImageServiceLayer:"TileLayer",ArcGISTiledMapServiceLayer:"TileLayer",OpenStreetMap:"OpenStreetMapLayer",VectorTileLayer:"VectorTileLayer",WebTiledLayer:"WebTileLayer",BingMapsAerial:"BingMapsLayer",BingMapsRoad:"BingMapsLayer",BingMapsHybrid:"BingMapsLayer",WMS:"WMSLayer",DefaultTileLayer:"TileLayer"};q.createLayer=t;q.populateOperationalLayers=function(a,d,c){return k(this,void 0,void 0,function(){return m(this,function(b){return[2,v(a,d,c)]})})}});