// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports dojo/date/locale ../../../intl ../../../core/Error ../../../core/lang ../../../core/Logger ../../../core/promiseUtils ../../../core/unitUtils ./geometryUtils".split(" "),function(V,t,I,J,v,K,L,A,M,B){function C(a,c){var b=a.filter,g=a.searchExtent;c=c&&c.extent;a=a.withinViewEnabled&&c?c:void 0;return b&&b.geometry||g||a}function D(a){return a?a.load().then(A.resolve).catch(A.reject):A.resolve()}function E(a){return a&&!!a.get("capabilities.query.supportsPagination")}function F(a){var c=
"";a&&(a=a.fields)&&a.some(function(a){return"string"===a.type?(c=a.name,!0):!1});return c}function y(a,c){return a&&c?c.every(function(c){return!!a.getField(c)}):!1}function N(a){for(var c=0;c<a.length;c++)if(255<a.charCodeAt(c))return!0;return!1}function O(a,c,b){var g=null;(a=a.codedValues)&&a.some(function(a){var e=a.name,e=b?e:e.toLowerCase();return(b?c:c.toLowerCase())===e?(g=a.code.toString(),!0):!1});return g}function w(a,c){return(c=c&&c.where)?"("+a+") AND ("+c+")":a}function G(a,c,b,g,
h){var e=c.definitionExpression,m="";if(a){var d=P.test(c.url)&&N(a)?"N":"";b&&b.forEach(function(b){var f=c.getField(b);b=((b="function"===typeof c.getFieldDomain&&c.getFieldDomain(b))&&"coded-value"===b.type?O(b,a,h):null)||a||null;if(null!==b){var e=f.type,f=f.name;"string"===e||"date"===e||"global-id"===e?h?f=w(f+" \x3d "+d+"'"+b+"'",g):(b=b.toUpperCase(),f=w("UPPER("+f+") LIKE "+d+"'%"+b+"%'",g)):"oid"===e||"small-integer"===e||"integer"===e||"single"===e||"double"===e?(b=Number(b),f=isNaN(b)?
null:w(f+" \x3d "+b,g)):f=w(f+" \x3d "+b,g);f&&(m+=m?" OR ("+f+")":"("+f+")")}})}return e?"("+e+") AND ("+m+")":m}function Q(a,c){var b=null;(a=a.codedValues)&&a.length&&a.some(function(a){return a.code===c?(b=a.name,!0):!1});return b}function H(a,c,b){var g=a.layer,h=a.attributes,e="function"===typeof g.getFieldDomain&&g.getFieldDomain(b);return c?J.substitute(c,h):b&&a.hasOwnProperty("attributes")&&h.hasOwnProperty(b)?(a=h[b],b=g.getField(b),e&&"coded-value"===e.type?Q(e,a):b&&"date"===b.type?I.format(new Date(a)):
"number"===typeof a?a.toString():"string"!==typeof a?"":a.trim()):""}function R(a,c,b,g){return a.features.map(function(a){var e=a.attributes[a.layer.objectIdField];return{text:H(a,c.suggestionTemplate,g),key:e,sourceIndex:b}})}function S(a,c,b,g,h,e,m){return a.features.map(function(a){var d=a.clone(),f=a.layer,f=(f=f&&f.objectIdField)&&a.attributes[f];a=H(a,b.searchTemplate,h);var q=B.createExtentFromGeometry(d.geometry,c,e);return{extent:m?B.scaleExtent(K.clone(q),c,m):q,feature:d,key:f,name:a,
sourceIndex:g}})}Object.defineProperty(t,"__esModule",{value:!0});var P=/https?:\/\/services.*\.arcgis\.com/i,T=/(?:\{([^}]+)\})/g,x=L.getLogger("esri.widgets.Search.support.layerSearchUtils");t.getResults=function(a,c){var b=a.exactMatch,g=void 0===b?!1:b,h=a.location,e=a.maxResults,m=a.spatialReference,d=a.source,w=a.sourceIndex,f=a.suggestResult,q=a.view,n=d.layer,U=d.filter,r=d.zoomScale,k=q&&q.scale,l=C(d,q),u=c&&c.signal;return D(n).then(function(){var a=n.popupTemplate;return a?a.getRequiredFields(n.fields):
null}).then(function(a){var b=n.objectIdField,c=n.returnZ,z=d.displayField||d.layer.displayField||F(d.layer);if(!n.getField(z))throw x.error("invalid-field: displayField is invalid."),new v("getResults():invalid-field","displayField is invalid.");a=a&&a.length?a:[z];var p=(a=d.outFields||a)&&-1!==a.indexOf("*");-1!==a.indexOf(b)||p||a.push(b);if(!p&&!y(n,a))throw x.error("invalid-field: outField is invalid."),new v("getResults():invalid-field","outField is invalid.");var b=n.createQuery(),p=d.orderByFields,
t=d.searchQueryParams;t&&b.set(t);p&&(b.orderByFields=p);m&&(b.outSpatialReference=m,p=1/M.getMetersPerUnitForSR(m))&&(b.maxAllowableOffset=p);p=!!n.get("capabilities.data.supportsZ");b.returnZ=p&&!1!==c;b.returnGeometry=!0;a&&(b.outFields=a);if(h)b.geometry=h;else if(f.key)b.objectIds=[parseInt(f.key,10)];else{c=d.searchFields||[z];if(!y(n,c))throw x.error("invalid-field: search field is invalid."),new v("getResults():invalid-field","search field is invalid.");E(n)&&(b.num=e);l&&(b.geometry=l);if(!f.text.trim())return[];
a=d.prefix;p=d.suffix;a=(""+(void 0===a?"":a)+f.text+(void 0===p?"":p)).replace(/\'/g,"''");c=G(a,n,c,U,g);if(!c)return[];b.where=c}return n.queryFeatures(b,{signal:u}).then(function(a){return S(a,q,d,w,z,k,r)})})};t.getSuggestions=function(a,c){var b=a.source,g=a.spatialReference,h=a.suggestTerm,e=a.maxSuggestions,m=a.sourceIndex,d=b.layer,t=b.filter,f=c&&c.signal,q=C(b,a.view);return D(d).then(function(){if(!E(d))return[];var a=b.displayField||b.layer.displayField||F(b.layer),c=b.searchFields||
[a],r=[];b.suggestionTemplate?b.suggestionTemplate.replace(T,function(a,b){r.push(b);return a}):r.push(a);var k=r&&-1!==r.indexOf("*");-1!==r.indexOf(d.objectIdField)||k||r.push(d.objectIdField);var l=!!d.getField(a),k=k||y(d,r),u=y(d,c);if(!l)throw x.error("invalid-field: displayField is invalid."),new v("getSuggestions():invalid-field","displayField is invalid.");if(!k)throw x.error("invalid-field: outField is invalid."),new v("getSuggestions():invalid-field","outField is invalid.");if(!u)throw x.error("invalid-field: search field is invalid."),
new v("getSuggestions():invalid-field","search field is invalid.");l=d.createQuery();k=b.orderByFields;(u=b.suggestQueryParams)&&l.set(u);k&&(l.orderByFields=k);l.outSpatialReference=g;l.returnGeometry=!1;l.num=e;l.outFields=r;q&&(l.geometry=q);if(!h.trim())return[];k=b.prefix;u=b.suffix;k=(""+(void 0===k?"":k)+h+(void 0===u?"":u)).replace(/\'/g,"''");c=G(k,d,c,t,!1);if(!c)return[];l.where=c;return d.queryFeatures(l,{signal:f}).then(function(c){return R(c,b,m,a)})})}});