// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/decorateHelper ../../../../../core/tsSupport/declareExtendsHelper ../../../../../core/Evented ../../../../../core/Handles ../../../../../core/maybe ../../../../../core/watchUtils ../../../../../core/accessorSupport/decorators ./isSupportedGraphic ./ReshapeOperation ./reshapeUtils ../../../../interactive/InteractiveToolBase".split(" "),function(c,f,e,h,k,l,m,n,d,g,p,q,r){Object.defineProperty(f,"__esModule",{value:!0});c=function(c){function a(b){b=
c.call(this,b)||this;b._handles=new l;b._reshapeOperation=null;b._internalGeometryUpdate=!1;b.type="reshape-3d";b._emitter.target=null;return b}h(a,c);a.prototype.destroy=function(){this._handles.removeAll();this._reshapeOperation&&(this._reshapeOperation.destroy(),this._reshapeOperation=null);this._set("view",null);this._set("graphic",null)};a.prototype._updateGeometry=function(){0===g.isSupportedGraphic(this.graphic)&&q.isReshapeGeometry(this.graphic.geometry)?this._reshapeOperation.inputGeometry=
this.graphic.geometry.clone():this._reshapeOperation.inputGeometry=null};a.prototype._updateGraphic=function(){var b=this;this._handles.remove("onGraphicGeometryChange");this._updateGeometry();if(0===g.isSupportedGraphic(this.graphic)){var a=this.watch("graphic.geometry",function(){!1===b._internalGeometryUpdate&&b._updateGeometry()},!0);this._handles.add(a,"onGraphicGeometryChange")}};a.prototype.manipulatorSelectionChanged=function(){this._reshapeOperation&&this._reshapeOperation.manipulatorSelectionChanged()};
a.prototype._onReshapeGeometryChanged=function(){m.isNone(this.graphic)||(this._internalGeometryUpdate=!0,this.graphic.geometry=this._reshapeOperation.outputGeometry.clone(),this._internalGeometryUpdate=!1)};a.prototype.initialize=function(){var b=this;this._reshapeOperation=new p.ReshapeOperation({view:this.view,graphic:this.graphic,manipulators:this.manipulators});this._handles.add([this._reshapeOperation.on("reshape",function(a){"reshape"===a.type&&b._onReshapeGeometryChanged();b.emit("reshape",
a)}),this._reshapeOperation.on("move",function(a){"move"===a.type&&b._onReshapeGeometryChanged();b.emit("move",a)}),this._reshapeOperation.on("vertex-add",function(a){b._onReshapeGeometryChanged();b.emit("vertex-add",a)}),this._reshapeOperation.on("vertex-remove",function(a){b._onReshapeGeometryChanged();b.emit("vertex-remove",a)}),this._reshapeOperation.on("immediate-click",function(){return b.emit("immediate-click")}),n.init(this,"graphic",function(){b._updateGraphic()},!0)])};a.prototype.handleInputEvent=
function(a){"key-down"!==a.type||"Delete"!==a.key&&"Backspace"!==a.key||this._reshapeOperation.removeSelectedVertices()};a.prototype.reset=function(){};e([d.property({constructOnly:!0,nonNullable:!0})],a.prototype,"view",void 0);e([d.property({constructOnly:!0})],a.prototype,"graphic",void 0);e([d.property({readOnly:!0})],a.prototype,"type",void 0);return a=e([d.subclass("esri.views.3d.interactive.editingTools.graphicReshape3D.GraphicReshape3DTool")],a)}(d.declared(k.EventedMixin(r.InteractiveToolBase)));
f.GraphicReshape3DTool=c});