// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/decorateHelper ../../../../../core/tsSupport/extendsHelper ../../../../../core/maybe ../../../../../core/libs/gl-matrix-2/vec2 ../../../../../core/libs/gl-matrix-2/vec2f64 ../../../../../core/libs/gl-matrix-2/vec3 ../../../../../core/libs/gl-matrix-2/vec3f64 ../../../../../core/libs/gl-matrix-2/vec4 ../../../../../core/libs/gl-matrix-2/vec4f64 ../../../../../geometry/support/coordsUtils ../../../../../geometry/support/spatialReferenceUtils".split(" "),
function(k,f,F,r,t,z,u,A,v,B,w,m,C){Object.defineProperty(f,"__esModule",{value:!0});var p=function(){function b(){this.vertices=[];this.edges=[]}b.prototype.makeVertex=function(a,c,d){void 0===c&&(c=null);void 0===d&&(d=null);a={pos:a,unnormalizedPos:a,left:c,right:d,type:"vertex",component:this};this.vertices.push(a);return a};b.prototype.makeEdge=function(a,c){var d={v0:a,v1:c,type:"edge",component:this};a.right=d;c.left=d;this.edges.push(d);return d};b.prototype.removeVertex=function(a){this.vertices.splice(this.vertices.indexOf(a),
1);a.left&&this.removeEdge(a.left);a.right&&this.removeEdge(a.right)};b.prototype.removeEdge=function(a){this.edges.splice(this.edges.indexOf(a),1);a.v0.right=null;a.v1.left=null};return b}();f.Component=p;var x=function(){function b(){}b.prototype.createNew=function(){return u.vec2f64.create()};b.prototype.fromArray=function(a){return u.vec2f64.fromValues(a[0],a[1])};b.prototype.toArray=function(a){return[a[0],a[1]]};b.prototype.toPoint=function(a,c){c.x=a[0];c.y=a[1];c.hasZ=!1;c.hasM=!1;return c};
b.prototype.lerp=function(a,c,d,b){return z.vec2.lerp(b,a,c,d)};b.prototype.addDelta=function(a,c,d){a[0]+=c;a[1]+=d};return b}();f.CoordinateHelper2D=x;var l=function(){function b(a){this.ztype=a}b.prototype.createNew=function(){return v.vec3f64.create()};b.prototype.fromArray=function(a){return v.vec3f64.fromValues(a[0],a[1],a[2]||0)};b.prototype.toArray=function(a){return[a[0],a[1],a[2]]};b.prototype.toPoint=function(a,c){c.x=a[0];c.y=a[1];0===this.ztype?(c.z=a[2],c.hasZ=!0,c.hasM=!1):(c.m=a[2],
c.hasZ=!1,c.hasM=!0);return c};b.prototype.lerp=function(a,c,d,b){return A.vec3.lerp(b,a,c,d)};b.prototype.addDelta=function(a,c,d,b){a[0]+=c;a[1]+=d;0===this.ztype&&(a[2]+=b)};return b}();f.CoordinateHelper3D=l;var y=function(){function b(){}b.prototype.createNew=function(){return w.vec4f64.create()};b.prototype.fromArray=function(a){return w.vec4f64.fromValues(a[0],a[1],a[2]||0,a[3]||0)};b.prototype.toArray=function(a){return[a[0],a[1],a[2],a[3]]};b.prototype.toPoint=function(a,c){c.x=a[0];c.y=
a[1];c.z=a[2];c.m=a[3];c.hasZ=!0;c.hasM=!0;return c};b.prototype.lerp=function(a,c,d,b){return B.vec4.lerp(b,a,c,d)};b.prototype.addDelta=function(a,c,d,b){a[0]+=c;a[1]+=d;a[2]+=b};return b}();f.CoordinateHelper4D=y;k=function(){function b(a,c,d){this.geometry=a;this.doUnnormalization=c;this.coordinateHelper=d;this.components=[];a=C.getInfo(this.geometry.spatialReference);this._tmpMapPoint=d.createNew();a?(this._spanMin=a.valid[0],this._spanMax=a.valid[1],this._span=this._spanMax-this._spanMin):this.doUnnormalization=
!1}b.prototype.addDelta=function(a,c,d,b){this.coordinateHelper.addDelta(a.pos,c,d,b)};b.prototype.getVertexPositionAsPoint=function(a,c){this.coordinateHelper.toPoint(a.pos,c);c.spatialReference=this.geometry.spatialReference;return c};b.prototype.getEdgePosition=function(a,c,b){void 0===b&&(b=this.coordinateHelper.createNew());return this.coordinateHelper.lerp(a.v0.unnormalizedPos,a.v1.unnormalizedPos,c,b)};b.prototype.getEdgePositionAsPoint=function(a,c,b){a=this.getEdgePosition(a,c,this._tmpMapPoint);
this.coordinateHelper.toPoint(a,b);b.spatialReference=this.geometry.spatialReference;return b};b.prototype.canRemoveVertex=function(a){return!0};b.prototype.removeVertex=function(a){var c=a.component,b=a.left,g=a.right;c.removeVertex(a);return b&&g?c.makeEdge(b.v0,g.v1):null};b.prototype.splitEdge=function(a,c){var b=a.component;c=b.makeVertex(this.getEdgePosition(a,c));var g=a.v0,q=a.v1;b.removeEdge(a);b.makeEdge(g,c);b.makeEdge(c,q);return c};return b}();f.ReshapeHelper=k;var D=function(b){function a(a,
d,g){d=b.call(this,a,d,g)||this;d.geometry=a;a=d.geometry.rings;for(var c=0;c<a.length;++c){for(var n=a[c],e=new p,h=n.length-1,f=0;f<h;++f){var k=g.fromArray(n[f]);e.makeVertex(k)}n=e.vertices.length-1;for(h=0;h<n;++h)e.makeEdge(e.vertices[h],e.vertices[h+1]);e.makeEdge(e.vertices[e.vertices.length-1],e.vertices[0]);d.doUnnormalization&&m.computeUnnormalizedVertexPositionsOnDateLineCrossing(e.vertices,d._spanMin,d._spanMax,d._span);d.components.push(e)}return d}r(a,b);a.prototype.canRemoveVertex=
function(a){return 3<a.component.vertices.length};a.prototype.commit=function(){var a=this,b=[],g=this.coordinateHelper.toArray;this.components.forEach(function(c){var d=[];a.doUnnormalization&&m.computeUnnormalizedVertexPositionsOnDateLineCrossing(c.vertices,a._spanMin,a._spanMax,a._span);var e=c.vertices[0],q=e;do d.push(g(e.unnormalizedPos)),e=e.right.v1;while(e&&e!==q);d.push(g(c.vertices[0].unnormalizedPos));b.push(d)});this.geometry.rings=b;return this.geometry};return a}(k),E=function(b){function a(a,
d,g){d=b.call(this,a,d,g)||this;d.geometry=a;a=d.geometry.paths;for(var c=0;c<a.length;++c){for(var f=a[c],e=new p,h=f.length,k=0;k<h;++k){var l=g.fromArray(f[k]);e.makeVertex(l)}f=e.vertices.length-1;for(h=0;h<f;++h)e.makeEdge(e.vertices[h],e.vertices[h+1]);d.doUnnormalization&&m.computeUnnormalizedVertexPositionsOnDateLineCrossing(e.vertices,d._spanMin,d._spanMax,d._span);d.components.push(e)}return d}r(a,b);a.prototype.canRemoveVertex=function(a){return 2<a.component.vertices.length};a.prototype.commit=
function(){var a=this,b=[],f=this.coordinateHelper.toArray;this.components.forEach(function(c){var d=[];a.doUnnormalization&&m.computeUnnormalizedVertexPositionsOnDateLineCrossing(c.vertices,a._spanMin,a._spanMax,a._span);var e=c=c.vertices[0];do d.push(f(c.unnormalizedPos)),c=c.right?c.right.v1:null;while(c&&c!==e);b.push(d)});this.geometry.paths=b;return this.geometry};return a}(k);f.isReshapeGeometry=function(b){return t.isSome(b)&&("polygon"===b.type||"polyline"===b.type)};f.createReshapeHelper=
function(b,a){if(t.isNone(b))return null;var c;c=b.hasZ&&b.hasM?new y:b.hasM?new l(1):b.hasZ?new l(0):new x;return"polygon"===b.type?new D(b,a,c):new E(b,a,c)}});