// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper dojo/string ../../../Basemap ./adapters/CSVLayerAdapter ./adapters/FeatureLayerAdapter ./adapters/LayerAdapter ./adapters/PointCloudLayerAdapter ./adapters/SceneLayerAdapter ../../../support/arcadeOnDemand ../../../support/basemapUtils".split(" "),function(B,c,q,r,t,u,v,n,w,x,y,z,A){function h(a){return t.pad(a,2,"0")}function p(a,b,d){if("date"===b||"number"===b){"number"===b&&(a=new Date(a));b=
d?a.getFullYear():a.getUTCFullYear();var e=h((d?a.getMonth():a.getUTCMonth())+1),f=h(d?a.getDate():a.getUTCDate()),c=h(d?a.getHours():a.getUTCHours()),g=h(d?a.getMinutes():a.getUTCMinutes());a=h(d?a.getSeconds():a.getUTCSeconds());a="TIMESTAMP'"+b+"-"+e+"-"+f+" "+c+":"+g+":"+a+"'"}return a}function k(a,b){if(b instanceof Date)return"date";if("number"===typeof b)return"number";if("string"===typeof b&&(a=a.getField(b),"\x3cnow\x3e"!==b.toLowerCase()&&a&&"date"===a.type))return"field"}Object.defineProperty(c,
"__esModule",{value:!0});var g;c.defaultBasemapGroups={light:"streets gray topo terrain national-geographic oceans osm gray-vector streets-vector topo-vector streets-relief-vector streets-navigation-vector".split(" "),dark:["satellite","hybrid","dark-gray","dark-gray-vector","streets-night-vector"]};var l=(g={},g[0]={adapter:v,type:"csv",label:"CSVLayer"},g[2]={adapter:n,type:"feature",label:"FeatureLayer"},g[1]={adapter:n,type:"geojson",label:"GeoJSONLayer"},g[3]={adapter:y,type:"scene",label:"SceneLayer"},
g[4]={adapter:x,type:"point-cloud",label:"PointCloudLayer"},g);c.unitValueInDays={years:365,months:30,days:1,hours:1/24,minutes:1/1440,seconds:1/86400,milliseconds:1/864E5};var m=null;c.getLayerTypeLabels=function(a){return a.map(function(a){return l[a].label})};c.createLayerAdapter=function(a,b){if(a instanceof w)return a;var d=null;b.some(function(b){var e=a.type===l[b].type;e&&(d=new l[b].adapter({layer:a}));return e});return d};c.getFieldsList=function(a){return r(this,void 0,void 0,function(){var b,
d,e,c,g;return q(this,function(f){switch(f.label){case 0:return b=a.field,d=a.normalizationField,e=a.valueExpression,c=[],e?m?[3,2]:[4,z.loadArcade()]:[3,3];case 1:m=g=f.sent().arcadeUtils,f.label=2;case 2:c=m.extractFieldNames(e),f.label=3;case 3:return b&&c.push(b),d&&c.push(d),[2,c]}})})};c.getNormalizationType=function(a){var b=a.normalizationType;b||(a.normalizationField?b="field":null!=a.normalizationTotal&&(b="percent-of-total"));return b};c.getDateDiffSQL=function(a,b,d,e){var f=a.hasQueryEngine;
d=p(d,k(a,d),f);a=p(b,k(a,b),f);a="("+d+" - "+a+")";f&&(a="("+a+" * "+c.unitValueInDays.milliseconds+")");e=c.unitValueInDays[e];f="/";1>e&&(e=1/e,f="*");return{sqlExpression:1===e?a:"("+a+" "+f+" "+e+")",sqlWhere:null}};c.getDateType=k;c.getBasemapGroup=function(a,b){void 0===b&&(b=c.defaultBasemapGroups);for(var d in b)if(-1<b[d].indexOf(a))return d};c.getBasemapId=function(a,b,d){void 0===d&&(d=!0);var c=null;"string"===typeof a&&-1<b.indexOf(a)?c=a:a instanceof u&&(c=A.getWellKnownBasemapId(a));
return d?c||"gray":c}});