// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/assignHelper ../../../../core/has ../../../../core/screenUtils ../../../../core/libs/rbush/rbush ../../../../geometry/support/aaBoundingRect ../../../../geometry/support/contains ../../../../geometry/support/extentUtils ../../../../geometry/support/jsonUtils ../../../../geometry/support/normalizeUtils ./GraphicStoreItem ./graphicsUtils".split(" "),function(A,B,x,C,D,E,k,y,F,G,H,v,p){function w(e,a,c,b,f){u.minX=a;u.minY=c;u.maxX=b;u.maxY=f;return e.search(u)}
Object.defineProperty(B,"__esModule",{value:!0});var u={minX:0,minY:0,maxX:0,maxY:0},r=k.create(),z=[];A=function(){function e(a,c,b,f,n,g){this._graphics=f;this._onAdd=n;this._onRemove=g;this._index=E(9,C("csp-restrictions")?function(a){return{minX:a[0],minY:a[1],maxX:a[2],maxY:a[3]}}:[".bounds[0]",".bounds[1]",".bounds[2]",".bounds[3]"]);this._itemByGraphic=new Map;this._currentLevel=-Infinity;this._tileInfoView=a;this._uidFieldName=b;if(a=a.getClosestInfoForScale(c))this._currentLevel=a.level,
this._resolution=this._tileInfoView.getTileResolution(a.level)}e.prototype.hitTest=function(a,c,b,f,n){a=H.normalizeMapX(a,this._tileInfoView.spatialReference);var g=.5*f*b;r[0]=a-g;r[1]=c-g;r[2]=a+g;r[3]=c+g;b=.5*f*(b+50);b=w(this._index,a-b,c-b,a+b,c+b);if(!b||0===b.length)return[];for(var g={x:a,y:c},l=[],d,e=0;e<b.length;e++){var h=b[e];if(h.graphic.visible)switch(G.getJsonType(h.geometry)){case "esriGeometryPoint":d=h.symbol;if(!d)continue;var m=h.geometry,q=void 0;switch(d.type){case "text":q=
p.getTextSymbolBounds(m.x,m.y,d,h.size,this._resolution,n);break;case "cim":q=p.getCIMMarkerBounds(m.x,m.y,d,this._resolution,n);break;default:q=p.getMarkerSymbolBounds(m.x,m.y,d,this._resolution,n)}y.polygonContainsPoint(q,g)&&l.push(h);break;case "esriGeometryPolyline":d=h.symbol;if(!d)continue;d=1.5*f*window.devicePixelRatio*D.pt2px(d.width);p.isPointOnPolyline(h.geometry,a,c,d)&&l.push(h);break;case "esriGeometryEnvelope":d=h.geometry;d=k.fromValues(d.xmin,d.ymin,d.xmax,d.ymax);k.intersects(d,
r)&&l.push(h);break;case "esriGeometryPolygon":if(y.polygonContainsPoint(h.geometry,g)){l.push(h);break}d=F.getPolygonExtent(h.geometry);if(Math.abs(d.ymax-d.ymin)<5*f||Math.abs(d.xmax-d.xmin)<5*f)d=k.fromValues(d.xmin,d.ymin,d.xmax,d.ymax),k.intersects(d,r)&&l.push(h);break;case "esriGeometryMultipoint":if(d=h.symbol)for(var m=h.geometry.points,q=void 0,t=0;t<m.length;t++)if(q="text"===d.type?p.getTextSymbolBounds(m[t][0],m[t][1],d,h.size,this._resolution,n):p.getMarkerSymbolBounds(m[t][0],m[t][1],
d,this._resolution,n),y.polygonContainsPoint(q,g)){l.push(h);break}}}l.sort(function(a,b){var c=p.graphicGeometryToNumber(a.graphic),d=p.graphicGeometryToNumber(b.graphic);return c===d?b.zorder-a.zorder:c-d});return l.map(function(a){return a.graphic})};e.prototype.getGraphicsData=function(a,c){var b=w(this._index,a.bounds[0],a.bounds[1],a.bounds[2],a.bounds[3]);if(0===b.length||0===c.length)return[];b.sort(function(a,b){return a.zorder-b.zorder});b[0].insertAfter=-1;for(var f=1;f<b.length;f++)b[f].insertAfter=
b[f-1].graphic.uid;b.sort(function(a,b){return a.graphic.uid-b.graphic.uid});c.sort(function(a,b){return a.uid-b.uid});var n=f=0,g,e=[];a={originPosition:"upperLeft",scale:[a.resolution,a.resolution],translate:[a.bounds[0],a.bounds[3]]};for(var d=0;d<c.length;d++){for(var k=c[d],n=-2;f<b.length;)if(g=b[f],f++,k.uid===g.graphic.uid){n=g.insertAfter;break}if(g.geometry&&-2!==n){var h=g.getGeometryQuantized(a),m=x({},g.graphic.attributes);m[this._uidFieldName]=k.uid;e.push({centroid:v.default.getCentroidQuantized(g,
a),geometry:h,attributes:m,symbol:g.symbol,insertAfter:n})}}return e};e.prototype.getGraphicData=function(a,c){var b=this._itemByGraphic.get(c);if(!b)return null;var f=w(this._index,a.bounds[0],a.bounds[1],a.bounds[2],a.bounds[3]);f.sort(function(a,b){return a.zorder-b.zorder});var e=f.indexOf(b),f=0===e||-1===e?-1:f[e-1].graphic.uid;a={originPosition:"upperLeft",scale:[a.resolution,a.resolution],translate:[a.bounds[0],a.bounds[3]]};var e=b.getGeometryQuantized(a),g=x({},b.graphic.attributes);g[this._uidFieldName]=
c.uid;return{centroid:v.default.getCentroidQuantized(b,a),geometry:e,attributes:g,symbol:b.symbol,insertAfter:f}};e.prototype.queryTileData=function(a){var c=k.pad(a.bounds,50*a.resolution,k.create()),c=w(this._index,c[0],c[1],c[2],c[3]),b=[];this._createTileGraphics(b,c,{originPosition:"upperLeft",scale:[a.resolution,a.resolution],translate:[a.bounds[0],a.bounds[3]]});return b};e.prototype.has=function(a){return this._itemByGraphic.has(a)};e.prototype.getBounds=function(a){return this._itemByGraphic.has(a)?
this._itemByGraphic.get(a).bounds:null};e.prototype.add=function(a,c,b){if(a)return this._onAdd(a),c=v.default.acquire(a,c,b,this._resolution,this._tileInfoView.spatialReference),this._itemByGraphic.set(a,c),b&&this._index.insert(c),c.bounds};e.prototype.remove=function(a){if(this._itemByGraphic.has(a)){this._onRemove(a);var c=this._itemByGraphic.get(a);this._index.remove(c);this._itemByGraphic.delete(a)}};e.prototype.updateZ=function(){for(var a=this._graphics.items,c,b=0;b<a.length;b++)if(c=a[b],
c=this._itemByGraphic.get(c))c.zorder=b};e.prototype.update=function(a,c,b){var f=this._itemByGraphic.get(a),e=k.clone(f.bounds);f.size[0]=f.size[1]=0;this._index.remove(f);f.set(a,c,b,this._resolution,this._tileInfoView.spatialReference);b&&this._index.insert(f);return{oldBounds:e,newBounds:f.bounds}};e.prototype.updateLevel=function(a){var c=this;this._currentLevel!==a&&(this._currentLevel=a,this._resolution=this._tileInfoView.getTileResolution(a),this._index.clear(),z.length=0,this._itemByGraphic.forEach(function(a){a.updateBounds(a.symbol,
c._resolution,c._tileInfoView.spatialReference);a.geometry&&z.push(a)}),this._index.load(z))};e.prototype.clear=function(){this._itemByGraphic.clear();this._index.clear()};e.prototype._createTileGraphics=function(a,c,b){var f=this._uidFieldName;c.sort(function(a,b){return a.zorder-b.zorder});for(var e,g,l,d,k=0;k<c.length;k++){l=c[k];e=l.graphic;g=l.getGeometryQuantized(b);d=0===k?-1:c[k-1].graphic.uid;var h=x({},l.graphic.attributes);h[f]=e.uid;a.push({centroid:v.default.getCentroidQuantized(l,b),
geometry:g,attributes:h,symbol:l.symbol,insertAfter:d})}};return e}();B.default=A});