// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/assignHelper ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../../../geometry ../../../Graphic ../../../core/Collection ../../../core/Error ../../../core/has ../../../core/Loadable ../../../core/Logger ../../../core/maybe ../../../core/Promise ../../../core/promiseUtils ../../../core/requireUtils ../../../core/workers ../../../core/accessorSupport/decorators ../../../core/accessorSupport/ensureType ../../../tasks/support/FeatureSet module".split(" "),
function(z,g,A,p,r,B,C,v,y,D,t,E,F,G,u,H,I,J,K,l,L,M,N){Object.defineProperty(g,"__esModule",{value:!0});var O=0,x=G.getLogger("esri.layers.graphics.sources.MemorySource");r=function(g){function b(a){a=g.call(this,a)||this;a._idToClientGraphic=null;a.type="memory";return a}A(b,g);b.prototype.load=function(a){a=u.isSome(a)?a.signal:null;this.addResolvingPromise(this._startWorker(a));return this.when()};Object.defineProperty(b.prototype,"workerGeometryType",{get:function(){var a=this.layer&&this.layer.geometryType;
return a?this._geometryTypeRequiresClientGraphicMapping(a)?"polygon":a:null},enumerable:!0,configurable:!0});b.prototype.applyEdits=function(a){var c=this;return this.load().then(function(){return c._applyEdits(a)})};b.prototype.openPorts=function(){var a=this;return this.load().then(function(){return a._connection.openPorts()})};b.prototype.queryFeatures=function(a,c){var d=this;void 0===c&&(c={});return this.load(c).then(function(){return d._connection.invoke("queryFeatures",a?a.toJSON():null,c)}).then(function(a){a=
M.fromJSON(a);if(!d._requiresClientGraphicMapping())return a;for(var c=d.layer.objectIdField,b=0,m=a.features;b<m.length;b++){var k=m[b],e=d._idToClientGraphic.get(k.attributes[c]);e&&(k.geometry=e.geometry)}a.geometryType=d.layer.geometryType;return a})};b.prototype.queryFeaturesJSON=function(a,c){var d=this;void 0===c&&(c={});return this._requiresClientGraphicMapping()?I.reject(new t("query-features-json:unsupported","Cannot query in JSON format for client only geometry types (mesh and extent)")):
this.load(c).then(function(){return d._connection.invoke("queryFeatures",a?a.toJSON():null,c)})};b.prototype.queryFeatureCount=function(a,c){var d=this;void 0===c&&(c={});return this.load(c).then(function(){return d._connection.invoke("queryFeatureCount",a?a.toJSON():null,c)})};b.prototype.queryObjectIds=function(a,c){var d=this;void 0===c&&(c={});return this.load(c).then(function(){return d._connection.invoke("queryObjectIds",a?a.toJSON():null,c)})};b.prototype.queryExtent=function(a,c){var d=this;
void 0===c&&(c={});return this.load(c).then(function(){return d._connection.invoke("queryExtent",a?a.toJSON():null,c)}).then(function(a){return{count:a.count,extent:v.Extent.fromJSON(a.extent)}})};b.prototype._applyEdits=function(a){var c=this;if(!this._connection)throw new t("feature-layer-source:edit-failure","Memory source not loaded");var d=this.layer.objectIdField,b=null,h=[],n=[];a.addFeatures&&(b=this._prepareAddFeatures(a.addFeatures));if(a.deleteFeatures)for(var q=0,k=a.deleteFeatures;q<
k.length;q++){var e=k[q];"objectId"in e&&null!=e.objectId?h.push(e.objectId):"attributes"in e&&null!=e.attributes[d]&&h.push(e.attributes[d])}if(a.updateFeatures)for(d=0,a=a.updateFeatures;d<a.length;d++)e=a[d],n.push(this._serializeFeature(e));return this._connection.invoke("applyEdits",{adds:b?b.features:[],updates:n,deletes:h}).then(function(a){var d=a.featureEditResults;c.fullExtent=a.fullExtent;b&&b.finish(d.uidToObjectId);if(c._idToClientGraphic){a=0;for(var e=d.deleteResults;a<e.length;a++){var f=
e[a];f.success&&c._idToClientGraphic.delete(f.objectId)}}return c._createEditsResult(d)})};b.prototype._createEditsResult=function(a){return{addFeatureResults:a.addResults?a.addResults.map(this._createFeatureEditResult,this):[],updateFeatureResults:a.updateResults?a.updateResults.map(this._createFeatureEditResult,this):[],deleteFeatureResults:a.deleteResults?a.deleteResults.map(this._createFeatureEditResult,this):[],addAttachmentResults:[],updateAttachmentResults:[],deleteAttachmentResults:[]}};b.prototype._createFeatureEditResult=
function(a){var c=!0===a.success?null:a.error||{code:void 0,description:void 0};return{objectId:a.objectId,globalId:a.globalId,error:c?new t("feature-layer-source:edit-failure",c.description,{code:c.code}):null}};b.prototype._prepareAddFeatures=function(a){for(var c=new Map,b=Array(a.length),m=null,h=0;h<a.length;h++){var n=a[h],q=this._serializeFeature(n);!m&&u.isSome(n.geometry)&&(m=n.geometry.type);b[h]=q;c.set(""+q.uid,n)}var k=this;return{features:b,inferredGeometryType:m,finish:function(a){var b=
k.sourceJSON.objectIdField,d;for(d in a){var e=a[d],f=c.get(d);f&&(f.attributes||(f.attributes={}),-1===e?delete f.attributes[b]:f.attributes[b]=e,k._addIdToClientGraphic(f))}}}};b.prototype._addIdToClientGraphic=function(a){if(this._idToClientGraphic){var c=this.sourceJSON.objectIdField,c=a.attributes&&a.attributes[c];null!=c&&this._idToClientGraphic.set(c,a)}};b.prototype._requiresClientGraphicMapping=function(){return this._geometryTypeRequiresClientGraphicMapping(this.layer.geometryType||this.sourceJSON.geometryType)};
b.prototype._geometryRequiresClientGraphicMapping=function(a){return this._geometryTypeRequiresClientGraphicMapping(a.type)};b.prototype._geometryTypeRequiresClientGraphicMapping=function(a){return"mesh"===a||"multipatch"===a||"extent"===a};b.prototype._serializeFeature=function(a){var c=a.attributes;a=this._geometryForSerialization(a);var b=(O++).toString();return a?{uid:b,geometry:a.toJSON(),attributes:c}:{uid:b,attributes:c}};b.prototype._geometryForSerialization=function(a){a=a.geometry;return u.isNone(a)?
null:this._geometryRequiresClientGraphicMapping(a)?v.Polygon.fromExtent(a.extent):a};b.prototype._startWorker=function(a){return C(this,void 0,void 0,function(){var c,b,m,h,n,q,k,e,l,g,p,f,w,r,t,u;return B(this,function(d){switch(d.label){case 0:return[3,2];case 1:d.sent(),d.label=2;case 2:return c=this,[4,K.open(J.getAbsMid("./support/MemorySourceWorker",z,N),{strategy:E("esri-workers-for-memory-layers")?"dedicated":"local",signal:a})];case 3:return c._connection=d.sent(),b=this.layer,m=b.fields,
h=b.spatialReference,n=b.objectIdField,q=b.hasM,k=b.hasZ,e=b.timeInfo,l="defaults"===this.layer.originOf("spatialReference"),g=this._prepareAddFeatures(this.items),this.on("before-changes",function(a){x.error("Source modifications will not propagate after layer has been loaded. Please use .applyEdits() instead");a.preventDefault()}),p={features:g.features,fields:m&&m.map(function(a){return a.toJSON()}),geometryType:v.typeKebabDictionary.toJSON(this.workerGeometryType),hasM:q,hasZ:k,objectIdField:n,
spatialReference:l?null:h&&h.toJSON(),timeInfo:e?e.toJSON():null},[4,this._connection.invoke("load",p,{signal:a})];case 4:f=d.sent();w=0;for(r=f.warnings;w<r.length;w++)t=r[w],x.warn(t.message,{layer:this.layer,warning:t});f.featureErrors.length&&x.warn("Encountered "+f.featureErrors.length+" validation errors while loading features",f.featureErrors);u=f.layerDefinition;this._geometryTypeRequiresClientGraphicMapping(g.inferredGeometryType)&&(u.geometryType=v.typeKebabDictionary.toJSON(g.inferredGeometryType));
this.sourceJSON=u;this._requiresClientGraphicMapping()&&(this._idToClientGraphic=new Map);g.finish(f.assignedObjectIds);return[2]}})})};p([l.shared({Type:y,ensureType:L.ensureType(y)})],b.prototype,"itemType",void 0);p([l.property()],b.prototype,"type",void 0);p([l.property({constructOnly:!0})],b.prototype,"layer",void 0);p([l.property({readOnly:!0,dependsOn:["layer.geometryType"]})],b.prototype,"workerGeometryType",null);p([l.property()],b.prototype,"sourceJSON",void 0);return b=p([l.subclass("esri.layers.graphics.sources.MemorySource")],
b)}(l.declared(F.LoadableMixin(H.EsriPromiseMixin(D))));g.MemorySource=r;g.default=r});