// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/generatorHelper ../../core/tsSupport/awaiterHelper ../../request ../../core/promiseUtils ../../core/screenUtils ../../geometry/support/jsonUtils ./cimAnalyzer ./Rasterizer ./TextRasterizer ./utils ../support/cimSymbolUtils ../support/Symbol3DAnchorPosition2D".split(" "),function(S,T,C,H,N,F,w,O,G,P,Q,f,I,R){function J(f,a,b){var c=(f?Object.keys(f):[]).map(function(a){return{name:a,alias:a,type:"string"===typeof f[a]?"esriFieldTypeString":"esriFieldTypeDouble"}});
return{geometryType:a,spatialReference:b,fields:c}}return function(){function q(a,b){this._spatialReference=a;this._avoidSDF=b;this._resourceCache=new Map;this._rasterizer=new P.default;this._textRasterizer=new Q.default;this._pictureMarkerCache=new Map}q.prototype.rasterizeCIMSymbolAsync=function(a,b,c,e,d,g){return H(this,void 0,void 0,function(){var h,l,f,u,n,p,v,r,m,k;return C(this,function(t){switch(t.label){case 0:return[4,I.expandSymbol(a)];case 1:return h=t.sent(),l=[],b?(u=null!==b.centroid?
"esriGeometryPolygon":O.getJsonType(b.geometry),f=J(b.attributes,u,this._spatialReference)):(h=h.clone(),h.data.primitiveOverrides=[],f=null),n=[],n.push(G.analyzeCIMSymbol(h.data,c,f,l,this._avoidSDF)),[4,F.all(n)];case 2:t.sent(),p=[],v=0,r=l,t.label=3;case 3:if(!(v<r.length))return[3,7];m=r[v];return"CIMPictureMarker"!==m.cim.type?[3,5]:[4,this.fetchPictureMarkerResource(m)];case 4:t.sent(),t.label=5;case 5:k=this._getRasterizedResource(m,b,e,d,g),null!=k&&p.push({cimLayer:m,rasterizedResource:k}),
t.label=6;case 6:return v++,[3,3];case 7:return[2,this.getSymbolImage(p,b,e,d,g)]}})})};q.prototype.analyzeCIMSymbol=function(a,b,c,e,d){return H(this,void 0,void 0,function(){var g,h,l,f,u,n;return C(this,function(p){switch(p.label){case 0:return[4,I.expandSymbol(a,d)];case 1:return g=p.sent(),h=[],b?l=J(b,e,this._spatialReference):(g=g.clone(),g.data.primitiveOverrides=[],l=null),f=[],f.push(G.analyzeCIMSymbol(g.data,c,l,h,this._avoidSDF)),[4,F.all(f)];case 2:p.sent(),F.throwIfAborted(d),u=0,p.label=
3;case 3:if(!(u<h.length))return[3,6];n=h[u];return"CIMPictureMarker"!==n.cim.type?[3,5]:[4,this.fetchPictureMarkerResource(n,d)];case 4:p.sent(),p.label=5;case 5:return u++,[3,3];case 6:return[2,h]}})})};q.prototype.fetchPictureMarkerResource=function(a,b){return H(this,void 0,void 0,function(){var c,e,d;return C(this,function(g){switch(g.label){case 0:return c=a.materialHash,this._pictureMarkerCache.get(c)?[3,2]:[4,N(a.cim.url,{responseType:"image",signal:b.signal})];case 1:e=g.sent(),d=e.data,
this._pictureMarkerCache.set(c,d),g.label=2;case 2:return[2]}})})};q.prototype.rasterizeCIMSymbol=function(a,b,c,e,d){for(var g=[],h=0;h<a.length;h++){var f=a[h];!c||"function"!==typeof c.scaleFactor||"marker"!==f.type&&"text"!==f.type||(c.scaleFactor=c.scaleFactor(b,e,d));var w=this._getRasterizedResource(f,b,c,e,d);null!=w&&g.push({cimLayer:f,rasterizedResource:w})}return this.getSymbolImage(g,b,c,e,d)};q.prototype.getSymbolImage=function(a,b,c,e,d){for(var g=document.createElement("canvas"),h=
g.getContext("2d"),l=0,q=0,u=0,n=0,p=[],v=0;v<a.length;v++){var r=a[v],m=r.rasterizedResource;if(m){var k=r.cimLayer;if("line"!==k.type&&"fill"!==k.type){var t=c.targetSize?c.targetSize/k.referenceSize:c.scaleFactor?c.scaleFactor:1,D=m.size,K=f.evaluateValueOrFunction(k.offsetX,b,e,d)*t,t=f.evaluateValueOrFunction(k.offsetY,b,e,d)*t,K=K?K:0,t=t?t:0,L=r.rasterizedResource.anchorX,r=r.rasterizedResource.anchorY,C=!1,H=k.type,z=void 0;"marker"===k.type&&(z=f.evaluateValueOrFunction(k.rotation,b,e,d),
C=k.rotateClockwise?k.rotateClockwise:!1);if("text"===k.type){z=f.evaluateValueOrFunction(k.angle,b,e,d);if(void 0!==k.horizontalAlignment)switch(k.horizontalAlignment){case "left":L=-.5;break;case "right":L=.5;break;default:L=0}if(void 0!==k.verticalAlignment)switch(k.verticalAlignment){case "top":r=.5;break;case "bottom":r=-.5;break;case "baseline":r=-.25;break;default:r=0}}var k=w.pt2px(K)-D[0]*(.5+L),A=w.pt2px(t)-D[1]*(.5+r),E=k+D[0],y=A+D[1];if(z){C&&(z=-z);var x=Math.sin(z*Math.PI/180),B=Math.cos(z*
Math.PI/180),D=k*B-A*x,F=k*x+A*B,G=k*B-y*x,I=k*x+y*B,J=E*B-y*x,y=E*x+y*B,M=E*B-A*x,x=E*x+A*B,k=Math.min(D,G,J,M),A=Math.min(F,I,y,x),E=Math.max(D,G,J,M),y=Math.max(F,I,y,x)}l=k<l?k:l;q=A<q?A:q;u=E>u?E:u;n=y>n?y:n;k=h.createImageData(m.size[0],m.size[1]);k.data.set(new Uint8ClampedArray(m.image.buffer));m={offsetX:K,offsetY:t,rotateClockwise:C,type:H,angle:z,rasterizedImage:k,anchorX:L,anchorY:r};p.push(m)}}}g.width=u-l;g.height=n-q;a=-l;for(v=0;v<p.length;v++)m=p[v],b=this._imageDataToCanvas(m.rasterizedImage),
c=a-m.rasterizedImage.width*(.5+m.anchorX),e=n-m.rasterizedImage.height*(.5-m.anchorY),m.angle?(d=(360-m.angle)*Math.PI/180,h.save(),h.translate(w.pt2px(m.offsetX),-w.pt2px(m.offsetY)),h.translate(a,n),h.rotate(d),h.translate(-a,-n),h.drawImage(b,c,e),h.restore()):h.drawImage(b,c+w.pt2px(m.offsetX),e-w.pt2px(m.offsetY));p=new R.default({x:a/g.width-.5,y:n/g.height-.5});return{imageData:h.getImageData(0,0,g.width,g.height),anchorPosition:p}};q.prototype._imageDataToCanvas=function(a){this._imageDataCanvas||
(this._imageDataCanvas=document.createElement("canvas"));var b=this._imageDataCanvas,c=b.getContext("2d");b.width=a.width;b.height=a.height;c.putImageData(a,0,0);return b};q.prototype._imageTo32Array=function(a,b,c){this._imageDataCanvas||(this._imageDataCanvas=document.createElement("canvas"));var e=this._imageDataCanvas,d=e.getContext("2d");e.width=b;e.height=c;d.drawImage(a,0,0,b,c);return new Uint32Array(d.getImageData(0,0,b,c).data.buffer)};q.prototype._getRasterizedResource=function(a,b,c,e,
d){var g;if("text"===a.type)g=a.cim,a=this._rasterizeTextResource(a,b,c,e,d);else{var h=this._resourceCache,l=void 0;"function"===typeof a.materialHash?(l=a.materialHash,l=l(b,e,d),g=G.analyzeCIMResource(a.cim,a.materialOverrides)):(l=a.materialHash,c&&(l+=JSON.stringify(c)),g=a.cim);if(h.has(l))return h.get(l);c=c.targetSize?c.targetSize/a.referenceSize:c.scaleFactor?c.scaleFactor:1;g.size*=c;if("CIMPictureMarker"===a.cim.type){d=f.evaluateValueOrFunction(a.cim.size,b,e,d)*c;b=this._pictureMarkerCache.get(a.materialHash);
if(!b)return null;c=b.height/b.width;e=1<c?w.pt2px(d):w.pt2px(d)/c;d=1<c?w.pt2px(d)*c:w.pt2px(d);a={image:this._imageTo32Array(b,e,d),size:[e,d],sdf:!1,simplePattern:!1,anchorX:a.anchorPoint?a.anchorPoint.x:0,anchorY:a.anchorPoint?a.anchorPoint.y:0}}else a=this._rasterizer.rasterizeJSONResource(g,this._avoidSDF);h.set(l,a)}return a};q.prototype._rasterizeTextResource=function(a,b,c,e,d){var g=c.targetSize?c.targetSize/a.referenceSize:c.scaleFactor?c.scaleFactor:1;c=f.evaluateValueOrFunction(a.text,
b,e,d);if(!c||0===c.length)return null;var h=f.evaluateValueOrFunction(a.fontName,b,e,d),l=f.evaluateValueOrFunction(a.style,b,e,d),q=f.evaluateValueOrFunction(a.weight,b,e,d),u=f.evaluateValueOrFunction(a.decoration,b,e,d),g=f.evaluateValueOrFunction(a.size,b,e,d)*g,n=f.evaluateValueOrFunction(a.horizontalAlignment,b,e,d),p=f.evaluateValueOrFunction(a.verticalAlignment,b,e,d),v=f.colorToArray(f.evaluateValueOrFunction(a.color,b,e,d)),r=f.colorToArray(f.evaluateValueOrFunction(a.outlineColor,b,e,
d));a=f.evaluateValueOrFunction(a.outlineSize,b,e,d);return this._textRasterizer.rasterizeText(c,{color:v,size:g,horizontalAlignment:n,verticalAlignment:p,font:{family:h,style:l,weight:q,decoration:u},halo:{size:a||0,color:r,style:l},pixelRatio:1,premultiplyColors:!this._avoidSDF})};return q}()});