// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/decorateHelper ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/assignHelper ../../core/Accessor ../../core/Evented ../../core/Logger ../../core/maybe ../../core/screenUtils ../../core/accessorSupport/decorators ../../core/libs/gl-matrix-2/vec2 ../../core/libs/gl-matrix-2/vec3 ../../core/libs/gl-matrix-2/vec3f64 ../../geometry/support/webMercatorUtils ../../support/elevationInfoUtils ../../symbols/support/defaults ../../symbols/support/ElevationInfo ../../views/support/drapedUtils".split(" "),
function(h,l,d,n,E,p,q,r,f,k,c,t,u,v,m,w,x,y,z){Object.defineProperty(l,"__esModule",{value:!0});var A=r.getLogger("esri.views.interactive.GraphicManipulator");h=function(h){function b(a){a=h.call(this,a)||this;a.layer=null;a.interactive=!0;a.selectable=!1;a.dragging=!1;a.cursor=null;a.events=new q({target:a});a._circleCollisionCache=null;a._originalSymbol=null;return a}n(b,h);Object.defineProperty(b.prototype,"graphic",{set:function(a){"mesh"===f.get(a.geometry,"type")?A.error("Mesh geometries are not supported"):
(this._circleCollisionCache=null,this._originalSymbol=a.symbol,this._set("graphic",a))},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"elevationInfo",{get:function(){var a="elevationInfo"in this.graphic.layer&&this.graphic.layer.elevationInfo,b=w.getGraphicEffectiveElevationMode(this.graphic);return new y({mode:b,offset:a?a.offset:0})},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"focusedSymbol",{set:function(a){a!==this._get("focusedSymbol")&&(this._set("focusedSymbol",
a),this._updateGraphicSymbol(),this._circleCollisionCache=null)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"grabbing",{set:function(a){if(a!==this._get("grabbing")){var b=this._focused;this._set("grabbing",a);this._updateGraphicSymbol(b)}},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"hovering",{set:function(a){if(a!==this._get("hovering")){var b=this._focused;this._set("hovering",a);this._updateGraphicSymbol(b)}},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,
"selected",{set:function(a){a!==this._get("selected")&&(this._set("selected",a),this._updateGraphicSymbol())},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"_focused",{get:function(){return this._get("hovering")||this._get("grabbing")},enumerable:!0,configurable:!0});b.prototype.destroy=function(){this._resetGraphicSymbol();this._set("view",null)};b.prototype.intersectionDistance=function(a){var b=this._get("graphic");if(!1===b.visible)return null;var g=this._get("focusedSymbol"),
g=f.isSome(g)?g:b.symbol,c=b.geometry;if(f.isNone(c))return null;var e=this._get("view");return"2d"===e.type?this._intersectDistance2D(a,e,c,g):this._intersectDistance3D(a,e,b)};b.prototype.attach=function(){f.isNone(this.layer)||this.layer.add(this.graphic)};b.prototype.detach=function(){this._resetGraphicSymbol();f.isNone(this.layer)||this.layer.remove(this.graphic)};b.prototype._updateGraphicSymbol=function(a){void 0===a&&(a=this._focused);a!==this._focused&&(a=this.graphic.symbol,a!==this._originalSymbol&&
a!==this.focusedSymbol&&(this._originalSymbol=a));this.graphic.symbol=this._focused&&f.isSome(this.focusedSymbol)?this.focusedSymbol:this._originalSymbol};b.prototype._resetGraphicSymbol=function(){this.graphic.symbol=this._originalSymbol};b.prototype._intersectDistance2D=function(a,b,c,d){d=d||x.getDefaultSymbol2D(c);if(f.isNone(d))return null;var e=this._circleCollisionCache;if("point"!==c.type||"simple-marker"!==d.type)return e=z.intersectsDrapedGeometry(a,c,b),f.isSome(e)?1:null;if(f.isNone(e)||
!e.originalPoint.equals(c)){var g=b.spatialReference;m.canProject(c,g)&&(e=m.project(c,g),this._circleCollisionCache=e={originalPoint:c.clone(),mapPoint:e,radiusPx:k.pt2px(d.size)})}return f.isSome(e)?(a=k.screenPointObjectToArray(a,B),b=b.state.toScreen(C,e.mapPoint.x,e.mapPoint.y),e=e.radiusPx,t.vec2.squaredDistance(a,b)<e*e?1:null):null};b.prototype._intersectDistance3D=function(a,b,c){a=b.toMap(a,{include:[c]});if(!a)return null;c=D;return b.renderCoordsHelper.toRenderCoords(a,c)?u.vec3.distance(c,
b.state.camera.eye):null};d([c.property({constructOnly:!0,nonNullable:!0})],b.prototype,"graphic",null);d([c.property({readOnly:!0,dependsOn:["graphic"]})],b.prototype,"elevationInfo",null);d([c.property({constructOnly:!0,nonNullable:!0})],b.prototype,"view",void 0);d([c.property({value:null})],b.prototype,"focusedSymbol",null);d([c.property({constructOnly:!0})],b.prototype,"layer",void 0);d([c.property()],b.prototype,"interactive",void 0);d([c.property()],b.prototype,"selectable",void 0);d([c.property({value:!1})],
b.prototype,"grabbing",null);d([c.property()],b.prototype,"dragging",void 0);d([c.property()],b.prototype,"hovering",null);d([c.property({value:!1})],b.prototype,"selected",null);d([c.property()],b.prototype,"cursor",void 0);return b=d([c.subclass("esri.views.interactive.GraphicManipulator")],b)}(c.declared(p));l.GraphicManipulator=h;var D=v.vec3f64.create(),B=k.createScreenPointArray(),C=k.createScreenPointArray()});