// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../core/iteratorUtils ../../core/mathUtils ../../core/maybe ../../core/screenUtils ./interactiveToolUtils".split(" "),function(p,q,u,r,g,k,t){Object.defineProperty(q,"__esModule",{value:!0});p=function(){function h(){this._hoveredManipulators=new Map;this._grabbedManipulators=new Map;this._draggedManipulators=new Map;this._stopDrag=!1;this._cursor=this._revertToActiveTool=null}Object.defineProperty(h.prototype,"cursor",{get:function(){return this._cursor},enumerable:!0,
configurable:!0});h.prototype.handleInputEvent=function(a,d){var f=function(){return a.stopPropagation()};switch(a.type){case "drag":0<this._grabbedManipulators.size&&(this._stopDrag=!0);this._stopDrag&&(f(),"end"===a.action&&(this._stopDrag=!1));break;case "pointer-down":if("mouse"===a.pointerType&&0!==a.button||a.native.shiftKey)break;var b=k.createScreenPointFromEvent(a),c=this._intersect(b,a.pointerType,d.forEachTool);if(g.isNone(c))break;var e=this._findManipulatorByKey(c,d.forEachTool);g.isSome(e)&&
e.interactive&&!e.grabbing&&(this._grabbedManipulators.set(a.pointerId,{key:c,start:b}),1===this._grabbedManipulators.size&&(this._revertToActiveTool=d.activeTool,d.setActiveTool(c.tool)),e.grabbing=!0,e.events.emit("grab",{action:"start",screenPoint:b}),f());break;case "pointer-up":this._handlePointerEnd(a,d);break;case "pointer-drag":if("mouse"===a.pointerType&&0!==a.button)break;var l=this._grabbedManipulators.get(a.pointerId),e=this._draggedManipulators.get(a.pointerId),c=g.applySome(l||e,function(a){return a.key}),
m=this._findManipulatorByKey(c,d.forEachTool);if(g.isNone(m))break;b=k.createScreenPointFromEvent(a);b.x=r.clamp(b.x,0,d.view.width);b.y=r.clamp(b.y,0,d.view.height);l=g.expect(l||e).start;b={action:a.action,start:l,screenPoint:b};switch(a.action){case "start":case "update":if("update"===b.action||1===this._grabbedManipulators.size)m.dragging=!0,e||(b.action="start"),m.events.emit("drag",b),this._draggedManipulators.set(a.pointerId,{key:g.expect(c),start:l});break;case "end":e&&m.events.emit("drag",
b),m.dragging=!1,this._draggedManipulators.delete(a.pointerId),this._handlePointerEnd(a,d)}f();break;case "immediate-click":b=k.createScreenPointFromEvent(a);c=this._intersect(b,a.pointerType,d.forEachTool);e=this._findToolAndManipulatorByKey(c,d.forEachTool,n);a.native.shiftKey||d.forEachTool(function(a){if(a.manipulators){var c=!1;a.manipulators.forEach(function(a){a=a.manipulator;a.selected&&(a.selected=!1,c=!0)});c&&a.manipulatorSelectionChanged&&a.manipulatorSelectionChanged()}});if(!e)break;
e=n.manipulator;c=n.tool;if(!e.interactive)break;e.selectable&&(e.selected=!e.selected,c.manipulatorSelectionChanged&&c.manipulatorSelectionChanged());c=a.native.shiftKey;e.events.emit("immediate-click",{screenPoint:b,button:a.button,pointerType:a.pointerType,shiftKey:c,stopPropagation:f});break;case "click":b=k.createScreenPointFromEvent(a);c=this._intersect(b,a.pointerType,d.forEachTool);e=this._findManipulatorByKey(c,d.forEachTool);if(g.isNone(e)||!e.interactive)break;c=a.native.shiftKey;e.events.emit(a.type,
{screenPoint:b,button:a.button,pointerType:a.pointerType,shiftKey:c});f();break;case "double-click":b=k.createScreenPointFromEvent(a),c=this._intersect(b,a.pointerType,d.forEachTool),e=this._findManipulatorByKey(c,d.forEachTool),!g.isNone(e)&&e.interactive&&(c=a.native.shiftKey,e.events.emit("double-click",{screenPoint:b,button:a.button,pointerType:a.pointerType,shiftKey:c,stopPropagation:f}))}this._updateCursor(d.forEachTool)};h.prototype._handlePointerEnd=function(a,d){var f=g.applySome(this._grabbedManipulators.get(a.pointerId),
function(a){return a.key}),b=this._findManipulatorByKey(f,d.forEachTool);g.isSome(b)&&!b.dragging&&(f=g.isSome(d.creatingTool)&&d.creatingTool===g.expect(f).tool,1!==this._grabbedManipulators.size||0!==this._draggedManipulators.size||f||(d.setActiveTool(this._revertToActiveTool),this._revertToActiveTool=null),b.grabbing&&(b.grabbing=!1,b.events.emit("grab",{action:"end",screenPoint:k.createScreenPointFromEvent(a)})),this._grabbedManipulators.delete(a.pointerId))};h.prototype._cursorFromMap=function(a,
d){var f=this,b=null;u.someMap(a,function(a){a=f._findManipulatorByKey(a.key,d);return g.isSome(a)&&a.interactive&&"cursor"in a&&a.cursor?(b=a.cursor,!0):!1});return b};h.prototype._updateCursor=function(a){this._cursor=0<this._grabbedManipulators.size?this._cursorFromMap(this._grabbedManipulators,a)||"grabbing":0<this._hoveredManipulators.size?this._cursorFromMap(this._hoveredManipulators,a)||"pointer":null};h.prototype.clearPointers=function(a,d,f,b){var c=this;void 0===f&&(f=!0);var e=function(c){return c.tool===
a&&(g.isNone(b)||c.manipulatorId===b)};this._grabbedManipulators.forEach(function(a,b){a=a.key;e(a)&&(c._grabbedManipulators.delete(b),b=c._findManipulatorByKey(a,d),g.isSome(b)&&(b.grabbing=!1,b.events.emit("grab",{action:"end",screenPoint:null})))});this._draggedManipulators.forEach(function(a,b){a=a.key;e(a)&&(c._draggedManipulators.delete(b),b=c._findManipulatorByKey(a,d),g.isSome(b)&&(b.dragging=!1))});f&&this._hoveredManipulators.forEach(function(a,b){a=a.key;e(a)&&(c._hoveredManipulators.delete(b),
b=c._findManipulatorByKey(a,d),g.isSome(b)&&(b.hovering=!1))});this._updateCursor(d)};h.prototype._intersect=function(a,d,f){var b=null;f(function(c){if(null==c.manipulators||!t.areToolManipulatorsEditable(c))return!1;var e=c.manipulators.intersect(a,d);if(g.isNone(e))return!1;b={manipulatorId:e,tool:c};return!0});return b};h.prototype.handleHoverEvent=function(a,d){if(("pointer-up"===a.type||"immediate-click"===a.type||"pointer-move"===a.type)&&"touch"!==a.pointerType){var f=g.applySome(this._hoveredManipulators.get(a.pointerId),
function(a){return a.key}),f=this._findManipulatorByKey(f,d),b=this._intersect(k.createScreenPointFromEvent(a),a.pointerType,d),c=this._findManipulatorByKey(b,d);g.isSome(c)&&!c.interactive&&(c=null);f!==c&&(g.isSome(f)&&(f.hovering=!1),g.isSome(c)?(c.hovering=!0,this._hoveredManipulators.set(a.pointerId,{key:g.expect(b)})):this._hoveredManipulators.delete(a.pointerId),this._updateCursor(d))}};h.prototype._findManipulatorByKey=function(a,d){return this._findToolAndManipulatorByKey(a,d,n)?n.manipulator:
null};h.prototype._findToolAndManipulatorByKey=function(a,d,f){if(g.isNone(a))return null;f.tool=null;f.manipulator=null;d(function(b){if(b!==a.tool||null==b.manipulators||!t.areToolManipulatorsEditable(b))return!1;var c=b.manipulators.findById(a.manipulatorId);return g.isSome(c)?(f.manipulator=c,f.tool=b,!0):!1});return null!=f.manipulator};return h}();q.default=p;var n={manipulator:null,tool:null}});