// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/assignHelper ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../.. ../../../Color ../../../core/Error ../../../core/maybe ./support/utils ../statistics/heatmapStatistics ../support/utils ../symbology/heatmap ../../support/HeatmapColorStop".split(" "),function(M,q,G,m,h,H,E,r,t,y,I,n,z,w){function J(b){return h(this,void 0,void 0,function(){var a,c,d,e,f,g,k,u,v;return m(this,function(p){switch(p.label){case 0:if(!(b&&b.layer&&
b.view))throw new r("heatmap-renderer:missing-parameters","'layer' and 'view' parameters are required");a=b.blurRadius;c=b.minRatio;d=b.maxRatio;e=b.fadeToTransparent;f=G({},b);f.blurRadius=null==a?10:a;f.minRatio=null==c?.01:c;f.maxRatio=null==d?1:d;f.fadeToTransparent=null==e?!0:e;g=[0,2,1];k=n.createLayerAdapter(f.layer,g);f.layer=k;if(!k)throw new r("heatmap-renderer:invalid-parameters","'layer' must be one of these types: "+n.getLayerTypeLabels(g).join(", "));return[4,k.load()];case 1:return p.sent(),
[4,n.getFieldsList({field:f.field})];case 2:u=p.sent();if(v=y.verifyBasicFieldValidity(k,u,"heatmap-renderer:invalid-parameters"))throw v;return[2,f]}})})}function K(b){return h(this,void 0,void 0,function(){var a,c,d,e,f;return m(this,function(g){switch(g.label){case 0:return a=b.scheme,d=c=null,[4,y.getBasemapInfo(b.basemap,b.view)];case 1:e=g.sent();c=t.isSome(e.basemapId)?e.basemapId:null;d=t.isSome(e.basemapTheme)?e.basemapTheme:null;if(a)return[2,{scheme:z.cloneScheme(a),basemapId:c,basemapTheme:d}];
if(f=z.getSchemes({basemap:c,basemapTheme:d}))a=f.primaryScheme,c=f.basemapId,d=f.basemapTheme;return[2,{scheme:a,basemapId:c,basemapTheme:d}]}})})}function L(b,a){return h(this,void 0,void 0,function(){var c,d,e,f,g,k,u,v,p,h,n,q,r,x,A,t,B,F,l,C,D;return m(this,function(m){switch(m.label){case 0:return c=b.fieldOffset,d=a.field,e=a.basemap,f=a.blurRadius,g=a.minRatio,k=a.maxRatio,u=a.fadeToTransparent,v=a.heatmapScheme,p=a.view,[4,K({basemap:e,scheme:v,view:p})];case 1:return h=m.sent(),n=h.scheme,
q=h.basemapId,r=h.basemapTheme,x=n.colors,A=x.length,B=(t=!b.count)?[0,100]:[b.min,b.max],F=(k-g)/(A-1),l=x[0],C=[new w.HeatmapColorStop({ratio:0,color:new E([l.r,l.g,l.b,0])}),new w.HeatmapColorStop({ratio:.01,color:new E([l.r,l.g,l.b,0])}),new w.HeatmapColorStop({ratio:u?g:.01,color:l})],y.createColors(x,A).forEach(function(a,b){C.push(new w.HeatmapColorStop({ratio:g+F*b,color:a}))}),D=new H.HeatmapRenderer({blurRadius:f,colorStops:C,field:d,minPixelIntensity:B[0],maxPixelIntensity:B[1]}),null!=
c&&(D.fieldOffset=c),[2,{renderer:D,statistics:b,defaultValuesUsed:t,scheme:z.cloneScheme(n),basemapId:q,basemapTheme:r}]}})})}Object.defineProperty(q,"__esModule",{value:!0});q.createRenderer=function(b){return h(this,void 0,void 0,function(){var a,c,d;return m(this,function(e){switch(e.label){case 0:return[4,J(b)];case 1:a=e.sent();if(!a.statistics)return[3,2];d=a.statistics;return[3,4];case 2:return[4,I({layer:a.layer,field:a.field,fieldOffset:a.fieldOffset,blurRadius:a.blurRadius,view:a.view})];
case 3:d=e.sent(),e.label=4;case 4:return c=d,[2,L(c,a)]}})})}});