// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/assignHelper ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper dojo/i18n!../../nls/smartMapping ../../../core/Error ../../../core/maybe ../../../core/promiseUtils ./size ./type ./support/utils ../heuristics/outline ../statistics/predominantCategories ../statistics/summaryStatistics ../statistics/support/predominanceUtils ../support/utils ../symbology/predominance ../../support/AuthoringInfo ../../support/AuthoringInfoVisualVariable ../../support/numberUtils ../../visualVariables/OpacityVariable".split(" "),
function(ha,y,S,f,n,H,k,z,M,T,U,m,V,W,X,Y,A,B,N,Z,aa,ba){function ca(b){return n(this,void 0,void 0,function(){var a,c,e,d,g,h,u;return f(this,function(l){switch(l.label){case 0:if(!(b&&b.layer&&b.view&&b.fields&&b.fields.length))throw new k("predominance-renderer:missing-parameters","'layer', 'view' and 'fields' parameters are required");if(2>b.fields.length)throw new k("predominance-renderer:invalid-parameters","Minimum 2 fields are required");if(10<b.fields.length)throw new k("predominance-renderer:invalid-parameters",
"Maximum 10 fields are supported");a=S({},b);a.symbolType=a.symbolType||"2d";a.defaultSymbolEnabled=null==a.defaultSymbolEnabled?!0:a.defaultSymbolEnabled;a.includeOpacityVariable=b.includeOpacityVariable||!1;a.includeSizeVariable=b.includeSizeVariable||!1;a.sortBy=null==a.sortBy?"count":a.sortBy;c=[0,2,1,3];e=A.createLayerAdapter(a.layer,c);a.layer=e;if(!e)throw new k("predominance-renderer:invalid-parameters","'layer' must be one of these types: "+A.getLayerTypeLabels(c).join(", "));return[4,e.load()];
case 1:l.sent();d=e.geometryType;g=-1<a.symbolType.indexOf("3d");a.outlineOptimizationEnabled="polygon"===d?a.outlineOptimizationEnabled:!1;a.includeSizeVariable||(a.sizeOptimizationEnabled="point"===d||"multipoint"===d||"polyline"===d?a.sizeOptimizationEnabled:!1);if("mesh"===d)a.symbolType="3d-volumetric",a.colorMixMode=a.colorMixMode||"replace",a.edgesType=a.edgesType||"none",a.sizeOptimizationEnabled=!1;else{if(g&&("polyline"===d||"polygon"===d))throw new k("predominance-renderer:not-supported",
"3d symbols are not supported for polyline and polygon layers");if(-1<a.symbolType.indexOf("3d-volumetric")&&(!a.view||"3d"!==a.view.type))throw new k("predominance-renderer:invalid-parameters","'view' parameter should be an instance of SceneView when 'symbolType' parameter is '3d-volumetric' or '3d-volumetric-uniform'");}h=a.fields.map(function(a){return a.name});if(u=m.verifyBasicFieldValidity(e,h,"predominance-renderer:invalid-parameters"))throw u;return[2,a]}})})}function da(b){return n(this,
void 0,void 0,function(){var a,c,e,d,g;return f(this,function(h){switch(h.label){case 0:return a=b.predominanceScheme,e=c=null,[4,m.getBasemapInfo(b.basemap,b.view)];case 1:d=h.sent();c=z.isSome(d.basemapId)?d.basemapId:null;e=z.isSome(d.basemapTheme)?d.basemapTheme:null;if(a)return[2,{scheme:B.cloneScheme(a),basemapId:c,basemapTheme:e}];if(g=B.getSchemes({basemap:c,basemapTheme:e,geometryType:b.geometryType,numColors:b.numColors,theme:b.theme,worldScale:b.worldScale,view:b.view}))a=g.primaryScheme,
c=g.basemapId,e=g.basemapTheme;return[2,{scheme:a,basemapId:c,basemapTheme:e}]}})})}function ea(b,a,c,e){return n(this,void 0,void 0,function(){var d,g,h,u,l,O,P,q,r,v,w,p,t,Q,R,k,n,D,I,E,J,F,G,x,C,y,K,L,z,A,B;return f(this,function(f){switch(f.label){case 0:return d=b.layer,g={layer:b.layer,view:b.view},P=(O=M).all,q=[W({layer:d,fields:e,view:b.view})],b.outlineOptimizationEnabled?[4,V(g)]:[3,2];case 1:return r=f.sent(),[3,3];case 2:r=null,f.label=3;case 3:return[4,P.apply(O,[q.concat([r])])];case 4:return h=
f.sent(),u=h[0],l=h[1],(v=u)&&u.predominantCategoryInfos||(v={predominantCategoryInfos:e.map(function(a){return{value:a,count:0}})}),w=l&&l.opacity,[4,U.createRenderer({layer:d,basemap:b.basemap,valueExpression:a.valueExpression,valueExpressionTitle:H.predominantCategory,numTypes:-1,defaultSymbolEnabled:b.defaultSymbolEnabled,sortBy:b.sortBy,typeScheme:c,statistics:{uniqueValueInfos:v.predominantCategoryInfos},legendOptions:b.legendOptions,outlineOptimizationEnabled:!1,sizeOptimizationEnabled:b.includeSizeVariable&&
b.sizeOptimizationEnabled?!1:b.sizeOptimizationEnabled,symbolType:b.symbolType,colorMixMode:b.colorMixMode,edgesType:b.edgesType,view:b.view})];case 5:p=f.sent();t=p.renderer;Q=p.basemapId;R=p.basemapTheme;k=p.uniqueValueInfos;n=p.excludedUniqueValueInfos;D=t.uniqueValueInfos;I={};E=0;for(J=b.fields;E<J.length;E++)F=J[E],G=d.getField(F.name),I[G.name]=F.label||G&&G.alias||F.name;D.forEach(function(a,b){var c=I[a.value];a.label=c;k[b].label=c});b.includeSizeVariable&&(x=d.geometryType,C=null,"polygon"===
x?(y=c,K=y.sizeScheme,L=K.background,t.backgroundFillSymbol=m.createSymbol(x,{type:b.symbolType,color:L.color,outline:m.getSymbolOutlineFromScheme(L,x,w)}),C=K.marker.size,x="point"):"polyline"===x?(z=c,C=z.width):(A=c,C=A.size),B=m.createColors(c.colors,D.length),D.forEach(function(a,d){var e=m.createSymbol(x,{type:b.symbolType,color:B[d],size:C,outline:m.getSymbolOutlineFromScheme(c,x,w),meshInfo:{colorMixMode:b.colorMixMode,edgesType:b.edgesType}});a.symbol=e;k[d].symbol=e.clone()}));l&&l.visualVariables&&
l.visualVariables.length&&(t.visualVariables=l.visualVariables.map(function(a){return a.clone()}));t.authoringInfo=new N({type:"predominance",fields:e.slice()});return[2,{renderer:t,predominantCategoryInfos:k,excludedCategoryInfos:n,predominanceScheme:c,basemapId:Q,basemapTheme:R}]}})})}function fa(b,a,c){return T.createVisualVariables({layer:b.layer,basemap:b.basemap,valueExpression:a.valueExpression,sqlExpression:a.statisticsQuery.sqlExpression,sqlWhere:a.statisticsQuery.sqlWhere,sizeScheme:c,sizeOptimizationEnabled:b.sizeOptimizationEnabled,
worldScale:-1<b.symbolType.indexOf("3d-volumetric"),legendOptions:{title:H.sumOfCategories},view:b.view})}function ga(b,a){return n(this,void 0,void 0,function(){var c,e,d,g,h,u,l,k;return f(this,function(f){switch(f.label){case 0:return[4,X({layer:b.layer,valueExpression:a.valueExpression,sqlExpression:a.statisticsQuery.sqlExpression,sqlWhere:a.statisticsQuery.sqlWhere,view:b.view})];case 1:return c=f.sent(),e=null==c.avg||null==c.stddev,d=1/b.fields.length*100,g=e?100:c.avg+1.285*c.stddev,100<g&&
(g=100),h=aa.round([d,g],{strictBounds:!0}),u=new ba({valueExpression:a.valueExpression,stops:[{value:h[0],opacity:.15},{value:h[1],opacity:1}],legendOptions:{title:H.strengthOfPredominance}}),l=new Z({type:"opacity",minSliderValue:c.min,maxSliderValue:c.max}),k=new N({visualVariables:[l]}),[2,{visualVariable:u,statistics:c,defaultValuesUsed:e,authoringInfo:k}]}})})}Object.defineProperty(y,"__esModule",{value:!0});y.createRenderer=function(b){return n(this,void 0,void 0,function(){var a,c,e,d,g,h,
k,l,n,m,q,r,v,w,p,t;return f(this,function(f){switch(f.label){case 0:return[4,ca(b)];case 1:return a=f.sent(),c=a.layer,[4,da({basemap:a.basemap,geometryType:c.geometryType,numColors:a.fields.length,predominanceScheme:a.predominanceScheme,worldScale:-1<a.symbolType.indexOf("3d-volumetric"),view:a.view})];case 2:return e=f.sent(),d=e.scheme,g=a.fields.map(function(a){return a.name}),h=Y.getPredominanceExpressions(c,g),k=ea(a,h.predominantCategory,d,g),l=a.includeSizeVariable?fa(a,h.size,d.sizeScheme):
null,n=a.includeOpacityVariable?ga(a,h.opacity):null,[4,M.all([k,l,n])];case 3:return m=f.sent(),q=m[0],r=m[1],v=m[2],w=[],p=[],r&&(Array.prototype.push.apply(w,r.visualVariables.map(function(a){return a.clone()})),delete r.sizeScheme,q.size=r,Array.prototype.push.apply(p,r.authoringInfo.visualVariables.map(function(a){return a.clone()}))),v&&(w.push(v.visualVariable.clone()),q.opacity=v,Array.prototype.push.apply(p,v.authoringInfo.visualVariables.map(function(a){return a.clone()}))),w.length&&(t=
q.renderer.visualVariables||[],Array.prototype.push.apply(t,w),q.renderer.visualVariables=t,q.renderer.authoringInfo.visualVariables=p),[2,q]}})})}});