// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/assignHelper ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper dojo/i18n!../../nls/smartMapping ../.. ../../../pointCloudRenderers ../../../core/Error ../../../core/lang ../../../core/maybe ../../../core/promiseUtils ./support/utils ../heuristics/outline ../heuristics/sizeRange ../statistics/uniqueValues ../support/utils ../symbology/type ../../support/LegendOptions ../../support/utils".split(" "),function(ca,u,D,q,n,Q,R,
w,k,x,K,S,l,T,U,L,p,E,V,F){function W(d){return n(this,void 0,void 0,function(){var a,b,c,e,f,g;return q(this,function(h){switch(h.label){case 0:if(!d||!d.layer||!d.field&&!d.valueExpression)throw new k("type-renderer:missing-parameters","'layer' and 'field' or 'valueExpression' parameters are required");if(d.valueExpression&&!d.view)throw new k("type-renderer:missing-parameters","View is required when 'valueExpression' is specified");a=D({},d);a.symbolType=a.symbolType||"2d";a.numTypes=null==a.numTypes?
10:a.numTypes;a.defaultSymbolEnabled=null==a.defaultSymbolEnabled?!0:a.defaultSymbolEnabled;a.sortBy=null==a.sortBy?"count":a.sortBy;a.sortEnabled=null==a.sortEnabled?!0:a.sortEnabled;a.statistics=x.clone(a.statistics);b=[0,2,1,3];c=p.createLayerAdapter(a.layer,b);a.layer=c;if(!c)throw new k("type-renderer:invalid-parameters","'layer' must be one of these types: "+p.getLayerTypeLabels(b).join(", "));return[4,c.load()];case 1:h.sent();e=c.geometryType;a.outlineOptimizationEnabled="polygon"===e?a.outlineOptimizationEnabled:
!1;a.sizeOptimizationEnabled="point"===e||"multipoint"===e||"polyline"===e?a.sizeOptimizationEnabled:!1;if("mesh"===e)a.symbolType="3d-volumetric",a.colorMixMode=a.colorMixMode||"replace",a.edgesType=a.edgesType||"none";else{if("3d-volumetric-uniform"===a.symbolType&&"point"!==e)throw new k("type-renderer:not-supported","3d-volumetric-uniform symbols are supported for point layers only");if(-1<a.symbolType.indexOf("3d-volumetric")&&(!a.view||"3d"!==a.view.type))throw new k("type-renderer:invalid-parameters",
"'view' parameter should be an instance of SceneView when 'symbolType' parameter is '3d-volumetric' or '3d-volumetric-uniform'");}return[4,p.getFieldsList({field:a.field,valueExpression:a.valueExpression})];case 2:f=h.sent();if(g=l.verifyBasicFieldValidity(c,f,"type-renderer:invalid-parameters"))throw g;return[2,a]}})})}function X(d){return n(this,void 0,void 0,function(){var a,b,c,e,f;return q(this,function(g){switch(g.label){case 0:if(!(d&&d.layer&&d.field))throw new k("type-point-cloud-class-renderer:missing-parameters",
"'layer' and 'field' parameters are required");a=D({},d);a.statistics=x.clone(a.statistics);b=[4];c=p.createLayerAdapter(a.layer,b);a.layer=c;a.density=a.density||25;a.size=a.size||"100%";if(!l.isValidPointSize(a.size))throw new k("type-point-cloud-class-renderer:invalid-parameters","Invalid 'size' parameter. It should be a string of the form '100%'");if(!c)throw new k("type-point-cloud-class-renderer:invalid-parameters","'layer' must be one of these types: "+p.getLayerTypeLabels(b).join(", "));return[4,
c.load()];case 1:return g.sent(),[4,p.getFieldsList({field:a.field})];case 2:e=g.sent();if(f=l.verifyBasicFieldValidity(c,e,"type-point-cloud-class-renderer:invalid-parameters"))throw f;return[2,a]}})})}function M(d){return n(this,void 0,void 0,function(){var a,b,c,e,f;return q(this,function(g){switch(g.label){case 0:return a=d.typeScheme,c=b=null,[4,l.getBasemapInfo(d.basemap,d.view)];case 1:e=g.sent();b=K.isSome(e.basemapId)?e.basemapId:null;c=K.isSome(e.basemapTheme)?e.basemapTheme:null;if(a)return[2,
{scheme:E.cloneScheme(a),basemapId:b,basemapTheme:c}];if(f=E.getSchemes({basemap:b,basemapTheme:c,geometryType:d.geometryType,theme:d.theme,worldScale:d.worldScale,view:d.view}))a=f.primaryScheme,b=f.basemapId,c=f.basemapTheme;return[2,{scheme:a,basemapId:b,basemapTheme:c}]}})})}function N(d,a){return d.label<a.label?-1:d.label>a.label?1:0}function O(d,a){return d.value<a.value?-1:d.value>a.value?1:0}function Y(d,a){var b=a.count-d.count;0===b&&(b=N(d,a));return b}function Z(d,a){var b=a.count-d.count;
0===b&&(b=O(d,a));return b}function P(d,a,b){var c;"count"===a?(c=Z,b&&b.codedValues&&(c=Y)):"value"===a&&(c=O,b&&b.codedValues&&(c=N));c&&d.sort(c)}function aa(d,a,b,c){return n(this,void 0,void 0,function(){var e,f,g,h,G,A,t,B,k,m,n,p,v,u,w,x,C,y,z,r,H,I,J;return q(this,function(q){switch(q.label){case 0:return e=d.uniqueValueInfos,f=a.layer,G=(h=(g=a.field)?f.getField(g):null)?f.getFieldDomain(h.name):null,A=-1===a.numTypes?e.length:a.numTypes,t=f.geometryType,[4,M({basemap:a.basemap,geometryType:t,
typeScheme:a.typeScheme,worldScale:-1<a.symbolType.indexOf("3d-volumetric"),view:a.view})];case 1:B=q.sent();k=B.scheme;m=new R.UniqueValueRenderer({field:g});n=-1;v={value:null,domain:G,fieldInfo:h};e.forEach(function(a,b){v.value=a.value;a.label=F.createUniqueValueLabel(v);null===a.value&&(n=b)});-1<n&&(p=e.splice(n,1)[0]);!1!==a.sortEnabled&&P(e,a.sortBy,G);h&&"date"===h.type&&(u=e.filter(function(a,b){return b<A}),w=u.map(function(a){return a.value}),v.dateFormatInterval=F.calculateDateFormatInterval(w));
x=b&&b.opacity;C=l.createColors(k.colors,e.length);y=l.getSymbolSizeFromScheme(k,t);z=l.getSymbolOutlineFromScheme(k,t,x);e.forEach(function(b,c){v.value=b.value;b.label=F.createUniqueValueLabel(v);b.symbol=l.createSymbol(t,{type:a.symbolType,color:C[c],size:y,outline:z,meshInfo:{colorMixMode:a.colorMixMode,edgesType:a.edgesType}})});a.valueExpression&&(m.valueExpression=a.valueExpression,m.valueExpressionTitle=a.valueExpressionTitle);a.legendOptions&&(m.legendOptions=new V.LegendOptions(a.legendOptions));
C=l.createColors(k.colors,A);for(r=0;r<A;r++)(H=e[r])&&m.addUniqueValueInfo({value:H.value,label:H.label,symbol:l.createSymbol(t,{type:a.symbolType,color:C[r],size:y,outline:z,meshInfo:{colorMixMode:a.colorMixMode,edgesType:a.edgesType}})});a.defaultSymbolEnabled&&(m.defaultSymbol=l.createSymbol(t,{type:a.symbolType,color:k.noDataColor,size:y,outline:z,meshInfo:{colorMixMode:a.colorMixMode,edgesType:a.edgesType}}),m.defaultLabel=Q.other);p&&(p.symbol=l.createSymbol(t,{type:a.symbolType,color:k.noDataColor,
size:y,outline:z,meshInfo:{colorMixMode:a.colorMixMode,edgesType:a.edgesType}}),e.push(p));I=[];J=m.uniqueValueInfos.length===e.length?-1:m.uniqueValueInfos.length;if(-1<J)for(r=J;r<e.length;r++)I.push(D({},e[r]));b&&b.visualVariables&&b.visualVariables.length&&(m.visualVariables=b.visualVariables.map(function(a){return a.clone()}));c&&c.minSize&&(m.visualVariables?m.visualVariables.push(c.minSize):m.visualVariables=[c.minSize]);return[2,{renderer:m,uniqueValueInfos:e,excludedUniqueValueInfos:I,typeScheme:E.cloneScheme(k),
basemapId:B.basemapId,basemapTheme:B.basemapTheme}]}})})}function ba(d,a){return n(this,void 0,void 0,function(){var b,c,e,f,g;return q(this,function(h){switch(h.label){case 0:return b=d.uniqueValueInfos,[4,M({basemap:"gray",theme:"point-cloud-class",geometryType:"point",typeScheme:a})];case 1:return e=(c=h.sent())&&c.scheme,g=(f="point-cloud-class"===e.theme)?e.colors:l.createColors(e.colors,b.length),P(b,"value"),[2,b.map(function(a,b){var c=a.value,d=null;f?(d=g[c])||(d=g[g.length-1]):d=g[b];return{values:[c],
color:d,label:a.label}})]}})})}Object.defineProperty(u,"__esModule",{value:!0});u.createRenderer=function(d){return n(this,void 0,void 0,function(){var a,b,c,e,f,g,h,k;return q(this,function(l){switch(l.label){case 0:return[4,W(d)];case 1:return a=l.sent(),b=a.layer,c=a.view,e={layer:b,field:a.field,valueExpression:a.valueExpression,returnAllCodedValues:a.returnAllCodedValues,view:c},[4,S.all([null!=a.statistics?a.statistics:L(e),a.outlineOptimizationEnabled?T({layer:b,view:c}):null,a.sizeOptimizationEnabled?
U({layer:b,view:c}):null])];case 2:return f=l.sent(),g=f[0],h=f[1],k=f[2],[2,aa(g,a,h,k)]}})})};u.createPCClassRenderer=function(d){return n(this,void 0,void 0,function(){var a,b,c,e,f,g;return q(this,function(h){switch(h.label){case 0:return[4,X(d)];case 1:a=h.sent();if(null==a.statistics)return[3,2];c=a.statistics;return[3,4];case 2:return[4,L({layer:a.layer,field:a.field})];case 3:c=h.sent(),h.label=4;case 4:return b=c,f=w.PointCloudUniqueValueRenderer.bind,g={field:a.field,pointsPerInch:a.density,
pointSizeAlgorithm:l.getPointSizeAlgorithm(a.size)},[4,ba(b,a.typeScheme)];case 5:return e=new (f.apply(w.PointCloudUniqueValueRenderer,[void 0,(g.colorUniqueValueInfos=h.sent(),g)])),[2,{renderer:e}]}})})}});