// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/tsSupport/assignHelper ../../../../core/maybe ../../../../core/libs/gl-matrix-2/mat3f64 ../../../../core/libs/gl-matrix-2/vec3 ../../../../core/libs/gl-matrix-2/vec3f64 ../../support/buffer/InterleavedLayout ../core/shaderLibrary/DiscardOrAdjustAlpha.glsl ../lib/GLMaterialTexture ../lib/Material ../lib/Util ./internal/bufferWriterUtils ./internal/MaterialUtil ./renderers/InstancedRenderer ./renderers/MergedRenderer ../shaders/DefaultMaterialTechnique ../../../webgl/renderState ../../../webgl/renderState".split(" "),
function(q,S,p,T,z,A,k,m,w,B,n,C,D,E,f,F,G,l,H,g){var t=D.assert;q=function(d){function a(b,e){e=d.call(this,e)||this;e.supportsEdges=!0;e.techniqueConfig=new l.DefaultMaterialTechniqueConfiguration;e.params=f.copyParameters(b,I);e.vertexBufferLayout=a.getVertexBufferLayout(e.params);e.instanceBufferLayout=b.instanced?a.getInstanceBufferLayout(e.params):null;return e}p(a,d);a.prototype.isVisibleInPass=function(b){return 3===b?this.params.castShadows:!0};a.prototype.isVisible=function(){var b=this.params;
if(!d.prototype.isVisible.call(this)||0===b.layerOpacity)return!1;var e=b.instanced,a=b.vertexColors,c=b.symbolColors,e=!!e&&-1<e.indexOf("color"),f=b.vvColorEnabled,g="replace"===b.colorMixMode,k=0<b.opacity,b=b.externalColor&&0<b.externalColor[3];return a&&(e||f||c)?g?!0:k:a?g?b:k:e||f||c?g?!0:k:g?b:k};a.prototype.setParameterValues=function(b){var e=this.params,a;for(a in b)"instanced"===a&&t(b.instanced===e.instanced,"Can not change instanced attributes"),"textureId"===a&&t(e.textureId,"Can only change texture of material that already has a texture"),
"vertexColors"===a&&!0===b[a]&&b[a]!==e[a]&&t(e.vertexColors,"Can not enable vertex colors after DefaultMaterial creation"),e[a]=b[a];this.notifyDirty("matChanged")};a.prototype.getParameters=function(){return this.params};a.prototype.getTechniqueConfig=function(b){this.techniqueConfig.output=b;this.techniqueConfig.hasNormalTexture=!!this.params.normalTextureId;this.techniqueConfig.hasColorTexture=!!this.params.textureId;this.techniqueConfig.vertexTangents=this.params.vertexTangents;this.techniqueConfig.instanced=
!!this.params.instanced;this.techniqueConfig.instancedDoublePrecision=this.params.instancedDoublePrecision;this.techniqueConfig.vvSize=this.params.vvSizeEnabled;this.techniqueConfig.verticalOffset=null!==this.params.verticalOffset;this.techniqueConfig.screenSizePerspective=null!==this.params.screenSizePerspective;this.techniqueConfig.slice=this.params.slicePlaneEnabled;this.techniqueConfig.sliceHighlightDisabled=this.params.sliceHighlightDisabled;this.techniqueConfig.alphaDiscardMode="opaque"===this.params.textureAlphaMode?
1:"mask"===this.params.textureAlphaMode?2:"maskBlend"===this.params.textureAlphaMode?3:0;this.techniqueConfig.normalsTypeDerivate="screenDerivative"===this.params.normals?!0:!1;0===b&&(this.techniqueConfig.treeRendering=!!this.params.treeRendering,this.techniqueConfig.vertexColors=this.params.vertexColors,this.techniqueConfig.symbolColors=this.params.symbolColors,this.techniqueConfig.doubleSidedMode=this.params.doubleSided&&"normal"===this.params.doubleSidedType?1:this.params.doubleSided&&"winding-order"===
this.params.doubleSidedType?2:0,this.techniqueConfig.instancedColor=!!this.params.instanced&&-1<this.params.instanced.indexOf("color"),this.techniqueConfig.receiveShadows=this.params.receiveShadows,this.techniqueConfig.receiveAmbientOcclusion=this.params.receiveSSAO,this.techniqueConfig.vvColor=this.params.vvColorEnabled,this.techniqueConfig.textureAlphaPremultiplied=!!this.params.textureAlphaPremultiplied,this.techniqueConfig.usePBR=this.params.usePBR,this.techniqueConfig.hasMetalnessAndRoughnessTexture=
!!this.params.metallicRoughnessTextureId,this.techniqueConfig.hasEmissionTexture=!!this.params.emissiveTextureId,this.techniqueConfig.hasOcclusionTexture=!!this.params.occlusionTextureId,this.techniqueConfig.offsetBackfaces=!(!this.params.transparent||!this.params.offsetTransparentBackfaces));return this.techniqueConfig};a.prototype.intersect=function(b,e,a,c,d,g,m){if(null!==this.params.verticalOffset){var h=c.camera;k.vec3.set(u,a[12],a[13],a[14]);a=null;switch(c.viewingMode){case "global":a=k.vec3.normalize(x,
u);break;case "local":a=k.vec3.copy(x,J)}var n=0;if(null!==this.params.verticalOffset){var l=k.vec3.subtract(K,u,h.eye),p=k.vec3.length(l),l=k.vec3.scale(l,l,1/p),q=null;this.params.screenSizePerspective&&(q=k.vec3.dot(a,l));n+=f.verticalOffsetAtDistance(h,p,this.params.verticalOffset,q,this.params.screenSizePerspective)}k.vec3.scale(a,a,n);k.vec3.transformMat3(v,a,c.transform.inverseRotation);d=k.vec3.subtract(L,d,v);g=k.vec3.subtract(M,g,v)}f.intersectTriangleGeometry(b,e,c,d,g,z.isSome(c.options.verticalOffset)?
c.options.verticalOffset.object3D:void 0,m)};a.prototype.getGLMaterials=function(){return{color:N,depthShadowMap:O,normal:P,depth:y,highlight:Q}};a.prototype.createRenderer=function(b,e){return this.params.softwareInstanced?new F(b,e,this):new G(b,e,this)};a.prototype.createBufferWriter=function(){return new R(this.vertexBufferLayout,this.instanceBufferLayout)};a.getVertexBufferLayout=function(b){var e=b.textureId||b.normalTextureId||b.metallicRoughnessTextureId||b.emissiveTextureId||b.occlusionTextureId,
a=w.newLayout().vec3f("position").vec3f("normal");b.vertexTangents&&a.vec4f("tangent");e&&a.vec2f("uv0");b.vertexColors&&a.vec4u8("color");b.symbolColors&&a.vec4u8("symbolColor");return a};a.getInstanceBufferLayout=function(b){var a=w.newLayout(),a=b.instancedDoublePrecision?a.vec3f("modelOriginHi").vec3f("modelOriginLo").mat3f("model").mat3f("modelNormal"):a.mat4f("model").mat4f("modelNormal");b.instanced&&-1<b.instanced.indexOf("color")&&(a=a.vec4f("instanceColor"));b.instanced&&-1<b.instanced.indexOf("featureAttribute")&&
(a=a.vec4f("instanceFeatureAttribute"));return a};return a}(C.Material);var N=function(d){function a(b){var a=this,h=b.material.getParameters(),a=d.call(this,n.makeCtorParameters(b,h))||this;a.params=f.copyParameters(h);b=a.params;a.slot=b.transparent?b.writeDepth?6:9:4;a.technique=a.techniqueRep.acquireAndReleaseExisting(l.DefaultMaterialTechnique,a.material.getTechniqueConfig(0),a.technique);a.selectPipeline(0);return a}p(a,d);a.prototype.selectPipeline=function(b){var a=this.params;b=0===b?a.transparent&&
H.separateBlendingParams(770,1,771,771):null;this.pipelineState=g.makePipelineState({blending:b,culling:r(a),depthTest:{func:513},depthWrite:a.writeDepth&&g.defaultDepthWriteParams,colorWrite:g.defaultColorWriteParams})};a.prototype.beginSlot=function(b){return b===this.slot};a.prototype.getProgram=function(){return this.technique.program};a.prototype.getPrograms=function(){return null};a.prototype.updateParameters=function(){this.params=f.copyParameters(this.material.getParameters());this.slot=this.params.transparent?
this.params.writeDepth?6:9:4;this.updateTexture(this.params.textureId);this.technique=this.techniqueRep.acquireAndReleaseExisting(l.DefaultMaterialTechnique,this.material.getTechniqueConfig(0),this.technique);this.selectPipeline(0)};a.prototype._updateShadowState=function(b){b.shadowMappingEnabled!==this.params.receiveShadows&&(this.material.setParameterValues({receiveShadows:b.shadowMappingEnabled}),this.updateParameters())};a.prototype.bind=function(b,a){var e=this.params;this._updateShadowState(a);
var c=this.technique.program;b.bindProgram(c);b.setPipelineState(this.pipelineState);this.technique.bindPass(b,e,a);f.bindVerticalOffset(e.verticalOffset,a,c);f.bindScreenSizePerspective(e.screenSizePerspective,c);this.bindTexture(b,c)};a.prototype.release=function(){};a.prototype.bindView=function(b){var a=this.technique.program,h=this.params,c=h.instancedDoublePrecision?m.vec3f64.fromValues(b.viewInvTransp[3],b.viewInvTransp[7],b.viewInvTransp[11]):b.origin;f.bindView(c,b.view,a);f.bindCamPos(c,
b.viewInvTransp,a);h.instancedDoublePrecision&&f.bindViewOriginDouble(c,a);h.slicePlaneEnabled&&f.bindSlicePlane(c,b.slicePlane,a);b.shadowMappingEnabled&&b.shadowMap.bindView(a,c)};a.prototype.bindInstance=function(b){var a=this.technique.program;a.setUniformMatrix4fv("model",b.transformation);a.setUniformMatrix4fv("modelNormal",b.transformationNormal)};a.prototype.getDrawMode=function(){return 4};return a}(n),y=function(d){function a(b){var a=this,a=d.call(this,n.makeCtorParameters(b,b.material.getParameters()))||
this;a.updateParameters();return a}p(a,d);a.prototype.beginSlot=function(a){return a===this.slot};a.prototype.getProgram=function(){return this.technique.program};a.prototype.getPrograms=function(){return null};a.prototype.selectPipeline=function(){var a=this.params;this.pipelineState=g.makePipelineState({culling:r(a),depthTest:{func:513},depthWrite:a.writeDepth&&g.defaultDepthWriteParams,colorWrite:g.defaultColorWriteParams})};a.prototype.selectSlot=function(){this.slot=this.params.transparent?this.params.writeDepth?
6:9:4};a.prototype.updateParameters=function(){this.params=f.copyParameters(this.material.getParameters());this.technique=this.techniqueRep.acquireAndReleaseExisting(l.DefaultMaterialTechnique,this.material.getTechniqueConfig(1),this.technique);this.selectPipeline();this.selectSlot();this.updateTexture(this.params.textureId)};a.prototype.bind=function(a,e){var b=this.technique.program,c=this.params;a.bindProgram(b);a.setPipelineState(this.pipelineState);this.technique.bindPass(a,c,e);f.bindVerticalOffset(c.verticalOffset,
e,b);f.bindScreenSizePerspective(c.screenSizePerspective,b);this.bindTexture(a,b)};a.prototype.release=function(){};a.prototype.bindView=function(a){var b=this.technique.program,h=this.params,c=h.instancedDoublePrecision?m.vec3f64.fromValues(a.viewInvTransp[3],a.viewInvTransp[7],a.viewInvTransp[11]):a.origin;f.bindView(c,a.view,b);h.slicePlaneEnabled&&f.bindSlicePlane(c,a.slicePlane,b);h.screenSizePerspective&&f.bindCamPos(c,a.viewInvTransp,b);h.instancedDoublePrecision&&f.bindViewOriginDouble(c,
b)};a.prototype.bindInstance=function(a){this.technique.program.setUniformMatrix4fv("model",a.transformation)};a.prototype.getDrawMode=function(){return 4};return a}(n),O=function(d){function a(a){return d.call(this,a)||this}p(a,d);a.prototype.updateParameters=function(){this.params=f.copyParameters(this.material.getParameters());this.technique=this.techniqueRep.acquireAndReleaseExisting(l.DefaultMaterialTechnique,this.material.getTechniqueConfig(3),this.technique);this.selectPipeline();this.selectSlot();
this.updateTexture(this.params.textureId)};return a}(y),P=function(d){function a(a){var b=this,h=a.material.getParameters(),b=d.call(this,n.makeCtorParameters(a,h))||this;b.params=f.copyParameters(h);b.technique=b.techniqueRep.acquireAndReleaseExisting(l.DefaultMaterialTechnique,b.material.getTechniqueConfig(2),b.technique);b.selectPipeline();b.selectSlot();return b}p(a,d);a.prototype.beginSlot=function(a){return a===this.slot};a.prototype.getProgram=function(){return this.technique.program};a.prototype.getPrograms=
function(){return null};a.prototype.selectPipeline=function(){var a=this.params;this.pipelineState=g.makePipelineState({culling:r(a),depthTest:{func:513},depthWrite:a.writeDepth&&g.defaultDepthWriteParams,colorWrite:g.defaultColorWriteParams})};a.prototype.selectSlot=function(){this.slot=this.params.transparent?this.params.writeDepth?6:9:4};a.prototype.updateParameters=function(){this.params=f.copyParameters(this.material.getParameters());this.technique=this.techniqueRep.acquireAndReleaseExisting(l.DefaultMaterialTechnique,
this.material.getTechniqueConfig(2),this.technique);this.selectPipeline();this.selectSlot();this.updateTexture(this.params.textureId)};a.prototype.bind=function(a,e){var b=this.technique.program,c=this.params;a.bindProgram(b);a.setPipelineState(this.pipelineState);this.technique.bindPass(a,c,e);f.bindVerticalOffset(c.verticalOffset,e,b);f.bindScreenSizePerspective(c.screenSizePerspective,b);this.bindTexture(a,b)};a.prototype.release=function(){};a.prototype.bindView=function(a){var b=this.technique.program,
d=this.params,c=d.instancedDoublePrecision?m.vec3f64.fromValues(a.viewInvTransp[3],a.viewInvTransp[7],a.viewInvTransp[11]):a.origin;f.bindView(c,a.view,b);b.setUniformMatrix4fv("viewNormal",a.viewInvTransp);d.slicePlaneEnabled&&f.bindSlicePlane(c,a.slicePlane,b);d.screenSizePerspective&&f.bindCamPos(c,a.viewInvTransp,b);d.instancedDoublePrecision&&f.bindViewOriginDouble(c,b)};a.prototype.bindInstance=function(a){var b=this.technique.program;b.setUniformMatrix4fv("model",a.transformation);b.setUniformMatrix4fv("modelNormal",
a.transformationNormal)};a.prototype.getDrawMode=function(){return 4};return a}(n),Q=function(d){function a(a){var b=this,b=d.call(this,n.makeCtorParameters(a,a.material.getParameters()))||this;b.updateParameters();return b}p(a,d);a.prototype.beginSlot=function(a){return a===this.slot};a.prototype.getProgram=function(){return this.technique.program};a.prototype.getPrograms=function(){return null};a.prototype.selectPipeline=function(){var a=this.params;this.pipelineState=g.makePipelineState({culling:r(a),
depthTest:{func:513},depthWrite:a.writeDepth&&g.defaultDepthWriteParams,colorWrite:g.defaultColorWriteParams})};a.prototype.selectSlot=function(){this.slot=this.params.transparent?this.params.writeDepth?6:9:4};a.prototype.updateParameters=function(){this.params=f.copyParameters(this.material.getParameters());this.technique=this.techniqueRep.acquireAndReleaseExisting(l.DefaultMaterialTechnique,this.material.getTechniqueConfig(4),this.technique);this.selectPipeline();this.selectSlot();this.updateTexture(this.params.textureId)};
a.prototype.bind=function(a,e){var b=this.technique.program,c=this.params;a.bindProgram(b);a.setPipelineState(this.pipelineState);this.technique.bindPass(a,c,e);f.bindVerticalOffset(c.verticalOffset,e,b);f.bindScreenSizePerspective(c.screenSizePerspective,b);this.bindTexture(a,b)};a.prototype.release=function(){};a.prototype.bindView=function(a){var b=this.technique.program,d=this.params,c=d.instancedDoublePrecision?m.vec3f64.fromValues(a.viewInvTransp[3],a.viewInvTransp[7],a.viewInvTransp[11]):a.origin;
f.bindView(c,a.view,b);d.slicePlaneEnabled&&f.bindSlicePlane(c,a.slicePlane,b);d.screenSizePerspective&&f.bindCamPos(c,a.viewInvTransp,b);d.instancedDoublePrecision&&f.bindViewOriginDouble(c,b)};a.prototype.bindInstance=function(a){var b=this.technique.program;b.setUniformMatrix4fv("model",a.transformation);b.setUniformMatrix4fv("modelNormal",a.transformationNormal)};a.prototype.getDrawMode=function(){return 4};return a}(n);(q||(q={})).COLOR_GAMMA=2.1;var I={textureId:void 0,initTextureTransparent:!1,
usePBR:!1,normalTextureId:void 0,vertexTangents:!1,occlusionTextureId:void 0,emissiveTextureId:void 0,metallicRoughnessTextureId:void 0,emissiveFactor:[0,0,0],metallicFactor:0,roughnessFactor:1,reflectanceFactor:.5,ambient:[.2,.2,.2],diffuse:[.8,.8,.8],specular:[0,0,0],externalColor:[1,1,1,1],colorMixMode:"multiply",opacity:1,layerOpacity:1,vertexColors:!1,symbolColors:!1,doubleSided:!1,doubleSidedType:"normal",cullFace:void 0,softwareInstanced:!1,instanced:void 0,instancedDoublePrecision:!1,normals:"default",
receiveSSAO:!0,receiveShadows:!1,castShadows:!0,verticalOffset:null,screenSizePerspective:null,slicePlaneEnabled:!1,sliceHighlightDisabled:!1,offsetTransparentBackfaces:!1,vvSizeEnabled:!1,vvSizeMinSize:[1,1,1],vvSizeMaxSize:[100,100,100],vvSizeOffset:[0,0,0],vvSizeFactor:[1,1,1],vvSizeValue:[1,1,1],vvColorEnabled:!1,vvColorValues:[0,0,0,0,0,0,0,0],vvColorColors:[1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0],vvSymbolAnchor:[0,0,0],vvSymbolRotationMatrix:A.mat3f64.create(),transparent:!1,
writeDepth:!0,textureAlphaMode:"blend",textureAlphaCutoff:B.TEXTURE_ALPHA_CUTOFF_DEFAULT,textureAlphaPremultiplied:!1},R=function(){function d(a,b){this.vertexBufferLayout=a;this.instanceBufferLayout=b}d.prototype.allocate=function(a){return this.vertexBufferLayout.createBuffer(a)};d.prototype.elementCount=function(a){return a.indices.position.length};d.prototype.write=function(a,b,d,f){E.writeDefaultAttributes(b,this.vertexBufferLayout,a.transformation,a.invTranspTransformation,d,f)};return d}(),
r=function(d){var a;a=d.cullFace?0!==d.cullFace:d.slicePlaneEnabled?!1:!d.transparent&&!d.doubleSided;return a&&{face:1===d.cullFace?1028:1029,mode:2305}},L=m.vec3f64.create(),M=m.vec3f64.create(),J=m.vec3f64.fromValues(0,0,1),x=m.vec3f64.create(),v=m.vec3f64.create(),u=m.vec3f64.create(),K=m.vec3f64.create();return q});