// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/libs/gl-matrix-2/vec2f32 ../../support/buffer/InterleavedLayout ../lib/GLMaterial ../lib/Material ../lib/Util ./internal/bufferWriterUtils ./internal/MaterialUtil ./renderers/MergedRenderer ../shaders/LineCalloutPrograms ../../../webgl/renderState".split(" "),function(l,A,m,g,r,t,u,d,k,e,v,n,h){function p(c,a,b){3===b.length?c.setUniform4f(a,b[0],b[1],b[2],1):c.setUniform4fv(a,b)}l=function(c){function a(b,f){f=c.call(this,
f)||this;f.params=e.copyParameters(b,w);f._uniqueMaterialIdentifier=a.uniqueMaterialIdentifier(f.params);return f}m(a,c);Object.defineProperty(a.prototype,"uniqueMaterialIdentifier",{get:function(){return this._uniqueMaterialIdentifier},enumerable:!0,configurable:!0});a.prototype.dispose=function(){};a.prototype.getGLMaterials=function(){return{color:x,depthShadowMap:void 0,normal:void 0,depth:void 0,highlight:void 0}};a.prototype.intersect=function(){};a.prototype.createBufferWriter=function(){return new y};
a.prototype.createRenderer=function(b,a){return new v(b,a,this)};a.prototype.setParameterValues=function(b){e.updateParameters(this.params,b)&&(this._uniqueMaterialIdentifier=a.uniqueMaterialIdentifier(this.params),this.notifyDirty("matChanged"))};a.prototype.getParameters=function(){return this.params};a.uniqueMaterialIdentifier=function(b){return JSON.stringify({screenOffset:b.screenOffset||[0,0],centerOffsetUnits:b.centerOffsetUnits||"world"})};return a}(u.Material);var x=function(c){function a(b){b=
c.call(this,b)||this;b.isRenderSlot=!0;b.updateParameters();return b}m(a,c);a.prototype.updateParameters=function(){this.params=e.copyParameters(this.material.getParameters());this.selectProgram()};a.prototype.selectProgram=function(){var b=this.params;this.renderProgram=this.programRep.getProgram(n.program,{occlTest:!!b.occlusionTest,verticalOffset:!!b.verticalOffset,screenSizePerspective:!!b.screenSizePerspective,depthHud:!1,depthHudAlignStart:!!b.depthHUDAlignStart,centerOffsetUnitsScreen:"screen"===
b.centerOffsetUnits,slice:b.slicePlaneEnabled});this.depthProgram=this.programRep.getProgram(n.program,{occlTest:!!b.occlusionTest,verticalOffset:!!b.verticalOffset,screenSizePerspective:!!b.screenSizePerspective,depthHud:!0,depthHudAlignStart:!!b.depthHUDAlignStart,centerOffsetUnitsScreen:"screen"===b.centerOffsetUnits,slice:b.slicePlaneEnabled});this.renderPipelineState=h.makePipelineState({blending:h.separateBlendingParams(1,770,771,771),depthTest:{func:513},colorWrite:h.defaultColorWriteParams});
this.depthPipelineState=h.makePipelineState({depthTest:{func:513},depthWrite:h.defaultDepthWriteParams})};a.prototype.beginSlot=function(b){switch(b){case 17:return this.isRenderSlot=!0;case 18:return this.isRenderSlot=!1,!0}return!1};Object.defineProperty(a.prototype,"program",{get:function(){return this.isRenderSlot?this.renderProgram:this.depthProgram},enumerable:!0,configurable:!0});a.prototype.getProgram=function(){return this.program};a.prototype.getPrograms=function(){return[this.renderProgram,
this.depthProgram]};a.prototype.getDrawMode=function(){return 4};a.prototype.bind=function(b,a){var f=a.cameraAboveGround?1:-1,c=this.program,d=this.params;b.bindProgram(c);c.setUniform1f("cameraGroundRelative",f);c.setUniform1f("polygonOffset",d.shaderPolygonOffset);c.setUniform4fv("viewport",a.viewport);c.setUniform1f("perDistancePixelRatio",Math.tan(a.fovY/2)/(a.viewport[2]/2));c.setUniformMatrix4fv("viewNormal",a.viewInvTransp);c.setUniform1i("hudVisibilityTexture",0);b.bindTexture(a.hudVisibilityTexture,
0);p(c,"color",d.color);f=a.pixelRatio||1;c.setUniform1f("pixelRatio",f);c.setUniform2f("screenOffset",d.screenOffset[0]*f,d.screenOffset[1]*f);this.bindBorder(b,a);e.bindVerticalOffset(d.verticalOffset,a,c);this.bindSizing(b,a);e.bindScreenSizePerspective(d.screenSizePerspective,c);this.isRenderSlot?b.setPipelineState(this.renderPipelineState):b.setPipelineState(this.depthPipelineState)};a.prototype.bindView=function(b){var a=this.program,c=this.params;e.bindView(b.origin,b.view,a);e.bindCamPos(b.origin,
b.viewInvTransp,a);c.slicePlaneEnabled&&e.bindSlicePlane(b.origin,b.slicePlane,a)};a.prototype.bindInstance=function(b){var a=this.program;a.setUniformMatrix4fv("model",b.transformation);a.setUniformMatrix4fv("modelNormal",b.transformationNormal)};a.prototype.release=function(){};a.prototype.bindSizing=function(b,a){b=this.program;var c=this.params;b.setUniform2f("pixelToNDC",2/a.viewport[2],2/a.viewport[3]);b.setUniform1f("lineSize",Math.ceil(c.size)*(a.pixelRatio||1))};a.prototype.bindBorder=function(b,
a){b=this.program;var c=this.params;a=a.pixelRatio||1;null!==c.borderColor?(p(b,"borderColor",c.borderColor),b.setUniform1f("borderSize",a)):(b.setUniform4f("borderColor",0,0,0,0),b.setUniform1f("borderSize",0))};return a}(t.GLMaterial),w={verticalOffset:null,screenSizePerspective:null,screenOffset:[0,0],color:[0,0,0,1],size:1,borderColor:null,occlusionTest:!1,shaderPolygonOffset:1E-5,depthHUDAlignStart:!1,centerOffsetUnits:"world",slicePlaneEnabled:!1},z=r.newLayout().vec3f(d.VertexAttrConstants.POSITION).vec3f(d.VertexAttrConstants.NORMAL).vec2f(d.VertexAttrConstants.UV0).vec4f(d.VertexAttrConstants.AUXPOS1),
q=[g.vec2f32.fromValues(0,0),g.vec2f32.fromValues(1,0),g.vec2f32.fromValues(0,1),g.vec2f32.fromValues(1,0),g.vec2f32.fromValues(1,1),g.vec2f32.fromValues(0,1)],y=function(){function c(){this.vertexBufferLayout=z}c.prototype.allocate=function(a){return this.vertexBufferLayout.createBuffer(a)};c.prototype.elementCount=function(a){return 6*a.indices[d.VertexAttrConstants.POSITION].length};c.prototype.write=function(a,b,c,e){k.writePosition(b.indices[d.VertexAttrConstants.POSITION],b.vertexAttr[d.VertexAttrConstants.POSITION].data,
a.transformation,c.position,e,6);k.writeNormal(b.indices[d.VertexAttrConstants.NORMAL],b.vertexAttr[d.VertexAttrConstants.NORMAL].data,a.invTranspTransformation,c.normal,e,6);k.writeBufferVec4(b.indices[d.VertexAttrConstants.AUXPOS1],b.vertexAttr[d.VertexAttrConstants.AUXPOS1].data,c.auxpos1,e,6);for(a=0;a<q.length;++a)c.uv0.setVec(e+a,q[a])};return c}();return l});