// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/libs/gl-matrix-2/vec3 ../../../../core/libs/gl-matrix-2/vec3f64 ../../support/buffer/InterleavedLayout ../lib/GLMaterial ../lib/Material ../lib/Util ./internal/MaterialUtil ./renderers/MergedRenderer ../shaders/MeasurementArrowPrograms ../../../webgl/renderState".split(" "),function(q,J,r,c,d,A,B,C,k,h,D,E,p){q=function(c){function a(a,b){b=c.call(this,b)||this;b.params=h.copyParameters(a,F);return b}r(a,c);a.prototype.dispose=
function(){};a.prototype.setParameterValues=function(a){h.updateParameters(this.params,a)&&this.notifyDirty("matChanged")};a.prototype.getParameters=function(){return this.params};a.prototype.intersect=function(){};a.prototype.createBufferWriter=function(){return new G};a.prototype.createRenderer=function(a,b){return new D(a,b,this)};a.prototype.getGLMaterials=function(){return{color:H,depthShadowMap:void 0,normal:void 0,depth:void 0,highlight:void 0}};return a}(C.Material);var H=function(c){function a(a){a=
c.call(this,a)||this;a.updateParameters();return a}r(a,c);a.prototype.selectProgram=function(){this.program=this.programRep.getProgram(E.colorPass);this.pipelineState=p.makePipelineState({polygonOffset:this.params.polygonOffset&&{factor:0,units:-4},depthTest:{func:513},depthWrite:p.defaultDepthWriteParams,colorWrite:p.defaultColorWriteParams})};a.prototype.updateParameters=function(){this.params=h.copyParameters(this.material.getParameters());this.selectProgram()};a.prototype.beginSlot=function(a){return 4===
a};a.prototype.getProgram=function(){return this.program};a.prototype.getDrawMode=function(){return 5};a.prototype.bind=function(a){var b=this.program;a.bindProgram(b);a.setPipelineState(this.pipelineState);b.setUniform1f("width",this.params.width);b.setUniform1f("outlineSize",this.params.outlineSize);b.setUniform4fv("outlineColor",this.params.outlineColor);b.setUniform1f("stripeLength",this.params.stripeLength);b.setUniform4fv("stripeEvenColor",this.params.stripeEvenColor);b.setUniform4fv("stripeOddColor",
this.params.stripeOddColor)};a.prototype.bindView=function(a){h.bindView(a.origin,a.view,this.program)};a.prototype.bindInstance=function(a){this.program.setUniformMatrix4fv("model",a.transformation)};a.prototype.release=function(){};return a}(B.GLMaterial),F={width:32,outlineSize:.2,outlineColor:[1,.5,0,1],stripeLength:1,stripeEvenColor:[1,1,1,1],stripeOddColor:[1,.5,0,1],polygonOffset:!1},I=A.newLayout().vec3f(k.VertexAttrConstants.POSITION).vec3f(k.VertexAttrConstants.NORMAL).vec2f(k.VertexAttrConstants.UV0).f32(k.VertexAttrConstants.AUXPOS1),
l=d.vec3f64.create(),t=d.vec3f64.create(),w=d.vec3f64.create(),m=d.vec3f64.create(),x=d.vec3f64.create(),G=function(){function d(){this.vertexBufferLayout=I}d.prototype.allocate=function(a){return this.vertexBufferLayout.createBuffer(a)};d.prototype.elementCount=function(a){return 2*(a.indices[k.VertexAttrConstants.POSITION].length/2+1)};d.prototype.write=function(a,f,b,d){var n=f.vertexAttr[k.VertexAttrConstants.POSITION].data,h=f.vertexAttr[k.VertexAttrConstants.NORMAL].data,u=n.length/3;(f=f&&
f.indices&&f.indices.position)&&f.length!==2*(u-1)&&console.warn("MeasurementArrowMaterial does not support indices");f=a.transformation;for(var p=a.invTranspTransformation,q=b.position,r=b.normal,y=b.uv0,g=a=0;g<u;++g){var e=3*g;c.vec3.set(l,n[e],n[e+1],n[e+2]);g<u-1&&(e=3*(g+1),c.vec3.set(t,n[e],n[e+1],n[e+2]),c.vec3.set(x,h[e],h[e+1],h[e+2]),c.vec3.normalize(x,x),c.vec3.subtract(w,t,l),c.vec3.normalize(w,w),c.vec3.cross(m,x,w),c.vec3.normalize(m,m));e=c.vec3.distance(l,t);f&&p&&(c.vec3.transformMat4(l,
l,f),c.vec3.transformMat4(t,t,f),c.vec3.transformMat4(m,m,p));var v=d+2*g,z=v+1;q.setVec(v,l);q.setVec(z,l);r.setVec(v,m);r.setVec(z,m);y.set(v,0,a);y.set(v,1,-1);y.set(z,0,a);y.set(z,1,1);g<u-1&&(a+=e)}b=b.auxpos1;for(g=0;g<2*u;++g)b.set(d+g,a)};return d}();return q});