// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/tsSupport/assignHelper ../../../../core/Logger ../../../../core/maybe ../../../../core/screenUtils ../../../../core/libs/gl-matrix-2/vec2 ../../../../core/libs/gl-matrix-2/vec3 ../../../../core/libs/gl-matrix-2/vec3f64 ../../support/geometryUtils ../../support/buffer/BufferView ../lib/ComponentUtils ../lib/geometryDataUtils ../lib/GLMaterial ../lib/Material ../lib/Util ./internal/bufferWriterUtils ./internal/DefaultBufferWriter ./internal/MaterialUtil ./renderers/MergedRenderer ../shaders/NativeLineTechnique".split(" "),
function(I,ea,z,J,P,B,x,Q,f,n,b,R,S,T,A,U,t,V,C,K,W,L){var X=P.getLogger("esri.views.3d.webgl-engine.materials.NativeLineMaterial");I=function(p){function a(c,a){a=p.call(this,a)||this;a.techniqueConfig=new L.NativeLineTechniqueConfiguration;a.params=K.copyParameters(c,Y);return a}z(a,p);a.prototype.setParameterValues=function(c){var a=this.params,d;for(d in c)a[d]=c[d];this.notifyDirty("matChanged")};a.prototype.getParameters=function(){return this.params};a.prototype.getTechniqueConfig=function(c){this.techniqueConfig.output=
c;this.techniqueConfig.slicePlaneEnabled=this.params.slicePlaneEnabled;this.techniqueConfig.vertexColors=this.params.vertexColors;this.techniqueConfig.transparent=1>this.params.color[3]||1>this.params.width;c=B.isSome(this.params.stipplePattern);this.techniqueConfig.stippleEnabled=c;this.techniqueConfig.stippleOffColorEnabled=c&&B.isSome(this.params.stippleOffColor);this.techniqueConfig.stippleIntegerRepeatsEnabled=c&&this.params.stippleIntegerRepeats;return this.techniqueConfig};a.prototype.getPassParameters=
function(){return this.params};a.prototype.intersect=function(c,a,d,b,f,p,k,h,g){g?this.intersectLineGeometry(c,a,d,b,k):K.intersectDrapedRenderLineGeometry(c,b,p,1,k)};a.prototype.intersectLineGeometry=function(c,a,d,p,n){if(p.options.selectionMode&&!S.isAllHidden(a.componentVisibilities,c.componentOffsets))if(t.isTranslationMatrix(d)){a=c.data.getVertexAttr().position.data;var e=p.camera,k=Z;Q.vec2.copy(k,p.point);f.vec3.set(y[0],k[0]-2,k[1]+2,0);f.vec3.set(y[1],k[0]+2,k[1]+2,0);f.vec3.set(y[2],
k[0]+2,k[1]-2,0);f.vec3.set(y[3],k[0]-2,k[1]-2,0);for(var h=0;4>h;h++)e.unprojectPoint(y[h],r[h]);b.plane.fromPoints(e.eye,r[0],r[1],D);b.plane.fromPoints(e.eye,r[1],r[2],E);b.plane.fromPoints(e.eye,r[2],r[3],F);b.plane.fromPoints(e.eye,r[3],r[0],G);c=Number.MAX_VALUE;for(h=0;h<a.length-5;h+=3)if(l[0]=a[h]+d[12],l[1]=a[h+1]+d[13],l[2]=a[h+2]+d[14],m[0]=a[h+3]+d[12],m[1]=a[h+4]+d[13],m[2]=a[h+5]+d[14],!(0>b.plane.signedDistance(D,l)&&0>b.plane.signedDistance(D,m)||0>b.plane.signedDistance(E,l)&&0>
b.plane.signedDistance(E,m)||0>b.plane.signedDistance(F,l)&&0>b.plane.signedDistance(F,m)||0>b.plane.signedDistance(G,l)&&0>b.plane.signedDistance(G,m))){e.projectPoint(l,u);e.projectPoint(m,v);if(0>u[2]&&0<v[2]){f.vec3.subtract(q,l,m);var g=e.frustum,H=-b.plane.signedDistance(g.planes[4],l),g=H/f.vec3.dot(q,g.planes[4]);f.vec3.scale(q,q,g);f.vec3.add(l,l,q);e.projectPoint(l,u)}else if(0<u[2]&&0>v[2])f.vec3.subtract(q,m,l),g=e.frustum,H=-b.plane.signedDistance(g.planes[4],m),g=H/f.vec3.dot(q,g.planes[4]),
f.vec3.scale(q,q,g),f.vec3.add(m,m,q),e.projectPoint(m,v);else if(0>u[2]&&0>v[2])continue;u[2]=0;v[2]=0;g=b.lineSegment.distance2(b.lineSegment.fromPoints(u,v,M),k);g<c&&(c=g,f.vec3.copy(N,l),f.vec3.copy(O,m))}d=p.rayBeginPoint;p=p.rayEndPoint;4>c&&(c=Number.MAX_VALUE,b.lineSegment.closestLineSegmentPoint(b.lineSegment.fromPoints(N,O,M),b.lineSegment.fromPoints(d,p,aa),w)&&(f.vec3.subtract(w,w,d),c=f.vec3.length(w),f.vec3.scale(w,w,1/c),c/=f.vec3.distance(d,p)),n(c,w))}else X.error("intersection assumes a translation-only matrix")};
a.prototype.computeAttachmentOrigin=function(a,e){a=a.data;return(a="getVertexAttr"in a?a.getVertexAttr():"vertexAttr"in a?a.vertexAttr:null)?T.computeAttachmentOriginLines(a[t.VertexAttrConstants.POSITION],null,e):null};a.prototype.createBufferWriter=function(){var a=this.params.vertexColors?C.PositionColorLayout:C.PositionLayout;return B.isNone(this.params.stipplePattern)?new C.DefaultBufferWriter(a):new ba(a.clone().vec3f(t.VertexAttrConstants.AUXPOS1))};a.prototype.createRenderer=function(a,e){return new W(a,
e,this)};a.prototype.getGLMaterials=function(){return{color:ca,depthShadowMap:void 0,normal:void 0,depth:void 0,highlight:da}};return a}(U.Material);A=function(b){function a(a){var c=b.call(this,a)||this;c.output=a.output;c.updateParameters();return c}z(a,b);a.prototype.updateParameters=function(){this.technique=this.techniqueRep.acquireAndReleaseExisting(L.NativeLineTechnique,this.material.getTechniqueConfig(this.output),this.technique)};a.prototype.beginSlot=function(a){return 4===a};a.prototype.getProgram=
function(){return this.technique.program};a.prototype.getPrograms=function(){return null};a.prototype.bind=function(a,b){a.bindProgram(this.technique.program);this.technique.bindPipelineState(a);this.technique.bindPass(a,this.material.getPassParameters(),b)};a.prototype.release=function(){};a.prototype.bindView=function(a){this.technique.bindDraw(a)};a.prototype.bindInstance=function(a){this.technique.program.setUniformMatrix4fv("model",a.transformation)};a.prototype.getDrawMode=function(){return 1};
return a}(A.GLMaterial);var ca=function(b){function a(a){return b.call(this,J({},a,{output:0}))||this}z(a,b);return a}(A),da=function(b){function a(a){return b.call(this,J({},a,{output:4}))||this}z(a,b);return a}(A),ba=function(){function b(a){this.vertexBufferLayout=a}b.prototype.allocate=function(a){return this.vertexBufferLayout.createBuffer(a)};b.prototype.elementCount=function(a){return a.indices[t.VertexAttrConstants.POSITION].length};b.prototype.write=function(a,b,e,d){V.writeDefaultAttributes(b,
this.vertexBufferLayout,a.transformation,a.invTranspTransformation,e,d);this.writeAuxpos1(a,b,e,d)};b.prototype.writeAuxpos1=function(a,b,e,d){var c=e.getField(t.VertexAttrConstants.AUXPOS1,R.BufferViewVec3f);e=b.indices[t.VertexAttrConstants.POSITION];b=b.vertexAttr[t.VertexAttrConstants.POSITION].data;a=a.transformation;var f=c.typedBufferStride,c=c.typedBuffer;d*=f;for(var l=0;l<e.length;l+=2)for(var k=3*e[l],h=b[k],g=b[k+1],m=b[k+2],k=a[0]*h+a[4]*g+a[8]*m+a[12],n=a[1]*h+a[5]*g+a[9]*m+a[13],h=
a[2]*h+a[6]*g+a[10]*m+a[14],g=0;2>g;++g)c[d]=k,c[d+1]=n,c[d+2]=h,d+=f};return b}(),Y={color:[1,1,1,1],vertexColors:!1,slicePlaneEnabled:!1,width:1,stipplePattern:null,stippleIntegerRepeats:!1,stippleOffColor:null},l=n.vec3f64.create(),m=n.vec3f64.create(),q=n.vec3f64.create(),w=n.vec3f64.create(),u=x.createRenderScreenPointArray3(),v=x.createRenderScreenPointArray3(),N=n.vec3f64.create(),O=n.vec3f64.create(),M=b.lineSegment.create(),aa=b.lineSegment.create(),Z=n.vec3f64.create(),y=[x.createRenderScreenPointArray3(),
x.createRenderScreenPointArray3(),x.createRenderScreenPointArray3(),x.createRenderScreenPointArray3()],r=[n.vec3f64.create(),n.vec3f64.create(),n.vec3f64.create(),n.vec3f64.create()],D=b.plane.create(),E=b.plane.create(),F=b.plane.create(),G=b.plane.create();return I});