// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/tsSupport/decorateHelper ../../../../core/tsSupport/assignHelper ../core/shaderLibrary/Slice.glsl ../core/shaderLibrary/Transform.glsl ../core/shaderLibrary/attributes/PathVertexPosition.glsl ../core/shaderLibrary/attributes/VertexNormal.glsl ../core/shaderLibrary/output/ReadLinearDepth.glsl ../core/shaderLibrary/shading/ReadShadowMap.glsl ../core/shaderLibrary/util/Camera.glsl ../core/shaderTechnique/ReloadableShaderModule ../core/shaderTechnique/ShaderTechnique ../core/shaderTechnique/ShaderTechniqueConfiguration ../shaders/Path.glsl ../../../webgl/Program ../../../webgl/renderState".split(" "),
function(k,f,h,d,g,l,m,n,p,q,r,t,u,v,c,w,x,e){Object.defineProperty(f,"__esModule",{value:!0});f.PathVertexAttrConstants={POSITION:"position",PROFILERIGHT:"profileRight",PROFILEUP:"profileUp",PROFILEVERTEXANDNORMAL:"profileVertexAndNormal",FEATUREVALUE:"featureValue"};f.pathVertexAttributeLocations={position:0,profileRight:1,profileUp:2,profileVertexAndNormal:3,featureValue:4};g=function(c){function b(){return null!==c&&c.apply(this,arguments)||this}h(b,c);b.prototype.initializeProgram=function(a){var c=
b.shader.get(),d=this.configuration,c=c.build({output:d.output,viewingMode:a.viewingMode,slicePlaneEnabled:d.slicePlaneEnabled,sliceHighlightDisabled:!1,receiveShadows:d.receiveShadows,vvSize:d.vvSize,vvColor:d.vvColor,vvOpacity:d.vvOpacity,useOldSceneLightInterface:!1,usePBR:!1,usePBRforWater:!1,useCustomDTRExponentForWater:!1,receiveAmbientOcclusion:d.receiveSSAO,doubleSidedMode:d.doubleSidedMode});return new x(a.rctx,c.generateSource("vertex"),c.generateSource("fragment"),f.pathVertexAttributeLocations)};
b.prototype.bindPass=function(a,b,c){this.program.setUniform3fv("size",b.size);0===this.configuration.output?(this.program.setUniform3fv("size",b.size),this.program.setUniform3fv("ambient",b.ambient),this.program.setUniform3fv("diffuse",b.diffuse),this.program.setUniform3fv("specular",b.specular),this.program.setUniform1f("opacity",b.opacity)):1!==this.configuration.output&&3!==this.configuration.output||q.ReadLinearDepth.bindUniforms(this.program,c);n.setVVUniforms(this.program,b)};b.prototype.bindDraw=
function(a){m.Transform.bindUniforms(this.program,a);l.Slice.bindUniformsWithOrigin(this.program,this.configuration,a);0===this.configuration.output&&(t.Camera.bindUniforms(this.program,a),r.ReadShadowMap.bindUniforms(this.program,a));2===this.configuration.output&&p.VertexNormal.bindUniforms(this.program,a)};b.prototype.bindInstance=function(a){this.program.setUniformMatrix4fv("model",a.transformation);0!==this.configuration.output&&4!==this.configuration.output&&2!==this.configuration.output||this.program.setUniformMatrix4fv("modelNormal",
a.transformationNormal)};b.prototype.initializePipeline=function(){var a=this.configuration;return 0===a.output?e.makePipelineState({blending:a.transparent&&e.separateBlendingParams(770,1,771,771),culling:(a.slicePlaneEnabled?!1:!a.transparent&&0!==a.doubleSidedMode)&&{face:1028,mode:2305},depthTest:{func:513},depthWrite:e.defaultDepthWriteParams,colorWrite:e.defaultColorWriteParams}):e.makePipelineState({culling:(a.slicePlaneEnabled?!1:!a.transparent&&0!==a.doubleSidedMode)&&{face:1028,mode:2305},
depthTest:{func:513},depthWrite:e.defaultDepthWriteParams,colorWrite:e.defaultColorWriteParams})};b.prototype.bindPipelineState=function(a){a.setPipelineState(this.pipeline)};b.shader=new u.ReloadableShaderModule(w,"../shaders/Path.glsl",k);return b}(v.ShaderTechnique);f.PathTechnique=g;g=function(e){function b(){var a=null!==e&&e.apply(this,arguments)||this;a.output=0;a.doubleSidedMode=0;a.receiveShadows=!1;a.receiveSSAO=!1;a.vvSize=!1;a.vvColor=!1;a.vvOpacity=!1;a.slicePlaneEnabled=!1;a.shadowMap=
!1;a.transparent=!1;return a}h(b,e);d([c.parameter({count:6})],b.prototype,"output",void 0);d([c.parameter({count:3})],b.prototype,"doubleSidedMode",void 0);d([c.parameter()],b.prototype,"receiveShadows",void 0);d([c.parameter()],b.prototype,"receiveSSAO",void 0);d([c.parameter()],b.prototype,"vvSize",void 0);d([c.parameter()],b.prototype,"vvColor",void 0);d([c.parameter()],b.prototype,"vvOpacity",void 0);d([c.parameter()],b.prototype,"slicePlaneEnabled",void 0);d([c.parameter()],b.prototype,"shadowMap",
void 0);d([c.parameter()],b.prototype,"transparent",void 0);return b}(c.ShaderTechniqueConfiguration);f.PathTechniqueConfiguration=g});