// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/tsSupport/assignHelper ../../../../core/Logger ../../../../core/mathUtils ../../../../core/maybe ../../../../core/screenUtils ../../../../core/libs/gl-matrix-2/vec2 ../../../../core/libs/gl-matrix-2/vec3 ../../../../core/libs/gl-matrix-2/vec3f64 ../../support/geometryUtils ../../support/buffer/InterleavedLayout ../lib/ComponentUtils ../lib/geometryDataUtils ../lib/GLMaterial ../lib/Material ../lib/Util ./VisualVariableMaterialParameters ./internal/MaterialUtil ./renderers/MergedRenderer ../shaders/RibbonLineTechnique ../shaders/RibbonLineTechnique".split(" "),
function(Q,sa,G,K,W,X,R,E,Y,d,p,f,Z,aa,ba,H,ca,da,ea,S,fa,ga,h){function L(d,b,a,c,h){for(var I=0;I<h;I++)a[c++]=d[b++];return c}var J=W.getLogger("esri.views.3d.webgl-engine.materials.RibbonLineMaterial");Q=function(w){function b(a,c){c=w.call(this,c)||this;c.techniqueConfig=new h.RibbonLineTechniqueConfiguration;c.params=S.copyParameters(a,ha);c.validateParams();c.params.transparent=1>c.params.color[3]||c.params.transparent;c.layout=c.createLayout();return c}G(b,w);b.prototype.dispose=function(){};
b.prototype.setParameterValues=function(a){for(var c in a)"cap"===c?J.error("cap cannot be changed after creation"):"join"===c&&"round"===this.params[c]!==("round"===a[c])?J.error("join cannot be changed after creation"):"stipplePattern"===c&&!!this.params[c]!==!!a[c]?J.error("stippledness cannot be changed after creation"):this.params[c]=a[c];this.validateParams();this.notifyDirty("matChanged")};b.prototype.getParameters=function(){return this.params};b.prototype.getPassParameters=function(){return this.params};
b.prototype.getTechniqueConfig=function(a){this.techniqueConfig.output=a;a=R.isSome(this.params.stipplePattern);this.techniqueConfig.stippleEnabled=a;this.techniqueConfig.stippleIntegerRepeatsEnabled=a&&this.params.stippleIntegerRepeats;this.techniqueConfig.stippleOffColorEnabled=a&&R.isSome(this.params.stippleOffColor);this.techniqueConfig.slicePlaneEnabled=this.params.slicePlaneEnabled;this.techniqueConfig.roundJoins="round"===this.params.join;this.techniqueConfig.roundCaps="round"===this.params.cap;
this.techniqueConfig.transparent=this.params.transparent;this.techniqueConfig.polygonOffset=this.params.polygonOffset;this.techniqueConfig.writeDepth=this.params.writeDepth;this.techniqueConfig.vvColor=this.params.vvColorEnabled;this.techniqueConfig.vvOpacity=this.params.vvOpacityEnabled;this.techniqueConfig.vvSize=this.params.vvSizeEnabled;this.techniqueConfig.writeDepth=this.params.writeDepth;this.techniqueConfig.writeDepth=this.params.writeDepth;return this.techniqueConfig};b.prototype.intersect=
function(a,c,b,d,g,h,e,l,f){f?S.intersectDrapedRenderLineGeometry(a,d,h,this.params.width,e):this.intersectLineGeometry(a,c,b,d,this.params.width,e)};b.prototype.intersectLineGeometry=function(a,c,b,w,g,n){if(w.options.selectionMode&&!aa.isAllHidden(c.componentVisibilities,a.componentOffsets))if(da.isTranslationMatrix(b)){c=a.data.getVertexAttr();a=c[h.RibbonVertexAttributeConstants.POSITION].data;this.params.vvSizeEnabled?g*=X.clamp(this.params.vvSizeOffset[0]+c[h.RibbonVertexAttributeConstants.SIZEFEATUREATTRIBUTE].data[0]*
this.params.vvSizeFactor[0],this.params.vvSizeMinSize[0],this.params.vvSizeMaxSize[0]):c[h.RibbonVertexAttributeConstants.SIZE]&&(g*=c[h.RibbonVertexAttributeConstants.SIZE].data[0]);var e=w.camera,l=ia;Y.vec2.copy(l,w.point);g=g*e.pixelRatio/2+4*e.pixelRatio;d.vec3.set(F[0],l[0]-g,l[1]+g,0);d.vec3.set(F[1],l[0]+g,l[1]+g,0);d.vec3.set(F[2],l[0]+g,l[1]-g,0);d.vec3.set(F[3],l[0]-g,l[1]-g,0);for(var t=0;4>t;t++)e.unprojectPoint(F[t],x[t]);f.plane.fromPoints(e.eye,x[0],x[1],M);f.plane.fromPoints(e.eye,
x[1],x[2],N);f.plane.fromPoints(e.eye,x[2],x[3],O);f.plane.fromPoints(e.eye,x[3],x[0],P);c=Number.MAX_VALUE;for(var I=this.params.isClosed?a.length-2:a.length-5,t=0;t<I;t+=3){u[0]=a[t]+b[12];u[1]=a[t+1]+b[13];u[2]=a[t+2]+b[14];var r=(t+3)%a.length;q[0]=a[r]+b[12];q[1]=a[r+1]+b[13];q[2]=a[r+2]+b[14];if(!(0>f.plane.signedDistance(M,u)&&0>f.plane.signedDistance(M,q)||0>f.plane.signedDistance(N,u)&&0>f.plane.signedDistance(N,q)||0>f.plane.signedDistance(O,u)&&0>f.plane.signedDistance(O,q)||0>f.plane.signedDistance(P,
u)&&0>f.plane.signedDistance(P,q))){e.projectPoint(u,D);e.projectPoint(q,C);if(0>D[2]&&0<C[2]){d.vec3.subtract(z,u,q);var r=e.frustum,p=-f.plane.signedDistance(r.planes[4],u),r=p/d.vec3.dot(z,r.planes[4]);d.vec3.scale(z,z,r);d.vec3.add(u,u,z);e.projectPoint(u,D)}else if(0<D[2]&&0>C[2])d.vec3.subtract(z,q,u),r=e.frustum,p=-f.plane.signedDistance(r.planes[4],q),r=p/d.vec3.dot(z,r.planes[4]),d.vec3.scale(z,z,r),d.vec3.add(q,q,z),e.projectPoint(q,C);else if(0>D[2]&&0>C[2])continue;D[2]=0;C[2]=0;r=f.lineSegment.distance2(f.lineSegment.fromPoints(D,
C,T),l);r<c&&(c=r,d.vec3.copy(U,u),d.vec3.copy(V,q))}}b=w.rayBeginPoint;w=w.rayEndPoint;c<g*g&&(a=Number.MAX_VALUE,f.lineSegment.closestLineSegmentPoint(f.lineSegment.fromPoints(U,V,T),f.lineSegment.fromPoints(b,w,ja),B)&&(d.vec3.subtract(B,B,b),a=d.vec3.length(B),d.vec3.scale(B,B,1/a),a/=d.vec3.distance(b,w)),n(a,B))}else J.error("intersection assumes a translation-only matrix")};b.prototype.computeAttachmentOrigin=function(a,b){a=a.data;return(a="getVertexAttr"in a?a.getVertexAttr():"vertexAttr"in
a?a.vertexAttr:null)?ba.computeAttachmentOriginLines(a[h.RibbonVertexAttributeConstants.POSITION],null,b):null};b.prototype.createLayout=function(){var a=Z.newLayout().vec3f(h.RibbonVertexAttributeConstants.POSITION).f32(h.RibbonVertexAttributeConstants.SUBDIVISIONFACTOR).vec2f(h.RibbonVertexAttributeConstants.UV0).vec3f(h.RibbonVertexAttributeConstants.AUXPOS1).vec3f(h.RibbonVertexAttributeConstants.AUXPOS2);this.params.vvSizeEnabled?a.f32(h.RibbonVertexAttributeConstants.SIZEFEATUREATTRIBUTE):a.f32(h.RibbonVertexAttributeConstants.SIZE);
this.params.vvColorEnabled?a.f32(h.RibbonVertexAttributeConstants.COLORFEATUREATTRIBUTE):a.vec4f(h.RibbonVertexAttributeConstants.COLOR);this.params.vvOpacityEnabled&&a.f32(h.RibbonVertexAttributeConstants.OPACITYFEATUREATTRIBUTE);return a};b.prototype.createBufferWriter=function(){return new ka(this.layout,this.params)};b.prototype.createRenderer=function(a,b){return new fa(a,b,this,h.ribbonVertexAttributeLocations)};b.prototype.getGLMaterials=function(){return{color:la,depthShadowMap:void 0,normal:void 0,
depth:void 0,highlight:ma}};b.prototype.validateParams=function(){this.params.width&&1<this.params.width&&(this.params.width=Math.round(this.params.width));"miter"!==this.params.join&&(this.params.miterLimit=0)};return b}(ca.Material);H=function(d){function b(a){var b=d.call(this,a)||this;b.output=a.output;b.updateParameters();return b}G(b,d);b.prototype.updateParameters=function(){this.technique=this.techniqueRep.acquireAndReleaseExisting(ga.RibbonLineTechnique,this.material.getTechniqueConfig(this.output),
this.technique)};b.prototype.beginSlot=function(a){return 0===this.output?a===(this.technique.configuration.writeDepth?6:9):4===a};b.prototype.getProgram=function(){return this.technique.program};b.prototype.getPrograms=function(){return null};b.prototype.bind=function(a,b){a.bindProgram(this.technique.program);this.technique.bindPipelineState(a);this.technique.bindPass(a,this.material.getPassParameters(),b)};b.prototype.release=function(){};b.prototype.bindView=function(a){this.technique.bindDraw(a)};
b.prototype.bindInstance=function(a){this.technique.bindInstance(a)};b.prototype.getDrawMode=function(){return 5};return b}(H.GLMaterial);var la=function(d){function b(a){return d.call(this,K({},a,{output:0}))||this}G(b,d);return b}(H),ma=function(d){function b(a){return d.call(this,K({},a,{output:4}))||this}G(b,d);return b}(H),ha=K({width:0,color:[1,1,1,1],join:"miter",cap:"butt",miterLimit:5,writeDepth:!0,polygonOffset:!1,stipplePattern:null,stippleIntegerRepeats:!1,stippleOffColor:null,slicePlaneEnabled:!1,
vvFastUpdate:!1,transparent:!1,isClosed:!1},ea.Default),ka=function(){function f(b,a){this.params=a;this.numJoinSubdivisions=this.numCapSubdivisions=0;this.vertexBufferLayout=b;if(!a.isClosed)switch(this.params.cap){case "butt":this.numCapSubdivisions=0;break;case "square":this.numCapSubdivisions=1;break;case "round":this.numCapSubdivisions=na}switch(this.params.join){case "miter":case "bevel":this.numJoinSubdivisions=a.stipplePattern?1:0;break;case "round":this.numJoinSubdivisions=oa}}f.prototype.allocate=
function(b){return this.vertexBufferLayout.createBuffer(b)};f.prototype.elementCount=function(b){var a=2*this.numCapSubdivisions+2,c=b.indices[h.RibbonVertexAttributeConstants.POSITION].length/2+1,d=this.params.isClosed,a=d?2:2*a,c=d?c:c-1;if(b.vertexAttr[h.RibbonVertexAttributeConstants.SUBDIVISIONS])for(b=b.vertexAttr[h.RibbonVertexAttributeConstants.SUBDIVISIONS].data,d=d?0:1;d<c;++d)a+=4+2*b[d];else a+=c*(2*this.numJoinSubdivisions+4);return a+2};f.prototype.write=function(b,a,c,f){var p=this,
g=pa,n=qa,e=ra,l=a.vertexAttr[h.RibbonVertexAttributeConstants.POSITION].data,t=a.indices&&a.indices[h.RibbonVertexAttributeConstants.POSITION];t&&t.length!==2*(l.length/3-1)&&console.warn("RibbonLineMaterial does not support indices");t=null;a.vertexAttr[h.RibbonVertexAttributeConstants.SUBDIVISIONS]&&(t=a.vertexAttr[h.RibbonVertexAttributeConstants.SUBDIVISIONS].data);var u=1,r=0;this.params.vvSizeEnabled?r=a.vertexAttr[h.RibbonVertexAttributeConstants.SIZEFEATUREATTRIBUTE].data[0]:a.vertexAttr[h.RibbonVertexAttributeConstants.SIZE]&&
(u=a.vertexAttr[h.RibbonVertexAttributeConstants.SIZE].data[0]);var q=[1,1,1,1],w=0;this.params.vvColorEnabled?w=a.vertexAttr[h.RibbonVertexAttributeConstants.COLORFEATUREATTRIBUTE].data[0]:a.vertexAttr[h.RibbonVertexAttributeConstants.COLOR]&&(q=a.vertexAttr[h.RibbonVertexAttributeConstants.COLOR].data);var z=0;this.params.vvOpacityEnabled&&(z=a.vertexAttr[h.RibbonVertexAttributeConstants.OPACITYFEATUREATTRIBUTE].data[0]);a=l.length/3;b=b.transformation;var m=new Float32Array(c.buffer);c=this.vertexBufferLayout.stride/
4;var k=f*c;f=k;var y=function(a,b,c,d,e,f){m[k++]=b[0];m[k++]=b[1];m[k++]=b[2];m[k++]=d;m[k++]=e;m[k++]=f;m[k++]=a[0];m[k++]=a[1];m[k++]=a[2];m[k++]=c[0];m[k++]=c[1];m[k++]=c[2];p.params.vvSizeEnabled?m[k++]=r:m[k++]=u;p.params.vvColorEnabled?m[k++]=w:(m[k++]=q[0],m[k++]=q[1],m[k++]=q[2],m[k++]=q[3]);p.params.vvOpacityEnabled&&(m[k++]=z)},k=k+c;d.vec3.set(n,l[0],l[1],l[2]);b&&d.vec3.transformMat4(n,n,b);var x=this.params.isClosed;if(x){var v=l.length-3;d.vec3.set(g,l[v],l[v+1],l[v+2]);b&&d.vec3.transformMat4(g,
g,b)}else{d.vec3.copy(g,n);d.vec3.set(e,l[3],l[4],l[5]);b&&d.vec3.transformMat4(e,e,b);for(v=0;v<this.numCapSubdivisions;++v){var A=1-v/this.numCapSubdivisions;y(g,n,e,A,1,-4);y(g,n,e,A,1,4)}y(g,n,e,0,0,-4);y(g,n,e,0,0,4);d.vec3.copy(g,n);d.vec3.copy(n,e)}for(var D=x?a:a-1,v=x?0:1;v<D;v++){A=(v+1)%a*3;d.vec3.set(e,l[A+0],l[A+1],l[A+2]);b&&d.vec3.transformMat4(e,e,b);y(g,n,e,0,1,-1);y(g,n,e,0,1,1);for(var C=t?t[v]:this.numJoinSubdivisions,B=0;B<C;++B)A=(B+1)/(C+1),y(g,n,e,A,1,-2),y(g,n,e,A,1,2);y(g,
n,e,1,0,-2);y(g,n,e,1,0,2);d.vec3.copy(g,n);d.vec3.copy(n,e)}if(x)k=L(m,f+c,m,k,2*c);else for(y(g,n,e,0,1,-5),y(g,n,e,0,1,5),v=0;v<this.numCapSubdivisions;++v)A=(v+1)/this.numCapSubdivisions,y(g,n,e,A,1,-5),y(g,n,e,A,1,5);L(m,f+c,m,f,c);k=L(m,k-c,m,k,c)};return f}(),na=3,oa=1,u=p.vec3f64.create(),q=p.vec3f64.create(),z=p.vec3f64.create(),B=p.vec3f64.create(),ia=p.vec3f64.create(),D=E.createRenderScreenPointArray3(),C=E.createRenderScreenPointArray3(),U=p.vec3f64.create(),V=p.vec3f64.create(),T=f.lineSegment.create(),
ja=f.lineSegment.create(),pa=p.vec3f64.create(),qa=p.vec3f64.create(),ra=p.vec3f64.create(),F=[E.createRenderScreenPointArray3(),E.createRenderScreenPointArray3(),E.createRenderScreenPointArray3(),E.createRenderScreenPointArray3()],x=[p.vec3f64.create(),p.vec3f64.create(),p.vec3f64.create(),p.vec3f64.create()],M=f.plane.create(),N=f.plane.create(),O=f.plane.create(),P=f.plane.create();return Q});