// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../lib/GLMaterial ./WaterTechnique ./internal/MaterialUtil ./internal/waterMaterialUtils".split(" "),function(f,g,h,k,l,d,e){Object.defineProperty(g,"__esModule",{value:!0});f=function(c){function b(a){a=c.call(this,a)||this;a.techniqueConfig=new l.WaterTechniqueConfiguration;a.updateParameters();return a}h(b,c);b.prototype.updateParameters=function(){this.params=d.copyParameters(this.material.getParameters());this.selectProgram(0)};
b.prototype.selectProgram=function(a){this.techniqueConfig.output=a;this.techniqueConfig.writeDepth=this.params.writeDepth;this.techniqueConfig.receiveShadows=this.params.receiveShadows;this.techniqueConfig.slice=this.params.slicePlaneEnabled;this.techniqueConfig.transparent=this.params.transparent;this.technique=this.techniqueRep.acquireAndReleaseExisting(l.WaterTechnique,this.techniqueConfig,this.technique)};b.prototype.beginSlot=function(a){var b=4;this.params.transparent&&(b=this.params.writeDepth?
6:9);return a===b};b.prototype.getProgram=function(){return this.technique.program};b.prototype.getPrograms=function(){return null};b.prototype._initTextures=function(a){this.texturePaths=[this.params.waveTexture,this.params.perturbationTexture];e.waterTextureRepo.initialize(a,this.texturePaths)};b.prototype._setWaveUniforms=function(a){a.setUniform1i("texWaveNormal",0);a.setUniform1i("texWavePerturbation",1);a.setUniform4f("waveParams",this.params.waveStrength,this.params.waveTextureRepeat,this.params.flowStrength,
this.params.flowOffset);a.setUniform2f("waveDirection",this.params.waveDirection[0]*this.params.waveVelocity,this.params.waveDirection[1]*this.params.waveVelocity);a.setUniform1f("timeElapsed",.001*this.material.animation.time*this.params.animationSpeed)};b.prototype._updateShadowState=function(a){a.shadowMappingEnabled!==this.params.receiveShadows&&(this.material.setParameterValues({receiveShadows:a.shadowMappingEnabled}),this.updateParameters())};b.prototype.ensureResources=function(a){e.waterTextureRepo.ready()||
e.waterTextureRepo.loading()||this._initTextures(a);return e.waterTextureRepo.ready()?2:1};b.prototype.bind=function(a,b){e.waterTextureRepo.ready()&&(this._updateShadowState(b),a.bindProgram(this.technique.program),a.setPipelineState(this.technique.pipeline),e.waterTextureRepo.bindRepo(a),this.technique.program.setUniform4fv("waterColor",this.params.color),this._setWaveUniforms(this.technique.program))};b.prototype.release=function(){};b.prototype.bindView=function(a){var b=this.technique.program;
b.setUniform3fv("localOrigin",a.origin);d.bindView(a.origin,a.view,b);d.bindCamPos(a.origin,a.viewInvTransp,b);this.params.slicePlaneEnabled&&d.bindSlicePlane(a.origin,a.slicePlane,b);a.shadowMappingEnabled&&(a.shadowMap.bind(b),a.shadowMap.bindView(b,a.origin))};b.prototype.bindInstance=function(a){this.technique.program.setUniformMatrix4fv("model",a.transformation)};b.prototype.getDrawMode=function(){return 4};return b}(k.GLMaterial);g.WaterGLMaterial=f;k=function(c){function b(){return null!==
c&&c.apply(this,arguments)||this}h(b,c);b.prototype.updateParameters=function(){this.params=d.copyParameters(this.material.getParameters());this.selectProgram(5)};b.prototype.bind=function(a){a.bindProgram(this.technique.program);a.setPipelineState(this.technique.pipeline);this.technique.program.setUniform4fv("waterColor",this.params.color)};b.prototype.bindView=function(a){this.technique.program.setUniform3fv("localOrigin",a.origin);d.bindView(a.origin,a.view,this.technique.program)};b.prototype.beginSlot=
function(a){return null==a};return b}(f);g.WaterDrapedGLMaterial=k;f=function(c){function b(){return null!==c&&c.apply(this,arguments)||this}h(b,c);b.prototype.updateParameters=function(){this.params=d.copyParameters(this.material.getParameters());this.selectProgram(2)};b.prototype.bind=function(a){e.waterTextureRepo.ready()&&(a.bindProgram(this.technique.program),a.setPipelineState(this.technique.pipeline),e.waterTextureRepo.bindRepo(a),this._setWaveUniforms(this.technique.program))};b.prototype.bindView=
function(a){this.technique.program.setUniform3fv("localOrigin",a.origin);d.bindView(a.origin,a.view,this.technique.program)};b.prototype.beginSlot=function(a){return 19===a};return b}(f);g.WaterNormalGLMaterial=f});