// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../tsSupport/generatorHelper ../tsSupport/awaiterHelper ../global ../has ../promiseUtils ./utils @dojo/framework/shim/Promise".split(" "),function(c,v,r,n,g,w,t,h){var u=function(){return function(){var a=this,d=document.createDocumentFragment();["addEventListener","dispatchEvent","removeEventListener"].forEach(function(b){a[b]=function(){for(var q=[],a=0;a<arguments.length;a++)q[a]=arguments[a];return d[b].apply(d,q)}})}}(),k=g.MutationObserver||g.WebKitMutationObserver,l=
function(){var a;if(g.process&&g.process.nextTick)a=function(d){g.process.nextTick(d)};else if(g.Promise)a=function(d){g.Promise.resolve().then(d)};else if(k){var d=[],b=document.createElement("div");(new k(function(){for(;0<d.length;)d.shift()()})).observe(b,{attributes:!0});a=function(a){d.push(a);b.setAttribute("queueStatus","1")}}return a}(),m=function(){var a=g.MessageEvent;try{new a("message",{data:null})}catch(d){return function(d,a){void 0===a&&(a={});var b=a.data,c=a.bubbles,c=void 0===c?
!1:c;a=a.cancelable;a=void 0===a?!1:a;var e=document.createEvent("Event");e.initEvent(d,c,a);e.data=b;return e}}return function(d,b){return new a(d,b)}}();return function(){function a(){this._dispatcher=new u;this._isInitialized=!1;this._workerPostMessage({type:h.MessageType.HANDSHAKE})}a.prototype.terminate=function(){};Object.defineProperty(a.prototype,"onmessage",{get:function(){return this._onmessageHandler},set:function(a){this._onmessageHandler&&this.removeEventListener("message",this._onmessageHandler);
(this._onmessageHandler=a)&&this.addEventListener("message",a)},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"onerror",{get:function(){return this._onerrorHandler},set:function(a){this._onerrorHandler&&this.removeEventListener("error",this._onerrorHandler);(this._onerrorHandler=a)&&this.addEventListener("error",a)},enumerable:!0,configurable:!0});a.prototype.postMessage=function(a){var d=this;l(function(){d._workerMessageHandler(m("message",{data:a}))})};a.prototype.dispatchEvent=
function(a){return this._dispatcher.dispatchEvent(a)};a.prototype.addEventListener=function(a,b,c){this._dispatcher.addEventListener(a,b,c)};a.prototype.removeEventListener=function(a,b,c){this._dispatcher.removeEventListener(a,b,c)};a.prototype._workerPostMessage=function(a){var b=this;l(function(){b.dispatchEvent(m("message",{data:a}))})};a.prototype._workerMessageHandler=function(a){return n(this,void 0,void 0,function(){var b,d,g,p,e,k,l,m,n=this;return r(this,function(f){switch(f.label){case 0:b=
h.receiveMessage(a);if(!b)return[2];d=b.type;switch(d){case h.MessageType.CONFIGURE:return[3,1];case h.MessageType.OPEN:return[3,2]}return[3,27];case 1:return this._isInitialized||this._workerPostMessage({type:h.MessageType.CONFIGURED}),[3,27];case 2:return g=b.modulePath,p=b.jobId,[3,25];case 3:k=f.sent();l=g;switch(l){case "esri/tasks/operations/PBFWorker":return[3,4];case "esri/views/2d/engine/vectorTiles/WorkerTileHandler":return[3,6];case "esri/views/2d/layers/features/Pipeline":return[3,8];
case "esri/views/3d/layers/PointCloudWorker":return[3,10];case "esri/views/3d/layers/SceneLayerWorker":return[3,12];case "esri/layers/graphics/sources/support/CSVSourceWorker":return[3,14];case "esri/layers/support/LercWorker":return[3,16];case "esri/views/3d/webgl-engine/lib/edgeRendering/EdgeProcessingWorker":return[3,18];case "esri/geometry/support/meshUtils/ElevationSamplerWorker":return[3,20]}return[3,22];case 4:return[4,new Promise(function(a,b){c(["esri/tasks/operations/PBFWorker"],a,b)})];
case 5:return e=f.sent(),[3,24];case 6:return[4,new Promise(function(a,b){c(["esri/views/2d/engine/vectorTiles/WorkerTileHandler"],a,b)})];case 7:return e=f.sent(),[3,24];case 8:return[4,new Promise(function(a,b){c(["esri/views/2d/layers/features/Pipeline"],a,b)})];case 9:return e=f.sent(),[3,24];case 10:return[4,new Promise(function(a,b){c(["esri/views/3d/layers/PointCloudWorker"],a,b)})];case 11:return e=f.sent(),[3,24];case 12:return[4,new Promise(function(a,b){c(["esri/views/3d/layers/SceneLayerWorker"],
a,b)})];case 13:return e=f.sent(),[3,24];case 14:return[4,new Promise(function(a,b){c(["esri/layers/graphics/sources/support/CSVSourceWorker"],a,b)})];case 15:return e=f.sent(),[3,24];case 16:return[4,new Promise(function(a,b){c(["esri/layers/support/LercWorker"],a,b)})];case 17:return e=f.sent(),[3,24];case 18:return[4,new Promise(function(a,b){c(["esri/views/3d/webgl-engine/lib/edgeRendering/EdgeProcessingWorker"],a,b)})];case 19:return e=f.sent(),[3,24];case 20:return[4,new Promise(function(a,
b){c(["esri/geometry/support/meshUtils/ElevationSamplerWorker"],a,b)})];case 21:return e=f.sent(),[3,24];case 22:return[4,t.create(function(a){return c([g],a)})];case 23:e=f.sent(),f.label=24;case 24:return m=k.connect(e),this._workerPostMessage({type:h.MessageType.OPENED,jobId:p,data:m}),[3,26];case 25:c(["esri/core/workers/RemoteClient",g],function(a,b){a=a.connect(b);n._workerPostMessage({type:h.MessageType.OPENED,jobId:p,data:a})}),f.label=26;case 26:return[3,27];case 27:return[2]}})})};return a}()});