// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define(["require","exports","../../../../core/LRUCache","../../tiling/TileCoverage","../../tiling/TileKey"],function(A,B,C,D,g){function E(c,a){if(a&&c.level>=a)return[c.id];a=c.level+1;var b=2*c.row,k=2*c.col;c=c.world;return[g.getId(a,b,k,c),g.getId(a,b+1,k,c),g.getId(a,b,k+1,c),g.getId(a,b+1,k+1,c)]}function x(c,a,b){0>=b&&c.set(a.level,a.row,a.col,a.world);var k=a.level-b;c.set(b,a.row>>k,a.col>>k,a.world);return c}Object.defineProperty(B,"__esModule",{value:!0});A=function(){function c(a,b){this._tiles=
new Map;this._tileCache=new C(40,function(a){return a.dispose()});this._viewSize=[0,0];this._previousScale=Number.POSITIVE_INFINITY;this.fadeDuration=300;this.acquireTile=a.acquireTile;this.releaseTile=a.releaseTile;this.tileInfoView=a.tileInfoView;a.fadeDuration&&(this.fadeDuration=a.fadeDuration);this._container=b;a=this.tileInfoView.tileInfo.lods;this._minLevel=a[0].level;this._maxLevel=a[a.length-1].level}c.prototype.destroy=function(){this._tiles.clear();this._tiles=null;this._tileCache.clear();
this._tileCache=null};c.prototype.update=function(a){var b=this;this._updateCacheSize(a);var c=this.tileInfoView.getTileCoverage(a.state,0,"smallest"),h=c.spans,p=c.lodInfo,q=p.level,n=a.state.scale,r=!a.stationary&&n>this._previousScale,e=0,t=0;this._previousScale=n;for(var l=new Set,u=new Set,v=0;v<h.length;v++){a=h[v];var n=a.row,d=a.colFrom;a=a.colTo;for(var m=d;m<=a;m++){e++;var f=g.getId(q,n,p.normalizeCol(m),p.getWorldForColumn(m)),d=this._getOrAcquireTile(f);l.add(f);d.hasData()?(t++,this._container.addChild(d)):
u.add(f)}}v=this._minLevel;this._retainLoadedChildren(u,l,q,this._maxLevel,r,t===e);r=new g(null);e=new Set;for(t=0;t<h.length;t++)for(a=h[t],n=a.row,d=a.colFrom,a=a.colTo,m=d;m<=a;m++)if(f=g.getId(q,n,p.normalizeCol(m),p.getWorldForColumn(m)),d=this._tiles.get(f),!(d.hasData()||(f=E(d.key),l.has(f[0])&&l.has(f[1])&&l.has(f[2])&&l.has(f[3]))))for(var f=d.key,u=!0,y=f.level-1;y>=v;--y){var w=x(r,f,y).id;!e.has(w)&&(e.add(w),d=this._getTile(w))&&(l.add(w),u&&d.hasData()&&(this._container.addChild(d),
u=!1))}l.forEach(function(a){b._tiles.get(a).clearSymbolFadeHold()});var z=[];this._tiles.forEach(function(a,b){l.has(b)||z.push(b)});for(h=0;h<z.length;h++)f=z[h],d=this._tiles.get(f),d.hasSymbolBuckets&&!d.isHoldingForFade?d.setSymbolHoldDuration(this.fadeDuration):d.hasSymbolBuckets&&!d.isSymbolFadeDone||this._releaseTile(f);D.pool.release(c)};c.prototype._retainLoadedChildren=function(a,b,c,h,p,q){var k=this,r=new g(null);this._tiles.forEach(function(e,g){k._retainTopMostLoadedChild(e,g,c,a,b,
h,p,q,r)})};c.prototype._retainTopMostLoadedChild=function(a,b,c,h,g,q,n,r,e){if(!(g.has(b)||!a.hasData()||a.key.level<=c||a.key.level>q))if(n||!r)g.add(a.key.id);else{b=a;for(a=b.key;b&&b.key.level>c+1;)b=x(e,b.key,b.key.level-1),(b=this._tiles.get(b.id))&&b.hasData()&&(a=b.key);for(e.set(a);e.level>c;)if(e=x(e,e,e.level-1),h.has(e.id)){g.add(a.id);break}}};c.prototype._getOrAcquireTile=function(a){var b=this._tiles.get(a);if(b)return b;(b=this._tileCache.pop(a))||(b=this.acquireTile(new g(a)));
this._tiles.set(a,b);return b};c.prototype._getTile=function(a){var b=this._tiles.get(a);if(b)return b;(b=this._tileCache.pop(a))&&this._tiles.set(a,b);return b};c.prototype._releaseTile=function(a){var b=this._tiles.get(a);this.releaseTile(b);this._container.removeChild(b);this._tiles.delete(a);b.hasData()?this._tileCache.put(a,b,1):b.dispose()};c.prototype._updateCacheSize=function(a){a=a.state.size;if(a[0]!==this._viewSize[0]||a[1]!==this._viewSize[1]){var b=Math.ceil(a[0]/512)+1,c=Math.ceil(a[1]/
512)+1;this._viewSize[0]=a[0];this._viewSize[1]=a[1];this._tileCache.maxSize=5*b*c}};return c}();B.TileManager=A});