// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/decorateHelper ../../../../../core/tsSupport/declareExtendsHelper ../../../../../core/tsSupport/generatorHelper ../../../../../core/tsSupport/awaiterHelper ../../../../../core/Handles ../../../../../core/maybe ../../../../../core/watchUtils ../../../../../core/libs/gl-matrix-2/mat4 ../../../../../core/libs/gl-matrix-2/mat4f64 ../../../../../core/libs/gl-matrix-2/vec3f64 ../../Manipulator3D ../../manipulatorUtils ../../dragUtils/projectScreenToMap ./graphicTransform3DToolConfig ../../../webgl-engine/lib/Geometry ../../../webgl-engine/lib/GeometryUtil ../../../webgl-engine/materials/ColorMaterial ../../../../interactive/dragUtils/dragActions ../../../../interactive/dragUtils/dragHandlers ../../../../interactive/dragUtils/screenDragToMap".split(" "),
function(h,k,B,C,D,E,m,e,l,n,p,f,q,r,t,d,u,v,w,x,y,z){Object.defineProperty(k,"__esModule",{value:!0});var g;(g||(g={})).Highlighted=512;h=function(){function b(a){this._handles=new m;this.tool=a.tool}b.prototype.destroy=function(){this._clear()};b.prototype._clear=function(){this._handles.removeAll();this.tool.manipulators.remove(this.discManipulator);this.discManipulator=null};Object.defineProperty(b.prototype,"focused",{get:function(){return this.discManipulator.focused},enumerable:!0,configurable:!0});
Object.defineProperty(b.prototype,"dragging",{get:function(){return this.discManipulator.dragging},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"renderLocation",{get:function(){return this.discManipulator.renderLocation},enumerable:!0,configurable:!0});b.prototype.recreateManipulators=function(){var a=this;this._clear();this.discManipulator=this.createDiscManipulator();this.tool.manipulators.add(this.discManipulator);var c=this.createDragAction(),c=y.createManipulatorDragHandler(this.discManipulator,
this.createDragEventMappingFunction(),c);this._handles.add(c);this._handles.add([l.init(this.tool.graphic,"geometry",function(){r.placeManipulatorAtGraphic(a.discManipulator,a.tool.graphic)}),this.discManipulator.events.on("immediate-click",function(a){a.stopPropagation()}),l.init(this.tool.graphic,["visible","layer.visible"],function(){a.discManipulator.visible=a.tool.graphic.visible&&a.tool.graphic.layer.visible})]);this._handles.add([this.discManipulator.events.on("focus",function(){a.tool.updateManipulators()})])};
b.prototype.updateManipulators=function(a,c){this.discManipulator.modelTransform=a;this.discManipulator.state=c?g.Highlighted:0};b.prototype.createDiscManipulator=function(){var a=this.tool.view,c=new u(v.createCylinderGeometry(d.DISC_HEIGHT,1,d.GEOMETRY_SEGMENTS,f.vec3f64.fromValues(0,0,1),f.vec3f64.fromValues(0,0,0)),"graphic-transform-disc"),b=n.mat4.fromScaling(p.mat4f64.create(),f.vec3f64.fromValues(d.DISC_RADIUS,d.DISC_RADIUS,d.DISC_RADIUS)),A=this.createMaterial(),e=this.createMaterial(.5);
return new q.Manipulator3D({view:a,renderObjects:[{geometry:c,material:A,transform:b,stateMask:g.Highlighted},{geometry:c,material:e,transform:b}],worldSized:!1,autoScaleRenderObjects:!1,focusMultiplier:1,touchMultiplier:1,radius:d.DISC_COLLISION_RADIUS,elevationInfo:{mode:"on-the-ground",offset:0},collisionType:{type:"disc",direction:f.vec3f64.fromValues(0,0,1)}})};b.prototype.createMaterial=function(a){void 0===a&&(a=1);var b=d.HANDLE_COLOR.concat([a]);a=new w({color:b,transparent:1!==a,cullFace:2},
"graphic-transform");a.renderOccluded=2;return a};b.prototype.createDragEventMappingFunction=function(){var a=this;return function(b){var c=z.createXYConstrainedFromProject(t.createForGraphicAtLocation(a.tool.view,a.tool.graphic,b.elevationAlignedLocation),e.expect(a.tool.graphic.geometry).spatialReference);return e.isNone(c)?null:function(a){a=c(a);return e.isNone(a)?null:a}}};b.prototype.createDragAction=function(){var a=this,b=x.createGraphicDragAction(this.tool.graphic);return function(c){"start"===
c.action&&a.tool.emit("graphic-translate-start",{graphic:a.tool.graphic});b(c);switch(c.action){case "update":a.tool.emit("graphic-translate",{graphic:a.tool.graphic,dx:c.deltaX,dy:c.deltaY,dz:c.deltaZ,type:"translate"});break;case "end":a.tool.emit("graphic-translate-stop",{graphic:a.tool.graphic})}}};return b}();k.GraphicXYTransform=h});