// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/decorateHelper ../../../../../core/tsSupport/declareExtendsHelper ../../../../../core/tsSupport/generatorHelper ../../../../../core/tsSupport/awaiterHelper ../../../../../core/Evented ../../../../../core/Handles ../../../../../core/Logger ../../../../../core/maybe ../../../../../core/watchUtils ../../../../../core/accessorSupport/decorators ../../../../../core/libs/gl-matrix-2/mat4 ../../../../../core/libs/gl-matrix-2/vec3 ../../../../../core/libs/gl-matrix-2/math/common ../../../../../support/elevationInfoUtils ../../../../../support/featureFlags ../isSupportedGraphicUtils ../manipulatorUtils ./GraphicScaleRotateTransform ./GraphicXYAxisTransform ./GraphicXYTransform ./GraphicZTransform ./isSupportedGraphic ../../../support/stack ../../../../interactive/InteractiveToolBase".split(" "),
function(g,k,f,p,H,I,q,r,t,c,u,e,l,v,w,x,y,z,A,B,C,D,E,F,h,G){Object.defineProperty(k,"__esModule",{value:!0});var m=t.getLogger("esri.views.3d.interactive.editingTools.graphicTransform3D.GraphicTransform3DTool");g=function(g){function a(b){b=g.call(this,b)||this;b.enableRotation=!0;b.enableScaling=!0;b.type="transform-3d";b.handles=new r;b.zTransform=null;b.scaleRotate=null;return b}p(a,g);a.prototype.initialize=function(){this.xyTransform=new D.GraphicXYTransform({tool:this});this.xyAxisTransform=
new C.GraphicXYAxisTransform({tool:this});if(this.enableScaling||this.enableRotation)this.scaleRotate=new B.GraphicScaleRotateTransform({tool:this,mode:this.enableScaling&&this.enableRotation?null:this.enableScaling?"scale":"rotate"});y.enableEditing3D()&&A.canMoveZ(this.graphic,x.getGraphicEffectiveElevationInfo(this.graphic))&&(this.zTransform=new E.GraphicZTransform({tool:this}));this._recreateManipulators()};a.prototype.destroy=function(){this._clear();this.xyTransform.destroy();this.xyTransform=
null;this.xyAxisTransform.destroy();this.xyAxisTransform=null;c.isSome(this.scaleRotate)&&(this.scaleRotate.destroy(),this.scaleRotate=null);c.isSome(this.zTransform)&&(this.zTransform.destroy(),this.zTransform=null);this._set("view",null);this._set("graphic",null)};Object.defineProperty(a.prototype,"graphic",{set:function(b){if(null==b)m.error("invalid graphic");else{var n=F.isSupportedGraphic(b);0!==n?(m.error("Transform tool not supported for graphic ("+z.isSupportedGraphicResultMessage(n)+")."),
this._set("graphic",null)):this._set("graphic",b)}},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"symbolRotationAngle",{get:function(){var b=this.graphic.symbol;return b?(b=b.symbolLayers.find(function(b){return"object"===b.type}),w.toRadian(-(b&&b.heading||0))):0},enumerable:!0,configurable:!0});a.prototype.reset=function(){};a.prototype.onDetach=function(){c.isSome(this.scaleRotate)&&this.scaleRotate.cancelActiveAnimation()};a.prototype.onHide=function(){c.isSome(this.scaleRotate)&&
this.scaleRotate.cancelActiveAnimation()};a.prototype._clear=function(){this.handles.removeAll()};a.prototype._recreateManipulators=function(){var b=this;this._clear();var a=c.unwrap(this.graphic);this.xyTransform.recreateManipulators();this.xyAxisTransform.recreateManipulators();c.isSome(this.scaleRotate)&&this.scaleRotate.recreateManipulators();c.isSome(this.zTransform)&&this.zTransform.recreateManipulators();this.handles.add([u.watch(a,"geometry",function(){return b.updateManipulators()})]);this.updateManipulators()};
a.prototype.updateManipulators=function(){var b=this.view.renderCoordsHelper.basisMatrixAtPosition(this.xyTransform.renderLocation,h.sm4d.get()),a="none";this.xyTransform.focused?a="xy":this.xyAxisTransform.focused?a="xy-axis":c.isSome(this.scaleRotate)&&this.scaleRotate.getFocused()&&(a="scale-rotate");c.isSome(this.zTransform)&&this.zTransform.dragging&&(a="z");c.isSome(this.scaleRotate)&&this.scaleRotate.dragging&&(a="scale-rotate");this.xyAxisTransform.dragging&&(a="xy-axis");this.xyTransform.dragging&&
(a="xy");var d=b;c.isSome(this.scaleRotate)&&(this.scaleRotate.updateManipulators(b,"scale-rotate"===a),d=this.scaleRotate.getScale(),d=l.mat4.fromScaling(h.sm4d.get(),v.vec3.set(h.sv3d.get(),d,d,d)),d=l.mat4.multiply(h.sm4d.get(),b,d));this.xyTransform.updateManipulators(d,"none"===a||"xy"===a);this.xyAxisTransform.updateManipulators(d,"xy"===a||"xy-axis"===a,"xy-axis"===a);c.isSome(this.zTransform)&&this.zTransform.updateManipulators(d)};f([e.property({constructOnly:!0,nonNullable:!0})],a.prototype,
"view",void 0);f([e.property({value:null})],a.prototype,"graphic",null);f([e.property()],a.prototype,"enableRotation",void 0);f([e.property()],a.prototype,"enableScaling",void 0);f([e.property({readOnly:!0})],a.prototype,"type",void 0);return a=f([e.subclass("esri.views.3d.interactive.editingTools.graphicTransform3D.GraphicTransform3DTool")],a)}(e.declared(q.EventedMixin(G.InteractiveToolBase)));k.GraphicTransform3DTool=g});