// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
require({cache:{"esri/core/sql/AggregateFunctions":function(){define(["require","exports"],function(F,d){function x(d){for(var m=0,q=0;q<d.length;q++)m+=d[q];return m/d.length}function g(d){for(var m=x(d),q=d.length,g=0,A=0;A<d.length;A++)g+=Math.pow(d[A]-m,2);return 1<q?g/(q-1):0}Object.defineProperty(d,"__esModule",{value:!0});d.aggregateFunction=function(d,g){var q=m[d.toLowerCase()];if(null==q)throw Error("Function Not Recognised");if(g.length<q.minParams||g.length>q.maxParams)throw Error("Invalid Parameter count for call to "+
d.toUpperCase());return q.evaluate(g)};d.isAggregate=function(d,g){d=m[d.toLowerCase()];return null!=d&&g>=d.minParams&&g<=d.maxParams};var m={min:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:Math.min.apply(Math,d[0])}},max:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:Math.max.apply(Math,d[0])}},avg:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:x(d[0])}},sum:{minParams:1,maxParams:1,evaluate:function(d){if(null==d[0])d=null;else{d=
d[0];for(var m=0,l=0;l<d.length;l++)m+=d[l];d=m}return d}},stddev:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:Math.sqrt(g(d[0]))}},count:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:d[0].length}},var:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:g(d[0])}}}})},"esri/core/sql/StandardizedFunctions":function(){define(["require","exports","../string"],function(F,d,x){Object.defineProperty(d,"__esModule",{value:!0});F=function(){function d(){this.op=
"+";this.minute=this.year=this.month=this.hour=this.second=this.day=0}d.fixDefaults=function(d){if(null!==d.precision||null!==d.secondary)throw Error("Primary and Secondary SqlInterval qualifiers not supported");};d.createFromMilliseconds=function(m){var q=new d;q.second=m/1E3;return q};d.createFromValueAndQualifer=function(m,g,l){var q=null,A=new d;A.op="-"===l?"-":"+";if("interval-period"===g.type){d.fixDefaults(g);if("year"===g.period||"month"===g.period)throw Error("Year-Month Intervals not supported");
if(/^[0-9]{1,}$/.test(m))A[g.period]=parseFloat(m);else throw Error("Illegal Interval");}else{d.fixDefaults(g.start);d.fixDefaults(g.end);if("year"===g.start.period||"month"===g.start.period)throw Error("Year-Month Intervals not supported");if("year"===g.end.period||"month"===g.end.period)throw Error("Year-Month Intervals not supported");switch(g.start.period){case "day":switch(g.end.period){case "hour":q=/^[0-9]{1,} [0-9]{1,}$/;if(q.test(m))A[g.start.period]=parseFloat(m.split(" ")[0]),A[g.end.period]=
parseFloat(m.split(" ")[1]);else throw Error("Illegal Interval");break;case "minute":q=/^[0-9]{1,} [0-9]{1,2}:[0-9]{1,}$/;if(q.test(m))A[g.start.period]=parseFloat(m.split(" ")[0]),m=m.split(" ")[1].split(":"),A.hour=parseFloat(m[0]),A.minute=parseFloat(m[1]);else throw Error("Illegal Interval");break;case "second":q=/^[0-9]{1,} [0-9]{1,2}:[0-9]{1,2}:[0-9]{1,}([.]{1}[0-9]{1,}){0,1}$/;if(q.test(m))A[g.start.period]=parseFloat(m.split(" ")[0]),m=m.split(" ")[1].split(":"),A.hour=parseFloat(m[0]),A.minute=
parseFloat(m[1]),A.second=parseFloat(m[2]);else throw Error("Illegal Interval");break;default:throw"Invalid Interval.";}break;case "hour":switch(g.end.period){case "minute":q=/^[0-9]{1,}:[0-9]{1,}$/;if(q.test(m))A.hour=parseFloat(m.split(":")[0]),A.minute=parseFloat(m.split(":")[1]);else throw Error("Illegal Interval");break;case "second":q=/^[0-9]{1,}:[0-9]{1,2}:[0-9]{1,}([.]{1}[0-9]{1,}){0,1}$/;if(q.test(m))m=m.split(":"),A.hour=parseFloat(m[0]),A.minute=parseFloat(m[1]),A.second=parseFloat(m[2]);
else throw Error("Illegal Interval");break;default:throw"Invalid Interval.";}break;case "minute":switch(g.end.period){case "second":q=/^[0-9]{1,}:[0-9]{1,}([.]{1}[0-9]{1,}){0,1}$/;if(q.test(m))m=m.split(":"),A.minute=parseFloat(m[0]),A.second=parseFloat(m[1]);else throw Error("Illegal Interval");break;default:throw"Invalid Interval.";}break;default:throw"Invalid Interval.";}}return A};d.prototype.valueInMilliseconds=function(){return("-"===this.op?-1:1)*(1E3*this.second+6E4*this.minute+36E5*this.hour+
864E5*this.day+365/12*this.month*864E5+31536E6*this.year)};return d}();d.SqlInterval=F;d.evaluateFunction=function(d,q){var m=g[d.toLowerCase()];if(null==m)throw Error("Function Not Recognised");if(q.length<m.minParams||q.length>m.maxParams)throw Error("Invalid Parameter count for call to "+d.toUpperCase());return m.evaluate(q)};d.isStandardized=function(d,q){d=g[d.toLowerCase()];return null!=d&&q>=d.minParams&&q<=d.maxParams};var g={extract:{minParams:2,maxParams:2,evaluate:function(d){var m=d[0];
d=d[1];if(null==d)return null;if(d instanceof Date)switch(m.toUpperCase()){case "SECOND":return d.getSeconds();case "MINUTE":return d.getMinutes();case "HOUR":return d.getHours();case "DAY":return d.getDate();case "MONTH":return d.getMonth()+1;case "YEAR":return d.getFullYear()}throw Error("Invalid Parameter for call to EXTRACT");}},substring:{minParams:2,maxParams:3,evaluate:function(d){if(2===d.length){var m=d[0],g=d[1];return null==m||null==g?null:m.toString().substring(g-1)}if(3===d.length)return m=
d[0],g=d[1],d=d[2],null==m||null==g||null==d?null:0>=d?"":m.toString().substring(g-1,g+d-1)}},position:{minParams:2,maxParams:2,evaluate:function(d){var m=d[0];d=d[1];return null==m||null==d?null:d.indexOf(m)+1}},trim:{minParams:2,maxParams:3,evaluate:function(d){var m=3===d.length,g=m?d[1]:" ",m=m?d[2]:d[1];if(null==g||null==m)return null;g="("+x.escapeRegExpString(g)+")";switch(d[0]){case "BOTH":return m.replace(new RegExp("^"+g+"*|"+g+"*$","g"),"");case "LEADING":return m.replace(new RegExp("^"+
g+"*","g"),"");case "TRAILING":return m.replace(new RegExp(g+"*$","g"),"")}throw Error("Invalid Parameter for call to TRIM");}},abs:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:Math.abs(d[0])}},ceiling:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:Math.ceil(d[0])}},floor:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:Math.floor(d[0])}},log:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:Math.log(d[0])}},log10:{minParams:1,
maxParams:1,evaluate:function(d){return null==d[0]?null:Math.log(d[0])*Math.LOG10E}},sin:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:Math.sin(d[0])}},cos:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:Math.cos(d[0])}},tan:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:Math.tan(d[0])}},asin:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:Math.asin(d[0])}},acos:{minParams:1,maxParams:1,evaluate:function(d){return null==
d[0]?null:Math.acos(d[0])}},atan:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:Math.atan(d[0])}},sign:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:0<d[0]?1:0>d[1]?-1:0}},power:{minParams:2,maxParams:2,evaluate:function(d){return null==d[0]||null==d[1]?null:Math.pow(d[0],d[1])}},mod:{minParams:2,maxParams:2,evaluate:function(d){return null==d[0]||null==d[1]?null:d[0]%d[1]}},round:{minParams:1,maxParams:2,evaluate:function(d){var g=d[0];d=2===d.length?
Math.pow(10,d[1]):1;return null==g?null:Math.round(g*d)/d}},truncate:{minParams:1,maxParams:2,evaluate:function(d){return null==d[0]?null:1===d.length?parseInt(d[0].toFixed(0),10):parseFloat(d[0].toFixed(d[1]))}},char_length:{minParams:1,maxParams:1,evaluate:function(d){return"string"===typeof d[0]||d[0]instanceof String?d[0].length:0}},concat:{minParams:1,maxParams:Infinity,evaluate:function(d){for(var g="",m=0;m<d.length;m++){if(null==d[m])return null;g+=d[m].toString()}return g}},lower:{minParams:1,
maxParams:1,evaluate:function(d){return null==d[0]?null:d[0].toString().toLowerCase()}},upper:{minParams:1,maxParams:1,evaluate:function(d){return null==d[0]?null:d[0].toString().toUpperCase()}}}})},"esri/core/sql/WhereGrammar":function(){define(["require","exports","./sql92grammar"],function(F,d,x){Object.defineProperty(d,"__esModule",{value:!0});F=function(){function d(){}d.parse=function(d){return x.parse(d)};return d}();d.WhereGrammar=F})},"esri/core/sql/sql92grammar":function(){define([],function(){function F(d,
x,g,m){this.message=d;this.expected=x;this.found=g;this.location=m;this.name="SyntaxError";"function"===typeof Error.captureStackTrace&&Error.captureStackTrace(this,F)}(function(d,x){function g(){this.constructor=d}g.prototype=x.prototype;d.prototype=new g})(F,Error);F.buildMessage=function(d,x){function g(d){return d.charCodeAt(0).toString(16).toUpperCase()}function m(d){return d.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\0/g,"\\0").replace(/\t/g,"\\t").replace(/\n/g,"\\n").replace(/\r/g,
"\\r").replace(/[\x00-\x0F]/g,function(d){return"\\x0"+g(d)}).replace(/[\x10-\x1F\x7F-\x9F]/g,function(d){return"\\x"+g(d)})}function q(d){return d.replace(/\\/g,"\\\\").replace(/\]/g,"\\]").replace(/\^/g,"\\^").replace(/-/g,"\\-").replace(/\0/g,"\\0").replace(/\t/g,"\\t").replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/[\x00-\x0F]/g,function(d){return"\\x0"+g(d)}).replace(/[\x10-\x1F\x7F-\x9F]/g,function(d){return"\\x"+g(d)})}var F={literal:function(d){return'"'+m(d.text)+'"'},"class":function(d){var g=
"",l;for(l=0;l<d.parts.length;l++)g+=d.parts[l]instanceof Array?q(d.parts[l][0])+"-"+q(d.parts[l][1]):q(d.parts[l]);return"["+(d.inverted?"^":"")+g+"]"},any:function(d){return"any character"},end:function(d){return"end of input"},other:function(d){return d.description}};return"Expected "+function(d){var g=Array(d.length),l;for(l=0;l<d.length;l++){var m=l,q;q=d[l];q=F[q.type](q);g[m]=q}g.sort();if(0<g.length){for(d=l=1;l<g.length;l++)g[l-1]!==g[l]&&(g[d]=g[l],d++);g.length=d}switch(g.length){case 1:return g[0];
case 2:return g[0]+" or "+g[1];default:return g.slice(0,-1).join(", ")+", or "+g[g.length-1]}}(d)+" but "+(x?'"'+m(x)+'"':"end of input")+" found."};return{SyntaxError:F,parse:function(d,x){function g(a,b){return{type:"literal",text:a,ignoreCase:b}}function m(a,b,h){return{type:"class",parts:a,inverted:b,ignoreCase:h}}function q(a){var b=ra[a],e;if(!b){for(e=a-1;!ra[e];)e--;b=ra[e];for(b={line:b.line,column:b.column};e<a;)10===d.charCodeAt(e)?(b.line++,b.column=1):b.column++,e++;ra[a]=b}return b}
function ka(a,b){var e=q(a),p=q(b);return{start:{offset:a,line:e.line,column:e.column},end:{offset:b,line:p.line,column:p.column}}}function l(a){b<R||(b>R&&(R=b,Da=[]),Da.push(a))}function I(){var e,p,h;e=b;p=n();p!==a?(p=G(),p!==a?(h=n(),h!==a?e=p:(b=e,e=a)):(b=e,e=a)):(b=e,e=a);return e}function A(){var e,p,h,d,c,f,k,g;e=b;p=G();if(p!==a){h=[];d=b;c=n();c!==a?(f=la(),f!==a?(k=n(),k!==a?(g=G(),g!==a?d=c=[c,f,k,g]:(b=d,d=a)):(b=d,d=a)):(b=d,d=a)):(b=d,d=a);for(;d!==a;)h.push(d),d=b,c=n(),c!==a?(f=
la(),f!==a?(k=n(),k!==a?(g=G(),g!==a?d=c=[c,f,k,g]:(b=d,d=a)):(b=d,d=a)):(b=d,d=a)):(b=d,d=a);if(h!==a){e={type:"expr_list"};p=[p];for(d=0;d<h.length;d++)p.push(h[d][3]);e.value=p}else b=e,e=a}else b=e,e=a;return e}function G(){var e,p,h,d,c,f,k,g;e=b;p=N();if(p!==a){h=[];d=b;c=n();c!==a?(f=Pa(),f!==a?(k=n(),k!==a?(g=N(),g!==a?d=c=[c,f,k,g]:(b=d,d=a)):(b=d,d=a)):(b=d,d=a)):(b=d,d=a);for(;d!==a;)h.push(d),d=b,c=n(),c!==a?(f=Pa(),f!==a?(k=n(),k!==a?(g=N(),g!==a?d=c=[c,f,k,g]:(b=d,d=a)):(b=d,d=a)):(b=
d,d=a)):(b=d,d=a);h!==a?e=p=ma(p,h):(b=e,e=a)}else b=e,e=a;return e}function N(){var e,p,h,d,c,f,k,g;e=b;p=L();if(p!==a){h=[];d=b;c=n();c!==a?(f=ga(),f!==a?(k=n(),k!==a?(g=L(),g!==a?d=c=[c,f,k,g]:(b=d,d=a)):(b=d,d=a)):(b=d,d=a)):(b=d,d=a);for(;d!==a;)h.push(d),d=b,c=n(),c!==a?(f=ga(),f!==a?(k=n(),k!==a?(g=L(),g!==a?d=c=[c,f,k,g]:(b=d,d=a)):(b=d,d=a)):(b=d,d=a)):(b=d,d=a);h!==a?e=p=ma(p,h):(b=e,e=a)}else b=e,e=a;return e}function L(){var e,p,h,c,f;e=b;p=da();p===a&&(p=b,33===d.charCodeAt(b)?(h=ad,
b++):(h=a,0===k&&l(bd)),h!==a?(c=b,k++,61===d.charCodeAt(b)?(f=Qa,b++):(f=a,0===k&&l(Ra)),k--,f===a?c=void 0:(b=c,c=a),c!==a?p=h=[h,c]:(b=p,p=a)):(b=p,p=a));p!==a?(h=n(),h!==a?(c=L(),c!==a?e=p={type:"unary_expr",operator:"NOT",expr:c}:(b=e,e=a)):(b=e,e=a)):(b=e,e=a);if(e===a)if(e=b,p=M(),p!==a)if(h=n(),h!==a){var g,r,m;h=[];c=b;f=n();f!==a?(g=ca(),g!==a?(r=n(),r!==a?(m=M(),m!==a?c=f=[f,g,r,m]:(b=c,c=a)):(b=c,c=a)):(b=c,c=a)):(b=c,c=a);if(c!==a)for(;c!==a;)h.push(c),c=b,f=n(),f!==a?(g=ca(),g!==a?(r=
n(),r!==a?(m=M(),m!==a?c=f=[f,g,r,m]:(b=c,c=a)):(b=c,c=a)):(b=c,c=a)):(b=c,c=a);else h=a;h!==a&&(h={type:"arithmetic",tail:h});h===a&&(h=b,c=S(),c!==a?(f=n(),f!==a?(f=O(),f!==a?(f=n(),f!==a?(f=A(),f!==a?(g=n(),g!==a?(g=P(),g!==a?h=c={op:c,right:f}:(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a),h===a&&(h=b,c=S(),c!==a?(f=n(),f!==a?(f=O(),f!==a?(f=n(),f!==a?(f=P(),f!==a?h=c={op:c,right:{type:"expr_list",value:[]}}:(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a),h===
a&&(h=b,c=S(),c!==a?(f=n(),f!==a?(f=Sa(),f!==a?h=c={op:c,right:f}:(b=h,h=a)):(b=h,h=a)):(b=h,h=a))),h===a&&(h=b,f=da(),f!==a?(c=n(),c!==a?(c=Ta(),c!==a?(g=n(),g!==a?(g=M(),g!==a?(r=n(),r!==a?(r=ga(),r!==a?(f=n(),f!==a?(f=M(),f!==a?h=f={op:"NOT"+c,right:{type:"expr_list",value:[g,f]}}:(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a),h===a&&(h=b,f=Ta(),f!==a?(c=n(),c!==a?(c=M(),c!==a?(g=n(),g!==a?(g=ga(),g!==a?(r=n(),r!==a?(r=M(),r!==a?h=f={op:f,right:{type:"expr_list",
value:[c,r]}}:(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)),h===a&&(h=b,c=Ua(),c!==a?(f=n(),f!==a?(f=da(),f!==a?(f=n(),f!==a?(f=M(),f!==a?h=c={op:c+"NOT",right:f}:(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a),h===a&&(h=b,c=Ua(),c!==a?(f=n(),f!==a?(f=M(),f!==a?h=c={op:c,right:f}:(b=h,h=a)):(b=h,h=a)):(b=h,h=a)),h===a&&(h=b,c=na(),c!==a?(f=n(),f!==a?(f=t(),f!==a?(g=n(),g!==a?(g=b,d.substr(b,6).toLowerCase()===cd?(r=d.substr(b,6),b+=6):(r=a,0===k&&l(dd)),r!==a?
(r=b,k++,m=v(),k--,m===a?r=void 0:(b=r,r=a),r!==a?g="ESCAPE":(b=g,g=a)):(b=g,g=a),g!==a?(g=n(),g!==a?(g=cc(),g!==a?h=c={op:c,right:f,escape:g.value}:(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a),h===a&&(h=b,c=na(),c!==a?(f=n(),f!==a?(f=t(),f!==a?h=c={op:c,right:f,escape:""}:(b=h,h=a)):(b=h,h=a)):(b=h,h=a))))));h===a&&(h=null);h!==a?(e=p,p=h,""==p||void 0==p||null==p?p=e:(h=null,p=h="arithmetic"==p.type?ma(e,p.tail):Va(p.op,e,p.right,p.escape)),e=p):(b=e,e=a)}else b=e,
e=a;else b=e,e=a;return e}function ca(){var e;d.substr(b,2)===Wa?(e=Wa,b+=2):(e=a,0===k&&l(ed));e===a&&(62===d.charCodeAt(b)?(e=fd,b++):(e=a,0===k&&l(gd)),e===a&&(d.substr(b,2)===Xa?(e=Xa,b+=2):(e=a,0===k&&l(hd)),e===a&&(d.substr(b,2)===Ya?(e=Ya,b+=2):(e=a,0===k&&l(id)),e===a&&(60===d.charCodeAt(b)?(e=jd,b++):(e=a,0===k&&l(kd)),e===a&&(61===d.charCodeAt(b)?(e=Qa,b++):(e=a,0===k&&l(Ra)),e===a&&(d.substr(b,2)===Za?(e=Za,b+=2):(e=a,0===k&&l(ld))))))));return e}function na(){var e,c,d,f;e=e=b;c=da();
c!==a?(d=n(),d!==a?(f=$a(),f!==a?e=c=[c,d,f]:(b=e,e=a)):(b=e,e=a)):(b=e,e=a);e!==a&&(e=e[0]+" "+e[2]);e===a&&(e=$a());return e}function S(){var e,c,d,f;e=e=b;c=da();c!==a?(d=n(),d!==a?(f=dc(),f!==a?e=c=[c,d,f]:(b=e,e=a)):(b=e,e=a)):(b=e,e=a);e!==a&&(e=e[0]+" "+e[2]);e===a&&(e=dc());return e}function M(){var e,c,d,f,g,k,r,t;e=b;c=T();if(c!==a){d=[];f=b;g=n();g!==a?(k=H(),k!==a?(r=n(),r!==a?(t=T(),t!==a?f=g=[g,k,r,t]:(b=f,f=a)):(b=f,f=a)):(b=f,f=a)):(b=f,f=a);for(;f!==a;)d.push(f),f=b,g=n(),g!==a?(k=
H(),k!==a?(r=n(),r!==a?(t=T(),t!==a?f=g=[g,k,r,t]:(b=f,f=a)):(b=f,f=a)):(b=f,f=a)):(b=f,f=a);d!==a?e=c=ma(c,d):(b=e,e=a)}else b=e,e=a;return e}function H(){var e;43===d.charCodeAt(b)?(e=ec,b++):(e=a,0===k&&l(fc));e===a&&(45===d.charCodeAt(b)?(e=gc,b++):(e=a,0===k&&l(hc)));return e}function T(){var e,c,d,f,g,k,r,t;e=b;c=ha();if(c!==a){d=[];f=b;g=n();g!==a?(k=V(),k!==a?(r=n(),r!==a?(t=ha(),t!==a?f=g=[g,k,r,t]:(b=f,f=a)):(b=f,f=a)):(b=f,f=a)):(b=f,f=a);for(;f!==a;)d.push(f),f=b,g=n(),g!==a?(k=V(),k!==
a?(r=n(),r!==a?(t=ha(),t!==a?f=g=[g,k,r,t]:(b=f,f=a)):(b=f,f=a)):(b=f,f=a)):(b=f,f=a);d!==a?e=c=ma(c,d):(b=e,e=a)}else b=e,e=a;return e}function V(){var e;42===d.charCodeAt(b)?(e=md,b++):(e=a,0===k&&l(nd));e===a&&(47===d.charCodeAt(b)?(e=od,b++):(e=a,0===k&&l(pd)));return e}function ha(){var e,c,h,f,g,r,m;m=cc();if(m===a){var q,x,F,M;q=b;var C,J,H,R;C=b;J=Ab();J!==a?(H=xc(),H!==a?(R=yc(),R!==a?C=J=parseFloat(J+H+R):(b=C,C=a)):(b=C,C=a)):(b=C,C=a);C===a&&(C=b,J=Ab(),J!==a?(H=xc(),H!==a?C=J=parseFloat(J+
H):(b=C,C=a)):(b=C,C=a),C===a&&(C=b,J=Ab(),J!==a?(H=yc(),H!==a?C=J=parseFloat(J+H):(b=C,C=a)):(b=C,C=a),C===a&&(C=b,J=Ab(),J!==a&&(J=parseFloat(J)),C=J)));x=C;x!==a?(F=b,k++,M=Ea(),k--,M===a?F=void 0:(b=F,F=a),F!==a?q=x={type:"number",value:x}:(b=q,q=a)):(b=q,q=a);m=q;if(m===a){var L,I;L=b;var N,S,T,ha;N=b;d.substr(b,4).toLowerCase()===qd?(S=d.substr(b,4),b+=4):(S=a,0===k&&l(rd));S!==a?(T=b,k++,ha=v(),k--,ha===a?T=void 0:(b=T,T=a),T!==a?N=S=[S,T]:(b=N,N=a)):(b=N,N=a);I=N;I!==a&&(I={type:"bool",value:!0});
L=I;if(L===a){L=b;var sa,V,U,ma;sa=b;d.substr(b,5).toLowerCase()===sd?(V=d.substr(b,5),b+=5):(V=a,0===k&&l(td));V!==a?(U=b,k++,ma=v(),k--,ma===a?U=void 0:(b=U,U=a),U!==a?sa=V=[V,U]:(b=sa,sa=a)):(b=sa,sa=a);I=sa;I!==a&&(I={type:"bool",value:!1});L=I}m=L;if(m===a){var da,ta,ca,Fa,na;ta=b;d.substr(b,4).toLowerCase()===ud?(ca=d.substr(b,4),b+=4):(ca=a,0===k&&l(vd));ca!==a?(Fa=b,k++,na=v(),k--,na===a?Fa=void 0:(b=Fa,Fa=a),Fa!==a?ta=ca=[ca,Fa]:(b=ta,ta=a)):(b=ta,ta=a);da=ta;da!==a&&(da={type:"null",value:null});
m=da;if(m===a){var ia,ka,ra,la;ia=b;var ua,ga,ab,Ca;ua=b;d.substr(b,4).toLowerCase()===wd?(ga=d.substr(b,4),b+=4):(ga=a,0===k&&l(xd));ga!==a?(ab=b,k++,Ca=v(),k--,Ca===a?ab=void 0:(b=ab,ab=a),ab!==a?ua=ga="DATE":(b=ua,ua=a)):(b=ua,ua=a);ka=ua;ka!==a?(ra=n(),ra!==a?(la=t(),la!==a?ia=ka={type:"date",value:la.value}:(b=ia,ia=a)):(b=ia,ia=a)):(b=ia,ia=a);m=ia;if(m===a){var ja,qa,Da,ic;ja=b;var va,Bb,bb,Pa;va=b;d.substr(b,9).toLowerCase()===yd?(Bb=d.substr(b,9),b+=9):(Bb=a,0===k&&l(zd));Bb!==a?(bb=b,k++,
Pa=v(),k--,Pa===a?bb=void 0:(b=bb,bb=a),bb!==a?va=Bb="TIMESTAMP":(b=va,va=a)):(b=va,va=a);qa=va;qa!==a?(Da=n(),Da!==a?(ic=t(),ic!==a?ja=qa={type:"timestamp",value:ic.value}:(b=ja,ja=a)):(b=ja,ja=a)):(b=ja,ja=a);m=ja;if(m===a){var y,Ga,Cb,ea,Db,Ha,Qa,jc;y=b;Ga=zc();Ga!==a?(Cb=n(),Cb!==a?(45===d.charCodeAt(b)?(ea=gc,b++):(ea=a,0===k&&l(hc)),ea===a&&(43===d.charCodeAt(b)?(ea=ec,b++):(ea=a,0===k&&l(fc))),ea!==a?(Db=n(),Db!==a?(Ha=t(),Ha!==a?(Qa=n(),Qa!==a?(jc=Eb(),jc!==a?y=Ga={type:"interval",value:Ha,
qualifier:jc,op:ea}:(b=y,y=a)):(b=y,y=a)):(b=y,y=a)):(b=y,y=a)):(b=y,y=a)):(b=y,y=a)):(b=y,y=a);y===a&&(y=b,Ga=zc(),Ga!==a?(Cb=n(),Cb!==a?(ea=t(),ea!==a?(Db=n(),Db!==a?(Ha=Eb(),Ha!==a?y=Ga={type:"interval",value:ea,qualifier:Ha,op:""}:(b=y,y=a)):(b=y,y=a)):(b=y,y=a)):(b=y,y=a)):(b=y,y=a));m=y}}}}}}e=m;if(e===a){var D,kc,Ra,Ta,Ua,lc,Va,Wa,Xa,mc,Ya,Za;D=b;var wa,Fb,cb,$a;wa=b;d.substr(b,7).toLowerCase()===Ad?(Fb=d.substr(b,7),b+=7):(Fb=a,0===k&&l(Bd));Fb!==a?(cb=b,k++,$a=v(),k--,$a===a?cb=void 0:(b=
cb,cb=a),cb!==a?wa=Fb="EXTRACT":(b=wa,wa=a)):(b=wa,wa=a);kc=wa;if(kc!==a)if(Ra=n(),Ra!==a)if(Ta=O(),Ta!==a)if(Ua=n(),Ua!==a){var W;W=Ac();W===a&&(W=Bc(),W===a&&(W=Cc(),W===a&&(W=Dc(),W===a&&(W=Ec(),W===a&&(W=xa())))));lc=W;lc!==a?(Va=n(),Va!==a?(Wa=nc(),Wa!==a?(Xa=n(),Xa!==a?(mc=G(),mc!==a?(Ya=n(),Ya!==a?(Za=P(),Za!==a?D=kc={type:"function",name:"extract",args:{type:"expr_list",value:[{type:"string",value:lc},mc]}}:(b=D,D=a)):(b=D,D=a)):(b=D,D=a)):(b=D,D=a)):(b=D,D=a)):(b=D,D=a)):(b=D,D=a)}else b=
D,D=a;else b=D,D=a;else b=D,D=a;else b=D,D=a;e=D;if(e===a){var B,oc,mb,nb,ob,Gb,pb,qb,rb,Hb,sb,Q,Ia,pc,qc,rc;B=b;var ya,Ib,db,tb;ya=b;d.substr(b,9).toLowerCase()===Cd?(Ib=d.substr(b,9),b+=9):(Ib=a,0===k&&l(Dd));Ib!==a?(db=b,k++,tb=v(),k--,tb===a?db=void 0:(b=db,db=a),db!==a?ya=Ib="SUBSTRING":(b=ya,ya=a)):(b=ya,ya=a);oc=ya;if(oc!==a)if(mb=n(),mb!==a)if(nb=O(),nb!==a)if(ob=n(),ob!==a)if(Gb=G(),Gb!==a)if(pb=n(),pb!==a)if(qb=nc(),qb!==a)if(rb=n(),rb!==a)if(Hb=G(),Hb!==a)if(sb=n(),sb!==a){Q=b;var za,Jb,
eb,ub;za=b;d.substr(b,3).toLowerCase()===Ed?(Jb=d.substr(b,3),b+=3):(Jb=a,0===k&&l(Fd));Jb!==a?(eb=b,k++,ub=v(),k--,ub===a?eb=void 0:(b=eb,eb=a),eb!==a?za=Jb="FOR":(b=za,za=a)):(b=za,za=a);Ia=za;Ia!==a?(pc=n(),pc!==a?(qc=G(),qc!==a?(rc=n(),rc!==a?Q=Ia=[Ia,pc,qc,rc]:(b=Q,Q=a)):(b=Q,Q=a)):(b=Q,Q=a)):(b=Q,Q=a);Q===a&&(Q=null);Q!==a?(Ia=P(),Ia!==a?B=oc={type:"function",name:"substring",args:{type:"expr_list",value:Q?[Gb,Hb,Q[2]]:[Gb,Hb]}}:(b=B,B=a)):(b=B,B=a)}else b=B,B=a;else b=B,B=a;else b=B,B=a;else b=
B,B=a;else b=B,B=a;else b=B,B=a;else b=B,B=a;else b=B,B=a;else b=B,B=a;else b=B,B=a;e=B;if(e===a){var u,Ja,Kb,Lb,Mb,X,Nb,Ka,Ob,Pb,vb,sc,wb,xb;u=b;Ja=Fc();Ja!==a?(Kb=n(),Kb!==a?(Lb=O(),Lb!==a?(Mb=n(),Mb!==a?(X=Qb(),X===a&&(X=null),X!==a?(Nb=n(),Nb!==a?(Ka=G(),Ka!==a?(Ob=n(),Ob!==a?(Pb=nc(),Pb!==a?(vb=n(),vb!==a?(sc=G(),sc!==a?(wb=n(),wb!==a?(xb=P(),xb!==a?u=Ja={type:"function",name:"trim",args:{type:"expr_list",value:[{type:"string",value:null==X?"BOTH":X},Ka,sc]}}:(b=u,u=a)):(b=u,u=a)):(b=u,u=a)):
(b=u,u=a)):(b=u,u=a)):(b=u,u=a)):(b=u,u=a)):(b=u,u=a)):(b=u,u=a)):(b=u,u=a)):(b=u,u=a)):(b=u,u=a)):(b=u,u=a);u===a&&(u=b,Ja=Fc(),Ja!==a?(Kb=n(),Kb!==a?(Lb=O(),Lb!==a?(Mb=n(),Mb!==a?(X=Qb(),X===a&&(X=null),X!==a?(Nb=n(),Nb!==a?(Ka=G(),Ka!==a?(Ob=n(),Ob!==a?(Pb=P(),Pb!==a?u=Ja={type:"function",name:"trim",args:{type:"expr_list",value:[{type:"string",value:null==X?"BOTH":X},Ka]}}:(b=u,u=a)):(b=u,u=a)):(b=u,u=a)):(b=u,u=a)):(b=u,u=a)):(b=u,u=a)):(b=u,u=a)):(b=u,u=a)):(b=u,u=a));e=u;if(e===a){var E,tc,
yb,zb,Gc,uc,Hc,Ic,Jc,vc,Kc,Lc;E=b;var Aa,Rb,fb,Mc;Aa=b;d.substr(b,8).toLowerCase()===Gd?(Rb=d.substr(b,8),b+=8):(Rb=a,0===k&&l(Hd));Rb!==a?(fb=b,k++,Mc=v(),k--,Mc===a?fb=void 0:(b=fb,fb=a),fb!==a?Aa=Rb="POSITION":(b=Aa,Aa=a)):(b=Aa,Aa=a);tc=Aa;tc!==a?(yb=n(),yb!==a?(zb=O(),zb!==a?(Gc=n(),Gc!==a?(uc=G(),uc!==a?(Hc=n(),Hc!==a?(Ic=dc(),Ic!==a?(Jc=n(),Jc!==a?(vc=G(),vc!==a?(Kc=n(),Kc!==a?(Lc=P(),Lc!==a?E=tc={type:"function",name:"position",args:{type:"expr_list",value:[uc,vc]}}:(b=E,E=a)):(b=E,E=a)):
(b=E,E=a)):(b=E,E=a)):(b=E,E=a)):(b=E,E=a)):(b=E,E=a)):(b=E,E=a)):(b=E,E=a)):(b=E,E=a)):(b=E,E=a);e=E;if(e===a){var K,Sb,Nc,Oc,Pc,La,Qc,Rc;K=b;var Y,gb,hb,fa;Y=b;Y=gb=ib();if(Y===a)if(Y=b,96===d.charCodeAt(b)?(gb=Sc,b++):(gb=a,0===k&&l(Tc)),gb!==a){hb=[];Uc.test(d.charAt(b))?(fa=d.charAt(b),b++):(fa=a,0===k&&l(Vc));if(fa!==a)for(;fa!==a;)hb.push(fa),Uc.test(d.charAt(b))?(fa=d.charAt(b),b++):(fa=a,0===k&&l(Vc));else hb=a;hb!==a?(96===d.charCodeAt(b)?(fa=Sc,b++):(fa=a,0===k&&l(Tc)),fa!==a?Y=gb=hb.join(""):
(b=Y,Y=a)):(b=Y,Y=a)}else b=Y,Y=a;Sb=Y;Sb!==a?(Nc=n(),Nc!==a?(Oc=O(),Oc!==a?(Pc=n(),Pc!==a?(La=A(),La===a&&(La=null),La!==a?(Qc=n(),Qc!==a?(Rc=P(),Rc!==a?K=Sb={type:"function",name:Sb,args:La?La:{type:"expr_list",value:[]}}:(b=K,K=a)):(b=K,K=a)):(b=K,K=a)):(b=K,K=a)):(b=K,K=a)):(b=K,K=a)):(b=K,K=a);e=K;if(e===a){var Tb,w,Ma,Ub,Na,Vb,oa,Z,jb,Wc,Xc;w=b;Ma=Wb();if(Ma!==a)if(Ub=n(),Ub!==a)if(Na=G(),Na!==a)if(Vb=n(),Vb!==a){oa=[];for(Z=aa();Z!==a;)oa.push(Z),Z=aa();oa!==a?(Z=n(),Z!==a?(jb=Xb(),jb!==a?
w=Ma={type:"case_expression",format:"simple",operand:Na,clauses:oa,else:null}:(b=w,w=a)):(b=w,w=a)):(b=w,w=a)}else b=w,w=a;else b=w,w=a;else b=w,w=a;else b=w,w=a;if(w===a)if(w=b,Ma=Wb(),Ma!==a)if(Ub=n(),Ub!==a)if(Na=G(),Na!==a)if(Vb=n(),Vb!==a){oa=[];for(Z=aa();Z!==a;)oa.push(Z),Z=aa();oa!==a?(Z=n(),Z!==a?(jb=Yc(),jb!==a?(Wc=n(),Wc!==a?(Xc=Xb(),Xc!==a?w=Ma={type:"case_expression",format:"simple",operand:Na,clauses:oa,else:jb.value}:(b=w,w=a)):(b=w,w=a)):(b=w,w=a)):(b=w,w=a)):(b=w,w=a)}else b=w,w=
a;else b=w,w=a;else b=w,w=a;else b=w,w=a;Tb=w;if(Tb===a){var z,Oa,Yb,pa,ba,kb,Zc,$c;z=b;Oa=Wb();if(Oa!==a)if(Yb=n(),Yb!==a){pa=[];for(ba=Zb();ba!==a;)pa.push(ba),ba=Zb();pa!==a?(ba=n(),ba!==a?(kb=Xb(),kb!==a?z=Oa={type:"case_expression",format:"searched",clauses:pa,else:null}:(b=z,z=a)):(b=z,z=a)):(b=z,z=a)}else b=z,z=a;else b=z,z=a;if(z===a)if(z=b,Oa=Wb(),Oa!==a)if(Yb=n(),Yb!==a){pa=[];for(ba=Zb();ba!==a;)pa.push(ba),ba=Zb();pa!==a?(ba=n(),ba!==a?(kb=Yc(),kb!==a?(Zc=n(),Zc!==a?($c=Xb(),$c!==a?z=
Oa={type:"case_expression",format:"searched",clauses:pa,else:kb.value}:(b=z,z=a)):(b=z,z=a)):(b=z,z=a)):(b=z,z=a)):(b=z,z=a)}else b=z,z=a;else b=z,z=a;Tb=z}e=Tb;if(e===a){var lb,Ba,wc,$b,ac;Ba=b;wc=Ea();if(wc!==a){$b=[];for(ac=bc();ac!==a;)$b.push(ac),ac=bc();$b!==a?Ba=wc+=$b.join(""):(b=Ba,Ba=a)}else b=Ba,Ba=a;lb=Ba;lb!==a&&(lb={type:"column_ref",table:"",column:lb});e=lb;e===a&&(e=Sa(),e===a&&(e=b,c=O(),c!==a?(h=n(),h!==a?(f=G(),f!==a?(g=n(),g!==a?(r=P(),r!==a?(f.paren=!0,e=c=f):(b=e,e=a)):(b=e,
e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)))}}}}}}}return e}function ib(){var e,c,d,f;e=b;c=Ea();if(c!==a){d=[];for(f=v();f!==a;)d.push(f),f=v();d!==a?e=c+=d.join(""):(b=e,e=a)}else b=e,e=a;return e}function Ea(){var e;Id.test(d.charAt(b))?(e=d.charAt(b),b++):(e=a,0===k&&l(Jd));return e}function v(){var e;Kd.test(d.charAt(b))?(e=d.charAt(b),b++):(e=a,0===k&&l(Ld));return e}function bc(){var e;Md.test(d.charAt(b))?(e=d.charAt(b),b++):(e=a,0===k&&l(Nd));return e}function Sa(){var e,c,h;e=b;64===d.charCodeAt(b)?
(c=Od,b++):(c=a,0===k&&l(Pd));c!==a?(h=ib(),h!==a?e=c=[c,h]:(b=e,e=a)):(b=e,e=a);e!==a&&(e={type:"param",value:e[1]});return e}function Qb(){var e,c,h;e=b;d.substr(b,7).toLowerCase()===Qd?(c=d.substr(b,7),b+=7):(c=a,0===k&&l(Rd));c!==a?(c=b,k++,h=v(),k--,h===a?c=void 0:(b=c,c=a),c!==a?e="LEADING":(b=e,e=a)):(b=e,e=a);e===a&&(e=b,d.substr(b,8).toLowerCase()===Sd?(c=d.substr(b,8),b+=8):(c=a,0===k&&l(Td)),c!==a?(c=b,k++,h=v(),k--,h===a?c=void 0:(b=c,c=a),c!==a?e="TRAILING":(b=e,e=a)):(b=e,e=a),e===a&&
(e=b,d.substr(b,4).toLowerCase()===Ud?(c=d.substr(b,4),b+=4):(c=a,0===k&&l(Vd)),c!==a?(c=b,k++,h=v(),k--,h===a?c=void 0:(b=c,c=a),c!==a?e="BOTH":(b=e,e=a)):(b=e,e=a)));return e}function Eb(){var e,p,h;e=b;var g,t;p=b;h=r();h!==a?(g=n(),g!==a?(g=O(),g!==a?(g=n(),g!==a?(g=f(),g!==a?(t=n(),t!==a?(t=P(),t!==a?p=h={type:"interval-period",period:h.value,precision:g,secondary:null}:(b=p,p=a)):(b=p,p=a)):(b=p,p=a)):(b=p,p=a)):(b=p,p=a)):(b=p,p=a)):(b=p,p=a);p===a&&(p=b,h=r(),h!==a&&(h=mb(h)),p=h);if(p!==
a)if(h=n(),h!==a)if(h=b,d.substr(b,2).toLowerCase()===Wd?(g=d.substr(b,2),b+=2):(g=a,0===k&&l(Xd)),g!==a?(g=b,k++,t=v(),k--,t===a?g=void 0:(b=g,g=a),g!==a?h="TO":(b=h,h=a)):(b=h,h=a),h!==a)if(h=n(),h!==a){var m;h=b;g=r();g!==a&&(g={type:"interval-period",period:g.value,precision:null,secondary:null});h=g;h===a&&(h=b,g=xa(),g!==a?(g=n(),g!==a?(g=O(),g!==a?(g=n(),g!==a?(g=f(),g!==a?(t=n(),t!==a?(t=la(),t!==a?(t=n(),t!==a?(t=c(),t!==a?(m=n(),m!==a?(m=P(),m!==a?h=g=nb(g,t):(b=h,h=a)):(b=h,h=a)):(b=h,
h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a),h===a&&(h=b,g=xa(),g!==a?(g=n(),g!==a?(g=O(),g!==a?(g=n(),g!==a?(g=f(),g!==a?(t=n(),t!==a?(t=P(),t!==a?h=g={type:"interval-period",period:"second",precision:g,secondary:null}:(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a)):(b=h,h=a),h===a&&(h=b,g=xa(),g!==a&&(g={type:"interval-period",period:"second",precision:null,secondary:null}),h=g)));h!==a?e=p={type:"interval-qualifier",start:p,end:h}:
(b=e,e=a)}else b=e,e=a;else b=e,e=a;else b=e,e=a;else b=e,e=a;e===a&&(e=b,h=r(),h!==a?(p=n(),p!==a?(p=O(),p!==a?(p=n(),p!==a?(p=c(),p!==a?(g=n(),g!==a?(g=P(),g!==a?e=h={type:"interval-period",period:h.value,precision:p,secondary:null}:(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a),e===a&&(e=b,h=r(),h!==a&&(h=mb(h)),e=h,e===a&&(e=b,h=xa(),h!==a?(p=n(),p!==a?(p=O(),p!==a?(p=n(),p!==a?(p=f(),p!==a?(g=n(),g!==a?(g=la(),g!==a?(h=n(),h!==a?(h=c(),h!==a?(g=n(),g!==a?(g=P(),g!==
a?e=h=nb(p,h):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a),e===a&&(e=b,h=xa(),h!==a?(p=n(),p!==a?(p=O(),p!==a?(p=n(),p!==a?(p=c(),p!==a?(g=n(),g!==a?(g=P(),g!==a?e=h={type:"interval-period",period:"second",precision:p,secondary:null}:(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a),e===a&&(e=b,h=xa(),h!==a&&(h={type:"interval-period",period:"second",precision:null,secondary:null}),e=h)))));return e}
function r(){var e;e=b;e=Cc();e!==a&&(e={type:"string",value:"day"});e===a&&(e=b,e=Dc(),e!==a&&(e={type:"string",value:"hour"}),e===a&&(e=b,e=Ec(),e!==a&&(e={type:"string",value:"minute"}),e===a&&(e=b,e=Bc(),e!==a&&(e={type:"string",value:"month"}),e===a&&(e=b,e=Ac(),e!==a&&(e={type:"string",value:"year"})))));return e}function c(){var b;b=U();b!==a&&(b=parseFloat(b));return b}function f(){var b;b=U();b!==a&&(b=parseFloat(b));return b}function t(){var b;b=cc();b===a&&(b=Sa());return b}function cc(){var e,
c,h;e=b;39===d.charCodeAt(b)?(c=ob,b++):(c=a,0===k&&l(pb));c===a&&(d.substr(b,2)===qb?(c=qb,b+=2):(c=a,0===k&&l(Yd)));if(c!==a){c=[];h=b;d.substr(b,2)===Ca?(h=Ca,b+=2):(h=a,0===k&&l(rb));h!==a&&(h="'");h===a&&(sb.test(d.charAt(b))?(h=d.charAt(b),b++):(h=a,0===k&&l(tb)));for(;h!==a;)c.push(h),h=b,d.substr(b,2)===Ca?(h=Ca,b+=2):(h=a,0===k&&l(rb)),h!==a&&(h="'"),h===a&&(sb.test(d.charAt(b))?(h=d.charAt(b),b++):(h=a,0===k&&l(tb)));c!==a?(39===d.charCodeAt(b)?(h=ob,b++):(h=a,0===k&&l(pb)),h!==a?e=c={type:"string",
value:c.join("")}:(b=e,e=a)):(b=e,e=a)}else b=e,e=a;return e}function Zb(){var e,c,d;e=b;c=ub();c!==a?(c=n(),c!==a?(c=G(),c!==a?(d=n(),d!==a?(d=vb(),d!==a?(d=n(),d!==a?(d=G(),d!==a?e=c={type:"when_clause",operand:c,value:d}:(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a);return e}function aa(){var e,c,d;e=b;c=ub();c!==a?(c=n(),c!==a?(c=G(),c!==a?(d=n(),d!==a?(d=vb(),d!==a?(d=n(),d!==a?(d=G(),d!==a?e=c={type:"when_clause",operand:c,value:d}:(b=e,e=a)):(b=e,e=a)):(b=e,e=
a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a);return e}function Yc(){var e,c;e=b;var h,f;c=b;d.substr(b,4).toLowerCase()===Zd?(h=d.substr(b,4),b+=4):(h=a,0===k&&l($d));h!==a?(h=b,k++,f=v(),k--,f===a?h=void 0:(b=h,h=a),h!==a?c="ELSE":(b=c,c=a)):(b=c,c=a);c!==a?(c=n(),c!==a?(c=G(),c!==a?e={type:"else_clause",value:c}:(b=e,e=a)):(b=e,e=a)):(b=e,e=a);return e}function Ab(){var e,c,h;e=U();e===a&&(e=b,45===d.charCodeAt(b)?(c=gc,b++):(c=a,0===k&&l(hc)),c===a&&(43===d.charCodeAt(b)?(c=ec,b++):(c=a,0===
k&&l(fc))),c!==a?(h=U(),h!==a?e=c=c[0]+h:(b=e,e=a)):(b=e,e=a));return e}function xc(){var e,c;e=b;46===d.charCodeAt(b)?(c=ae,b++):(c=a,0===k&&l(be));c!==a?(c=U(),c===a&&(c=null),c!==a?e="."+(null!=c?c:""):(b=e,e=a)):(b=e,e=a);return e}function yc(){var e,c,h;c=e=b;ce.test(d.charAt(b))?(h=d.charAt(b),b++):(h=a,0===k&&l(de));h!==a?(ee.test(d.charAt(b))?(h=d.charAt(b),b++):(h=a,0===k&&l(fe)),h===a&&(h=null),h!==a?c="e"+(null===h?"":h):(b=c,c=a)):(b=c,c=a);c!==a?(h=U(),h!==a?e=c+h:(b=e,e=a)):(b=e,e=a);
return e}function U(){var b,c;b=[];c=wb();if(c!==a)for(;c!==a;)b.push(c),c=wb();else b=a;b!==a&&(b=b.join(""));return b}function wb(){var e;ge.test(d.charAt(b))?(e=d.charAt(b),b++):(e=a,0===k&&l(he));return e}function dc(){var e,c,h;e=b;d.substr(b,2).toLowerCase()===ie?(c=d.substr(b,2),b+=2):(c=a,0===k&&l(je));c!==a?(c=b,k++,h=v(),k--,h===a?c=void 0:(b=c,c=a),c!==a?e="IN":(b=e,e=a)):(b=e,e=a);return e}function Ua(){var e,c,h;e=b;d.substr(b,2).toLowerCase()===ke?(c=d.substr(b,2),b+=2):(c=a,0===k&&
l(le));c!==a?(c=b,k++,h=v(),k--,h===a?c=void 0:(b=c,c=a),c!==a?e="IS":(b=e,e=a)):(b=e,e=a);return e}function $a(){var e,c,h;e=b;d.substr(b,4).toLowerCase()===me?(c=d.substr(b,4),b+=4):(c=a,0===k&&l(ne));c!==a?(c=b,k++,h=v(),k--,h===a?c=void 0:(b=c,c=a),c!==a?e="LIKE":(b=e,e=a)):(b=e,e=a);return e}function da(){var e,c,h;e=b;d.substr(b,3).toLowerCase()===oe?(c=d.substr(b,3),b+=3):(c=a,0===k&&l(pe));c!==a?(c=b,k++,h=v(),k--,h===a?c=void 0:(b=c,c=a),c!==a?e="NOT":(b=e,e=a)):(b=e,e=a);return e}function ga(){var c,
f,h;c=b;d.substr(b,3).toLowerCase()===qe?(f=d.substr(b,3),b+=3):(f=a,0===k&&l(re));f!==a?(f=b,k++,h=v(),k--,h===a?f=void 0:(b=f,f=a),f!==a?c="AND":(b=c,c=a)):(b=c,c=a);return c}function Pa(){var c,f,h;c=b;d.substr(b,2).toLowerCase()===se?(f=d.substr(b,2),b+=2):(f=a,0===k&&l(te));f!==a?(f=b,k++,h=v(),k--,h===a?f=void 0:(b=f,f=a),f!==a?c="OR":(b=c,c=a)):(b=c,c=a);return c}function Ta(){var c,f,h;c=b;d.substr(b,7).toLowerCase()===ue?(f=d.substr(b,7),b+=7):(f=a,0===k&&l(ve));f!==a?(f=b,k++,h=v(),k--,
h===a?f=void 0:(b=f,f=a),f!==a?c="BETWEEN":(b=c,c=a)):(b=c,c=a);return c}function nc(){var c,f,h;c=b;d.substr(b,4).toLowerCase()===we?(f=d.substr(b,4),b+=4):(f=a,0===k&&l(xe));f!==a?(f=b,k++,h=v(),k--,h===a?f=void 0:(b=f,f=a),f!==a?c="FROM":(b=c,c=a)):(b=c,c=a);return c}function Fc(){var c,f,h;c=b;d.substr(b,4).toLowerCase()===ye?(f=d.substr(b,4),b+=4):(f=a,0===k&&l(ze));f!==a?(f=b,k++,h=v(),k--,h===a?f=void 0:(b=f,f=a),f!==a?c="TRIM":(b=c,c=a)):(b=c,c=a);return c}function zc(){var c,f,h;c=b;d.substr(b,
8).toLowerCase()===Ae?(f=d.substr(b,8),b+=8):(f=a,0===k&&l(Be));f!==a?(f=b,k++,h=v(),k--,h===a?f=void 0:(b=f,f=a),f!==a?c="INTERVAL":(b=c,c=a)):(b=c,c=a);return c}function Ac(){var c,f,h;c=b;d.substr(b,4).toLowerCase()===Ce?(f=d.substr(b,4),b+=4):(f=a,0===k&&l(De));f!==a?(f=b,k++,h=v(),k--,h===a?f=void 0:(b=f,f=a),f!==a?c="YEAR":(b=c,c=a)):(b=c,c=a);return c}function Bc(){var c,f,h;c=b;d.substr(b,5).toLowerCase()===Ee?(f=d.substr(b,5),b+=5):(f=a,0===k&&l(Fe));f!==a?(f=b,k++,h=v(),k--,h===a?f=void 0:
(b=f,f=a),f!==a?c="MONTH":(b=c,c=a)):(b=c,c=a);return c}function Cc(){var c,f,h;c=b;d.substr(b,3).toLowerCase()===Ge?(f=d.substr(b,3),b+=3):(f=a,0===k&&l(He));f!==a?(f=b,k++,h=v(),k--,h===a?f=void 0:(b=f,f=a),f!==a?c="DAY":(b=c,c=a)):(b=c,c=a);return c}function Dc(){var c,f,h;c=b;d.substr(b,4).toLowerCase()===Ie?(f=d.substr(b,4),b+=4):(f=a,0===k&&l(Je));f!==a?(f=b,k++,h=v(),k--,h===a?f=void 0:(b=f,f=a),f!==a?c="HOUR":(b=c,c=a)):(b=c,c=a);return c}function Ec(){var c,f,h;c=b;d.substr(b,6).toLowerCase()===
Ke?(f=d.substr(b,6),b+=6):(f=a,0===k&&l(Le));f!==a?(f=b,k++,h=v(),k--,h===a?f=void 0:(b=f,f=a),f!==a?c="MINUTE":(b=c,c=a)):(b=c,c=a);return c}function xa(){var c,f,h;c=b;d.substr(b,6).toLowerCase()===Me?(f=d.substr(b,6),b+=6):(f=a,0===k&&l(Ne));f!==a?(f=b,k++,h=v(),k--,h===a?f=void 0:(b=f,f=a),f!==a?c="SECOND":(b=c,c=a)):(b=c,c=a);return c}function Wb(){var c,f,h;c=b;d.substr(b,4).toLowerCase()===Oe?(f=d.substr(b,4),b+=4):(f=a,0===k&&l(Pe));f!==a?(f=b,k++,h=v(),k--,h===a?f=void 0:(b=f,f=a),f!==a?
c="CASE":(b=c,c=a)):(b=c,c=a);return c}function Xb(){var c,f,h;c=b;d.substr(b,3).toLowerCase()===Qe?(f=d.substr(b,3),b+=3):(f=a,0===k&&l(Re));f!==a?(f=b,k++,h=v(),k--,h===a?f=void 0:(b=f,f=a),f!==a?c="END":(b=c,c=a)):(b=c,c=a);return c}function ub(){var c,f,h;c=b;d.substr(b,4).toLowerCase()===Se?(f=d.substr(b,4),b+=4):(f=a,0===k&&l(Te));f!==a?(f=b,k++,h=v(),k--,h===a?f=void 0:(b=f,f=a),f!==a?c="WHEN":(b=c,c=a)):(b=c,c=a);return c}function vb(){var c,f,h;c=b;d.substr(b,4).toLowerCase()===Ue?(f=d.substr(b,
4),b+=4):(f=a,0===k&&l(Ve));f!==a?(f=b,k++,h=v(),k--,h===a?f=void 0:(b=f,f=a),f!==a?c="THEN":(b=c,c=a)):(b=c,c=a);return c}function la(){var c;44===d.charCodeAt(b)?(c=We,b++):(c=a,0===k&&l(Xe));return c}function O(){var c;40===d.charCodeAt(b)?(c=Ye,b++):(c=a,0===k&&l(Ze));return c}function P(){var c;41===d.charCodeAt(b)?(c=$e,b++):(c=a,0===k&&l(af));return c}function n(){var b,c;b=[];for(c=xb();c!==a;)b.push(c),c=xb();return b}function xb(){var c;bf.test(d.charAt(b))?(c=d.charAt(b),b++):(c=a,0===
k&&l(cf));return c}function Va(a,b,c,f){a={type:"binary_expr",operator:a,left:b,right:c};void 0!==f&&(a.escape=f);return a}function ma(a,b){for(var c=0;c<b.length;c++)a=Va(b[c][1],a,b[c][3]);return a}x=void 0!==x?x:{};var a={},yb={start:I},zb=I,ad="!",bd=g("!",!1),Qa="\x3d",Ra=g("\x3d",!1),Wa="\x3e\x3d",ed=g("\x3e\x3d",!1),fd="\x3e",gd=g("\x3e",!1),Xa="\x3c\x3d",hd=g("\x3c\x3d",!1),Ya="\x3c\x3e",id=g("\x3c\x3e",!1),jd="\x3c",kd=g("\x3c",!1),Za="!\x3d",ld=g("!\x3d",!1),ec="+",fc=g("+",!1),gc="-",hc=
g("-",!1),md="*",nd=g("*",!1),od="/",pd=g("/",!1),Id=/^[A-Za-z_\x80-\uFFFF]/,Jd=m([["A","Z"],["a","z"],"_",["\u0080","\uffff"]],!1,!1),Kd=/^[A-Za-z0-9_]/,Ld=m([["A","Z"],["a","z"],["0","9"],"_"],!1,!1),Md=/^[A-Za-z0-9_.\x80-\uFFFF]/,Nd=m([["A","Z"],["a","z"],["0","9"],"_",".",["\u0080","\uffff"]],!1,!1),Od="@",Pd=g("@",!1),mb=function(a){return{type:"interval-period",period:a.value,precision:null,secondary:null}},nb=function(a,b){return{type:"interval-period",period:"second",precision:a,secondary:b}},
ob="'",pb=g("'",!1),qb="N'",Yd=g("N'",!1),Ca="''",rb=g("''",!1),sb=/^[^']/,tb=m(["'"],!0,!1),ae=".",be=g(".",!1),ge=/^[0-9]/,he=m([["0","9"]],!1,!1),ce=/^[eE]/,de=m(["e","E"],!1,!1),ee=/^[+\-]/,fe=m(["+","-"],!1,!1),ud="null",vd=g("NULL",!0),qd="true",rd=g("TRUE",!0),sd="false",td=g("FALSE",!0),ie="in",je=g("IN",!0),ke="is",le=g("IS",!0),me="like",ne=g("LIKE",!0),cd="escape",dd=g("ESCAPE",!0),oe="not",pe=g("NOT",!0),qe="and",re=g("AND",!0),se="or",te=g("OR",!0),ue="between",ve=g("BETWEEN",!0),we=
"from",xe=g("FROM",!0),Ed="for",Fd=g("FOR",!0),Cd="substring",Dd=g("SUBSTRING",!0),Ad="extract",Bd=g("EXTRACT",!0),ye="trim",ze=g("TRIM",!0),Gd="position",Hd=g("POSITION",!0),yd="timestamp",zd=g("TIMESTAMP",!0),wd="date",xd=g("DATE",!0),Qd="leading",Rd=g("LEADING",!0),Sd="trailing",Td=g("TRAILING",!0),Ud="both",Vd=g("BOTH",!0),Wd="to",Xd=g("TO",!0),Ae="interval",Be=g("INTERVAL",!0),Ce="year",De=g("YEAR",!0),Ee="month",Fe=g("MONTH",!0),Ge="day",He=g("DAY",!0),Ie="hour",Je=g("HOUR",!0),Ke="minute",
Le=g("MINUTE",!0),Me="second",Ne=g("SECOND",!0),Oe="case",Pe=g("CASE",!0),Qe="end",Re=g("END",!0),Se="when",Te=g("WHEN",!0),Ue="then",Ve=g("THEN",!0),Zd="else",$d=g("ELSE",!0),We=",",Xe=g(",",!1),Ye="(",Ze=g("(",!1),$e=")",af=g(")",!1),bf=/^[ \t\n\r]/,cf=m([" ","\t","\n","\r"],!1,!1),Sc="`",Tc=g("`",!1),Uc=/^[^`]/,Vc=m(["`"],!0,!1),b=0,ra=[{line:1,column:1}],R=0,Da=[],k=0,qa;if("startRule"in x){if(!(x.startRule in yb))throw Error("Can't start parsing from rule \""+x.startRule+'".');zb=yb[x.startRule]}qa=
zb();if(qa!==a&&b===d.length)return qa;qa!==a&&b<d.length&&l({type:"end"});throw function(a,b,c){return new F(F.buildMessage(a,b),a,b,c)}(Da,R<d.length?d.charAt(R):null,R<d.length?ka(R,R+1):ka(R,R));}}})},"*noref":1}});
define("require exports ../has ../iteratorUtils ./AggregateFunctions ./StandardizedFunctions ./WhereGrammar".split(" "),function(F,d,x,g,m,q,ka){function l(d,c){d+="";return d.length>=c?d:Array(c-d.length+1).join("0")+d}function I(d,c,f,g,m,q,aa,v,x){void 0===f&&(f="0");void 0===g&&(g="0");void 0===m&&(m="0");void 0===q&&(q="0");void 0===aa&&(aa="");void 0===v&&(v="0");void 0===x&&(x="0");return"+"===aa||"-"===aa?(d=l(parseInt(d,10),4)+"-"+l(parseInt(c,10),2)+"-"+l(parseInt(f,10),2),c="",10>parseFloat(q)&&
(c="0"),g=l(parseInt(g,10),2)+":"+l(parseInt(m,10),2)+":"+(c+parseFloat(q).toString()),aa=""+aa+l(parseInt(v,10),2)+":"+l(parseInt(x,10),2),new Date(d+"T"+g+aa)):new Date(parseInt(d,10),parseInt(c,10),parseInt(f,10),parseInt(g,10),parseInt(m,10),parseFloat(q))}function A(d){var c=v.exec(d);if(null!==c){d=c[1];var f=c[2],g=c[3],r=c[4],m=c[5],l=c[6];return I(d,f,g,r,m,l)}c=bc.exec(d);if(null!==c){d=c[1];var f=c[2],g=c[3],r=c[4],m=c[5],l=c[6],q=c[7],x=c[8],c=c[9];return I(d,f,g,r,m,l,q,x,c)}c=Sa.exec(d);
if(null!==c)return d=c[1],f=c[2],g=c[3],r=c[4],m=c[5],q=c[6],x=c[7],c=c[8],I(d,f,g,r,m,"0",q,x,c);c=Qb.exec(d);if(null!==c)return d=c[1],f=c[2],g=c[3],r=c[4],m=c[5],I(d,f,g,r,m);c=Ea.exec(d);if(null!==c)return d=c[1],f=c[2],g=c[3],I(d,f,g);throw Error("SQL Invalid Timestamp");}function G(d){d=Ea.exec(d);if(null===d)throw Error("SQL Invalid Date");var c=d[2],f=d[3];return new Date(parseInt(d[1],10),parseInt(c,10)-1,parseInt(f,10))}function N(d){return Array.isArray(d)?d:[d]}function L(d){return null!==
d?!0!==d:null}function ca(d,c){return null!=d&&null!=c?!0===d&&!0===c:!1===d||!1===c?!1:null}function na(d,c){return null!=d&&null!=c?!0===d||!0===c:!0===d||!0===c?!0:null}function S(d,c){if(null==d)return null;for(var f=!1,g=0;g<c.length;g++){var m=c[g];if(null==m)f=null;else if(d===m){f=!0;break}}return f}function M(d,c,f){if(null==d)return null;for(var g="",m=0,r=0;r<c.length;r++){var l=c.charAt(r);switch(m){case 0:l===f?m=1:g=0<="-[]/{}()*+?.\\^$|".indexOf(l)?g+("\\"+l):"%"===l?g+".*":"_"===l?
g+".":g+l;break;case 1:g=0<="-[]/{}()*+?.\\^$|".indexOf(l)?g+("\\"+l):g+l,m=0}}return(new RegExp("^"+g+"$")).test(d)}function H(d){return d instanceof Date?d.valueOf():d}function T(d,c,f){if(null==c||null==f)return null;c=H(c);f=H(f);switch(d){case "\x3c\x3e":return c!==f;case "\x3d":return c===f;case "\x3e":return c>f;case "\x3c":return c<f;case "\x3e\x3d":return c>=f;case "\x3c\x3d":return c<=f}}function V(d){for(var c=[],f={},g=0;g<d.length;g++){var m=d[g],l=m.toLowerCase();void 0===f[l]&&(c.push(m),
f[l]=1)}return c}function ha(d,c,f){if(c instanceof q.SqlInterval)if(f instanceof Date)switch(d){case "+":return new Date(c.valueInMilliseconds()+f.getTime());case "-":return c.valueInMilliseconds()-f.getTime();case "*":return c.valueInMilliseconds()*f.getTime();case "/":return c.valueInMilliseconds()/f.getTime()}else if(f instanceof q.SqlInterval)switch(d){case "+":return q.SqlInterval.createFromMilliseconds(c.valueInMilliseconds()+f.valueInMilliseconds());case "-":return q.SqlInterval.createFromMilliseconds(c.valueInMilliseconds()-
f.valueInMilliseconds());case "*":return c.valueInMilliseconds()*f.valueInMilliseconds();case "/":return c.valueInMilliseconds()/f.valueInMilliseconds()}else c=c.valueInMilliseconds();else if(f instanceof q.SqlInterval)if(c instanceof Date)switch(d){case "+":return new Date(f.valueInMilliseconds()+c.getTime());case "-":return new Date(c.getTime()-f.valueInMilliseconds());case "*":return c.getTime()*f.valueInMilliseconds();case "/":return c.getTime()/f.valueInMilliseconds()}else f=f.valueInMilliseconds();
else if(c instanceof Date&&"number"===typeof f)switch(f*=864E5,c=c.getTime(),d){case "+":return new Date(c+f);case "-":return new Date(c-f);case "*":return new Date(c*f);case "/":return new Date(c/f)}else if(f instanceof Date&&"number"===typeof c)switch(c*=864E5,f=f.getTime(),d){case "+":return new Date(c+f);case "-":return new Date(c-f);case "*":return new Date(c*f);case "/":return new Date(c/f)}switch(d){case "+":return c+f;case "-":return c-f;case "*":return c*f;case "/":return c/f}}function ib(d,
c,f,g){d=g.getAttribute(d,c);return null!=d&&1===f[c]?new Date(d):d}Object.defineProperty(d,"__esModule",{value:!0});var Ea=/^(\d{4})-(\d{1,2})-(\d{1,2})$/,v=/^(\d{4})-(\d{1,2})-(\d{1,2}) (\d{1,2}):(\d{1,2}):(\d{1,2}(\.[0-9]+)?)$/,bc=/^(\d{4})-(\d{1,2})-(\d{1,2}) (\d{1,2}):(\d{1,2}):(\d{1,2}(\.[0-9]+)?)(\+|\-)(\d{1,2}):(\d{1,2})$/,Sa=/^(\d{4})-(\d{1,2})-(\d{1,2}) (\d{1,2}):(\d{1,2})(\+|\-)(\d{1,2}):(\d{1,2})$/,Qb=/^(\d{4})-(\d{1,2})-(\d{1,2}) (\d{1,2}):(\d{1,2})$/,Eb=function(){function d(){}d.makeBool=
function(c){return!0===c};d.featureValue=function(c,d,g,m){return ib(c,d,g,m)};d.equalsNull=function(c){return null===c};d.applyLike=function(c,d,g){return M(c,d,g)};d.ensureArray=function(c){return N(c)};d.applyIn=function(c,d){return S(c,d)};d.currentDate=function(){var c=new Date;c.setHours(0,0,0,0);return c};d.makeSqlInterval=function(c,d,g){return q.SqlInterval.createFromValueAndQualifer(c,d,g)};d.convertInterval=function(c){return c instanceof q.SqlInterval?c.valueInMilliseconds():c};d.currentTimestamp=
function(){return new Date};d.compare=function(c,d,g){return T(c,d,g)};d.calculate=function(c,d,g){return ha(c,d,g)};d.makeComparable=function(c){return H(c)};d.evaluateFunction=function(c,d){return q.evaluateFunction(c,d)};d.lookup=function(c,d){c=d[c];return void 0===c?null:c};d.between=function(c,d){return null==c||null==d[0]||null==d[1]?null:c>=d[0]&&c<=d[1]};d.notbetween=function(c,d){return null==c||null==d[0]||null==d[1]?null:c<d[0]||c>d[1]};d.ternaryNot=function(c){return L(c)};d.ternaryAnd=
function(c,d){return ca(c,d)};d.ternaryOr=function(c,d){return na(c,d)};return d}();F=function(){function l(c,d){this.fieldsIndex=d;this.datefields={};this.parameters={};this.parseTree=ka.WhereGrammar.parse(c);c=this.extractExpressionInfo(d);d=c.isStandardized;var f=c.isAggregate;this.referencedFieldNames=c.referencedFieldNames;this.isStandardized=d;this.isAggregate=f}l.create=function(c,d){return new l(c,d)};Object.defineProperty(l.prototype,"fieldNames",{get:function(){return this.referencedFieldNames},
enumerable:!0,configurable:!0});l.prototype.testSet=function(c,f){void 0===f&&(f=d.defaultAttributeAdapter);for(var g={},m=function(d){g[d]=c.map(function(c){return f.getAttribute(c,d)})},l=0,q=this.fieldNames;l<q.length;l++)m(q[l]);return!!this.evaluateNode(this.parseTree,{attributes:g},d.defaultAttributeAdapter)};l.prototype.calculateValue=function(c,f){void 0===f&&(f=d.defaultAttributeAdapter);c=this.evaluateNode(this.parseTree,c,f);return c instanceof q.SqlInterval?c.valueInMilliseconds()/864E5:
c};l.prototype.calculateValueCompiled=function(c,f){void 0===f&&(f=d.defaultAttributeAdapter);if(null!=this.parseTree._compiledVersion)return this.parseTree._compiledVersion(c,this.parameters,f,this.datefields);if(x("csp-restrictions"))return this.calculateValue(c,f);this.compileMe();return this.parseTree._compiledVersion(c,this.parameters,f,this.datefields)};l.prototype.testFeature=function(c,f){void 0===f&&(f=d.defaultAttributeAdapter);return!!this.evaluateNode(this.parseTree,c,f)};l.prototype.testFeatureCompiled=
function(c,f){void 0===f&&(f=d.defaultAttributeAdapter);if(void 0===this.parseTree._compiledVersion)return!!this.parseTree._compiledVersion(c,this.parameters,f,this.datefields);if(x("csp-restrictions"))return this.testFeature(c,f);this.compileMe();return!!this.parseTree._compiledVersion(c,this.parameters,f,this.datefields)};l.prototype.getFunctions=function(){var c=[];this.visitAll(this.parseTree,function(d){"function"===d.type&&c.push(d.name.toLowerCase())});return V(c)};l.prototype.getExpressions=
function(){var c=new Map;this.visitAll(this.parseTree,function(d){if("function"===d.type){var f=d.name.toLowerCase();d=d.args.value[0];if("column_ref"===d.type){d=d.column;var g=f+"-"+d;c.has(g)||c.set(g,{aggregateType:f,field:d})}}});return g.valuesOfMap(c)};l.prototype.getVariables=function(){var c=[];this.visitAll(this.parseTree,function(d){"param"===d.type&&c.push(d.value.toLowerCase())});return V(c)};l.prototype.compileMe=function(){var c="return this.convertInterval("+this.evaluateNodeToJavaScript(this.parseTree)+
")";this.parseTree._compiledVersion=(new Function("feature","lookups","attributeAdapter","datefields",c)).bind(Eb)};l.prototype.extractExpressionInfo=function(c){var d=this,g=[],l=!0,r=!0;this.visitAll(this.parseTree,function(f){switch(f.type){case "column_ref":var t=f.column.toUpperCase();if("CURRENT_DATE"!==t&&"CURRENT_TIMESTAMP"!==t){var v=(t=c.get(f.column))&&t.name;!t||"date"!==t.type&&"esriFieldTypeDate"!==t.type||(d.datefields[t.name]=1);void 0!==v?(g.push(v),f.column=v):g.push(f.column)}break;
case "function":t=f.name,f=f.args.value.length,l&&(l=q.isStandardized(t,f)),r&&(r=m.isAggregate(t,f))}});return{referencedFieldNames:V(g),isStandardized:l,isAggregate:r}};l.prototype.visitAll=function(c,d){if(null!=c)switch(d(c),c.type){case "when_clause":this.visitAll(c.operand,d);this.visitAll(c.value,d);break;case "case_expression":for(var f=0,g=c.clauses;f<g.length;f++){var l=g[f];this.visitAll(l,d)}"simple"===c.format&&this.visitAll(c.operand,d);null!==c.else&&this.visitAll(c.else,d);break;case "expr_list":f=
0;for(c=c.value;f<c.length;f++)l=c[f],this.visitAll(l,d);break;case "unary_expr":this.visitAll(c.expr,d);break;case "binary_expr":this.visitAll(c.left,d);this.visitAll(c.right,d);break;case "function":this.visitAll(c.args,d)}};l.prototype.evaluateNodeToJavaScript=function(c){switch(c.type){case "interval":return"this.makeSqlInterval("+this.evaluateNodeToJavaScript(c.value)+", "+JSON.stringify(c.qualifier)+","+JSON.stringify(c.op)+")";case "case_expression":var d="";if("simple"===c.format)for(var g=
"this.makeComparable("+this.evaluateNodeToJavaScript(c.operand)+")",d="( ",l=0;l<c.clauses.length;l++)d+=" ("+g+" \x3d\x3d\x3d this.makeComparable("+this.evaluateNodeToJavaScript(c.clauses[l].operand)+")) ? ("+this.evaluateNodeToJavaScript(c.clauses[l].value)+") : ";else for(d="( ",l=0;l<c.clauses.length;l++)d+=" this.makeBool("+this.evaluateNodeToJavaScript(c.clauses[l].operand)+")\x3d\x3d\x3dtrue ? ("+this.evaluateNodeToJavaScript(c.clauses[l].value)+") : ";d=null!==c.else?d+this.evaluateNodeToJavaScript(c.else):
d+"null";return d+" )";case "param":return"this.lookup("+JSON.stringify(c.value.toLowerCase())+",lookups)";case "expr_list":d="[";g=0;for(c=c.value;g<c.length;g++)l=c[g],"["!==d&&(d+=","),d+=this.evaluateNodeToJavaScript(l);return d+"]";case "unary_expr":return"this.ternaryNot("+this.evaluateNodeToJavaScript(c.expr)+")";case "binary_expr":switch(c.operator){case "AND":return"this.ternaryAnd("+this.evaluateNodeToJavaScript(c.left)+","+this.evaluateNodeToJavaScript(c.right)+" )";case "OR":return"this.ternaryOr("+
this.evaluateNodeToJavaScript(c.left)+","+this.evaluateNodeToJavaScript(c.right)+" )";case "IS":if("null"!==c.right.type)throw Error("Unsupported RHS for IS");return"this.equalsNull("+this.evaluateNodeToJavaScript(c.left)+")";case "ISNOT":if("null"!==c.right.type)throw Error("Unsupported RHS for IS");return"(!(this.equalsNull("+this.evaluateNodeToJavaScript(c.left)+")))";case "IN":return"this.applyIn("+this.evaluateNodeToJavaScript(c.left)+",this.ensureArray("+this.evaluateNodeToJavaScript(c.right)+
"))";case "NOT IN":return"this.ternaryNot(this.applyIn("+this.evaluateNodeToJavaScript(c.left)+",this.ensureArray("+this.evaluateNodeToJavaScript(c.right)+")))";case "BETWEEN":return"this.between("+this.evaluateNodeToJavaScript(c.left)+","+this.evaluateNodeToJavaScript(c.right)+")";case "NOTBETWEEN":return"this.notbetween("+this.evaluateNodeToJavaScript(c.left)+","+this.evaluateNodeToJavaScript(c.right)+")";case "LIKE":return"this.applyLike("+this.evaluateNodeToJavaScript(c.left)+","+this.evaluateNodeToJavaScript(c.right)+
","+JSON.stringify(c.escape)+")";case "NOT LIKE":return"this.ternaryNot(this.applyLike("+this.evaluateNodeToJavaScript(c.left)+","+this.evaluateNodeToJavaScript(c.right)+","+JSON.stringify(c.escape)+"))";case "\x3c\x3e":case "\x3c":case "\x3e":case "\x3e\x3d":case "\x3c\x3d":case "\x3d":return"this.compare("+JSON.stringify(c.operator)+","+this.evaluateNodeToJavaScript(c.left)+","+this.evaluateNodeToJavaScript(c.right)+")";case "*":case "-":case "+":case "/":return"this.calculate("+JSON.stringify(c.operator)+
","+this.evaluateNodeToJavaScript(c.left)+","+this.evaluateNodeToJavaScript(c.right)+")"}throw Error("Not Supported Operator "+c.operator);case "null":case "bool":case "string":case "number":return JSON.stringify(c.value);case "date":return"(new Date("+G(c.value).getTime().toString()+"))";case "timestamp":return"(new Date("+A(c.value).getTime().toString()+"))";case "column_ref":return"CURRENT_DATE"===c.column.toUpperCase()?"this.currentDate()":"CURRENT_TIMESTAMP"===c.column.toUpperCase()?"this.currentTimestamp()":
"this.featureValue(feature,"+JSON.stringify(c.column)+",datefields,attributeAdapter)";case "function":return"this.evaluateFunction("+JSON.stringify(c.name)+","+this.evaluateNodeToJavaScript(c.args)+")"}throw Error("Unsupported sql syntax "+c.type);};l.prototype.evaluateNode=function(c,d,g){switch(c.type){case "interval":return d=this.evaluateNode(c.value,d,g),q.SqlInterval.createFromValueAndQualifer(d,c.qualifier,c.op);case "case_expression":if("simple"===c.format)for(var f=H(this.evaluateNode(c.operand,
d,g)),l=0;l<c.clauses.length;l++){if(f===H(this.evaluateNode(c.clauses[l].operand,d,g)))return this.evaluateNode(c.clauses[l].value,d,g)}else for(l=0;l<c.clauses.length;l++)if(!0===this.evaluateNode(c.clauses[l].operand,d,g))return this.evaluateNode(c.clauses[l].value,d,g);return null!==c.else?this.evaluateNode(c.else,d,g):null;case "param":return this.parameters[c.value.toLowerCase()];case "expr_list":f=[];l=0;for(c=c.value;l<c.length;l++){var r=c[l];f.push(this.evaluateNode(r,d,g))}return f;case "unary_expr":return L(this.evaluateNode(c.expr,
d,g));case "binary_expr":switch(c.operator){case "AND":return ca(this.evaluateNode(c.left,d,g),this.evaluateNode(c.right,d,g));case "OR":return na(this.evaluateNode(c.left,d,g),this.evaluateNode(c.right,d,g));case "IS":if("null"!==c.right.type)throw Error("Unsupported RHS for IS");return null===this.evaluateNode(c.left,d,g);case "ISNOT":if("null"!==c.right.type)throw Error("Unsupported RHS for IS");return null!==this.evaluateNode(c.left,d,g);case "IN":return f=N(this.evaluateNode(c.right,d,g)),S(this.evaluateNode(c.left,
d,g),f);case "NOT IN":return f=N(this.evaluateNode(c.right,d,g)),L(S(this.evaluateNode(c.left,d,g),f));case "BETWEEN":return f=this.evaluateNode(c.left,d,g),c=this.evaluateNode(c.right,d,g),null==f||null==c[0]||null==c[1]?null:f>=H(c[0])&&f<=H(c[1]);case "NOTBETWEEN":return f=this.evaluateNode(c.left,d,g),c=this.evaluateNode(c.right,d,g),null==f||null==c[0]||null==c[1]?null:f<H(c[0])||f>H(c[1]);case "LIKE":return M(this.evaluateNode(c.left,d,g),this.evaluateNode(c.right,d,g),c.escape);case "NOT LIKE":return L(M(this.evaluateNode(c.left,
d,g),this.evaluateNode(c.right,d,g),c.escape));case "\x3c\x3e":case "\x3c":case "\x3e":case "\x3e\x3d":case "\x3c\x3d":case "\x3d":return T(c.operator,this.evaluateNode(c.left,d,g),this.evaluateNode(c.right,d,g));case "-":case "+":case "*":case "/":return ha(c.operator,this.evaluateNode(c.left,d,g),this.evaluateNode(c.right,d,g))}throw Error("Not Supported Operator "+c.operator);case "null":case "bool":case "string":case "number":return c.value;case "date":return G(c.value);case "timestamp":return A(c.value);
case "column_ref":return"CURRENT_DATE"===c.column.toUpperCase()?(r=new Date,r.setHours(0,0,0,0),r):"CURRENT_TIMESTAMP"===c.column.toUpperCase()?new Date:ib(d,c.column,this.datefields,g);case "function":return d=this.evaluateNode(c.args,d,g),this.isAggregate?m.aggregateFunction(c.name,d):q.evaluateFunction(c.name,d)}throw Error("Unsupported sql syntax "+c.type);};return l}();d.WhereClause=F;d.defaultAttributeAdapter={getAttribute:function(d,c){return(d&&"object"===typeof d.attributes?d.attributes:
d)[c]}}});