// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/mathUtils ../../../../core/maybe ../../webgl-engine/core/shaderLibrary/DiscardOrAdjustAlpha.glsl ../../webgl-engine/materials/internal/MaterialUtil".split(" "),function(r,f,k,m,l,n){Object.defineProperty(f,"__esModule",{value:!0});f.getMaterialAndTextures=function(b,a){var d=new Map,e=function(a,b){if(m.isNone(a))return-1;if(d.has(a.id))return a=d.get(a.id),a.usage|=b,a.id;var c=d.size;d.set(a.id,{id:c,usage:b});return c},c=a.pbrMetallicRoughness,g=c&&c.baseColorFactor,
h=a.emissiveFactor,f=null==a.normalTexture&&null==a.emissiveTexture&&null==a.occlusionTexture&&(c?null==c.metallicRoughnessTexture&&1===c.roughnessFactor&&(1===c.metallicFactor||0===c.metallicFactor):!0),k=f?n.defaultPBRMaterialParameters.metallicFactor:c?c.metallicFactor:1,l=f?n.defaultPBRMaterialParameters.roughnessFactor:c?c.roughnessFactor:1,c={baseColorFactor:g?[g[0],g[1],g[2],g[3]]:[1,1,1,1],baseColorTextureId:e(c&&c.baseColorTexture,1),metallicRoughnessTextureId:e(c&&c.metallicRoughnessTexture,
2),metallicFactor:k,roughnessFactor:l};a={alphaMode:a.alphaMode,alphaCutoff:a.alphaCutoff,doubleSided:a.doubleSided,cullFace:"none"===a.cullFace?0:"back"===a.cullFace?2:"front"===a.cullFace?1:void 0,normalTextureId:e(a.normalTexture,4),emissiveTextureId:e(a.emissiveTexture,16),occlusionTextureId:e(a.occlusionTexture,8),emissiveFactor:h?[h[0],h[1],h[2]]:[0,0,0],metallicRoughness:c,wrapTextures:!1,isSchematic:f};var p=[];d.forEach(function(a,c){a=a.usage;var d=m.isSome(b)&&b[c]&&b[c].formats,d=d?d.map(function(a){return{name:a.name,
encoding:q[a.format]}}):[];p.push({id:c,usage:a,encodings:d})});return{material:a,textures:p}};var q={jpg:"image/jpeg",png:"image/png",dds:"image/vnd-ms.dds","ktx-etc2":"image/ktx"};f.getMaterialAndTexturesFromShared=function(b){var a=b&&b.materialDefinitions?Object.keys(b.materialDefinitions)[0]:null,d=b&&b.textureDefinitions?Object.keys(b.textureDefinitions)[0]:null,a=a&&b.materialDefinitions[a],d=d&&b.textureDefinitions[d];b={alphaMode:"opaque",alphaCutoff:l.TEXTURE_ALPHA_CUTOFF_DEFAULT,doubleSided:!0,
cullFace:0,normalTextureId:-1,emissiveTextureId:-1,occlusionTextureId:-1,emissiveFactor:[0,0,0],metallicRoughness:{baseColorFactor:[.8,.8,.8,1],baseColorTextureId:-1,metallicRoughnessTextureId:-1,metallicFactor:0,roughnessFactor:.6},wrapTextures:!1,isSchematic:!0};if(null!=a){a=a.params;a.diffuse&&(b.metallicRoughness.baseColorFactor=[a.diffuse[0],a.diffuse[1],a.diffuse[2],1]);null!=a.doubleSided&&(b.doubleSided=a.doubleSided,b.cullFace=a.doubleSided?0:2);if("none"===a.cullFace||"front"===a.cullFace||
"back"===a.cullFace)b.cullFace="none"===a.cullFace?0:"back"===a.cullFace?2:1;a.transparency&&(b.metallicRoughness.baseColorFactor[3]=k.clamp(1-a.transparency,0,1));if(a.useVertexColorAlpha||1>b.metallicRoughness.baseColorFactor[3])b.alphaMode="blend"}a=[];if(null!=d){!d.wrap||"repeat"!==d.wrap[0]&&"repeat"!==d.wrap[1]||(b.wrapTextures=!0);"rgba"===d.channels&&(b.alphaMode="blend");var e=d.images[d.images.length-1],c=function(a){return a&&a.split("/").pop()},d=Array.isArray(d.encoding)?d.encoding.map(function(a,
b){return{name:c(e.href[b]),encoding:a}}):[{name:c(e.href),encoding:d.encoding}];a.push({id:0,usage:1,encodings:d});b.metallicRoughness.baseColorTextureId=0}return{material:b,textures:a}}});