// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../request ../../../../core/arrayUtils ../../../../core/Error ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/typedArrayUtil ../../../../core/libs/gl-matrix-2/mat4f64 ../../../../core/libs/gl-matrix-2/quat ../../../../core/libs/gl-matrix-2/quatf32 ../../../../core/libs/gl-matrix-2/vec3 ../../../../core/libs/gl-matrix-2/vec3f64 ../../../../core/libs/gl-matrix-2/vec4f64 ../../../../geometry/SpatialReference ../../../../geometry/support/aaBoundingBox ../../../../geometry/support/webMercatorUtils ../../../../tasks/QueryTask ../../../../tasks/support/Query ./I3SBinaryReader ../../support/projectionUtils".split(" "),
function(fa,e,M,N,n,w,u,B,O,z,P,m,Q,R,C,S,T,U,V,W,q){function A(a){return a&&parseInt(a.substring(a.lastIndexOf("/")+1,a.length),10)}function D(a,b){var c=b[0],f=b[1],d=b[2];b=b[3];var k=a[0]-c,c=c-a[3],e=a[1]-f,f=f-a[4],l=a[2]-d;a=d-a[5];var d=Math.max(k,c,0),x=Math.max(e,f,0),v=Math.max(l,a,0),d=d*d+x*x+v*v;return d>b*b?0:0<d?1:-Math.max(k,c,e,f,l,a)>b?3:2}function F(a,b,c){var f=[],d=c&&c.missingFields;c=c&&c.originalFields;for(var k=0;k<a.length;k++){for(var e=a[k],l=e.toLowerCase(),x=!1,v=0,
g=b;v<g.length;v++){var h=g[v];if(l===h.name.toLowerCase()){f.push(h.name);x=!0;c&&c.push(e);break}}!x&&d&&d.push(e)}return f}function X(a,b){return a.filter(function(a){return a!==b}).concat([b])}function Y(a,b,c,f){b.sort(function(a,b){return a.attributes[c]-b.attributes[c]});var d=b.map(function(a){return a.attributes[c]}),k=[],e=F(f,a.fields,{originalFields:k});return G(a,d,e).then(function(a){for(var c=0;c<b.length;c++){var d=b[c],f=a[c],l={};if(d.attributes)for(var E in d.attributes)l[E]=d.attributes[E];
for(var g=0;g<k.length;g++)l[k[g]]=f[e[g]];d.attributes=l}return b})}function G(a,b,c){var f=a.capabilities.query.maxRecordCount;if(null!=f&&b.length>f)return f=Z(b,f),u.all(f.map(function(b){return G(a,b,c)})).then(aa);f=new V({objectIds:b,outFields:c,orderByFields:[a.objectIdField]});return(new U(a.parsedUrl.path)).execute(f).then(function(a){if(a&&a.features&&a.features.length===b.length)return a.features.map(function(a){return a.attributes});throw new n("scenelayer:feature-not-in-associated-layer",
"Feature not found in associated feature layer");})}function ba(a,b,c,f,d){for(var e=[],g=0;g<b.length;g++){var l=b[g];l&&-1!==d.indexOf(l.name)&&e.push({url:a+"/nodes/"+c.resources.attributes+"/attributes/"+l.key+"/0",storageInfo:l})}return u.eachAlways(e.map(function(a){return M(a.url,{responseType:"array-buffer"}).then(function(b){return W.readBinaryAttribute(a.storageInfo,b.data)})})).then(function(a){for(var b=[],c=0;c<f.length;c++){for(var d=f[c],k={},g=0;g<a.length;g++)null!=a[g].value&&(k[e[g].storageInfo.name]=
H(a[g].value,d));b.push(k)}return b})}function H(a,b){if(!a)return null;b=a[b];return B.isInt16Array(a)?b===ca?null:b:B.isInt32Array(a)?b===da?null:b:b!==b?null:b}function Z(a,b){var c=a.length;b=Math.ceil(c/b);for(var f=[],d=0;d<b;d++)f.push(a.slice(Math.floor(c*d/b),Math.floor(c*(d+1)/b)));return f}function aa(a){for(var b=[],c=0;c<a.length;c++)b=b.concat(a[c]);return b}function I(a){var b=new C(A(a.store.indexCRS||a.store.geographicCRS));return b.equals(a.spatialReference)?a.spatialReference:b}
function J(a){var b=new C(A(a.store.vertexCRS||a.store.projectedCRS));return b.equals(a.spatialReference)?a.spatialReference:b}function y(a,b,c){if(!T.canProject(a,b))throw new n("layerview:spatial-reference-incompatible","The spatial reference of this scene layer is incompatible with the spatial reference of the view",{});if("local"===c&&a.isGeographic)throw new n("layerview:local-gcs-not-supported","Geographic coordinate systems are not supported in local scenes",{});}function K(a,b,c){var f=I(a);
a=J(a);y(f,b,c);y(a,b,c)}Object.defineProperty(e,"__esModule",{value:!0});e.DDS_ENCODING_STRING="image/vnd-ms.dds";e.BROWSER_SUPPORTED_IMAGE_ENCODING_STRINGS=["image/jpeg","image/png"];e.extractWkid=A;e.selectEncoding=function(a,b){if(b)for(b=0;b<a.length;b++)if(a[b].encoding===e.DDS_ENCODING_STRING)return a[b];for(b=0;b<a.length;b++)if(-1<e.BROWSER_SUPPORTED_IMAGE_ENCODING_STRINGS.indexOf(a[b].encoding))return a[b];return null};e.findIntersectingNodes=function(a,b,c,f,d,e){d.traverse(c,function(c){var d=
c.mbs;b!==f&&(d=ea,q.mbsToMbs(c.mbs,f,d,b));d=D(a,d);if(0!==d)return e(c,d),!0})};e.filterInPlace=function(a,b,c){for(var f=0,d=0,e=0;e<b.length&&f<a.length;e++)a[f]===b[e]&&(c(e)&&(a[d]=a[f],d++),f++);a.length=d};var r=S.create();e.getClipAABB=function(a,b){if(0===b.rotationScale[1]&&0===b.rotationScale[2]&&0===b.rotationScale[3]&&0===b.rotationScale[5]&&0===b.rotationScale[6]&&0===b.rotationScale[7])return r[0]=(a[0]-b.position[0])/b.rotationScale[0],r[1]=(a[1]-b.position[1])/b.rotationScale[4],
r[2]=(a[2]-b.position[2])/b.rotationScale[8],r[3]=(a[3]-b.position[0])/b.rotationScale[0],r[4]=(a[4]-b.position[1])/b.rotationScale[4],r[5]=(a[5]-b.position[2])/b.rotationScale[8],r};var ea=R.vec4f64.create();e.intersectBoundingBoxWithMbs=D;e.findFieldsCaseInsensitive=F;e.whenGraphicAttributes=function(a,b,c,f,d,e){!0===(e&&e.populateObjectId)&&(f=X(f,c));if(0===b.length)return u.resolve(b);e=a.associatedLayer;var g=a.attributeStorageInfo;if(e)return Y(e,b,c,f);if(g){b=d(b);if(!b)return u.reject(new n("scenelayer:features-not-loaded",
"Tried to query attributes for unloaded features"));var k=a.parsedUrl.path;return u.all(b.map(function(a){return ba(k,g,a.node,a.indices,f).then(function(b){for(var c=0;c<a.graphics.length;c++){var d=a.graphics[c],f=b[c];if(d.attributes)for(var e in d.attributes)e in f||(f[e]=d.attributes[e]);d.attributes=f}return a.graphics})})).then(N.flatten)}return u.reject(new n("scenelayer:no-attribute-source","This scene layer does not have a source for attributes available"))};var ca=-Math.pow(2,15),da=-Math.pow(2,
31);e.getCachedAttributeValue=H;e.convertFlatRangesToOffsets=function(a,b,c){b=null!=b?b:a.length/c;for(var f=new Uint32Array(b+1),d=0;d<b;d++){var e=a[d*c];f[d]=3*e;var g=(d-1)*c+1;if(0<=g&&e-1!==a[g])throw new n("Face ranges are not continuous");}f[f.length-1]=3*(a[(b-1)*c+1]+1);return f};e.getIndexCrs=I;e.getVertexCrs=J;e.getCacheKeySuffix=function(a,b){return b===q.SphericalECEFSpatialReference?"@ECEF":a.equals(b)?"":null!=b.wkid?"@"+b.wkid:null};e.checkSpatialReference=y;e.checkSpatialReferences=
K;e.checkSceneLayerValid=function(a){var b;(b=null==a.store||null==a.store.defaultGeometrySchema)||(a=a.store.defaultGeometrySchema,b=!!(null!=a.geometryType&&"triangles"!==a.geometryType||null!=a.topology&&"PerAttributeArray"!==a.topology||null==a.vertexAttributes||null==a.vertexAttributes.position));if(b)throw new n("scenelayer:unsupported-geometry-schema","The geometry schema of this scene layer is not supported.",{});};e.checkSceneLayerCompatibleWithView=function(a,b){K(a,b.spatialReference,b.viewingMode)};
e.checkPointCloudLayerValid=function(a){var b;(b=null==a.store||null==a.store.defaultGeometrySchema)||(a=a.store.defaultGeometrySchema,b=!!(null==a.geometryType||"points"!==a.geometryType||null!=a.topology&&"PerAttributeArray"!==a.topology||null!=a.encoding&&""!==a.encoding&&"lepcc-xyz"!==a.encoding||null==a.vertexAttributes||null==a.vertexAttributes.position));if(b)throw new n("pointcloud:unsupported-geometry-schema","The geometry schema of this point cloud scene layer is not supported.",{});};e.checkPointCloudLayerCompatibleWithView=
function(a,b){y(a.spatialReference,b.spatialReference,b.viewingMode)};e.rendererNeedsTextures=function(a){if(null==a||"simple"!==a.type&&"class-breaks"!==a.type&&"unique-value"!==a.type||("unique-value"===a.type||"class-breaks"===a.type)&&null==a.defaultSymbol)return!0;a=a.getSymbols();if(0===a.length)return!0;for(var b=0;b<a.length;b++){var c=a[b];if("mesh-3d"!==c.type||0===c.symbolLayers.length)return!0;for(var f=0,c=c.symbolLayers.items;f<c.length;f++){var d=c[f];if("fill"!==d.type||w.isNone(d.material)||
w.isNone(d.material.color)||"replace"!==d.material.colorMixMode)return!0}}return!1};var L=function(){return function(){this.material=this.edges=null;this.castShadows=!0}}();e.SymbolInfo=L;e.getSymbolInfo=function(a){var b=new L,c=!1,f=!1,d=0;for(a=a.symbolLayers.items;d<a.length;d++){var e=a[d];if("fill"===e.type&&e.enabled){var g=e.material,h=e.edges;w.isSome(g)&&!c&&(c=g.color,g=g.colorMixMode,w.isSome(c)?b.material={color:[c.r/255,c.g/255,c.b/255],alpha:c.a,colorMixMode:g}:b.material={color:[1,
1,1],alpha:1,colorMixMode:"multiply"},b.castShadows=e.castShadows,c=!0);w.isSome(h)&&!f&&(b.edges=h,f=!0)}}b.material||(b.material={color:[1,1,1],alpha:1,colorMixMode:"multiply"});return b};e.addWraparound=function(a,b){return(a|0)+(b|0)|0};e.transformObb=function(a,b,c,e,d){void 0===d&&(d=0);m.vec3.set(c.center,a.center[0],a.center[1],a.center[2]+d);if(b===q.SphericalECEFSpatialReference||e!==q.SphericalECEFSpatialReference||b.isGeographic)q.bufferToBuffer(c.center,b,0,c.center,e,0,1),z.quat.copy(c.quaternion,
a.quaternion),m.vec3.copy(c.halfSize,a.halfSize);else{for(d=0;8>d;d++)m.vec3.set(g,a.halfSize[0]*(1===(d&1)?-1:1),a.halfSize[1]*(2===(d&2)?-1:1),a.halfSize[2]*(4===(d&4)?-1:1)),m.vec3.transformQuat(g,g,a.quaternion),m.vec3.add(g,g,c.center),p[3*d+0]=g[0],p[3*d+1]=g[1],p[3*d+2]=g[2];q.computeLinearTransformation(b,c.center,h,e);d=2*Math.sqrt(1+h[0]+h[5]+h[10]);t[0]=(h[6]-h[9])/d;t[1]=(h[8]-h[2])/d;t[2]=(h[1]-h[4])/d;t[3]=.25*d;z.quat.multiply(c.quaternion,t,a.quaternion);m.vec3.set(c.center,h[12],
h[13],h[14]);q.bufferToBuffer(p,b,0,p,e,0,8);z.quat.conjugate(t,c.quaternion);for(d=e=b=a=0;8>d;d++)m.vec3.set(g,p[3*d+0],p[3*d+1],p[3*d+2]),m.vec3.sub(g,g,c.center),m.vec3.transformQuat(g,g,t),a=Math.max(a,Math.abs(g[0])),b=Math.max(b,Math.abs(g[1])),e=Math.max(e,Math.abs(g[2]));m.vec3.set(c.halfSize,a,b,e)}};var g=Q.vec3f64.create(),h=O.mat4f64.create(),t=P.quatf32.create(),p=new Float64Array(24)});