// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
require({cache:{"esri/views/2d/layers/BitmapTileLayerView2D":function(){define("require exports ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/declareExtendsHelper ../../../core/accessorSupport/decorators ../engine/BitmapTileContainer ../engine/Container".split(" "),function(l,e,g,h,b,c,f){Object.defineProperty(e,"__esModule",{value:!0});e.BitmapTileLayerView2D=function(a){return function(a){function d(){var c=null!==a&&a.apply(this,arguments)||this;c.container=new f.Container;return c}
h(d,a);d.prototype.attach=function(){var a=this;this.view.timeline.record(this.layer.title+" (BitmapTileLayer) Attach");this._bitmapView=new c.BitmapTileContainer(this._tileInfoView,this.clips);this.handles.add(this.clips.on("change",function(){return a._bitmapView.setClips(a.clips)}));this.container.addChild(this._bitmapView)};d.prototype.detatch=function(){this.container.removeChild(this._bitmapView);this._bitmapView.removeAllChildren()};return d=g([b.subclass("esri.views.2d.layers.BitmapTileLayerView2D")],
d)}(b.declared(a))}})},"esri/views/2d/layers/LayerView2D":function(){define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/Collection ../../../core/collectionUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators ../../layers/support/ClipArea ../../layers/support/ClipRect ../../layers/support/Geometry ../../layers/support/Path".split(" "),function(l,e,g,h,b,c,f,a,d,m,n,q){Object.defineProperty(e,"__esModule",{value:!0});
var k=b.ofType({key:"type",base:d,typeMap:{rect:m,path:q,geometry:n}});e.LayerView2D=function(d){return function(d){function b(){var a=null!==d&&d.apply(this,arguments)||this;a.clips=new k;a.moving=!1;a.attached=!1;a.lastUpdateId=-1;a.updateRequested=!1;return a}g(b,d);b.prototype.initialize=function(){var a=this;this.when(function(){a.requestUpdate()},function(){});var c=function(){return a.notifyChange("rendering")};this.handles.add([f.init(this,"suspended",function(c){a.container&&(a.container.visible=
!c);a.view&&!c&&a.updateRequested&&a.view.requestLayerViewUpdate(a)},!0),f.init(this,["fullOpacity","container"],function(){a.container&&(a.container.opacity=a.fullOpacity)},!0),f.on(this,"container","post-render",c),f.on(this,"container","will-render",c)])};b.prototype.destroy=function(){this.attached&&(this.attached=!1,this.detach());this.handles.remove("initialize");this.updateRequested=!1;this.view=this.layer=null};Object.defineProperty(b.prototype,"rendering",{get:function(){return this.attached&&
!this.suspended&&(this.moving||this.container.renderRequested||this.isRendering())},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"updating",{get:function(){return!this.suspended&&(!this.attached||this.updateRequested||this.isUpdating())},enumerable:!0,configurable:!0});b.prototype.isVisibleAtScale=function(a){var c=!0,b=this.layer,f=b.minScale,b=b.maxScale;if(null!=f&&null!=b){var c=!f,d=!b;!c&&a<=f&&(c=!0);!d&&a>=b&&(d=!0);c=c&&d}return c};b.prototype.requestUpdate=function(){this.updateRequested||
(this.updateRequested=!0,this.suspended||this.view.requestLayerViewUpdate(this))};b.prototype.processUpdate=function(a){this.isFulfilled()&&!this.isResolved()?this.updateRequested=!1:(this._set("updateParameters",a),this.updateRequested&&!this.suspended&&(this.updateRequested=!1,this.update(a)))};b.prototype.isUpdating=function(){return!1};b.prototype.isRendering=function(){return!1};b.prototype.canResume=function(){var a=this.inherited(arguments);a&&(a=this.isVisibleAtScale(this.view.scale));return a};
h([a.property({type:k,set:function(a){a=c.referenceSetter(a,this._get("clips"),k);this._set("clips",a)}})],b.prototype,"clips",void 0);h([a.property()],b.prototype,"moving",void 0);h([a.property({dependsOn:["attached","suspended","moving"]})],b.prototype,"rendering",null);h([a.property()],b.prototype,"attached",void 0);h([a.property()],b.prototype,"container",void 0);h([a.property({dependsOn:["view.scale","layer.minScale","layer.maxScale"]})],b.prototype,"suspended",void 0);h([a.property({readOnly:!0})],
b.prototype,"updateParameters",void 0);h([a.property()],b.prototype,"updateRequested",void 0);h([a.property({dependsOn:["updateRequested","attached","suspended"]})],b.prototype,"updating",null);h([a.property()],b.prototype,"view",void 0);return b=h([a.subclass("esri.views.2d.layers.LayerView2D")],b)}(a.declared(d))}})},"esri/views/layers/support/ClipArea":function(){define("require exports ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/declareExtendsHelper ../../../core/JSONSupport ../../../core/accessorSupport/decorators".split(" "),
function(l,e,g,h,b,c){return function(b){function a(){return null!==b&&b.apply(this,arguments)||this}h(a,b);return a=g([c.subclass("esri.views.layers.support.ClipArea")],a)}(c.declared(b.JSONSupport))})},"esri/views/layers/support/ClipRect":function(){define("require exports ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/declareExtendsHelper ../../../core/accessorSupport/decorators ./ClipArea".split(" "),function(l,e,g,h,b,c){return function(c){function a(){var a=null!==c&&c.apply(this,
arguments)||this;a.type="rect";a.left=null;a.right=null;a.top=null;a.bottom=null;return a}h(a,c);d=a;a.prototype.clone=function(){return new d({left:this.left,right:this.right,top:this.top,bottom:this.bottom})};Object.defineProperty(a.prototype,"version",{get:function(){return(this._get("version")||0)+1},enumerable:!0,configurable:!0});var d;g([b.property({type:[Number,String],json:{write:!0}})],a.prototype,"left",void 0);g([b.property({type:[Number,String],json:{write:!0}})],a.prototype,"right",
void 0);g([b.property({type:[Number,String],json:{write:!0}})],a.prototype,"top",void 0);g([b.property({type:[Number,String],json:{write:!0}})],a.prototype,"bottom",void 0);g([b.property({readOnly:!0,dependsOn:["left","right","top","bottom"]})],a.prototype,"version",null);return a=d=g([b.subclass("esri.views.layers.support.ClipRect")],a)}(b.declared(c))})},"esri/views/layers/support/Geometry":function(){define("require exports ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/declareExtendsHelper ../../../geometry ../../../core/accessorSupport/decorators ../../../geometry/Geometry ../../../geometry/support/jsonUtils ./ClipArea".split(" "),
function(l,e,g,h,b,c,f,a,d){var m={base:f,key:"type",typeMap:{extent:b.Extent,polygon:b.Polygon}};return function(b){function d(){var a=null!==b&&b.apply(this,arguments)||this;a.type="geometry";a.geometry=null;return a}h(d,b);f=d;Object.defineProperty(d.prototype,"version",{get:function(){return(this._get("version")||0)+1},enumerable:!0,configurable:!0});d.prototype.clone=function(){return new f({geometry:this.geometry.clone()})};var f;g([c.property({types:m,json:{read:a.fromJSON,write:!0}})],d.prototype,
"geometry",void 0);g([c.property({readOnly:!0,dependsOn:["geometry"]})],d.prototype,"version",null);return d=f=g([c.subclass("esri.views.layers.support.Geometry")],d)}(c.declared(d))})},"esri/views/layers/support/Path":function(){define("require exports ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/declareExtendsHelper ../../../core/accessorSupport/decorators ./ClipArea".split(" "),function(l,e,g,h,b,c){return function(c){function a(){var a=null!==c&&c.apply(this,arguments)||this;
a.type="path";a.path=[];return a}h(a,c);Object.defineProperty(a.prototype,"version",{get:function(){return(this._get("version")||0)+1},enumerable:!0,configurable:!0});g([b.property({type:[[[Number]]],json:{write:!0}})],a.prototype,"path",void 0);g([b.property({readOnly:!0,dependsOn:["path"]})],a.prototype,"version",null);return a=g([b.subclass("esri.views.layers.support.Path")],a)}(b.declared(c))})},"esri/views/2d/layers/support/popupUtils2D":function(){define(["require","exports","../../../../core/tsSupport/extendsHelper",
"../../../../core/tsSupport/decorateHelper","../../../../geometry/Extent"],function(l,e,g,h,b){Object.defineProperty(e,"__esModule",{value:!0});e.createQueryGeometry=function(c,f,a){var d=a.get("state.resolution"),d=f*("number"===typeof d?d:1);f=c.clone().offset(-d,-d);c=c.clone().offset(d,d);return new b({xmin:Math.min(f.x,c.x),ymin:Math.min(f.y,c.y),xmax:Math.max(f.x,c.x),ymax:Math.max(f.y,c.y),spatialReference:a.spatialReference})}})},"esri/views/layers/TileLayerView":function(){define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/tsSupport/generatorHelper ../../core/tsSupport/awaiterHelper ../../core/Error ../../core/promiseUtils ../../core/accessorSupport/decorators ../../renderers/support/clickToleranceUtils".split(" "),
function(l,e,g,h,b,c,f,a,d,m){Object.defineProperty(e,"__esModule",{value:!0});e.TileLayerView=function(e){return function(e){function k(){return null!==e&&e.apply(this,arguments)||this}g(k,e);k.prototype.fetchPopupFeatures=function(d){return c(this,void 0,void 0,function(){var h,g,e,k=this;return b(this,function(n){h=this.layer;if(!d)return[2,a.reject(new f("tilelayerview:fetchPopupFeatures","Nothing to fetch without area",{layer:h}))];if("tile"!==h.type)return[2,a.reject(new f("tilelayerview:fetchPopupFeatures",
"Layer type should be 'tile'",{type:h.type}))];g=this.get("view.scale");e=h.allSublayers.toArray().filter(function(a){var c=0===a.minScale||g<=a.minScale,b=0===a.maxScale||g>=a.maxScale;return a.popupTemplate&&a.popupEnabled&&a.visible&&c&&b});return[2,a.eachAlways(e.map(function(a){return c(k,void 0,void 0,function(){var c,f,h,g;return b(this,function(b){switch(b.label){case 0:return c=a.createQuery(),f=m.calculateTolerance(a.renderer),c.geometry=this.createFetchPopupFeaturesQueryGeometry(d,f),h=
c,[4,a.popupTemplate.getRequiredFields()];case 1:return h.outFields=b.sent(),[4,a.queryFeatures(c)];case 2:return g=b.sent(),[2,g.features]}})})})).then(function(a){return[].concat.apply([],a.map(function(a){return a.value}).filter(Boolean))})]})})};h([d.property()],k.prototype,"layer",void 0);return k=h([d.subclass("esri.layers.mixins.TileLayerView")],k)}(d.declared(e))}})},"esri/renderers/support/clickToleranceUtils":function(){define(["require","exports"],function(l,e){function g(c,b){return b&&
b.xoffset?Math.max(c,Math.abs(b.xoffset)):b&&b.yoffset?Math.max(c,Math.abs(b.yoffset)):c}function h(c,b){if("number"===typeof c)return c;if(c&&c.stops&&c.stops.length){c=c.stops;for(var a=b=0,d=0;d<c.length;d++){var f=c[d].size;"number"===typeof f&&(b+=f,a++)}return b/a}return b}function b(c,b){if(!b)return c;b=b.filter(function(a){return"size"===a.type}).map(function(a){var b=a.minSize;return(h(a.maxSize,c)+h(b,c))/2});var a=0,d=b.length;if(0===d)return c;for(var f=0;f<d;f++)a+=b[f];return Math.max(Math.floor(a/
d),c)}Object.defineProperty(e,"__esModule",{value:!0});e.calculateTolerance=function(c){if(!c)return 6;var f="visualVariables"in c?b(6,c.visualVariables):6;if("simple"===c.type)return g(f,c.symbol);if("unique-value"===c.type){var a=f;c.uniqueValueInfos.forEach(function(b){a=g(a,b.symbol)});return a}if("class-breaks"===c.type){var d=f;c.classBreakInfos.forEach(function(a){d=g(d,a.symbol)});return d}return f}})},"*noref":1}});
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../../../core/Error ../../../core/Logger ../../../core/maybe ../../../core/promiseUtils ../../../core/accessorSupport/decorators ../engine/Container ./BitmapTileLayerView2D ./LayerView2D ./support/popupUtils2D ../tiling/TileInfoView ../tiling/TileKey ../tiling/TileQueue ../tiling/TileStrategy ../../layers/LayerView ../../layers/RefreshableLayerView ../../layers/TileLayerView".split(" "),function(l,
e,g,h,b,c,f,a,d,m,n,q,k,u,v,w,r,x,y,z,A,B){var C=a.getLogger("esri.views.2d.layers.TileLayerView2D"),D=[0,0];return function(a){function e(){var b=null!==a&&a.apply(this,arguments)||this;b._tileStrategy=null;b._fetchQueue=null;b.container=new q.Container;b.layer=null;return b}g(e,a);e.prototype.initialize=function(){var a=this,b=this.layer.tileInfo,b=b&&b.spatialReference,c;b||(c=new f("layerview:tiling-information-missing","The layer doesn't provide tiling information",{layer:this.layer}));b.equals(this.view.spatialReference)||
(c=new f("layerview:spatial-reference-incompatible","The spatial reference of this layer does not meet the requirements of the view",{layer:this.layer}));this.watch("resampling",function(){a.refresh()});c&&this.addResolvingPromise(m.reject(c))};Object.defineProperty(e.prototype,"resampling",{get:function(){return!("resampling"in this.layer)||!1!==this.layer.resampling},enumerable:!0,configurable:!0});e.prototype.hitTest=function(){return null};e.prototype.update=function(a){this._fetchQueue.pause();
this._fetchQueue.state=a.state;this._tileStrategy.update(a);this._fetchQueue.resume();this.notifyChange("updating")};e.prototype.attach=function(){var a=this,b="tileServers"in this.layer?this.layer.tileServers:null;this._tileInfoView=new w(this.layer.tileInfo,this.layer.fullExtent);this._fetchQueue=new x({tileInfoView:this._tileInfoView,concurrency:b&&10*b.length||10,process:function(b,c){return a.fetchTile(b,c)}});this._tileStrategy=new y({cachePolicy:"keep",resampling:this.resampling,acquireTile:function(b){return a.acquireTile(b)},
releaseTile:function(b){return a.releaseTile(b)},tileInfoView:this._tileInfoView});this.requestUpdate();this.container.requestRender();this.inherited(arguments)};e.prototype.detach=function(){this.inherited(arguments);this._tileStrategy.destroy();this._fetchQueue.clear();this.container.removeAllChildren();this._fetchQueue=this._tileStrategy=this._tileInfoView=null};e.prototype.moveStart=function(){this.requestUpdate()};e.prototype.viewChange=function(){this.requestUpdate()};e.prototype.moveEnd=function(){this.requestUpdate()};
e.prototype.createFetchPopupFeaturesQueryGeometry=function(a,b){return v.createQueryGeometry(a,b,this.view)};e.prototype.doRefresh=function(){return c(this,void 0,void 0,function(){var a=this;return b(this,function(b){if(this.updateRequested||this.suspended)return[2];this._fetchQueue.reset();this._tileStrategy.tiles.forEach(function(b){return a._enqueueTileFetch(b)});this.notifyChange("updating");return[2]})})};e.prototype.isUpdating=function(){return 0<this._fetchQueue.length};e.prototype.acquireTile=
function(a){var b;a=this._bitmapView.createTile(a);var c=a.bitmap;b=this._tileInfoView.getTileCoords(D,a.key);c.x=b[0];c.y=b[1];c.resolution=this._tileInfoView.getTileResolution(a.key);b=this._tileInfoView.tileInfo.size;c.width=b[0];c.height=b[1];this._enqueueTileFetch(a);this.requestUpdate();return a};e.prototype.releaseTile=function(a){var b=this;this._fetchQueue.abort(a.key.id);this._bitmapView.removeChild(a);a.once("detach",function(){a.destroy();b.requestUpdate()});this.requestUpdate()};e.prototype.fetchTile=
function(a,e){return c(this,void 0,void 0,function(){var c,f,h,g,p,t,k,l,n;return b(this,function(b){switch(b.label){case 0:c="tilemapCache"in this.layer?this.layer.tilemapCache:null;f=!d.isNone(e)&&e.signal;if(c)return[3,4];b.label=1;case 1:return b.trys.push([1,3,,4]),[4,this._fetchImage(a,f)];case 2:return[2,b.sent()];case 3:h=b.sent();if(!m.isAbortError(h)&&!this.resampling)return[2,this._createBlankImage()];throw h;case 4:g=r.pool.acquire(),b.label=5;case 5:return b.trys.push([5,8,,10]),[4,c.fetchAvailabilityUpsample(a.level,
a.row,a.col,g,{signal:f})];case 6:return b.sent(),g.level===a.level||this.resampling?[4,this._fetchImage(g,f)]:[2,this._createBlankImage()];case 7:return p=b.sent(),[3,10];case 8:t=b.sent();if(m.isAbortError(t))throw r.pool.release(g),t;return[4,this._fetchImage(a,f)];case 9:return p=b.sent(),[3,10];case 10:return k=g.level,l=g.row,n=g.col,r.pool.release(g),this.resampling&&k!==a.level?[2,this._resampleImage(p,k,l,n,a.level,a.row,a.col)]:[2,p]}})})};e.prototype._enqueueTileFetch=function(a){return c(this,
void 0,void 0,function(){var c,d,e=this;return b(this,function(b){switch(b.label){case 0:if(this._fetchQueue.has(a.key.id))return[2];b.label=1;case 1:return b.trys.push([1,3,,4]),[4,this._fetchQueue.push(a.key)];case 2:return c=b.sent(),a.bitmap.source=c,a.bitmap.width=this._tileInfoView.tileInfo.size[0],a.bitmap.height=this._tileInfoView.tileInfo.size[1],a.once("attach",function(){return e.requestUpdate()}),this._bitmapView.addChild(a),[3,4];case 3:return d=b.sent(),m.isAbortError(d)||C.error(d),
[3,4];case 4:return this.requestUpdate(),[2]}})})};e.prototype._fetchImage=function(a,d){return c(this,void 0,void 0,function(){return b(this,function(b){return[2,this.layer.fetchTile(a.level,a.row,a.col,{timestamp:this.refreshTimestamp,signal:d})]})})};e.prototype._resampleImage=function(a,b,c,d,e,f,g){var h=this._tileInfoView.tileInfo.size,k=this._tileInfoView.getTileResolution(b),l=this._tileInfoView.getTileResolution(e);e=this._tileInfoView.getLODInfoAt(e);g=e.getXForColumn(g);f=e.getYForRow(f);
e=this._tileInfoView.getLODInfoAt(b);b=e.getXForColumn(d);d=e.getYForRow(c);c=Math.round((g-b)/k);b=Math.round(-(f-d)/k);d=Math.round(l/k*h[0]);k=Math.round(l/k*h[1]);l=this._createBlankImage();l.getContext("2d").drawImage(a,c,b,d,k,0,0,h[0],h[1]);return l};e.prototype._createBlankImage=function(){var a=this._tileInfoView.tileInfo.size,b=document.createElement("canvas");b.width=a[0];b.height=a[1];return b};h([n.property({dependsOn:["layer.resampling?"]})],e.prototype,"resampling",null);return e=h([n.subclass("esri.views.2d.layers.TileLayerView2D")],
e)}(n.declared(B.TileLayerView(A.RefreshableLayerView(k.BitmapTileLayerView2D(u.LayerView2D(z))))))});