// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper dojo/i18n!../nls/common dojo/i18n!./Expand/nls/Expand ../core/accessorSupport/decorators ./Widget ./Expand/ExpandViewModel ./support/widget".split(" "),function(v,w,r,d,n,t,e,u,p,c){return function(q){function b(a){a=q.call(this,a)||this;a.autoCollapse=null;a.collapseTooltip="";a.content="";a.expanded=null;a.expandTooltip="";a.group=null;a.iconNumber=0;a.label=t.widgetLabel;a.mode="auto";a.view=null;a.viewModel=
new p;return a}r(b,q);Object.defineProperty(b.prototype,"collapseIconClass",{get:function(){return"esri-icon-collapse"},set:function(a){a?this._override("collapseIconClass",a):this._clearOverride("collapseIconClass")},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"expandIconClass",{get:function(){return c.isWidget(this.content)?this.content.iconClass:"esri-icon-expand"},set:function(a){a?this._override("expandIconClass",a):this._clearOverride("expandIconClass")},enumerable:!0,
configurable:!0});b.prototype.expand=function(){this.viewModel.expanded=!0};b.prototype.collapse=function(){this.viewModel.expanded=!1};b.prototype.toggle=function(){this.viewModel.expanded=!this.viewModel.expanded};b.prototype.render=function(){var a,b,d,e,g,f=this.viewModel.expanded,k=this.mode,m=this.expandTooltip||n.expand,l=this.collapseTooltip||n.collapse,m=f?l:m,l=this.collapseIconClass,h=this.expandIconClass,l=(a={},a["esri-expand__icon--expanded"]=f,a[l]=f,a[h]=!f,a);a=(b={},b["esri-expand__container--expanded"]=
f,b);b=(d={},d["esri-expand__content--expanded"]=f,d);d=(e={},e["esri-expand__mask--expanded"]=f,e);e=(h=this.iconNumber)&&!f?c.tsx("span",{key:"expand__icon-number",class:"esri-expand__icon-number"},h):null;h=h&&f?c.tsx("span",{key:"expand__expand-icon-number",class:this.classes("esri-expand__icon-number","esri-expand__icon-number--expanded")},h):null;k=(g={},g["esri-expand--auto"]="auto"===k,g["esri-expand--drawer"]="drawer"===k,g["esri-expand--floating"]="floating"===k,g);g=this.id+"_controls_content";
return c.tsx("div",{class:this.classes("esri-expand esri-widget",k)},c.tsx("div",{bind:this,onclick:this._toggle,class:this.classes("esri-expand__mask",d)}),c.tsx("div",{class:this.classes("esri-expand__container",a)},c.tsx("div",{class:"esri-expand__panel"},c.tsx("div",{bind:this,onclick:this._toggle,onkeydown:this._toggle,"aria-controls":g,"aria-expanded":f?"true":"false",title:m,role:"button",tabindex:"0",class:"esri-widget--button"},e,c.tsx("span",{"aria-hidden":"true",class:this.classes("esri-collapse__icon",
l)}),c.tsx("span",{class:"esri-icon-font-fallback-text"},m)),h),c.tsx("div",{id:g,role:"region",class:this.classes("esri-expand__content",b)},this._renderContent())))};b.prototype._toggle=function(){this.toggle()};b.prototype._renderContent=function(){var a=this.content;return"string"===typeof a?c.tsx("div",{innerHTML:a}):c.isWidget(a)?a.render():a instanceof HTMLElement?c.tsx("div",{bind:a,afterCreate:this._attachToNode}):c.isWidgetBase(a)?c.tsx("div",{bind:a.domNode,afterCreate:this._attachToNode}):
null};b.prototype._attachToNode=function(a){a.appendChild(this)};d([e.aliasOf("viewModel.autoCollapse")],b.prototype,"autoCollapse",void 0);d([e.property({dependsOn:["content"]}),c.renderable()],b.prototype,"collapseIconClass",null);d([e.property(),c.renderable()],b.prototype,"collapseTooltip",void 0);d([e.property(),c.renderable()],b.prototype,"content",void 0);d([e.aliasOf("viewModel.expanded"),c.renderable()],b.prototype,"expanded",void 0);d([e.property({dependsOn:["content"]}),c.renderable()],
b.prototype,"expandIconClass",null);d([e.property(),c.renderable()],b.prototype,"expandTooltip",void 0);d([e.aliasOf("viewModel.group")],b.prototype,"group",void 0);d([e.property(),c.renderable()],b.prototype,"iconNumber",void 0);d([e.property()],b.prototype,"label",void 0);d([e.property(),c.renderable()],b.prototype,"mode",void 0);d([e.aliasOf("viewModel.view"),c.renderable()],b.prototype,"view",void 0);d([e.property({type:p}),c.renderable("viewModel.state")],b.prototype,"viewModel",void 0);d([c.accessibleHandler()],
b.prototype,"_toggle",null);return b=d([e.subclass("esri.widgets.Expand")],b)}(e.declared(u))});