spring:
  #线程池配置信息
  thread:
    pool:
      corePoolSize: 10
      maxPoolSize: 100
      keepAliveSeconds: 120
      queueCapacity: 200
      waitForTasksToCompleteOnShutdown: true
      awaitTerminationSeconds: 30
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
    maxIdle: 200
    maxActive: 1024
    maxWait: 1000
  #数据库连接配置信息
  datasource:
    url: jdbc:mysql://119.23.242.234:9306/wxdc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#    url: jdbc:mysql://127.0.0.1:3306/wxdc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  #    url: jdbc:oracle:thin:@//47.98.39.45:1521/orcl
  #    username: 'C##wdxc_admin'
  #    password: 'wdxc123456'
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    cachePrepStmts: true

#  boot:
#   admin:
#      url: http://127.0.0.1:9078
#      client:
#        name: WD-JOB
#management.security.enabled: false
#mybatis配置信息
mybatis:
  configLocation: classpath:mybatis/MapperConfig.xml
  mapperLocations: classpath:mybatis/sql/*.xml,classpath:mybatis/sql/extend/*.xml

logging:
  config: classpath:log4j2.xml

mapper:
  identity: MYSQL

server:
  port: 81

biz:
  url: http://127.0.0.1:8080/pub/gps/save

ticserver:
   url: http://127.0.0.1:9095/api/push/checkOnlin/
znzp:
   url:
