// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/generatorHelper ../../../../core/tsSupport/decorateHelper ../../../../core/tsSupport/awaiterHelper ../../../../core/tsSupport/declareExtendsHelper ../../../../geometry ../../../../request ../../../../core/Error ../../../../core/Logger ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/accessorSupport/decorators ../../../FeatureLayer ./StreamConnection ../../../../tasks/operations/query ../../../../tasks/support/Query".split(" "),
function(x,r,q,v,l,z,A,B,p,C,h,w,u,D,E,y,F){Object.defineProperty(r,"__esModule",{value:!0});var m=C.getLogger("esri.layers.graphics.sources.connections.GeoEventConnection"),t;(function(h){h[h.CONNECTING=0]="CONNECTING";h[h.OPEN=1]="OPEN";h[h.CLOSING=2]="CLOSING";h[h.CLOSED=3]="CLOSED"})(t=r.ReadyState||(r.ReadyState={}));x=function(r){function f(a,c,b,d,e,g){void 0===d&&(d=5);void 0===e&&(e=3);var k=r.call(this)||this;k.errorString=null;k._source=a;k._spatialReference=c;k._filter=b;k._outFields=
g;k._maxQueryDepth=d;k._maxRecordCountFactor=e;k._open();return k}z(f,r);f.prototype._open=function(){return l(this,void 0,void 0,function(){var a,c,b,d;return q(this,function(e){switch(e.label){case 0:return[4,this._fetchServiceDefinition(this._source)];case 1:return a=e.sent(),a.timeInfo.trackIdField||m.warn("GeoEvent service was configured without a TrackIdField. This may result in certain functionality being disabled. The maximumTrackPoints property will have no effect."),[4,this._fetchWebSocketUrl(a.streamUrls,
this._spatialReference)];case 2:return c=e.sent(),this._buddyServicesQuery||(this._buddyServicesQuery=this._queryBuddyServices()),[4,this._buddyServicesQuery];case 3:return e.sent(),[4,this._tryCreateWebSocket(c)];case 4:return e.sent(),b=this._filter,d=this._outFields,this._setFilter(b,d),[2]}})})};f.prototype.destroy=function(){h.isSome(this._websocket)&&(this._websocket.onopen=null,this._websocket.onclose=null,this._websocket.onerror=null,this._websocket.onmessage=null,this._websocket.close());
this._websocket=null};Object.defineProperty(f.prototype,"connectionStatus",{get:function(){if(h.isNone(this._websocket))return"disconnected";switch(this._websocket.readyState){case t.CONNECTING:case t.OPEN:return"connected";case t.CLOSING:case t.CLOSED:return"disconnected"}},enumerable:!0,configurable:!0});f.prototype._tryCreateWebSocket=function(a,c){void 0===c&&(c=1E3);return l(this,void 0,void 0,function(){var b,d,e;return q(this,function(g){switch(g.label){case 0:return g.trys.push([0,2,,4]),
b=this,[4,this._createWebSocket(a)];case 1:return b._websocket=g.sent(),this.notifyChange("connectionStatus"),[3,4];case 2:return d=g.sent(),e=c/1E3,m.error(new p("geoevent-connection","Failed to connect. Attempting to reconnect in "+e+"s",d)),[4,w.after(c)];case 3:return g.sent(),[2,this._tryCreateWebSocket(a,1.5*c)];case 4:return[2]}})})};f.prototype._createWebSocket=function(a){var c=this,b=new WebSocket(a);a=w.create(function(a,c){b.onopen=function(){return a(b)};b.onclose=function(a){return c(a)}});
a.then(function(){b.onclose=function(a){return c._onClose(a)};b.onerror=function(a){return c._onError(a)};b.onmessage=function(a){return c._onMessage(a)}});return a};f.prototype._onMessage=function(a){var c;try{c=this._enrich(JSON.parse(a.data))}catch(b){m.error(new p("geoevent-connection","Failed to parse message",b));return}this.onFeature(c)};f.prototype._onError=function(a){this._set("errorString","Encountered an error over WebSocket connection");m.error("geoevent-connection","Encountered an error over WebSocket connection")};
f.prototype._onClose=function(a){this._websocket=null;this.notifyChange("connectionStatus");1E3!==a.code&&m.error("geoevent-connection","WebSocket closed unexpectedly with error code "+a.code);this._open()};f.prototype._fetchServiceDefinition=function(a){return l(this,void 0,void 0,function(){var c,b,d,e;return q(this,function(g){switch(g.label){case 0:return c={f:"json"},b=B(a,{query:c,responseType:"json"}),[4,b];case 1:return d=g.sent(),this._serviceDefinition=e=d.data,[2,e]}})})};f.prototype._fetchWebSocketUrl=
function(a,c){return l(this,void 0,void 0,function(){var b,d,e,g;return q(this,function(k){b=a[0];d=b.urls;e=b.token;g=this._inferWebSocketBaseUrl(d);return[2,g+"/subscribe?outSR\x3d"+c.wkid+(e?"\x26token\x3d"+e:"")]})})};f.prototype._inferWebSocketBaseUrl=function(a){if(1===a.length)return a[0];for(var c=0;c<a.length;c++){var b=a[c];if(-1!==b.indexOf("wss"))return b}m.error(new p("geoevent-connection","Unable to infer WebSocket url",a));return null};f.prototype._setFilter=function(a,c){return l(this,
void 0,void 0,function(){var b,d,e,g,k,f,l=this;return q(this,function(n){b=this._websocket;this._filter=a;this._outFields=c;if(h.isNone(b)||h.isNone(a)&&h.isNone(c))return[2];d=JSON.stringify({filter:this._serializeFilter(a,c)});e=!1;g=w.createResolver();k=function(){e||(l._websocket===b&&m.error(new p("geoevent-connection","Server timed out when setting filter")),g.reject())};f=function(a){a=JSON.parse(a.data);a.filter&&(a.error&&(m.error(new p("geoevent-connection","Failed to set service filter",
a.error)),l._set("errorString","Could not set service filter - "+a.error),g.reject(a.error)),b.onmessage=l._onMessage.bind(l),e=!0,g.resolve())};b.onmessage=f;b.send(d);setTimeout(k,1E4);return[2,g.promise]})})};f.prototype._serializeFilter=function(a,c){var b={};if(h.isNone(a)&&h.isNone(c))return b;if(h.isSome(a)&&a.geometry)try{var d=A.fromJSON(a.geometry);if("extent"!==d.type)throw new p("Expected extent but found type "+d.type);b.geometry=JSON.stringify(d.shiftCentralMeridian())}catch(e){m.error(new p("geoevent-connection",
"Encountered an error when setting connection geometryDefinition",e))}h.isSome(a)&&a.where&&(b.where=a.where);h.isSome(c)&&(b.outFields=c.join(","));return b};f.prototype._enrich=function(a){if(!this._relatedFeatures)return a;var c=a.attributes[this._serviceDefinition.relatedFeatures.joinField];if(!this._relatedFeatures.has(c))return m.warn("geoevent-connection","Feature join failed. Is the join field configured correctly?",a),a;var b=this._relatedFeatures.get(c),c=b.attributes,b=b.geometry,d;for(d in c)a.attributes[d]=
c[d];b&&(a.geometry=b);a.geometry||a.centroid||m.error(new p("geoevent-connection","Found malformed feature - no geometry found",a));return a};f.prototype._queryBuddyServices=function(){return l(this,void 0,void 0,function(){var a,c,b,d,e,g,f,h,l,n;return q(this,function(k){switch(k.label){case 0:return k.trys.push([0,3,,4]),a=this._serviceDefinition,c=a.relatedFeatures,b=a.keepLatestArchive,d=this._queryRelatedFeatures(c),e=this._queryArchive(b),[4,d];case 1:return k.sent(),[4,e];case 2:g=k.sent();
if(!g)return[2];f=0;for(h=g.features;f<h.length;f++)l=h[f],this.onFeature(this._enrich(l));return[3,4];case 3:return n=k.sent(),m.error(new p("geoevent-connection","Encountered an error when querying buddy services",{error:n})),[3,4];case 4:return[2]}})})};f.prototype._queryRelatedFeatures=function(a){return l(this,void 0,void 0,function(){var c;return q(this,function(b){switch(b.label){case 0:return a?[4,this._queryBuddy(a.featuresUrl)]:[2];case 1:return c=b.sent(),this._addRelatedFeatures(c),[2]}})})};
f.prototype._queryArchive=function(a){return l(this,void 0,void 0,function(){return q(this,function(c){return a?[2,this._queryBuddy(a.featuresUrl)]:[2,void 0]})})};f.prototype._queryBuddy=function(a){return l(this,void 0,void 0,function(){var c,b,d,e,f,k,l,m,n,p;return q(this,function(g){switch(g.label){case 0:return c=new D({url:a}),[4,c.load()];case 1:return b=g.sent().capabilities,d=b.query.supportsMaxRecordCountFactor,e=b.query.supportsPagination,f=b.query.supportsCentroid,k=this._maxRecordCountFactor,
l=c.capabilities.query.maxRecordCount,m=d?l*k:l,n=new F,n.outFields=h.unwrapOr(this._outFields,["*"]),n.where=h.unwrapOr(h.get(this._filter,"where"),"1\x3d1"),n.returnGeometry=!0,n.returnExceededLimitFeatures=!0,n.outSpatialReference=this._spatialReference,f&&(n.returnCentroid=!0),d&&(n.maxRecordCountFactor=k),e?(n.num=m,c.destroy(),[2,this._queryPages(a,n)]):[4,y.executeQuery(a,n)];case 2:return p=g.sent(),c.destroy(),[2,p.data]}})})};f.prototype._queryPages=function(a,c,b,d){void 0===b&&(b=[]);
void 0===d&&(d=0);return l(this,void 0,void 0,function(){var e;return q(this,function(f){switch(f.label){case 0:return c.start=d*c.num,[4,y.executeQuery(a,c)];case 1:e=f.sent().data;if(e.exceededTransferLimit&&d<this._maxQueryDepth)return e.features.forEach(function(a){return b.push(a)}),[2,this._queryPages(a,c,b,d+1)];b.forEach(function(a){return e.features.push(a)});return[2,e]}})})};f.prototype._addRelatedFeatures=function(a){var c=new Map,b=this._serviceDefinition.relatedFeatures.joinField,d=
0;for(a=a.features;d<a.length;d++){var e=a[d];c.set(e.attributes[b],e)}this._relatedFeatures=c};v([u.property()],f.prototype,"connectionStatus",null);v([u.property()],f.prototype,"errorString",void 0);return f=v([u.subclass("esri.layers.graphics.sources.connections.GeoEventConnection")],f)}(u.declared(E.default));r.default=x});