// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/assignHelper ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/tsSupport/generatorHelper ../../core/tsSupport/awaiterHelper ../../rasterRenderers ../../core/JSONSupport ../../core/Logger ../../core/accessorSupport/decorators ../../layers/support/RasterInfo ../../layers/support/rasterFunctions/pixelUtils ../support/colorRampUtils".split(" "),function(B,C,m,v,p,D,E,t,w,x,k,y,h,z){var A=x.getLogger("esri.renderers.support.RasterSymbolizer");
return function(u){function e(a){return u.call(this,a)||this}v(e,u);e.prototype.readRenderer=function(a,c,b){return t.read(a,b)};e.prototype.bind=function(){this.lookup={};if(!this.renderer)return!1;var a;switch(this.renderer.type){case "unique-value":a=this._updateUVRenderer(this.renderer);break;case "raster-colormap":a=this._updateColormapRenderer(this.renderer);break;case "raster-stretch":a=this._updateStretchRenderer(this.renderer);break;case "class-breaks":a=this._updateClassBreaksRenderer(this.renderer)}return a};
e.prototype.symbolize=function(a){if(!(a&&a.pixels&&0<a.pixels.length&&0!==a.validPixelCount))return a;try{3<a.pixels.length&&(a=h.extractBands(a,[0,1,2]));var c=void 0;switch(this.renderer.type){case "unique-value":case "raster-colormap":c=this._symbolize_colormap(a);break;case "class-breaks":c=this._symbolize_classBreaks(a);break;case "raster-stretch":c=this._symbolize_stretch(a)}return c}catch(b){return A.error("symbolize",b.message),a}};e.prototype._isLUTChanged=function(a){if(!this.lookup)return!0;
if("raster-stretch"===this.renderer.type){var c=this.renderer.colorRamp;if(a)return JSON.stringify(c.toJSON())!==JSON.stringify(this.lookup.rendererJson.colorRamp);a=m({},this.renderer.toJSON());c=m({},this.lookup.rendererJson);a.colorRamp=null;c.colorRamp=null}return JSON.stringify(this.renderer.toJSON())!==JSON.stringify(this.lookup.rendererJson)};e.prototype._symbolize_colormap=function(a){return this._isLUTChanged()&&!this.bind()?a:h.colorize(a,this.lookup.lut)};e.prototype._symbolize_classBreaks=
function(a){var c=-1<["u8","u16","s8","s16"].indexOf(this.rasterInfo.pixelType);return this._isLUTChanged()&&!this.bind()?a:c?h.colorize(a,this.lookup.lut):h.remapColor(a,this.lookup.lut)};e.prototype._symbolize_stretch=function(a){var c=this.rasterInfo.pixelType,b=this.renderer,n=-1<["u8","u16","s8","s16"].indexOf(c),d=b.gamma,e=b.useGamma;if(n){if(b.dynamicRangeAdjustment)n=this.getStretchCutoff(b,a),c=h.createStretchLUT(m({pixelType:c},n,{gamma:e?d:null}));else{if(this._isLUTChanged()&&(d=this.bind(),
!d))return a;c=this.lookup?this.lookup.lut:null}if(!c)return a;c=h.lookupPixels(a,c)}else n=this.getStretchCutoff(b,a),c=h.stretch(a,m({},n,{gamma:e?d:null}));if(b.colorRamp){if(this._isLUTChanged(!0)&&(d=this.bind(),!d))return a;c=h.colorize(c,this.lookup.colorRampLut)}return c};e.prototype._updateUVRenderer=function(a){var c=this.rasterInfo,b=c.bandCount,n=c.attributeTable,d=c.statistics,c=-1<["u8","s8"].indexOf(c.pixelType)&&d&&null!=d[0].min&&null!=d[0].max;if(1!==b||!n&&!c)return!1;var e=a.field;
if(!e)return!1;var f=[];if(n){var q=n.fields.filter(function(a){return"value"===a.name.toLowerCase()})[0];if(!q)return!1;n.features.forEach(function(b){var c=a.uniqueValueInfos.filter(function(a){return String(a.value)===String(b.attributes[e])})[0];(c=c&&c.symbol&&c.symbol.color)&&f.push([b.attributes[q.name],c.r,c.g,c.b,1<c.a?c.a:Math.round(255*c.a)])})}else{if("Value"!==e.toLowerCase())return!1;a.uniqueValueInfos.forEach(function(a){var b=a&&a.symbol&&a.symbol.color;b&&f.push([parseInt(a.value,
10),b.r,b.g,b.b,1<b.a?b.a:Math.round(255*b.a)])})}if(0===f.length)return!1;b=h.createColormapLUT({colormap:f});this.lookup={rendererJson:a.toJSON(),lut:b};return!0};e.prototype._updateColormapRenderer=function(a){var c=a.extractColormap();if(!c||0===c.length)return!1;c=h.createColormapLUT({colormap:c});this.lookup={rendererJson:a.toJSON(),lut:c};return!0};e.prototype._updateClassBreaksRenderer=function(a){var c=-1<["u8","u16","s8","s16"].indexOf(this.rasterInfo.pixelType),b=a.classBreakInfos;if(!b||
0===b.length)return!1;var e=b.sort(function(a,b){return a.minValue-b.minValue}),b=e[e.length-1];if(!c)return c=e.map(function(a){return{value:a.minValue,mappedColor:[a.symbol.color.r,a.symbol.color.g,a.symbol.color.b,1<a.symbol.color.a?a.symbol.color.a:Math.round(255*a.symbol.color.a)]}}),c.push({value:b.maxValue,mappedColor:[b.symbol.color.g,b.symbol.color.b,1<b.symbol.color.a?b.symbol.color.a:Math.round(255*b.symbol.color.a)]}),this.lookup={rendererJson:a.toJSON(),lut:c},!0;var d=[],l,f=0;e.forEach(function(a){l=
Math.ceil(a.minValue);f=Math.floor(a.maxValue);for(var b=l;b<f;b++)d.push([b,a.symbol.color.r,a.symbol.color.g,a.symbol.color.b,1<a.symbol.color.a?a.symbol.color.a:Math.round(255*a.symbol.color.a)])});d.push([b.maxValue,b.symbol.color.r,b.symbol.color.g,b.symbol.color.b,1<b.symbol.color.a?b.symbol.color.a:Math.round(255*b.symbol.color.a)]);c=h.createColormapLUT({colormap:d,fillUnspecified:!1});this.lookup={rendererJson:a.toJSON(),lut:c};return!0};e.prototype._updateStretchRenderer=function(a){if(!(a.statistics||
this.rasterInfo.statistics||a.dynamicRangeAdjustment))return!1;var c=a.histograms||this.rasterInfo.histograms;if(!a.dynamicRangeAdjustment&&"percent-clip"===a.stretchType&&!c)return!1;var b=a.gamma,e=a.useGamma,c=a.colorRamp,d=this.rasterInfo.pixelType;if(!a.dynamicRangeAdjustment&&-1<["u8","u16","s8","s16"].indexOf(d)){var l=this.getStretchCutoff(a),b=h.createStretchLUT(m({pixelType:d},l,{gamma:e?b:null}));this.lookup={rendererJson:a.toJSON(),lut:b}}c&&(c=z.convertColorRampToColormap(c,256),this.lookup.colorRampLut=
h.createColormapLUT({colormap:c}),this.lookup.rendererJson=a.toJSON());return!0};e.prototype.getStretchCutoff=function(a,c){var b,e,d=a.stretchType;a.dynamicRangeAdjustment?"min-max"===d&&c.statistics?b=c.statistics.map(function(a){return[a.minValue,a.maxValue,0,0]}):(e=h.estimateStatisticsHistograms(c),b=e.statistics,e=e.histograms):(b=a.statistics,e=a.histograms||this.rasterInfo.histograms);c=b||e?(b||e).length:this.rasterInfo.bandCount;var l=[],f=[],q,k,r,m,p,g;b[0]instanceof Array||(b=b.map(function(a){return[a.min,
a.max,a.avg,a.stddev]}));switch(d){case "min-max":for(d=0;d<c;d++)l[d]=b[d][0],f[d]=b[d][1];break;case "standard-deviation":for(d=0;d<c;d++)l[d]=b[d][2]-a.numberOfStandardDeviations*b[d][3],f[d]=b[d][2]+a.numberOfStandardDeviations*b[d][3],l[d]<b[d][0]&&(l[d]=b[d][0]),f[d]>b[d][1]&&(f[d]=b[d][1]);break;case "percent-clip":for(d=0;d<c;d++){b=e[d];m=new Uint32Array(b.size);r=b.counts;k=0;q=(b.max-b.min)/b.size;p=-.5===b.min&&1===q?.5:0;for(g=0;g<b.size;g++)k+=r[g],m[g]=k;r=a.minPercent*k/100;for(g=
0;g<b.size;g++)if(m[g]>r){l[d]=b.min+q*(g+p);break}r=(1-a.maxPercent/100)*k;for(g=b.size-2;0<=g;g--)if(m[g]<r){f[d]=b.min+q*(g+2-p);break}}break;default:for(d=0;d<c;d++)l[d]=b[d][0],f[d]=b[d][1]}return{minCutOff:l,maxCutOff:f,outMax:a.outputMax||255,outMin:a.outputMin||0}};p([k.property({types:t.rasterRendererTypes,json:{write:!0}})],e.prototype,"renderer",void 0);p([k.reader("renderer")],e.prototype,"readRenderer",null);p([k.property({type:y,json:{write:!0}})],e.prototype,"rasterInfo",void 0);p([k.property({json:{write:!0}})],
e.prototype,"lookup",void 0);return e=p([k.subclass("esri.renderers.support.RasterSymbolizer")],e)}(k.declared(w.JSONSupport))});