// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/assignHelper ../../core/Logger ../../core/unitUtils ../../intl/date ./numberUtils ../visualVariables/support/ColorStop".split(" "),function(z,f,A,v,d,m,g,w){function r(a,c,e){var b="";0===c?b=k.lt+" ":c===e&&(b=k.gt+" ");return b+a}function n(a){var c=a.minValue,e=a.maxValue,b=a.isFirstBreak?"":k.gt+" ";a="percent-of-total"===a.normalizationType?k.pct:"";c=null==c?"":g.format(c);e=null==e?"":g.format(e);return b+c+a+" "+k.ld+" "+e+a}Object.defineProperty(f,
"__esModule",{value:!0});var t=v.getLogger("esri.renderers.support.utils"),k={lte:"\x3c\x3d",gte:"\x3e\x3d",lt:"\x3c",gt:"\x3e",pct:"%",ld:"\u2013"},x={millisecond:0,second:1,minute:2,hour:3,day:4,month:5,year:6},y={millisecond:"long-month-day-year-long-time",second:"long-month-day-year-long-time",minute:"long-month-day-year-short-time",hour:"long-month-day-year-short-time",day:"long-month-day-year",month:"long-month-day-year",year:"year"};f.meterIn={inches:d.convertUnit(1,"meters","inches"),feet:d.convertUnit(1,
"meters","feet"),"us-feet":d.convertUnit(1,"meters","us-feet"),yards:d.convertUnit(1,"meters","yards"),miles:d.convertUnit(1,"meters","miles"),"nautical-miles":d.convertUnit(1,"meters","nautical-miles"),millimeters:d.convertUnit(1,"meters","millimeters"),centimeters:d.convertUnit(1,"meters","centimeters"),decimeters:d.convertUnit(1,"meters","decimeters"),meters:d.convertUnit(1,"meters","meters"),kilometers:d.convertUnit(1,"meters","kilometers"),"decimal-degrees":1/d.lengthToDegrees(1,"meters")};f.timelineDateFormatOptions=
m.convertDateFormatToIntlOptions("short-date");f.createColorStops=function(a){var c=a.values,e=a.colors,b=a.labelIndexes,q=a.isDate,h=a.dateFormatOptions;return c.map(function(a,d){var u=null;if(!b||-1<b.indexOf(d)){var p=void 0;(p=q?m.formatDate(a,h):g.format(a))&&(u=r(p,d,c.length-1))}return new w({value:a,color:e[d],label:u})})};f.updateColorStops=function(a){var c=a.stops,e=a.changes,b=a.isDate,q=a.dateFormatOptions,h=c.map(function(a){return a.value});a=[];for(var d=0;d<e.length;d++){var f=e[d];
a.push(f.index);h[f.index]=f.value}var k=g.round(h,{indexes:a});c.forEach(function(a,e){a.value=h[e];if(null!=a.label){var d=void 0,f=null;(d=b?m.formatDate(k[e],q):g.format(k[e]))&&(f=r(d,e,c.length-1));a.label=f}})};f.createClassBreakLabel=n;f.setLabelsForClassBreaks=function(a){var c=a.classBreakInfos,e=a.normalizationType,b=[];if(c&&c.length)if("standard-deviation"===a.classificationMethod)t.warn("setLabelsForClassBreaks","cannot set labels for class breaks generated using 'standard-deviation' method.");
else if(a.round){b.push(c[0].minValue);for(a=0;a<c.length;a++)b.push(c[a].maxValue);b=g.round(b);c.forEach(function(a,c){a.label=n({minValue:0===c?b[0]:b[c],maxValue:b[c+1],isFirstBreak:0===c,normalizationType:e})})}else c.forEach(function(a,b){a.label=n({minValue:a.minValue,maxValue:a.maxValue,isFirstBreak:0===b,normalizationType:e})})};f.updateClassBreak=function(a){if("standard-deviation"===a.classificationMethod)t.warn("updateClassBreak","cannot update labels for class breaks generated using 'standard-deviation' method.");
else{var c=a.classBreaks,e=a.change,b=e.index,e=e.value,d=c.length,h=-1,f=-1;0===b?h=b:b===d?f=b-1:(f=b-1,h=b);a=a.normalizationType;b=null;-1<h&&h<d&&(b=c[h],b.minValue=e,b.label=n({minValue:b.minValue,maxValue:b.maxValue,isFirstBreak:0===h,normalizationType:a}));-1<f&&f<d&&(b=c[f],b.maxValue=e,b.label=n({minValue:b.minValue,maxValue:b.maxValue,isFirstBreak:0===f,normalizationType:a}))}};f.calculateDateFormatInterval=function(a){a=a.map(function(a){return new Date(a)});for(var c=a.length,e=Infinity,
b=null,d=0;d<c-1;d++){for(var f=a[d],k=[],g=Infinity,m=null,p=d+1;p<c;p++){var l=a[p],l=f.getFullYear()!==l.getFullYear()&&"year"||f.getMonth()!==l.getMonth()&&"month"||f.getDate()!==l.getDate()&&"day"||f.getHours()!==l.getHours()&&"hour"||f.getMinutes()!==l.getMinutes()&&"minute"||f.getSeconds()!==l.getSeconds()&&"second"||"millisecond",n=x[l];n<g&&(g=n,m=l);k.push(l)}g<e&&(e=g,b=m)}return b};f.createUniqueValueLabel=function(a){var c=a.value,e=a.domain,b=a.fieldInfo;a=a.dateFormatInterval;var d=
String(c);(e=e&&"codedValues"in e&&e.codedValues?e.getName(c):null)?d=e:"number"===typeof c&&(d=b&&"date"===b.type?m.formatDate(c,a&&m.convertDateFormatToIntlOptions(y[a])):g.format(c));return d}});