// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/decorateHelper ../../../../../core/tsSupport/declareExtendsHelper ../../../../../core/tsSupport/assignHelper ../../../../../core/Collection ../../../../../core/Evented ../../../../../core/Handles ../../../../../core/maybe ../../../../../core/watchUtils ../../../../../core/accessorSupport/decorators ../../Manipulator3D ../../manipulatorUtils ../manipulatorUtils ./isSupportedGraphic ../../../../interactive/InteractiveToolBase ../../../../interactive/dragUtils/dragActions ../../../../interactive/dragUtils/dragHandlers".split(" "),
function(l,d,h,r,t,u,v,w,x,m,g,y,z,k,A,B,C,D){Object.defineProperty(d,"__esModule",{value:!0});var n=function(){return function(e){this.allGraphics=e;this.type="graphic-move-start"}}();d.GraphicMoveStartEvent=n;var p=function(){return function(e,a,c,E){this.dx=e;this.dy=a;this.dz=c;this.allGraphics=E;this.type="graphic-move"}}();d.GraphicMoveEvent=p;var q=function(){return function(e){this.allGraphics=e;this.type="graphic-move-stop"}}();d.GraphicMoveStopEvent=q;l=function(e){function a(c){c=e.call(this,
c)||this;c.graphics=new u;c.type="move-3d";c._handles=new w;return c}r(a,e);a.prototype.initialize=function(){var c=this;this._handles.add(this.graphics.on("change",function(){c._refreshManipulators()}));this._refreshManipulators()};a.prototype.destroy=function(){this._handles.destroy();this._handles=null;this.graphics.removeAll();this._set("view",null)};a.prototype.reset=function(){};a.prototype._createDragAction=function(c){var a=this,e=C.createGraphicDragActionMany(c);return function(b){switch(b.action){case "start":a.emit("graphic-move-start",
new n(c))}e(b);switch(b.action){case "start":case "update":("update"===b.action||b.deltaX||b.deltaY||b.deltaZ)&&a.emit("graphic-move",new p(b.deltaX,b.deltaY,b.deltaZ,c));break;case "end":a.emit("graphic-move-stop",new q(c))}}};a.prototype._refreshManipulators=function(){var c=this;this._handles.remove("graphics");this.manipulators.removeAll();for(var a=this.graphics.toArray(),e=[],b=function(a){if(0!==A.isSupportedGraphic(a))return"continue";var b=k.createGraphicMoveXYManipulator(f.view,a);f._handles.add(b.events.on("immediate-click",
function(b){c.emit("immediate-click",t({},b,{graphic:a}));b.stopPropagation()}),"graphics");f.manipulators.add(b);e.push(b);var d=k.createGraphicMoveZManipulator({view:f.view,graphic:a});if(x.isNone(d))return"continue";f._handles.add([m.init(a,"geometry",function(){return z.placeManipulatorAtGraphic(d,a)}),m.init(a,["visible","layer.visible"],function(){return d.visible=a.visible&&a.layer.visible})],"graphics");f.manipulators.add(d);e.push(d)},f=this,d=0;d<a.length;d++)b(a[d]);D.createManipulatorDragHandlerOneOf(e,
function(a,b){return a instanceof y.Manipulator3D?k.createGraphicMoveZScreenDragToMap(c.view,a):k.createGraphicMoveXYScreenDragToMap(c.view,a,b)},this._createDragAction(a))};h([g.property({constructOnly:!0,nonNullable:!0})],a.prototype,"view",void 0);h([g.property({readOnly:!0})],a.prototype,"graphics",void 0);h([g.property({readOnly:!0})],a.prototype,"type",void 0);return a=h([g.subclass("esri.views.3d.interactive.editingTools.graphicMove3D.GraphicMove3DTool")],a)}(g.declared(v.EventedMixin(B.InteractiveToolBase)));
d.GraphicMove3DTool=l});