// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/declareExtendsHelper ../../../../../core/tsSupport/decorateHelper ../../../../../core/tsSupport/assignHelper ../../../../../core/tsSupport/generatorHelper ../../../../../core/tsSupport/awaiterHelper ../../../../../core/ArrayPool ../../../../../core/Error ../../../../../core/has ../../../../../core/Logger ../../../../../core/now ../../../../../core/promiseUtils ../../../../../core/watchUtils ../../../../../core/workers ../../../../../core/accessorSupport/decorators ../../../../../geometry/Extent ../../../../../geometry/support/jsonUtils ../../../../../layers/graphics/featureConversionUtils ../../../../../tasks/operations/query ../../../engine ./BaseController ./EditsQueue ../support/DataTile ../support/DataTileFeaturesIndex ../support/Tile ../support/TileUpdateQueue ../../../tiling/TileQueue".split(" "),
function(l,L,S,w,z,u,f,T,U,C,V,M,A,W,X,r,Y,N,D,O,Z,E,aa,F,ba,G,ca,P){Object.defineProperty(L,"__esModule",{value:!0});var H=V.getLogger("esri.views.2d.layers.features.controllers.OnDemandController");l=C("esri-featurelayer-webgl");C=C("esri-mobile");var I=l&&"object"===typeof l&&null!=l.maxDrillLevel?l.maxDrillLevel:C?1:4,Q=l&&"object"===typeof l&&null!=l.maxRecordCountFactor?l.maxRecordCountFactor:C?1:3,da=l&&"object"===typeof l&&null!=l.enablePBFQuery?l.enablePBFQuery:!0,J=new Set,x=[],ea=function(){function g(c,
a){this.objectIdField=a;this.client=X.openWithPorts(c)}g.prototype.destroy=function(){this.client.close();this.client=null};g.prototype.executeQuery=function(c,a){return f(this,void 0,void 0,function(){var b;return u(this,function(d){switch(d.label){case 0:return[4,this.client.invoke("queryFeatures",c.toJSON(),a)];case 1:return b=d.sent(),[2,D.convertFromFeatureSet(b,this.objectIdField)]}})})};return g}(),fa=function(){function g(c){this.source=c}g.prototype.destroy=function(){};g.prototype.executeQuery=
function(c,a){return f(this,void 0,void 0,function(){var b;return u(this,function(d){switch(d.label){case 0:return[4,O.executeQueryPBF(this.source,c,{type:"optimized"},a)];case 1:return b=d.sent().data,[2,b]}})})};return g}(),ga=function(){function g(c,a){this.source=c;this.objectIdField=a}g.prototype.destroy=function(){};g.prototype.executeQuery=function(c,a){return f(this,void 0,void 0,function(){var b;return u(this,function(d){switch(d.label){case 0:return[4,O.executeQuery(this.source,c,a)];case 1:return b=
d.sent().data,[2,D.convertFromFeatureSet(b,this.objectIdField)]}})})};return g}();E=function(g){function c(){var a=null!==g&&g.apply(this,arguments)||this;a.type="on-demand";a._queryInfoHash=null;a._dataTileIndex=new ba.default;a._editsQueue=new aa.EditsQueue({processEdits:a._processEdits.bind(a)});a._featuresInFlight=new Map;return a}S(c,g);c.prototype.initialize=function(){var a=this,b=this._createFeatureStore();b.onFeatureAdd=this.onFeatureAdd.bind(this);b.onFeatureRemove=this.onFeatureRemove.bind(this);
this._set("featureStore",b);this._dataTileIndex.featureStore=this.featureStore;this._dataTileIndex.forEach(function(a){return a.done=!1});this._fetchQueue=new P({concurrency:10,strategy:"center-first",tileInfoView:this.tileStore.tileScheme,process:function(b,d){return a._fetchTile(b,a.queryInfo,d)}});this._patchQueue=new P({concurrency:10,strategy:"center-first",tileInfoView:this.tileStore.tileScheme,process:function(b,d){return a._fetchTile(b.dataTile,b.queryInfo,d)}});this._updateQueue=new ca.default({tileInfoView:this.tileStore.tileScheme,
process:function(b,d,h){return a._updateTile(b,d,h)}});var d=this.service,b=d.capabilities,h=d.source,d=d.objectIdField;Array.isArray(h)?this.sourceAdapter=new ea(h,d):this.sourceAdapter=da&&b.query.supportsFormatPBF?new fa(h):new ga(h,d);this.handles.add([this.watch("updating",function(b){return!b&&a.onIdle()})]);this.featureStore.events.on("valueRangesChanged",function(b){a.remoteClient.invoke("emitEvent",{name:"valueRangesChanged",event:{valueRanges:b.valueRanges}})})};c.prototype.destroy=function(){this._fetchQueue.clear();
this._patchQueue.clear();this._updateQueue.clear();this._editsQueue.destroy();this.queryEngine.destroy();this.sourceAdapter.destroy()};Object.defineProperty(c.prototype,"queryEngine",{get:function(){return this._createQueryEngine(this.featureStore)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"updating",{get:function(){return!this.viewState||this._fetchQueue.updating||this._patchQueue.updating||this._updateQueue.updating||this._editsQueue.updating},enumerable:!0,configurable:!0});
c.prototype.update=function(a,b){return f(this,void 0,void 0,function(){var d,h,c,v,m,K,q=this;return u(this,function(e){switch(e.label){case 0:return this.validateConfig(a),d=JSON.stringify(this.config.filters),h=this.renderer.getAttributeHash(),c=a.availableFields.filter(function(a){return-1===q.availableFields.indexOf(a)}),v=this.config.definitionExpression,this._set("config",a),v!==this.config.definitionExpression&&this._set("queryEngine",this._createQueryEngine(this.featureStore)),[4,this.updatePixelBuffer()];
case 1:return e.sent(),m=d!==JSON.stringify(a.filters),K=h!==this.renderer.getAttributeHash(),b?K?[4,this.attributeStore.setAttributeBindings(this.renderer,this.arcadeInfo)]:[3,3]:[3,6];case 2:e.sent(),e.label=3;case 3:return[4,this.attributeStore.updateFilters(this)];case 4:return e.sent(),[4,this.featureStore.update(m,a)];case 5:return e.sent(),this.refresh(),[2];case 6:return c.length?[4,this._handleAttributeChange(c)]:[3,8];case 7:e.sent(),e.label=8;case 8:return"heatmap"===this.renderer.type?
[2]:K?[4,this.attributeStore.setAttributeBindings(this.renderer,this.arcadeInfo)]:[3,10];case 9:e.sent(),this.featureStore.forEach(function(a){return q.attributeStore.setAttributeData(a.localId,a,q.geometryInfo,q.viewParams)}),e.label=10;case 10:return[4,this.attributeStore.updateFilters(this)];case 11:return e.sent(),[4,this.featureStore.update(m,a)];case 12:return e.sent(),[4,this.attributeStore.sendUpdates()];case 13:return e.sent(),[2]}})})};c.prototype.invalidate=function(){return f(this,void 0,
void 0,function(){var a,b,d;return u(this,function(h){a=0;for(b=this.tileStore.tiles;a<b.length;a++)d=b[a],this._updateQueue.push(d.id,Date.now());return[2]})})};c.prototype.onIdle=function(){this.featureStore.sweepClusters()};c.prototype.onEdits=function(a){var b=this;this._fetchQueue.pause();this._fetchQueue.reset();return this._editsQueue.push(a).then(function(){b._editsQueue.updating||b._fetchQueue.resume()})};c.prototype.queryFeatures=function(a){return this.queryEngine.executeQuery(a)};c.prototype.queryFeatureCount=
function(a){return this.queryEngine.executeQueryForCount(a)};c.prototype.queryObjectIds=function(a){return this.queryEngine.executeQueryForIds(a)};c.prototype.queryExtent=function(a){return this.queryEngine.executeQueryForExtent(a)};c.prototype.queryStatistics=function(a){return f(this,void 0,void 0,function(){var a,d,h,c=this;return u(this,function(b){switch(b.label){case 0:return h=d=a=0,[4,A.all(this.tileStore.tiles.map(function(b){return f(c,void 0,void 0,function(){var c,k,e,t,n,v,m,R,f,g,B;
return u(this,function(p){switch(p.label){case 0:return c=this.queryInfo,k=c.returnCentroid,e=c.returnGeometry,t=this._pixelBuffer,n={pixelBuffer:t,returnGeometry:e,returnCentroid:k,returnOutline:this.returnOutline},v=M(),[4,this.featureStore.executeTileQuery(b,this.spatialReference,n)];case 1:m=p.sent().features;R=M();h+=R-v;a+=m.length;f=0;for(g=m;f<g.length;f++)B=g[f],B.geometry&&(N.isPolygon(B.geometry)?d+=B.geometry.rings.reduce(function(a,b){return a+b.length},0):N.isPolyline(B.geometry)&&(d+=
B.geometry.paths.reduce(function(a,b){return a+b.length},0)));return[2]}})})}))];case 1:return b.sent(),[2,z({},this.featureStore.storeStatistics,{displayedFeatureCount:a,displayedVertexCount:d,displayPreProcessTime:h})]}})})};c.prototype.refresh=function(){return f(this,void 0,void 0,function(){var a=this;return u(this,function(b){switch(b.label){case 0:return this._queryInfoHash=Math.random().toString(),this._dataTileIndex.clear(),this._fetchQueue.pause(),this._updateQueue.pause(),this._editsQueue.clear(),
this._fetchQueue.clear(),this._updateQueue.clear(),this.featureStore.startMarkingUsedFeatures(),this._manageTiles(this.tileStore.tiles),this._fetchQueue.resume(),[4,W.whenFalseOnce(this._fetchQueue,"updating")];case 1:return b.sent(),this.featureStore.sweep(),this.featureStore.forEach(function(b){return a.attributeStore.setAttributeData(b.localId,b,a.geometryInfo,a.viewParams)}),this.attributeStore.sendUpdates(),this._updateQueue.resume(),[2]}})})};c.prototype.setViewState=function(a){var b=this,
d=this.viewState&&this.viewState.scale;this.inherited(arguments);this._fetchQueue.state=a;this._updateQueue.state=a;d!==this.viewState.scale&&this.attributeStore.hasScaleExpr&&(this.featureStore.forEach(function(a){return b.attributeStore.setAttributeData(a.localId,a,b.geometryInfo,b.viewParams)}),this.attributeStore.sendUpdates())};c.prototype.getAggregate=function(a){return this.featureStore.getAggregate(a)};c.prototype.getAggregateValueRanges=function(){return this.featureStore.getAggregateValueRanges()};
c.prototype.onTileUpdate=function(a){this._manageTiles(a.added,a.removed);this.featureStore.onTileUpdate(a)};c.prototype.onFeatureAdd=function(a){if(this._featuresInFlight.has(a.objectId)){var b=this._featuresInFlight.get(a.objectId).attributes;a.attributes=z({},b,a.attributes);this._featuresInFlight.delete(a.objectId)}a.localId=this.attributeStore.createLocalId(a.objectId);this.attributeStore.setAttributeData(a.localId,a,this.geometryInfo,this.viewParams)};c.prototype._handleAttributeChange=function(a){return f(this,
void 0,void 0,function(){return u(this,function(b){switch(b.label){case 0:return[4,this._fetchChangedFields(a)];case 1:return b.sent(),[2]}})})};c.prototype._fetchChangedTileFields=function(a,b){return f(this,void 0,void 0,function(){var d;return u(this,function(c){return(d=this._dataTileIndex.get(a.id))?[2,this._fetchChangedTileFieldsDrill(d,b)]:[2]})})};c.prototype._fetchChangedTileFieldsDrill=function(a,b,d){void 0===d&&(d=0);return f(this,void 0,void 0,function(){var c,k,v,m,f,q,e,t,n,p,g=this;
return u(this,function(h){switch(h.label){case 0:return c=z({},this.queryInfo,{returnGeometry:!1,returnCentroid:!1,outFields:b.concat([this.service.objectIdField])}),a.returnExceeded=a.returnExceeded||d>=I,k=a.key,v={key:k,dataTile:a,queryInfo:c},[4,this._patchQueue.push(v)];case 1:m=h.sent();if(!(m.exceededTransferLimit&&d<I))return[3,3];f=a.tile.createChildTiles();q=f.map(function(b){var d=new F.default;d.tile=b;d.displayTile=a.displayTile;return d});return[4,A.all(q.map(function(a){return g._fetchChangedTileFieldsDrill(a,
b,d+1)}))];case 2:return h.sent(),[2];case 3:e=0;for(t=m.features;e<t.length;e++)n=t[e],this.featureStore.has(n.objectId)?(p=this.featureStore.getFeature(n.objectId),p.attributes=z({},p.attributes,n.attributes)):this._featuresInFlight.set(n.objectId,n);return[2]}})})};c.prototype._fetchChangedTileFieldsPaged=function(a,b,d){void 0===d&&(d=0);return f(this,void 0,void 0,function(){var c,k,v,m,f,q,e,t,n,p,g;return u(this,function(h){switch(h.label){case 0:return c=this.service.capabilities.query.supportsMaxRecordCountFactor,
k=this.service.tileMaxRecordCount,v=k*(c?1:Q),m=z({},this.queryInfo,{returnGeometry:!1,returnCentroid:!1,outFields:b.concat([this.service.objectIdField]),resultOffset:d*v,num:v}),a.returnExceeded=!0,f=a.key,q={key:f,dataTile:a,queryInfo:m},[4,this._patchQueue.push(q)];case 1:e=h.sent();t=0;for(n=e.features;t<n.length;t++)p=n[t],this.featureStore.has(p.objectId)?(g=this.featureStore.getFeature(p.objectId),g.attributes=z({},g.attributes,p.attributes)):this._featuresInFlight.set(p.objectId,p);return e.exceededTransferLimit?
[2,this._fetchChangedTileFieldsPaged(a,b,d+1)]:[2]}})})};c.prototype._fetchChangedFields=function(a){return f(this,void 0,void 0,function(){var b,d,c=this;return u(this,function(h){switch(h.label){case 0:return b=this.tileStore.tiles,d=b.map(function(b){return c._fetchChangedTileFields(b,a)}),[4,A.all(d)];case 1:return h.sent(),[2]}})})};c.prototype._manageTiles=function(a,b){void 0===b&&(b=null);for(var d=this._dataTileIndex,c=this._fetchQueue,k=this._updateQueue,v="esriGeometryPoint"===this.service.geometryType,
m=function(a){var b=d.get(a.id);b?(b.displayTile=a,v?d.forEach(function(d){G.isChildOf(d,b)&&(d.displayTile=a)}):b.done=!1):(b=new F.default,b.tile=a.clone(),b.displayTile=a,d.add(b));f._processDataTile(b)},f=this,g=0;g<a.length;g++){var e=a[g];m(e)}if(b)for(a=0;a<b.length;a++)e=b[a],J.add(e),k.abort(e.id);d.forEach(function(a){J.has(a.displayTile)&&x.push(a)});for(k=0;k<x.length;k++)e=x[k],c.abort(e.id),d.delete(e);x.length=0;J.clear()};c.prototype._processDataTile=function(a){var b=this,d=a.key,
c=this._fetchQueue,k=d.id,f=this._queryInfoHash,d=d.level-a.displayTile.key.level>=I;this._dataTileIndex.add(a);if(a.done||c.has(k)){if(a.queryInfoHash!==f||a.returnExceeded!==d)if(a.done)a.done=!1;else if(c.isOngoing(k))c.abort(k);else{a.queryInfoHash=f;a.returnExceeded=d;return}}else a.queryInfoHash=f,a.returnExceeded=d;a.done?this._invalidateTile(a.displayTile):c.has(k)||c.push(a).then(function(d){return b._handleResponse(a,d)}).catch(function(d){A.isAbortError(d)||H.error(new U("featurelayer-controller:tile-error",
"Encountered an error when handling tile response",d));a.done=!0;b._invalidateTile(a.displayTile)})};c.prototype._handleResponse=function(a,b){a.done=!0;D.hydrateOptimizedFeatureSet(b);if(b.exceededTransferLimit)if(a.returnExceeded)this._dataTileIndex.setTileFeatures(a,b.features),this._deleteChildrenDataTiles(a);else{b=a.tile.createChildTiles();for(var d=0;d<b.length;d++){var c=b[d],k=new F.default;k.tile=c;k.displayTile=a.displayTile;this._processDataTile(k)}T.release(b)}else this._dataTileIndex.setTileFeatures(a,
b.features),this._deleteChildrenDataTiles(a);this._invalidateTile(a.tile)};c.prototype._deleteChildrenDataTiles=function(a){this._dataTileIndex.forEach(function(b){G.isChildOf(b,a)&&x.push(b)});for(var b=0;b<x.length;b++){var d=x[b];this._fetchQueue.abort(d.id);this._dataTileIndex.delete(d)}x.length=0};c.prototype._fetchTile=function(a,b,d){return f(this,void 0,void 0,function(){var c,k,f,g,l,q,e,t,n,p,y;return u(this,function(h){switch(h.label){case 0:return c=new Y({xmin:a.bounds[0],ymin:a.bounds[1],
xmax:a.bounds[2],ymax:a.bounds[3],spatialReference:this.spatialReference}),k=this.service.geometryType,f="esriGeometryPoint"===k?a.tile:a.displayTile,g=f.extent,l=f.resolution,q=a.returnExceeded,e=this._createQuery(c,g,l,b,Q,q),[4,this.sourceAdapter.executeQuery(e,d)];case 1:t=h.sent();if("esriGeometryPolygon"===k)for(n=0,p=t.features;n<p.length;n++)y=p[n],y.geometry=D.removeCollinearVectices(y.geometry,y.geometry,k,!1,!1);return[2,t]}})})};c.prototype._invalidateTile=function(a){var b=this._updateQueue,
d=0;for(a=this.tileStore.intersections(a,this._pixelBuffer);d<a.length;d++){var c=a[d].tile;b.push(c.id,c.updateTimestamp)}};c.prototype._updateTile=function(a,b,d){return f(this,void 0,void 0,function(){var c,f,g,m,l,q,e,t,n,p,y,r,w=this;return u(this,function(h){switch(h.label){case 0:return c=this.tileStore.get(a),f=this.queryInfo,g=f.returnCentroid,m=f.returnGeometry,l=this._pixelBuffer,q={pixelBuffer:l,returnGeometry:m,returnCentroid:g,returnOutline:this.returnOutline},[4,this.featureStore.executeTileQuery(c,
this.spatialReference,q)];case 1:return e=h.sent(),t=e.features,n=e.objectIds,[4,this.attributeStore.sendUpdates()];case 2:return h.sent(),p={geometryType:this.service.geometryType,features:t,fields:this.service.fields,objectIdFieldName:this.service.objectIdField,transform:c.transform},y=[],r=!0,this._dataTileIndex.forEach(function(a){c.id!==a.id&&G.isChildOf(a,c)&&r&&!a.done&&(r=!1)}),r&&c&&c.objectIds.forEach(function(a){n.has(a)||(a=w.attributeStore.getLocalId(a),y.push(a))}),n.forEach(function(a){c.objectIds.add(a)}),
c.updateTimestamp=b,[2,this.processor.onTileData(c,{clear:!0,addOrUpdate:p.features,remove:y,transformParams:Z.Utils.getTransformParams(p)},d).catch(function(a){A.isAbortError(a)||H.error("update-tile",a)})]}})})};c.prototype._processEdits=function(a,b,c){return f(this,void 0,void 0,function(){var d,g,l,m,r,q=this;return u(this,function(e){switch(e.label){case 0:return d=this._createTempQueryEngine(),g=this._createObjectIdsQuery(a),a.length?[4,this.sourceAdapter.executeQuery(g)]:[3,2];case 1:l=e.sent(),
D.hydrateOptimizedFeatureSet(l),this._dataTileIndex.addOrUpdateFeatures(l.features),d.featureStore.addMany(l.features),e.label=2;case 2:return m=b.concat(a).map(function(a){return q.attributeStore.getLocalId(a)}),this._dataTileIndex.deleteFeaturesById(b),this.attributeStore.sendUpdates(),r=z({},this.queryInfo,{pixelBuffer:this._pixelBuffer,returnOutline:this.returnOutline}),this.tileStore.tiles.map(function(a){return f(q,void 0,void 0,function(){var b,e;return u(this,function(f){switch(f.label){case 0:return[4,
d.featureStore.executeTileQuery(a,this.spatialReference,r)];case 1:return b=f.sent().features,e={transform:a.transform,hasZ:!1,hasM:!1},[2,this.processor.onTileData(a,{addOrUpdate:b,remove:m,transformParams:e},c).catch(function(a){A.isAbortError(a)||H.error("update-tile",a)})]}})})}),d.destroy(),[2]}})})};c.prototype._createObjectIdsQuery=function(a){var b=this._createDefaultQuery(this.queryInfo);b.objectIds=a;return b};w([r.property()],c.prototype,"_fetchQueue",void 0);w([r.property()],c.prototype,
"_patchQueue",void 0);w([r.property()],c.prototype,"_updateQueue",void 0);w([r.property()],c.prototype,"_editsQueue",void 0);w([r.property({readOnly:!0})],c.prototype,"featureStore",void 0);w([r.property()],c.prototype,"sourceAdapter",void 0);w([r.property({readOnly:!0,dependsOn:["featureStore","service"]})],c.prototype,"queryEngine",null);w([r.property({dependsOn:["viewState","_fetchQueue.updating","_updateQueue.updating","_patchQueue.updating","_editsQueue.updating"]})],c.prototype,"updating",null);
return c=w([r.subclass("esri.views.2d.layers.features.controllers.OnDemandController")],c)}(r.declared(E.default));L.default=E});