// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/declareExtendsHelper ../../../../../core/tsSupport/decorateHelper ../../../../../core/tsSupport/assignHelper ../../../../../core/tsSupport/generatorHelper ../../../../../core/tsSupport/awaiterHelper ../../../../../core/Error ../../../../../core/has ../../../../../core/iteratorUtils ../../../../../core/maybe ../../../../../core/promiseUtils ../../../../../core/accessorSupport/decorators ../../../../../layers/graphics/featureConversionUtils ../../../../../layers/graphics/data/executeTileQuery ../../../../../layers/graphics/data/StreamStore ../../../../../layers/graphics/sources/connections/GeoEventConnection ./BaseController ./support/DispatchQueue".split(" "),
function(p,q,A,g,I,l,m,r,J,B,k,w,h,C,D,E,F,G,H){Object.defineProperty(q,"__esModule",{value:!0});p=function(n){function b(){var a=null!==n&&n.apply(this,arguments)||this;a.type="stream";a._tileDispatchMap=new Map;a._updateIntervalId=0;return a}A(b,n);b.prototype.initialize=function(){var a=this,c=this.service,b=c.objectIdField,e=c.timeInfo,d=c.maximumTrackPoints,f=c.purgeOptions;this.connection=new F.default(c.source,this.spatialReference,c.serviceFilter);this._set("store",new E.default(b,e,this.geometryInfo,
d,f));this.connection.on("feature",function(c){return a._onFeature(c)});this.store.events.on("update",function(c){return a._onUpdate(c.addOrUpdated,c.removed)});["connectionStatus","errorString"].forEach(function(c){a.watch("connection."+c,function(b){return a.remoteClient.invoke("setProperty",{propertyName:c,value:b})})});this._updateIntervalId=setInterval(function(){return a.store.checkForUpdates()},64);this._shouldPushDataReceived=this.service.enableDataRecieved};b.prototype.destroy=function(){clearInterval(this._updateIntervalId);
this.connection.destroy();this.queryEngine.destroy();this._tileDispatchMap.forEach(function(a){return a.destroy()})};Object.defineProperty(b.prototype,"queryEngine",{get:function(){return this._createQueryEngine(this.store)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"updating",{get:function(){return this._tempQueryEngine&&!!this._tempQueryEngine.featureStore.numFeatures||this._anyUpdatesQueued()},enumerable:!0,configurable:!0});b.prototype.update=function(a){return m(this,
void 0,void 0,function(){var c,b,e=this;return l(this,function(d){switch(d.label){case 0:return this.validateConfig(a),c=this.renderer.getAttributeHash(),this._set("config",a),[4,this.updatePixelBuffer()];case 1:d.sent();if("heatmap"===this.renderer.type)return[2];if(c===this.renderer.getAttributeHash())return[3,3];b=this.queryEngine.featureStore;return[4,this.attributeStore.setAttributeBindings(this.renderer,this.arcadeInfo)];case 2:d.sent(),b.forEach(function(a){return e.attributeStore.setAttributeData(a.localId,
a,e.geometryInfo,e.viewParams)}),d.label=3;case 3:return[4,this.attributeStore.updateFilters(this)];case 4:return d.sent(),[4,this.attributeStore.sendUpdates()];case 5:return d.sent(),[2]}})})};b.prototype.invalidate=function(){this._repushActiveTiles()};b.prototype.onEdits=function(){};b.prototype.queryFeatures=function(a){return this.queryEngine.executeQuery(a)};b.prototype.queryFeatureCount=function(a){return this.queryEngine.executeQueryForCount(a)};b.prototype.queryObjectIds=function(a){return this.queryEngine.executeQueryForIds(a)};
b.prototype.queryExtent=function(a){return this.queryEngine.executeQueryForExtent(a)};b.prototype.queryLatestObservations=function(a){return m(this,void 0,void 0,function(){return l(this,function(c){if(!this.service.timeInfo.trackIdField)throw r("mapview-no-trackIdField","queryLatestObservation can only be used with services that define a TrackIdField");return[2,this.queryEngine.executeQueryForLatestObservations(a)]})})};b.prototype.queryStatistics=function(){throw r("Method not implemented.");};
b.prototype.refresh=function(){};b.prototype.setViewState=function(){var a=this,c=this.viewState&&this.viewState.scale;this.inherited(arguments);c!==this.viewState.scale&&this.attributeStore.hasScaleExpr&&(this.queryEngine.featureStore.forEach(function(c){return a.attributeStore.setAttributeData(c.localId,c,a.geometryInfo,a.viewParams)}),this.attributeStore.sendUpdates())};b.prototype.onTileUpdate=function(a){var c=this,b=a.added;a.removed.forEach(function(a){return c._handleTileRemove(a)});b.forEach(function(a){return c._handleTileAdd(a)})};
b.prototype.enableEvent=function(a){"data-received"===a.name&&(this._shouldPushDataReceived=a.value)};b.prototype._onFeature=function(a){this._shouldPushDataReceived&&this.remoteClient.invoke("emitEvent",{name:"data-received",event:{attributes:a.attributes,centroid:a.centroid,geometry:a.geometry}});try{var c=this.geometryInfo,b=C.convertFromFeature(a,c.geometryType,c.hasZ,c.hasM,this.store.objectIdField);this.store.add(b)}catch(e){}};b.prototype._createStoreWithFeatures=function(a){if(k.isNone(a))return null;
var c=this._createFeatureStore();c.addMany(a);return c};b.prototype._onUpdate=function(a,c){return m(this,void 0,void 0,function(){var b,e,d=this;return l(this,function(f){switch(f.label){case 0:return k.isSome(a)&&a.forEach(function(a){return d.onFeatureAdd(a)}),b=this._createStoreWithFeatures(a),e=this._createStoreWithFeatures(c),this.attributeStore.sendUpdates(),this.processor.supportsTileUpdates?[4,this._updateActiveTiles(b,e)]:[3,2];case 1:return f.sent(),[3,3];case 2:this._repushActiveTiles(),
f.label=3;case 3:return k.isSome(c)&&c.forEach(function(a){return d.onFeatureRemove(a)}),[2]}})})};b.prototype._handleTileAdd=function(a){if(this._tileDispatchMap.has(a.id)){var b=this._tileDispatchMap.get(a.id);b.up()}else b=new H.default,this._tileDispatchMap.set(a.id,b);this._queryTileFeatures(a,!0,this.queryEngine)};b.prototype._handleTileRemove=function(a){this._tileDispatchMap.get(a.id).destroy();this._tileDispatchMap.delete(a.id)};b.prototype._anyUpdatesQueued=function(){return B.valuesOfMap(this._tileDispatchMap).some(function(a){return a.hasAction()})};
b.prototype._updateActiveTiles=function(a,b){return m(this,void 0,void 0,function(){var c,e,d=this;return l(this,function(f){switch(f.label){case 0:return c=k.applySome(a,function(a){return d._createQueryEngine(a)}),e=k.applySome(b,function(a){return d._createQueryEngine(a)}),[4,w.all(this.tileStore.tiles.map(function(a){return d._queryTileFeatures(a,!1,c,e)}))];case 1:return f.sent(),[2]}})})};b.prototype._repushActiveTiles=function(){for(var a=0,b=this.tileStore.tiles;a<b.length;a++)this._queryTileFeatures(b[a],
!0,this.queryEngine)};b.prototype._queryTileFeatures=function(a,b,h,e){return m(this,void 0,void 0,function(){var c,f,g,n,p,t,q,r,x,y,u,z,v=this;return l(this,function(d){switch(d.label){case 0:return c={hasZ:!1,hasM:!1,transform:{originPosition:"upperLeft",scale:[a.resolution,a.resolution],translate:[a.bounds[0],a.bounds[3]]}},f=this.queryInfo,g=f.returnCentroid,n=f.returnGeometry,p=this._pixelBuffer,t={returnCentroid:g,returnGeometry:n,pixelBuffer:p,returnOutline:this.returnOutline},q=this._tileDispatchMap.get(a.id),
[4,k.applySome(h,function(b){return b.featureStore.executeTileQuery(a,v.spatialReference,t)})];case 1:return r=d.sent(),x=k.mapOr(r,[],function(a){return a.features}),y=k.mapOr(e,[],function(b){return D.executeTileQueryForIds(b,a,t)}).map(function(a){return v.attributeStore.getLocalId(a)}),u=w.createResolver(),z=function(d){return m(v,void 0,void 0,function(){return l(this,function(e){switch(e.label){case 0:return[4,this.processor.onTileData(a,{addOrUpdate:x,remove:y,clear:b,transformParams:c},{signal:d})];
case 1:return e.sent(),u.resolve(),[2]}})})},q.enqueue(z),[2,u.promise]}})})};g([h.property()],b.prototype,"connection",void 0);g([h.property()],b.prototype,"service",void 0);g([h.property({readOnly:!0})],b.prototype,"store",void 0);g([h.property({readOnly:!0,dependsOn:["store","service","config"]})],b.prototype,"queryEngine",null);g([h.property()],b.prototype,"updating",null);return b=g([h.subclass("esri.views.2d.layers.features.controllers.StreamController")],b)}(h.declared(G.default));q.default=
p});