// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/generatorHelper ../../core/tsSupport/awaiterHelper ../../core/tsSupport/assignHelper ../../Graphic ../../core/Collection ../../core/Error ../../core/lang ../../core/promiseUtils ../../core/urlUtils ../../geometry/support/normalizeUtils".split(" "),function(G,l,r,t,z,A,u,e,B,w,C,D){function E(a,b,d){return t(this,void 0,void 0,function(){var q,g,c,f;return r(this,function(p){q=b.addFeatures&&b.addFeatures.length||b.updateFeatures&&b.updateFeatures.length||
b.deleteFeatures&&b.deleteFeatures.length;g=b.addAttachments&&b.addAttachments.length||b.updateAttachments&&b.updateAttachments.length||b.deleteAttachments&&b.deleteAttachments.length;if(!b||!q&&!g)throw new e(a.type+"-layer:missing-parameters","'addFeatures', 'updateFeatures', 'deleteFeatures', 'addAttachments', 'updateAttachments' or 'deleteAttachments' parameter is required");if(!a.capabilities.data.isVersioned&&d&&d.gdbVersion)throw new e(a.type+"-layer:invalid-parameter","'gdbVersion' is applicable only if the layer supports versioned data. See: 'capabilities.data.isVersioned'");
if(!a.capabilities.editing.supportsRollbackOnFailure&&d&&d.rollbackOnFailureEnabled)throw new e(a.type+"-layer:invalid-parameter","This layer does not support 'rollbackOnFailureEnabled' parameter. See: 'capabilities.editing.supportsRollbackOnFailure'");if(!a.capabilities.editing.supportsGlobalId&&d&&d.globalIdUsed)throw new e(a.type+"-layer:invalid-parameter","This layer does not support 'globalIdUsed' parameter. See: 'capabilities.editing.supportsGlobalId'");if(!a.capabilities.editing.supportsGlobalId&&
g)throw new e(a.type+"-layer:invalid-parameter","'addAttachments', 'updateAttachments' and 'deleteAttachments' are applicable only if the layer supports global ids. See: 'capabilities.editing.supportsGlobalId'");if((!d||!d.globalIdUsed)&&g)throw new e(a.type+"-layer:invalid-parameter","When 'addAttachments', 'updateAttachments' or 'deleteAttachments' is specified, globalIdUsed should be set to true");c=z({},b);c.addFeatures=u.isCollection(c.addFeatures)?c.addFeatures.toArray():c.addFeatures||[];c.updateFeatures=
u.isCollection(c.updateFeatures)?c.updateFeatures.toArray():c.updateFeatures||[];c.deleteFeatures=u.isCollection(c.deleteFeatures)?c.deleteFeatures.toArray():c.deleteFeatures||[];c.addAttachments=c.addAttachments||[];c.updateAttachments=c.updateAttachments||[];c.deleteAttachments=c.deleteAttachments||[];c.addFeatures=c.addFeatures.map(x);c.updateFeatures=c.updateFeatures.map(x);f=d&&d.globalIdUsed;c.addFeatures.forEach(function(b){return v(b,a,f)});c.updateFeatures.forEach(function(b){return v(b,
a,f)});c.deleteFeatures.forEach(function(b){return v(b,a,f)});c.addAttachments.forEach(function(b){return y(b,a)});c.updateAttachments.forEach(function(b){return y(b,a)});return[2,F(c)]})})}function v(a,b,d){if(d){if("attributes"in a&&!a.attributes[b.globalIdField])throw new e(b.type+"-layer:invalid-parameter","Feature should have 'globalId' when 'globalIdUsed' is true");if(!("attributes"in a||a.globalId))throw new e(b.type+"-layer:invalid-parameter","'globalId' of the feature should be passed when 'globalIdUsed' is true");
}}function y(a,b){var d=a.feature;a=a.attachment;if(!d||"attributes"in d&&!d.attributes[b.globalIdField])throw new e(b.type+"-layer:invalid-parameter","Attachment should have reference to a feature with 'globalId'");if(!("attributes"in d||d.globalId))throw new e(b.type+"-layer:invalid-parameter","Attachment should have reference to 'globalId' of the parent feature");if(!a.globalId)throw new e(b.type+"-layer:invalid-parameter","Attachment should have 'globalId'");if(!a.data&&!a.uploadId)throw new e(b.type+
"-layer:invalid-parameter","Attachment should have 'data' or 'uploadId'");if(!(a.data instanceof File&&a.data.name||a.name))throw new e(b.type+"-layer:invalid-parameter","'name' is required when attachment is specified as Base64 encoded string using 'data'");if(!b.capabilities.editing.supportsUploadWithItemId&&a.uploadId)throw new e(b.type+"-layer:invalid-parameter","This layer does not support 'uploadId' parameter. See: 'capabilities.editing.supportsUploadWithItemId'");if("string"===typeof a.data&&
(d=C.dataComponents(a.data))&&!d.isBase64)throw new e(b.type+"-layer:invalid-parameter","Attachment 'data' should be a Blob, File or Base64 encoded string");}function F(a){return t(this,void 0,void 0,function(){var b,d,e,g,c,f;return r(this,function(p){switch(p.label){case 0:return b=a.addFeatures,d=a.updateFeatures,e=b.concat(d).map(function(a){return a.geometry}),[4,D.normalizeCentralMeridian(e)];case 1:return g=p.sent(),c=b.length,f=d.length,g.slice(0,c).forEach(function(b,c){a.addFeatures[c].geometry=
b}),g.slice(c,c+f).forEach(function(b,c){a.updateFeatures[c].geometry=b}),[2,a]}})})}function x(a){var b=new A;a.attributes||(a.attributes={});b.geometry=a.geometry;b.attributes=a.attributes;return b}Object.defineProperty(l,"__esModule",{value:!0});l.isEditableLayer=function(a){return!0===a.get("capabilities.operations.supportsEditing")};l.applyEdits=function(a,b,d){return t(this,void 0,void 0,function(){var q,g,c,f,p,k,m,h,l;return r(this,function(n){switch(n.label){case 0:return c={edits:b,result:w.create(function(a,
b){q=a;g=b})},a.emit("apply-edits",c),[4,a.load()];case 1:n.sent();f=a.source;if(!f||null==f.applyEdits)return[2,w.reject(new e(a.type+"-layer:no-editing-support","Layer source does not support applyEdits capability",{layer:a}))];if(!a.editingEnabled)throw new e(a.type+"-layer:editing-disabled","Editing is disabled for layer",{layer:a});return[4,E(a,b,d)];case 2:p=n.sent(),n.label=3;case 3:return n.trys.push([3,5,,6]),[4,f.applyEdits(p,d)];case 4:return k=n.sent(),m=function(a){return a.filter(function(a){return!a.error}).map(B.clone)},
h={addedFeatures:m(k.addFeatureResults),updatedFeatures:m(k.updateFeatureResults),deletedFeatures:m(k.deleteFeatureResults),addedAttachments:m(k.addAttachmentResults),updatedAttachments:m(k.updateAttachmentResults),deletedAttachments:m(k.deleteAttachmentResults)},(h.addedFeatures.length||h.updatedFeatures.length||h.deletedFeatures.length||h.addedAttachments.length||h.updatedAttachments.length||h.deletedAttachments.length)&&a.emit("edits",h),q(h),[2,k];case 5:throw l=n.sent(),g(l),l;case 6:return[2]}})})}});