// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/assignHelper ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../../../Graphic ../../../core/Error ../../../core/iteratorUtils ../../../core/Logger ../../../core/maybe ../../../core/promiseUtils ../../../core/accessorSupport/decorators ../../../core/sql/WhereClause ../../../layers/support/fieldUtils ./BuildingSublayerView3D ./I3SMeshView3D ./i3s/I3SUtil ./support/DefinitionExpressionSceneLayerView ./support/fieldProperties ../../layers/support/popupUtils".split(" "),
function(I,J,K,z,d,r,t,A,u,B,C,v,w,c,D,m,E,F,x,G,H,n){var e=C.getLogger("esri.views.3d.layers.BuildingComponentSublayerView3D"),y=H.defineFieldProperties();return function(f){function b(){var a=null!==f&&f.apply(this,arguments)||this;a.layerView=null;a._elevationContext="scene";a._isIntegratedMesh=!1;a._supportsLabeling=!1;a.lodFactor=1;a.progressiveLoadFactor=1;return a}z(b,f);Object.defineProperty(b.prototype,"layerUid",{get:function(){return this.layer.layer.uid},enumerable:!0,configurable:!0});
Object.defineProperty(b.prototype,"sublayerUid",{get:function(){return this.layer.uid},enumerable:!0,configurable:!0});b.prototype.initialize=function(){var a=this;this.updatingHandles.add(this,"layer.renderer",function(){return a._updateRequiredFields()});this.updatingHandles.add(this,"definitionExpressionFields",function(){return a._updateRequiredFields()});this.updatingHandles.add(this,"filterExpressionFields",function(){return a._updateRequiredFields()});this.updatingHandles.add(this.layer,"renderer",
function(b){return a._rendererChange(b)},2);this.updatingHandles.add(this,"parsedDefinitionExpression",function(){return a._filterChange()});this.updatingHandles.add(this,"parsedFilterExpression",function(){return a._filterChange()});this.addResolvingPromise(this._updateRequiredFields())};Object.defineProperty(b.prototype,"parsedFilterExpression",{get:function(){if("Overview"===this.layer.modelName||v.isNone(this.layerView.filterExpression))return null;var a;try{a=D.WhereClause.create(this.layerView.filterExpression,
this.layer.fieldsIndex)}catch(h){return e.error("Failed to parse filterExpression: "+h),null}if(!a.isStandardized)return e.error("filterExpression is using non standard function"),null;var b=[];x.findFieldsCaseInsensitive(a.fieldNames,this.layer.fields,{missingFields:b});return 0<b.length?(e.error("filterExpression references unknown fields: "+b.join(", ")),null):a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"filterExpressionFields",{get:function(){return this.parsedFilterExpression?
x.findFieldsCaseInsensitive(this.parsedFilterExpression.fieldNames,this.layer.fields):null},enumerable:!0,configurable:!0});b.prototype._createLayerGraphic=function(a){a=new A(null,null,a);a.layer=this.layer.layer;a.sourceLayer=this.layer;return a};b.prototype.canResume=function(){return this.inherited(arguments)&&(!this._controller||this._controller.rootNodeVisible)};b.prototype.isUpdating=function(){return this.updatingMeshView3D};b.prototype.fetchPopupFeatures=function(a,b){return t(this,void 0,
void 0,function(){var a,c,d,g,e,f,p,k,q,l;return r(this,function(h){switch(h.label){case 0:if(a=this._validateFetchPopupFeatures(b))return[2,w.reject(a)];if(!v.isSome(b)||!b.clientGraphics||0===b.clientGraphics.length)return[2,[]];c=[];d=[];e=m.unpackFieldNames;f=[this.layer.fields];return[4,n.getRequiredFields(this.layer,n.getFetchPopupTemplate(this.layer,b))];case 1:g=e.apply(void 0,f.concat([h.sent()]));p=new Set;k=0;for(q=b.clientGraphics;k<q.length;k++)l=q[k],m.populateMissingFields(g,l,p)?d.push(l):
c.push(l);return 0===d.length?[2,w.resolve(c)]:[2,this.whenGraphicAttributes(d,B.valuesOfSet(p)).catch(function(){return d}).then(function(a){return c.concat(a)})]}})})};b.prototype._updateRequiredFields=function(){return t(this,void 0,void 0,function(){var a,b,d,c;return r(this,function(g){switch(g.label){case 0:return b=m.fixFields,d=[this.layer.fields],this.layer.renderer?[4,this.layer.renderer.getRequiredFields(this.layer.fields)]:[3,2];case 1:return c=g.sent(),[3,3];case 2:c=[],g.label=3;case 3:return a=
b.apply(void 0,d.concat([c.concat(this.definitionExpressionFields||[],this.filterExpressionFields||[])])),this._set("requiredFields",a),[2]}})})};b.prototype._validateFetchPopupFeatures=function(b){var a=this.layer;if(!a.popupEnabled)return new u("buildingscenelayerview3d:fetchPopupFeatures","Popups are disabled",{layer:a});if(!n.getFetchPopupTemplate(a,b))return new u("buildingscenelayerview3d:fetchPopupFeatures","Layer does not define a popup template",{layer:a})};b.prototype.getFilters=function(){var a=
this.inherited(arguments);this.addSqlFilter(a,this.parsedFilterExpression,this.filterExpressionFields,this.logError);this.addSqlFilter(a,this.parsedDefinitionExpression,this.definitionExpressionFields,this.logError);return a};d([c.property()],b.prototype,"layer",void 0);d([c.property()],b.prototype,"layerView",void 0);d([c.property({dependsOn:["updatingMeshView3D"]})],b.prototype,"updating",void 0);d([c.property({dependsOn:["_controller.rootNodeVisible"]})],b.prototype,"suspended",void 0);d([c.property({readOnly:!0,
aliasOf:"view.qualitySettings.sceneService.3dObject.lodFactor"})],b.prototype,"lodFactor",void 0);d([c.property({readOnly:!0,dependsOn:["layerView.filterExpression","layer.fieldsIndex"]})],b.prototype,"parsedFilterExpression",null);d([c.property({type:[String],readOnly:!0,dependsOn:["parsedFilterExpression"]})],b.prototype,"filterExpressionFields",null);d([c.property(y.requiredFields)],b.prototype,"requiredFields",void 0);d([c.property(y.availableFields)],b.prototype,"availableFields",void 0);return b=
d([c.subclass("esri.views.3d.layers.BuildingComponentSublayerView3D")],b)}(c.declared(G.DefinitionExpressionSceneLayerView(F.I3SMeshView3D(E))))});