// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/assignHelper ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../../../Graphic ../../../core/Collection ../../../core/maybe ../../../core/promiseUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators ./BuildingComponentSublayerView3D ./BuildingGroupSublayerView3D ./LayerView3D ./i3s/I3SUtil ./support/layerViewUpdatingProperties ../../layers/LayerView".split(" "),
function(B,C,D,q,e,r,t,m,k,f,n,p,d,u,v,w,x,y,z){return function(l){function b(){var a=null!==l&&l.apply(this,arguments)||this;a.componentLayerViews=new k;a.groupLayerViews=new k;a._abortController=n.createAbortController();a._loadingComponents=0;return a}q(b,l);Object.defineProperty(b.prototype,"filterExpression",{get:function(){var a=this.layer.activeFilterId,c=null!=a?this.layer.filters.find(function(c){return c.id===a}):null;return(c=null!=c?c.filterBlocks.find(function(a){return"solid"===a.filterMode.type}):
null)?c.filterExpression:null},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"updatingProgressValue",{get:function(){var a=this.componentLayerViews,c=this._loadingComponents+(a?a.length:0);return a.reduce(function(a,c){return a+c.updatingProgress},0)/c},enumerable:!0,configurable:!0});b.prototype.isUpdating=function(){return 0<this._loadingComponents||this.componentLayerViews&&this.componentLayerViews.some(function(a){return a.updating})};b.prototype.initialize=function(){x.checkSpatialReference(this.layer.spatialReference,
this.view.spatialReference,this.view.viewingMode);this.initializeSubLayerViews(this.layer.sublayers,this)};b.prototype.destroy=function(){this.groupLayerViews&&(this.groupLayerViews.forEach(function(a){return a.destroy()}),this.groupLayerViews=null);this.componentLayerViews&&(this.componentLayerViews.forEach(function(a){return a.destroy()}),this.componentLayerViews=null);this._abortController.abort();this._abortController=null};b.prototype.initializeSubLayerViews=function(a,c){var b=this,A=this,d=
this.view;a.forEach(function(a){if("building-group"===a.type){var g=new v({layer:a,view:d,parent:c});b.groupLayerViews.push(g);b.initializeSubLayerViews(a.sublayers,g)}else b._loadingComponents++,a.load({signal:b._abortController.signal}).then(function(){b._loadingComponents--;var g=new u({layer:a,layerView:A,view:d,parent:c});b.componentLayerViews.push(g);b.handles.add([p.init(g,"updating",function(){return b.notifyChange("updating")},!0),p.init(g,"updatingProgress",function(){return b.notifyChange("updatingProgressValue")},
!0)])})})};b.prototype.getGraphicFromIntersectorMetadata=function(a){for(var c=0,b=this.componentLayerViews.items;c<b.length;c++){var d=b[c];if(d.layer.uid===a.sublayerUid)return d.getGraphicFromIntersectorMetadata(a)}return null};b.prototype.fetchPopupFeatures=function(a,c){return t(this,void 0,void 0,function(){var b;return r(this,function(d){if(!f.isSome(c)||!c.clientGraphics||0===c.clientGraphics.length)return[2,void 0];b=this._findComponent(c.clientGraphics[0].sourceLayer);return f.isNone(b)?
[2,void 0]:[2,b.fetchPopupFeatures(a,c)]})})};b.prototype.whenGraphicBounds=function(a){var b=this._findComponent(a.sourceLayer);return f.isNone(b)?n.reject():b.whenGraphicBounds(a)};b.prototype._findComponent=function(a){return this.componentLayerViews.find(function(b){return a===b.layer})};b.prototype.highlight=function(a){a instanceof m?a=[a]:a instanceof k&&(a=a.toArray());var b=[];if(Array.isArray(a)&&0<a.length&&a[0]instanceof m){for(var d=new Map,e=0;e<a.length;e++){var f=a[e],h=d.get(f.sourceLayer);
null==h&&(h=[],d.set(f.sourceLayer,h));h.push(f)}this.componentLayerViews.forEach(function(a){var c=d.get(a.layer);c&&b.push(a.highlight(c))})}return{remove:function(){return b.forEach(function(a){return a.remove()})},pause:function(){return b.forEach(function(a){return a.pause()})},resume:function(){return b.forEach(function(a){return a.resume()})}}};b.prototype.getUsedMemory=function(){return this.componentLayerViews.reduce(function(a,b){return a+b.getUsedMemory()},0)};b.prototype.getUnloadedMemory=
function(){return this.componentLayerViews.reduce(function(a,b){return a+b.getUnloadedMemory()},0)};b.prototype.ignoresMemoryFactor=function(){return!1};e([d.property()],b.prototype,"layer",void 0);e([d.property()],b.prototype,"componentLayerViews",void 0);e([d.property()],b.prototype,"groupLayerViews",void 0);e([d.property({readOnly:!0,dependsOn:["layer.filters","layer.activeFilterId"]})],b.prototype,"filterExpression",null);e([d.property(y.updatingProgress)],b.prototype,"updatingProgress",void 0);
e([d.property({readOnly:!0})],b.prototype,"updatingProgressValue",null);return b=e([d.subclass("esri.views.3d.layers.BuildingSceneLayerView3D")],b)}(d.declared(w.LayerView3D(z)))});