// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/assignHelper ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../../../core/asyncUtils ../../../core/Logger ../../../core/promiseUtils ../../../core/promiseUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators ../../../core/libs/gl-matrix-2/mat4f64 ../../../geometry/Extent ../../../geometry/support/aaBoundingRect ./LayerView3D ./support/overlayImageUtils ./support/projectExtentUtils ../support/debugFlags ../webgl-engine/lib/RenderGeometry ../webgl-engine/lib/Texture ../webgl-engine/materials/DefaultMaterial ../../layers/LayerView ../../layers/RefreshableLayerView".split(" "),
function(v,O,z,h,A,q,m,B,C,r,w,D,f,E,x,l,F,t,G,H,I,J,K,L,M){var y=C.getLogger("esri.views.3d.layers.DynamicLayerView3D");v=function(u){function d(){var a=null!==u&&u.apply(this,arguments)||this;a.supportsDraping=!0;a.hasDraped=!0;a.fullExtentInLocalViewSpatialReference=null;a.overlayUpdating=!1;a.maximumDataResolution=null;a._images=[];a._extents=[];a.updateWhenStationary=!0;return a}z(d,u);Object.defineProperty(d.prototype,"drawingOrder",{get:function(){return this._get("drawingOrder")},set:function(a){if(a!==
this._get("drawingOrder")){this._set("drawingOrder",a);var b=new Set;this._images.forEach(function(e){e&&e.material&&(e.material.renderPriority=a,b.add(e.material.id))});0<b.size&&(this.view._stage.renderView.getDrapedRenderer().updateRenderOrder(b),this.emit("draped-data-change"))}},enumerable:!0,configurable:!0});d.prototype.initialize=function(){var a=this;this.drawingOrder=this.view.getDrawingOrder(this.layer.uid);this.addResolvingPromise(G.toViewIfLocal(this).then(function(b){return a._set("fullExtentInLocalViewSpatialReference",
b)}));this.updatingHandles.add(this,"suspended",function(){return a._suspendedChangeHandler()});this.handles.add(this.view.resourceController.scheduler.registerIdleStateCallbacks(function(){a._isScaleRangeActive()&&a.notifyChange("suspended")},function(){}));this._isScaleRangeLayer()&&this.updatingHandles.add(this.layer,"scaleRangeId",function(){return a.notifyChange("suspended")});this.updatingHandles.add(this,"fullOpacity",function(b){return a._opacityChangeHandler(b)})};d.prototype.destroy=function(){this.clear()};
d.prototype.setDrapingExtent=function(a,b,e,c,d,g){var n=this._clippedExtent(b,N);b=t.computeImageExportSize(b,n,c);g*=this.view.pixelRatio;if("imageMaxWidth"in this.layer||"imageMaxHeight"in this.layer){c=this.layer.imageMaxWidth;var f=this.layer.imageMaxHeight;if(b.width>c){var k=c/b.width;b.height=Math.floor(b.height*k);b.width=c;g*=k}b.height>f&&(k=f/b.height,b.width=Math.floor(b.width*k),b.height=f,g*=k)}c=this._extents[a];c&&l.equals(c.extent,n)&&!this._imageSizeDiffers(n,c.imageSize,b)||(this._extents[a]=
{extent:l.create(n),spatialReference:e,imageSize:b,renderLocalOrigin:d,pixelRatio:g},this.suspended||this._fetch(a))};d.prototype.getGraphicFromGraphicUid=function(){return null};d.prototype.clear=function(){for(var a=0;a<this._images.length;a++)this._clearImage(a)};d.prototype.doRefresh=function(a){return m(this,void 0,void 0,function(){var b,e;return q(this,function(c){switch(c.label){case 0:if(this.suspended)return[2];b=[];for(e=0;e<this._extents.length;e++)this._extents[e]&&b.push(this._fetch(e,
a));return[4,r.eachAlways(b)];case 1:return c.sent(),[2]}})})};d.prototype.canResume=function(){if(!this.inherited(arguments))return!1;if(this._isScaleRangeLayer()){var a=this.layer,b=a.minScale,a=a.maxScale;if(0<b||0<a){var e=this.view.scale;if(e<a||0<b&&e>b)return!1}}return!0};d.prototype.isUpdating=function(){if(this.overlayUpdating)return!0;for(var a=0,b=this._images;a<b.length;a++)if(b[a].loadingPromise)return!0;return!1};d.prototype.processResult=function(a,b,e){return m(this,void 0,void 0,
function(){return q(this,function(c){if(b instanceof HTMLImageElement||b instanceof HTMLCanvasElement)a.image=b;return[2]})})};d.prototype.findExtentInfoAt=function(a){for(var b=0,e=this._extents;b<e.length;b++){var c=e[b],d=c.extent;if((new x(d[0],d[1],d[2],d[3],c.spatialReference)).contains(a))return c}return null};d.prototype.getFetchOptions=function(){};d.prototype.redraw=function(a,b){return m(this,void 0,void 0,function(){var e=this;return q(this,function(c){switch(c.label){case 0:return[4,
B.forEach(this._images,function(c,d){return m(e,void 0,void 0,function(){return q(this,function(e){switch(e.label){case 0:return c?[4,a(c,b)]:[2];case 1:return e.sent(),this._createStageObjects(d,c.image),this.emit("draped-data-change"),[2]}})})})];case 1:return c.sent(),[2]}})})};d.prototype._imageSizeDiffers=function(a,b,e){if(!this.maximumDataResolution||H.TESTS_DISABLE_UPDATE_THRESHOLDS)return!0;var c=l.width(a)/this.maximumDataResolution.x;a=l.height(a)/this.maximumDataResolution.y;a=Math.abs(a/
b.height-a/e.height);return 1.5<Math.abs(c/b.width-c/e.width)||1.5<a?!0:!1};d.prototype._fetch=function(a,b){return m(this,void 0,void 0,function(){var e,c,d,g,f,h,k,m,p=this;return q(this,function(n){switch(n.label){case 0:if(this.suspended)return[2];e=this._extents[a];c=e.extent;d=new x(c[0],c[1],c[2],c[3],e.spatialReference);this._images[a]||(this._images[a]={texture:null,material:null,rendergeometry:null,loadingPromise:null,loadingAbortController:null,image:null,pixelData:null,renderExtent:l.create(c)});
g=this._images[a];g.loadingAbortController&&(g.loadingAbortController.abort(),g.loadingAbortController=null);if(0===d.width||0===d.height)return this._clearImage(a),[2];f=r.createAbortController();g.loadingAbortController=f;r.onAbort(b,function(){return f.abort()});h=f.signal;k=this._waitFetchReady(h).then(function(){var a=A({requestAsImageElement:!0,pixelRatio:e.pixelRatio},p.getFetchOptions(),{signal:h}),b=e.imageSize;return p.layer.fetchImage(d,b.width,b.height,a)}).then(function(a){if(w.isAborted(h))throw y.warnOnce("A call to fetchImage resolved even though the request was aborted. fetchImage should not resolve if options.signal.aborted is true."),
w.createAbortError();return p.processResult(g,a)});g.loadingPromise=k;r.always(k,function(){k===g.loadingPromise&&(g.loadingPromise=null,g.loadingAbortController=null)});m=k.then(function(){l.set(g.renderExtent,c);p._createStageObjects(a,g.image);p.notifyChange("updating");p.emit("draped-data-change")}).catch(function(a){a&&!r.isAbortError(a)&&y.error(a);p.notifyChange("updating");throw a;});this.notifyChange("updating");return[4,m];case 1:return n.sent(),[2]}})})};d.prototype._clearImage=function(a){a=
this._images[a];var b=this.view._stage;a&&(a.rendergeometry&&(b.renderView.getDrapedRenderer().removeRenderGeometries([a.rendergeometry]),a.rendergeometry=null),a.texture&&(b.remove(4,a.texture.id),a.texture=null),a.material&&(b.remove(3,a.material.id),a.material=null),a.loadingAbortController&&(a.loadingAbortController.abort(),a.loadingAbortController=null),a.loadingPromise=null,a.image=null,a.pixelData=null)};d.prototype._createStageObjects=function(a,b){var d=this.view._stage,c=this._images[a];
c.texture&&(d.remove(4,c.texture.id),c.texture=null);b?(c.texture=new J(b,"dynamicLayer",{width:b.width,height:b.height,wrap:{s:33071,t:33071}}),d.add(4,c.texture)):c.material&&(d.remove(3,c.material.id),c.material=null);!c.material&&c.texture?(c.material=new K({ambient:[1,1,1],diffuse:[0,0,0],transparent:!0,opacity:this.fullOpacity,textureId:c.texture.id,receiveSSAO:!1},"dynamicLayer"),c.material.renderPriority=this.drawingOrder,d.add(3,c.material)):c.material&&b&&c.material.setParameterValues({textureId:c.texture.id});
b=d.renderView.getDrapedRenderer();if(c.material){var f=void 0,d=this._extents[a].renderLocalOrigin;if(0===a)f=t.createGeometryForExtent(c.renderExtent,-1);else if(1===a){a=this._images[0].renderExtent;if(!a)return;f=t.createOuterImageGeometry(a,c.renderExtent,-1)}else{console.error("DynamicLayerView3D._createStageObjects: Invalid extent idx");return}a=new I(f);a.material=c.material;a.origin=d;a.transformation=E.mat4f64.create();a.name="dynamicLayer";a.uniqueName="dynamicLayer#"+f.id;b.addRenderGeometries([a]);
c.rendergeometry&&b.removeRenderGeometries([c.rendergeometry]);c.rendergeometry=a}else c.rendergeometry&&(b.removeRenderGeometries([c.rendergeometry]),c.rendergeometry=null)};d.prototype._isScaleRangeLayer=function(){return"minScale"in this.layer&&"maxScale"in this.layer};d.prototype._isScaleRangeActive=function(){return this._isScaleRangeLayer()?0<this.layer.minScale||0<this.layer.maxScale:!1};d.prototype._clippedExtent=function(a,b){if("local"!==this.view.viewingMode)return l.set(b,a);var d=this.view.basemapTerrain,
c=d.extent;return d.ready&&c?l.intersection(a,c,b):l.set(b,a)};d.prototype._opacityChangeHandler=function(a){for(var b=0,d=this._images;b<d.length;b++){var c=d[b];c&&c.material&&c.material.setParameterValues({opacity:a})}this.emit("draped-data-change")};d.prototype._suspendedChangeHandler=function(){this.suspended?(this.clear(),this.emit("draped-data-change")):this.refresh()};d.prototype._waitFetchReady=function(a){return m(this,void 0,void 0,function(){return q(this,function(b){switch(b.label){case 0:return this.updateWhenStationary?
[4,D.whenOnce(this.view,"stationary",a)]:[3,2];case 1:b.sent(),b.label=2;case 2:return[2]}})})};h([f.property()],d.prototype,"layer",void 0);h([f.property({dependsOn:["view.scale","layer.minScale","layer.maxScale"]})],d.prototype,"suspended",void 0);h([f.property({type:Boolean})],d.prototype,"supportsDraping",void 0);h([f.property({type:Boolean})],d.prototype,"hasDraped",void 0);h([f.property({value:0,type:Number})],d.prototype,"drawingOrder",null);h([f.property({readOnly:!0})],d.prototype,"fullExtentInLocalViewSpatialReference",
void 0);h([f.property()],d.prototype,"overlayUpdating",void 0);h([f.property({dependsOn:["overlayUpdating"]})],d.prototype,"updating",void 0);return d=h([f.subclass("esri.views.3d.layers.DynamicLayerView3D")],d)}(f.declared(M.RefreshableLayerView(F.LayerView3D(L))));var N=l.create();return v});