// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../../../core/tsSupport/assignHelper ../../../core/Error ../../../core/maybe ../../../core/promiseUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators ../../../layers/graphics/dehydratedFeatures ../../../renderers/support/renderingInfoUtils ../../../tasks/support/Query ./graphics/Graphics3DFeatureLikeLayerView ./graphics/QueryEngine ./support/projectExtentUtils ../../support/index".split(" "),
function(z,f,p,e,h,k,q,l,g,m,r,d,t,n,u,v,w,x,y){Object.defineProperty(f,"__esModule",{value:!0});f.FeatureLikeLayerView3D=function(f){return function(f){function a(){var b=null!==f&&f.apply(this,arguments)||this;b.controller=null;b.asyncGraphicsUpdates=!1;b.suspendResumeExtentMode="computed";b.slicePlaneEnabled=!1;b.supportsDraping=!0;b.overlayUpdating=!1;b.fullExtentInLocalViewSpatialReference=null;b.suspendResumeExtent=null;b._controllerCreated=!1;b.clippingExtent=null;b.supportsHeightUnitConversion=
!0;b.pendingController=null;b.queryEngine=null;return b}p(a,f);a.prototype.initialize=function(){var b=this;this.layer.isTable?this.addResolvingPromise(m.reject(new l("featurelayerview:table-not-supported","table feature layer can't be displayed",{layer:this.layer}))):(this._set("graphics3d",new v({owner:this,layer:this.layer,frustumVisibilityEnabled:!0,scaleVisibilityEnabled:!0,filterVisibilityEnabled:!0,timeExtentVisibilityEnabled:!0,elevationAlignmentEnabled:!0,elevationFeatureExpressionEnabled:!0,
preferredUpdatePolicy:this.asyncGraphicsUpdates?1:0,suspendResumeExtentMode:this.suspendResumeExtentMode,updateClippingExtent:function(c){return b.updateClippingExtent(c)}})),this.updatingHandles.add(this,"asyncGraphicsUpdates",function(c){b.graphics3d.graphicsCore.preferredUpdatePolicy=c?1:0}),this.updatingHandles.add(this,"suspendResumeExtentMode",function(c){b.graphics3d.suspendResumeExtentMode=c}),this.drawingOrder=this.view.getDrawingOrder(this.layer.uid),this.addResolvingPromise(this.graphics3d.setup().then(function(){return b.validateGeometryType()}).then(function(){return b.queryEngine=
new w.default({layerView:b,task:y.Task.FEATURE_QUERY_ENGINE})}).then(function(){return x.toViewIfLocal(b)}).then(function(c){return b.fullExtentInLocalViewSpatialReference=c}).then(function(){return b.initializeController()})),this.notifyChange("updating"))};a.prototype.destroy=function(){this.destroyPendingController();this.controller&&(this.controller.destroy(),this.controller=null);this.graphics3d&&(this.graphics3d.destroy(),this._set("graphics3d",null));this.queryEngine&&(this.queryEngine.destroy(),
this.queryEngine=null);this.loadedGraphics=null};a.prototype.destroyPendingController=function(){this.pendingController&&(this.pendingController.destroy(),this.pendingController=null)};Object.defineProperty(a.prototype,"drawingOrder",{set:function(b){this.graphics3d.graphicsCore.setDrawingOrder(b);this._set("drawingOrder",b)},enumerable:!0,configurable:!0});a.prototype.getRenderingInfo=function(b,c,a){(b=n.getRenderingInfo(b,{renderer:c,arcade:a}))&&b.color&&(c=b.color,c[0]/=255,c[1]/=255,c[2]/=255);
return b};a.prototype.getRenderingInfoAsync=function(b,c,a,d){return k(this,void 0,void 0,function(){return h(this,function(e){return[2,n.getRenderingInfoAsync(b,q({renderer:c,arcade:a},d))]})})};a.prototype.getGraphicFromGraphicUid=function(b){var c=this,a=null;this.loadedGraphics&&this.loadedGraphics.forEach(function(d){d.uid===b&&(a=t.hydrateGraphic(d,c.layer))});return a};Object.defineProperty(a.prototype,"graphics3DGraphics",{get:function(){return this.graphics3d?this.graphics3d.graphicsCore.graphics3DGraphics:
null},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"graphics3DGraphicsByObjectID",{get:function(){return this.graphics3d?this.graphics3d.graphicsCore.graphics3DGraphicsByObjectID:null},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"symbolUpdateType",{get:function(){return this.graphics3d?this.graphics3d.graphicsCore.symbolUpdateType:null},enumerable:!0,configurable:!0});a.prototype.whenGraphicBounds=function(b,a){return this.graphics3d?this.graphics3d.graphicsCore.whenGraphicBounds(b,
a):null};a.prototype.computeAttachmentOrigin=function(b,a){return this.graphics3d?this.graphics3d.graphicsCore.computeAttachmentOrigin(b,a):null};a.prototype.getSymbolLayerSize=function(b,a){return this.graphics3d?this.graphics3d.graphicsCore.getSymbolLayerSize(b,a):null};a.prototype.queryFeatures=function(b,a){return this.queryEngine.executeQuery(this._ensureQuery(b),g.get(a,"signal"))};a.prototype.queryObjectIds=function(b,a){return this.queryEngine.executeQueryForIds(this._ensureQuery(b),g.get(a,
"signal"))};a.prototype.queryFeatureCount=function(b,a){return this.queryEngine.executeQueryForCount(this._ensureQuery(b),g.get(a,"signal"))};a.prototype.queryExtent=function(b,a){return this.queryEngine.executeQueryForExtent(this._ensureQuery(b),g.get(a,"signal"))};a.prototype._ensureQuery=function(b){return g.isNone(b)?this.createQuery():u.from(b)};a.prototype.highlight=function(b,a){void 0===a&&(a={});return this.graphics3d.highlight(b,a,this.layer.objectIdField)};a.prototype.getStats=function(){var b=
this.graphics3d.graphicsCore.getStats();b.features=this.loadedGraphics.length;b.updating=this.updating;b.elevationUpdating=this.graphics3d.elevationAlignment.updating;b.visibilityFrustum=!this.graphics3d.frustumVisibility.suspended;b.visibilityScale=!this.graphics3d.scaleVisibility.suspended;return b};a.prototype.canResume=function(){return!this.inherited(arguments)||this.graphics3d&&this.graphics3d.suspended?!1:!0};a.prototype.isUpdating=function(){return!this.graphics3d||this.graphics3d.destroyed?
!1:!(!(!this._controllerCreated||this.controller&&this.controller.updating||this.overlayUpdating)&&this.view.basemapTerrain&&this.view.basemapTerrain.ready&&!this.graphics3d.updating)};a.prototype.initializeController=function(){return k(this,void 0,void 0,function(){var b;return h(this,function(a){switch(a.label){case 0:return[4,this.createController()];case 1:return this.pendingController=b=a.sent(),[4,b.when()];case 2:return a.sent(),this.setControllerWhenInitialized(b),[2]}})})};a.prototype.setControllerWhenInitialized=
function(b){return k(this,void 0,void 0,function(){return h(this,function(a){switch(a.label){case 0:return a.trys.push([0,2,,3]),[4,this.when()];case 1:return a.sent(),[3,3];case 2:return a.sent(),[3,3];case 3:return this._controllerCreated=!0,this.notifyChange("updating"),this.isResolved()?[4,r.whenTrueOnce(this.view,"basemapTerrain.ready")]:(this.destroyPendingController(),[2]);case 4:return a.sent(),this.pendingController=null,this.controller=b,this.loadedGraphics=b.graphics,this.notifyChange("updating"),
[2]}})})};a.prototype.updateClippingExtent=function(a){this.clippingExtent=a;if(!this.controller)return!1;switch(this.controller.type){case "stream":return!1;case "feature-tile-3d":return this.controller.extent=a,!0}};a.prototype.validateGeometryType=function(){switch(this.layer.geometryType){case "multipatch":case "multipoint":return m.reject(new l("featurelayerview3d:unsupported-geometry-type","Unsupported geometry type ${geometryType}",{geometryType:this.layer.geometryType}))}};e([d.property()],
a.prototype,"loadedGraphics",void 0);e([d.property({dependsOn:["graphics3d.suspended"]})],a.prototype,"suspended",void 0);e([d.property({dependsOn:["graphics3d.updating","controller.updating","overlayUpdating"]})],a.prototype,"updating",void 0);e([d.property()],a.prototype,"controller",void 0);e([d.property()],a.prototype,"graphics3d",void 0);e([d.property({readOnly:!0})],a.prototype,"asyncGraphicsUpdates",void 0);e([d.property({readOnly:!0})],a.prototype,"suspendResumeExtentMode",void 0);e([d.property({type:Boolean})],
a.prototype,"slicePlaneEnabled",void 0);e([d.property({aliasOf:"graphics3d.graphicsCore.hasDraped"})],a.prototype,"hasDraped",void 0);e([d.property({readOnly:!0,type:Boolean})],a.prototype,"supportsDraping",void 0);e([d.property({type:Boolean})],a.prototype,"overlayUpdating",void 0);e([d.property()],a.prototype,"drawingOrder",null);return a=e([d.subclass("esri.views.3d.layers.FeatureLikeLayerView3D")],a)}(d.declared(f))}});