// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../../../core/maybe ../../../core/promiseUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators ./LayerView3D ./graphics/Graphics3DFrustumVisibility ./graphics/Graphics3DGraphicLikeLayerView ./graphics/graphicUtils ./support/projectExtentUtils ../../layers/LayerView".split(" "),function(w,x,h,d,k,
l,m,n,g,c,p,q,r,t,u,v){return function(e){function a(){var a=null!==e&&e.apply(this,arguments)||this;a.frustumVisibility=new q;a.slicePlaneEnabled=!1;a.supportsDraping=!0;a.overlayUpdating=!1;a.suspendResumeExtent=null;a.fullExtentInLocalViewSpatialReference=null;return a}h(a,e);a.prototype.initialize=function(){var a=this;this._set("graphics3d",new r({owner:this,layer:this.layer,scaleVisibilityEnabled:!0}));this.graphics3d.setup();this.frustumVisibility.setup(this);this.setupSuspendResumeExtent();
this.updatingHandles.add(this,"fullOpacity",function(){return a.graphics3d.graphicsCore.opacityChange()});this.handles.add(this.layer.on("graphic-update",function(f){return a.graphics3d.graphicsCore.graphicUpdateHandler(f)}));var b=u.toViewIfLocal(this).then(function(f){a.fullExtentInLocalViewSpatialReference=f});b&&this.addResolvingPromise(b);this.drawingOrder=this.view.getDrawingOrder(this.layer.uid);this.handles.add(g.whenTrueOnce(this.view,"basemapTerrain.ready",function(){return a.notifyChange("updating")}))};
a.prototype.destroy=function(){this.frustumVisibility&&(this.frustumVisibility.destroy(),this._set("frustumVisibility",null));this.graphics3d&&(this.graphics3d.destroy(),this._set("graphics3d",null))};Object.defineProperty(a.prototype,"drawingOrder",{set:function(a){this.graphics3d.graphicsCore.setDrawingOrder(a);this._set("drawingOrder",a)},enumerable:!0,configurable:!0});a.prototype.fetchPopupFeatures=function(a,b){return l(this,void 0,void 0,function(){return k(this,function(a){return[2,m.isSome(b)?
b.clientGraphics:null]})})};Object.defineProperty(a.prototype,"graphics3DGraphics",{get:function(){return this.graphics3d.graphicsCore.graphics3DGraphics},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"graphics3DGraphicsByObjectID",{get:function(){return this.graphics3d?this.graphics3d.graphicsCore.graphics3DGraphicsByObjectID:null},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"symbolUpdateType",{get:function(){return this.graphics3d.graphicsCore.symbolUpdateType},
enumerable:!0,configurable:!0});a.prototype.getGraphicFromGraphicUid=function(a){return this.graphics3d.getGraphicFromGraphicUid(a)};a.prototype.whenGraphicBounds=function(a,b){return this.graphics3d.whenGraphicBounds(a,b)};a.prototype.computeAttachmentOrigin=function(a,b){return this.graphics3d?this.graphics3d.graphicsCore.computeAttachmentOrigin(a,b):null};a.prototype.getSymbolLayerSize=function(a,b){return this.graphics3d.getSymbolLayerSize(a,b)};a.prototype.queryGraphics=function(){return n.resolve(this.loadedGraphics)};
a.prototype.highlight=function(a,b){void 0===b&&(b={});return this.graphics3d.highlight(a,b)};a.prototype.getStats=function(){return{features:this.loadedGraphics.length,updating:this.updating,elevationUpdating:this.graphics3d.elevationAlignment.updating,visibilityFrustum:!this.frustumVisibility.suspended}};a.prototype.canResume=function(){return!this.inherited(arguments)||this.frustumVisibility&&this.frustumVisibility.suspended||this.graphics3d&&this.graphics3d.suspended?!1:!0};a.prototype.isUpdating=
function(){return!(!(this.overlayUpdating||this.graphics3d&&this.graphics3d.updating||this.frustumVisibility&&this.frustumVisibility.updating)&&this.view&&this.view.basemapTerrain&&this.view.basemapTerrain.ready)};a.prototype.setupSuspendResumeExtent=function(){var a=this;g.init(this.graphics3d.graphicsCore,"computedExtent",function(b){a.suspendResumeExtent=t.enlargeExtent(b,a.suspendResumeExtent,1.2);a.frustumVisibility.setExtent(a.suspendResumeExtent)},!0)};d([c.property({aliasOf:"layer.graphics"})],
a.prototype,"loadedGraphics",void 0);d([c.property({dependsOn:["frustumVisibility.suspended","graphics3d.suspended"]})],a.prototype,"suspended",void 0);d([c.property({dependsOn:["frustumVisibility.updating","graphics3d.updating","overlayUpdating"]})],a.prototype,"updating",void 0);d([c.property()],a.prototype,"layer",void 0);d([c.property({readOnly:!0})],a.prototype,"frustumVisibility",void 0);d([c.property({readOnly:!0})],a.prototype,"graphics3d",void 0);d([c.property({type:Boolean})],a.prototype,
"slicePlaneEnabled",void 0);d([c.property({aliasOf:"graphics3d.graphicsCore.hasDraped"})],a.prototype,"hasDraped",void 0);d([c.property({type:Boolean})],a.prototype,"supportsDraping",void 0);d([c.property({type:Boolean})],a.prototype,"overlayUpdating",void 0);d([c.property()],a.prototype,"drawingOrder",null);return a=d([c.subclass("esri.views.3d.layers.GraphicsLayerView3D")],a)}(c.declared(p.LayerView3D(v)))});