// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/declareExtendsHelper ../../../Graphic ../../../symbols ../../../core/Accessor ../../../core/Handles ../../../core/maybe ../../../core/accessorSupport/decorators ../../../core/accessorSupport/diffUtils ../../../core/libs/gl-matrix-2/vec3f64 ./graphics/Graphics3DCore ./i3s/I3SGeometryUtil ../support/GraphicsMap".split(" "),function(g,l,e,n,p,q,r,t,m,c,u,v,w,x,y){Object.defineProperty(l,"__esModule",{value:!0});g=
function(g){function b(a){a=g.call(this,a)||this;a.loadedGraphics=new y.GraphicsMap;a.slicePlaneEnabled=!1;a._renderingInfo={symbol:new q.PointSymbol3D};a._handles=new t;a._attachmentGraphicsByNode=new Map;return a}n(b,g);b.prototype.initialize=function(){var a=this;this._labelGraphicsCore=new w({owner:this,layer:this.layer,preferredUpdatePolicy:0,elevationFeatureExpressionEnabled:!1,graphicSymbolSupported:!1,getRenderingInfoWithoutRenderer:!0,hasZ:!0,hasM:!1});var b=this.view.labeler.addGraphicsOwner(this._labelGraphicsCore,
null,{emptySymbolLabelSupported:!0,elevationInfoOverride:{mode:"absolute-height",offset:0},disablePlacement:{logEntityDescription:"3D Object Scene Layer features"}}),d=this.view.deconflictor.addGraphicsOwner(this._labelGraphicsCore);this._labelGraphicsCore.setup({labeler:b,deconflictor:d}).then(function(){a.destroyed||a._labelGraphicsCore.startCreateGraphics()});this._handles.add([this.layer.watch("labelingInfo",function(b,d){u.diff(b,d)&&a._labelGraphicsCore.updateLabelingInfo()})])};b.prototype.destroy=
function(){this._handles&&(this._handles.destroy(),this._handles=null);null!=this._labelGraphicsCore&&(this._labelGraphicsCore.destroy(),this._labelGraphicsCore=null);this.view=null};b.prototype.addNodeMeta=function(a,b){var d=this,k=0,f=a.filteredIds,c=a.featureIds.map(function(c,e){x.boundingBoxTop(e,d.collection,a.objectHandle,h);var z={type:"point",x:h[0],y:h[1],z:h[2],spatialReference:d.view.renderSpatialReference,hasZ:!0,hasM:!1};e=b(e,a);var g=!1;m.isNone(f)?g=!0:k<f.length&&c===f[k]&&(g=!0,
k++);return{objectId:c,uid:p.generateUID(),attributes:e,visible:g,geometry:z}});this.loadedGraphics.addManyAndDeduplicate(c);this._attachmentGraphicsByNode.set(a.node.index,c)};b.prototype.setNodeMetaAttributes=function(a,b){for(var d=this._attachmentGraphicsByNode.get(a.node.index),c=0;c<d.length;c++)d[c].attributes=b(c,a);this._labelGraphicsCore.updateLabelingInfo(a.featureIds)};b.prototype.applyFilterChange=function(a){var b=this._attachmentGraphicsByNode.get(a.node.index);if(b)if(m.isNone(a.filteredIds))for(a=
0;a<b.length;a++){var d=b[a];d.visible||(d.visible=!0,f.graphic=d,f.property="visible",f.oldValue=!1,f.newValue=!0,this._labelGraphicsCore.graphicUpdateHandler(f))}else for(var c=0,e=0;e<b.length;e++){var d=b[e],g=d.visible;c<a.filteredIds.length&&d.objectId===a.filteredIds[c]?(d.visible=!0,c++):d.visible=!1;g!==d.visible&&(f.graphic=d,f.property="visible",f.oldValue=g,f.newValue=d.visible,this._labelGraphicsCore.graphicUpdateHandler(f))}};b.prototype.removeNodeMeta=function(a){this.loadedGraphics.removeManyObjectIds(a.featureIds)};
b.prototype.getRenderingInfo=function(){return this._renderingInfo};e([c.property()],b.prototype,"view",void 0);e([c.property()],b.prototype,"layer",void 0);e([c.property()],b.prototype,"collection",void 0);e([c.property()],b.prototype,"loadedGraphics",void 0);e([c.property({aliasOf:"_labelGraphicsCore.updating"})],b.prototype,"updating",void 0);e([c.property()],b.prototype,"slicePlaneEnabled",void 0);e([c.property()],b.prototype,"_labelGraphicsCore",void 0);return b=e([c.subclass("esri.views.3d.layers.I3SMeshViewLabeler")],
b)}(c.declared(r));var f={graphic:null,property:null,oldValue:null,newValue:null},h=v.vec3f64.create();l.default=g});