// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../../../core/tsSupport/assignHelper ../../../Graphic ../../../core/arrayUtils ../../../core/iteratorUtils ../../../core/Logger ../../../core/maybe ../../../core/promiseUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators ../../../core/libs/gl-matrix-2/vec3f64 ../../../geometry/support/aaBoundingBox ../../../geometry/support/aaBoundingRect ../../../geometry/support/contains ../../../layers/graphics/dehydratedFeatures ../../../layers/graphics/controllers/I3SOnDemandController ../../../layers/support/fieldUtils ../../../renderers/support/renderingInfoUtils ../../../tasks/support/Query ./LayerView3D ./graphics/Graphics3DFeatureLikeLayerView ./graphics/Graphics3DVerticalScale ./graphics/QueryEngine ./i3s/I3SUtil ./support/DefinitionExpressionSceneLayerView ./support/fieldProperties ./support/layerViewUpdatingProperties ./support/PopupSceneLayerView ../../3d/support/debugFlags ../support/GraphicsMap ../support/orientedBoundingBox ../support/projectionUtils ../../layers/LayerView ../../layers/support/FeatureFilter ../../support/Scheduler @dojo/framework/shim/Promise".split(" "),
function(S,l,T,g,n,m,U,L,V,x,W,E,F,X,d,Y,B,Z,aa,K,ba,y,M,N,ca,da,ea,fa,z,ga,ha,ia,ja,u,ka,la,G,ma,na,oa){function O(d,b){for(var a=0;a<d.length;a++)for(var c=0,t=d[a].graphics;c<t.length;c++){var e=t[c];e.attributes||(e.attributes={});if(b&&b.loadedAttributes)for(var k=0,P=b.loadedAttributes;k<P.length;k++){var h=P[k].name;b.attributeData[h]&&(e.attributes[h]=z.getCachedAttributeValue(b.attributeData[h],a))}}}var C=W.getLogger("esri.views.3d.layers.SceneLayerGraphicsView3D"),Q=ha.defineFieldProperties();
l=function(l){function b(a){a=l.call(this,a)||this;a._nodesAddedToStage=new Map;a.overlayUpdating=!1;a.supportsDraping=!0;a._queryEngine=null;a._memCache=null;a.loadedGraphics=new ka.GraphicsMap;a.progressiveLoadFactor=1;a.supportsHeightUnitConversion=!0;a._coordinatesOutsideExtentErrors=0;a._maxCoordinatesOutsideExtentErrors=20;return a}T(b,l);b.prototype.initialize=function(){var a=this;z.checkSpatialReferences(this.layer,this.view.spatialReference,this.view.viewingMode);for(var c=0,b=["layer.renderer",
"layer.labelingInfo","layer.labelsVisible","definitionExpressionFields","filter"];c<b.length;c++)this.updatingHandles.add(this,b[c],function(){return a._updateRequiredFields()});this.updatingHandles.add(this.layer,"rangeInfos",function(c){return a._rangeInfosChanged(c)},2);this.updatingHandles.add(this.layer,"renderer",function(c,b){return a._rendererChange(c,b)});this.updatingHandles.add(this,"layer.objectIdFilter",function(){return a._filterChange()});this.updatingHandles.add(this,"parsedDefinitionExpression",
function(){return a._filterChange()});this.handles.add(X.init(u,"I3S_TREE_SHOW_TILES",function(c){if(c&&!a._treeDebugger){var b=a._controller.crsIndex;(new Promise(function(a,c){S(["./support/I3STreeDebugger"],a,c)})).then(function(c){c=c.I3STreeDebugger;!a._treeDebugger&&u.I3S_TREE_SHOW_TILES&&(a._treeDebugger=new c({lv:a,view:a.view,nodeSR:b}))})}else c||!a._treeDebugger||u.I3S_TREE_SHOW_TILES||(a._treeDebugger.destroy(),a._treeDebugger=null)}));this._updateRequiredFields();this._set("graphics3d",
new da({owner:this,layer:this.layer,preferredUpdatePolicy:1,scaleVisibilityEnabled:!0,filterVisibilityEnabled:!0,timeExtentVisibilityEnabled:!1,frustumVisibilityEnabled:!1,elevationAlignmentEnabled:!0,elevationFeatureExpressionEnabled:!1,suspendResumeExtentMode:"data",dataExtent:this.layer.fullExtent,updateClippingExtent:function(c){return a._updateClippingExtent(c)}}));if(this.graphics3d.elevationAlignment)this.graphics3d.elevationAlignment.events.on("invalidate-elevation",function(c){return a._invalidateElevation(c.extent,
c.spatialReference)});this.supportsHeightUnitConversion&&(this._verticalScale=new ea({sourceSpatialReference:this.layer.spatialReference,destSpatialReference:this.view.spatialReference}));this.addResolvingPromise(this.graphics3d.setup());this.drawingOrder=this.view.getDrawingOrder(this.layer.uid);this._memCache=this.view.resourceController.memoryController.getMemCache(this.layer.uid);this._controller=new ba({layerView:this,scaleVisibilityEnabled:!1});this.when(function(){a._queryEngine=new fa.default({layerView:a,
task:oa.Task.FEATURE_QUERY_ENGINE});a.updatingHandles.add(a,"maximumNumberOfFeatures",function(c){return a._controller.featureTarget=c},2);a.updatingHandles.add(a,"suspended",function(c){c&&a._removeAllNodeData()})})};b.prototype.destroy=function(){this._treeDebugger&&(this._treeDebugger.destroy(),this._treeDebugger=null);this.graphics3d&&(this.graphics3d.destroy(),this._set("graphics3d",null));this._controller&&(this._controller.destroy(),this._controller=null);this._queryEngine&&(this._queryEngine.destroy(),
this._queryEngine=null);this._memCache.destroy();this._nodesAddedToStage=this._memCache=null};Object.defineProperty(b.prototype,"maximumNumberOfFeatures",{get:function(){var a=this.graphics3d&&this.graphics3d.graphicsCore&&this.graphics3d.graphicsCore.displayFeatureLimit;return a?a.maximumNumberOfFeatures:0},set:function(a){null!=a?(this._override("maximumNumberOfFeatures",a),this._controller.fixedFeatureTarget=!0):(this._clearOverride("maximumNumberOfFeatures"),this._controller.fixedFeatureTarget=
!1)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"maximumNumberOfFeaturesExceeded",{get:function(){return this.suspended?!1:!!this._controller&&!this._controller.leafsReached},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"hasM",{get:function(){return!1},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"hasZ",{get:function(){return!0},enumerable:!0,configurable:!0});b.prototype.whenGraphicAttributes=function(a,c){return m(this,void 0,void 0,
function(){var b,e=this;return n(this,function(t){b=function(a){for(var c=new Map,b=[],t=0;t<a.length;t++){var f=a[t],k=e._findGraphicNodeAndIndex(f),d=c.get(k.node);d||(d={node:k.node,indices:[],graphics:[]},b.push(d));d.indices.push(k.index);d.graphics.push(f)}return b};return[2,z.whenGraphicAttributes(this.layer,a,this._getObjectIdField(),c,b,{populateObjectId:!0})]})})};b.prototype.getGraphicFromGraphicUid=function(a){if(!this.loadedGraphics)return null;var c=K.hydrateGraphic(this.loadedGraphics.find(function(c){return c.uid===
a}),this.layer),b=this._getObjectIdField();if(!c||!c.attributes||!c.attributes[b])return null;c.layer=this.layer;c.sourceLayer=this.layer;return c};b.prototype.whenGraphicBounds=function(a,c){return this.graphics3d.graphicsCore.whenGraphicBounds(a,c)};b.prototype.computeAttachmentOrigin=function(a,c){return this.graphics3d.graphicsCore.computeAttachmentOrigin(a,c)};b.prototype.canResume=function(){return this.inherited(arguments)&&(!this._controller||this._controller.rootNodeVisible)};b.prototype.isUpdating=
function(){return this.overlayUpdating||this._controller&&this._controller.updating||this.graphics3d&&this.graphics3d.updating};b.prototype.getRenderingInfo=function(a,c,b){(a=M.getRenderingInfo(a,{renderer:c,arcade:b}))&&a.color&&(c=a.color,c[0]/=255,c[1]/=255,c[2]/=255);return a};b.prototype.getRenderingInfoAsync=function(a,c,b,e){return m(this,void 0,void 0,function(){return n(this,function(t){return[2,M.getRenderingInfoAsync(a,U({renderer:c,arcade:b},e))]})})};Object.defineProperty(b.prototype,
"symbolUpdateType",{get:function(){return this.graphics3d.graphicsCore.symbolUpdateType},enumerable:!0,configurable:!0});b.prototype._findGraphicNodeAndIndex=function(a){a=a.attributes[this.layer.objectIdField];for(var c=0,b=V.keysOfMap(this._nodesAddedToStage);c<b.length;c++){var e=this._nodesAddedToStage.get(b[c]),k=this._findGraphicIndex(e.bundle,a);if(0<=k)return{node:e.node,index:k}}return null};b.prototype._findGraphicIndex=function(a,c){for(var b=0;b<a.length;b++)for(var e=0,k=a[b].featureIds;e<
k.length;e++)if(k[e]===c)return b;return-1};b.prototype.highlight=function(a,c){void 0===c&&(c={});return this.graphics3d.highlight(a,c,this.layer.objectIdField)};b.prototype.addNodeData=function(a,c){if(this._nodesAddedToStage.has(a.index))C.error("I3S node "+a.id+" already added");else{var b=c.allGeometryData,e=c.attributeDataInfo;c=this._controller.crsIndex;var k=this._controller.crsVertex,d=this.view.spatialReference,h=[0,0,0],g=this._getObjectIdField(),p=[],f;if(f=this.layer.fullExtent)f=this.layer.fullExtent.clone(),
f.xmin-=.5,f.ymin-=.5,f.xmax+=.5,f.ymax+=.5,f.hasZ&&(f.zmin-=.5,f.zmax+=.5),f.hasM&&(f.mmin-=.5,f.mmax+=.5);var l=f;f=[];for(var A=[],r=0;r<b.length;r++){var n=b[r],m=n.featureDataPosition,H=m.length,x=n.geometries||[pa[H]],y=n.featureIds;l&&!aa.extentContainsCoords3D(l,m)&&(this._coordinatesOutsideExtentErrors<this._maxCoordinatesOutsideExtentErrors&&C.error("Service Error: Coordinates outside of layer extent"),this._coordinatesOutsideExtentErrors+1===this._maxCoordinatesOutsideExtentErrors&&C.error("Maximum number of errors reached. Further errors are ignored."),
this._coordinatesOutsideExtentErrors++);for(var D=0;D<x.length;D++){var v=x[D];if("points"===v.params.type){var I=[],w=y[D<y.length?D:0],z={};null!=w&&(z[g]=w);var w=null==w?L.generateUID():w,u=void 0;"Embedded"===v.type&&(u=v.params.vertexAttributes.position);for(v=0;v<u.length;v+=H){for(var q=0;q<H;q++)h[q]=m[q]+u[v+q];q=3===H;a.obb||A.push(h[0],h[1],q?h[2]:0);G.bufferToBuffer(h,k,0,J,d,0,1);var q=K.makeDehydratedPoint(J[0],J[1],q?J[2]:void 0,d),B=this.loadedGraphics.get(w);E.isSome(B)?I.push(B):
I.push({objectId:w,uid:L.generateUID(),geometry:q,attributes:z,visible:!0})}f.push.apply(f,I);p.push({featureIds:n.featureIds,graphics:I})}}}a.numFeatures=f.length;this._updateNodeMemory(a);b={bundle:p,attributeInfo:e,node:a};O(b.bundle,b.attributeInfo);0<A.length&&(e=c.isGeographic?this.view.renderSpatialReference:c,G.bufferToBuffer(A,k,0,A,e,0,A.length/3),a.obb=la.compute({data:A,size:3,offsetIdx:0,strideIdx:3}),c.isGeographic&&G.vectorToVector(a.obb.center,e,a.obb.center,c),this._controller.updateVisibility(a.index));
if(!this._controller.isGeometryVisible(a))return this._cacheNodeData(b),F.resolve();this._verticalScale&&this._verticalScale.adjust(f);this._nodesAddedToStage.set(a.index,b);this.loadedGraphics.addManyAndDeduplicate(f);this._filterNode(b);this._treeDebugger&&this._treeDebugger.update();return F.resolve()}};b.prototype.isNodeLoaded=function(a){return this._nodesAddedToStage.has(a)};b.prototype._updateNodeMemory=function(a){a.memory=4096+a.numFeatures*this.graphics3d.graphicsCore.usedMemoryPerGraphic};
b.prototype._cacheNodeData=function(a){var c=a.bundle.reduce(function(a,c){return c.graphics.reduce(function(a,c){return K.estimateSize(c)+a},512+8*c.featureIds.length+a)},1024);this._memCache.put(this._getMemCacheKey(a.node),a,c)};b.prototype._getMemCacheKey=function(a){return""+a.index};b.prototype._removeAllNodeData=function(){var a=this;this._nodesAddedToStage.forEach(function(c){c&&(a._updateNodeMemory(c.node),a._cacheNodeData(c))});this._nodesAddedToStage.clear();this._treeDebugger&&this._treeDebugger.update();
this.loadedGraphics.clear()};b.prototype.removeNodeData=function(a,c){for(;0<a.length&&!c.done;){var b=a.pop();if(b=this._removeNodeStageData(b))this._updateNodeMemory(b.node),this._cacheNodeData(b);c.madeProgress()}};b.prototype._removeNodeStageData=function(a){var c=this._nodesAddedToStage.get(a);if(!c)return null;for(var b=0,e=c.bundle;b<e.length;b++)this.loadedGraphics.removeMany(e[b].graphics);this._nodesAddedToStage.delete(a);this._treeDebugger&&this._treeDebugger.update();return c};b.prototype.loadCachedNodeData=
function(a){return F.resolve(this._memCache.pop(this._getMemCacheKey(a)))};b.prototype.addCachedNodeData=function(a,c,b){if(this._nodesAddedToStage.has(a.index))C.error("I3S node "+a.id+" already added");else{for(var e=0,d=c.bundle;e<d.length;e++)this.loadedGraphics.addManyAndDeduplicate(d[e].graphics);this._nodesAddedToStage.set(a.index,c);this._updateNodeMemory(a);this.setAttributeData(a.index,b);this._filterNode(c);this._treeDebugger&&this._treeDebugger.update();return F.resolve()}};b.prototype.getLoadedNodeIds=
function(){var a=[];this._nodesAddedToStage.forEach(function(c){return a.push(c.node.id)});return a.sort()};b.prototype.getLoadedNodes=function(){var a=[];this._nodesAddedToStage.forEach(function(c){return a.push(c.node)});return a};b.prototype.getLoadedNodeIndices=function(a){this._nodesAddedToStage.forEach(function(c,b){return a.push(b)})};b.prototype.getLoadedAttributes=function(a){if((a=this._nodesAddedToStage.get(a))&&a.attributeInfo)return a.attributeInfo.loadedAttributes};b.prototype.getAttributeData=
function(a){if((a=this._nodesAddedToStage.get(a))&&a.attributeInfo)return a.attributeInfo.attributeData};b.prototype.setAttributeData=function(a,b){if(a=this._nodesAddedToStage.get(a))a.attributeInfo=b,O(a.bundle,b),this._filterNode(a),this.graphics3d.graphicsCore.labelsEnabled&&(b=a.bundle.map(function(a){return a.graphics.length&&a.graphics[0].uid}),this.graphics3d.graphicsCore.updateLabelingInfo(b))};b.prototype._updateClippingExtent=function(a){this._controller&&this._controller.updateClippingArea(a);
return!1};b.prototype._getObjectIdField=function(){return this.layer.objectIdField||"OBJECTID"};b.prototype._rendererChange=function(a,b){return m(this,void 0,void 0,function(){var c,e,d,g;return n(this,function(h){switch(h.label){case 0:return c=this.layer.fields,e=new Set,a?[4,a.collectRequiredFields(e,c)]:[3,2];case 1:return h.sent(),d=x.valuesOfSet(e).sort(),[3,3];case 2:d=[],h.label=3;case 3:return e.clear(),b?[4,b.collectRequiredFields(e,c)]:[3,5];case 4:return h.sent(),g=x.valuesOfSet(e).sort(),
[3,6];case 5:g=[],h.label=6;case 6:if(d.length===g.length&&d.every(function(a,b){return d[b]===g[b]}))return[2];this._reloadAllNodes();return[2]}})})};b.prototype._rangeInfosChanged=function(a){null!=a&&0<a.length&&C.warn("Unsupported property: rangeInfos are currently only serialized to and from web scenes but do not affect rendering.")};b.prototype._filterChange=function(){var a=this;this._nodesAddedToStage.forEach(function(b){return a._filterNode(b)})};b.prototype._reloadAllNodes=function(){this._removeAllNodeData();
this._controller&&this._controller.restartNodeLoading()};b.prototype._filterNode=function(a){var b=this._getObjectIdField(),d=null;if(this.layer.objectIdFilter)var e=this.layer.objectIdFilter.ids,g="include"===this.layer.objectIdFilter.method,d=function(a){return 0<=e.indexOf(a)===g};var n=this.parsedDefinitionExpression,h=0;for(a=a.bundle;h<a.length;h++)for(var l=0,p=a[h].graphics;l<p.length;l++){var f=p[l],m=f.visible;d&&!d(f.attributes[b])?f.visible=!1:f.visible=n?this._evaluateClause(n,f):!0;
m!==f.visible&&(r.graphic=f,r.property="visible",r.oldValue=m,r.newValue=f.visible,this.graphics3d.graphicsCore.graphicUpdateHandler(r))}};b.prototype._updateRequiredFields=function(){return m(this,void 0,void 0,function(){var a,b,d,e,g,l,h,m,p;return n(this,function(c){switch(c.label){case 0:return a=this,d=b=a.layer,e=d.fields,g=d.renderer,l=d.labelsVisible,h=a.filter,m=a.definitionExpressionFields,p=new Set,g?[4,g.collectRequiredFields(p,e)]:[3,2];case 1:c.sent(),c.label=2;case 2:return l?[4,y.collectLabelingFields(p,
b)]:[3,4];case 3:c.sent(),c.label=4;case 4:return E.isSome(h)?[4,y.collectFilterFields(p,b,h)]:[3,6];case 5:c.sent(),c.label=6;case 6:return y.collectFields(p,e,m),this._set("requiredFields",x.valuesOfSet(p).sort()),[2]}})})};b.prototype._invalidateElevation=function(a,b){var c=this._controller.crsIndex;G.boundingRectToBoundingRect(a,b,R,c);a=qa;B.fromRect(a,R);a[2]=-Infinity;a[5]=Infinity;this._controller.updateElevationChanged(a,c)};b.prototype.createQuery=function(){var a={outFields:["*"],returnGeometry:!0,
outSpatialReference:this.view.spatialReference};return E.isSome(this.filter)?this.filter.createQuery(a):new N(a)};b.prototype.queryFeatures=function(a,b){return this._queryEngine.executeQuery(this._ensureQuery(a),b&&b.signal)};b.prototype.queryObjectIds=function(a,b){return this._queryEngine.executeQueryForIds(this._ensureQuery(a),b&&b.signal)};b.prototype.queryFeatureCount=function(a,b){return this._queryEngine.executeQueryForCount(this._ensureQuery(a),b&&b.signal)};b.prototype.queryExtent=function(a,
b){return this._queryEngine.executeQueryForExtent(this._ensureQuery(a),b&&b.signal)};b.prototype._ensureQuery=function(a){return this._addDefinitionExpressionToQuery(E.isNone(a)?this.createQuery():N.from(a))};b.prototype.getUsedMemory=function(){var a=this.graphics3d&&this.graphics3d.graphicsCore;return a?a.usedMemory:0};b.prototype.getUnloadedMemory=function(){var a=this.graphics3d&&this.graphics3d.graphicsCore;return.8*((this._controller?this._controller.unloadedMemoryEstimate:0)+(a?a.unprocessedMemoryEstimate:
0))};b.prototype.ignoresMemoryFactor=function(){return this._controller&&this._controller.fixedFeatureTarget};b.prototype.getNumberOfNodes=function(){return this._nodesAddedToStage.size};b.prototype.getNumberOfFeatures=function(){return this.loadedGraphics.length};b.prototype.getStats=function(){var a=this.graphics3d.graphicsCore.getStats();a.nodes=this.getNumberOfNodes();a.features=this.loadedGraphics.length;this._controller&&this._controller.updateStats(a);return a};g([d.property()],b.prototype,
"graphics3d",void 0);g([d.property()],b.prototype,"drawingOrder",void 0);g([d.property({aliasOf:"graphics3d.graphicsCore.hasDraped"})],b.prototype,"hasDraped",void 0);g([d.property({type:Boolean})],b.prototype,"overlayUpdating",void 0);g([d.property({type:Boolean})],b.prototype,"supportsDraping",void 0);g([d.property({type:na})],b.prototype,"filter",void 0);g([d.property()],b.prototype,"loadedGraphics",void 0);g([d.property()],b.prototype,"layer",void 0);g([d.property()],b.prototype,"_controller",
void 0);g([d.property({dependsOn:["_controller.updating","graphics3d.updating","overlayUpdating"]})],b.prototype,"updating",void 0);g([d.property({dependsOn:["_controller.rootNodeVisible"]})],b.prototype,"suspended",void 0);g([d.property(ia.updatingProgress)],b.prototype,"updatingProgress",void 0);g([d.property({aliasOf:"_controller.updatingProgress"})],b.prototype,"updatingProgressValue",void 0);g([d.property(Q.requiredFields)],b.prototype,"requiredFields",void 0);g([d.property(Q.availableFields)],
b.prototype,"availableFields",void 0);g([d.property({type:Number,dependsOn:["graphics3d.graphicsCore.displayFeatureLimit"]})],b.prototype,"maximumNumberOfFeatures",null);g([d.property({readOnly:!0,dependsOn:["suspended","_controller.leafsReached"]})],b.prototype,"maximumNumberOfFeaturesExceeded",null);g([d.property({readOnly:!0,aliasOf:"view.qualitySettings.sceneService.point.lodFactor"})],b.prototype,"lodFactor",void 0);g([d.property({readOnly:!0})],b.prototype,"hasM",null);g([d.property({readOnly:!0})],
b.prototype,"hasZ",null);return b=g([d.subclass("esri.views.3d.layers.SceneLayerGraphicsView3D")],b)}(d.declared(ga.DefinitionExpressionSceneLayerView(ja.PopupSceneLayerView(ca.LayerView3D(ma)))));var pa={2:{type:"Embedded",params:{type:"points",vertexAttributes:{position:[0,0]}}},3:{type:"Embedded",params:{type:"points",vertexAttributes:{position:[0,0,0]}}}},J=Y.vec3f64.create(),r={graphic:null,property:null,oldValue:null,newValue:null},qa=B.create(),R=Z.create();return l});