// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/promiseUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators ../../2d/engine/vectorTiles/SchemaHelper ../../2d/engine/vectorTiles/TileHandler ../../2d/engine/vectorTiles/VTLPainter3D ./LayerView3D ./TiledLayerView3D ../terrain/terrainUtils ../../layers/LayerView".split(" "),function(v,w,m,d,e,n,c,p,g,h,q,r,t,u){return function(f){function a(b){return f.call(this,
b)||this}m(a,f);a.prototype.initialize=function(){var b=this,a=this._getTileInfoSupportError(t.test.force512VTL?this.layer.tileInfo:this.layer.compatibleTileInfo256,this.layer.fullExtent);if(a)this.addResolvingPromise(e.reject(a));else{var a=n.whenTrueOnce(this.view,"basemapTerrain.tilingSchemeLocked").then(function(){var a=b.view.basemapTerrain.tilingScheme,c=a.pixelSize;b.schemaHelper=new p(c,b.view.spatialReference.isGeographic);c=256===c?b.layer.compatibleTileInfo256:b.view.spatialReference.isGeographic?
b.layer.compatibleTileInfo512:b.layer.tileInfo;if(a=b._getTileInfoCompatibilityError(c,a))throw a;b._set("tileInfo",c)}),c=e.createAbortController();this._memCache=this.view.resourceController.memoryController.getMemCache(this.layer.uid,function(a){return b.tileHandler.releaseVectorTile(a)});var d=this.view.resourceController.scheduler;this.tileHandler=new g.TileHandler(this.layer,this.view.pixelRatio,!1,null,this._memCache);var f=this.tileHandler.start({signal:c.signal,scheduler:d}),k=this.tileHandler.spriteMosaic;
k.then(function(a){return b.painter=new h.default(a,b.tileHandler.glyphMosaic)});var l=function(){b._tileHandlerController.abort();b._memCache.clear();var a=new g.TileHandler(b.layer,b.view.pixelRatio,!1,null,b._memCache),c=new AbortController,c=a.start({signal:c.signal,scheduler:d});b.updatingHandles.addPromise(e.all([c,a.spriteMosaic]).then(function(c){var d=b.tileHandler,e=b.painter;b.painter=new h.default(c[1],a.glyphMosaic);b.tileHandler=a;b.emit("data-changed");d.destroy();e&&e.dispose()}))};
this.updatingHandles.add(this,"layer.currentStyleInfo",l);this.updatingHandles.add(this,"view.pixelRatio",l);this._tileHandlerController=c;a=e.all([a,f,k]);this.addResolvingPromise(a)}};a.prototype.destroy=function(){this._memCache&&(this._memCache.destroy(),this._memCache=null);this.painter&&(this.painter.dispose(),this.painter=null);this.tileHandler&&(this.tileHandler.destroy(),this.tileHandler=null)};Object.defineProperty(a.prototype,"dataLevelRange",{get:function(){var a=this.tileInfo.lods,a=
this.levelRangeFromScaleRange(a[0].scale,a[a.length-1].scale);1===a.minLevel&&256===this.tileInfo.size[0]&&(a.minLevel=0);return a},enumerable:!0,configurable:!0});a.prototype.getStats=function(){return{memory:Math.round(this.view.basemapTerrain.getUsedMemoryForLayerView(this)/1024/1024)+" MB (included in Terrain)"}};d([c.property({aliasOf:"layer.fullExtent"})],a.prototype,"fullExtent",void 0);d([c.property()],a.prototype,"layer",void 0);d([c.property()],a.prototype,"tileInfo",void 0);d([c.property()],
a.prototype,"dataLevelRange",null);d([c.property()],a.prototype,"updatingProgressValue",void 0);return a=d([c.subclass("esri.views.3d.layers.VectorTileLayerView3D")],a)}(c.declared(r.TiledLayerView3D(q.LayerView3D(u))))});