// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/decorateHelper ../core/tsSupport/declareExtendsHelper ../core/tsSupport/generatorHelper ../core/tsSupport/awaiterHelper ../core/tsSupport/assignHelper ../core/Accessor ../core/Collection ../core/Handles ../core/Logger ../core/maybe ../core/promiseUtils ../core/watchUtils ../core/accessorSupport/decorators ./input/InputManager ./input/ViewEvents ./interactive/interactiveToolUtils ./interactive/ToolViewManagerManipulatorState".split(" "),function(D,E,h,t,u,
v,w,l,x,y,z,g,n,p,f,A,B,k,C){var q=z.getLogger("esri.views.ToolViewManager");return function(r){function d(b){var a=r.call(this,b)||this;a._handles=new y;a._creatingTool=null;a._manipulatorState=new C.default;a.tools=k.newToolCollection();a.cursor=null;a._forEachTool=function(b){if(!g.isSome(a._creatingTool)||!b(a._creatingTool))for(var c=0,e=a.tools.items;c<e.length&&!b(e[c]);c++);};return a}t(d,r);d.prototype.initialize=function(){var b=this;this._handles.add([this.view.on(B.eventTypes,function(a){b._handleInputEvent(a)},
A.ViewEventPriorities.TOOL),this.tools.on("before-add",function(a){var c=a.item;null==c||b.tools.includes(c)?a.preventDefault():null==c.created||c.created||(q.error("tools","Tool can not be added to view before it has been created"),a.preventDefault())}),this.tools.on("before-remove",function(a){b._manipulatorState.clearPointers(a.item,b._forEachTool)}),this.tools.on("change",function(){b._refreshToolWatchers()})])};d.prototype.destroy=function(){this._forEachTool(function(b){return b.destroy()});
this._handles.destroy();this._handles=null};Object.defineProperty(d.prototype,"activeTool",{set:function(b){var a=this;g.isSome(b)&&!this.view.ready?q.error("#activeTool\x3d","cannot set active tool while view is not ready"):(k.swap(this,b,function(c){a._set("activeTool",c);a._removeIncompleteTools(b);a._forEachTool(function(b){var c=g.isNone(a.activeTool)||b===a.activeTool;b.setEditableFlag&&b.setEditableFlag(1,c);c=k.areToolManipulatorsEditable(b);!g.isNone(a.activeTool)&&c||a._manipulatorState.clearPointers(b,
a._forEachTool,!c)});a._updateCursor()}),this._creatingTool!==b&&this._rejectCreatingTool())},enumerable:!0,configurable:!0});d.prototype.createTool=function(b,a,c){return v(this,void 0,void 0,function(){var d,e,f,h=this;return u(this,function(m){switch(m.label){case 0:return[4,this.view.whenReady()];case 1:return m.sent(),d=k.evaluateToolConstructorArguments(a),e=new b(w({},d,{view:this.view})),f=n.onAbort(c,function(){return h.activeTool=null}),this._rejectCreatingTool("Tool creation was interrupted by another tool being created"),
this._creatingTool=e,e.attach(),this._refreshToolWatchers(),k.setActive(e,!0),[4,e.when()];case 2:return m.sent(),g.isSome(f)&&f.remove(),this._creatingTool=null,this.tools.add(e),e instanceof l&&null!=e.completed&&p.whenOnce(e,"completed").then(function(){k.setActive(e,!1)}),[2,e]}})})};d.prototype.attach=function(){var b=this;this._forEachTool(function(a){return a.attach()});"3d"===this.view.type?this._handles.add([this.view.state.watch("camera",function(){b.forEachManipulator(function(a){if(null!=
a.onViewChange)a.onViewChange()})}),this.view.elevationProvider.on("elevation-change",function(a){b.forEachManipulator(function(b){if(null!=b.onElevationChange)b.onElevationChange(a)})})],"manipulators"):this._handles.add(this.view.watch("extent",function(){b.forEachManipulator(function(a){if(null!=a.onViewChange)a.onViewChange()})}))};d.prototype.detach=function(){this.activeTool=null;this._forEachTool(function(b){b.detach();b.destroy()});this.tools.removeAll();this._handles.remove("manipulators")};
d.prototype.forEachManipulator=function(b){this._forEachTool(function(a){a.manipulators&&a.manipulators.forEach(function(c){return b(c.manipulator,a)})})};d.prototype._handleInputEvent=function(b){var a=this;g.isSome(this.activeTool)?this.activeTool.handleInputEvent&&this.activeTool.handleInputEvent(b):this._forEachTool(function(a){!1!==a.visible&&a.handleInputEvent&&a.handleInputEvent(b)});"key-down"===b.type&&"Escape"===b.key&&this.activeTool&&(b.stopPropagation(),this.activeTool=null);this._manipulatorState.handleInputEvent(b,
{forEachTool:this._forEachTool,activeTool:this.activeTool,setActiveTool:function(b){a.activeTool=b},creatingTool:this._creatingTool,view:this.view});this._manipulatorState.handleHoverEvent(b,this._forEachTool);this._updateCursor()};d.prototype._refreshToolWatchers=function(){var b=this;this._handles.remove("tools");this._updateCursor();this._forEachTool(function(a){if(a instanceof l){var c=p.watch(a,["cursor","visible","editable"],function(){k.areToolManipulatorsEditable(a)||b._manipulatorState.clearPointers(a,
b._forEachTool);b._updateCursor()});b._handles.add(c,"tools")}a.manipulators&&b._handles.add(a.manipulators.on("change",function(c){c.removed.forEach(function(c){b._manipulatorState.clearPointers(a,b._forEachTool,!0,c.id)});b._updateCursor()}),"tools")})};d.prototype._updateCursor=function(){var b=null;this._forEachTool(function(a){return null!=a.cursor&&!1!==a.visible?(b=a.cursor,!0):!1});b||(b=this._manipulatorState.cursor);this._get("cursor")!==b&&this._set("cursor",b)};d.prototype._rejectCreatingTool=
function(b){var a=this._creatingTool;g.isNone(a)||(this._manipulatorState.clearPointers(a,this._forEachTool),a.rejectCreation&&a.rejectCreation(n.createAbortError(b)),a.destroy(),this._creatingTool=null,this._refreshToolWatchers())};d.prototype._removeIncompleteTools=function(b){var a=this;this.tools.filter(function(a){return(g.isNone(b)||a!==b)&&null!=a.completed&&!a.completed}).forEach(function(b){a.tools.remove(b)})};h([f.property({constructOnly:!0,nonNullable:!0})],d.prototype,"view",void 0);
h([f.property({value:null})],d.prototype,"activeTool",null);h([f.property({readOnly:!0,type:x})],d.prototype,"tools",void 0);h([f.property({readOnly:!0})],d.prototype,"cursor",void 0);return d=h([f.subclass("esri.views.ToolViewManager")],d)}(f.declared(l))});