// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/assignHelper ../../../../../core/tsSupport/extendsHelper ../../../../../core/tsSupport/decorateHelper ../../../../../core/Logger ../../../../../core/maybe ../../../../../core/typedArrayUtil ../../../../../core/libs/gl-matrix-2/mat3 ../../../../../core/libs/gl-matrix-2/mat3f32 ../../../../../core/libs/gl-matrix-2/vec3 ../../../../../core/libs/gl-matrix-2/vec3f64 ../../../../../core/libs/gl-matrix-2/vec4f32 ../../../../../geometry/support/aaBoundingBox ../../../layers/support/symbolColorUtils ../../../support/orientedBoundingBox ../../../support/buffer/BufferView ../../../support/buffer/glUtil ../../../support/buffer/InterleavedLayout ./interface ./RenderSubmitSystem ./SourceGeometry ./IndexRange/ComponentRangeRunLengthEncoded ./Material/ComponentMaterial ./Material/ComponentTechnique ../../core/util/BucketedObjectStore ../../core/util/TwoVectorPosition ../../lib/AutoDisposable ../../lib/geometryDataUtils ../../lib/Util ../../lib/TextureBackedBuffer/BufferManager ../../materials/internal/MaterialUtil ../../../../webgl/BufferObject ../../../../webgl/VertexArrayObject".split(" "),
function(G,v,na,x,y,P,l,Q,t,H,p,C,R,S,T,U,V,I,W,X,Y,Z,aa,z,ba,J,ca,g,da,ea,fa,D,E,ga){function ha(c,a,b){var d=[],e=b.length;a.forEachComponent(function(a){0<c[a]&&(e!==a-1&&(d.length&&d.push(b[e+1]-d[d.length-1]),d.push(b[a])),e=a);return!0});d.length&&d.push(b[e+1]-d[d.length-1]);return d}Object.defineProperty(v,"__esModule",{value:!0});var K=P.getLogger("esri.views.3d.webgl-engine.collections.Component.ComponentObjectCollection");G=function(){function c(a){this._renderManager=a;this._objects=new J.BucketedObjectStore;
this._renderSubmit=new Y.RenderSubmitSystem(this);this._renderManager.register(this._renderSubmit);this._componentBufferManager=new fa.BufferManager(a.rctx)}c.prototype.dispose=function(){ea.assert(0===this.count,"ObjectCollection should be empty upon disposal")};c.prototype.createObject=function(a){var b=new L;b.transform=a.transform;b.obb=U.clone(a.obb);b.components=new ia(this._componentBufferManager,a.geometry.componentOffsets);b.renderable=this._createRenderable(a,b.components);b.intersectionGeometry=
new ja(a.geometry.positionData,b.components);this._objects.add(a.visible?u:0,b);return b};c.prototype.destroyObject=function(a){this._objects.remove(a);a.dispose();this._notifyDirty()};c.prototype.setObjectVisibility=function(a,b){b!==a.visible&&(this._objects.updateKey(a,b?a.bucketKey|u:a.bucketKey&~u),this._notifyDirty())};Object.defineProperty(c.prototype,"count",{get:function(){return this._objects.count},enumerable:!0,configurable:!0});c.prototype.preRenderUpdate=function(a){var b=a.camera.eye;
this._objects.forEach(function(a,e){e&u&&a.forEach(function(a){var d=p.vec3.squaredDistance(b,a.transform.position);a.renderable.meta.cameraDepthSquared=d})})};c.prototype.updateMaterial=function(a,b){a=a.renderable.material;b(a);a.dirty&&this._notifyDirty()};c.prototype.setAllComponentVisibilities=function(a,b){a.components.visibility.reset(b);a.components.visibilityDirty();this._notifyDirty()};c.prototype.forEachVisibleComponent=function(a,b){return a.components.visibility.forEachComponent(b)};
c.prototype.getComponentCount=function(a){var b=a.components.visibility.componentCount();return{visible:b,invisible:a.components.count-b}};c.prototype.setComponentData=function(a,b){var d=a.renderable.material;if(X.isVaryingComponentParameters(b)){a=a.components;for(var e=a.materialDataBuffer,c=a.materialDataIndices,h={castShadows:!0,externalColor:R.vec4f32.create(),externalColorMixMode:1},e=e.textureBuffer,f=new Uint8Array(4),l=new Uint32Array(f.buffer),m=0,k=0,q=0,n=0,p=!1,g=0,w=0;w<a.count;w++)b(w,
h),m+=+(1>h.externalColor[3]),k+=+(3===h.externalColorMixMode&&1===h.externalColor[3]),q+=+(0<h.externalColor[3]),n+=+h.castShadows,T.encodeSymbolColor(h.externalColor,h.externalColorMixMode,f),f[2]=f[2]&254|+h.castShadows,e.setData(c[w],0,f[0],f[1],f[2],f[3]),p=p||0<w&&g!==l[0],g=l[0];p?(d.componentParameters=new z.ComponentParametersVarying,d.componentParameters.castShadows=n===a.count?0:0===n?2:1,d.componentParameters.transparent=m===a.count?0:0===m?2:1,d.componentParameters.opaqueOverride=k===
a.count?0:0===k?2:1,d.componentParameters.visible=q===a.count?0:0===q?2:1,d.componentParameters.texture=e,e.updateTexture()):(d.componentParameters=new z.ComponentParametersUniform,d.componentParameters.castShadows=h.castShadows?0:2,d.componentParameters.externalColor=h.externalColor,d.componentParameters.externalColorMixMode=h.externalColorMixMode)}else d.componentParameters=new z.ComponentParametersUniform,d.componentParameters.castShadows=b.castShadows?0:2,d.componentParameters.externalColor=b.externalColor,
d.componentParameters.externalColorMixMode=b.externalColorMixMode;this._notifyDirty()};c.prototype.getComponentAABB=function(a,b,d){return a.intersectionGeometry.getComponentAABB(b,d)};c.prototype.getObjectTransform=function(a){return a.transform};c.prototype.getComponentPositions=function(a,b,d){return a.intersectionGeometry.getComponentPositions(b,d)};c.prototype.intersect=function(a,b,d,c,r,h){l.isSome(r)&&(r.localOrigin=a.transform.position);var e=t.mat3.invert(M,a.transform.rotationScale);p.vec3.sub(A,
b,a.transform.position);p.vec3.sub(B,d,a.transform.position);p.vec3.transformMat3(A,A,e);p.vec3.transformMat3(B,B,e);b=t.mat3.transpose(M,e);return a.intersectionGeometry.intersect(A,B,c,b,r,h)};c.prototype.addEdges=function(a,b,d,c){return b.addComponentObject(a,a.transform,a.obb.center,a.intersectionGeometry.positions,a.intersectionGeometry.indices,a.components.offsets,d,c)};c.prototype.addComponentHighlight=function(a,b){a=a.components;l.isNone(a.highlightCounts)&&(a.highlightCounts=new Uint32Array(a.count+
1));0===a.highlightCounts[b]++&&(a.highlightsDirty(),this._notifyDirty());a.highlightCounts[a.count]++};c.prototype.removeComponentHighlight=function(a,b){a=a.components;if(l.isNone(a.highlightCounts))K.warn("Removing non-existing highlight.");else{var d=a.highlightCounts[b],c=a.highlightCounts[a.count];0===d?K.warn("Removing non-existing highlight."):1<d?(a.highlightCounts[b]=d-1,a.highlightCounts[a.count]=c-1):(a.highlightCounts[b]=0,a.highlightsDirty(),this._notifyDirty(),1===c?a.highlightCounts=
null:a.highlightCounts[a.count]=c-1)}};c.prototype.clearHighlights=function(a){a=a.components;l.isSome(a.highlightCounts)&&(a.highlightCounts=null,a.highlightsDirty(),this._notifyDirty())};c.prototype.getObjectMemoryUsageGPU=function(a){return a.renderable.meta.gpuMemoryEstimate};Object.defineProperty(c.prototype,"visibleObjects",{get:function(){return this._objects.getBucket(u)},enumerable:!0,configurable:!0});c.prototype._createRenderable=function(a,b){for(var d=this._renderManager.rctx,c=a.geometry,
r=c.vertices.layoutParameters,h=E.createVertex(d,35044,c.vertices.data),f=l.applySome(c.indices,function(a){return E.createIndex(d,35044,a)}),F=I.glLayout(Z.createVertexBufferLayout(r)),m=new Uint16Array(c.vertices.count),k=0;k<b.count;k++){var q=b.offsets[k],n=b.offsets[k+1],g=b.materialDataIndices[k];if(l.isSome(c.indices))for(;q<n;q++)m[c.indices[q]]=g;else for(;q<n;q++)m[q]=g}b=E.createVertex(d,35044,m.buffer);k=new ca.TwoVectorPosition(a.transform.position);n=H.mat3f32.clone(a.transform.rotationScale);
t.mat3.invert(n,n);t.mat3.transpose(n,n);m=new ba.ComponentDrawParameters;p.vec3.copy(m.worldFromModel_TL,k.low);p.vec3.copy(m.worldFromModel_TH,k.high);t.mat3.copy(m.worldFromModel_RS,a.transform.rotationScale);t.mat3.copy(m.transformNormal_GlobalFromModel,n);a=new z.ComponentMaterial;F=new ga(d,a.attributeLocations,{data:F,componentIndices:ka},{data:h,componentIndices:b},l.unwrap(f));k=new N;k.material=a;k.drawParameters=m;k.geometry=new O(F,c.primitiveType,r,l.isSome(f));k.meta.cameraDepthSquared=
.5;k.meta.gpuMemoryEstimate=h.byteSize+b.byteSize+(l.isSome(f)?f.byteSize:0);return k};c.prototype._notifyDirty=function(){this._renderManager.notifyDirty()};return c}();v.ComponentObjectCollection=G;var ia=function(c){function a(a,d){var b=c.call(this)||this;b.highlightCounts=null;b.cachedGeometryRanges=null;b.cachedHighlightRanges=null;b.offsets=Q.slice(d);d=b.count;b.visibility=new aa.ComponentRangeRunLengthEncoded(d);b.materialDataBuffer=a.getBuffer(d);b.materialDataIndices=new Uint16Array(d);
for(a=0;a<d;a++)b.materialDataIndices[a]=b.materialDataBuffer.acquireIndex();return b}x(a,c);a.prototype.dispose=function(){c.prototype.dispose.call(this);for(var a=0;a<this.count;a++)this.materialDataBuffer.releaseIndex(this.materialDataIndices[a])};Object.defineProperty(a.prototype,"count",{get:function(){return this.offsets.length-1},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"geometryRanges",{get:function(){l.isNone(this.cachedGeometryRanges)&&(this.cachedGeometryRanges=
this.visibility.computeOffsetRanges(this.offsets));return this.cachedGeometryRanges},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"highlightRanges",{get:function(){if(l.isNone(this.highlightCounts))return null;l.isNone(this.cachedHighlightRanges)&&(this.cachedHighlightRanges=ha(this.highlightCounts,this.visibility,this.offsets));return this.cachedHighlightRanges},enumerable:!0,configurable:!0});a.prototype.highlightsDirty=function(){this.cachedHighlightRanges=null};a.prototype.visibilityDirty=
function(){this.cachedHighlightRanges=this.cachedGeometryRanges=null};return a}(g.AutoDisposable),ja=function(){function c(a,b){this._indices=l.isSome(a.indices)?a.indices:da.generateDefaultIndexArray(a.positions.length/3);this._positions=new V.BufferViewVec3f(a.positions);this._components=b}c.prototype.getComponentAABB=function(a,b){if(l.isSome(this._perComponentAABBs)){for(var c=0;6>c;c++)b[c]=this._perComponentAABBs[6*a+c];return b}this._computePerComponentAABBs();return this.getComponentAABB(a,
b)};c.prototype.getComponentPositions=function(a,b){b.indices=this._indices;b.data=this._positions.typedBuffer;b.stride=this._positions.typedBufferStride;b.startIndex=this._components.offsets[a];b.endIndex=this._components.offsets[a+1]};c.prototype.intersect=function(a,b,c,e,r,h){var d=this,g={data:this._positions.typedBuffer,strideIdx:this._positions.typedBufferStride,offsetIdx:0,size:3},m=this._indices,k=this._components.offsets,q=D.computeInvDir(a,b,la);this._components.visibility.forEachComponent(function(f){var n=
d.getComponentAABB(f,ma);l.isSome(r)&&r.applyToAABB(n);if(!D.intersectAabbInvDir(n,a,q,c))return!0;D.intersectTriangles(a,b,k[f]/3,k[f+1]/3,m,g,void 0,r,function(a,b,c){return h(f,a,p.vec3.transformMat3(b,b,e),c)});return!0})};c.prototype._computePerComponentAABBs=function(){var a=this._components.count;this._perComponentAABBs=new Float32Array(6*a);for(var b=0;b<a;b++)this._computeAABB(b)};c.prototype._computeAABB=function(a){for(var b=this._indices,c=this._positions,e=this._components.offsets,l=
e[a+1],h=[0,0,0],f=[Infinity,Infinity,Infinity],g=[-Infinity,-Infinity,-Infinity],e=e[a];e<l;e++)c.getVec(b[e],h),p.vec3.min(f,f,h),p.vec3.max(g,g,h);a*=6;this._perComponentAABBs[a++]=f[0];this._perComponentAABBs[a++]=f[1];this._perComponentAABBs[a++]=f[2];this._perComponentAABBs[a++]=g[0];this._perComponentAABBs[a++]=g[1];this._perComponentAABBs[a]=g[2]};Object.defineProperty(c.prototype,"positions",{get:function(){return this._positions},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,
"indices",{get:function(){return this._indices},enumerable:!0,configurable:!0});return c}(),O=function(c){function a(a,d,e,g){var b=c.call(this)||this;b.vao=a;b.primitiveType=d;b.parameters=e;b.indexed=g;return b}x(a,c);y([g.autoDispose()],a.prototype,"vao",void 0);return a}(g.AutoDisposable);v.RenderGeometry=O;var N=function(c){function a(){var a=null!==c&&c.apply(this,arguments)||this;a.meta={cameraDepthSquared:0,gpuMemoryEstimate:0};return a}x(a,c);y([g.autoDispose()],a.prototype,"geometry",void 0);
return a}(g.AutoDisposable);v.Renderable=N;var ka=I.glLayout(W.newLayout().u16("componentIndex")),L=function(c){function a(){return null!==c&&c.apply(this,arguments)||this}x(a,c);Object.defineProperty(a.prototype,"visible",{get:function(){return!!(this.bucketKey&u)},enumerable:!0,configurable:!0});y([g.autoDispose()],a.prototype,"renderable",void 0);y([g.autoDispose()],a.prototype,"components",void 0);return a}(J.BucketStorable);v.ComponentObject=L;var M=H.mat3f32.create(),la=C.vec3f64.create(),A=
C.vec3f64.create(),B=C.vec3f64.create(),ma=S.create(),u=1});