// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/tsSupport/assignHelper ../../core/tsSupport/generatorHelper ../../core/tsSupport/awaiterHelper ../../geometry ../../core/Collection ../../core/Error ../../core/Handles ../../core/Logger ../../core/maybe ../../core/promiseUtils ../../core/watchUtils ../../core/accessorSupport/decorators ../../geometry/support/webMercatorUtils ../../support/actions/ActionBase ../../support/actions/ActionButton ../../support/actions/ActionToggle ../../views/input/InputManager ../../views/support/layerViewUtils ./actions ../support/AnchorElementViewModel ../support/GoTo".split(" "),
function(L,M,v,d,w,x,y,z,A,m,B,C,t,k,l,e,D,E,F,G,H,I,g,J,K){var r=A.ofType({key:"type",defaultKeyValue:"button",base:E,typeMap:{button:F,toggle:G}}),n=C.getLogger("esri.widgets.Popup.PopupViewModel");return function(u){function b(a){a=u.call(this,a)||this;a._handles=new B;a._pendingPromises=new Set;a._zoomToLocation=null;a._fetchFeaturesController=null;a.actions=new r([g.zoomToFeature.clone()]);a.defaultPopupTemplateEnabled=!1;a.autoCloseEnabled=!1;a.autoOpenEnabled=!0;a.content=null;a.highlightEnabled=
!0;a.title=null;a.updateLocationEnabled=!1;a.view=null;a.visible=!1;a.zoomFactor=4;return a}v(b,u);b.prototype.initialize=function(){var a=this;this._handles.add([l.init(this,["autoOpenEnabled","view"],this._autoOpenEnabledChange),this.on("view-change",this._autoClose),l.watch(this,["highlightEnabled","selectedFeature","visible","view"],this._highlightFeature),l.watch(this,"view.animation.state",function(c){a._zoomToLocation||(g.zoomToFeature.disabled="waiting-for-target"===c)}),l.watch(this,"location",
function(c){var b=a.selectedFeature;a.updateLocationEnabled&&c&&(!b||b.geometry)&&a.centerAtLocation()}),l.watch(this,"selectedFeature",function(c){if(c){var b=a.location,h=a.updateLocationEnabled,e=a.view;!h&&b||!c.geometry?h&&!c.geometry&&a.centerAtLocation().then(function(){a.location=e.center.clone()}):a.location=t.unwrap(a._getPointFromGeometry(c.geometry))}}),this.on("trigger-action",function(c){return g.triggerAction({event:c,view:a.view})})])};b.prototype.destroy=function(){this._cancelFetchingFeatures();
this._handles.destroy();this._handles=null;this._pendingPromises.clear();this.view=null};Object.defineProperty(b.prototype,"allActions",{get:function(){var a=this._get("allActions")||new r;a.removeAll();var c=this.selectedFeature&&("function"===typeof this.selectedFeature.getEffectivePopupTemplate&&this.selectedFeature.getEffectivePopupTemplate(this.defaultPopupTemplateEnabled)||this.selectedFeature.popupTemplate),b=c&&c.actions;(c=c&&c.overwriteActions?b:b?b.concat(this.actions):this.actions)&&c.filter(Boolean).forEach(function(c){return a.add(c)});
return a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"featureCount",{get:function(){return this.features.length},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"features",{get:function(){return this._get("features")||[]},set:function(a){a=a||[];this._set("features",a);var c=this.pendingPromisesCount,b=this.selectedFeatureIndex,h=this.promiseCount&&a.length;h&&c&&-1===b?this.selectedFeatureIndex=0:h&&-1!==b||(this.selectedFeatureIndex=a.length?0:-1)},enumerable:!0,
configurable:!0});Object.defineProperty(b.prototype,"location",{get:function(){return this._get("location")||null},set:function(a){var c=this.get("view.spatialReference.isWebMercator");a&&a.get("spatialReference.isWGS84")&&c&&(a=D.geographicToWebMercator(a));this._set("location",a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"pendingPromisesCount",{get:function(){return this._pendingPromises.size},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"waitingForResult",
{get:function(){return 0<this.pendingPromisesCount&&0===this.featureCount},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"promiseCount",{get:function(){return this.promises.length},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"promises",{get:function(){return this._get("promises")||[]},set:function(a){var c=this;this._pendingPromises.clear();this.features=[];Array.isArray(a)&&a.length?(this._set("promises",a),a=a.slice(0),a.forEach(function(a){c._pendingPromises.add(a);
a.then(function(b){c._pendingPromises.has(a)&&c._updateFeatures(b);c._updatePendingPromises(a)},function(){return c._updatePendingPromises(a)})})):this._set("promises",[]);this.notifyChange("pendingPromisesCount")},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"selectedFeature",{get:function(){var a=this.selectedFeatureIndex;return-1===a?null:this.features[a]||null},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"selectedFeatureIndex",{get:function(){var a=this._get("selectedFeatureIndex");
return"number"===typeof a?a:-1},set:function(a){var c=this.featureCount;a=isNaN(a)||-1>a||!c?-1:(a+c)%c;this._set("selectedFeatureIndex",a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"state",{get:function(){return this.get("view.ready")?"ready":"disabled"},enumerable:!0,configurable:!0});b.prototype.centerAtLocation=function(){var a=this.view,c=this._getSelectedTarget();return c?this.callGoTo({target:{target:c,scale:a.scale}}):(a=new m("center-at-location:invalid-target-or-view",
"Cannot center at a location without a target and view.",{target:c,view:a}),n.error(a),k.reject(a))};b.prototype.clear=function(){this.set({promises:[],features:[],content:null,title:null,location:null})};b.prototype.open=function(a){var c=this;a=w({updateLocationEnabled:!1,promises:[],fetchFeatures:!1,visible:!1},a);var b=a.fetchFeatures;delete a.fetchFeatures;b=b?this._fetchFeatures(a.location||this.location):k.resolve();this.set(a);b.then(function(){c._setVisibleWhenContentExists()})};b.prototype.triggerAction=
function(a){(a=this.allActions.getItemAt(a))&&this.emit("trigger-action",{action:a})};b.prototype.next=function(){this.selectedFeatureIndex+=1;return this};b.prototype.previous=function(){--this.selectedFeatureIndex;return this};b.prototype.zoomToLocation=function(){var a=this,c=this.location,b=this.selectedFeature,h=this.view,e=this.zoomFactor,d=this._getSelectedTarget();if(!d)return c=new m("zoom-to:invalid-target-or-view","Cannot zoom to location without a target and view.",{target:d,view:h}),
n.error(c),k.reject(c);var h=h.scale/e,p=this.get("selectedFeature.geometry")||c,q=p&&"point"===p.type&&this._isScreenSize(b);g.zoomToFeature.active=!0;g.zoomToFeature.disabled=!0;return this._zoomToLocation=c=this.callGoTo({target:{target:d,scale:q?h:void 0}}).then(function(){q&&(a.location=p);g.zoomToFeature.active=!1;g.zoomToFeature.disabled=!1;a._zoomToLocation=null}).catch(function(){g.zoomToFeature.active=!1;g.zoomToFeature.disabled=!1;a._zoomToLocation=null})};b.prototype._getSelectedTarget=
function(){var a=this.selectedFeature,b=this.location,f=this.view;if(!f)return null;var f="3d"===f.type,h=this.get("selectedFeature.geometry");return f?a||b:h||b};b.prototype._fetchPopupFeatures=function(a){var b=this.view;this._cancelFetchingFeatures();if(!b||!a)return a=new m("fetch-features:invalid-screenPoint-or-view","Cannot fetch features without a screenPoint and view.",{screenPoint:a,view:b}),n.error(a),k.reject(a);var f=k.createAbortController();this._fetchFeaturesController=f;return b.fetchPopupFeatures(a,
{defaultPopupTemplateEnabled:this.defaultPopupTemplateEnabled,signal:f.signal})};b.prototype._autoOpenEnabledChange=function(){var a=this,b=this._handles,f=this.autoOpenEnabled;b.remove("auto-fetch-features");f&&this.view&&(f=this.view.on("click",function(b){"mouse"===b.pointerType&&0!==b.button||a._fetchFeaturesAndOpen(b)},H.ViewEventPriorities.WIDGET),b.add(f,"auto-fetch-features"))};b.prototype._cancelFetchingFeatures=function(){var a=this._fetchFeaturesController;a&&a.abort();this._fetchFeaturesController=
null};b.prototype._fetchFeatures=function(a){var b=this,f=this.view;if(!a||!f)return a=new m("open:invalid-location-or-view","Cannot fetch content without a location and view.",{location:a,view:f}),n.error(a),k.reject(a);a="function"===typeof f.toScreen?f.toScreen(a):null;return this._fetchPopupFeatures(a).then(function(a){b.promises=a.promises})};b.prototype._fetchFeaturesAndOpen=function(a){var b=a.mapPoint,f=this.view;this._fetchPopupFeatures(a.screenPoint).then(function(a){f.popup.open({location:a.location||
b,promises:a.promises});return a})};b.prototype._updatePendingPromises=function(a){a&&this._pendingPromises.has(a)&&(this._pendingPromises.delete(a),this.notifyChange("pendingPromisesCount"))};b.prototype._setVisibleWhenContentExists=function(){var a=this,b=this._handles,f=this.promiseCount;b.remove("pendingVisible");f?(f=l.init(this,"pendingPromisesCount",function(c){a.featureCount&&(a.set("visible",!0),b.remove("pendingVisible"));c||b.remove("pendingVisible")}),b.add(f,"pendingVisible")):this.set("visible",
!0)};b.prototype._autoClose=function(){this.autoCloseEnabled&&(this.visible=!1)};b.prototype._isScreenSize=function(a){var b=this.view;if("3d"!==b.type||!a||"esri.Graphic"!==a.declaredClass)return!0;if((b=b.getViewForGraphic(a))&&"whenGraphicBounds"in b){var f=!1;b.whenGraphicBounds(a,{useViewElevation:!0}).then(function(a){f=!a||!a.boundingBox||a.boundingBox[0]===a.boundingBox[3]&&a.boundingBox[1]===a.boundingBox[4]&&a.boundingBox[2]===a.boundingBox[5]});return f}return!0};b.prototype._getPointFromGeometry=
function(a){return t.isNone(a)?null:"point"===a.type?a:"extent"===a.type?a.center:"polygon"===a.type?a.centroid:"multipoint"===a.type||"polyline"===a.type?a.extent.center:null};b.prototype._highlightFeature=function(){return y(this,void 0,void 0,function(){var a,b,f,e,d,g,p,q,k,l,m,n;return x(this,function(c){switch(c.label){case 0:return a="highlight",this._handles.remove(a),b=this,f=b.selectedFeature,e=b.highlightEnabled,d=b.view,g=b.visible,f&&d&&e&&g?(p=f.layer)?[4,d.when()]:[2]:[2];case 1:return c.sent(),
[4,d.whenLayerView(p)];case 2:q=c.sent();if(!q||!I.hasHighlight(q))return[2];k=p.objectIdField;m=(l=f.attributes)&&l[k];n=q.highlight(m||f);this._handles.add(n,a);return[2]}})})};b.prototype._updateFeatures=function(a){var b=this.features;a&&a.length&&(b.length?(a=a.filter(function(a){return-1===b.indexOf(a)}),this.features=b.concat(a)):this.features=a)};d([e.property({type:r})],b.prototype,"actions",void 0);d([e.property({dependsOn:["actions.length","selectedFeature.sourceLayer.popupTemplate.actions.length",
"selectedFeature.sourceLayer.popupTemplate.overwriteActions","selectedFeature.popupTemplate.actions.length","selectedFeature.popupTemplate.overwriteActions"],readOnly:!0})],b.prototype,"allActions",null);d([e.property({type:Boolean})],b.prototype,"defaultPopupTemplateEnabled",void 0);d([e.property()],b.prototype,"autoCloseEnabled",void 0);d([e.property()],b.prototype,"autoOpenEnabled",void 0);d([e.property()],b.prototype,"content",void 0);d([e.property({readOnly:!0,dependsOn:["features"]})],b.prototype,
"featureCount",null);d([e.property()],b.prototype,"features",null);d([e.property()],b.prototype,"highlightEnabled",void 0);d([e.property({type:z.Point})],b.prototype,"location",null);d([e.property({readOnly:!0,dependsOn:["promises"]})],b.prototype,"pendingPromisesCount",null);d([e.property({readOnly:!0,dependsOn:["featureCount","pendingPromisesCount"]})],b.prototype,"waitingForResult",null);d([e.property({readOnly:!0,dependsOn:["promises"]})],b.prototype,"promiseCount",null);d([e.property()],b.prototype,
"promises",null);d([e.property({value:null,readOnly:!0,dependsOn:["features","selectedFeatureIndex","updateLocationEnabled"]})],b.prototype,"selectedFeature",null);d([e.property({value:-1})],b.prototype,"selectedFeatureIndex",null);d([e.property({readOnly:!0,dependsOn:["view.ready"]})],b.prototype,"state",null);d([e.property()],b.prototype,"title",void 0);d([e.property()],b.prototype,"updateLocationEnabled",void 0);d([e.property()],b.prototype,"view",void 0);d([e.property()],b.prototype,"visible",
void 0);d([e.property()],b.prototype,"zoomFactor",void 0);d([e.property()],b.prototype,"centerAtLocation",null);d([e.property()],b.prototype,"zoomToLocation",null);return b=d([e.subclass("esri.widgets.Popup.PopupViewModel")],b)}(e.declared(K.GoToMixin(J)))});