// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.14/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/extendsHelper ../../../../../core/libs/gl-matrix-2/vec2f64 ../../../../../core/libs/gl-matrix-2/vec3 ../../../../../core/libs/gl-matrix-2/vec3f64 ../../../../../core/libs/gl-matrix-2/vec4 ../../../../../core/libs/gl-matrix-2/vec4f64 ../../../webgl-engine/lib/glUtil3D ../../../webgl-engine/lib/Util ../../../webgl-engine/materials/internal/MaterialUtil ../../../webgl-engine/shaders/LaserLinePrograms ../../../../webgl/renderState".split(" "),function(C,
D,E,v,c,f,r,n,w,x,t,y,p){function u(e,a,z,g){var f=q,b=A;c.vec3.transformMat4(f,a,g);c.vec3.copy(b,z);b[3]=0;r.vec4.transformMat4(b,b,g);r.vec4.set(e,b[0],b[1],b[2],-c.vec3.dot(b,f))}var q=f.vec3f64.create(),A=n.vec4f64.create(),B={glowColor:[1,.5,0],glowWidth:8,innerColor:[1,1,1],innerWidth:1,globalAlpha:.75};return function(){function e(a,c){void 0===c&&(c={});this._projInfo=n.vec4f64.create();this._zScale=v.vec2f64.create();this._segmentActive=this._focusSphereActive=this._focusPlaneActive=!1;
this._focusPosition=f.vec3f64.create();this._focusSpherePosition=f.vec3f64.create();this._segmentStartPosition=f.vec3f64.create();this._segmentEndPosition=f.vec3f64.create();this.canRender=!0;this._tempNormal=f.vec3f64.create();this._tempDir=f.vec3f64.create();this._tempUp=f.vec3f64.create();this._tempVec3=f.vec3f64.create();this._tempVec4=n.vec4f64.create();this._renderCoordsHelper=a;this._params=t.copyParameters(c,B)}Object.defineProperty(e.prototype,"renderSlots",{get:function(){return[14]},enumerable:!0,
configurable:!0});Object.defineProperty(e.prototype,"needsLinearDepth",{get:function(){return!0},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"focusPlaneActive",{get:function(){return this._focusPlaneActive},set:function(a){a!==this._focusPlaneActive&&(this._focusPlaneActive=a,this._requestRender())},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"focusSphereActive",{get:function(){return this._focusSphereActive},set:function(a){a!==this._focusSphereActive&&
(this._focusSphereActive=a,this._requestRender())},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"segmentActive",{get:function(){return this._segmentActive},set:function(a){a!==this._segmentActive&&(this._segmentActive=a,this._requestRender())},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"focusPosition",{get:function(){return this._focusPosition},set:function(a){c.vec3.copy(this._focusPosition,a);this._requestRender()},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,
"focusSpherePosition",{get:function(){return this._focusSpherePosition},set:function(a){c.vec3.copy(this._focusSpherePosition,a);this._requestRender()},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"segmentStartPosition",{get:function(){return this._segmentStartPosition},set:function(a){c.vec3.copy(this._segmentStartPosition,a);this._requestRender()},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"segmentEndPosition",{get:function(){return this._segmentEndPosition},
set:function(a){c.vec3.copy(this._segmentEndPosition,a);this._requestRender()},enumerable:!0,configurable:!0});e.prototype.setParameterValues=function(a){t.updateParameters(this._params,a)&&this._requestRender()};e.prototype.initializeRenderContext=function(a){this._initContext=a;this._quadVAO=w.createQuadVAO(a.rctx);this._laserLineProgram=a.programRep.getProgram(y.program);this._laserLinePipelineState=p.makePipelineState({blending:p.simpleBlendingParams(1,771),colorWrite:p.defaultColorWriteParams})};
e.prototype.uninitializeRenderContext=function(){this._quadVAO.dispose();this._projInfo=this._laserLineProgram=this._quadVAO=null};e.prototype.render=function(a){var e=a.rctx,g=a.camera,f=this._renderCoordsHelper,b=this._laserLineProgram,d=this._projInfo,h=this._zScale;e.bindProgram(b);e.setPipelineState(this._laserLinePipelineState);x.inverseProjectionInfo(g.projectionMatrix,g.fullWidth,g.fullHeight,d,h);b.setUniform4fv("projInfo",d);b.setUniform2fv("zScale",h);b.setUniform2f("nearFar",g.near,g.far);
b.setUniform1f("maxPixelDistance",2*g.computeScreenPixelSizeAt(this._focusPosition));if(this._focusPlaneActive){var d=this._focusPosition,h=this._tempVec3,k=this._tempVec4;f.worldUpAtPosition(d,h);u(k,d,h,g.viewMatrix);b.setUniform4fv("focusPlane",k)}else b.setUniform4fv("focusPlane",[0,0,0,1E10]);this._focusSphereActive?(h=this._tempVec4,d=this._tempVec3,c.vec3.copy(h,this._focusSpherePosition),c.vec3.transformMat4(h,h,g.viewMatrix),c.vec3.copy(d,this._focusPosition),c.vec3.transformMat4(d,d,g.viewMatrix),
h[3]=c.vec3.distance(h,d),b.setUniform4fv("focusSphere",h)):b.setUniform4fv("focusSphere",[0,0,0,1E10]);if(this._segmentActive){var d=this._tempVec4,h=this._tempVec3,k=this._tempUp,l=this._tempDir,m=this._tempNormal;c.vec3.lerp(h,this._segmentStartPosition,this._segmentEndPosition,.5);f.worldUpAtPosition(h,k);c.vec3.subtract(l,this._segmentEndPosition,this._segmentStartPosition);c.vec3.normalize(l,l);c.vec3.cross(m,k,l);c.vec3.normalize(m,m);u(d,this._segmentStartPosition,m,g.viewMatrix);b.setUniform4fv("segmentPlane",
d)}else b.setUniform4fv("segmentPlane",[0,0,0,1E10]);d=q;c.vec3.copy(d,this._segmentStartPosition);f.setAltitude(0,d);c.vec3.transformMat4(d,d,g.viewMatrix);b.setUniform3fv("segmentStart",d);d=q;c.vec3.copy(d,this._segmentEndPosition);f.setAltitude(0,d);c.vec3.transformMat4(d,d,g.viewMatrix);b.setUniform3fv("segmentEnd",d);b.setUniform1i("depthMap",0);e.bindTexture(a.offscreenRenderingHelper.linearDepthTexture,0);a=a.camera.pixelRatio;b.setUniform3fv("innerColor",this._params.innerColor);b.setUniform1f("innerWidth",
this._params.innerWidth*a);b.setUniform3fv("glowColor",this._params.glowColor);b.setUniform1f("glowWidth",this._params.glowWidth*a);b.setUniform1f("globalAlpha",this._params.globalAlpha);e.bindVAO(this._quadVAO);e.drawArrays(5,0,4);return!0};e.prototype._requestRender=function(){this._initContext&&this._initContext.requestRender()};return e}()});